### ISSUE TITLE
Autoinstalling dependencies concurrently

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#1058]
🐛 bug report

### 🤔 Expected Behavior

The workers shouldn't all automatically install dependencies at the same time.

### 😯 Current Behavior

They do.

### 🔦 Context

```
$ yarn start
yarn run v1.5.1
$ parcel src/index.html
Server running at http://localhost:1234
🚨  ...../Phaser.io-v3-Boilerplate/node_modules/phaser/src/renderer/webgl/shaders/ForwardDiffuse.frag: Failed to install glslify-bundle.
[1/4] Resolving packages...
[2/4] Fetching packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/dargs/-/dargs-5.1.0.tgz: ENOENT: no such file or directory, open '/Users/niklas/Library/Caches/Yarn/v1/npm-dargs-5.1.0-ec7ea50c78564cd36c9d5ec18f66329fade27829/.yarn-tarball.tgz'".
info If you think this is a bug, please open a bug report with the information provided in "...../Phaser.io-v3-Boilerplate/node_modules/phaser/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error An unexpected error occurred: "https://registry.yarnpkg.com/dargs/-/dargs-5.1.0.tgz: ENOENT: no such file or directory, open '/Users/niklas/Library/Caches/Yarn/v1/npm-dargs-5.1.0-ec7ea50c78564cd36c9d5ec18f66329fade27829/.yarn-tarball.tgz'".
info If you think this is a bug, please open a bug report with the information provided in "...../Phaser.io-v3-Boilerplate/node_modules/phaser/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    at PromiseQueue.install [as process] (...../parcel2/src/utils/installPackage.js:41:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

```sh
$ ps
  PID TTY           TIME CMD
31374 ttys000    0:00.96 -bash
33028 ttys000    0:00.75 node /usr/local/Cellar/yarn/1.5.1_1/libexec/bin/yarn.js start
33029 ttys000    0:10.91 node /usr/local/bin/parcel src/index.html
33057 ttys000    0:11.55 /usr/local/Cellar/node/9.9.0/bin/node ...../parcel2/node_modules/worker-farm/lib/child/index.js /usr/l
33058 ttys000    0:10.80 /usr/local/Cellar/node/9.9.0/bin/node ...../parcel2/node_modules/worker-farm/lib/child/index.js /usr/l
33424 ttys000    0:01.89 node /usr/local/Cellar/yarn/1.5.1_1/libexec/bin/yarn.js add glslify-bundle -D
33426 ttys000    0:01.91 node /usr/local/Cellar/yarn/1.5.1_1/libexec/bin/yarn.js add glslify-bundle -D
32328 ttys001    0:00.74 -bash
```
### 💻 Code Sample

https://github.com/22mahmoud/Phaser.io-v3-Boilerplate (at dfaab01b4f94b4ada8da0892bc02ab527aa9cc17)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | master
| Node             | 9.9.0
| npm/Yarn         | 1.5.2
| Operating System | macOS 10.12.6

**Comment by davidnagli** [comment]
That’s strange.... the PromiseQue should take care of scheduling them such that they only run one at a time. 

I’ll take a deeper look into the shortly. 

@devongovett Maybe you know what’s causing this?

**Comment by DeMoorJasper** [comment]
@davidnagli Isn’t this due to the multiple workers? If each workers triggers an install especially if it’s the same package they’ll conflict

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by davidnagli** [comment]
@DeMoorJasper We implemented a queue within AutoInstall with is supposed to handle exactly this.

https://github.com/parcel-bundler/parcel/blob/fc041d03c36bf41ea73c398e8d177de1a456e796/src/utils/installPackage.js#L102-L106

**Comment by DeMoorJasper** [comment]
@davidnagli This won't prevent it will it? The queue is created per process/worker right?
