### ISSUE TITLE
🙋 Add support WASM support for Node targets

### ISSUE THREAD

**Issue by davidnagli** [parcel-bundler/parcel#1070]
🙋 Feature Request

Currently if you run Parcel on a project that uses WASM (I tried it on Rust), the output uses `fetch()` to get the `.wasm` file. We should detect if `target` is `'node'`, and use `fs` instead of `fetch`.

As far as I understood WASM is already supported in Node 8 and Node 9.

Running the way it is, I get the following error:
```
$ node dist/index.js
/Users/davidnagli/Desktop/coding/playground/parcel-rust-test/dist/index.js:8
module.exports=function(t){return fetch(t).then(function(t){return WebAssembly.instantiateStreaming?WebAssembly.instantiateStreaming(t):t.arrayBuffer().then(function(t){return WebAssembly.instantiate(t)})}).then(function(t){return t.instance.exports})};
                           ^

ReferenceError: fetch is not defined
    at module.exports (/Users/davidnagli/Desktop/coding/playground/parcel-rust-test/dist/index.js:8:28)
    at u (/Users/davidnagli/Desktop/coding/playground/parcel-rust-test/dist/index.js:6:610)
    at Array.map (<anonymous>)
    at Function.t [as load] (/Users/davidnagli/Desktop/coding/playground/parcel-rust-test/dist/index.js:6:303)
    at Object.require.0 (/Users/davidnagli/Desktop/coding/playground/parcel-rust-test/dist/index.js:10:50)
    at t (/Users/davidnagli/Desktop/coding/playground/parcel-rust-test/dist/index.js:1:408)
    at /Users/davidnagli/Desktop/coding/playground/parcel-rust-test/dist/index.js:1:646
    at Object.<anonymous> (/Users/davidnagli/Desktop/coding/playground/parcel-rust-test/dist/index.js:1:663)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
```

[Repo to Reproduce](https://github.com/davidnagli/parcel-rust-test)

Here's where that `fetch()` comes from:
https://github.com/parcel-bundler/parcel/blob/fc041d03c36bf41ea73c398e8d177de1a456e796/src/builtins/loaders/wasm-loader.js#L1-L16

**Comment by fathyb** [comment]
#981 fixes it

**Comment by davidnagli** [comment]
Oh cool 👍 😃
