### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by mgnath65** [parcel-bundler/parcel#1077]
Parcel never worked for me. What is this error?

🚨  Cannot find module 'tslib'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (/mnt/c/Users/Tyler/Documents/code/parcelapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/mnt/c/Users/Tyler/Documents/code/parcelapp/node_modules/parcel-plugin-pug/build/PugAsset.js:2:17)
    at Module._compile (/mnt/c/Users/Tyler/Documents/code/parcelapp/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

**Comment by fathyb** [comment]
Are you using `importHelpers: true` in your `tsconfig.json`?

**Comment by mgnath65** [comment]
No.

I've these packages installed: node-sass, autoprefixer, parcel-bundler, and parcel-plugin-pug. And my entry point is an index.pug file inside "src/pug/" folder with relative links to .scss and .js files. The command I used is parcel src/pug/index.pug --open. I've a .postcssrc file and package.json. That's all. I don't understand why I'm getting this error.

**Comment by fathyb** [comment]
Ah, it's a `parcel-plugin-pug` issue. See Ty3uK/parcel-plugin-pug#17.

Installing `tslib` should fix the issue as a workaround.

**Comment by mgnath65** [comment]
Yea, it worked. Thank you!
