### ISSUE TITLE
Better failover for EADDRINUSE

### ISSUE THREAD

**Issue by davidnagli** [parcel-bundler/parcel#111]
🙋 feature request

I’ve noticed people complaining about this issue before, and I’ve encountered it accidentally several times. If you already have something else using `:1234` (like another process running parcel) you get a pretty nasty error message.

```
⏳  Building...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1234
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Object.serve (/Users/davidnagli/.config/yarn/global/node_modules/parcel-bundler/src/Server.js:50:49)
    at Bundler.serve (/Users/davidnagli/.config/yarn/global/node_modules/parcel-bundler/src/Bundler.js:421:19)
    at Command.bundle (/Users/davidnagli/.config/yarn/global/node_modules/parcel-bundler/bin/cli.js:67:13)
    at Command.listener (/Users/davidnagli/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
```
For people who use Node all the time, this error is pretty familiar, but for someone others it can be pretty confusing.

Can we just wrap a simple try/catch or check for `err` in the callback or whatever it is, so that we display a more readable message to the user?

Maybe we can even automatically choose a different port…

**Comment by Raathigesh** [comment]
I'll take this. May be tonight or tomorrow.

**Comment by devongovett** [comment]
moving to #164
