### ISSUE TITLE
Unknown version 6.2 of samsung

### ISSUE THREAD

**Issue by rodney757** [parcel-bundler/parcel#1144]
**Choose one:** this is a 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

`parcel src/app/app.js`

```js
{
  "presets": ["env"],
  "plugins": ["transform-class-properties", "angularjs-annotate"]
}
```

### 🤔 Expected Behavior

compile project files

### 😯 Current Behavior
```
/Users/rjewing/code/biocode/rjewbiscicol-ui/src/app/app.js: Unknown version 6.2 of samsung
    at Function.select (/Users/rjewing/code/biocode/biscicol-ui/node_modules/babel-preset-env/node_modules/browserslist/index.js:769:17)
    at /Users/rjewing/code/biocode/biscicol-ui/node_modules/babel-preset-env/node_modules/browserslist/index.js:181:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/rjewing/code/biocode/biscicol-ui/node_modules/babel-preset-env/node_modules/browserslist/index.js:162:18)
    at browserslist (/Users/rjewing/code/biocode/biscicol-ui/node_modules/babel-preset-env/node_modules/browserslist/index.js:272:16)
    at getTargets (/Users/rjewing/code/biocode/biscicol-ui/node_modules/babel-preset-env/lib/targets-parser.js:103:63)
    at Object.buildPreset [as default] (/Users/rjewing/code/biocode/biscicol-ui/node_modules/babel-preset-env/lib/index.js:144:45)
    at getEnvPlugins (/Users/rjewing/code/biocode/biscicol-ui/node_modules/parcel-bundler/src/transforms/babel.js:252:34)
    at getEnvConfig (/Users/rjewing/code/biocode/biscicol-ui/node_modules/parcel-bundler/src/transforms/babel.js:219:25)
    at <anonymous>
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.7.0
| Node             |  8.9.4
| npm/Yarn         | 1.5.1
| Operating System | osx 10.13.3

**Comment by DeMoorJasper** [comment]
Appears to be a browserlist issue, have you defined this samsung v6.2 anywhere?

**Comment by rodney757** [comment]
I haven't defined it anywhere

**Comment by starkwang** [comment]
@rodney757 I've meet this error before. This is because your local `caniuse-lite` (`browserlist` depends on it) is too old. Try `npm i caniuse-lite`.

**Comment by rodney757** [comment]
unfortunately that didn't help

**Comment by chay22** [comment]
This probably similar. https://github.com/parcel-bundler/parcel/issues/1036

I've tried all suggestions appear there and here, also tried to add `not android 6.2`,  it still persists after upgrading to `1.7.0`, too.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 8.9.3
| npm/Yarn         | 1.5.1
| Operating System | Windows 8

**Comment by guayom** [comment]
I have the same issue. I started ignoring browsers in my browserlist, but everytime I ignore a version, a new error pops up, claiming that it doesn't recognize some other browser. It looks like a never-ending task.

**Comment by eliask** [comment]
Similar issue after upgrading to 1.7.x
🚨 src/index.js: Unknown version 11.3 of ios_saf

**Comment by eliask** [comment]
I get a similar issue when upgrading from 1.6.2 to 1.7.1:
🚨  src/index.js: Unknown version 11.3 of ios_saf

**Comment by kennedyrose** [comment]
I've got "Unknown version 11.3 of ios_saf" as well

**Comment by DeMoorJasper** [comment]
Track progress here: #1036
