### ISSUE TITLE
scss file not compiled in build mode

### ISSUE THREAD

**Issue by barriber** [parcel-bundler/parcel#1210]
🐛 bug report 
build fails when scss file is imported, dev mode works fine

### 🎛 Configuration (.babelrc, package.json, cli command)

babel:
{
    "presets": ["env", "react"]
}

package.json
 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "devserver": "parcel index.html",
    "build": "parcel build index.html"
  },
### 😯 Current Behavior

When running "parcel build index.html" build fails with the following expectation:

app.scss:undefined:undefined: stringify is not a function
    at ValueParser.toString (C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss-value-parser\lib\index.js:14:40)
    at C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss-convert-values\dist\index.js:87:12
    at C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:188:28
    at C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:144:26
    at Rule.each (C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:110:22)
    at Rule.walk (C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:143:21)
    at C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:146:32
    at Root.each (C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:110:22)
    at Root.walk (C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:143:21)
    at Root.walkDecls (C:\Users\Me\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\postcss\lib\container.js:186:25)

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 8.1.2
| npm| 5.3.0
| Operating System | Windows

**Comment by mischnic** [comment]
If this is still an issue, please post a code sample to reproduce this.
