### ISSUE TITLE
Getting 'Cannot read property 'css' of null' when the imported scss file is empty

### ISSUE THREAD

**Issue by vargabalazs** [parcel-bundler/parcel#1267]
**Choose one:** is this a 🐛
Getting 'Cannot read property 'css' of null' when imported scss file is empty.

### 🎛 Configuration (.babelrc, package.json, cli command)
package.json:
```js
{
  "name": "angular-cli-sandbox",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.7.1",
    "parcel-plugin-angular": "^0.5.0",
    "parcel-plugin-inlinesvg": "^1.0.0",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```
### 🤔 Expected Behavior

The build process should complete without any error.

### 😯 Current Behavior
Build fails with the following error:
```js
 C:\workspace\angular-cli-sandbox\src\app\app.component.ts: Cannot read property 'css' of null
    at SASSAsset.generate (C:\workspace\angular-cli-sandbox\node_modules\parcel-bundler\src\assets\SASSAsset.js:51:25)
    at SASSAsset.process (C:\workspace\angular-cli-sandbox\node_modules\parcel-bundler\src\Asset.js:157:35)
    at <anonymous>
```
### 💁 Possible Solution

Skip, empty scss files.

### 🔦 Context

I create new empty Angular-CLI project, and integrate it Parcel bundler.

### 💻 Code Sample
```js

import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'app';
}
```
[project.zip](https://github.com/parcel-bundler/parcel/files/1960781/project.zip)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 8.9.4
| npm             | 5.8.0
| Operating System | Win 10 v1709, build: 16299.371

**Comment by DeMoorJasper** [comment]
Already fixed in master branch
