### ISSUE TITLE
 Cannot read property 'env' of undefined

### ISSUE THREAD

**Issue by pke** [parcel-bundler/parcel#1277]
this a 🐛 bug report 

Parcel produced an error but builds the packages just fine.

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [["env", "react"]],
  "plugins": [
    ["transform-class-properties"],
    ["transform-object-rest-spread", {
      "useBuiltIns": true
    }],
    ["module-resolver", {
      "root": ["./src"]
    }],
    ["transform-class-properties"],
    ["syntax-dynamic-import"],
    ["styled-jsx/babel"]
  ],
  "env": {
    "test": {
      "plugins": ["istanbul"]
    }
  }
}
```

### 😯 Current Behavior

```cli
> parcel --no-cache ./src/index.html

Server running at http://localhost:1234
∞  Building...

‼  Cannot read property 'env' of undefined
    at Object.init (C:\dev\projects\product-frontend\node_modules\parcel-bundler\src\worker.js:10:38)
    at WorkerFarm.init (C:\dev\projects\product-frontend\node_modules\parcel-bundler\src\workerfarm\WorkerFarm.js:179:22)
    at new WorkerFarm (C:\dev\projects\product-frontend\node_modules\parcel-bundler\src\workerfarm\WorkerFarm.js:32:10)
    at Function.getShared (C:\dev\projects\product-frontend\node_modules\parcel-bundler\src\workerfarm\WorkerFarm.js:261:16)
    at Object.addCall (C:\dev\projects\product-frontend\node_modules\parcel-bundler\src\worker.js:33:23)
    at localRequire (C:\dev\projects\product-frontend\node_modules\parcel-bundler\src\utils\localRequire.js:16:22)
    at Bundler.loadPlugins (C:\dev\projects\product-frontend\node_modules\parcel-bundler\src\Bundler.js:165:30)
    at <anonymous>
∞  Building index.html...
∞  Building index.js...
∞  Building style.scss...

```

### 🔦 Context

This happens when calling
`parcel --no-cache ./src/index.html`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 9.9.0
| npm        | 5.6.0
| Operating System | Win  8.1

**Comment by bencooper222** [comment]
any progress in figuring it out @pke ? Getting a similar error when running on Netlify but not in WSL.

**Comment by bencooper222** [comment]
Regardless, here's my environment:

Parcel: 1.81
Node: 8.9.4
yarn: 1.5.1
OS: Netlify??

**Comment by DeMoorJasper** [comment]
Please try #1387 as I couldn't reproduce and just tried something that should normally fix this

**Comment by bencooper222** [comment]
Not sure if you're familiar with Netlify but I'm having trouble reproducing it there. The contents in this PR (https://github.com/bencooper222/benc.io/pull/19) work locally (note the npm script `prod`) but fail in Netlify's cloud. Is there anyway I could install Parcel from git and use it as a dependency without having to run `yarn build`?

**Comment by DeMoorJasper** [comment]
I’ve only usef netlify a couple times i’m no expert at it. To me it looks like it should work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by QAQLiuCong** [comment]
> parcel build index.html --public-url ./ --no-source-maps

√  Built in 12.43s.
‼  Cannot read property 'env' of undefined
    at Object.init (f:\VueProject\node_modules\parcel-bundler\src\worker.js:10:38)
    at WorkerFarm.init (f:\VueProject\node_modules\parcel-bundler\src\workerfarm\WorkerFarm.js:208:22)
    at new WorkerFarm (f:\VueProject\node_modules\parcel-bundler\src\workerfarm\WorkerFarm.js:30:10)
    at Function.getShared (f:\VueProject\node_modules\parcel-bundler\src\workerfarm\WorkerFarm.js:258:16)
    at Object.addCall (f:\VueProject\node_modules\parcel-bundler\src\worker.js:33:23)
    at localRequire (f:\VueProject\node_modules\parcel-bundler\src\utils\localRequire.js:16:22)
    at Bundler.loadPlugins (f:\VueProject\node_modules\parcel-bundler\src\Bundler.js:192:30)


Parcel: 1.81
Node: 10.2.0
npm: 6.1.0
OS: win10

package.json
{
  "name": "vueproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "parcel index.html",
    "build": "parcel build index.html --public-url ./ --no-source-maps"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.0"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^1.3.1",
    "autoprefixer": "^8.6.1",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-vue": "^2.0.2",
    "cssnano": "^3.10.0",
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.8.1",
    "parcel-plugin-imagemin": "^1.1.1",
    "postcss-modules": "^1.1.0",
    "precss": "^3.1.2",
    "vue-template-compiler": "^2.5.16"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8",
    "iOS >= 7",
    "Android > 4.1"
  ]
}

**Comment by HybridKat** [comment]
I had the same problem, managed to find how to fix it in my case.  Seems like it does not like it when the entry file given in the command line and not at the root.  So instead, I changed the "main" from my package.json and didn't pass the entry.  No more env errors.

**Before**
parcel --no-cache ./src/index.html

**After**
parcel --no-cache
(In package.json) "main": "src/index.html",

Hoping it helps :)

**Comment by Jimexist** [comment]
@pke see #1671

**Comment by OttoTrezza** [comment]
### THE ERROR [nodemon] restarting due to changes...
[nodemon] starting `node app.js`
D:\proyecto\Adminpro-Angular\backend-server\middlewares\autenticacion.js:3
var SEED = require('../config/config').process.env.SEED;
                                              ^

TypeError: Cannot read property 'env' of undefined
    at Object.<anonymous> (D:\proyecto\Adminpro-Angular\backend-server\middlewares\autenticacion.js:3:47)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\proyecto\Adminpro-Angular\backend-server\routes\usuario.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
[nodemon] app crashed - waiting for file changes before starting...

 ### config.ts...

// ============================
// Puerto
// ============================
process.env.PORT = process.env.PORT || 3000;


// ============================
// Entorno
// ============================

process.env.NODE_ENV = process.env.NODE_ENV || 'dev';

// ============================
// vENCIMIENTO DEL TOKEN
// ============================
// 60 segundos
// 60 minutos
// 24 horas 
// 30 dias
process.env.CADUCIDAD_TOKEN = '48h';
// ///
SEED = 'eo';
GOOGLE_CLIENT_ID = '57-vc.apps.googleusercontent.com';
GOOGLE_SECRET = 'be';

SERVER_PORT = 3000;
// ///
// ============================
// SEED de autenticacion
// ============================
process.env.SEED = process.env.SEED || 'eo';

// ============================
// Base de datos
// ============================

let urlDB;
if (process.env.NODE_ENV === 'dev') {

    urlDB = 'mongodb://localhost:27017/tt';
} else {
    urlDB = 'mongodb+srv://Mn:39@cluster0-q.mongodb.net/tt?retryWrites=true&w=majority';
}

process.env.URLDB = urlDB;

// ============================
// Google CLIENT_ID
// ============================

process.env.CLIENT_ID = process.env.CLIENT_ID || '7-sk.apps.googleusercontent.com';

### app.js


//Coneccion a la base de datos
mongoose.set('useCreateIndex', true);
mongoose.connect(process.env.URLDB, { useNewUrlParser: true }, (err, res) => {
    if (err) throw err;
    console.log('Base de datos:\x1b[32m%s\x1b[0m', 'online');
});
// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// //// ESTO ES PARA VER LA CARPETA UPLOADS DEL FILESYSTEM DIRECTAMENTE EN EL NAVEGADOR SOLO CON: HTTP:LOCALHOST3000/UPLOADS/
// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Server index config
// var serveIndex = require('serve-index');
// app.use(express.static(__dirname + '/'));
// app.use('/uploads', serveIndex(__dirname + '/uploads'));


server.start(() => { // Me quedo escuchando el puerto 80!
    console.log(`Servidor corriendo en el puerto ${ server.port }`);
