### ISSUE TITLE
🐛 Parcel cannot require 'when' module

### ISSUE THREAD

**Issue by joelnordell** [parcel-bundler/parcel#1283]
### 🎛 Configuration (.babelrc, package.json, cli command)

Parcel fails to properly bundle the `when` package. I think this might be related to #959 but maybe this is more of an edge case.

### Steps to reproduce

```
## Clone the below referenced gist
$ npm install
$ npm run build
$ node dist/index.js
```

### 🤔 Expected Behavior

The `index.js` should successfully require `when` without errors, and you should therefore see "Hello, world" printed to the console.

### 😯 Current Behavior

```
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module './lib/decorators/timed'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at newRequire (/tmp/parcel-test/dist/index.js:36:18)
    at localRequire (/tmp/parcel-test/dist/index.js:54:14)
    at /tmp/parcel-test/dist/index.js:113:14
    at /tmp/parcel-test/dist/index.js:329:96
    at /tmp/parcel-test/dist/index.js:111:1
    at Object.parcelRequire.3 (/tmp/parcel-test/dist/index.js:329:3)
```

### 💁 Possible Solution

`when` appears to be a UMD module. I don't know enough about UMDs to suggest a solution at this point, but might do some more digging into it later. This might be related to #959 -- maybe @davidnagli, @markandrus, or @fathyb has an idea?

### 💻 Code Sample

https://gist.github.com/joelnordell/c98962f2dd54f21cf5fd854be764ebbf

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.0 |
| Node             | 9.11.1 |
| npm/Yarn         | npm 5.6.0 |
| Operating System | Ubuntu 16.04 |

**Comment by joelnordell** [comment]
I can confirm that #1284 fixes this issue in my application. Thanks @fathyb!
