### ISSUE TITLE
Unable to build Font Awesome 4: property "var" must be followed by a ':'

### ISSUE THREAD

**Issue by marcelkorpel** [parcel-bundler/parcel#1298]
This is a 🐛 bug report.

Since Parcel 1.8.0 I am unable to build Font Awesome 4.

### 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```js
{
  "name": "backend",
  "version": "1.0.0",
  "description": "",
  "main": "",
  "scripts": {
    "start": "parcel watch -d ../dist --public-url /dist index.html",
    "build": "NODE_ENV=production parcel build -d ../dist --public-url /dist --no-minify --no-source-maps index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "compass-mixins": "^0.12.10",
    "font-awesome": "^4.7.0",
    "prosemirror-commands": "^1.0.7",
    "prosemirror-dropcursor": "^1.0.0",
    "prosemirror-gapcursor": "^1.0.2",
    "prosemirror-history": "^1.0.2",
    "prosemirror-inputrules": "^1.0.1",
    "prosemirror-keymap": "^1.0.1",
    "prosemirror-menu": "^1.0.4",
    "prosemirror-model": "^1.4.0",
    "prosemirror-schema-list": "^1.0.1",
    "prosemirror-state": "^1.2.0",
    "prosemirror-view": "^1.2.0",
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^1.0.0",
    "babel-core": "^6.26.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "css-loader": "^0.28.11",
    "node-sass": "^4.7.2",
    "typescript": "^2.7.2",
    "vue-template-compiler": "^2.5.16"
  }
}
```
.babelrc:
```js
{
  "presets": ["env"]
}
```
### 🤔 Expected Behavior
When building with Parcel 1.7.1, a correct build appears:
```
✨  Built in 503ms.

../dist/src.39f234a3.js                                 804.04 KB    568ms
../dist/fontawesome-webfont.a9acc805.svg                433.96 KB     29ms
../dist/fontawesome-webfont.4a2277d0.eot                161.86 KB     31ms
../dist/fontawesome-webfont.152c194f.ttf                161.67 KB     30ms
../dist/fontawesome-webfont.4e039e70.woff                95.73 KB     30ms
../dist/fontawesome-webfont.9fb3877d.woff2               75.35 KB     30ms
[…]
../dist/styles.73c54c61.css                              39.52 KB    308ms
../dist/src.bb4aab41.css                                 11.85 KB     57ms
../dist/index.html                                          371 B     18ms
Done in 1.04s.
```
### 😯 Current Behavior
Both the `watch` as well as the `build` option give the following error:
```
/srv/http/symfony/public/backend-www/stylesheets/styles.scss: property "var" must be followed by a ':'
    at options.error (/srv/http/symfony/public/backend-www/node_modules/node-sass/lib/index.js:291:26)
    at Function.module.exports.loopWhile (/usr/lib/node_modules/parcel-bundler/node_modules/deasync/index.js:72:22)
    at syncPromise (/usr/lib/node_modules/parcel-bundler/src/utils/syncPromise.js:22:11)
    at Object.opts.importer (/usr/lib/node_modules/parcel-bundler/src/assets/SASSAsset.js:47:20)
    at options.importer (/srv/http/symfony/public/backend-www/node_modules/node-sass/lib/index.js:336:31)
```

### 🔦 Context

I'm trying to use Font Awesome 4.

### 💻 Code Sample

The issue apears when including 
```css
@import "../node_modules/font-awesome/scss/font-awesome";
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | 9.11.1
| Yarn         | 1.6.0 |
| Operating System | Arch Linux |

**Comment by mjgerace** [comment]
Can confirm this is a bug as well. Works on other bundlers just fine.

**Comment by DeMoorJasper** [comment]
Would be nice to actually have the line where this error is thrown, so we don't have to dig into fontawesome for debugging this.

**Comment by devongovett** [comment]
Sounds like it's fixed?

**Comment by marcelkorpel** [comment]
Indeed.
