### ISSUE TITLE
🐛 npm install on window yields error MSB3411: Could not load the Visual C++ component "VCBuild.exe"

### ISSUE THREAD

**Issue by jtenner** [parcel-bundler/parcel#1338]
# 🐛 bug report

This error occurs when you haven't installed `windows-build-tools`, but I actually checked and tried installing `buffer-util` and it worked just fine. One of the submodules is specified in the error message: `deasync`.

## 🤔 Expected Behavior

Parcel should install normally.

## 😯 Current Behavior

npm install currently yields this message:

```
S C:\projectFolder > npm install --save-dev parcel-bundler

> deasync@0.1.12 install C:\projectFolder\node_modules\deasync
> node ./build.js


C:\projectFolder\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
C:\projectFolder\node_modules\deasync\build\binding.sln : error MSB3411: Could not load the Visual C++ com
ponent "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET
Framework 3.5, or 2) install Microsoft Visual Studio 2008.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projectFolder\node_modules\deasync
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed
npm WARN lang-maker@1.0.0 No description
npm WARN lang-maker@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jtenner\AppData\Roaming\npm-cache\_logs\2018-05-09T18_53_52_824Z-debug.log
```
Upon further investigation the `verbose` stack trace for building `deasync` shows this error.

```
2700 verbose stack Error: deasync@0.1.12 install: `node ./build.js`
2700 verbose stack Exit status 1
2700 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
2700 verbose stack     at EventEmitter.emit (events.js:182:13)
2700 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2700 verbose stack     at ChildProcess.emit (events.js:182:13)
2700 verbose stack     at maybeClose (internal/child_process.js:957:16)
2700 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
2701 verbose pkgid deasync@0.1.12
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | 10.1.0 |
| npm/Yarn         | 5.6.0 |
| Operating System | windows 10 |

**Comment by DeMoorJasper** [comment]
This is an issue with deasync, it's reported to their repo.
The node 10 binaries aren't added to their package yet.

**Comment by jtenner** [comment]
AH that makes perfect sense! I should really be more careful about upgrading node versions.

I guess the fix for now is to avoid using `node 10` for a while, huh?

Thanks for the quick reply.

**Comment by DeMoorJasper** [comment]
I'll do a PR to the binaries repo of deasync in a bit.

You can install all the tools required to build the C++ code or just use node 9 instead

**Comment by jtenner** [comment]
I think I'll just wait. I can do all my library development without the need for parcel just yet. Thank you so much.
