### ISSUE TITLE
Cannot resolve dependency when using parcel-plugin-inlinesvg

### ISSUE THREAD

**Issue by natew** [parcel-bundler/parcel#1418]
# 🐛 bug report

Works without, doesn't work with.

## 🎛 Configuration (.babelrc, package.json, cli command)

babel-preset-env

## 😯 Current Behavior

```
🚨  /Users/nw/projects/motion/orbit/apps/site/src/views/icons.js: Cannot resolve dependency '../public/slack.svg' at '/Users/nw/projects/motion/orbit/apps/site/src/public/slack.svg'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (/Users/nw/n/lib/node_modules/parcel/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/nw/projects/motion/orbit/apps/site/node_modules/parcel-plugin-inlinesvg/lib/asset.js:1:81)
    at Module._compile (/Users/nw/n/lib/node_modules/parcel/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

## 🔦 Context

This is working in 1.6!

The icon is a really simple svg (tried making it just a line). And I tried doing a relative and absolute path import. 

For some reason the error seems incorrect. It's being required from a different folder like so:

```
/views
   someview.js  // require('../public/slack.svg')
/public
   slack.svg
```

But the error seems to indicate it's trying to resolve `../public/slack.svg` *from inside of* `/public`, which would be incorrect.

Taking out the inline-svg code makes it work just fine.

Using:

```
"parcel-plugin-inlinesvg": "^0.0.14",
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 9
| Operating System | High Sierra

**Comment by shulamyt** [comment]
I had the same problem and after debug I found that it failed because lib/asset.js require missing dependency 'parcel-bundler'.
