### ISSUE TITLE
Parcel doesn't always generate index.html files in sub-directories

### ISSUE THREAD

**Issue by Kerrick** [parcel-bundler/parcel#1420]
# 🐛 bug report

When using Parcel to build and/or serve a website made of static HTML files, linking to directories doesn't work as expected. Example:

```html
<a href="about/">About</a>
```

## 🎛 Configuration (.babelrc, package.json, cli command)

N/A - bug is visible without any configuration files.

## 🤔 Expected Behavior

It should generate `dist/about/index.html`, and clicking the "About" link should go to `http://localhost:1234/about/` -- which should serve the content from `about/index.html`.

## 😯 Current Behavior

It does not generate `dist/about/index.html`, and clicking the "About" link goes to `http://localhost:1234/about/` -- but it serves the content from `index.html`.

## 💁 Possible Solution

Generate `index.html` files found in a directory, and serve their content when visiting that directory URL directly.

## 🔦 Context

I came upon this bug when trying to make a simple marketing website: primarily HTML and CSS, very little JS, and not a single-page applicatino.

## 💻 Code Sample

https://github.com/Kerrick/parcel-problems

Simply run `parcel serve index.html` and click the links to see the inconsistent behavior.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | v10.1.0
| npm/Yarn         | yarn 1.5.1
| Operating System | macOS 10.13.4

**Comment by DeMoorJasper** [comment]
This is because parcel detects this syntax as front-end routing or a custom back-end route instead of a html file if I'm not mistaken

**Comment by Kerrick** [comment]
> not that hard to add index.html to the href property

It isn't hard to add, but it has negative side effects: the browser bar shows an ugly URL (`example.com/about/index.html`) instead of the desired pretty URL (`example.com/about/`). I wouldn't mind _writing_ `index.html` in the `href` if the final output omitted it.

**Comment by DeMoorJasper** [comment]
Intresting, I'll change this to RFC/Feature

**Comment by awendt** [comment]
I ran into the same problem. I found this: https://github.com/parcel-bundler/parcel/blob/060db2e2c56f08e223e9a9075035f0998e249763/packages/core/parcel-bundler/src/Resolver.js#L252-L253 and while it sounds very similar it doesn't seem to apply to this problem.

My current work-around is to:

```
$ parcel build index.html subdir/index.html
```

and have parcel ignore `<a href="./subdir">Go to subdir</a>` in the top-level HTML file but I'd like parcel to figure this out on its own and just specify one target.

**Comment by jediyozh** [comment]
I have a same problem...any updated?

**Comment by kilianplapp** [comment]
Same problem

**Comment by folknor** [comment]
I'd also like this to be "fixed". I want users to see nice and tidy URLs like `domain.com/about/`.

**Comment by folknor** [comment]
@DeMoorJasper Perhaps add "Parcel 2" and "Static" tags to this issue, and any other relevant ones.

**Comment by folknor** [comment]
Apologies, I didn't mean to spam 3 comments in a row, but one solution I tried was to add separate subfolders to the build command, like `parcel build index.html about/index.html`, but that generates this error:
```
> parcel build index.html about/index.html

🚨 Build failed.

Error: Bundles must have unique names

AssertionError [ERR_ASSERTION]: Bundles must have unique names
at BundlerRunner.nameBundles (/.../node_modules/.pnpm/@parcel+core@2.0.0-nightly.1029/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:343:23)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async BundlerRunner.bundle (/.../node_modules/.pnpm/@parcel+core@2.0.0-nightly.1029/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:286:5)
at async RequestTracker.runRequest (/.../node_modules/.pnpm/@parcel+core@2.0.0-nightly.1029/node_modules/@parcel/core/lib/RequestTracker.js:725:20)
at async Object.run (/.../node_modules/.pnpm/@parcel+core@2.0.0-nightly.1029/node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:62:7)
at async RequestTracker.runRequest (/.../node_modules/.pnpm/@parcel+core@2.0.0-nightly.1029/node_modules/@parcel/core/lib/RequestTracker.js:725:20)
at async Parcel._build (/.../node_modules/.pnpm/@parcel+core@2.0.0-nightly.1029/node_modules/@parcel/core/lib/Parcel.js:397:11)
at async Parcel.run (/.../node_modules/.pnpm/@parcel+core@2.0.0-nightly.1029/node_modules/@parcel/core/lib/Parcel.js:276:18)
at async run (/.../node_modules/.pnpm/parcel@2.0.0-nightly.1029/node_modules/parcel/lib/cli.js:374:7)

```

**Comment by Duckers** [comment]
Observed same behavior, parcel `2.6.0`

Upgraded to parcel `2.8.3` and the problem went away

**Comment by pkgw** [comment]
The discussion in #1186 addresses this issue, from a certain perspective. I was able to use the [parcel-resolver-ignore] module to get my use case working as described in that issue, although it's not a pretty solution (IMO).

[parcel-resolver-ignore]: https://www.npmjs.com/package/parcel-resolver-ignore

**Comment by redrockzee** [comment]
I have a simple work-around that forces Parcel to build the subdirectories while retaining nice URLs ending in /.

Keep your link as-is.
`<a href="about/">About</a>`

Then at the bottom of the body, add this line to force Parcel to build the referenced subdirectory.
`  <a href="about/index.html" style="display:none">Not displayed</a>`

or, if your file is in a subdirectory of the project, /src in my case...
`  <a href="/src/about/index.html" style="display:none">Not displayed</a>`

**Comment by macx** [comment]
> I have a simple work-around

This causes new problems. You are using inline-styles and links with `display: none`, which Google hates.
