### ISSUE TITLE
After install, I execute the command: `parcel`, it report error to me.

### ISSUE THREAD

**Issue by kybetter** [parcel-bundler/parcel#1434]
# 🐛 bug report

After install, I execute the command: `parcel`, it report error to me.

## 🎛 Configuration (.babelrc, package.json, cli command)

**no configuration**

## 😯 Current Behavior

```
/Users/xxx/parcel-test/index.js: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/    
at /Users/xxx/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/xxx/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/xxx/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/xxx/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/xxx/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/xxx/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.getParserOptions (/Users/xxx/.config/yarn/global/node_modules/parcel-bundler/src/assets/JSAsset.js:72:20)
```

## 💁 Possible Solution

I try to use npm to install, but it has error too.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | v10.1.0
| npm/Yarn         | 5.6.0/1.6.0
| Operating System | MacOS

**Comment by fathyb** [comment]
It looks like Parcel is installed globally on your system, does it works if you install it locally?

**Comment by kybetter** [comment]
I follow the `Getting started` guide, and use the command: `yarn global add parcel-bundler`.
Am I wrong? It shouldn't installed globally on my system?

**Comment by fathyb** [comment]
Yup, but I'm trying to see if global is causing the problem. Could you try it please?

**Comment by kybetter** [comment]
I install it locally and execute, it seems report the same error too.
command: `./node_modules/parcel-bundler/bin/cli.js`
errors:
```
Server running at http://localhost:1234
/Users/xxx/parcel-test/index.js: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/
```
Is my system environment is not fit parcel?

**Comment by kybetter** [comment]
now, I know how to use parcel. You should update your document, otherwise I got errors if I didn't generate a `.babelrc` and config babel. Thank You.

**Comment by DeMoorJasper** [comment]
This sounds resolved, gonna close it
