### ISSUE TITLE
Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

### ISSUE THREAD

**Issue by Maneeshashokan** [parcel-bundler/parcel#1459]
bundling failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/home/maneesh/source/IPS-React/node_modules/@babel/preset-env/lib/index.js")
    at throwVersionError (/home/maneesh/source/IPS-React/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/home/maneesh/source/IPS-React/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/home/maneesh/source/IPS-React/node_modules/@babel/preset-env/lib/index.js:150:7)
    at /home/maneesh/source/IPS-React/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /home/maneesh/source/IPS-React/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/maneesh/source/IPS-React/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/maneesh/source/IPS-React/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/maneesh/source/IPS-React/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/maneesh/source/IPS-React/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/maneesh/source/IPS-React/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/maneesh/source/IPS-React/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/maneesh/source/IPS-React/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.transform (/home/maneesh/source/IPS-React/node_modules/metro/src/transformer.js:135:5)
    at Object.transformCode [as transform] (/home/maneesh/source/IPS-React/node_modules/metro/src/JSTransformer/worker/index.js:253:15)
    at /home/maneesh/source/IPS-React/node_modules/metro/src/JSTransformer/index.js:113:43
    at Generator.next (<anonymous>)
    at step (/home/maneesh/source/IPS-React/node_modules/metro/src/JSTransformer/index.js:11:445)
    at /home/maneesh/source/IPS-React/node_modules/metro/src/JSTransformer/index.js:11:675
    at new Promise (<anonymous>)
    at /home/maneesh/source/IPS-React/node_modules/metro/src/JSTransformer/index.js:11:356
    at Transformer.transform (/home/maneesh/source/IPS-React/node_modules/metro/src/JSTransformer/index.js:140:10)
    at /home/maneesh/source/IPS-React/node_modules/metro/src/Bundler/index.js:315:44
    at Generator.next (<anonymous>)

Hi, this is my error log, am trying to run react native code, 

{
  "dependencies": {
    "@babel/preset-env": "^7.0.0-beta.48",
    "@babel/preset-react": "^7.0.0-beta.48",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-native": "0.55.4",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "react-tv-cli": "react-tv-cli",
    "start": "webpack-dev-server --progress --colors",
    "build": "webpack",
    "build-prod": "cross-env NODE_ENV=production yarn build",
    "run-webos": "yarn build-prod && react-tv-cli run-webos",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "native-start": "node node_modules/react-native/local-cli/cli.js start",
    "react-tv-start": "webpack-dev-server --progress --colors"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.48",
    "babel-jest": "23.0.0",
    "babel-loader": "^7.1.2",
    "@babel/polyfill": "^7.0.0-beta.48",
    "@babel/preset-env": "^7.0.0-beta.48",
    "@babel/preset-react": "^7.0.0-beta.48",
    "babel-preset-react-native": "^4.0.0",
    "cross-env": "^5.1.1",
    "jest": "23.0.0",
    "react": "^16.2.0",
    "react-test-renderer": "16.3.1",
    "react-tv": "^0.3.4",
    "react-tv-cli": "^0.3.4",
    "react-tv-navigation": "^0.4.0",
    "webpack": "^3.8.1",
    "webpack-dev-server": "^2.9.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

this is the package.json

.babelrc
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ]
}

please help me,, am  new to react native

**Comment by DeMoorJasper** [comment]
Babel 7 is not supported in Parcel yet.

**Comment by Maneeshashokan** [comment]
hey, what i can do now ? can you give me your gmail, have some questions. can you please help me

**Comment by DeMoorJasper** [comment]
See #868 You can just use babel 6 plugins and config for now that's the only way. Untill someone gets around to looking into implementing and testing the differences and breaking changes between 6 & 7

**Comment by Maneeshashokan** [comment]
Okya, thank you. I will look into it.

**Comment by MiracleBlue** [comment]
If this is the case, I would suggest that this incompatibility be documented somewhere obvious, especially for new users. Earlier I tried creating a new parcel project with babel 7 and I could not find this information in any of the usual places I would expect, and took a while before I came across the github issues. What would be the most appropriate place to document such incompatibilities?

**Comment by lloydjatkinson** [comment]
Yep still broken for me

**Comment by ManikantaAdimulam** [comment]
Please upgrade Package.json for babel 7

**Comment by lifeinvader00** [comment]
Will babel 7.0.0 be added to parcel in the near future?
