### ISSUE TITLE
error when tried to open chrome developer tools

### ISSUE THREAD

**Issue by slmjkdbtl** [parcel-bundler/parcel#1519]
## setup
> server.js
```javascript
const app = new Koa();
const Bundler = require("parcel-bundler");
const bundler = new Bundler("./public/src/main.js", {
    outDir: "./public/dist"
});
app.use(bundler.middleware());
```

## behavior
when opening the chrome developer tools:
```
11:51:31 PM web.1 |  /Users/t/Projects/Games/DIRTY-FINGER-X/node_modules/parcel-bundler/src/Server.js:21
11:51:31 PM web.1 |    res.setHeader('Access-Control-Allow-Origin', '*');
11:51:31 PM web.1 |        ^
11:51:31 PM web.1 |  TypeError: res.setHeader is not a function
11:51:31 PM web.1 |      at enableCors (/Users/t/Projects/Games/DIRTY-FINGER-X/node_modules/parcel-bundler/src/Server.js:21:7)
11:51:31 PM web.1 |      at SendStream.setHeaders (/Users/t/Projects/Games/DIRTY-FINGER-X/node_modules/parcel-bundler/src/Server.js:17:3)
11:51:31 PM web.1 |      at SendStream.emit (events.js:182:13)
11:51:31 PM web.1 |      at SendStream.setHeader (/Users/t/Projects/Games/DIRTY-FINGER-X/node_modules/send/index.js:864:8)
11:51:31 PM web.1 |      at SendStream.send (/Users/t/Projects/Games/DIRTY-FINGER-X/node_modules/send/index.js:625:8)
11:51:31 PM web.1 |      at onstat (/Users/t/Projects/Games/DIRTY-FINGER-X/node_modules/send/index.js:730:10)
11:51:31 PM web.1 |      at FSReqWrap.oncomplete (fs.js:183:5)
[DONE] Killing all processes with signal  null
internal/util.js:232
  throw new ERR_UNKNOWN_SIGNAL(signal);
  ^

TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: null
    at convertToValidSignal (internal/util.js:232:9)
    at ChildProcess.kill (internal/child_process.js:413:5)
    at EventEmitter.<anonymous> (/Users/t/.config/yarn/global/node_modules/foreman/lib/proc.js:54:11)
    at EventEmitter.emit (events.js:187:15)
    at ChildProcess.<anonymous> (/Users/t/.config/yarn/global/node_modules/foreman/lib/proc.js:50:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 10.3.0
| npm/Yarn         | 1.7.0
| Operating System | macOS High Sierra 10.13.4

**Comment by saadq** [comment]
I don't think Parcel's middleware is compatible with Koa, it's meant for Express.

**Comment by DeMoorJasper** [comment]
Parcel middleware only works with any http server that implements the same api as the default node one being:
(req, res, next) => ...

This includes express.
Perhaps there is a way to map koa to a node http instance or get the underlying http instance koa uses

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saadq** [comment]
There is indeed, [`app.callback()`](https://koajs.com/#app-callback-) returns a callback function that can be used with a normal `http` server.

**Comment by slmjkdbtl** [comment]
@saadq yes i was using `app.calllback()` with normal `http` server, guess it just doesn't work with koa now, thanks

**Comment by DeMoorJasper** [comment]
Closed due to being resolved I think
