### ISSUE TITLE
Tree Shaking claims a library in an applications doesn't export a function

### ISSUE THREAD

**Issue by kennetpostigo** [parcel-bundler/parcel#1540]
# 🐛 bug report
Running `--experimental-scope-hoisting` will fail to bundle an app claiming that an library is not exporting a file. I checked node modules to see if this was the case, but it's not. The function is being exported.

## 🎛 Configuration (.babelrc, package.json, cli command)
bsconfig:
```json
{
  "name": "...",
  "bs-dependencies": [
    "reason-react",
    "bs-fetch",
    "@glennsl/bs-json",
    "bs-css",
    "regql"
  ],
  "ppx-flags": ["graphql_ppx/ppx"],
  "reason": {
    "react-jsx": 2
  },
  "refmt": 3,
  "sources": ["vcomponents", "components", "pages", "styles"],
  // "package-specs": ["es6-global"],
  "bsc-flags": ["-bs-super-errors"]
}
```

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
would be helpful if you could provide some code that reproduces the issue. it will be pretty hard for us to debug otherwise.

**Comment by kennetpostigo** [comment]
Sorry issue created as I was filling out the fields

**Comment by goyney** [comment]
Can confirm, same issue here, using material-ui/core.

**myFile.jsx:***
`import { Button, CircularProgress, Grid } from '@material-ui/core';`

**index.es.js from material-ui/core:**
```
...
export { default as Grid } from './Grid';
...
```

```
🚨  ../node_modules/@material-ui/core/index.es.js does not export 'Grid'
    at replaceExportNode (/Users/mirigoyen/Git/projectname/node_modules/parcel/src/scope-hoisting/concat.js:98:13)
    at ReferencedIdentifier (/Users/mirigoyen/Git/projectname/node_modules/parcel/src/scope-hoisting/concat.js:353:20)
    at newFn (/Users/mirigoyen/Git/projectname/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/Users/mirigoyen/Git/projectname/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/mirigoyen/Git/projectname/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/mirigoyen/Git/projectname/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/mirigoyen/Git/projectname/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/mirigoyen/Git/projectname/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/mirigoyen/Git/projectname/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/mirigoyen/Git/projectname/node_modules/babel-traverse/lib/index.js:114:17)
```

**Comment by oliviertassinari** [comment]
@goyney I was curious to try it out on Material-UI too. 

> ../node_modules/@material-ui/core/index.es.js does not export 'Grid'

Stil, we have this line in the `index.es.js` file:
```jsx
export { default as Grid } from './Grid';
```
Going one step deeper, you will find the following in `Grid.js`:
```js
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/builtin/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "default", {
  enumerable: true,
  get: function get() {
    return _Grid.default;
  }
});

var _Grid = _interopRequireDefault(require("./Grid"));
```

**Comment by devongovett** [comment]
mmm looks like Grid is precompiled to compiled commonjs. sounds like an issue with interop between es6 imports and commonjs exports.

**Comment by reflog** [comment]
Same error here, while trying to use Apollo Client:
```
×  ..\node_modules\apollo-client\index.js does not export 'ApolloError'
    at replaceExportNode (D:\Dev\new_urelay\shipper\node_modules\parcel-bundler\src\scope-hoisting\concat.js:98:13)
    at ReferencedIdentifier (D:\Dev\new_urelay\shipper\node_modules\parcel-bundler\src\scope-hoisting\concat.js:353:20)
    at newFn (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\visitors.js:318:17)
    at NodePath._call (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\index.js:114:17)
error Command failed with exit code 1.
```

**Comment by reflog** [comment]
also happens when using antd
```
×  ..\node_modules\antd\es\version\index.js does not export 'default'
    at replaceExportNode (D:\Dev\new_urelay\shipper\node_modules\parcel-bundler\src\scope-hoisting\concat.js:98:13)
    at ReferencedIdentifier (D:\Dev\new_urelay\shipper\node_modules\parcel-bundler\src\scope-hoisting\concat.js:353:20)
    at newFn (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\visitors.js:318:17)
    at NodePath._call (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\Dev\new_urelay\shipper\node_modules\babel-traverse\lib\index.js:114:17)
```

**Comment by fathyb** [comment]
@reflog did you try #1542 ?

**Comment by oliviertassinari** [comment]
@devongovett Awesome.
Still, I have this issue now. I can open an issue if you wish:
>   Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/Users/oliviertassinari/material-ui-next/examples/parcel/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/oliviertassinari/material-ui-next/examples/parcel/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/Users/oliviertassinari/material-ui-next/examples/parcel/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath._remove (/Users/oliviertassinari/material-ui-next/examples/parcel/node_modules/babel-traverse/lib/path/removal.js:58:10)
    at NodePath.remove (/Users/oliviertassinari/material-ui-next/examples/parcel/node_modules/babel-traverse/lib/path/removal.js:30:8)
    at binding.referencePaths.concat.forEach.path (/Users/oliviertassinari/material-ui-next/examples/parcel/node_modules/parcel-bundler/src/scope-hoisting/shake.js:41:22)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach.name (/Users/oliviertassinari/material-ui-next/examples/parcel/node_modules/parcel-bundler/src/scope-hoisting/shake.js:32:10)
    at Array.forEach (<anonymous>)
    at treeShake (/Users/oliviertassinari/material-ui-next/examples/parcel/node_modules/parcel-bundler/src/scope-hoisting/shake.js:20:33)

```jsx
import { Grid } from '@material-ui/core';
```

**Comment by devongovett** [comment]
@oliviertassinari sounds like #1549.

**Comment by oliviertassinari** [comment]
Thanks, yes it's.

**Comment by kennetpostigo** [comment]
@devongovett just tried out the new release, I still come across this same exact error.

**Comment by mturki** [comment]
Still i have the issue with `date-fns` on build + tree shake (but it works pretty well with a normal build).

`node_modules/date-fns/esm/endOfWeek/index.js does not export 'default'
    at replaceExportNode ((...)/node_modules/parcel-bundler/src/scope-hoisting/concat.js:54:13)
    at ReferencedIdentifier ((...)/node_modules/parcel-bundler/src/scope-hoisting/concat.js:317:20)
    at newFn ((...)/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call ((...)/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call ((...)/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit ((...)/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue ((...)/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle ((...)/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit ((...)/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node ((...)/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/index.js:94:17)
error Command failed with exit code 1`

**Comment by baltuonis** [comment]
Issue with `    "@sentry/browser": "^5.4.3",`
Throws `node_modules/@sentry/browser/esm/sdk.js does not export 'init'` when `--experimental-scope-hoisting`

**Comment by mischnic** [comment]
@baltuonis Can you provide a code sample? 

@mturki Which version of `date-fns` are you using and please provide a code sample.

**Comment by baltuonis** [comment]
```typescript
import * as Sentry from '@sentry/browser'; (fails)
// also tried:
// import { init } from '@sentry/browser'; (fails)
// <...> from '@sentry/browser/dist/sdk; (in this case the init part gets transpiled to ({})   )
// <...> from '@sentry/browser/esm/sdk; (fails)
// <...> from '@sentry/browser/esm/; (fails)
// tried old Sentry v5.0 - and the init get's transpiled to ({})

  Sentry.init({
    dsn: window.SENTRY_DSN,
    environment: window.ENV
  });
```

Deps:

```
    "@babel/core": "^7.4.5",
    "@google/markerclusterer": "1.0.3",
    "@types/googlemaps": "^3.36.5",
    "@sentry/browser": "^5.4.3",
    "babel-plugin-transform-remove-console": "6.9.4",
    "choices.js": "^7.0.0",
    "cross-env": "^5.2.0",
    "lazysizes": "^5.1.0",
    "parcel-bundler": "^1.12.3",
    "smooth-scroll": "^16.1.0",
    "typescript": "^3.5.2"
```

**Comment by mischnic** [comment]
@baltuonis Works fine for me with just that code. Is that a typescript file? What's your `tsconfig.json`?

**Comment by baltuonis** [comment]
@mischnic  - yes it's Typescript.
No `tsconfig.json` (it's parcel ;-))
It was failing both on build server and my machine

**Comment by mischnic** [comment]
Still, can't get it to throw that error: https://github.com/mischnic/parcel-issue-1540

**Comment by orballo** [comment]
Hi! I'm getting this same error (or maybe just similar) when using `"@risingstack/react-easy-state": "^6.3.0"`.

The error:
```
🚨 Build failed.
@parcel/packager-js: nodemodules/@risingstack/react-easy-state/dist/react-platform.js does not export 'unstablebatchedUpdates'
node_modules/@risingstack/react-easy-state/dist/es.es6.js:4:10
  3 | export { unobserve as clearEffect } from '@nx-js/observer-util';
> 4 | import { unstable_batchedUpdates } from './react-platform';
>   |          ^^^^^^^^^^^^^^^^^^^^^^^
```
This is happening with `"parcel": "^2.0.0-beta.1"` but also with the `v1`. The error log is slightly different, but it's still the same error.

The code in the files referenced:
```js
// nodemodules/@risingstack/react-easy-state/dist/react-platform.js

export * from 'react-dom';
```

```js
// node_modules/@risingstack/react-easy-state/dist/es.es6.js:4:10

import { useState, memo, useMemo, useEffect, Component } from 'react';
import { observe, unobserve, isObservable, raw, observable } from '@nx-js/observer-util';
export { unobserve as clearEffect } from '@nx-js/observer-util';
import { unstable_batchedUpdates } from './react-platform';
```

Let me know if you need any other details, or if you have suggestions on how to fix it :)
