### ISSUE TITLE
Cannot read property 'process' of undefined

### ISSUE THREAD

**Issue by cheneyweb** [parcel-bundler/parcel#1548]
# 🐛 bug report

when run parcel build , it show me the error with "Cannot read property 'process' of undefined"
at Object.run (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/worker.js:23:27)
    at Child.handleRequest (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/workerfarm/child.js:59:49)
    at Child.messageListener (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/workerfarm/child.js:34:19)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

when I use MacOS 10.13.6，it work!
but when I use CentOS 7 ，it show the error

the nodejs version is the same with two Operating System, the nodejs version is 10.4.1
the only difference with those system is the NODE_ENV
I haven't ser NODE_ENV with MacOS
I set NODE_ENV=production with CentOS 7

The parcel 1.7.0 version is work find with two Operating System
this problem happen with parcel 1.9.0

the follow is my package.json description

  "scripts": {
    "dev": "parcel index.html",
    "build": "parcel build index.html --public-url / --no-source-maps"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "vue-hot-reload-api": "^2.3.0",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^2.0.0",
    "iview": "^2.14.2",
    "parcel-bundler": "^1.9.0",
    "vue": "^2.5.16",
    "vue-template-compiler": "^2.5.16"
  }

## 🤔 Expected Behavior

build success

## 😯 Current Behavior

when run parcel build , it show me the error with "Cannot read property 'process' of undefined"
at Object.run (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/worker.js:23:27)
    at Child.handleRequest (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/workerfarm/child.js:59:49)
    at Child.messageListener (/usr/local/node/parcel-vue/node_modules/parcel-bundler/src/workerfarm/child.js:34:19)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

## 💁 Possible Solution

use parcel 1.7.0

## 🌍 Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| parcel-plugin-vue | 1.9.0
| Parcel            | 1.9.0
| Vue                | 2.5.16
| Node             | 10.4.1 
| npm/Yarn      |  6.1.0
| Operating System  |  CentOS 7

**Comment by abellion** [comment]
It worked in Parcel 1.8 too, same issue starting at 1.9

**Comment by devongovett** [comment]
sounds like `run` is being called before `init`? that's the only reason `pipeline` would be undefined. @DeMoorJasper ideas?

**Comment by DeMoorJasper** [comment]
@devongovett I guess a worker died and a new one spawned, that would result in not initialising. Perhaps something in 1.9 puts a lot more stress on the workers?
Good thing to fix this anyways, I'll try to create a fix for this and do a PR

**Comment by DeMoorJasper** [comment]
Could you check if this still happens when using #1587

**Comment by cheneyweb** [comment]
I update parcel version to 1.9.2
and this problem still happen

**Comment by DeMoorJasper** [comment]
@cheneyweb  1.9.2 doesn't contain any fix for this. try out the PR I linked earlier.

**Comment by cheneyweb** [comment]
@DeMoorJasper I don't konw how to install the branch of fix/worker-init，i git clone it and replace /node_modules/parcel-bundler and npm install，but it won't work，could you show me the step of it？thank you very much :)

**Comment by cheneyweb** [comment]
@DeMoorJasper 
I follow your strp,here is my setp:

1、git clone https://github.com/parcel-bundler/parcel.git && cd parcel
2、git checkout fix/worker-init
3、npm link

4、Go into my project
5、npm link parcel-bundler

6、npm install 【for rest modules in package.json】

and I try "npm run build" for my project，it show me follow error msg:

(node:3707) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/node/parcel/src/builtins/prelude2.min.js'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.readFileSync (fs.js:485:33)
    at Object.<anonymous> (/usr/local/node/parcel/src/packagers/JSConcatPackager.js:11:4)
    at Module._compile (/usr/local/node/parcel/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (/usr/local/node/parcel/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
(node:3707) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3707) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I also try npm link parcel-bundler after npm install 【for rest modules in package.json】，and it show me the same message

my npm stript of project is 

"scripts": {
"dev": "parcel index.html",
"build": "parcel build index.html --public-url / --no-source-maps"
},

**Comment by DeMoorJasper** [comment]
@cheneyweb you also have to do npm install & npm run build inside the parcel folder

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cheneyweb** [comment]
@DeMoorJasper 
It work with branch fix/worker-init
Thank you very much!
I wonder when would this fix will publish with parcel master branch, and we could npm install it

please message me if it work with parcel master package:)
