### ISSUE TITLE
[Parcel 1.9.0][experimental-scope-hoisting] Error "does not export 'function'" in apollo library

### ISSUE THREAD

**Issue by szagi3891** [parcel-bundler/parcel#1553]
# 🐛 bug report

I run command :
./node_modules/.bin/parcel build --experimental-scope-hoisting ./index.html

And I receive error:

```
🚨  node_modules/apollo-utilities/lib/index.js does not export 'getOperationName'
    at replaceExportNode (/home/oem/Desktop/parcel-bug/node_modules/parcel-bundler/src/scope-hoisting/concat.js:98:13)
    at ReferencedIdentifier (/home/oem/Desktop/parcel-bug/node_modules/parcel-bundler/src/scope-hoisting/concat.js:353:20)
    at newFn (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/index.js:114:17)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

I have created a small test repository:
https://github.com/szagi3891/parcel-bug
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.0 |
| Node             | v10.0.0 |
| npm/Yarn         | 1.7.0 |
| Operating System | Linux Mint |

**Comment by devongovett** [comment]
probably related to #1540. might be fixed by #1542?

**Comment by szagi3891** [comment]
I updated parcel-bundler to version 1.9.1
The problem still exists.

**Comment by szagi3891** [comment]
```
oem@oem-Inspiron-5767 ~/Desktop/parcel-bug $ ./build.sh 
🚨  node_modules/apollo-utilities/lib/getFromAST.js does not export 'getOperationName'
    at replaceExportNode (/home/oem/Desktop/parcel-bug/node_modules/parcel-bundler/src/scope-hoisting/concat.js:102:13)
    at ReferencedIdentifier (/home/oem/Desktop/parcel-bug/node_modules/parcel-bundler/src/scope-hoisting/concat.js:357:20)
    at newFn (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/oem/Desktop/parcel-bug/node_modules/babel-traverse/lib/index.js:114:17)
```

**Comment by raja** [comment]
Still an issue with Parcel 1.9.4

**Comment by rafaelrinaldi** [comment]
Having the same issue with Redux Form on `v1.9.4`.

**Comment by szagi3891** [comment]
Cool :)
When will version 1.9.5 be available? :)

**Comment by szagi3891** [comment]
Unfortunately, the problem is still there. 
I used the version 1.9.5.

Steps to reproduce:
```
git clone https://github.com/szagi3891/parcel-bug
yarn
./build.sh
```

**Comment by ZY-Ang** [comment]
v1.9.7. I believe the issue still persists with Apollo. I'm using 
```
..\..\..\node_modules\apollo-utilities\lib\getFromAST.js does not export 'getOperationName'
    at replaceExportNode (C:\Users\...project...\node_modules\parcel-bundler\src\scope-hoisting\concat.js:54:13)
    at ReferencedIdentifier (C:\Users\...project...\node_modules\parcel-bundler\src\scope-hoisting\concat.js:317:20)
    at newFn (C:\Users\...project...\node_modules\babel-traverse\lib\visitors.js:318:17)
    at NodePath._call (C:\Users\...project...\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\...project...\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\...project...\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\...project...\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\...project...\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\Users\...project...\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\Users\...project...\node_modules\babel-traverse\lib\index.js:114:17)
```

My .babelrc is:
```json
{
  "presets": [
    "react-app"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-es2015-arrow-functions",
    "transform-es2015-modules-commonjs"
  ]
}

```
Any update?

**Comment by szagi3891** [comment]
I created a new bug report some time ago:
https://github.com/parcel-bundler/parcel/issues/1819
