### ISSUE TITLE
[Parcel 1.9.3][experimental-scope-hoisting] lodash-es/isPlainObject.js does not export 'default'

### ISSUE THREAD

**Issue by tamuraryoya** [parcel-bundler/parcel#1621]
# 🐛 bug report

I run command:

`parcel build src/index.pug --no-source-maps  --experimental-scope-hoisting`

And I receive error:

```
🚨  ../node_modules/lodash-es/isPlainObject.js does not export 'default'
    at replaceExportNode (/my/project/node_modules/parcel-bundler/src/scope-hoisting/concat.js:102:13)
    at ReferencedIdentifier (/my/project/node_modules/parcel-bundler/src/scope-hoisting/concat.js:357:20)
    at newFn (/my/project/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/my/project/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/my/project/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/my/project/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/my/project/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/my/project/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/my/project/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/my/project/node_modules/babel-traverse/lib/index.js:114:17)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

**package.json**

```json
{
  "scripts": {
    "start": "BUILD_ENV=development LOCAL_IP=`my-local-ip` parcel src/index.pug -p 4300 --no-autoinstall"
    "prod": "rm -rf dist; BUILD_ENV=production parcel build src/index.pug --no-source-maps"
  },
  "devDependencies": {
    "@types/chroma-js": "^1.3.5",
    "@types/classnames": "^2.2.3",
    "@types/js-cookie": "^2.1.0",
    "@types/lockr": "^0.8.6",
    "@types/lodash": "^4.14.109",
    "@types/node": "^10.3.4",
    "@types/query-string": "^5.1.0",
    "@types/react": "^16.3.16",
    "@types/react-dom": "^16.0.6",
    "@types/react-redux": "^6.0.0",
    "@types/react-router-dom": "^4.2.6",
    "@types/react-router-redux": "^5.0.14",
    "@types/react-transition-group": "^2.0.11",
    "@types/redux-logger": "^3.0.6",
    "@types/redux-thunk": "^2.1.0",
    "autoprefixer": "^8.5.0",
    "babel-core": "^6.26.3",
    "json-server": "^0.13.0",
    "my-local-ip": "^1.0.0",
    "node-sass": "^4.9.0",
    "nodemon": "^1.17.5",
    "parcel-bundler": "^1.9.3",
    "parcel-plugin-bundle-visualiser": "^1.1.2",
    "parcel-plugin-typescript": "^1.0.0",
    "postcss": "^6.0.22",
    "postcss-modules": "^1.1.0",
    "pug": "^2.0.3",
    "react-docgen-typescript-webpack-plugin": "^1.1.0",
    "redux-devtools-extension": "^2.13.2",
    "sass-loader": "^7.0.3",
    "tslint": "^5.10.0",
    "tslint-config-standard": "^7.0.0",
    "tslint-react": "^3.6.0",
    "typescript": "^2.8.3",
    "webpack": "^4.11.1"
  },
  "dependencies": {
    "@babel/polyfill": "^7.0.0-beta.47",
    "chroma-js": "^1.3.7",
    "classnames": "^2.2.5",
    "inobounce": "^0.1.6",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.2.0",
    "lockr": "^0.8.4",
    "lodash": "^4.17.10",
    "query-string": "^6.1.0",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-minimal-pie-chart": "^3.0.2",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^4.0.8",
    "react-transition-group": "^2.3.1",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "reset-css": "^4.0.1",
    "typescript-fsa": "^3.0.0-beta-2",
    "typescript-fsa-reducers": "^0.4.5",
    "typescript-fsa-redux-thunk": "^2.0.0-beta.11"
  }
}
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "moduleResolution": "node",
    "baseUrl": ".",
    "types": [
      "node"
    ],
    "paths": {
      "~/*": [
        "src/scripts/*"
      ],
      "=/*": [
        "src/assets/*"
      ]
    }
  }
}
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |v1.9.3|
| Node             |v8.11.1|
| npm/Yarn         |yarn v1.5.1|
| Operating System |MacBook Pro High Sierra (10.13.5)|

**Comment by fathyb** [comment]
Could you provide a reproduction? How do you import `lodash-es`?

**Comment by tehfailsafe** [comment]
I'm having this issue as well, and I don't directly use lodash anywhere. One of my dependencies must be using it, but how do I track that down?

**Comment by nigelzor** [comment]
I've hit this too. It seems like the error is triggered when importing `lodash-es` transitively from a typescript file.

Here's a minimal reproduction: https://github.com/nigelzor/parcel-issue-1621

**Comment by mischnic** [comment]
@nigelzor Your example seems to build successfully with parcel 1.10.3. Can you confirm that?

**Comment by nigelzor** [comment]
@mischnic yep; I'm no longer seeing this error when using parcel 1.10.3.

**Comment by vivex** [comment]
I am still getting it in parcel 1.12.4 and same with 1.10.3 also.

**Comment by mrcoles** [comment]
@vivex you another thing to check in your project is to see if you’re doing `import isPlainObject from 'is-plain-object'` and if so, change it to `import { isPlainObject } from 'is-plain-object'`
