### ISSUE TITLE
Plugins are not loaded if the entry is not on the same directory as package.json

### ISSUE THREAD

**Issue by fathyb** [parcel-bundler/parcel#167]
This is a 🐛 bug report.

### 🎛 Directory structure

```
- package.json
+ src
  - main.js
+ node_modules
  + parcel-bundler
  + parcel-plugin-plugin
```

### 🤔 Expected Behavior
Parcel should be able to load the plugins from the `package.json`.

### 😯 Current Behavior
It does not if the entry file is not in the root directory of the project.

The error is silenced but if we log it we get :
```
Error: Cannot find module './package.json' from '[project]/src'
at Function.module.exports [as sync] ([project]/node_modules/resolve/lib/sync.js:40:15)
at module.exports ([project]/node_modules/parcel-bundler/src/utils/localRequire.js:11:24)
at Bundler.loadPlugins ([project]/node_modules/parcel-bundler/src/Bundler.js:86:17)
at new Bundler ([project]/node_modules/parcel-bundler/src/Bundler.js:44:10)
at Command.bundle ([project]/node_modules/parcel-bundler/bin/cli.js:66:19)
at Command.listener ([project]/node_modules/commander/index.js:315:8)
at emitTwo (events.js:126:13)
at Command.emit (events.js:214:7)
at Command.parseArgs ([project]/node_modules/commander/index.js:653:12)
at Command.parse ([project]/node_modules/commander/index.js:475:21) code: 'MODULE_NOT_FOUND'
```

### 💁 Possible Solution

I dirty-fixed it by replacing `./package.json` to `../package.json`, but the best solution should be to traverse the directory tree until a `package.json` is found.

### 🔦 Context

Found this while working on a plugin

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.1.0
| Node             | 8.9.1
| npm/Yarn         | 1.3.2
| Operating System | macOS 10.13.2

**Comment by DeMoorJasper** [comment]
Path traversing up is prob a solid way to go, i'll take a look at it

**Comment by brandon93s** [comment]
There is a `pkg-up` module that currently handled this:

https://github.com/sindresorhus/pkg-up

**Comment by davidnagli** [comment]
@fathyb Are you running parcel via an npm script?

**Comment by fathyb** [comment]
@davidnagli yes, I have `"build": "parcel src/main.js"` in my `scripts` and I run `yarn build`. Same with `$(yarn bin)/parcel src/main.js`
