### ISSUE TITLE
Path must be a string. Received null

### ISSUE THREAD

**Issue by lnorton89** [parcel-bundler/parcel#1705]
# 🐛 bug report

Fresh project with blank HTML5 boilerplate index file will not build.

## 🎛 Configuration (.babelrc, package.json, cli command)

No configuration.

## 🤔 Expected Behavior

It should build and show the preview in the browser.

## 😯 Current Behavior

``lawrence@LIGHTNING:/mnt/c/Users/Lawrence/Documents/dev/sandbox/instagram-api$ parcel index.html
Server running at http://localhost:1234
🚨  /mnt/c/Users/Lawrence/Documents/dev/sandbox/instagram-api/index.html: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at module.exports (/usr/lib/node_modules/parcel-bundler/src/utils/urlJoin.js:11:29)
    at HTMLAsset.processSingleDependency (/usr/lib/node_modules/parcel-bundler/src/assets/HTMLAsset.js:91:19)
    at ast.walk.node (/usr/lib/node_modules/parcel-bundler/src/assets/HTMLAsset.js:138:43)
    at traverse (/usr/lib/node_modules/parcel-bundler/node_modules/posthtml/lib/api.js:105:26)
    at traverse (/usr/lib/node_modules/parcel-bundler/node_modules/posthtml/lib/api.js:111:5)
    at traverse (/usr/lib/node_modules/parcel-bundler/node_modules/posthtml/lib/api.js:105:17)
    at traverse (/usr/lib/node_modules/parcel-bundler/node_modules/posthtml/lib/api.js:111:5)
    at traverse (/usr/lib/node_modules/parcel-bundler/node_modules/posthtml/lib/api.js:105:17)``

## 🔦 Context

This is the first time using parcel. There is no context. It should work.

## 💻 Code Sample

[index.html](https://gist.github.com/lnorton89/3208638a978f88f4319caa1e55137823
)
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Latest
| Node             | 8.11.1
| npm/Yarn         | 5.6.0
| Operating System | Ubuntu / WSL

**Comment by DeMoorJasper** [comment]
In your html you have an empty `link` tag that should probably be requiring your css?

`<link rel="stylesheet" href="">`

But you're definitely right that we need to work on creating more detailed and explanatory error messages.

**Comment by peanutbother** [comment]
Theres also this line: 
`<!--[if gt IE 8]><!-->`

**Comment by tgmarinho** [comment]
@DeMoorJasper Your commentary was helpful, I generated my index.html file with boilerplate, then I had this: `<link rel="stylesheet" href="">`! I removed it so it works fine. Thanks

**Comment by icavalheiro** [comment]
Placing a <img src=""> returns the same error (took me 20 min to figure out that)
