### ISSUE TITLE
fallback to the source version of the builtins when minified versions not available

### ISSUE THREAD

**Issue by martell** [parcel-bundler/parcel#1744]
# 🐛 bug report

In source tree of parcel does not contain minified versions of builtins though the source expects it.
People should be working with release tags but in the off chance they want to work with a newly merged feature we need to fallback to the source version of the builtins.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  "devDependencies": {
    "parcel-bundler": "parcel-bundler/parcel"
  }
```

## 🤔 Expected Behavior

```
$ parcel ./src/index.html --no-cache --open
Server running at http://localhost:1234
```

## 😯 Current Behavior

```
(node:89140) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'modernize-ng1/node_modules/parcel-bundler/src/builtins/prelude2.min.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.<anonymous> (modernize-ng1/node_modules/parcel-bundler/src/packagers/JSConcatPackager.js:16:6)
    at Module._compile (modernize-ng1/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (modernize-ng1/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
```

## 💁 Possible Solution

If someone in future installs parcel from git with package.json they will not need extra steps to work with it from tree.
https://github.com/parcel-bundler/parcel/pull/1741

## 🔦 Context

I was trying to work with the new html support on the master branch

## 💻 Code Sample
To reproduce checkout this PR and just run `yarn install && yarn dev`
https://github.com/edm00se/modernize-ng1/pull/3

The environment is not as important for this bug as it is not OS specific.
It is due to the difference between a built bundled version and git tree source version

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | master - v1.9.7 + html support (075ca6f)

**Comment by DeMoorJasper** [comment]
Can you please use the issue template

**Comment by martell** [comment]
@DeMoorJasper updated :)
I hope that helps

**Comment by martell** [comment]
Thanks for making sure it got merged. :)
