### ISSUE TITLE
Error on typescript: Cannot destructure property `parser` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by duduluu** [parcel-bundler/parcel#1787]
# 🐛 bug report

Cannot dev-serve or build with typescript, even just a simple hello-world script.

## 🎛 Configuration (.babelrc, package.json, cli command)

tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["dom", "scripthost", "es5", "es2015", "es2016", "es2017", "es2018", "esnext"],
    "target": "es5",
    "sourceMap": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "dist",
    "rootDir": "src",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    // "allowSyntheticDefaultImports": true, /* This will make some problems in parcel.js. */
    "strict": true,
    "strictPropertyInitialization": false
  },
  "exclude": ["node_modules"],
  "include": ["src/**/*"]
}
```

## 😯 Current Behavior

```
🚨  /mnt/w/fe/template-parcel-ts/src/index.html: Cannot destructure property `parser` of 'undefined' or 'null'.
    at Object.MakeTranspileAsset (/mnt/w/fe/template-parcel-ts/node_modules/parcel-plugin-typescript/build/frontend/assets/classes/transpile.js:7:24)
    at new module.exports (/mnt/w/fe/template-parcel-ts/node_modules/parcel-plugin-typescript/build/frontend/assets/forked.js:6:43)
    at Parser.getAsset (/mnt/w/fe/template-parcel-ts/node_modules/parcel-bundler/src/Parser.js:81:12)
    at HTMLAsset.addURLDependency (/mnt/w/fe/template-parcel-ts/node_modules/parcel-bundler/src/Asset.js:113:8)
    at HTMLAsset.processSingleDependency (/mnt/w/fe/template-parcel-ts/node_modules/parcel-bundler/src/assets/HTMLAsset.js:89:26)
    at ast.walk.node (/mnt/w/fe/template-parcel-ts/node_modules/parcel-bundler/src/assets/HTMLAsset.js:151:43)
    at traverse (/mnt/w/fe/template-parcel-ts/node_modules/posthtml/lib/api.js:105:26)
    at traverse (/mnt/w/fe/template-parcel-ts/node_modules/posthtml/lib/api.js:111:5)
    at traverse (/mnt/w/fe/template-parcel-ts/node_modules/posthtml/lib/api.js:105:17)
    at traverse (/mnt/w/fe/template-parcel-ts/node_modules/posthtml/lib/api.js:111:5)
```

## 💻 Code Sample

https://github.com/HuijiFE/template-parcel-ts

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | parcel-bundler@1.9.7 parcel-plugin-typescript@0.7.1|
| Node             |v8.10.0|
| Yarn         |v1.7.0|
| Operating System |Windows10 WSL Ubuntu 18.04|

**Comment by duduluu** [comment]
@coffeeowl Thx! It work. I used `yarn upgrade-interactive` to update the modules, but it didn't update parcel-plugin-typescript. I updated the plugin manuallly just now, it works.
