### ISSUE TITLE
aliases has error when used in vue style

### ISSUE THREAD

**Issue by wocanbe** [parcel-bundler/parcel#1866]
I write like this
```html
<style lang="scss">
@import '~@/assets/common';
@import '~@/assets/page';
</style>
<template lang="pug">
  .lt-page the demo page
</template>
<script>
import {mapState} from 'vuex'
export default {
  name: 'App',
  computed: {
    ...mapState(['errMsg', 'loading', 'mask'])
  }
}
</script>
```

has next error

```
/workspaces/work-project/my-project/src/App.vue: File to import not found or unreadable: @/assets/common.
    at options.error (/workspaces/work-project/my-project/node_modules/node-sass/lib/index.js:291:26)
```

**Comment by wocanbe** [comment]
It not add fileExt(scss) but add dot(.)

**Comment by DeMoorJasper** [comment]
Not sure I understand, what aliases? I just see an incorrect usage of `~`?

`~` is used for node modules if not followed by `/` and otherwise seen as root.

Please share pkg.json or at least the aliases section of pkg.json.

**Comment by wocanbe** [comment]
This is my package.json
```json
{
  "name": "my-project",
  "version": "0.0.1",
  "main": "main.js",
  "license": "MIT",
  "author": "liuying",
  "scripts": {
    "dev": "parcel index.html -p 8888",
    "build": "parcel build index.html --public-url /"
  },
  "alias": {
    "@": "src"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^2.1.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1",
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.8.1",
    "parcel-plugin-vue-auto-router": "^0.0.1",
    "pug": "^2.0.3",
    "vue-hot-reload-api": "^2.3.0",
    "vue-template-compiler": "^2.5.17"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "lodash": "^4.17.10",
    "vue": "^2.5.17",
    "vue-hot-reload-api": "^2.3.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  }
}
```
When i use alias in vue-style with webpack,must add '~',else can not work.

If i use error,what is the right way of use

**Comment by DeMoorJasper** [comment]
Try this:

`"@": "./src"`

**Comment by wocanbe** [comment]
still error
```
/workspaces/work-project/my-project/src/App.vue: File to import not found or unreadable: @/assets/common.
    at options.error (/workspaces/work-project/my-project/node_modules/node-sass/lib/index.js:291:26)
```
parcel-bundler version is 1.9.7

**Comment by wocanbe** [comment]
I make sure again. this is my tree in path src
```
.
|____App.vue
|____config
| |____ajax.js
|____aa.txt
|____libs
| |____ajax
| | |____index.js
| | |____ajax.js
|____main.js
|____styles
| |____common.css
|____components
| |____index.js
| |____Hello
| | |____index.js
| | |____appHello.vue
|____views
| |____index.vue
| |____login.vue
| |_____.vue
|____assets
| |____page.scss
| |____common.scss
| |____logo.png
|____store
| |____mutations.js
| |____.DS_Store
| |____actions.js
| |____getters.js
| |____index.js
| |____mutation-types.js
| |____modules
| | |____login.js
|____router
| |____index.js
```

**Comment by DeMoorJasper** [comment]
Make sure you’re running parcel-bundler 1.9.7

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wocanbe** [comment]
Wait a monent,I push my project to github.

**Comment by wocanbe** [comment]
https://github.com/wocanbe/autorouter-project.git
@DeMoorJasper

**Comment by wocanbe** [comment]
I edit parcel-bundler/src/assets/SASSAsset.js
add next code at line 56
```javascript
      console.log('>-------------------<', url)
      url = this.options.rootDir + url.replace('@', '/src')
      console.log('---------<>----------', url)
```
the console
```
>-------------------< @/assets/common
---------<>---------- /workspaces/work-project/luck7-project/src/assets/common
>-------------------< @/assets/common
---------<>---------- /workspaces/work-project/luck7-project/src/assets/common
>-------------------< @/assets/page
---------<>---------- /workspaces/work-project/luck7-project/src/assets/page
```
The file path must absolute path at here,but i found is the path use write.

This is not common method,Maybe can help you.

**Comment by wocanbe** [comment]
my project: 
https://github.com/wocanbe/autorouter-project.git

**Comment by DeMoorJasper** [comment]
I think I figured out why this isn't working. It's actually the same thing I explained earlier. Do not use symbols, they should be preserved for usage by tools and npm.

Basically it comes down to npm using `@` for organisations. So Parcel tries to resolve this to an organisations, change `"@": "./src"` into `"source": "./src"` and it'll work perfectly (on Parcel 1.9.7)
