### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by hiroppy** [parcel-bundler/parcel#1884]
# 🐛 bug report
CI fails only when it is Node 10.

```
Error: Cannot find module 'add.wasm'
      at newRequire (evalmachine.<anonymous>:39:19)
      at newRequire (evalmachine.<anonymous>:23:18)
      at localRequire (evalmachine.<anonymous>:54:14)
      at Object.parcelRequire.dynamic.js../add.wasm (evalmachine.<anonymous>:107:16)
      at newRequire (evalmachine.<anonymous>:48:24)
      at parcelRequire.dynamic.js../add.wasm (evalmachine.<anonymous>:80:5)
      at evalmachine.<anonymous>:106:3
      at Script.runInContext (vm.js:102:20)
      at runInContext (vm.js:280:6)
      at Object.vm.runInContext (node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:178:16)
```

and some flaky tests.

CI log of current master: https://travis-ci.org/parcel-bundler/parcel/jobs/414768244

## 🎛 Configuration (.babelrc, package.json, cli command)
none

## 🤔 Expected Behavior

CI passes.

## 😯 Current Behavior

CI failes.
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest
| Node             | 10
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
This is flaky because it downloads a nightly version every time and sometimes wasm tests fail. Not sure if we can lock the installed wasm version

**Comment by DeMoorJasper** [comment]
This is probably not related to parcel but due to a nightly version of the compiler

**Comment by hiroppy** [comment]
Should we ignore this failing test only at Node 10? (or should we keep to fail CI?)

**Comment by DeMoorJasper** [comment]
The more stable we can get the tests the better, but I personally just ignore it
