### ISSUE TITLE
 <css input>:1:3: Unknown word

### ISSUE THREAD

**Issue by gkumar9** [parcel-bundler/parcel#1916]
# 🐛 bug report

We started using parcel.js recently and found it awesome and easier than webpack.
 
- We are having website with html/css/javascript and running parcel for bundling code. While we run `parcel *.html`, it is working fine and able to browse on http://localhost:1234. But it seems in production mode, while running `parcel build *.html`, it gives below error.

- We also found that with `parcel build --no-minify *.html`, it works fine. But we need to minify css/js at the time of build. Can you please help us in this regard.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parceljs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jquery": "^3.3.1"
  },
  "devDependencies": {
    "cssnano": "^4.0.5"
  }
}
```

## 🤔 Expected Behavior

It should build with minified css/js.
## 😯 Current Behavior
Does not build without --no-minify in production mode.

shows above error

> 🚨  /home/software/parceljs/builddir/productdetail.html: <css input>:1:3: Unknown word
>     at Input.error (/usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/node_modules/postcss/lib/input.js:113:22)
>     at Parser.unknownWord (/usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/node_modules/postcss/lib/parser.js:468:26)
>     at Parser.other (/usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/node_modules/postcss/lib/parser.js:174:14)
>     at Parser.loop (/usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/node_modules/postcss/lib/parser.js:81:26)
>     at parse (/usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/node_modules/postcss/lib/parse.js:26:16)
>     at new LazyResult (/usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/node_modules/postcss/lib/lazy-result.js:70:24)
>     at Processor.process (/usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/node_modules/postcss/lib/processor.js:117:12)
>     at Function.cssnano.process (/usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/node_modules/cssnano/dist/index.js:306:55)
>     at processStyleAttr (/usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/lib/modules/minifyCss.js:45:30)
>     at /usr/lib/node_modules/parcel-bundler/node_modules/htmlnano/lib/modules/minifyCss.js:21:27

## 🔦 Context

We need to bundle website with minified js/css.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.11.3
| npm/Yarn         | npm 6.2.0
| Operating System | Ubuntu 16.04 (Xenial Xerus)

**Comment by DeMoorJasper** [comment]
Could you try with the current master branch?

Parcel now processes inline styles in it's own pipeline, to resolve dependencies and such
