### ISSUE TITLE
parcel bulid error

### ISSUE THREAD

**Issue by ollieSk8** [parcel-bundler/parcel#196]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
this a 🐛 bug

### 😯 Current Behavior
i am run **parcel bulid index.html -d build** and the terminal show error 

`erver running at http://localhost:1234
🚨  Cannot find module '/Users/ollie/myspace/parcel/bulid' from '.'
    at /Users/ollie/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/ollie/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/ollie/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/ollie/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:166:21)`

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.1.0
| Node             | 9.2.1
| npm/Yarn         | yarn 1.3.2
| Operating System | mac os high sierra

**Comment by davidnagli** [comment]
Try `parcel bulid -d build index.html`

**Comment by ollieSk8** [comment]
@davidnagli 

error angin

`parcel bulid -d build index.html
Server running at http://localhost:1234
🚨  Cannot find module '/Users/ollie/myspace/parcel/bulid' from '.'
    at /Users/ollie/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/ollie/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/ollie/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/ollie/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:166:21)`

**Comment by davidnagli** [comment]
Oh! You misspelled the word "build" 😇 

```
 parcel build index.html -d build
```

**Comment by ollieSk8** [comment]
@davidnagli 

another error 


`parcel build index.html -d build
🚨  /Users/ollie/myspace/parcel/index.js: Cannot read property 'start' of undefined
    at module.exports (/Users/ollie/.config/yarn/global/node_modules/babel-to-estree/babylon-to-espree/attachComments.js:56:42)
    at module.exports (/Users/ollie/.config/yarn/global/node_modules/babel-to-estree/babylon-to-espree/index.js:35:3)
    at exports.toEstree (/Users/ollie/.config/yarn/global/node_modules/babel-to-estree/index.js:9:3)
    at module.exports (/Users/ollie/.config/yarn/global/node_modules/parcel-bundler/src/transforms/uglify.js:10:39)
    at <anonymous>`

**Comment by davidnagli** [comment]
That’s a known error :)

Please see #8

**Comment by ollieSk8** [comment]
@davidnagli thx your patience
