### ISSUE TITLE
Reason ML inclusion fails to build

### ISSUE THREAD

**Issue by t-hart** [parcel-bundler/parcel#1972]
# 🐛 bug report

I tried adding some Reason files to an existing project built with parcel and followed the documentation as close as I could, but when running `parcel index.html` (which is the entrypoint), I get an error and the build fails.

## 🎛 Configuration (.babelrc, package.json, cli command)
bsconfig.json
```js
{
    "name": "whatever",
    "reason": {
        "react-jsx": 2
    },
    "license": "MIT",
    "sources": {
        "dir": "src",
        "subdirs": true
    },
    "package-specs": {
        "module": "commonjs",
        "in-source": true
    },
    "suffix": ".bs.js",
    "bs-dependencies": [
        "reason-react"
    ],
    "warnings": {
        "error": "+101"
    },
    "namespace": true,
    "refmt": 3
}
```

package.json
```js
{
  "name": "pg6200_01",
  "version": "1.0.0",
  "description": "\"Coursework for graphics programming\"",
  "scripts": {
    "dev": "./node_modules/.bin/parcel src/index.html --no-cache",
    "build": "./node_modules/.bin/parcel build src/index.html --public-url=\"./\""
  },
  "private": true,
  "author": "Thomas Hartmann <thomas.o.hartmann@gmail.com>",
  "license": "MIT",
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "gl-matrix": "^2.7.1",
    "react": "^16.4.2",
    "react-dom": "^16.4.2"
  },
  "devDependencies": {
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "bs-platform": "^4.0.5",
    "bsb-js": "^1.1.7",
    "glslify-bundle": "^5.0.0",
    "glslify-deps": "^1.3.1",
    "parcel": "^1.9.7",
    "typescript": "^3.0.3"
  }
} 
```

.babelrc:
```js
{
    "plugins": ["transform-object-rest-spread"]
}
```

CLI commands tested:
```sh
./node_modules/.bin/parcel src/index.html --no-cache
```

```sh
"./node_modules/.bin/parcel build src/index.html --public-url=\"./\""
```

Reason file:
```re
Js.log("Hello from Reason");
```

## 🤔 Expected Behavior

The project shoud build and output "Hello from Reason" to the console.

## 😯 Current Behavior

The command errors and print to the console, telling me to link a global install if I have it.
However, I do not have it installed globally (I did, but got the same issue and then uninstalled it) and would rather use the local version.

When running `yarn exec bsb -make-world` it works as expected, no issues, but when trying to run parcel it fails to pick up on the installation.

Errors:

Terminal:
```
🚨  File "bsconfig.json", line 1
Error: package bs-platform is not found
It's the basic, required package. If you have it installed globally,
Please run `npm link bs-platform` to make it available
```

Appears if I try and import .re files while the dev server is running
```
🚨  Unknown error
    at Object.jsonToError (/Users/Thomas/MEGA/Westerdals/Spillprogrammering/2018-2019/PG6200/project/node_modules/parcel/src/workerfarm/errorUtils.js:15:15)
    at Worker.receive (/Users/Thomas/MEGA/Westerdals/Spillprogrammering/2018-2019/PG6200/project/node_modules/parcel/src/workerfarm/Worker.js:149:32)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

This appears in the browser console.
```
[parcel] 🚨  Unknown error
    at Object.jsonToError (/Users/Thomas/MEGA/Westerdals/Spillprogrammering/2018-2019/PG6200/project/node_modules/parcel/src/workerfarm/errorUtils.js:15:15)
    at Worker.receive (/Users/Thomas/MEGA/Westerdals/Spillprogrammering/2018-2019/PG6200/project/node_modules/parcel/src/workerfarm/Worker.js:149:32)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) src.bd8fcd79.js:13806:7
parcelRequire<["../node_modules/parcel/src/builtins/hmr-runtime.js"]</ws.onmessage
http://localhost:1234/src.bd8fcd79.js:13806:7
(Async: EventHandlerNonNull) parcelRequire<["../node_modules/parcel/src/builtins/hmr-runtime.js"]<
http://localhost:1234/src.bd8fcd79.js:13775:3
newRequire
http://localhost:1234/src.bd8fcd79.js:48:7
parcelRequire<
http://localhost:1234/src.bd8fcd79.js:80:5
<anonymous>
http://localhost:1234/src.bd8fcd79.js:10:18
```

## 💁 Possible Solution

Sorry 🤷‍♂️ 

## 🔦 Context

I'm trying to add a frontend to a project I'm doing as part of one of my university modules and thought I'd finally give Reason a go. Taking one step at a time, I thought I'd start with simple printing to the console.

To be honest, I assume that it's an error with my configuration somewhere, but as per the description, something isn't working as I expected, so I filed it as a bug. Feel free to demote it to a question if that is more appropriate.

## 💻 Code Sample

HTML:
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Whatever</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
</body>

<script src="./ui/Index.re"></script>
</html>
```
ui/Index.re:
```re
Js.log("Hello from Reason");
```

Repo: https://github.com/t-hart/pg6200_webgl/tree/ui

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             |10.4.0
| npm/Yarn         |6.1.0/1.7.0
| Operating System |macOS High Sierra 10.13.6

**Comment by t-hart** [comment]
So on further inspection, it seems I had not added `reason-react` as a dependency in my `package.json`, and even if I wasn't using it at all in any of my source files, adding that back in seems to have made things work--I'm assuming because it was referenced in `bsconfig.json`. Anyway, I'll be closing this issue now. Thanks!
