### ISSUE TITLE
Parcel errors with native modules

### ISSUE THREAD

**Issue by Mstrodl** [parcel-bundler/parcel#2042]
# 🐛 bug report

Not sure if this is intended or not, but when require()-ing a native module wrapped in a try { ... } catch { ... } block, parcel fails the build.
This usually works in parcel if it can't find the module (e.g. `try {electron = require("electron")} catch(err) {}`) but not in this case.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "plugins": [
        ["transform-runtime",
        {
            "polyfill": false,
            "regenerator": true
        }]
    ]
}
```

## 🤔 Expected Behavior

Parcel should swallow the error when it's wrapped around a `try { ... } catch { ... }` block

## 😯 Current Behavior

Parcel fails the whole build with `/node_modules/node-sass/lib/index.js: don't know how to turn this value into a node`

```
🚨  /home/heatingdevice/projects/myproject/node_modules/node-sass/lib/index.js: don't know how to turn this value into a node
    at Object.valueToNode (/home/heatingdevice/projects/myproject/node_modules/babel-types/lib/converters.js:349:9)
    at MemberExpression (/home/heatingdevice/projects/myproject/node_modules/parcel/src/visitors/env.js:10:25)
    at c (/home/heatingdevice/projects/myproject/node_modules/babylon-walk/lib/index.js:54:9)
    at c (/home/heatingdevice/projects/myproject/node_modules/babylon-walk/lib/index.js:91:9)
    at c (/home/heatingdevice/projects/myproject/node_modules/babylon-walk/lib/index.js:91:9)
    at c (/home/heatingdevice/projects/myproject/node_modules/babylon-walk/lib/index.js:88:11)
   at c (/home/heatingdevice/projects/myproject/node_modules/babylon-walk/lib/index.js:91:9)
    at Object.simple (/home/heatingdevice/projects/myproject/node_modules/babylon-walk/lib/index.js:113:5)
```

## 💁 Possible Solution

Maybe even just ignoring all code wrapped in a `if(!process.platform)` block would work?

## 🔦 Context

My code is intended to run in electron *and* the browser (I'm not using parcel with electron, just the browser). My code needs to compile sass, so when on electron it uses `node-sass` for better performance and when it's unavailable, uses `sass.js` (I would also be fine with only supporting css in the browser).

## 💻 Code Sample

```js
try {
    require("node-sass");
} catch(err) {}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.10.0
| npm/Yarn         | Yarn 1.7.0
| Operating System | Arch Linux

**Comment by DeMoorJasper** [comment]
Not sure if this is a bug or not, a require in a try catch is optional, but it can resolve node-sass, it just doesn't know how to handle it. Parcel is unable to handle native modules so it might be expected behaviour.

Haven't debugged it yet, but it's def trying to bundle it if it can resolve it.

**Comment by aminya** [comment]
I cannot use Parcel for the packages that require `.node` files. I get this error saying that there is no transformer for `.node` files.
