### ISSUE TITLE
Can't build project using 1.10.0-beta.1

### ISSUE THREAD

**Issue by scrossan-crown** [parcel-bundler/parcel#2052]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
.babelrc
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ]
}
```

## 🤔 Expected Behavior

Should build my app into production code (which it did previous to the beta version)

## 😯 Current Behavior

```
🚨  /app/node_modules/react-toastify/dist/ReactToastify.css:undefined:undefined: Cannot find module 'browserslist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/app/node_modules/postcss-minify-params/dist/index.js:7:21)
    at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

## 🔦 Context

Command run `npx parcel build main.tsx -d public/js`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.0-beta.1
| Node             |  10.0.0
| npm/Yarn         | 6.2.0
| Operating System | Linux / Node:1.0.0 Docker container

**Comment by scrossan-crown** [comment]
Installing `browserslist` package manually fixed the issue

**Comment by scrossan-crown** [comment]
After getting the project to build i get the following error in the console that wasn't there previously 
```
hoist-non-react-statics.cjs.js:31 Uncaught Error: Cannot find module 'MOM9'
    at u (hoist-non-react-statics.cjs.js:31)
    at u (account.8730b2f1.js:1)
    at p (account.8730b2f1.js:1)
    at Object.parcelRequire.vRc9.@babel/runtime/helpers/interopRequireDefault (AttachMoney.js:3)
    at u (account.8730b2f1.js:1)
    at p (account.8730b2f1.js:1)
    at Object.parcelRequire.8I/B.@babel/runtime/helpers/classCallCheck (account.tsx:15)
    at u (account.8730b2f1.js:1)
    at parcelRequire.vRc9.@babel/runtime/helpers/interopRequireDefault (account.8730b2f1.js:1)
    at account.8730b2f1.js:1
```

**Comment by scrossan-crown** [comment]
Just as a note it's working perfectly in development

**Comment by DeMoorJasper** [comment]
Please try 1.10.1

**Comment by scrossan-crown** [comment]
I've tired 1.10.1 and it's not having the above error but is now having a completely different error. 
```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**Comment by DeMoorJasper** [comment]
Run parcel 1.10.1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
@scrossan-crown well that looks like a react error. If that also happens in a dev build it’s a bug in your code

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by scrossan-crown** [comment]
@DeMoorJasper the issue is that there is no error's in dev build but the production build is broken as of `1.10.0-beta.1`

**Comment by DeMoorJasper** [comment]
Not sure if I’ll be able to do anything without a minimal reprodcuable example. It seems to be a minification issue but we didn’t change any minification in 1.10 afaik

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by scrossan-crown** [comment]
Ok, I’ll have a play around and try to get a reproducible example up and running.

Scott Crossan
Developer
t: 01617621819
s.crossan@crownoil.co.uk<mailto:s.crossan@crownoil.co.uk>
www.crownoil.co.uk<http://www.crownoil.co.uk/>

[Description: cid:BBDC52DE-BFB3-4947-AEC4-D900A598E80F]

**Comment by scrossan-crown** [comment]
I think I've found the error, it was a case of the localStorage containing some incorrect data. Thanks for your suggestions
