### ISSUE TITLE
`No Entries Found` after upgrade to version 1.10.1

### ISSUE THREAD

**Issue by brachi-wernick** [parcel-bundler/parcel#2095]
# 🐛 bug report

after upgrade to latest version 1.10.1
I get this error on build, working well in previous versions 

```
parcel build index.html



🚨  No entries found.

    at /home/jenkins/workspace/l-frontend-apps_cosmosInfra-5PK3F7ZCMYBJAZWXZ7KSKAUDWNPU3UUR24E22YETHNP5H2FFHHKQ/packages/md-cosmos/node_modules/parcel-bundler/lib/Bundler.js:291:19

    at next (native)

    at asyncGeneratorStep (/home/jenkins/workspace/l-frontend-apps_cosmosInfra-5PK3F7ZCMYBJAZWXZ7KSKAUDWNPU3UUR24E22YETHNP5H2FFHHKQ/packages/md-cosmos/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)

    at _next (/home/jenkins/workspace/l-frontend-apps_cosmosInfra-5PK3F7ZCMYBJAZWXZ7KSKAUDWNPU3UUR24E22YETHNP5H2FFHHKQ/packages/md-cosmos/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)



    at Promise.all.then.arr (/home/jenkins/workspace/l-frontend-apps_cosmosInfra-5PK3F7ZCMYBJAZWXZ7KSKAUDWNPU3UUR24E22YETHNP5H2FFHHKQ/node_modules/execa/index.js:236:11)

    at process._tickCallback (internal/process/next_tick.js:103:7)

```

**Comment by DeMoorJasper** [comment]
that's strange a defined entrypoint should be able to get resolved, did you try `./index.html`?

**Comment by popugang** [comment]
cross-env NODE_ENV=production parcel build './src/index.html

try it

**Comment by devongovett** [comment]
Is anyone still having this issue?

**Comment by radar** [comment]
Yes, I am still seeing this issue -- along with @nickrm97. I have this application which reproduces the issue: https://github.com/radar/parcel-bundler-repro-2095.

We can both reproduce this issue on our machines by running this command:

```
yarn parcel
```

Changing the `devDependencies` line for `parcel-bundler` down to `1.9.7` fixes this issue.

**Comment by mischnic** [comment]
@radar Did you mean `parcel dev`? That invokes `parcel src/index.html`, but that file doesn't exist.

I have no idea why parcel 1.9.7 prints no error, but actually opening `localhost:1234` results in a 404 error.

**Comment by DeMoorJasper** [comment]
@mischnic the `no entries found` error has been added in a recent version.
This because the no error and still having a successful build as you describe with Parcel 1.9.7 is quite strange as it actually just runs parcel without doing anything

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jeff-hykin** [comment]
I'm also getting this issue. I'm not sure if its an identical cause, but I think I found the source of it.<br>
Works: `/Users/jeffhykin/FindLater-no-sync/quik-stack/computer-generated-code/.website.html` <br>
Doesn't: `/Users/jeffhykin/Find Later (No Sync)/quik-stack/computer-generated-code/.website.html` <br>
Both work on 1.9.7, both fail on 1.10.3 and 1.11.0. Escaping the spaces and/or ()'s doesn't help.<br>
<br>
The source seems to be comping from `src/Bundler.js`, in the `normalizeEntries` function on the last line:
```
return entryFiles
      .reduce((p, m) => p.concat(glob.sync(m)), [])
      .map(f => Path.resolve(f));
```
The `glob.sync` is getting rid of valid paths. It's being imported from `fast-glob`, and it looks like it could be caused by an upstream bug: https://github.com/mrmlnc/fast-glob/issues/138

**Comment by humphd** [comment]
I'm hitting this today with an upgrade from parcel `1.11.0` to `1.12.3`.  No meaningful error, just fails with:

```
parcel build --detailed-report src/nohost-sw.js

⠋ Building...
🚨  No entries found.
    at Bundler.bundle (/Users/humphd/repos/nohost/node_modules/parcel/src/Bundler.js:276:17)
    at <anonymous>
```

**Comment by mischnic** [comment]
@humphd
`--detailed-report` can now take an option to specify the depth. This isn't yet updated in the docs:
 https://github.com/parcel-bundler/website/issues/413

PS: That's a *very* interesting project!

**Comment by humphd** [comment]
@mischnic I think you solved it.  By moving `--detailed-report` to the end of my command line args, I think it is now not consuming the entry point filename as a depth.  It works with latest parcel!

```diff
diff --git a/package.json b/package.json
index c647bea..0a528fe 100644
--- a/package.json
+++ b/package.json
@@ -14,7 +14,7 @@
     "eslint": "eslint src example",
     "test": "npm run eslint",
     "build-example": "copyfiles -u 1 example/index* dist",
-    "build-sw": "parcel build --detailed-report src/nohost-sw.js",
+    "build-sw": "parcel build src/nohost-sw.js --detailed-report",
     "prebuild": "npm run build-example",
     "build": "npm run build-sw",
     "predev": "npm run build",
```

Thanks re: nohost!  I'm using it to build a full computer with shared fs in the browser, https://github.com/humphd/browser-shell.  Almost done, another week or so and I'll tweet about it.

**Comment by mischnic** [comment]
This just happened to me when running `yarn parcel build index.html` inside a subfolder "browser" of the main directory with package.json and node_modules.
Parcel resolved `index.html` from the root instead of pwd.

**Comment by DanielOX** [comment]
**./node_modules/.bin/parcel build ./src/index.html** fixed the issue notice the **./** before **_src_**

**Comment by jeff-hykin** [comment]
still a problem @stalebot 
```
parcel --version
1.12.4
```
![Screen Shot 2020-01-17 at 10 44 49 AM](https://user-images.githubusercontent.com/17692058/72629680-6a144b00-3916-11ea-96cd-7c9071266bc6.png)

**Comment by ocundale** [comment]
Still seeing this too in `1.12.4`
<img width="813" alt="Screenshot 2020-03-14 at 10 49 38" src="https://user-images.githubusercontent.com/1638138/76680587-a5af5680-65e1-11ea-8304-6ac1c18df74a.png">

**Comment by rahul-kulkarni105** [comment]
@ocundale I had the same issue today, i kept trying in vscode. So for the sake of it, switched to iterm2 and it worked there.
`
parcel index.html
`
working fine now in 1.12.4

<img width="424" alt="Screen Shot 2020-03-24 at 21 32 31" src="https://user-images.githubusercontent.com/19542611/77495563-fa8b7200-6e16-11ea-891a-334163f9a943.png">

**Comment by Oumaima-abm** [comment]
> This just happened to me when running `yarn parcel build index.html` inside a subfolder "browser" of the main directory with package.json and node_modules.
> Parcel resolved `index.html` from the root instead of pwd.

and how did you resolve that ? i'm facing the same issue.

**Comment by johnrmremi** [comment]
This happens when the entry file you specified (index.html in your case) doesn't exist.

**Comment by DeMoorJasper** [comment]
We're released v2 rc soonish so we no longer are planning to update v1
