### ISSUE TITLE
Elm: importing

### ISSUE THREAD

**Issue by domenkozar** [parcel-bundler/parcel#2147]
# 🐛 bug report

In file B, importing a new file A that doesn't initially typecheck doesn't trigger reloads on subsequent reloads.

## 🎛 Configuration (.babelrc, package.json, cli command)

Barebones elm project.

## 🤔 Expected Behavior

When file A is saved, parcel reloads.

## 😯 Current Behavior

Nothing happens when saving file A, one needs to save file B.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Operating System | Linux

**Comment by domenkozar** [comment]
Got this again today. `findAllDependencies('./src/Main.elm').then(function(deps) { console.log(deps); });` did return the offending file. Restarting parcel fixes the issue.

@DeMoorJasper any tips how to debug how parcel picks up file changes?

**Comment by domenkozar** [comment]
The problem might be that there is an error:

```
    at ChildProcess.<anonymous> (/home/ielectric/dev/cachix/cachix-server/frontend/node_modules/node-elm-compiler/index.js:149:27)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by MattCheely** [comment]
I did some research on this and it seems the issue is that when the compile process throws an error, all processing of the asset halts, and any collected information such as dependencies is thrown away. At a high level, this happens in[ Bundler.js on line 556](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Bundler.js#L556), and dependencies aren't watched until [line 578](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Bundler.js#L578).

There are a few ways to potentially fix this, but I think the ideal situation would be to let `Asset.generate` return something that indicates that the asset is in error, while still retaining other data. Maybe something as simple as `{error: '...'}`. One nice thing about that would be that it would make errors more of a first-class part of the pipeline and open the door for things like customizing the error display in nice ways. That could be pretty interesting with tools like Elm and Rust that produce really nice error information.

I'd be happy to try tackling this problem, but I want to make sure I'm doing work that makes sense in the context of the larger project. @DeMoorJasper  or @devongovett - What's the best way to approach this? I can just start slinging code and open a PR, but if there's a particular approach you think would be best, I'm happy to go that route.

**Comment by sklirg** [comment]
Hi there. Sorry for commenting on this closed issue, but I'm not sure if I should raise a new issue since this feature isn't released yet.

I still experience this bug even after trying the fork mentioned in #2475 (@domenkozar: Did you do anything specific to make it work? Could you look at the example repo and see if you're able to reproduce it too?).

Steps to reproduce:

1) Edit text in `Feat.elm`, which is imported by `Main.elm`. Save Feat.elm
2) Expect hot reload.
3) No hot reload
4) Save Main.elm
5) Hot reload happens.

See this [example repo](https://github.com/sklirg/parcel-elm-hmr-repro) and this [demo video](https://imgur.com/GFGLsKK).

Any suggestions on what I can do to solve this problem?

Thanks a bunch!

**Comment by domenkozar** [comment]
How did you install the fork? To valifate you're using correct ckde, you should not see duplicate elm errors in the logs.

**Comment by domenkozar** [comment]
Ah you're missing `module Main exposing (main)`  on top of your `Main.elm`.

**Comment by domenkozar** [comment]
This is now fixed in 1.12 (although changelog doesn't mention that).
