### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by neotechmonk** [parcel-bundler/parcel#2172]
# 🐛 bug report

When building with parceljs where node-fetch is required, the below error is thrown when running the compiled js

## 🎛 Configuration (.babelrc, package.json, cli command)
{
  "presets": ["env"]
}
## 🤔 Expected Behavior

run js the built js file

## 😯 Current Behavior
Reference error is thrown 
module.exports = exports = self.fetch; // Needed for TypeScript and Webpack.
                           ^

ReferenceError: self is not defined
    at Object.parcelRequire.../node_modules/node-fetch/browser.js (C:\dev\sandbox\movie-app-parcel\dist\tmdb.js:110:28)
    at newRequire (C:\dev\sandbox\movie-app-parcel\dist\tmdb.js:49:24)
    at localRequire (C:\dev\sandbox\movie-app-parcel\dist\tmdb.js:55:14)
    at Object.parcelRequire.tmdb.js.node-fetch (C:\dev\sandbox\movie-app-parcel\dist\tmdb.js:70864:16)
    at newRequire (C:\dev\sandbox\movie-app-parcel\dist\tmdb.js:49:24)
    at parcelRequire.../node_modules/node-fetch/browser.js.module.exports.exports (C:\dev\sandbox\movie-app-parcel\dist\tmdb.js:81:5)
    at Object.<anonymous> (C:\dev\sandbox\movie-app-parcel\dist\tmdb.js:107:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

## 💁 Possible Solution

Not sure
## 🔦 Context

fetching data from themoviedb.org

## 💻 Code Sample

var fetch = require("node-fetch");

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Latest
| Node             |8.11.4
| npm        |
| Operating System | Windows

**Comment by szhu** [comment]
I ran into this issue too. I was able to fix it -- see solution below.

Here's my setup:
- I have a React app that I want to both client-side and server-side render.
- My build process involves these steps:
  1. `parcel build index.html`
  2. I have a short `build.tsx` script that basically runs `ReactDOMServer.renderToString(<App>)` and inserts the generated HTML into `dist/index.html`.
  3. I compile this script using `parcel build --target node build.tsx`
  4. `node dist/build.js`

The problem is that the React app uses the `semiotic` library, which has a dependency references `self`:
```
$ node dist/build.js
/path/to/repo/dist/build.js:1
parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"A0Ow":[function(require,module,exports) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^

ReferenceError: self is not defined
    at Object.<anonymous> (/path/to/repo/node_modules/roughjs-es5/lib/generator.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/path/to/repo/node_modules/semiotic-mark/lib/Mark.js:23:18)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

Note: It is similar to this issue I found (but this is not me): https://spectrum.chat/next-js/general/porting-from-create-react-app-semiotic-js-fails-self-is-not-defined~d8752c31-54c9-4d71-af45-2ad1b35649fb

---

I was able to fix this issue by adding the following line at the top of my `build.tsx`:

```tsx
(global as any).self = global;
```

**Comment by salsager** [comment]
> I ran into this issue too. I was able to fix it -- see solution below.
> 
> Here's my setup:
> 
> * I have a React app that I want to both client-side and server-side render.
> * My build process involves these steps:
>   
>   1. `parcel build index.html`
>   2. I have a short `build.tsx` script that basically runs `ReactDOMServer.renderToString(<App>)` and inserts the generated HTML into `dist/index.html`.
>   3. I compile this script using `parcel build --target node build.tsx`
>   4. `node dist/build.js`
> 
> The problem is that the React app uses the `semiotic` library, which has a dependency references `self`:
> 
> ```
> $ node dist/build.js
> /path/to/repo/dist/build.js:1
> parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"A0Ow":[function(require,module,exports) {
>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ^
> 
> ReferenceError: self is not defined
>     at Object.<anonymous> (/path/to/repo/node_modules/roughjs-es5/lib/generator.js:28:1)
>     at Module._compile (internal/modules/cjs/loader.js:1147:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
>     at Module.load (internal/modules/cjs/loader.js:996:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
>     at Module.require (internal/modules/cjs/loader.js:1036:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/path/to/repo/node_modules/semiotic-mark/lib/Mark.js:23:18)
>     at Module._compile (internal/modules/cjs/loader.js:1147:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
> ```
> 
> Note: It is similar to this issue I found (but this is not me): https://spectrum.chat/next-js/general/porting-from-create-react-app-semiotic-js-fails-self-is-not-defined~d8752c31-54c9-4d71-af45-2ad1b35649fb
> 
> I was able to fix this issue by adding the following line at the top of my `build.tsx`:
> 
> ```tsx
> (global as any).self = global;
> ```

@szhu i followed your approach but it breaks after the build. 
what worked for me is that i used [next.js dynamic import ](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) without `SSR` to make it run in the browser. 
check my reply here https://github.com/nteract/semiotic/issues/525#issuecomment-823505606
