### ISSUE TITLE
Fails to bundle Polymer 2 with certain browserslist values

### ISSUE THREAD

**Issue by Lange** [parcel-bundler/parcel#2242]
# 🐛 bug report

Attempting to bundle a Polymer 2 project results in a `Maximum call stack size exceeded` error being thrown, but only with certain values of `browserslist` in `package.json`.

## 🎛 Configuration (.babelrc, package.json, cli command)

There are many settings which do and do not invoke this crash, but here are two easy-to-test examples:

### Causes the crash
```js
{
  "browserslist": "since 2018"
}
```

### Does not cause a crash
```js
{
  "browserslist": "since 2017"
}
```

## 🤔 Expected Behavior

Parcel should be able to bundle Polymer 2 projects without throwing unhandled errors on certain `browserslist` settings.

## 😯 Current Behavior

Parcel crashes when bundling Polymer 2 projects with certain `browserslist` values:

```
> parcel-polymer-repro@1.0.0 build C:\Users\vanca\Desktop\parcel-polymer-repro
> parcel build src/index.html --out-dir dist --public-url ./

×  C:\Users\vanca\Desktop\parcel-polymer-repro\bower_components\polymer\lib\utils\html-tag.html: Maximum call stack size exceeded
    at Array.sort (native)
    at objectHash (C:\Users\vanca\Desktop\parcel-polymer-repro\node_modules\parcel-bundler\src\utils\objectHash.js:5:39)
    at objectHash (C:\Users\vanca\Desktop\parcel-polymer-repro\node_modules\parcel-bundler\src\utils\objectHash.js:8:25)
    at objectHash (C:\Users\vanca\Desktop\parcel-polymer-repro\node_modules\parcel-bundler\src\utils\objectHash.js:8:25)
    at objectHash (C:\Users\vanca\Desktop\parcel-polymer-repro\node_modules\parcel-bundler\src\utils\objectHash.js:8:25)
    at objectHash (C:\Users\vanca\Desktop\parcel-polymer-repro\node_modules\parcel-bundler\src\utils\objectHash.js:8:25)
    at objectHash (C:\Users\vanca\Desktop\parcel-polymer-repro\node_modules\parcel-bundler\src\utils\objectHash.js:8:25)
    at objectHash (C:\Users\vanca\Desktop\parcel-polymer-repro\node_modules\parcel-bundler\src\utils\objectHash.js:8:25)
    at objectHash (C:\Users\vanca\Desktop\parcel-polymer-repro\node_modules\parcel-bundler\src\utils\objectHash.js:8:25)
    at objectHash (C:\Users\vanca\Desktop\parcel-polymer-repro\node_modules\parcel-bundler\src\utils\objectHash.js:8:25)
```

## 💁 Possible Solution

Unknown.

## 🔦 Context

For better or worse, I currently am responsible for many projects built with Polymer 2. I'm trying to migrate them to TypeScript, which means I need a build step, which means I want to use Parcel (since it is the simplest option available).

## 💻 Code Sample

A minimal repro with a README can be found here: https://github.com/Lange/parcel-polymer-repro

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 8.10.0
| npm/Yarn         | 6.4.1
| Operating System | Win 10 x64 Pro

**Comment by Hoishin** [comment]
Looks like `this.generated` property in `Asset.js` has circular structure when it tries to hash the object.
