### ISSUE TITLE
Scope Hoisting bug with libphonenumber-js

### ISSUE THREAD

**Issue by acourdavault** [parcel-bundler/parcel#2284]
# 🐛 bug report

I could not build a code using libphonenumber-js library, which works well without --experimental-scope-hoisting.

## 🎛 Configuration (.babelrc, package.json, cli command)
I have NO configuration at all, only CLI, see below

```json
{
  "name": "components",
  "version": "1.0.0",
  "description": "components for stel app webpages",
  "main": "none",
  "devDependencies": {
    "cssnano": "^4.0.3",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "reactify": "^1.1.1"
  },
  "scripts": {
    "prebuild": "npm i -g parcel && npm i",
    "bundlePList": "parcel build -o patientlist.js -d ../../asset/components/ --no-source-maps --no-cache ./patientlist.js",
    "bundleGAtes": "parcel build -o gates.js -d ../../asset/components/ --no-source-maps --no-cache ./gates.js",
    "bundlePDetails": "parcel build -o patientdetails.js -d ../../asset/components/ --no-source-maps ./patientdetails.js",
    "bundle": "npm run bundlePDetails && npm run bundlePList && parcel build -o profile.js -d ../../asset/components/ --no-source-maps --no-cache ./profile.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "aesjs": "^1.0.0",
    "babel-polyfill": "^6.26.0",
    "chart.js": "^2.7.2",
    "crypto-js": "^3.1.9-1",
    "downloadjs": "^1.4.7",
    "formik": "^0.11.11",
    "isomorphic-fetch": "^2.2.1",
    "libphonenumber-js": "^1.2.15",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "pako": "^1.0.6",
    "postcss-modules": "^1.1.0",
    "react-chartjs-2": "^2.7.4",
    "react-datepicker": "^1.7.0",
    "react-table": "^6.8.6",
    "react-virtualized-select": "^3.1.3",
    "reactjs-popup": "^1.1.4",
    "yup": "^0.25.1"
  }
}

```

## 🤔 Expected Behavior

i expected the build to go through

## 😯 Current Behavior

cannot build
```batch
PS D:\wc\stel\stel_dev\stel-django\stel\stelapp\components> parcel build -o .\patientSettingsPage.js -d ../../asset/components/ --no-source-maps  --experimental-scope-hoisting .\patientSettingsPage.js
×  node_modules\libphonenumber-js\es6\findPhoneNumbers.js does not export '$HkE9$export$searchPhoneNumbers'
    at replaceExportNode (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\parcel-bundler\src\scope-hoisting\concat.js:54:13)
    at ReferencedIdentifier (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\parcel-bundler\src\scope-hoisting\concat.js:317:20)
    at newFn (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\visitors.js:230:17)
    at NodePath._call (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (C:\Users\adrie\AppData\Local\Yarn\Data\global\node_modules\@babel\traverse\lib\index.js:94:17)```
```

## 💁 Possible Solution

maybe related to a non ES6 compliant implementation of libphonenumber-js

## 🔦 Context

was trying to reduce the size of an existing page

## 💻 Code Sample

I used this import 
```js
import { parseNumber, AsYouType } from "libphonenumber-js";
```

## 🌍 Your Environment

windows 10, yarn install parcel bundler updated 1.10.3

**Comment by mischnic** [comment]
This really is a parcel bug, minimum example: (renaming `searchPhoneNumbers` fixed it!?)

```js
// index.js
import { searchPhoneNumbers } from "./lib.js";

console.log(searchPhoneNumbers);
```

```js
// lib.js
export { searchPhoneNumbersCustom } from './lib2.js'
```

```js
// lib2.js
export function searchPhoneNumbers() {}
```

```
parcel build index.js --no-cache --experimental-scope-hoisting
🚨  lib.js does not export 'searchPhoneNumbers'
    at replaceExportNode (.../parcel/packages/core/parcel-bundler/src/scope-hoisting/concat.js:54:13)
    at ReferencedIdentifier (.../parcel/packages/core/parcel-bundler/src/scope-hoisting/concat.js:317:20)
    at newFn (.../parcel/node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call (.../parcel/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (.../parcel/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (.../parcel/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (.../parcel/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (.../parcel/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (.../parcel/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (.../parcel/node_modules/@babel/traverse/lib/index.js:94:17)
```

Also, is there a scope hoisting test for the `export { x as y } from "..."` syntax? Couldn't find one.

**Comment by erikreedstrom** [comment]
This is an issue it seems with any component only referenced in the main code path through a reexport. 

For instance, the `FormField` component of Grommet v2 will fail with:

```js
$ parcel build public/index.html --experimental-scope-hoisting --detailed-report --no-source-maps
🚨  ../node_modules/grommet/es6/components/FormField/FormField.js does not export 'FormField'
    at replaceExportNode (.../node_modules/parcel-bundler/src/scope-hoisting/concat.js:48:13)
    at ReferencedIdentifier (.../node_modules/parcel-bundler/src/scope-hoisting/concat.js:280:20)
    at newFn (.../node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call (.../node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (.../node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (.../node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (.../node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (.../node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (.../node_modules/@babel/traverse/lib/index.js:94:17)
```

where `FormField/FormField.js`
```js
export { FormFieldWrapper as FormField };
```

and `FormField/index.js`
```js
export { FormField } from './FormField';
```

This fails when the the `FormField` is defined _only_ in a module that reexports. For instance,

`components/molecules/FormField.js`
```js
import { Box, Text, FormField } from 'grommet';
...
export { StyledFormField as FormField };
```

`components/molecules/index.js`
```js
export * from './FormField';
```

Thus, it is possible to work around by adding an import statement to the main code path, `index.js` for instance. The error will be resolved, but this seems crazy hacky.

**Comment by mischnic** [comment]
This is closely related to https://github.com/babel/babel/issues/9266, but parcel doesn't use babel's renaming facility so fixing it in babel doesn't help parcel.
