### ISSUE TITLE
🐛 Parcel fails with typescript files above root directory

### ISSUE THREAD

**Issue by maun** [parcel-bundler/parcel#2291]
🐛 Bug report

Parcel fails with typescript files above root directory. It does work with .js files, also with the .ts file in the root folder. Tested on macOS, Windows, and Windows WSL ubuntu.

### 🎛 Configuration (.babelrc, package.json, cli command)

Create the following files and folders:
test\hello.ts
```js
console.log("hello")
```
test\app\index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="../hello.ts"></script>
  </head>
  <body>
  </body>
</html>
```

test\app\package.json
```js
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "dependencies": {},
  "devDependencies": {
    "parcel-bundler": "^1.10.3",
    "typescript": "^3.1.6"
  },
  "scripts": {
    "build": "npx parcel build index.html --log-level 4"
  },
  "author": "",
  "license": "ISC"
}

```

### 🤔 Expected Behavior

App should build.

### 😯 Current Behavior
Does not build with the following output:
```
~/d/t/app ❯❯❯ npm run build                                                   ⏎

> app@1.0.0 build /Users/manuel/dev/test/app
> npx parcel build index.html --log-level 4

In file included from ../fsevents.cc:6:
../../nan/nan.h:1064:44: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                           ^
/Users/manuel/.node-gyp/11.1.0/include/node/v8.h:2537:3: note: 'ToString' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/manuel/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after
      field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
2 warnings generated.
[12:34:15 PM]: Building...
[12:34:15 PM]: Building index.html...
[12:34:15 PM]: Building hello.ts...
[12:34:15 PM]: Installing typescript...
npm WARN app No description
npm WARN app No repository field.
npm WARN app No license field.

+ typescript@3.1.6
updated 1 package and audited 1 package in 1.311s
found 0 vulnerabilities

[12:34:17 PM]: 🚨  /Users/manuel/dev/test/hello.ts: Cannot find module 'typescript' from '/Users/manuel/dev/test'
[12:34:17 PM]:     at /Users/manuel/.npm/_npx/4786/lib/node_modules/parcel/node_modules/resolve/lib/async.js:51:31
    at processDirs (/Users/manuel/.npm/_npx/4786/lib/node_modules/parcel/node_modules/resolve/lib/async.js:185:39)
    at ondir (/Users/manuel/.npm/_npx/4786/lib/node_modules/parcel/node_modules/resolve/lib/async.js:200:13)
    at load (/Users/manuel/.npm/_npx/4786/lib/node_modules/parcel/node_modules/resolve/lib/async.js:83:43)
    at onex (/Users/manuel/.npm/_npx/4786/lib/node_modules/parcel/node_modules/resolve/lib/async.js:108:17)
    at /Users/manuel/.npm/_npx/4786/lib/node_modules/parcel/node_modules/resolve/lib/async.js:12:69
    at FSReqCallback.oncomplete (fs.js:161:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.0 build: `npx parcel build index.html --log-level 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/manuel/.npm/_logs/2018-11-17T11_34_20_250Z-debug.log
~/d/t/app ❯❯❯
```

Also parcel tries to install typescript although it is already installed and the package.json file is cleared.
When open in an editor I see the file first look like this:
```
{}
```

and finally like this
```
{
  "devDependencies": {
    "typescript": "^3.1.6"
  }
}
```
but sometimes it also stays empty.

What does work is going one folder up and building from there:
```
npx parcel build app/index.html
...
✨  Built in 2.55s.

dist/hello.890500fb.js     1.08 KB    2.22s
dist/hello.890500fb.map      173 B      2ms
dist/index.html              112 B    288ms
```

### 🔦 Context

My use case is a shared source folder for a client server app. I have the following folder structure:
app/client/package.json
app/server/package.json
app/shared/*.ts

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | v11.1.0
| npm/Yarn         | npm 6.4.1
| Operating System | macOS 10.14.1

**Comment by mattgi** [comment]
I have this same result - the content inside each node_module folder is also cleared out when the package.json is.. this seems to be the cause of the actual file then falling over (as no dependencies exist).

I have the same shared folder setup so can confirm that to be the cause.
