### ISSUE TITLE
Multiple glob patterns not working

### ISSUE THREAD

**Issue by SpectralKH** [parcel-bundler/parcel#2293]
# 🐛 bug report

Using the JS API. Running the following does not ignore the `lib` directory:
```
  const bundler = new Bundler(['src/**/*', '!lib'], {
    outDir: 'build',
    target: 'browser',
    cache: false,
    sourceMaps: true,
    minify: false,
    watch: true,
  }).bundle()
```

I would expect it to work because Parcel has `fast-glob` as a dependency, which supports multiple patterns.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.1.3
| Node             | 11.1.0
| npm         | 6.4.1
| Operating System | macOS 10.13.6

**Comment by devongovett** [comment]
The array you are passing to Bundler is an array of entry points. So parcel is treating `src/**/*` as an entry point, and `!lib` as a separate entry point.

**Comment by SpectralKH** [comment]
@devongovett Ah, that makes sense. The documentation made me think glob entry points were not possible using arrays.

Still, though, this did not solve my issue. Passing multiple globs as one entry point gives me the following error:
```
TypeError: p.replace is not a function
    at normalisePath (/Users/kasper/dev/2018/taskler/node_modules/parcel-bundler/src/utils/glob.js:5:12)
    at Function.exports.glob.sync (/Users/kasper/dev/2018/taskler/node_modules/parcel-bundler/src/utils/glob.js:17:24)
    at entryFiles.reduce (/Users/kasper/dev/2018/taskler/node_modules/parcel-bundler/src/Bundler.js:87:39)
    at Array.reduce (<anonymous>)
    at Bundler.normalizeEntries (/Users/kasper/dev/2018/taskler/node_modules/parcel-bundler/src/Bundler.js:87:8)
    at new Bundler (/Users/kasper/dev/2018/taskler/node_modules/parcel-bundler/src/Bundler.js:32:28)
```

Code:
```
const Bundler = require('parcel-bundler')
new Bundler([['srcx/**/*', '!src/lib']], {outDir:'buildx'}).bundle()
```
