### ISSUE TITLE
Promise rejection handling issue???

### ISSUE THREAD

**Issue by ogomez92** [parcel-bundler/parcel#2336]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug report

### 🎛 Configuration (.babelrc, package.json, cli command)
Cli command

--target='electron'
```js
{
  "your": { "config": "here" }
}
```

### 🤔 Expected Behavior

Build success 

### 😯 Current Behavior

(node:14347) UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/build/deasync.node
 → /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/build/Debug/deasync.node
 → /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/build/Release/deasync.node
 → /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/out/Debug/deasync.node
 → /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/Debug/deasync.node
 → /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/out/Release/deasync.node
 → /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/Release/deasync.node
 → /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/build/default/deasync.node
 → /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/compiled/11.2.0/darwin/x64/deasync.node
    at bindings (/usr/local/lib/node_modules/parcel-bundler/node_modules/bindings/bindings.js:88:9)
    at /usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/usr/local/lib/node_modules/parcel-bundler/node_modules/deasync/index.js:76:2)
    at Module._compile (/usr/local/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/local/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
(node:14347) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14347) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
urimac:beat uri$ open meow.txt
urimac:beat uri$ 

### 💁 Possible Solution

I have not any promise rejection handling problems in my code and it always worked fine before I updated.
### 🔦 Context

Can't build.

I build using the fs module taht's why I use target electron
### 💻 Code Sample

https://code.oriolgomez.com:9900/ogomez92/beatstar.git
### 🌍 Your Environment
MAc OS Mojave, npm, terminal.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Try reinstalling parcel.
