### ISSUE TITLE
fs.readFileSync does not work with --target node

### ISSUE THREAD

**Issue by jsedlacek** [parcel-bundler/parcel#2345]
# 🐛 bug report

I am struggling when using `parcel` with `--target node` if my source contains `fs.ReadFileSync`. When I run the resulting build using `node`, it fails with `Error: ENOENT: no such file or directory`.

## 🎛 Configuration (.babelrc, package.json, cli command)

No babel config.

## 🤔 Expected Behavior

Running the result in `node` reads the file correctly.

## 😯 Current Behavior

Running the result in `node` fails with `Error: ENOENT: no such file or directory`.

```
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/jakub/Code/parcel-node-readfilesync/dist/test.txt'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.parcelRequire.Focm (/Users/jakub/Code/parcel-node-readfilesync/dist/index.js:2:47)
    at u (/Users/jakub/Code/parcel-node-readfilesync/dist/index.js:1:528)
    at parcelRequire.Focm (/Users/jakub/Code/parcel-node-readfilesync/dist/index.js:1:827)
    at Object.<anonymous> (/Users/jakub/Code/parcel-node-readfilesync/dist/index.js:1:1032)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
```

## 💁 Possible Solution

Possible solutions:
- Inline the referenced file using `fs.readFileSync`
- Copy the referenced file into the `dest` folder

## 🔦 Context

- I have a node application, that uses typescript, handlebars etc. I am using custom build script to compile the code. I would like to switch to `parcel`.

- I am using `fs.readFileSync` to read files from node so I am not able to use `parcel`.

## 💻 Code Sample

https://github.com/jsedlacek/parcel-node-readfilesync

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.10.3|
| Node             |10.13.0|
| npm/Yarn         |1.12.3|
| Operating System |macOS 10.14.1|

**Comment by DeMoorJasper** [comment]
When using node parcel ignores readFileSync's completely as it's a node package and can run perfectly fine in the node environment.
