### ISSUE TITLE
parcel-bundler 1.11.0 is missing some modules (parcel-bundler/src/Logger)

### ISSUE THREAD

**Issue by gugurete** [parcel-bundler/parcel#2463]
⚠️  Cannot find module 'parcel-bundler/src/Logger'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/Users/robert/zenyem/folio/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/robert/zenyem/folio/node_modules/parcel-plugin-eslint/index.js:1:78)
    at Module._compile (/Users/robert/zenyem/folio/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by gugurete** [comment]
issue caused by parcel-plugin-eslint
