### ISSUE TITLE
Azure Pipelines: EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by mike-ward** [parcel-bundler/parcel#2543]
# 🐛 bug report

Error raised when using Azure Pipelines for continous deployment (see output below). Is this something Parcel can detect and work around? 

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "js",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest",
    "build-Debug": "npx parcel build app.ts -d ../wwwroot/content --no-minify",
    "build-Release": "npx parcel build app.ts -d ../wwwroot/content --no-cache",
    "build-debug": "npx parcel build app.ts -d ../wwwroot/content --no-minify",
    "build-release": "npx parcel build app.ts -d ../wwwroot/content --no-cache",
    "watch": "npx parcel watch app.ts -d ../wwwroot/content"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/jest": "23.3.12",
    "@types/mithril": "1.1.14",
    "bulma": "0.7.2",
    "glob": "7.1.3",
    "jest": "23.6.0",
    "mithril": "2.0.0-rc.3",
    "mithril-query": "2.5.2",
    "parcel-bundler": "1.11.0",
    "sass": "1.16.0",
    "ts-jest": "23.10.5",
    "typescript": "3.2.2"
  }
}

```

## 😯 Current Behavior

```
2019-01-15T18:00:57.5568179Z   > parcel-bundler@1.11.0 postinstall D:\a\1\s\src\App\js\node_modules\parcel-bundler
2019-01-15T18:00:57.5568339Z   > node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"
2019-01-15T18:00:57.5568935Z   
2019-01-15T18:00:57.7039994Z   ‌Love Parcel? You can now donate to our open collective:‌
2019-01-15T18:00:57.7040840Z    > ‌https://opencollective.com/parcel/donate‌
2019-01-15T18:00:59.0218953Z   npm WARN js@1.0.0 No description
2019-01-15T18:00:59.0220353Z   npm WARN js@1.0.0 No repository field.
2019-01-15T18:00:59.0221132Z   npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
2019-01-15T18:00:59.0221480Z   npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2019-01-15T18:00:59.0221845Z   
2019-01-15T18:00:59.0259405Z   + typescript@3.2.2
2019-01-15T18:00:59.0260041Z   added 1159 packages from 744 contributors and audited 27455 packages in 37.324s
2019-01-15T18:00:59.0266393Z   found 0 vulnerabilities
2019-01-15T18:00:59.0266850Z   
2019-01-15T18:01:08.4628502Z   ΓêÜ  Built in 47.88s.
2019-01-15T18:01:08.4644678Z   
2019-01-15T18:01:08.4664412Z   ..\wwwroot\content\app.map    165.83 KB      41ms
2019-01-15T18:01:08.4664615Z   ..\wwwroot\content\app.css    163.65 KB     6.93s
2019-01-15T18:01:08.4664793Z   ..\wwwroot\content\app.js       56.8 KB    47.80s
2019-01-15T18:01:11.7377277Z   fs.js:1061
2019-01-15T18:01:11.7378517Z     return binding.unlink(pathModule._makeLong(path));
2019-01-15T18:01:11.7378961Z                    ^
2019-01-15T18:01:11.7379395Z   
2019-01-15T18:01:11.7919854Z EXEC : error : EPERM: operation not permitted, unlink 'C:\npm\cache\_npx\4132\node_modules\parcel\node_modules\deasync\bin\win32-x64-node-8\deasync.node' [D:\a\1\s\src\App\App.csproj]
2019-01-15T18:01:11.8154296Z       at Object.fs.unlinkSync (fs.js:1061:18)
2019-01-15T18:01:11.8154370Z       at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:211:13)
2019-01-15T18:01:11.8154629Z       at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:311:28)
2019-01-15T18:01:11.8154715Z       at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:5
2019-01-15T18:01:11.8154792Z       at Array.forEach (<anonymous>)
2019-01-15T18:01:11.8154855Z       at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:341:26)
2019-01-15T18:01:11.8154922Z       at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:334:7)
2019-01-15T18:01:11.8155016Z       at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:209:5)
2019-01-15T18:01:11.8155082Z       at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:311:28)
2019-01-15T18:01:11.8155502Z       at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:5
2019-01-15T18:01:11.8155560Z   npm ERR! code ELIFECYCLE
2019-01-15T18:01:11.8155605Z   npm ERR! errno 1
2019-01-15T18:01:11.8155713Z   npm ERR! js@1.0.0 build-release: `npx parcel build app.ts -d ../wwwroot/content --no-cache`
2019-01-15T18:01:11.8156083Z   npm ERR! Exit status 1
2019-01-15T18:01:11.8156151Z   npm ERR! 
2019-01-15T18:01:11.8156198Z   npm ERR! Failed at the js@1.0.0 build-release script.
2019-01-15T18:01:11.8156255Z   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-01-15T18:01:11.8554463Z   
2019-01-15T18:01:11.8555298Z   npm ERR! A complete log of this run can be found in:
2019-01-15T18:01:11.8555499Z   npm ERR!     C:\npm\cache\_logs\2019-01-15T18_01_11_791Z-debug.log
2019-01-15T18:01:11.8670628Z D:\a\1\s\src\App\App.csproj(117,5): error MSB3073: The command "cd js
2019-01-15T18:01:11.8671429Z D:\a\1\s\src\App\App.csproj(117,5): error MSB3073: npm run build-release" exited with code 1.
2019-01-15T18:01:11.8706042Z 
2019-01-15T18:01:11.8706392Z Build FAILED.
2019-01-15T18:01:11.8706991Z 
2019-01-15T18:01:11.8707765Z EXEC : error : EPERM: operation not permitted, unlink 'C:\npm\cache\_npx\4132\node_modules\parcel\node_modules\deasync\bin\win32-x64-node-8\deasync.node' [D:\a\1\s\src\App\App.csproj]
2019-01-15T18:01:11.8708110Z D:\a\1\s\src\App\App.csproj(117,5): error MSB3073: The command "cd js
2019-01-15T18:01:11.8708490Z D:\a\1\s\src\App\App.csproj(117,5): error MSB3073: npm run build-release" exited with code 1.
2019-01-15T18:01:11.8708771Z     0 Warning(s)
2019-01-15T18:01:11.8708997Z     2 Error(s)
2019-01-15T18:01:11.8709406Z 
2019-01-15T18:01:11.8709688Z Time Elapsed 00:01:54.47
```

## 🌍 Your Environment

Azure

**Comment by DeMoorJasper** [comment]
This is probably a permission error with Azure, you need admin privileges to create symbolic links on windows unfortunately. (you could try running it in a non-windows based pipeline, they're probably cheaper to run as well)

**Comment by DeMoorJasper** [comment]
I think this might be an issue with your setup or azure pipelines, it looks like node fails to unlink the deasync binding. Might be a permission issue or fs in use or something, could be pretty much anything.

**Comment by mike-ward** [comment]
Well, for what is worth, it does work on AppVeyor's windows environment.

**Comment by DeMoorJasper** [comment]
@mike-ward I think it's a permission issue, although if I remember correctly AppVeyor has stricter permissions than Azure.
