### ISSUE TITLE
kotlin test fails when Java is not configured or installed. 

### ISSUE THREAD

**Issue by sainthkh** [parcel-bundler/parcel#2603]
# 🐛 bug report

It's really rare for developers' machine to not have Java. But sometimes it happens. (And actually, mine was one of that rare one.)

Note: It's the issue for #2590. I'm writing it here because I messed that PR up and started again from scratch.  

I'll publish new PR soon. 

## 🎛 Configuration (.babelrc, package.json, cli command)

None

## 🤔 Expected Behavior

Tests pass without any problem. 

## 😯 Current Behavior

Tests fail and show 

```
 1) resolver
       "before all" hook:
     Error: EPERM: operation not permitted, symlink 'D:\parcel\packages\core\parcel-bundler\test\input\resolver\packages\source' -> 'D:\parcel\packages\core\parcel-bundler\test\input\resolver\node_modules\source'
      at symlinkSync (fs.js:905:3)
      at Context.<anonymous> (test\resolver.js:18:5)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

## 💁 Possible Solution

Install Java. Or [add the java.exe path to environment variables](https://www.java.com/en/download/help/path.xml). 

## 🔦 Context

I wanted to contribute to Parcel. So, I forked and cloned the repo and ran test. But it failed. I think showing a message like rust is a better solution. 

## 💻 Code Sample

None.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | 10.15.0 |
| npm/Yarn         | 1.12.3 |
| Operating System | Windows 10 Pro 1803 |

**Comment by outofambit** [comment]
Hi! I just encountered this error on a fresh clone of the repo, on the `master` branch (01174eb6f72cefaccc832d7729056e4727692b0c). Is this considered fixed or still in-progress? Is a documentation change might be needed, too?

**Comment by sainthkh** [comment]
@DeMoorJasper  It seems that recent master merge regresses some test cases.

**Comment by DeMoorJasper** [comment]
@sainthkh I’ll have a look at it in a couple hours

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
@sainthkh Seems like the tests on master are fairly stable?

**Comment by sainthkh** [comment]
Then, I'll check it and open a new PR.

**Comment by sainthkh** [comment]
@outofambit 

I ran tests and there was no problem with kotlin. Can you give us some error messages?

**Comment by outofambit** [comment]
@sainthkh after installing java on my machine, there were no kotlin or java related errors. I tried uninstalling java and running the tests again but wasn't able to reproduce my error. I wonder if only appears if the machine has never had java installed? (That was my case.) Unfortunately I didn't keep the logs of those failures, but one symptom was I would get a Mac OS popup prompting me to install java when I ran the tests.

**Comment by sainthkh** [comment]
Then, we need to wait until someone else has the same problem.

**Comment by samuelgozi** [comment]
I'm having the same issue, but im also working on a PR regarding posthtml, so ignore the errors coming from there.

Here are the errors I get:
```
@parcel/integration-tests:        should support transforming HTML with posthtml:
@parcel/integration-tests:      TypeError: plugin is not a function
@parcel/integration-tests:       at /Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:190:14
@parcel/integration-tests:       at tryCatch (/Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:273:12)
@parcel/integration-tests:       at PostHTML.<anonymous> (/Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:189:15)
@parcel/integration-tests:       at /Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:210:5
@parcel/integration-tests:       at new Promise (<anonymous>)
@parcel/integration-tests:       at PostHTML.process (/Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:209:10)
@parcel/integration-tests:       at Object.transform (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/transforms/posthtml.js:20:44)
@parcel/integration-tests:       at async HTMLAsset.pretransform (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/assets/HTMLAsset.js:202:5)
@parcel/integration-tests:       at async HTMLAsset.process (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Asset.js:214:7)
@parcel/integration-tests:       at async Pipeline.processAsset (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Pipeline.js:46:7)
@parcel/integration-tests:       at async Pipeline.process (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Pipeline.js:24:23)
@parcel/integration-tests:       at async Object.run (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/worker.js:15:12)
@parcel/integration-tests:       at async Bundler.loadAsset (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Bundler.js:577:19)
@parcel/integration-tests:       at async Bundler.processAsset (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Bundler.js:557:5)
@parcel/integration-tests:       at async PromiseQueue._runJob (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/utils/PromiseQueue.js:48:7)
@parcel/integration-tests:   2) html
@parcel/integration-tests:        should add dependencies referenced by plugins:
@parcel/integration-tests:      TypeError: plugin is not a function
@parcel/integration-tests:       at /Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:190:14
@parcel/integration-tests:       at tryCatch (/Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:273:12)
@parcel/integration-tests:       at PostHTML.<anonymous> (/Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:189:15)
@parcel/integration-tests:       at /Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:210:5
@parcel/integration-tests:       at new Promise (<anonymous>)
@parcel/integration-tests:       at PostHTML.process (/Users/myusername/Documents/GitHub/parcel/node_modules/posthtml/lib/index.js:209:10)
@parcel/integration-tests:       at Object.transform (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/transforms/posthtml.js:20:44)
@parcel/integration-tests:       at async HTMLAsset.pretransform (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/assets/HTMLAsset.js:202:5)
@parcel/integration-tests:       at async HTMLAsset.process (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Asset.js:214:7)
@parcel/integration-tests:       at async Pipeline.processAsset (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Pipeline.js:46:7)
@parcel/integration-tests:       at async Pipeline.process (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Pipeline.js:24:23)
@parcel/integration-tests:       at async Object.run (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/worker.js:15:12)
@parcel/integration-tests:       at async Bundler.loadAsset (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Bundler.js:577:19)
@parcel/integration-tests:       at async Bundler.processAsset (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Bundler.js:557:5)
@parcel/integration-tests:       at async PromiseQueue._runJob (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/utils/PromiseQueue.js:48:7)
@parcel/integration-tests:   3) javascript
@parcel/integration-tests:        should auto install babel plugins:
@parcel/integration-tests:      Error: Cannot find module '@babel/plugin-proposal-class-properties' from '/Users/myusername/Documents/GitHub/parcel/packages/core/integration-tests/test/integration/babel-plugin-autoinstall'
@parcel/integration-tests:       at Function.module.exports [as sync] (test/integration/babel-plugin-autoinstall/node_modules/resolve/lib/sync.js:71:15)
@parcel/integration-tests:       at resolveStandardizedName (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
@parcel/integration-tests:       at resolvePlugin (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
@parcel/integration-tests:       at loadPlugin (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
@parcel/integration-tests:       at createDescriptor (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
@parcel/integration-tests:       at /Users/myusername/Documents/GitHub/parcel/packages/core/integration-tests/test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
@parcel/integration-tests:       at Array.map (<anonymous>:null:null)
@parcel/integration-tests:       at createDescriptors (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
@parcel/integration-tests:       at createPluginDescriptors (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
@parcel/integration-tests:       at /Users/myusername/Documents/GitHub/parcel/packages/core/integration-tests/test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/config-descriptors.js:63:49
@parcel/integration-tests:       at cachedFunction (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/caching.js:33:19)
@parcel/integration-tests:       at plugins (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
@parcel/integration-tests:       at mergeChainOpts (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/config-chain.js:319:26)
@parcel/integration-tests:       at /Users/myusername/Documents/GitHub/parcel/packages/core/integration-tests/test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/config-chain.js:283:7
@parcel/integration-tests:       at buildRootChain (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/config-chain.js:68:29)
@parcel/integration-tests:       at loadPrivatePartialConfig (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/partial.js:85:55)
@parcel/integration-tests:       at loadFullConfig (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/config/full.js:43:39)
@parcel/integration-tests:       at Object.transformSync (test/integration/babel-plugin-autoinstall/node_modules/@babel/core/lib/transform.js:41:38)
@parcel/integration-tests:       at babel7 (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/transforms/babel/babel7.js:31:17)
@parcel/integration-tests:       at babelTransform (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/transforms/babel/transform.js:13:5)
@parcel/integration-tests:       at JSAsset.pretransform (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/assets/JSAsset.js:83:5)
@parcel/integration-tests:       at JSAsset.process (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Asset.js:214:7)
@parcel/integration-tests:       at Pipeline.processAsset (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Pipeline.js:46:7)
@parcel/integration-tests:       at Pipeline.process (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Pipeline.js:24:23)
@parcel/integration-tests:       at Object.run (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/worker.js:15:12)
@parcel/integration-tests:       at Bundler.loadAsset (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Bundler.js:577:19)
@parcel/integration-tests:       at Bundler.processAsset (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/Bundler.js:557:5)
@parcel/integration-tests:       at PromiseQueue._runJob (/Users/myusername/Documents/GitHub/parcel/packages/core/parcel-bundler/src/utils/PromiseQueue.js:48:7)
@parcel/integration-tests:
@parcel/integration-tests:   4) javascript
@parcel/integration-tests:        should support optional dependencies in try...catch blocks:
@parcel/integration-tests:       Expected values to be loosely deep-equal:
@parcel/integration-tests: Error: Cannot find module 'optional-dep'
@parcel/integration-tests:     at newRequire (evalmachine.<anonymous>:37:19)
@parcel/integration-tests:     at localRequire (evalmachine.<anonymous>:53:14)
@parcel/integration-tests:     at Object.parcelRequire.index.js (evalmachine.<anonymous>:122:3)
@parcel/integration-tests:     at newRequire (evalmachine.<anonymous>:47:24)
@parcel/integration-tests:     at evalmachine.<anonymous>:81:7
@parcel/integration-tests:     at evalmachine.<anonymous>:120:3
@parcel/integration-tests:     at Script.runInContext (vm.js:134:20)
@parcel/integration-tests:     at Object.runInContext (vm.js:297:6)
@parcel/integration-tests:     at run (/Users/myusername/Documents/GitHub/parcel/packages/core/test-utils/src/utils.js...
@parcel/integration-tests: should loosely deep-equal
@parcel/integration-tests: Error: Cannot find module "optional-dep"
@parcel/integration-tests:     at Context.<anonymous> (/Users/myusername/Documents/GitHub/parcel/packages/core/integration-tests/test/javascript.js:1551:15)
@parcel/integration-tests:  {
@parcel/integration-tests:   code: 'MODULE_NOT_FOUND'
@parcel/integration-tests: }
@parcel/integration-tests:       + expected - actual
@parcel/integration-tests:   AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be loosely deep-equal:
@parcel/integration-tests:
@parcel/integration-tests:   Error: Cannot find module 'optional-dep'
@parcel/integration-tests:       at newRequire (evalmachine.<anonymous>:37:19)
@parcel/integration-tests:       at localRequire (evalmachine.<anonymous>:53:14)
@parcel/integration-tests:       at Object.parcelRequire.index.js (evalmachine.<anonymous>:122:3)
@parcel/integration-tests:       at newRequire (evalmachine.<anonymous>:47:24)
@parcel/integration-tests:       at evalmachine.<anonymous>:81:7
@parcel/integration-tests:       at evalmachine.<anonymous>:120:3
@parcel/integration-tests:       at Script.runInContext (vm.js:134:20)
@parcel/integration-tests:       at Object.runInContext (vm.js:297:6)
@parcel/integration-tests:       at run (/Users/myusername/Documents/GitHub/parcel/packages/core/test-utils/src/utils.js...
@parcel/integration-tests:
@parcel/integration-tests:   should loosely deep-equal
@parcel/integration-tests:
@parcel/integration-tests:   Error: Cannot find module "optional-dep"
@parcel/integration-tests:       at Context.<anonymous> (test/javascript.js:1551:15)
@parcel/integration-tests:    {
@parcel/integration-tests:     code: 'MODULE_NOT_FOUND'
@parcel/integration-tests:   }
@parcel/integration-tests:       at Context.<anonymous> (test/javascript.js:1554:12)
@parcel/integration-tests:
@parcel/integration-tests:   5) kotlin
@parcel/integration-tests:        should produce a basic kotlin bundle:
@parcel/integration-tests:      No Java runtime present, requesting install.
@parcel/integration-tests:
@parcel/integration-tests: npm ERR! code ELIFECYCLE
@parcel/integration-tests: npm ERR! errno 5
@parcel/integration-tests: npm ERR! @parcel/integration-tests@1.12.3 test: `cross-env NODE_ENV=test mocha`
@parcel/integration-tests: npm ERR! Exit status 5
@parcel/integration-tests: npm ERR!
@parcel/integration-tests: npm ERR! Failed at the @parcel/integration-tests@1.12.3 test script.
@parcel/integration-tests: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@parcel/integration-tests: npm ERR! A complete log of this run can be found in:
@parcel/integration-tests: npm ERR!     /Users/myusername/.npm/_logs/2019-07-27T19_54_45_394Z-debug.log
lerna ERR! npm run test exited 5 in '@parcel/integration-tests'
error Command failed with exit code 5.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
