### ISSUE TITLE
Bundled app can't resolve path to core.*.node

### ISSUE THREAD

**Issue by quarties** [parcel-bundler/parcel#2768]
# 🐛 bug report

After upgrading parcel-bundler from `1.11.0` to `1.12.0` our app throws an error when we try to run it after building.

## 🎛 Configuration (.babelrc, package.json, cli command)

Here is a command that I used:

```bash
node index.js config.json
```

package.json
```json
{
  "name": "@livechat/bigcommerce-api",
  "version": "0.1.0",
  "description": "Service responsible for communication between LiveChat and BigCommerce",
  "main": "src/index.js",
  "scripts": {
    "start": "nodemon src/index.js config.json --env=development",
    "build": "parcel build src/index.js -d ../../dist/backend --target=node --bundle-node-modules --no-minify --out-file index.js --no-source-maps",
    "test": "jest",
    "accounts:mock": "nodemon --watch mocks/accounts --exec dyson mocks/accounts 3001",
    "bigcommerce:mock": "nodemon --watch mocks/bigcommerce --exec dyson mocks/bigcommerce 3002",
    "lcapi:mock": "nodemon --watch mocks/lcapi --exec dyson mocks/lcapi 3003",
    "mocks": "concurrently 'npm run accounts:mock' 'npm run bigcommerce:mock' 'npm run lcapi:mock'"
  },
  "keywords": [
    "nodejs",
    "bigcommerce",
    "integrations"
  ],
  "author": "LiveChat Inc.",
  "license": "UNLICENSED",
  "dependencies": {
    "@livechat/fastify-boilerplate": "^0.7.2",
    "command-line-args": "^5.0.2",
    "fastify-cors": "^1.0.0",
    "fastify-plugin": "^1.3.0",
    "hash-equals": "0.0.3",
    "jsonwebtoken": "^8.4.0",
    "lodash": "^4.17.11",
    "make-promises-safe": "^4.0.0",
    "mysql": "^2.16.0",
    "mysql-migrations": "^1.0.6",
    "node-fetch": "^2.3.0",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@livechat/parcel-plugin-node-addons": "^1.0.0",
    "concurrently": "^4.1.0",
    "dyson": "^2.0.3",
    "fetch-mock": "^7.3.0",
    "fsevents": "^1.2.7",
    "jest": "^24.1.0",
    "nodemon": "^1.18.10",
    "parcel-bundler": "1.12.0"
  }
}
```

## 🤔 Expected Behavior

It should run the app.

## 😯 Current Behavior

The app is not starting and throws an error:

```
/Users/michalsypko/Sites/bigcommerce/dist/backend/index.js:116
    throw error;
    ^

Error: Cannot find module './../../../../backend/core.c3506fea.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at newRequire (/Users/michalsypko/Sites/bigcommerce/dist/backend/index.js:34:18)
    at localRequire (/Users/michalsypko/Sites/bigcommerce/dist/backend/index.js:53:14)
    at eval (eval at parcelRequire.dz+m (/Users/michalsypko/Sites/bigcommerce/dist/backend/index.js:31333:16), <anonymous>:1:1)
    at Object.parcelRequire.dz+m (/Users/michalsypko/Sites/bigcommerce/dist/backend/index.js:31333:16)
    at newRequire (/Users/michalsypko/Sites/bigcommerce/dist/backend/index.js:47:24)
    at localRequire (/Users/michalsypko/Sites/bigcommerce/dist/backend/index.js:53:14)
````

## 🔦 Context

We are using lerna for our project to build backend and frontend of the app. It worked just fine with `parcel-bundler@1.11.0`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.0 |
| Node             | 10.11.0 |
| npm        | 6.4.1 |
| Operating System | MacOS Mojave v10.14.3 |

**Comment by quarties** [comment]
Additionally, here is soruce code for `@livechat/parcel-plugin-node-addons `:

index.js
```js
module.exports = function(bundler) {
    bundler.addAssetType('node', require.resolve('./NodeAsset'));
}
```

NodeAsset.js
```js
const { Asset } = require('parcel-bundler');
const path = require('path');
const URL = require('url');

class NodeAsset extends Asset {
    
    load() {}

    generate() {
        const pathToAsset = this.urlJoin(
            this.options.publicURL,
            this.generateBundleName()
        );
    
        return [
            {
                type: 'js',
                value: `module.exports=eval('require(${JSON.stringify(`.${pathToAsset}`)})');`
            }
        ];
    }

    urlJoin(publicURL, assetPath) {
        const url = URL.parse(publicURL, false, true);
        const assetUrl = URL.parse(assetPath);
        url.pathname = path.posix.join(url.pathname, assetUrl.pathname);
        url.search = assetUrl.search;
        url.hash = assetUrl.hash;

        return URL.format(url);
    }
}

module.exports = NodeAsset;
```

**Comment by mischnic** [comment]
Fixed by https://github.com/parcel-bundler/parcel/pull/2740
