### ISSUE TITLE
Treeshaking with Node builtins modules ES imports and --target=node fails

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#2796]
# 🐛 bug report

Scope handling fails with `--target node` and ES imports of Node builtin modules (e.g. `path`).

```
🚨  Cannot read property 'optional' of undefined
    at CallExpression (parcel/packages/core/parcel-bundler/src/scope-hoisting/concat.js:148:66)
    at NodePath._call (parcel/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (parcel/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (parcel/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (parcel/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (parcel/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (parcel/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (parcel/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (parcel/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (parcel/node_modules/@babel/traverse/lib/context.js:118:16)
```

## 💁 Possible Solution

In the hoisting phase, these imports need to be replace with a plain `require` call, not with `$parcel$require(...)`.
`require`ing builtin modules works fine.
https://github.com/parcel-bundler/parcel/blob/2edae260a4c2cf8f6153c602aa7e5623644f484a/packages/core/parcel-bundler/src/scope-hoisting/hoist.js#L346-L367

## 💻 Code Sample

`parcel build index.js --experimental-scope-hoisting -t node`

```js
import path from "path";

console.log(path.join("/dir", "b.js"));
```

**Comment by devongovett** [comment]
Related to #1686?
