### ISSUE TITLE
Parcel cannot bundle puppeteer inside react project

### ISSUE THREAD

**Issue by entrptaher** [parcel-bundler/parcel#2847]
# 🐛 bug report

- ❌ The cloned folder from github builds properly, but not usable with react directly
- ❌ Doing yarn add puppeteer or yarn add puppeteer-core, and then building the index.html fails
- ❌ Does not work with browserify bundle provided by puppeteer-web
- ✔️ alias in package.json works both with the built file, clonned git repo

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime"
  ]
}
```

## 🤔 Expected Behavior

Should bundle and serve properly just like it bundles when outside the project.

## 😯 Current Behavior

❌ The cloned folder from github builds properly, but not usable with react directly.

```
parcelRequire is not defined
...
long error message of what's not defined
```

❌ Doing `yarn add puppeteer` or `yarn add puppeteer-core`, and then building the `index.html` fails
```
 /home/projects/react-puppeteer/client/node_modules/puppeteer-core/lib/Connection.js: Property name expected type of string but got null
    at validate (/home/projects/react-puppeteer/client/node_modules/parcel-bundler/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at Object.validate (/home/projects/react-puppeteer/client/node_modules/parcel-bundler/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:172:7)
    at validate (/home/projects/react-puppeteer/client/node_modules/parcel-bundler/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/home/projects/react-puppeteer/client/node_modules/parcel-bundler/node_modules/@babel/core/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.Identifier (/home/projects/react-puppeteer/client/node_modules/parcel-bundler/node_modules/@babel/core/node_modules/@babel/types/lib/builders/generated/index.js:323:31)
    at /home/projects/react-puppeteer/client/node_modules/regenerator-transform/lib/hoist.js:30:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (/home/projects/react-puppeteer/client/node_modules/regenerator-transform/lib/hoist.js:27:23)
    at exit (/home/projects/react-puppeteer/client/node_modules/regenerator-transform/lib/hoist.js:46:20)
    at NodePath._call (/home/projects/react-puppeteer/client/node_modules/parcel-bundler/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)

```

❌ Does not work with browserify bundle provided by puppeteer-web
```
git clone https://github.com/GoogleChrome/puppeteer
cd puppeteer 
yarn run bundle

# use this file with alias
"alias": { "puppeteer": "./puppeteer/utils/browser/puppeteer-web.js"}
```

Error: 
```
# const puppeteer = require('puppeteer');
Uncaught (in promise) TypeError: puppeteer.connect is not a function

# import puppeteer from "puppeteer";
Uncaught (in promise) TypeError: _puppeteer.default.connect is not a function
    at _callee$ (robot.js:5)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(:1234/anonymous function) [as next] (http://localhost:1234/src.a2b27638.js:235:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at _getTitle (robot.js:3)
```

## 💁 Possible Solution

✔️ alias in package.json works both with the built file, clonned git repo

```
git clone https://github.com/GoogleChrome/puppeteer
# no need to do yarn install ... :/
```

```js
"alias": {"puppeteer": "./puppeteer"}
```

or build the file,
```
git clone https://github.com/GoogleChrome/puppeteer
cd puppeteer
parcel build index.js
```

```js
"alias": {"puppeteer": "./puppeteer/dist"}
```

## 🔦 Context

I'm trying to connect to a remote chrome browser from the react app.

![image](https://raw.githubusercontent.com/entrptaher/playground-react-puppeteer/nice-design/demo.gif)

## 💻 Code Sample

```js
import puppeteer from "puppeteer";

const browser = await puppeteer.connect({
    browserWSEndpoint: "ws://127.0.0.1:4000"
});
```

Full code here on this repository/tree: https://github.com/entrptaher/playground-react-puppeteer/tree/parcel

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v11.7.0
| npm/Yarn         | 6.5.0/1.13.0
| Operating System | Ubuntu 18.04.2 LTS

**Comment by Ebuall** [comment]
Same problem. Cannot build a simple script that uses puppeteer-core.

**Comment by lvkins** [comment]
I can reproduce this. Same behavior with **puppeteer-core** dep.

**Comment by amazingandyyy** [comment]
I bumped into same issue >,<

**Comment by entrptaher** [comment]
No stalebot, no, please. :D

**Comment by entrptaher** [comment]
Maybe I have to think and work on a PR :'(

**Comment by lvkins** [comment]
> This issue has been automatically marked as stale

In the name of Jesus Christ stop it
