### ISSUE TITLE
🐛 d3 import: Could not statically evaluate fs call

### ISSUE THREAD

**Issue by MoritzStefaner** [parcel-bundler/parcel#298]
Thanks for parcel! Looks great so far! 

I just hit one wall so far:
Importing d3.js (https://github.com/d3/d3) results in build error

```
node_modules/xmlhttprequest/lib/XMLHttpRequest.js: Could not statically evaluate fs call
    at evaluate (/usr/local/lib/node_modules/parcel-bundler/src/visitors/fs.js:164:11)
    at CallExpression.path.get.map.arg (/usr/local/lib/node_modules/parcel-bundler/src/visitors/fs.js:31:21)
    at Array.map (<anonymous>)
    at JSAsset.CallExpression (/usr/local/lib/node_modules/parcel-bundler/src/visitors/fs.js:31:10)
    at NodePath._call (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/context.js:192:19)
``` 

Any ideas? Thanks!

**Comment by fathyb** [comment]
This is because d3.js declares it's node.js version in the `main` field and the browser version in the `module` (and other) field. I made a PR to make Parcel uses these field in priority, it should totally work with d3.

**Comment by mbasso** [comment]
Hi,
I'm facing the same issue with `.js` and `.asm.js` files compiled with [emscripten](http://kripken.github.io/emscripten-site/) from C++. It seems that the compiled code contains something like this:

```js
function(a,b){var c=R(a);c||(hb||(hb=require("fs")),ib||(ib=require("path")),a=ib.normalize(a),c=hb.readFileSync(a));return b?c:c.toString()};
```

that, unfortunately, is in contrast with the doc:

> The URL must be statically analyzable, meaning it cannot have any variables in it (other than __dirname and __filename).

How can we make it work? Is there a way to ignore these checks for some files?

**Comment by MoritzStefaner** [comment]
Can confirm it d3.js works now - thanks for the quick fix! 🎉

**Comment by maxwondercorn** [comment]
Is there a long term fix for this or is this a module by module fix?  Tried Parcel for the first time and it has the same fa evaluation error for donenv.  It is the latest version of dotenv.  thanks

` /Users/greggmartell/Projects/Test-Projects/parcel-test/node_modules/dotenv/lib/main.js: Could not statically evaluate fs call
    at evaluate (/usr/local/lib/node_modules/parcel-bundler/src/visitors/fs.js:163:11)
    at CallExpression.path.get.map.arg (/usr/local/lib/node_modules/parcel-bundler/src/visitors/fs.js:30:21)
    at Array.map (<anonymous>)
    at JSAsset.CallExpression (/usr/local/lib/node_modules/parcel-bundler/src/visitors/fs.js:30:10)
    at NodePath._call (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-traverse/lib/context.js:190:19)`

**Comment by kriskate** [comment]
I tried switching to parcel on an project I've already been working on get the same error... but wouldn't know which package actually causes the issue, as I already have >20 dependencies
`/node_modules/mime/mime.js: Could not statically evaluate fs call
    at evaluate (/Users/cristi/work/pap/pap-portal/node_modules/parcel-bundler/src/visitors/fs.js:163:11)
    at CallExpression.path.get.map.arg (/Users/cristi/work/pap/pap-portal/node_modules/parcel-bundler/src/visitors/fs.js:30:21)
    at Array.map (<anonymous>)
    at JSAsset.CallExpression (/Users/cristi/work/pap/pap-portal/node_modules/parcel-bundler/src/visitors/fs.js:30:10)
    at NodePath._call (/Users/cristi/work/pap/pap-portal/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/cristi/work/pap/pap-portal/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/cristi/work/pap/pap-portal/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/cristi/work/pap/pap-portal/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/cristi/work/pap/pap-portal/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/cristi/work/pap/pap-portal/node_modules/babel-traverse/lib/context.js:192:19)`

**Comment by kriskate** [comment]
Oh... 
"This is probably happening because u use Asynchronous FS calls, those are not supported yet"

Didn't know that, sorry

**Comment by fathyb** [comment]
#587 has been created to prevent this

**Comment by maxwondercorn** [comment]
No complaints.  Looking forward to my life being easier with a new tool
