### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by andrewluetgers** [parcel-bundler/parcel#31]
`loot$ parcel build src/index.js 
🚨  /Users/loot/dev/project/src/index.js: Cannot read property 'start' of undefined
    at module.exports (/Users/loot/.nvm/versions/node/v8.7.0/lib/node_modules/parcel-bundler/node_modules/babel-to-estree/babylon-to-espree/attachComments.js:56:42)
    at module.exports (/Users/loot/.nvm/versions/node/v8.7.0/lib/node_modules/parcel-bundler/node_modules/babel-to-estree/babylon-to-espree/index.js:35:3)
    at exports.toEstree (/Users/loot/.nvm/versions/node/v8.7.0/lib/node_modules/parcel-bundler/node_modules/babel-to-estree/index.js:9:3)
    at module.exports (/Users/loot/.nvm/versions/node/v8.7.0/lib/node_modules/parcel-bundler/src/transforms/uglify.js:10:39)
    at <anonymous>
`
using babel preset env

**Comment by devongovett** [comment]
See #8.
