### ISSUE TITLE
Unknown plugin "transform-es2015-arrow-functions" with basic project

### ISSUE THREAD

**Issue by sergi** [parcel-bundler/parcel#325]
**Bug Report 🐛**

I created a minimal project (following https://parceljs.org/getting_started.html. The only difference is that I include the package "ws" in package.json). Launching parcel via `parcel index.html` causes the error you can see below.

### 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```js
{
  "name": "dashboard",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "ws": "^3.3.3"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

### 🤔 Expected Behavior
Parcel bundles up the project without any problem.

### 😯 Current Behavior
```
⏳  Building...
Server running at http://localhost:1234
🚨  /usr/local/lib/node_modules/parcel-bundler/node_modules/browserify-zlib/lib/binding.js: Unknown plugin "transform-es2015-arrow-functions" specified in "/usr/local/lib/node_modules/parcel-bundler/node_modules/browserify-zlib/package.json" at 0, attempted to resolve relative to "/usr/local/lib/node_modules/parcel-bundler/node_modules/browseri    at /usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.parse (/usr/local/lib/node_modules/parcel-bundler/src/assets/JSAsset.js:55:20)
    at JSAsset.parseIfNeeded (/usr/local/lib/node_modules/parcel-bundler/src/Asset.js:46:29)
    at <anonymous>
```

### 💁 Possible Solution
No idea. The project is too small for anything to cause this error.

### 🔦 Context
Just trying out parcel to bundle the simplest project.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           | 1.2.0
| Node             | v9.3.0
| npm/Yarn         | npm 5.6.0
| Operating System | OSX 10.13.2

**Comment by sergi** [comment]
Hi, this does not resolve the issue:

```
❯ npm install babel-plugin-transform-es2015-arrow-functions --save-dev
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN dashboard@1.0.0 No description
npm WARN dashboard@1.0.0 No repository field.

+ babel-plugin-transform-es2015-arrow-functions@6.22.0
added 4 packages in 5.364s

❯ parcel index.html
⏳  Building...
Server running at http://localhost:1234
🚨  /usr/local/lib/node_modules/parcel-bundler/node_modules/browserify-zlib/lib/binding.js: Unknown plugin "transform-es2015-arrow-functions" specified in "/usr/local/lib/node_modules/parcel-bundler/node_modules/browserify-zlib/pack    at /usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.parse (/usr/local/lib/node_modules/parcel-bundler/src/assets/JSAsset.js:55:20)
    at JSAsset.parseIfNeeded (/usr/local/lib/node_modules/parcel-bundler/src/Asset.js:46:29)
    at <anonymous>
```

**Comment by cristiandley** [comment]
@DeMoorJasper @sergi im having the same issue... same situation

**Comment by DeMoorJasper** [comment]
If someone could provide a basic project with this bug than i could confirm if its a bug or how to actually fix this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cristiandley** [comment]
@DeMoorJasper quick repo... https://github.com/cristiandley/parcel-example

**Comment by DeMoorJasper** [comment]
@cristiandley That example repo uses pug, which is not supported by default in parcel, i'm a bit confused at how this should work? Could u provide the correct run scripts and dependancies in package.json fit to parcel, because this seems like a webpack app?

**Comment by cristiandley** [comment]
@DeMoorJasper well... my bad ... yes it was a dirty repo. Now i updated it. Aboug `pug` i thought Parcel built everything, im sorry.

I removed everything that should not work... and should not be there and this is the new error...

```bash
/usr/lib/node_modules/parcel-bundler/bin/cli.js:84
async function bundle(main, command) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
error Command failed with exit code 1.
                                        
```

**Comment by DeMoorJasper** [comment]
That's a little compatibility error with node 6 and 7 atm, updating to node 8 would update this.
@cristiandley

**Comment by sergi** [comment]
@DeMoorJasper here's a minimal repo that reproduces the issue for me: https://github.com/sergi/parcel_testcase

**Comment by cyyyu** [comment]
Encountered the issue as well. 
It just happened when I tried to import [twitter](https://www.npmjs.com/package/twitter) lib into my repo.

**Comment by davidnagli** [comment]
Repopening as per @cyyyu’s request…

**Comment by davidnagli** [comment]
@cyyyu Can you please provide your Parcel version and an example repo so we can reproduce the issue

**Comment by cyyyu** [comment]
@davidnagli sure, I'm using parcel-bundler@1.2.0

A super minimal repo includes 3 files for reproduction. As I mentioned I had only one lib(twitter) imported.

Btw if it matters, I have npm@5.6.0 and node@9.3.0

index.html
```
<html>
<body>
  <script src="./index.js"></script>
</body>
</html>
```

index.js
```
import Twitter from 'twitter'
const client = new Twitter({
  //...
})
```

package.json
```
{
  "dependencies": {
    "twitter": "^1.7.1"
  }
}
```

**Comment by brandon93s** [comment]
The above example gives me the following:

```shell
Couldn't find preset "es2015" relative to directory "C:\\Source\\parcel-bundler\\parcel-test\\325\\node_modules\\hawk"
```

Running the following fixes the error:

```shell
npm install --save babel-preset-es2015
```

**Comment by cyyyu** [comment]
@brandon93s  emmm... while it gives me this.

```
⏳  Building...
Server running at http://localhost:1234
🚨  /usr/local/lib/node_modules/parcel-bundler/node_modules/browserify-zlib/lib/binding.js: Unknown plugin "transform-es2015-arrow-functions" specified in "/usr/local/lib/node_modules/parcel-bundler/node_modules/browserify-zlib/package.json" at 0, attempted to resolve relative to "/usr/local/lib/node_mod    at /usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.parse (/usr/local/lib/node_modules/parcel-bundler/src/assets/JSAsset.js:55:20)
    at JSAsset.parseIfNeeded (/usr/local/lib/node_modules/parcel-bundler/src/Asset.js:46:29)
    at <anonymous>
```

**Comment by cyyyu** [comment]
By investigating for a while I have myself a workaround. This might help anybody who encountered the same problem.

Instead of using parcel globally, I install it locally by `npm install --save-dev parcel-bundler`. 
Then I add a npm script like 
```
  "scripts": {
    "start": "parcel ./index.html"
  }
```
Also I need preset-es2015 or I will get another issue.
```
npm install --save-dev babel-preset-es2015
```

Then use `npm start` for bundling and everything works.

**Comment by felipe-gdr** [comment]
@cyyyu , your workaround worked for me

**Comment by lednhatkhanh** [comment]
Hey, any solution for this, I also get this error about missing: `transform-es3-member-expre
ssion-literals`

**Comment by whiskyoo** [comment]
try to run script with `--no-cache` option or remove `.cache` folder then running script
```
parcel src/index.html --no-cache
parcel build src/index.html --no-cache --public-url / -d dist
```

**Comment by Banandrew** [comment]
Hi @lednhatkhanh, it’s similar, I had to install 4 packages when I had the same error:
```
npm install --save-dev babel-plugin-transform-es3-member-expression-literals
npm install --save-dev babel-plugin-transform-es3-property-literals
npm install --save-dev babel-preset-es2015
npm install --save-dev babel-preset-stage-0
```

**Comment by devongovett** [comment]
This is probably #13.
