### ISSUE TITLE
Cannot read property 'js' of null

### ISSUE THREAD

**Issue by yw662** [parcel-bundler/parcel#3260]
# 🐛 bug report

Cannot read property 'js' of null when trying to build project.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
  "dependencies": {
    "parcel-bundler": ">=1.12.3",
    "parcel-plugin-wasm.rs": "1.2.9",
    "pug": "latest",
    "typescript": "latest"
  }
```
```
npx parcel build ./src/app/index.pug --public-url . --no-source-maps --no-content-hash
```

## 🤔 Expected Behavior

build should pass.

## 😯 Current Behavior

build always fail with this error, even if `.cache` is removed before build.

```
Cannot read property 'js' of null
    at JSPackager.dedupeKey (node_modules/parcel-bundler/src/packagers/JSPackager.js:110:40)
    at JSPackager.addAsset (node_modules/parcel-bundler/src/packagers/JSPackager.js:42:22)
    at JSPackager.addAssetToBundle (node_modules/parcel-bundler/src/packagers/JSPackager.js:145:16)
    at JSPackager.writeBundleLoaders (node_modules/parcel-bundler/src/packagers/JSPackager.js:161:18)
    at JSPackager.end (node_modules/parcel-bundler/src/packagers/JSPackager.js:221:20)
    at Bundle._package (node_modules/parcel-bundler/src/Bundle.js:222:20)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.0
| npm/Yarn         | npm 6.10.1
| Operating System | 5.1.17

**Comment by mischnic** [comment]
Can you provide an example project? Its likely related to webassembly.

**Comment by yw662** [comment]
I think it is probably related to wasm. However, my project is way too large to be provided as an example.

**Comment by mischnic** [comment]
Are you using dynamic imports (and wasm in both "parts")? If so, does it work when that dynamic import is replaced by a normal one?

Otherwise, maybe you can simplify it to only have one JS and one Rust (?) file where the build still fails.

**Comment by mischnic** [comment]
Closing because of inactivity.
