### ISSUE TITLE
Parcel not building files in Electron? How to config

### ISSUE THREAD

**Issue by patrykkalinowski** [parcel-bundler/parcel#3315]
# ❔ Question

I have an Electron project: https://github.com/patrykkalinowski/dcs-frontlines-electron

I want to require file `app/map.js` in `app/dcs.js`, but somehow `map.js` is not built correctly by Parcel?

After `npm start` I receive an error:
```
App threw an error during load
/Users/patryk/Code/dcs-frontlines-electron/app/map.js:7
import { Buffer } from "buffer"; // needed after 'fs' is being transpiled
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:752:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/patryk/Code/dcs-frontlines-electron/app/dcs.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
```

How to setup Parcel so it builds all files without errors?

## 🔦 Context

Parcel entry is index.html which contains `<script src="./renderer.jss">`
Renderer requires `app/map.js`
Electron's `main.js` requires `app/dcs.js`

These 3 work.

`app/dcs.js` requires `app/map.js` - this doesn't work, `Unexpected token {`

## 💻 Code Sample

https://github.com/patrykkalinowski/dcs-frontlines-electron

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v10.16.1
| npm/Yarn         | 6.9.0
| Operating System | OSX

**Comment by mischnic** [comment]
In your `main.js` (in the main process), you require `const DCS = require('./app/dcs')` and therefore './app/map' as well (which contains this ES6 import that Node can't work with).

In your setup, Parcel only transpiles the code for the renderer process inside of the window.
