### ISSUE TITLE
Tree shaking can't handle Vue SFC without <script>

### ISSUE THREAD

**Issue by ocavue** [parcel-bundler/parcel#3378]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

See this repo: 

https://github.com/ocavue/parcel_issue_vue_tree_shaking

## 🤔 Expected Behavior

`yarn build1` and `yarn build2` should both work well.

## 😯 Current Behavior

`yarn build1` works fine but `yarn build2` throw "Cannot convert undefined or null to object"

```
> yarn build1
$ parcel build ./index.html --no-cache --no-source-maps
dist/parcel_issue_vue_tree_shaking.a7fca0a5.js    68.25 KB    3.62s
dist/index.html                                      317 B    466ms
✨  Done in 4.91s.

> yarn build2
$ parcel build ./index.html --no-cache --no-source-maps --experimental-scope-hoisting
🚨  Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at JSConcatPackager.findExportModule (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/packagers/JSConcatPackager.js:564:39)
    at JSConcatPackager.markUsed (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/packagers/JSConcatPackager.js:108:21)
    at JSConcatPackager.markUsedExports (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/packagers/JSConcatPackager.js:102:14)
    at JSConcatPackager.markUsed (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/packagers/JSConcatPackager.js:121:10)
    at JSConcatPackager.markUsedExports (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/packagers/JSConcatPackager.js:102:14)
    at JSConcatPackager.start (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/packagers/JSConcatPackager.js:63:12)
    at Bundle._package (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/Bundle.js:215:20)
    at async Promise.all (index 0)
    at async Bundle.package (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Promise.all (index 1)
    at async Bundle.package (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Bundler.bundle (/path/parcel_issue_vue_tree_shaking/node_modules/parcel-bundler/src/Bundler.js:325:27)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 💁 Possible Solution

If I add a `script` tag into `A.vue`, this issue will not appear.

```
> echo '<script>
export default { name: "A" };
</script>' >> ./A.vue

> yarn build2
dist/parcel_issue_vue_tree_shaking.0e670759.js    64.4 KB    3.84s
dist/index.html                                     317 B    1.13s
✨  Done in 4.94s.

```

It seems that parcel presume all `.vue` files have `<script>` tag and cause this error.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3|
| Node             |v12.4.0|
| npm/Yarn         |yarn 1.16.0|
| Operating System |macOS 10.13|

**Comment by ocavue** [comment]
Update:

Just had a look at parcel@2.0.0-alpha.1.1 , and I noticed that parcel2 has no more `--experimental-scope-hoisting` but a `--no-scope-hoist` option. Does parcel2 enable tree shaking by default? If so, I cannot repeat this issue with parce2. 😃

**Comment by devongovett** [comment]
Yes, Parcel 2 enables tree shaking by default. However, Parcel 2 doesn't have Vue support yet, so if this issue is related to Vue then it might still be a thing.

**Comment by ocavue** [comment]
Will the parcel team fix tree shaking issues for parcel 1 anymore? 

(I will understand if the answer is no since it's only an experimental function and parcel 2 is more important.)

**Comment by devongovett** [comment]
Parcel 1 is pretty much in maintenance mode at this point. We don't plan to do any more releases unless absolutely necessary (e.g. it's completely broken).
