### ISSUE TITLE
Scope Hoisting with Sentry fails

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#3437]
# 🐛 bug report

When including the `@sentry/browser` dependency into the bundle the build fails.
Watch mode works as expected.

## 🎛 Configuration (.babelrc, package.json, cli command)

I am using a bare repository without any config files (but had the same error in a project with more configurations as well).

## 🤔 Expected Behavior

Should bundle the JavaScript file.

## 😯 Current Behavior

Failing with error

```
× Got unexpected null
    at nullthrows (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\nullthrows\nullthrows.js:7:15)
    at BundleGraph.resolveSymbol (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\@parcel\core\lib\BundleGraph.js:324:48)
    at BundleGraph.resolveSymbol (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\@parcel\core\lib\public\BundleGraph.js:103:51)
    at markUsed (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\@parcel\scope-hoisting\lib\concat.js:219:32)
    at bundle.traverseAssets.asset (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\@parcel\scope-hoisting\lib\concat.js:213:9)
    at enter (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\@parcel\core\lib\Graph.js:442:16)
    at enter (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\@parcel\core\lib\Graph.js:442:16)
    at enter (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\@parcel\core\lib\Graph.js:442:16)
    at walk (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\@parcel\core\lib\Graph.js:282:26)
    at walk (<path>\npm-cache\_npx\12688\node_modules\parcel\node_modules\@parcel\core\lib\Graph.js:303:22)
```

## 💁 Possible Solution

It only fails when using scope hoisting, in watch mode or with `--no-scope-hoist` it is working as expected.

## 💻 Code Sample

```
// src/index.js
import * as Sentry from '@sentry/browser';
```

`npx parcel@2.0.0-alpha.1.1 build .\src\index.js`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.1.1
| Node             | 10.15.1
| npm         | 4.6.1
| Operating System | Windows 10

I already saw issues when enabling scope hoisting in parcel v1 so I assume this is not a new bug.

**Comment by fredj** [comment]
I've a similar issue that can be seen using this repository: https://github.com/fredj/ol-parcel
```
🚨 Got unexpected undefined
    at nullthrows (/tmp/ol-parcel/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.removeById (/tmp/ol-parcel/node_modules/@parcel/core/lib/Graph.js:169:40)
    at AssetGraphBuilder.handleNodeRemovedFromAssetGraph (/tmp/ol-parcel/node_modules/@parcel/core/lib/AssetGraphBuilder.js:137:27)
    at AssetGraph.onNodeRemoved (/tmp/ol-parcel/node_modules/@parcel/core/lib/AssetGraphBuilder.js:74:35)
    at AssetGraph.removeNode (/tmp/ol-parcel/node_modules/@parcel/core/lib/AssetGraph.js:128:32)
    at AssetGraph.removeEdge (/tmp/ol-parcel/node_modules/@parcel/core/lib/Graph.js:186:12)
    at AssetGraph.removeNode (/tmp/ol-parcel/node_modules/@parcel/core/lib/Graph.js:161:14)
    at AssetGraph.removeNode (/tmp/ol-parcel/node_modules/@parcel/core/lib/AssetGraph.js:129:18)
    at AssetGraph.removeEdge (/tmp/ol-parcel/node_modules/@parcel/core/lib/Graph.js:186:12)
    at AssetGraph.replaceNodesConnectedTo (/tmp/ol-parcel/node_modules/@parcel/core/lib/Graph.js:227:12)
```

I suspect that this issue is caused by exports in the form `export { Foo } from '...'`

**Comment by garthenweb** [comment]
Hey @mischnic, thank you for your investigation! Unfortunately, I still have issues with Sentry. But I think it is another issue now. Therefore I created a new ticket #3640 and will close this one.
