### ISSUE TITLE
LESS: relative import in third-party package

### ISSUE THREAD

**Issue by lol768** [parcel-bundler/parcel#3448]
I have a dependency on the following NPM package in my `package.json`:

```
"@universityofwarwick/id7": "2.5.2"
```

My entry point imports a LESS file, which does an `@import`:

```
@import "~@universityofwarwick/id7/less/id7-no-fa.less";
```

This file tries to do the following:

```
// Bootstrap core variables and mixins
@import (reference) 'bootstrap/less/variables.less';
```

Which fails the build process:

```
🚨  /home/adamwilliams/Documents/Projects/play-app-template/app/assets/css/main.less: Cannot find module './bootstrap/less/variables.less' from '/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@universityofwarwick/id7/less'
    at Resolver.resolve (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/parcel-bundler/src/Resolver.js:71:17)
```

I've tried the following `.lessrc` to no avail:

```
{
    paths: ["node_modules"],
    relativeUrls: false,
    sourceMap: true
}
```

<details>
<pre>
"less": "^3.10.2",
"less-loader": "5.0.0",
"parcel-bundler": "^1.12.3"
</pre>
</details>

**Comment by DeMoorJasper** [comment]
This is a bug that has been fixed in Parcel 2. If anyone wants to fix this in v1 feel free to open up a PR

**Comment by lol768** [comment]
I thought this might be the case. When I tried parcel 2, I expeerienced this:

```
/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:197
        throw new Error(`Expected constructor ${value.$$type} to be registered with serializer to deserialize`);
        ^

Error: Expected constructor 2.0.0-alpha.1.1:NodeFS to be registered with serializer to deserialize
    at value (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:197:15)
    at memoizedFn (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:83:13)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:112:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:146:9)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:108:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:146:9)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:108:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:138:9)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:108:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:146:9)
```

Does it warrant another issue>

**Comment by DeMoorJasper** [comment]
@lol768 you should probably open a seperate issue for that bug
