### ISSUE TITLE
Parcel 2: Expected constructor errors when building or watching

### ISSUE THREAD

**Issue by lol768** [parcel-bundler/parcel#3450]
`Expected constructor` errors when building or watching

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json

```
    "babel-eslint": "10.0.1",
    "babel-preset-airbnb": "3.2.0",
    "babel-loader": "8.0.5",
    "babel-plugin-lodash": "3.3.4",
    "parcel": "2.0.0-alpha.1.1",

// ...
  "browser": "target/assets/main.js",
  "scripts": {
    "dev": "parcel watch app/assets/js/main.js",
    "build": "parcel build app/assets/js/main.js",
  }
```

babel.config.js

```
module.exports = function(api) {
  // Cache results until NODE_ENV changes
  api.cache.using(() => process.env.NODE_ENV);

  return {
    "presets": ["@babel/preset-env"],
    "plugins": ["@babel/plugin-syntax-dynamic-import", "lodash"]
  };
};
```

## 🤔 Expected Behavior

Build happens successfully

## 😯 Current Behavior

```
➜  play-app-template git:(feature/parcel) ✗ npm run build

> APP_NAME@1.0.0-SNAPSHOT build /home/adamwilliams/Documents/Projects/play-app-template
> parcel build app/assets/js/main.js

/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:197
        throw new Error(`Expected constructor ${value.$$type} to be registered with serializer to deserialize`);
        ^

Error: Expected constructor 2.0.0-alpha.1.1:NodeFS to be registered with serializer to deserialize
    at value (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:197:15)
    at memoizedFn (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:83:13)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:112:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:146:9)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:108:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:146:9)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:108:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:138:9)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:108:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:146:9)
/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:197
        throw new Error(`Expected constructor ${value.$$type} to be registered with serializer to deserialize`);
        ^

Error: Expected constructor 2.0.0-alpha.1.1:NodeFS to be registered with serializer to deserialize
    at value (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:197:15)
    at memoizedFn (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:83:13)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:112:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:146:9)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:108:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:146:9)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:108:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:138:9)
    at processKey (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:108:20)
    at walk (/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:146:9)
/home/adamwilliams/Documents/Projects/play-app-template/node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js:197
        throw new Error(`Expected constructor ${value.$$type} to be registered with serializer to deserialize`);
```

## 🔦 Context

Can't use Parcel.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.1.1
| Node             | v10.15.2
| npm/Yarn         | 6.10.3
| Operating System | Ubuntu 19.04

**Comment by aewing** [comment]
I was seeing this error as well. Removing the `parcel-bundler` and purging `node_modules` did the trick for me.

**Comment by aarjithn** [comment]
Same issue. node 10.16 and Windows 10.

**Comment by mischnic** [comment]
Could someone please provide a reproduction?

**Comment by shanehandley** [comment]
Not a reproduction, but here's a public repo which demonstrates this issue:

https://gitlab.com/shandley/minna-no-nihongo-companion/tree/parcel2

**Comment by mischnic** [comment]
@shanehandley That would be fine as well, but I get this error when running `yarn build`:
`src/activities/noActivity.ts: Missing class properties transform.`

**Comment by shanehandley** [comment]
Interesting - I have been using `npm` and the result seems to be different when using `yarn` - It looks like the original author was also using `npm` - I will play around with this a little today.

**Comment by shanehandley** [comment]
I got a little further with this by removing anything babel6 specific from my `package.json` and `.babelrc` and re-adding the babel 7 equivilent when it errored during build.

I am [now seeing](https://gitlab.com/shandley/minna-no-nihongo-companion/blob/parcel2/README.md) the issue described in 3467, I will wait for that merge.

**Comment by DeMoorJasper** [comment]
@shanehandley does this error still happen with the latest parcel 2 version and babel 7 plugins?

**Comment by shanehandley** [comment]
I've updated to latest parcel2 and am trying to build but have a lot of babel issues to work through...I'll try to come back to this over the next few days.

**Comment by shanehandley** [comment]
This specific issue no longer occurs for me, thank you.

**Comment by DeMoorJasper** [comment]
Awesome, than I'll close if :)
