### ISSUE TITLE
`does not export 'default'` without using default import

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#3463]
# 🐛 bug report

Scope hoisting doesn't work when a file is imported multiple times

## 💻 Code Sample

```js
// index.js
import { Foo } from "./libMain.js";
import { Foo as X } from "./libSub.js";

console.log(Foo, X);

// libMain.js
export { Foo } from "./libSub.js";

// libSub.js
export const Foo = "Important!";
```

`parcel build index.js`

```js
🚨 libSub.js does not export 'default'
    at replaceExportNode (parcel/packages/shared/scope-hoisting/src/link.js:95:13)
    at replaceExportNode (parcel/packages/shared/scope-hoisting/src/link.js:367:20)
    at newFn (parcel/node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call (parcel/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (parcel/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (parcel/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (parcel/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (parcel/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (parcel/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (parcel/node_modules/@babel/traverse/lib/index.js:94:17)
```

## 🌍 Your Environment

Parcel 2 (f8fb6c16)

Works with [Rollup](https://rollupjs.org/repl/?version=1.20.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEZvbyUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGbGliTWFpbi5qcyU1QyUyMiUzQiU1Q25pbXBvcnQlMjAlN0IlMjBGb28lMjBhcyUyMFglMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmxpYlN1Yi5qcyU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2coRm9vJTJDJTIwWCklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGliU3ViLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwRm9vJTIwJTNEJTIwJTVDJTIySW1wb3J0YW50ISU1QyUyMiUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybGliTWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0IlMjBGb28lMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmxpYlN1Yi5qcyU1QyUyMiUzQiU1Q24lMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by mischnic** [comment]
Can't reproduce anymore 😕
