### ISSUE TITLE
Tree Shaking with React/Ant.Design not working

### ISSUE THREAD

**Issue by marcojahn** [parcel-bundler/parcel#3487]
# 🐛 bug report

Using tree shaking with `parcel build --experimental-scope-hoisting ./src/index.html` does break with an error.

A small repo for reproducing the error is available here: https://github.com/marcojahn/parcel-treeshake-bug

Writing imports in another syntax does indeed work.
```js
import { Layout } from "antd"; // NOT WORKING
// WORKING import Layout from "antd/es/layout";
```

## Question
The following is quoted from Ant.design docs
> Note: antd support ES6 tree shaking, so import { Button } from 'antd'; will drop the js code you don't use too.
> We strongly recommend using babel-plugin-import, which can convert the following code to the 'antd/es/xxx' way:

Is there a solution for parcel that works like this plugin ?

## 🎛 Configuration (.babelrc, package.json, cli command)

- no babel configuration used
- package.json
```json
{
  "name": "parcel-treeshake-bug",
  "version": "0.0.1",
  "description": "bug example",
  "main": "index.tsx",
  "scripts": {
    "build": "rimraf ./dist && parcel build ./src/index.html",
    "build:treeshake": "rimraf ./dist && parcel build --experimental-scope-hoisting ./src/index.html",
    "start": "parcel ./src/index.html --no-cache"
  },
  "devDependencies": {
    "@types/jest": "^24.0.18",
    "@types/node": "^12.7.3",
    "@types/react": "^16.9.2",
    "less": "^3.10.3",
    "parcel-bundler": "^1.12.3",
    "rimraf": "^3.0.0",
    "typescript": "^3.6.2"
  },
  "dependencies": {
    "antd": "^3.22.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  }
}
```

## 🤔 Expected Behavior

Tree shake should run without an error

## 😯 Current Behavior
Full details are available in the linked repo: https://github.com/marcojahn/parcel-treeshake-bug
Mentioned filed `2019-09-03T06_15_03_866Z-debug.log` available here: https://github.com/marcojahn/parcel-treeshake-bug/blob/master/NPM_error_log.log

Console output:
```
$ npm run build:treeshake

> parcel-treeshake-bug@0.0.1 build:treeshake /Users/mjahn/Projects/cc/parcel-treeshake-bug
> rimraf ./dist && parcel build --experimental-scope-hoisting ./src/index.html

🚨  ../node_modules/dom-align/dist-web/index.js does not export 'alignElement'
    at replaceExportNode (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/parcel-bundler/src/scope-hoisting/concat.js:54:13)
    at ReferencedIdentifier (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/parcel-bundler/src/scope-hoisting/concat.js:317:20)
    at newFn (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/mjahn/Projects/cc/parcel-treeshake-bug/node_modules/@babel/traverse/lib/index.js:94:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parcel-treeshake-bug@0.0.1 build:treeshake: `rimraf ./dist && parcel build --experimental-scope-hoisting ./src/index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parcel-treeshake-bug@0.0.1 build:treeshake script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mjahn/.npm/_logs/2019-09-03T06_15_03_866Z-debug.log
```

## 💁 Possible Solution
File `src/root.tsx`

Importing the `Layout` as follows `import Layout from "antd/es/layout";` instead of `import { Layout } from "antd";`

Tree shaking is working.

### Solution 2
Add the following dependency `npm install babel-plugin-import --save-dev``

And create a `.babelrc` file containing
```
{
  "plugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es" }, "ant"]
  ]
}

```

## 🔦 Context
Building a small app with Ant.Design.
When using the describend import `import { Layout } from "antd";` the tree-shaking results in an error

## 💻 Code Sample

https://github.com/marcojahn/parcel-treeshake-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 11.10.0 |
| npm/Yarn         | 6.7.0 |
| Operating System | MacOS 10.14.6 |

# Effect on the bundle size

## without tree-shaking
```
> rimraf ./dist && parcel build ./src/index.html

✨  Built in 14.60s.

dist/src.e80c9e51.js.map      ⚠️  1.62 MB     101ms
dist/src.e80c9e51.js            887.9 KB    14.42s
dist/antd.255859f1.css.map     526.74 KB      42ms
dist/antd.255859f1.css         442.17 KB    14.19s
dist/index.html                    328 B      42ms
```

## with tree-shaking
```
> rimraf ./dist && parcel build --experimental-scope-hoisting ./src/index.html

✨  Built in 4.89s.

dist/src.31d1b794.js         824 KB    4.79s
dist/antd.69d1f987.css    442.12 KB    4.79s
dist/index.html               328 B    4.39s
```

**Comment by mischnic** [comment]
Seems to work Parcel 2
