### ISSUE TITLE
Babel compilation gives error "[BABEL]: FILE: .value is not a valid Plugin property"

### ISSUE THREAD

**Issue by mkg20001** [parcel-bundler/parcel#3503]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Command: `parcel build public/index.pug`

(Full command: `git clean -dxf && yarn install && yarn link parcel && yarn build`)

Repo: https://github.com/mercode-org/www.mercode.org/tree/feat/parcel-v2

## 🤔 Expected Behavior

Parcel should compile the files as-is

## 😯 Current Behavior

```
yarn run v1.17.3
warning ../package.json: No license field
$ rm -rf dist && parcel build public/index.pug && sed 's|"/|"https://mercode.org/|g' -i dist/portal.html
🚨 [BABEL] /home/maciej/Projekte/www.mercode.org/public/js/main.js: .value is not a valid Plugin property
    at Object.keys.forEach.key (/home/maciej/Projekte/www.mercode.org/node_modules/@babel/core/lib/config/validation/plugins.js:52:56)
    at Array.forEach (<anonymous>)
    at validatePluginObject (/home/maciej/Projekte/www.mercode.org/node_modules/@babel/core/lib/config/validation/plugins.js:50:20)
    at instantiatePlugin (/home/maciej/Projekte/www.mercode.org/node_modules/@babel/core/lib/config/full.js:209:55)
    at cachedFunction (/home/maciej/Projekte/www.mercode.org/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPluginDescriptor (/home/maciej/Projekte/www.mercode.org/node_modules/@babel/core/lib/config/full.js:200:10)
    at config.plugins.reduce (/home/maciej/Projekte/www.mercode.org/node_modules/@babel/core/lib/config/full.js:69:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/home/maciej/Projekte/www.mercode.org/node_modules/@babel/core/lib/config/full.js:67:38)
    at loadFullConfig (/home/maciej/Projekte/www.mercode.org/node_modules/@babel/core/lib/config/full.js:108:6)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

...
```

## 💻 Code Sample

Repo: https://github.com/mercode-org/www.mercode.org/tree/feat/parcel-v2 (note the branch)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2 git edbe2f527625a6dc28bc8c640ce163b5e95fc749
| Node             | node v10.16.3
| npm/Yarn         | yarn 1.17.3
| Operating System | ubuntu 19.04 amd64

**Comment by mkg20001** [comment]
Note that regardless if run with or without custom `.babelrc` the same error happens

**Comment by mkg20001** [comment]
When removing custom `.babelrc` and `@babel` dependencies it gives this error:

```
🚨 core-js@3 is required to use Parcel's babel integration. Detected version 2.6.9.
    at load (/home/maciej/Projekte/parcel/packages/transformers/babel/src/config.js:94:13)
⠹ Building font-awesome.min.css...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Looks like some modules depend on the wrong version of core-js?

```console
$ yarn why core-js
yarn why v1.17.3
warning ../package.json: No license field
[1/4] Why do we have the module "core-js"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "core-js@2.6.9"
info Reasons this module exists
   - "parcel#@parcel#config-default#@parcel#transformer-js#babylon-walk#babel-runtime" depends on it
   - Hoisted from "parcel#@parcel#config-default#@parcel#transformer-js#babylon-walk#babel-runtime#core-js"
info Disk size without dependencies: "7.69MB"
info Disk size with unique dependencies: "7.69MB"
info Disk size with transitive dependencies: "7.69MB"
info Number of shared dependencies: 0
Done in 0.81s.
```

**Comment by padmaia** [comment]
#3507 was just merged and should solve this issue. Could you please try it out and let us know? I get a 404 for the repo URLs in the description by the way.
