### ISSUE TITLE
Cache: RequestGraph empty after failed build?

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#3655]
# 🐛 bug report

```
niklas@nmb:3653-resolver-jsx $ rm -rf .parcel-cache
niklas@nmb:3653-resolver-jsx $ parcel2 build index.html
🚨 Cannot find module './other' from '.../3653-resolver-jsx'
    at ResolverRunner.resolve (parcel/packages/core/core/src/ResolverRunner.js:64:15)
    at RequestGraph.resolvePath (parcel/packages/core/core/src/RequestGraph.js:402:24)
    at PromiseQueue._runFn (parcel/packages/core/utils/src/PromiseQueue.js:81:7)
    at PromiseQueue._next (parcel/packages/core/utils/src/PromiseQueue.js:69:5)
niklas@nmb:3653-resolver-jsx $ parcel2 build index.html
🚨 External modules are not supported when building for browser
    at Object.generateExternalImport (parcel/packages/shared/scope-hoisting/src/formats/global.js:32:9)
    at generateExternalImport (parcel/packages/shared/scope-hoisting/src/link.js:538:25)
```

The resolve error is expected, but the second invocation should produce the same error and not just continue bundling as if nothing happened

## 💻 Code Sample

https://github.com/mischnic/parcel-issue-cache-after-error

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 96c25fa7

**Comment by padmaia** [comment]
Just ran this against v2 and am not seeing the issue, so I'm going to close. I believe this was fixed in #3717.
