### ISSUE TITLE
Error when using template strings: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by just-boris** [parcel-bundler/parcel#3667]
# 🐛 bug report

When I have the following content:

```js
const fs = require('fs');

function readContent(path) {
  return fs.readFileSync(`src/${path}`, 'utf-8');
}

const content = readContent('app.ts');

console.log(content);
```

the parcel build crashes with an error

```
🚨 Cannot read property 'start' of undefined
at MutableAsset.CallExpression (/path/to/project/node_modules/@parcel/transformer-js/lib/visitors/fs.js:59:79)
at NodePath._call (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:53:20)
at NodePath.call (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:40:17)
at NodePath.visit (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:88:12)
at TraversalContext.visitQueue (/path/to/project/node_modules/@babel/traverse/lib/context.js:112:16)
at TraversalContext.visitSingle (/path/to/project/node_modules/@babel/traverse/lib/context.js:84:19)
at TraversalContext.visit (/path/to/project/node_modules/@babel/traverse/lib/context.js:140:19)
at Function.traverse.node (/path/to/project/node_modules/@babel/traverse/lib/index.js:80:17)
at NodePath.visit (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:95:18)
at TraversalContext.visitQueue (/path/to/project/node_modules/@babel/traverse/lib/context.js:112:16)
```

When I modify `readContent` function and replace template strings with normal

```
function readContent(path) {
  return fs.readFileSync(src/' + path, 'utf-8');
}
```

It prints the warning "Cannot statically evaluate fs argument" instead. I guess, in case of template strings it should be the same message.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "demo",
  "version": "1.0.0",
  "files": [],
  "scripts": {
    "build": "parcel build src/test.js"
  },
  "dependencies": {},
  "devDependencies": {
    "parcel": "^1.12.4",

  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 (also tested on 2.0.0-alpha.2.1, the result is the same)
| Node             | v12.13.0
| npm/Yarn         | npm 6.12.0
| Operating System | MacOS Mojave

**Comment by mischnic** [comment]
Probably caused by this line
https://github.com/parcel-bundler/parcel/blob/351aeb73f698cf4877045e25e8937e93766f69de/packages/transformers/js/src/visitors/fs.js#L50

strange that a template literal doesn't have a `loc` property...
