### ISSUE TITLE
Cannot find module 'path-dirname' when running parcel index.html

### ISSUE THREAD

**Issue by Tobi696** [parcel-bundler/parcel#3680]
# 🐛 bug report

I just installed parcel via `npm i -g parcel-bundler`.
Then I created index.html with the basic HTML skeletton in a new folder and ran `parcel index.html` with and without package.json
## 🎛 Configuration (.babelrc, package.json, cli command)

No Babel configuration.

## 🤔 Expected Behavior

It should bundle my index.html

## 😯 Current Behavior

No matter if I try to bundle it with or without package.json, I get following error:
```
(node:4529) UnhandledPromiseRejectionWarning: Error: Cannot find module 'path-dirname'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/usr/local/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/parcel-bundler/node_modules/glob-parent/index.js:5:19)
    at Module._compile (/usr/local/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
(node:4529) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4529) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             |10.15.2
| npm         |6.12.0
| Operating System |Raspbian September 2019

**Comment by mischnic** [comment]
This error happens during startup, a package loaded by Parcel (v8-compile-cache) throws that error. Somehow, `npm i -g parcel-bundler` didn't install all dependencies

**Comment by mischnic** [comment]
Closing due to inactivity
