### ISSUE TITLE
[2.0] Error Installing watcher binaries

### ISSUE THREAD

**Issue by mattdesl** [parcel-bundler/parcel#3706]
# 🐛 bug report

Trying to `npm install parcel@next` and the install fails with errors.

# Env

macOS 10.13.6
node@8.10.0
npm@6.1.0

I realize I could perhaps re-install XCode to fix this but I don't think it should be a necessary dependency for a file watcher.

# Logs

```
> @parcel/watcher@2.0.0-alpha.3 install /projects/2017/texel-modules/texel-experiment/node_modules/@parcel/watcher
> prebuild-install -r napi || node-gyp rebuild

prebuild-install WARN This package does not support N-API version undefined 
prebuild-install WARN install No prebuilt binaries found (target=undefined runtime=napi arch=x64 libc= platform=darwin)
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/matt/.nvm/versions/node/v8.10.0/bin/node" "/Users/matt/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /projects/2017/texel-modules/texel-experiment/node_modules/@parcel/watcher
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN @parcel/transformer-typescript-types@2.0.0-alpha.2.1 requires a peer of typescript@^3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @parcel/watcher@2.0.0-alpha.3 install: `prebuild-install -r napi || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @parcel/watcher@2.0.0-alpha.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mattdesl** [comment]
Update: switching to node `12.11.1` fixes this for me.

**Comment by DeMoorJasper** [comment]
I don't think a lot of binaries are being published for the watcher yet, there's an issue for it https://github.com/parcel-bundler/watcher/issues/10

**Comment by devongovett** [comment]
There are some binaries here... https://github.com/parcel-bundler/watcher/releases/tag/v2.0.0-alpha.3

I guess we need to build against different versions of napi? https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix

**Comment by mischnic** [comment]
Node v8.10.0 only has experimental N-API support, but this should fix it: https://github.com/parcel-bundler/watcher/pull/19

**Comment by DeMoorJasper** [comment]
Didn't we actually drop Node 8 support for Parcel@2?

**Comment by mischnic** [comment]
Right. And it should work with the most Node 8 (8.10.0's NAPI support is only "experimental")
