### ISSUE TITLE
map.eachMapping is not a function

### ISSUE THREAD

**Issue by ricochet1k** [parcel-bundler/parcel#3711]
# 🐛 bug report

Nearly blank repo with custom transformer listed in .parcelrc gives this error:

```
🚨 map.eachMapping is not a function
    at SourceMap.addMap (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@parcel/source-map/lib/SourceMap.js:118:11)
    at /home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@parcel/packager-js/lib/JSPackager.js:109:15
    at enter (/home/matt/.npm-packages/lib/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:475:16)
    at enter (/home/matt/.npm-packages/lib/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:475:16)
    at walk (/home/matt/.npm-packages/lib/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:310:26)
    at walk (/home/matt/.npm-packages/lib/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:331:22)
    at Graph.dfs (/home/matt/.npm-packages/lib/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:355:12)
    at Graph.traverse (/home/matt/.npm-packages/lib/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:257:17)
    at Graph.filteredTraverse (/home/matt/.npm-packages/lib/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:265:17)
    at BundleGraph.traverseBundle (/home/matt/.npm-packages/lib/node_modules/parcel/node_modules/@parcel/core/lib/BundleGraph.js:238:24)
```

It then hangs until ^C is pressed.

Running without a .parcelrc file works as expected.
Running `parcel build index.js` also sorta works as expected, though it seems I don't understand sources and targets in package.json.

Looks like I typed `transformers` instead of `transforms`. Nothing noticed, no error messages?

```js
{
    "extends": ["@parcel/config-default"],
    "transformers": {
        "*.svelte": ["parcel-transformer-svelte"]
    }
}
```

## 💻 Code Sample

Repository to reproduce: https://github.com/ricochet1k/parcel-svelte

Using Parcel 2.0.0-alpha.2.1

**Comment by mischnic** [comment]
Should be fixed now by https://github.com/orlov-vo/parcel-transformer-svelte/pull/3
