### ISSUE TITLE
#<Promise> could not be cloned

### ISSUE THREAD

**Issue by ricochet1k** [parcel-bundler/parcel#3721]
# 🐛 bug report

Parcel prints this error to the console and then builds successfully:

```
🚨 @parcel/cache: #<Promise> could not be cloned.
Error: #<Promise> could not be cloned.
    at Object.serialize (v8.js:283:7)
    at serialize (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/utils/lib/serializer.js:221:21)
    at Cache.set (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/cache/lib/Cache.js:75:39)
    at InternalAsset.commit (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/InternalAsset.js:112:69)
    at /home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Transformation.js:210:31
    at Array.map (<anonymous>)
    at Transformation.writeToCache (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Transformation.js:210:12)
    at Transformation.runPipeline (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Transformation.js:151:18)
    at async Transformation.run (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Transformation.js:97:19)
    at async Child.handleRequest (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/workers/lib/child.js:160:9)
✨ Built in 3.06s.
 
dist/main/index.js     1.38 KB    685ms
├── Foo.svelte         3.77 KB    499ms
└── index.js             142 B    1.04s
 
dist/main/index.css        0 B    684ms
└── Foo.svelte             0 B    499ms
Done in 3.42s.
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Workspaces is there so that the repository can be tested with the latest version of parcel checked out from git, using yalc. They are not necessary to see this issue, but the current 2.0.0-alpha.2.1 doesn't print a stack trace, the latest git version does.

```js
{
    "workspaces": [
        ".yalc/@*/*",
        ".yalc/*"
    ],
    "private": true,
    "devDependencies": {
        "@parcel/config-default": "^2.0.0-alpha.2",
        "@parcel/plugin": "^2.0.0-alpha.2",
        "parcel": "^2.0.0-alpha.2.1",
        "parcel-transformer-svelte": "^1.0.2",
        "svelte": "^3.12.1"
    },
    "source": [
        "index.js",
        "other.js"
    ],
    "targets": {
        "main": {
            "engines": {
                "browsers": [
                    "> 0.2%",
                    "not dead"
                ]
            }
        }
    },
    "scripts": {
        "clean": "rm -r dist .parcel-cache",
        "parcel": "parcel build index.js"
    }
}
```

## 💻 Code Sample

https://github.com/ricochet1k/parcel-svelte/tree/cache-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.2.1

**Comment by mischnic** [comment]
Does this happen only with `parcel-transformer-svelte`?

**Comment by ricochet1k** [comment]
I haven't tried it with anything else. If it is a bug in parcel-transformer-svelte, and you can tell me what the problem is and how to fix it, I will. But this should have a better error message.

Also I should note, I've tried moving the main code into packages/parcel-svelte (similar to parcel's structure) and the `#<Promise> could not be cloned` stops appearing. I'll upload another branch in a second.

**Comment by mischnic** [comment]
I get this with the latest `v2` version: 
```
Error: Dependency did not resolve to an asset
    at MutableBundleGraph.createBundleGroup (/@parcel/core/src/public/MutableBundleGraph.js:54:13)
    at enter (/@parcel/bundler-default/src/DefaultBundler.js:47:41)
    at enter (/@parcel/core/src/Graph.js:572:16)
```

**Comment by mischnic** [comment]
See https://github.com/orlov-vo/parcel-transformer-svelte/pull/3
