### ISSUE TITLE
Parcel tries to include CSS asset in JS bundle when code splitting

### ISSUE THREAD

**Issue by ricochet1k** [parcel-bundler/parcel#3725]
# 🐛 bug report

When adding CSS to a Svelte component, I start getting this error:

```
🚨 Error: Identifier directly after number (1:12)
SyntaxError: Identifier directly after number (1:12)
    at Parser.raise (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:6420:17)
    at Parser.readNumber (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:7335:12)
    at Parser.getTokenFromCode (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:7052:14)
    at Parser.nextToken (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:6630:12)
    at Parser.next (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:6559:10)
    at Parser.parseExprOp (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:8444:14)
    at Parser.parseExprOps (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:8412:17)
    at Parser.parseMaybeConditional (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:8375:23)
    at Parser.parseMaybeAssign (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:8325:21)
    at Parser.parseExpression (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/node_modules/@babel/parser/lib/index.js:8275:23)
```

If you delete everything inside the `<style>` tag, the error goes away.

I cannot figure out how to make parcel give longer stack traces than that, is there a good way to debug this?

## 💻 Code Sample

https://github.com/ricochet1k/parcel-svelte/tree/css-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.2.1 (5e38099a)

**Comment by mischnic** [comment]
Once again, this likely caused by `parcel-transformer-svelte`

> I cannot figure out how to make parcel give longer stack traces than that, is there a good way to debug this?

*Maybe* with `PARCEL_WORKERS=0 yarn parcel build ...`

**Comment by ricochet1k** [comment]
I know that `parcel-transformer-svelte` is likely at fault, but I don't have a clue what would be wrong. Should I post a bug that parcel is difficult to debug? I'm going to try to attach a debugger to parcel now.

The issue seems to be related to bundle splitting. If I change the `import('./Foo.svelte').then(...)` in `other.js` to use a normal import then it works just fine.

**Comment by ricochet1k** [comment]
Okay, I convinced parcel to run under a debugger. The line of code that ends up calling into babel's parser is https://github.com/parcel-bundler/parcel/blob/4868055d024f99a57206e3d0d0f36da1223118ff/packages/shared/scope-hoisting/src/concat.js#L106
And the code it receives is the CSS output from svelte.

So from what I understand, Parcel incorrectly tries to bundle a `css` asset into a `js` bundle when code splitting is used. That sounds like a bug in parcel to me.

**Comment by ricochet1k** [comment]
When run in watch mode, this bug manifests in a different error message:
```
Error: The expression evaluated to a falsy value:

  (0, _assert.default)(!bundle.hasAsset(resolved))

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert.default)(!bundle.hasAsset(resolved))

    at /home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/packager-js/lib/JSPackager.js:79:31
    at enter (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Graph.js:505:16)
    at enter (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Graph.js:505:16)
    at walk (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Graph.js:340:26)
    at walk (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Graph.js:361:22)
    at walk (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Graph.js:361:22)
    at Graph.dfs (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Graph.js:385:12)
    at Graph.traverse (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Graph.js:287:17)
    at Graph.filteredTraverse (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/Graph.js:295:17)
    at BundleGraph.traverseBundle (/home/matt/Dropbox/homesettings/geeky/mycode/parcel-svelte/.yalc/@parcel/core/lib/BundleGraph.js:247:24)
```

In the debugger at JSPackager.js:79 I see `resolved.type` is `'css'`. So the assert is failing because the `css` asset is not supposed to be in the js bundle. Right?

**Comment by mischnic** [comment]
Does this still happen? Please test again with the latest nightly
