### ISSUE TITLE
v1.12.4 fails with "api.caller is not a function" when bundling an HTML file with a <style> tag

### ISSUE THREAD

**Issue by n1313** [parcel-bundler/parcel#3746]
# 🐛 bug report

parcel v1.12.4 fails with "api.caller is not a function" when bundling an HTML file with a `<style>` tag.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:

```json
{
  "name": "parcel",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "start": "parcel index.html --open"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel-bundler": "^1.12.4"
  }
}
```

No other files except for index.html (see below). Running parcel by `npm start`.

## 🤔 Expected Behavior

I should see a page in my browser.

## 😯 Current Behavior

Server fails with error message:

```
Server running at http://localhost:1234
🚨  /path_to_my_repo/node_modules/parcel-bundler/src/builtins/css-loader.js: api.caller is not a function
    at /path_to_my_repo/node_modules/@babel/preset-env/lib/index.js:237:35
    at Object.default (/path_to_my_repo/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12)
    at getEnvPlugins (/path_to_my_repo/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/path_to_my_repo/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)
    at async getBabelConfig (/path_to_my_repo/node_modules/parcel-bundler/src/transforms/babel/config.js:32:19)
    at async babelTransform (/path_to_my_repo/node_modules/parcel-bundler/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/path_to_my_repo/node_modules/parcel-bundler/src/assets/JSAsset.js:83:5)
    at async JSAsset.process (/path_to_my_repo/node_modules/parcel-bundler/src/Asset.js:214:7)
    at async Pipeline.processAsset (/path_to_my_repo/node_modules/parcel-bundler/src/Pipeline.js:46:7)
    at async Pipeline.process (/path_to_my_repo/node_modules/parcel-bundler/src/Pipeline.js:24:23)
```

## 💁 Possible Solution

Removing the `<style>` tag fixes the problem.

## 💻 Code Sample

index.html:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <style type="text/css">
      h1 {
        color: red;
      }
    </style>
  </head>

  <body>
    <h1>Parcel</h1>
  </body>
</html>

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | 12.8.1 |
| npm/Yarn         | npm 6.11.3 |
| Operating System | MacOS 10.14.6 (18G1012) |

**Comment by lmachens** [comment]
Looks like it's related to latest babel update:
https://github.com/babel/babel/pull/10649

**Comment by mischnic** [comment]
@n1313 What version of `@babel/preset-env` are you using in this project?

**Comment by linychuo** [comment]
my terminal also prompt same error **api.caller is not a function**, My parcel version is 1.12.4

**Comment by n1313** [comment]
@mischnic it's @babel/preset-env@7.7.0

**Comment by n1313** [comment]
@mischnic removing node_modules and reinstalling to get @babel/preset-env@7.7.1 installed fixed the problem. Thanks!
