### ISSUE TITLE
Different modules have the same hash value

### ISSUE THREAD

**Issue by MrKou47** [parcel-bundler/parcel#3747]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/MrKou47/parcel-playground

## 🤔 Expected Behavior

The file generated by `parcel build`, different module has same hashname.You can see [this file](https://github.com/MrKou47/parcel-playground/blob/master/build/src.7b44d61f.js),Line-147064, the './block-view' has hashname 'yOt4',and Line-59696,'./registry' has hashname 'yOt4' too.

## 😯 Current Behavior

If i just run `parcel`,everything would be ok.I guess it because use filepath instead of hash to require file.

## 💁 Possible Solution

Maybe we need a config like [webpack optimization.moduleids](https://webpack.js.org/configuration/optimization/#optimizationmoduleids) to solve this problem.

## 💻 Code Sample

https://github.com/MrKou47/parcel-playground

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             |8.11.1
| npm/Yarn         |1.5.1
| Operating System |macos 10.14

**Comment by mischnic** [comment]
Probably a hash collision. Parcel 2 uses longer hashes by default

**Comment by MrKou47** [comment]
> Probably a hash collision. Parcel 2 uses longer hashes by default

Thanks for your reply.I tried parcel@2.0.0-alpha.2.1, `parcel index.html` works fine, but `parcel build index.html` got an error:
```bash
$ parcel build ./src/index.html
(node:34183) Warning: N-API is an experimental feature and could change at any time.
🚨 External modules are not supported when building for browser
    at Object.generateExternalImport (/Users/koubo/workspace/parcel-playground/node_modules/@parcel/scope-hoisting/lib/formats/global.js:37:9)
    at exit (/Users/koubo/workspace/parcel-playground/node_modules/@parcel/scope-hoisting/lib/link.js:540:23)
    at NodePath._call (/Users/koubo/workspace/parcel-playground/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/koubo/workspace/parcel-playground/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/koubo/workspace/parcel-playground/node_modules/@babel/traverse/lib/path/context.js:99:8)
    at TraversalContext.visitQueue (/Users/koubo/workspace/parcel-playground/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/koubo/workspace/parcel-playground/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/koubo/workspace/parcel-playground/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/koubo/workspace/parcel-playground/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/Users/koubo/workspace/parcel-playground/node_modules/@babel/traverse/lib/index.js:66:12)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c parcel build ./src/index.html
```
Looks like https://github.com/parcel-bundler/parcel/issues/3432

**Comment by mtoso** [comment]
I have the same issue of modules with the same hashname. Is switching to Parcel 2 the only option?
