### ISSUE TITLE
Parcel 2: API Could not find a .parcelrc

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3749]
# 🐛 bug report

When trying to use the API, if you import another file which contains imported packages, Parcel throws an `Could not find a .parcelrc` error.

## 🤔 Expected Behavior

It should work as when trying to bundle the same file from the CLI

## 😯 Current Behavior

```
× Could not find a .parcelrc
    at loadParcelConfig (C:\dev\parcelrc-error\node_modules\@parcel\core\lib\loadParcelConfig.js:54:11)
    at async ConfigLoader.loadParcelConfig (C:\dev\parcelrc-error\node_modules\@parcel\core\lib\ConfigLoader.js:68:35)
    at async PromiseQueue._runFn (C:\dev\parcelrc-error\node_modules\@parcel\utils\lib\PromiseQueue.js:94:7)
    at async PromiseQueue._next (C:\dev\parcelrc-error\node_modules\@parcel\utils\lib\PromiseQueue.js:81:5)
```

## 💻 Code Sample

https://github.com/Banou26/parcelrc-error

```js
const Parcel = require('@parcel/core').default
const config = require('@parcel/config-default')

new Parcel({
  // defaultConfig: config,
  entries: ['./src/test.js'],
  targets: {
    test: {
      distDir: 'dist',
      browsers: ['last 1 Chrome versions']
    }
  },
  sourceMaps: true,
  minify: true,
  scopeHoist: true
}).watch((err, build) => {
  if (err) console.error(err)
  console.log('build successful')
})
```

**Comment by mischnic** [comment]
Parcel needs a default config. Either you pass it via `defaultConfig` (the CLI does this for example) or parcel searches for a .parcelrc (which is required in this case).

**Comment by Banou26** [comment]
Well, i tried to pass `@parcel/config-default` in the `defaultConfig` but it also returns an error.
```
× (node:23568) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.relative (path.js:435:5)
    at processConfig (C:\dev\parcelrc-error\node_modules\@parcel\core\lib\loadParcelConfig.js:86:36)
    at create (C:\dev\parcelrc-error\node_modules\@parcel\core\lib\loadParcelConfig.js:71:10)
    at loadParcelConfig (C:\dev\parcelrc-error\node_modules\@parcel\core\lib\loadParcelConfig.js:48:26)
    at async ConfigLoader.loadParcelConfig (C:\dev\parcelrc-error\node_modules\@parcel\core\lib\ConfigLoader.js:68:35)
    at async PromiseQueue._runFn (C:\dev\parcelrc-error\node_modules\@parcel\utils\lib\PromiseQueue.js:94:7)
```

Same error happens with the content of my minimalist `.parcelrc` file passed to `defaultConfig`

**Comment by mischnic** [comment]
You need to pass a filename as well (so Parcel knows from where to resolve the plugin names in the config):

https://github.com/parcel-bundler/parcel/blob/a00fb496e03e145c951d96f93de8a8ab7ea681f1/packages/core/parcel/src/cli.js#L141-L154

so:
```js
const Parcel = require('@parcel/core').default
const config = require('@parcel/config-default')

new Parcel({
  defaultConfig: {
    ...config
    filePath: require.resolve("@parcel/config-default"),
  }
  entries: ['./src/test.js'],
  targets: {
    test: {
      distDir: 'dist',
      browsers: ['last 1 Chrome versions']
    }
  },
  sourceMaps: true,
  minify: true,
  scopeHoist: true
}).watch((err, build) => {
  if (err) console.error(err)
  console.log('build successful')
})
```
