### ISSUE TITLE
🐛babel presets not working

### ISSUE THREAD

**Issue by Alphmega** [parcel-bundler/parcel#375]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .babelrc.js
module.exports = {
  presets: [
    ['@babel/preset-env', {
      target: {
        ie: 10,
        node: true,
        uglify: false
      },
      useBuiltIns: true
    }],
    'flow',
    'stage-1'
  ],
  plugins: [
    'babel-plugin-transform-runtime'
  ]
};
```

error in console

```
⏳  Building...
Server running at http://localhost:1234 
🚨  F:\Project\parcel-vue-example\src\vue-validation.js:83:12: Unexpected token (83:12)
  81 |             fields: {},
  82 |             rules: DEFAULT_RULES,
> 83 |             ...this.$options.validation,
     |             ^
  84 |             [promiseKey]: {}
  85 |           };
  86 |           Object.keys(this.$validation.fields).forEach((fieldName) => {
```

### 🤔 Expected Behavior

babel-preset-stage-1 contains babel-preset-stage-3 whitch contains babel-plugin-transform-object-rest-spread, but babel still not recognizes those syntaxes

### 💁 Possible Solution

I have no idea

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   1.2.1
| Node             |  8.9.3
| npm/Yarn         | npm 5.5.1
| Operating System | Winodws 10 Professional 1709 162299.125

**Comment by Alphmega** [comment]
And i create `.babelrc` file as following
```json
{
  "presets": [
    ["@babel/preset-env", {
      "target": {
        "ie": 10,
        "node": true,
        "uglify": false
      },
      "useBuiltIns": true
    }],
    "flow",
    "stage-1"
  ],
  "plugins": [
    "babel-plugin-transform-runtime"
  ]
}
```
parcel gave me another error

```
⏳  Building...
Server running at http://localhost:51382 - configured port 1234 could not be used.
🚨  Unexpected token :
  "presets": [
           ^

SyntaxError: Unexpected token :
    at NativeCompileCache._moduleCompile (F:\Project\parcel-vue-example\node_modules\v8-compile-cache\v8-compile-cache.js:226:18)
    at Module._compile (F:\Project\parcel-vue-example\node_modules\v8-compile-cache\v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (F:\Project\parcel-vue-example\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (F:\Project\parcel-vue-example\vue.config.js:2:10)
    at Module._compile (F:\Project\parcel-vue-example\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)

```

**Comment by shawwn** [comment]
According to the stack trace, parcel is loading the .babelrc as a
javascript file, not parsing it as JSON.

Where is `parcel-vue-example`? I'd like to check it out.

**Comment by Alphmega** [comment]
`parcel-vue-example` is just my little demo, I can not reproduce the problem, but I created another project that has a similar problem
`babel-preset-stage-1` was installed, but `transform-class-properties` plugin not working
and `preset-flow` was installed, it show me ` Unexpected token` too
[parcel-vue-example.zip](https://github.com/parcel-bundler/parcel/files/1581927/parcel-vue-example.zip)

**Comment by Alphmega** [comment]
When I save the `.babelrc.js` file as a` .babelrc` json file, it throws a previous error
```
Server running at http://localhost:1234
🚨  Unexpected token :
  "presets": [
           ^

SyntaxError: Unexpected token :
    at NativeCompileCache._moduleCompile (F:\Project\parcel-vue-example\node_modules\v8-compile-cache\v8-compile-cache.js:226:18)
    at Module._compile (F:\Project\parcel-vue-example\node_modules\v8-compile-cache\v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (F:\Project\parcel-vue-example\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (F:\Project\parcel-vue-example\vue.config.js:2:10)
    at Module._compile (F:\Project\parcel-vue-example\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
```

**Comment by shawwn** [comment]
at Object.<anonymous> (F:\Project\parcel-vue-example\vue.config.js:2:10)


What's at vue.config.js line 2?

I'll check out the zip file soon.

**Comment by devongovett** [comment]
@Alphmega Parcel isn't using Babel 7 yet, which added support for `.babelrc.js`. Babel 6 supports only JSON. Looks like you already tried that, but got a parse error in the JSON. This is because your `vue.config.js` is requiring it as a JS file.

I fixed it with 2 changes:

1. converted the `.babelrc.js` to JSON (`.babelrc`).
2. modified `vue.config.js` to read the file as JSON instead:

```javascript
module.exports = {
  babel: JSON.parse(require('fs').readFileSync('./.babelrc', 'utf8'))
};
```

**Comment by Alphmega** [comment]
@devongovett 
I fixed the problem you pointed out, but this example still does not work. Since parcel did not merge the babel-runtime modules to app.js, the browser throws the following error
```
Uncaught Error: Cannot find module 'babel-runtime/helpers/classCallCheck'
    at newRequire (f881b8b3da0f88a0165bf55ba835462c.js:32)
    at localRequire (f881b8b3da0f88a0165bf55ba835462c.js:38)
    at Object.require.4 (f881b8b3da0f88a0165bf55ba835462c.js:71)
    at newRequire (f881b8b3da0f88a0165bf55ba835462c.js:46)
    at require.4 (f881b8b3da0f88a0165bf55ba835462c.js:63)
    at f881b8b3da0f88a0165bf55ba835462c.js:68
```
parcel only uses previousRequire to run the babel-runtime module, but require is undefined for the browser
How can i handler these errors

**Comment by Topthinking** [comment]
.babelrc
```json
{
    "presets": [
        "react",
        "es2015",
        "stage-0"
    ],
    "plugins": [
        "transform-decorators-legacy",
        "transform-runtime"
    ]
}
```

```error
Uncaught Error: Cannot find module 'babel-runtime/core-js/symbol/to-primitive'
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:32)
    at localRequire (ccfdca706170b05661250a9fa899b9e8.js:47)
    at Object.require.10 (ccfdca706170b05661250a9fa899b9e8.js:18751)
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:41)
    at localRequire (ccfdca706170b05661250a9fa899b9e8.js:47)
    at Object.require.3.babel-runtime/core-js/object/define-property (ccfdca706170b05661250a9fa899b9e8.js:22245)
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:41)
    at localRequire (ccfdca706170b05661250a9fa899b9e8.js:47)
    at Object.require.2.react (ccfdca706170b05661250a9fa899b9e8.js:22316)
    at newRequire (ccfdca706170b05661250a9fa899b9e8.js:41)
```
