### ISSUE TITLE
Is it possible that loading a node package bundled with Parcel stops the import statements to work

### ISSUE THREAD

**Issue by RPDeshaies** [parcel-bundler/parcel#3766]
# ❔ Question

Is it possible that loading a node package bundled with Parcel stops the import statements to work ?

## 🔦 Context

I'm using parcel to bundle a `common` package used by a "client" and a "server".

Both my client and my server are bundled with Parcel and I was looking into using the following code to bundle my common package as well

`parcel build common.ts --target node --bundle-node-modules` 

I have the impression I'm either doing something wrong or Parcel doesn't support that particular usecase since I get the following error

## 💻 Code Sample

```
Error: Cannot find module 'react-dom/server'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at newRequire (/Users/me/my-project/packages/common/dist/common/common.js:34:18)
```

The thing is, my `common` package doesn't use React. But `server` does and `servers` uses `common`

My guess is that parcel reassigns the global variable `parcelRequire` when you load a package bundled with parcel

```
parcelRequire = (function (modules, cache, entry, globalName) {
```

Which then deletes `react-dom/server` from the list of possible requires

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v8.11.2
| npm/Yarn         | 6.11.3
| Operating System | MacOS Mojave

**Comment by Banou26** [comment]
I haven't had much success with bundling libraries with parcel either.
I'd suggest you use rollup to bundle libraries
I think parcel 2 intends to be able to bundle parcel with parcel, so i guess this would probably good to try back with parcel 2 once it's somewhat stable

**Comment by DeMoorJasper** [comment]
Parcel 2 has targets that are specific for bundling libraries and node code. Which should resolve this, parcel 1 works for libraries as well if using scope hoisting but that’s an experimental feature in parcel 1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
Could someone provide an example for this?

**Comment by mischnic** [comment]
Closing due to inactivity
