### ISSUE TITLE
Directory misdetected as Browserslist config

### ISSUE THREAD

**Issue by akx** [parcel-bundler/parcel#3768]
# 🐛 bug report

When traversing the file system, `asset.getConfig()` does not seem to check whether a name is a directory or a file. 

My project lives in `/Users/akx/build/my-project` (name changed to protect the innocent) and I happen to have been tinkering at browserslist proper at `/Users/akx/build/browserslist/`. When trying to find a browserslist configuration, Parcel finds that path, but doesn't realize it's a directory before it passes it on to the `browserslist` module.

## 🎛 Configuration (.babelrc, package.json, cli command)

Elided, shouldn't matter.

## 🤔 Expected Behavior

Parcel shouldn't crash when there's a browserslist directory in the directory tree.

## 😯 Current Behavior

```
🚨  /Users/akx/build/my-project/node_modules/parcel-bundler/src/builtins/css-loader.js: Can't read /Users/akx/build/browserslist config
    at Function.readConfig (/Users/akx/build/my-project/node_modules/browserslist/node.js:237:13)
    at loadBrowserslist (/Users/akx/build/my-project/node_modules/parcel-bundler/src/utils/getTargetEngines.js:112:25)
    at async getTargetEngines (/Users/akx/build/my-project/node_modules/parcel-bundler/src/utils/getTargetEngines.js:42:26)
    at async getEnvConfig (/Users/akx/build/my-project/node_modules/parcel-bundler/src/transforms/babel/env.js:11:23)
    at async getBabelConfig (/Users/akx/build/my-project/node_modules/parcel-bundler/src/transforms/babel/config.js:32:19)
    at async babelTransform (/Users/akx/build/my-project/node_modules/parcel-bundler/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/Users/akx/build/my-project/node_modules/parcel-bundler/src/assets/JSAsset.js:83:5)
    at async JSAsset.process (/Users/akx/build/my-project/node_modules/parcel-bundler/src/Asset.js:214:7)
    at async Pipeline.processAsset (/Users/akx/build/my-project/node_modules/parcel-bundler/src/Pipeline.js:46:7)
    at async Pipeline.process (/Users/akx/build/my-project/node_modules/parcel-bundler/src/Pipeline.js:24:23)
```

## 💁 Possible Solution

Make `asset.getConfig()` (optionally?) only allow files, not directories.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.12.0
| npm/Yarn         | 1.19.1
| Operating System | macOS 10.14

**Comment by AniaProkopHelpMeAndFuckMeAnal** [comment]
![PICT0107](https://user-images.githubusercontent.com/49832891/68662291-d81a4b80-053c-11ea-9993-8d9f68cd7290.JPG)
Zerznij mnie teraz
