### ISSUE TITLE
extension does not match bundle type "undefined"

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#3802]
# 🐛 bug report

```
🚨 @parcel/namer-default: Destination name test.5e747530.undefined extension does not match bundle type "undefined"
Error: Destination name test.5e747530.undefined extension does not match bundle type "undefined"
    at BundlerRunner.nameBundle (/parcel/packages/core/core/src/BundlerRunner.js:181:19)
    at async Promise.all (index 1)
    at BundlerRunner.nameBundles (/parcel/packages/core/core/src/BundlerRunner.js:150:5)
    at BundlerRunner.bundle (/parcel/packages/core/core/src/BundlerRunner.js:110:5)
    at Parcel.build (/parcel/packages/core/core/src/Parcel.js:257:25)
    at Parcel.run (/parcel/packages/core/core/src/Parcel.js:145:18)
    at Command.run (/parcel/packages/core/parcel/src/cli.js:203:7)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
	"browserslist": [
		"Chrome 70"
	]
}

```

test.html:
```html
<script type="module">import("./lib.js").then(console.log);</script>;
```

lib.js:
```js
for (let v of ["a", "b", "c"]) {
	module.exports[v] = v;
}

module.exports = "xyz";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |3187c169
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Seems fixed
