### ISSUE TITLE
Circular reexport: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#3810]
# 🐛 bug report

## 🤔 Expected Behavior

We should catch this properly and throw a helpful error.

## 😯 Current Behavior

```
🚨 @parcel/packager-js: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Graph.getNodesConnectedFrom (parcel/packages/core/core/src/Graph.js:145:24)
    at getChildren (parcel/packages/core/core/src/Graph.js:355:33)
    at walk (parcel/packages/core/core/src/Graph.js:427:25)
    at Graph.dfs (parcel/packages/core/core/src/Graph.js:455:12)
    at Graph.traverse (parcel/packages/core/core/src/Graph.js:352:17)
    at BundleGraph.getDependencyResolution (parcel/packages/core/core/src/BundleGraph.js:207:17)
    at BundleGraph.resolveSymbol (parcel/packages/core/core/src/BundleGraph.js:535:29)
    at BundleGraph.resolveSymbol (parcel/packages/core/core/src/BundleGraph.js:545:18)
    at BundleGraph.resolveSymbol (parcel/packages/core/core/src/BundleGraph.js:545:18)
    at BundleGraph.resolveSymbol (parcel/packages/core/core/src/BundleGraph.js:545:18)
```

## 💻 Code Sample

```js
// entry.js
export {c} from './b';

// b.js
export {c} from './c';

// c.js
export {c} from './d';

// d.js
export {c} from './c';
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2

**Comment by mischnic** [comment]
Chrome: `Uncaught SyntaxError: Detected cycle while resolving name 'c' in './d.js'`
