### ISSUE TITLE
Parcel 2.0.0-alpha.3.2: * could not be cloned.

### ISSUE THREAD

**Issue by a-x-** [parcel-bundler/parcel#3833]
# 🐛 bug report

I have usual react project with webpack, babel@7, postcss@7 etc. And I tries to use parcel now. Parcel@1 is working good. But parcel@next show misterious error (see below).

1. I found, that `fn(...args, function (err, ...re` is from `@parcel/utils/lib/promisify.js:4:17`
2. Next I added more useful stacktrace using `console.error(new Error("i'm here"))` in lib/promisify.js (see below original error)
3. I had not found any `'could not be cloned'` in node_modules, so looks it comes from Node.js. DOMException says about it too.

```
❯ parcel build src/index.jsx
DOMException [DataCloneError]: function (...args) {
    return new Promise(function (resolve, reject) {
      fn(...args, function (err, ...re...<omitted>... } could not be cloned.
    at Worker.postMessage (internal/worker.js:223:23)
    at ThreadsWorker.send (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:62:17)
    at Worker.send (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:81:17)
    at Worker.call (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:91:10)
    at WorkerFarm.processQueue (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/node_modules/@parcel/workers/lib/WorkerFarm.js:225:16)
    at Worker.<anonymous> (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/node_modules/@parcel/workers/lib/WorkerFarm.js:182:35)
    at Worker.emit (events.js:210:5)
    at Worker.fork (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:77:10)
```

useful stacktrace:
```
    at module.exports (/Users/mxtnr/rocket/felix/front/node_modules/parcel/node_modules/@parcel/utils/lib/promisify.js:4:17)
    at new NodeFS (/Users/mxtnr/rocket/felix/front/node_modules/parcel/node_modules/@parcel/fs/lib/NodeFS.js:48:58)
    at Command.run (/Users/mxtnr/rocket/felix/front/node_modules/parcel/lib/cli.js:97:63)
    at Command.listener (/Users/mxtnr/rocket/felix/front/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (/Users/mxtnr/rocket/felix/front/node_modules/commander/index.js:654:12)
    at Command.parse (/Users/mxtnr/rocket/felix/front/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/mxtnr/rocket/felix/front/node_modules/parcel/lib/cli.js:85:9)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
```

## 🎛 Configuration 

Ok, I attached my configs, by parcel fails before it read any of them.
When I install parcel into empty directory all going perfect.

<details><summary>cli command, .babelrc, .postcssrc, package.json,,,</summary>

`parcel build test.jsx`

.babelrc
```json
{
      "plugins": [],
      "presets": [
        ["@babel/env", {
          "targets": {
          },
          "modules":     false,
          "useBuiltIns": false,
          "loose":       true
        }],
      ]
}
```

package.json (part)
```json
{
  "name": "front",
  "version": "0.0.0",
  "main": "src/index.jsx",
  "dependencies": {
    "react": "^16.11.0",
  },
  "devDependencies": {
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "parcel": "^2.0.0-alpha.3.2",
    "postcss-modules": "^1.4.1",
  },
  "alias": {
    "src": "./src",
    "utils": "./src/utils",
    "components": "./src/components",
    "public": "./src/public",
    "layouts": "./src/layouts",
    "actions": "./src/actions",
    "containers": "./src/containers",
    "pages": "./src/pages",
    "reducers": "./src/reducers",
    "widgets": "./src/widgets"
  },
```

.postcssrc
```json
{
  "modules": true,
  "plugins": {
    "postcss-import": {},
    "postcss-preset-env":  {
      "features": {},
      "autoprefixer": {
        "flexbox": false,
      }
    },
    "postcss-nested": {}
  },
  "sourceMap": true,
}
```

.browserslistrc
```json
last 2 Chrome version
last 1 Safari version
```

</details>

## 💁 Possible Solution

Looks like parcel tried to send function via PostMessage...

## 💻 Code Sample

it's no matter, parcel fails before it can read any source code

src/test.jsx
```jsx
export function foo () {}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.13.0
| npm/Yarn         | 6.12.1/1.13.0
| Operating System | macos 10.14.6 mojave

**Comment by mischnic** [comment]
> Looks like parcel tried to send function via PostMessage...

Indeed


I tried to reproduce this with your config files, but no error is thrown?

**Comment by a-x-** [comment]
Next, I added console log at
node_modules/@parcel/core/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:62:17

  send(data) {
    console.log('>>', _utils.prepareForSerialization(data))
    this.worker.postMessage((0, _utils.prepareForSerialization)(data));
  }

```
{
  type: 'request',
  idx: 1,
  child: 2,
  handle: undefined,
  method: 'runTransform',
  args: [ { request: [Object], options: [Object] }, false ]
}
```

hm, look into `args[0]` more detailed:

```json
{
  request: {
    filePath: '/Users/mxtnr/rocket/felix/front/src/test.jsx',
    sideEffects: undefined,
    code: undefined,
    env: {
      context: 'node',
      engines: [Object],
      includeNodeModules: false,
      outputFormat: 'commonjs',
      isLibrary: true
    },
    pipeline: 'main'
  },
  options: {
    config: undefined,
    defaultConfig: {
      bundler: '@parcel/bundler-default',
      transforms: [Object],
      namers: [Array],
      runtimes: [Object],
      optimizers: [Object],
      packagers: [Object],
      resolvers: [Array],
      reporters: [Array],
      filePath: '/Users/mxtnr/rocket/felix/front/node_modules/@parcel/config-default/index.json'
    },
    patchConsole: false,
    env: {},
    mode: 'production',
    minify: true,
    autoinstall: true,
    hot: false,
    serve: false,
    disableCache: false,
    killWorkers: true,
    profile: false,
    cacheDir: '/Users/mxtnr/rocket/felix/front/.parcel-cache',
    entries: [ '/Users/mxtnr/rocket/felix/front/src/test.jsx' ],
    rootDir: '/Users/mxtnr/rocket/felix/front/src',
    defaultEngines: undefined,
    targets: null,
    sourceMaps: true,
    scopeHoist: true,
    logLevel: 'info',
    projectRoot: '/Users/mxtnr/rocket/felix/front',
    lockFile: '/Users/mxtnr/rocket/felix/front/package-lock.json',
    inputFS: { '$$type': '2.0.0-alpha.3.1:NodeFS', '$$raw': true, value: {} },
    outputFS: { '$$type': '2.0.0-alpha.3.1:NodeFS', '$$raw': true, value: {} },
    cache: Cache {
      fs: [Object],
      dir: '/Users/mxtnr/rocket/felix/front/.parcel-cache'
    },
    packageManager: NodePackageManager {
      fs: [NodeFS],
      installer: undefined,
      cache: [Map]
    }
  }
}
```

LOOOOK: `[NodeFS]`. So `NodeFS` is related with `@parcel/fs/lib/NodeFS.js` and so `@parcel/utils/lib/promisify.js`

**Comment by a-x-** [comment]
Next I removed `packageManager` for `request` with  method === `runTransform` from `args[0].options`

And replaced it by:
```js
var NodePackageManager = require('@parcel/package-manager').NodePackageManager;
var NodeFS = require('@parcel/fs').NodeFS;
var packageManager = new NodePackageManager(new NodeFS());
```
in all the places

Currently I have weird error:
```
TypeError: this.options.cache.get is not a function
    at Transformation.readFromCache (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/lib/Transformation.js:221:49)
    at Transformation.runPipeline (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/lib/Transformation.js:172:40)
    at Transformation.run (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/lib/Transformation.js:107:30)
    at async Child.handleRequest (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/node_modules/@parcel/workers/lib/child.js:162:9)
```

**Comment by a-x-** [comment]
ok I run `parcel build src/index.jsx` 

And I have new 3th error:
```
🚨 Error: Cannot find module '~public/logo3.png' from '/Users/mxtnr/rocket/felix/front/src'
Error: Cannot find module '~public/logo3.png' from '/Users/mxtnr/rocket/felix/front/src'
    at ResolverRunner.resolve (/Users/mxtnr/rocket/felix/front/node_modules/@parcel/core/lib/ResolverRunner.js:124:15)
```

This error is not pointing any my source file, but I found ` '~public/logo3.png'` at my `src/felix1.5-theme.css` file:
```css
.felix-1-5 h1#site_title {
  background: url(~public/logo3.png) center center no-repeat / 30px;
}
```

**Comment by a-x-** [comment]
... but fails on `'runPackage'`  method now, in a addition to `'runTransform'`, I mentioned above

**Comment by a-x-** [comment]
# Summary

### What nice to fix
1. don't pass options.cache and options.packageManager through workers. Import them directly instead 
2. improve some error informativity (e.g. `Destination name index.jsx extension does not match bundle type "js"
` should include full path to file)

### Some questions
3. why ~ was not work for me [here](https://github.com/parcel-bundler/parcel/issues/3833#issuecomment-557708011)?

**Comment by mischnic** [comment]
> don't pass options.cache and options.packageManager through workers. Import them directly instead

No, there is a reason it's done this way. And I still can't reproduce this issue locally!

**Comment by rlittlefield** [comment]
I'm getting the same error. Doesn't happen on a new project, just my existing ones. I'll see if I can find a subset of the code that causes this.

**Comment by pke** [comment]
I also run into this error. Parcel@1.x.x worked fine. I deleted the cache folder but the error keeps coming up:

```
 Error: function (...args) {
    return new Promise(function (resolve, reject) {
      fn(...args, function (err, ...re...<omitted>... } could not be cloned.
DataCloneError: function (...args) {
    return new Promise(function (resolve, reject) {
      fn(...args, function (err, ...re...<omitted>... } could not be cloned.
    at Worker.postMessage (internal/worker.js:223:23)

```

**Comment by mischnic** [comment]
@pke Can you provide a reproduction?

**Comment by pke** [comment]
@mischnic I tried to reproduce, but couldn't. It now gives me:

```
🚨 Error: Received URL without a pathname.
Error: Received URL without a pathname.
    at ResolverRunner.resolve (/var/node_modules/@parcel/core/lib/ResolverRunner.js:80:15)
    at async DepPathRequestRunner.runRequest (/var/node_modules/@parcel/core/lib/RequestTracker.js:356:43)
    at async Promise.all (index 19)
```

Which was not very helpful, cause it omitted the URL. I've created a PR #3968 to find out whats going on.

I think the original error originated maybe from a insufficient number of avail inotify handles on the system, cause parcel@1 watcher reported an error with inotify handles. Once I solved them parcel@1 ran ok but parcel@2 prints out this new error message.

**Comment by fregante** [comment]
I'm having that issue here https://github.com/sindresorhus/refined-github/tree/WIP-parcel

It's not a _minimal_ example but perhaps it can be useful.

I'm just running `parcel build source/content.ts` and the error appears even if `content.ts` is empty. It must be some configuration or dependency conflict.

Node v10.18.1 (or v12.14.1)
Parcel 2.0.0-alpha.3.2
macOS 10.15.2

**Comment by mischnic** [comment]
I think I've found the problem (it works with Yarn and is broken with npm):
Some Parcel classes like `MemoryFS` or `NodePackageManager` register themselves to make sure they are serialized properly (because the structured cloning algorithm between worker threads doesn't support among others functions).
For that, the individual plugins called 
```js
import {registerSerializableClass} from '@parcel/utils';

class XYZ {}
registerSerializableClass(version, XYZ);
```
The cache in `@parcel/core` would then use that list of classes to prepare objects:
```js
import {
  prepareForSerialization,
  restoreDeserializedObject,
} from '@parcel/utils';

this.worker.postMessage(prepareForSerialization(data));
```

Yarn hoists the dependencies and so `@parcel/utils` (and the classes list) exists only once.

<details>
<summary>With npm however, every package get's its own list, so that objects of these classes aren't replaced and therefore cloning fails</summary>
./parcel/node_modules/@parcel/utils/src/serializer.js
./@parcel/optimizer-data-url/node_modules/@parcel/utils/src/serializer.js
./@parcel/reporter-cli/node_modules/@parcel/utils/src/serializer.js
./@parcel/resolver-default/node_modules/@parcel/utils/src/serializer.js
./@parcel/packager-css/node_modules/@parcel/utils/src/serializer.js
./@parcel/core/node_modules/@parcel/utils/src/serializer.js
./@parcel/cache/node_modules/@parcel/utils/src/serializer.js
./@parcel/package-manager/node_modules/@parcel/utils/src/serializer.js
./@parcel/packager-js/node_modules/@parcel/utils/src/serializer.js
./@parcel/transformer-html/node_modules/@parcel/utils/src/serializer.js
./@parcel/runtime-browser-hmr/node_modules/@parcel/utils/src/serializer.js
./@parcel/packager-html/node_modules/@parcel/utils/src/serializer.js
./@parcel/transformer-postcss/node_modules/@parcel/utils/src/serializer.js
./@parcel/runtime-js/node_modules/@parcel/utils/src/serializer.js
./@parcel/optimizer-terser/node_modules/@parcel/utils/src/serializer.js
./@parcel/transformer-js/node_modules/@parcel/utils/src/serializer.js
./@parcel/transformer-stylus/node_modules/@parcel/utils/src/serializer.js
./@parcel/bundler-default/node_modules/@parcel/utils/src/serializer.js
./@parcel/source-map/node_modules/@parcel/utils/src/serializer.js
./@parcel/transformer-babel/node_modules/@parcel/utils/src/serializer.js
./@parcel/reporter-hmr-server/node_modules/@parcel/utils/src/serializer.js
./@parcel/transformer-coffeescript/node_modules/@parcel/utils/src/serializer.js
./@parcel/scope-hoisting/node_modules/@parcel/utils/src/serializer.js
./@parcel/transformer-sass/node_modules/@parcel/utils/src/serializer.js
./@parcel/reporter-dev-server/node_modules/@parcel/utils/src/serializer.js
./@parcel/optimizer-htmlnano/node_modules/@parcel/utils/src/serializer.js
./@parcel/transformer-react-refresh-wrap/node_modules/@parcel/utils/src/serializer.js
</details>

**Comment by fregante** [comment]
> With npm however, every package get's its own list, so that objects of these classes aren't replaced and therefore cloning fails

What?! Why aren't they getting deduplicated? 😅

**Comment by mischnic** [comment]
Mh, which npm version are you using?
I just tried it again and:
```
node_modules $ find . -name "serializer.js"
./whatwg-mimetype/lib/serializer.js
./@parcel/utils/lib/serializer.js
./@parcel/utils/src/serializer.js
node_modules $ npm -v
6.13.4
```

**Comment by fregante** [comment]
```sh
❯ npm --version
6.13.4
```

Here's the full log after deleting `node_modules` (but same package-log.json)

<details>
<summary>npm i</summary>

```
> dtrace-provider@0.8.8 install ./node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> deasync@0.1.19 install ./node_modules/deasync
> node ./build.js

`darwin-x64-node-12` exists; testing
Binary is fine; exiting

> fsevents@1.2.11 install ./node_modules/watchpack/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> @parcel/watcher@2.0.0-alpha.4 install ./node_modules/@parcel/core/node_modules/@parcel/watcher
> prebuild-install -r napi || node-gyp rebuild


> @parcel/watcher@2.0.0-alpha.4 install ./node_modules/@parcel/package-manager/node_modules/@parcel/watcher
> prebuild-install -r napi || node-gyp rebuild


> @parcel/watcher@2.0.0-alpha.4 install ./node_modules/@parcel/transformer-sass/node_modules/@parcel/watcher
> prebuild-install -r napi || node-gyp rebuild


> @parcel/watcher@2.0.0-alpha.4 install ./node_modules/parcel/node_modules/@parcel/watcher
> prebuild-install -r napi || node-gyp rebuild


> core-js@3.6.3 postinstall ./node_modules/@parcel/transformer-babel/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.11 postinstall ./node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall ./node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> spawn-sync@1.0.15 postinstall ./node_modules/spawn-sync
> node postinstall

added 2770 packages from 1368 contributors and audited 38857 packages in 48.693s

54 packages are looking for funding
  run `npm fund` for details

found 196 vulnerabilities (49 moderate, 49 high, 98 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

```

</details>
<details>
<summary>npm run build</summary>

```
> @ build .
> parcel build source/content.ts

🚨 Error: function (...args) {
    return new Promise(function (resolve, reject) {
      fn(...args, function (err, ...re...<omitted>... } could not be cloned.
DataCloneError: function (...args) {
🚨 Error: function (...args) {
    return new Promise(function (resolve, reject) {
      fn(...args, function (err, ...re...<omitted>... } could not be cloned.
DataCloneError: function (...args) {
    return new Promise(function (resolve, reject) {
      fn(...args, function (err, ...re...<omitted>... } could not be cloned.
    at Worker.postMessage (internal/worker.js:223:23)
    at ThreadsWorker.send 
(./node_modules/@parcel/core/no
de_modules/@parcel/workers/lib/threads/ThreadsWorker.js:62:17)
    at Worker.send (./node_modu
les/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:81:17)
    at Worker.call (./node_modu
les/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:91:10)
    at WorkerFarm.processQueue 
(./node_modules/@parcel/core/no
de_modules/@parcel/workers/lib/WorkerFarm.js:225:16)
    at ./node_modules/@parcel/c
ore/node_modules/@parcel/workers/lib/WorkerFarm.js:315:12
    at new Promise (<anonymous>)
    at WorkerFarm.addCall (./no
de_modules/@parcel/core/node_modules/@parcel/workers/lib/WorkerFarm.js:307:12)
    at AssetRequestRunner.runTransform 
(./node_modules/@parcel/core/no
de_modules/@parcel/workers/lib/WorkerFarm.js:155:21)
    at AssetRequestRunner.run (./node_modules/@parcel/core/lib/requests.js:118:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `parcel build source/content.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-01-20T16_13_53_218Z-debug.log
```

</details>

<details>
<summary>find . -name "serializer.js"</summary>


```
./node_modules/parcel/node_modules/@parcel/utils/lib/serializer.js
./node_modules/parcel/node_modules/@parcel/utils/src/serializer.js
./node_modules/fluent-syntax/src/serializer.js
./node_modules/whatwg-mimetype/lib/serializer.js
./node_modules/@parcel/optimizer-data-url/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/optimizer-data-url/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/reporter-cli/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/reporter-cli/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/resolver-default/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/resolver-default/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/packager-css/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/packager-css/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/core/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/core/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/cache/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/cache/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/package-manager/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/package-manager/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/packager-js/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/packager-js/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/transformer-html/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/transformer-html/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/runtime-browser-hmr/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/runtime-browser-hmr/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/packager-html/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/packager-html/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/transformer-postcss/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/transformer-postcss/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/runtime-js/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/runtime-js/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/optimizer-terser/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/optimizer-terser/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/transformer-js/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/transformer-js/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/transformer-stylus/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/transformer-stylus/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/bundler-default/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/bundler-default/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/source-map/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/source-map/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/transformer-babel/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/transformer-babel/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/reporter-hmr-server/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/reporter-hmr-server/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/transformer-coffeescript/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/transformer-coffeescript/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/scope-hoisting/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/scope-hoisting/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/transformer-sass/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/transformer-sass/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/reporter-dev-server/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/reporter-dev-server/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/optimizer-htmlnano/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/optimizer-htmlnano/node_modules/@parcel/utils/src/serializer.js
./node_modules/@parcel/transformer-react-refresh-wrap/node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/transformer-react-refresh-wrap/node_modules/@parcel/utils/src/serializer.js

```

</details>

**Comment by fregante** [comment]
Classic. I had to delete `package-lock.json` to have this result after `npm install`:

```
❯ find . -name "serializer.js"
./node_modules/fluent-syntax/src/serializer.js
./node_modules/whatwg-mimetype/lib/serializer.js
./node_modules/@parcel/utils/lib/serializer.js
./node_modules/@parcel/utils/src/serializer.js
```

Now the build seems to work 👍

**Comment by mischnic** [comment]
Should be somewhat fixed by https://github.com/parcel-bundler/parcel/pull/4018
