### ISSUE TITLE
Node 13.x not supported

### ISSUE THREAD

**Issue by stevenvachon** [parcel-bundler/parcel#3835]
## 🤔 Expected Behavior
It should install and build.

## 😯 Current Behavior
When building:
```
(node:9012) UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file. Tried:
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             |13.2.0
| npm/Yarn         |6.13.1
| Operating System | macOS 10.15.1

**Comment by DeMoorJasper** [comment]
That’s probably an issue with deasync. Could you give the full stacktrace?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
You might need to update your lockfile so that deasync v0.1.16 is used.

**Comment by Eward-Wang** [comment]
I try re-install parcel-bundler by yarn(v1.19.2), and it work good again;    

`yarn global add parcel-bundler`;

**Comment by stevenvachon** [comment]
It's working correctly now. I'd had Xcode CLT issues.

**Comment by ogomez92** [comment]
I'm having a similar issue. Happened right after upgrading to Node 13:

(base) MacBook-Pro-de-oriol:road uri$ npm run build

> roadsplat@4.0.1 build /Users/uri/git/road
> parcel build ./js/main.js -d . --target=electron

🚨  Cannot read property 'length' of undefined
    at lineCounter (/Users/uri/git/road/node_modules/parcel-bundler/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/Users/uri/git/road/node_modules/parcel-bundler/src/packagers/JSPackager.js:127:60)
    at async JSPackager.addAsset (/Users/uri/git/road/node_modules/parcel-bundler/src/packagers/JSPackager.js:88:5)
    at async Bundle._addDeps (/Users/uri/git/road/node_modules/parcel-bundler/src/Bundle.js:250:5)
    at async Bundle._package (/Users/uri/git/road/node_modules/parcel-bundler/src/Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (/Users/uri/git/road/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Bundler.bundle (/Users/uri/git/road/node_modules/parcel-bundler/src/Bundler.js:325:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! roadsplat@4.0.1 build: `parcel build ./js/main.js -d . --target=electron`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the roadsplat@4.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/uri/.npm/_logs/2020-04-20T09_33_53_350Z-debug.log
(base) MacBook-Pro-de-oriol:road uri$ npm -v
6.14.4
(base) MacBook-Pro-de-oriol:road uri$ node -v
v13.13.0
(base) MacBook-Pro-de-oriol:road uri$
