### ISSUE TITLE
Build fails on Zeit Now

### ISSUE THREAD

**Issue by partheseas** [parcel-bundler/parcel#3857]
# 🐛 bug report
When trying to deploy a project which uses Parcel 2 to Zeit Now an error is produced.
Runs fine locally.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "lowowee",
  "version": "1.0.0",
  "license": "MIT",
  "browser": "public/index.html",
  "dependencies": {
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "rxjs": "^6.5.3",
    "styled-components": "^4.4.1"
  },
  "devDependencies": {
    "@types/react": "^16.9.13",
    "@types/react-dom": "^16.9.4",
    "parcel": "^2.0.0-alpha.3.2",
    "sass": "^1.23.7",
    "typescript": "^3.7.2"
  },
  "scripts": {
    "build": "parcel build client/index.html",
    "dev": "parcel client/index.html"
  }
}
```

## 🤔 Expected Behavior

Build should succeed.

## 😯 Current Behavior

```
Installing build runtime...
Build runtime installed: 529.846ms
Looking up build cache...
Installing dependencies...
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 13.10s.
Running "yarn run build"
yarn run v1.17.3
$ parcel build client/index.html && mv dist public
/zeit/431d848/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /lib64/libc.so.6: version `GLIBC_2.23' not found (required by /zeit/431d848/node_modules/@parcel/watcher/build/Release/watcher.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/zeit/431d848/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/zeit/431d848/node_modules/@parcel/watcher/index.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Exited with 1
    at ChildProcess.child.on (/zeit/b541d31f72d62b8b/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:31591:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
worker exited with code 20 and signal null
done
```

## 💁 Possible Solution

The issue seems to be related to the file watcher. A possibly solution is to not load the file watcher when running in build mode.

## 🔦 Context

Issue prevents Parcel 2 from being used in my primary deployment environment.

## 💻 Code Sample

Error results from a simple test project with a single html file, a single scss file, and a single tsx file, that are all nearly empty.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | Unknown
| Yarn         | 1.17.3
| Operating System | Linux (Zeit Now)

**Comment by mischnic** [comment]
Please follow this issue: https://github.com/parcel-bundler/watcher/issues/18
