### ISSUE TITLE
Error: Cannot find module './src/data'

### ISSUE THREAD

**Issue by haansn08** [parcel-bundler/parcel#3864]
# 🐛 bug report

Something broke really badly. 😬

## 😯 Current Behavior

```

> parcel-issue@1.0.0 start /home/stefan/playground/parcel-issue
> parcel src/index.html

Server running at http://localhost:1234 
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/index.js". Threw the following error:
Error: Cannot find module './src/data'
Require stack:
- /home/stefan/playground/parcel-issue/node_modules/core-js-compat/helpers.js
- /home/stefan/playground/parcel-issue/node_modules/core-js-compat/get-modules-list-for-target-version.js
- /home/stefan/playground/parcel-issue/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/stefan/playground/parcel-issue/node_modules/@babel/preset-env/lib/index.js
- /home/stefan/playground/parcel-issue/node_modules/parcel/src/transforms/babel/env.js
- /home/stefan/playground/parcel-issue/node_modules/parcel/src/transforms/babel/config.js
- /home/stefan/playground/parcel-issue/node_modules/parcel/src/transforms/babel/transform.js
- /home/stefan/playground/parcel-issue/node_modules/parcel/src/assets/JSAsset.js
- /home/stefan/playground/parcel-issue/node_modules/parcel/src/Parser.js
- /home/stefan/playground/parcel-issue/node_modules/parcel/src/Bundler.js
- /home/stefan/playground/parcel-issue/node_modules/parcel/index.js
- /home/stefan/playground/parcel-issue/node_modules/parcel/src/cli.js
- /home/stefan/playground/parcel-issue/node_modules/parcel/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (/home/stefan/playground/parcel-issue/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/stefan/playground/parcel-issue/node_modules/core-js-compat/helpers.js:3:14)
    at Module._compile (/home/stefan/playground/parcel-issue/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) falling back to RawAsset
🚨  Cannot read property 'length' of undefined
    at lineCounter (/home/stefan/playground/parcel-issue/node_modules/parcel/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/home/stefan/playground/parcel-issue/node_modules/parcel/src/packagers/JSPackager.js:127:60)
    at async JSPackager.addAsset (/home/stefan/playground/parcel-issue/node_modules/parcel/src/packagers/JSPackager.js:88:5)
    at async Bundle._addDeps (/home/stefan/playground/parcel-issue/node_modules/parcel/src/Bundle.js:250:5)
    at async Bundle._package (/home/stefan/playground/parcel-issue/node_modules/parcel/src/Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (/home/stefan/playground/parcel-issue/node_modules/parcel/src/Bundle.js:202:5)
    at async Promise.all (index 1)
    at async Bundle.package (/home/stefan/playground/parcel-issue/node_modules/parcel/src/Bundle.js:202:5)
    at async Bundler.bundle (/home/stefan/playground/parcel-issue/node_modules/parcel/src/Bundler.js:325:27)

```

## 💻 Code Sample

https://github.com/haansn08/parcel-issue-cannot-find-module-src-data

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.4 |
| Node             | v12.13.0 |
| npm/Yarn         | npm 6.13.1 |
| Operating System | Fedora 31 / x86_64 Linux 5.3.12-300 |

**Comment by fourcube** [comment]
Same problem here.

**Comment by mischnic** [comment]
> https://github.com/zloirock/core-js/issues/710

**Comment by ArtemeeSenin** [comment]
still reproduces for me

**Comment by bidoubiwa** [comment]
I `rm -rf node_modules` and installed again and it fixed it for me
