### ISSUE TITLE
npm install parcel-bundler doesn't work on Linux machines?

### ISSUE THREAD

**Issue by ahsu1230** [parcel-bundler/parcel#3888]
Hello after running
`npm install parcel-bundler`

I get dependency warnings and non-supported error messages around `fsevents`.
```
8612 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
8613 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
8614 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
8614 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
8614 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
8614 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
8615 verbose stack Error: deasync@0.1.16 install: `node ./build.js`
8615 verbose stack spawn ENOENT
8615 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
8615 verbose stack     at ChildProcess.emit (events.js:198:13)
8615 verbose stack     at maybeClose (internal/child_process.js:982:16)
8615 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
8616 verbose pkgid deasync@0.1.16
...
8618 verbose Linux 4.14.138-89.102.amzn1.x86_64
8619 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "install" "parcel-bundler"
8620 verbose node v10.16.0
8621 verbose npm  v6.9.0
8622 error file sh
8623 error code ELIFECYCLE
8624 error errno ENOENT
8625 error syscall spawn
8626 error deasync@0.1.16 install: `node ./build.js`
8626 error spawn ENOENT
8627 error Failed at the deasync@0.1.16 install script.
8627 error This is probably not a problem with npm. There is likely additional logging output above.
```

It seems fsevents can only work for Mac (Darwin OS) installations? If that's the case, does parcel not work with Linux?

Please let me know if I'm misunderstanding something! Specifically, I'm trying to install parcel-bundler onto an AWS Ec2 instance. Thank you!

**Comment by ahsu1230** [comment]
Any idea why installing parcel would call deasync?

**Comment by ahsu1230** [comment]
@mischnic 
After looking around some more. I've found more recent discussions here:
https://github.com/parcel-bundler/parcel/issues/3799

Are there any updates regarding deasync?

**Comment by mischnic** [comment]
deasync is used by Parcel 1 in some places. Parcel 2 doesn't use it anymore (effectively).
The issues in the deasync repo don't seem very helpful either: https://github.com/abbr/deasync/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ENOENT
