### ISSUE TITLE
Unable to install parcel 2 in Alpine-based Docker containers

### ISSUE THREAD

**Issue by azz** [parcel-bundler/parcel#3895]
# 🐛 bug report

## 🤔 Expected Behavior

Parcel installs correctly.

## 😯 Current Behavior

Parcel fails to install because `python` is not available in Alpine containers (e.g. [`node:10-alpine`](https://hub.docker.com/_/node))

## 💻 Code Sample

Repro:

```shellsession
$ docker run -it --rm node:10-alpine sh
# cd ~ && yarn init -y
# yarn add parcel@2.0.0-alpha.3.2
```

Error:

```
error /root/node_modules/@parcel/watcher: Command failed.
Exit code: 1
Command: prebuild-install -r napi || node-gyp rebuild
Arguments:
Directory: /root/node_modules/@parcel/watcher
Output:
prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=x64 libc=musl platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/@parcel/watcher
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v10.15.1
| npm/Yarn         | 1.13.0
| Operating System | Alpine Linux - Linux 3bea573d4595 4.9.184-linuxkit

**Comment by azz** [comment]
Potentially the same issue as https://github.com/parcel-bundler/watcher/issues/10?
