### ISSUE TITLE
TypeScript sourcemap is not used in error stacktrace

### ISSUE THREAD

**Issue by ceilfors** [parcel-bundler/parcel#3913]
# 🐛 bug report

When parcel is being used for TypeScript files, an error thrown at runtime will not produce a stacktrace with the correct source map.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
npx parcel build src/throw-error.ts --target node
```

Do note that `source-map-support` is already configured.

## 🤔 Expected Behavior

When an error is thrown, the stack trace produced should point to the right file and line number in the source code

## 😯 Current Behavior

When an error is thrown, the stack trace produced does not point to the right file and line number in the source code. This is the output of the stack trace with the code from "Code Sample" section below.

```
± |master ↑2 U:7 ?:2 ✗| → node dist/throw-error.js

/Users/ceilfors/github/test-source-map/dist/throw-error.js:2
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});class e{myMethod(){throw new Error("My method boo")}}exports.default=e;
                                                                                             ^
Error: My method boo
    at e.myMethod (/Users/ceilfors/github/test-source-map/dist/throw-error.js:2:94)
    at Object.parcelRequire.zbOE../SomeClass (/Users/ceilfors/github/test-source-map/dist/throw-error.js:4:242)
    at f (/Users/ceilfors/github/test-source-map/dist/throw-error.js:1:468)
    at parcelRequire.wCti (/Users/ceilfors/github/test-source-map/dist/throw-error.js:1:771)
    at Object.<anonymous> (/Users/ceilfors/github/test-source-map/dist/throw-error.js:1:1023)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
```

## 💁 Possible Solution

Perhaps have a look into how webpack + ts-loader work. This is the output of the same source code when webpack is used to bundle the same file in the "Code Sample" section below.

```
± |master ↑2 U:7 ?:2 ✗| → node dist/throw-error.js

/Users/ceilfors/github/test-source-map/dist/webpack:/src/SomeClass.ts:3
    throw new Error("My method boo");
          ^
Error: My method boo
    at Object.myMethod (/Users/ceilfors/github/test-source-map/dist/webpack:/src/SomeClass.ts:3:11)
    at Module.call (/Users/ceilfors/github/test-source-map/dist/webpack:/src/throw-error.ts:4:17)
    at __webpack_require__ (/Users/ceilfors/github/test-source-map/dist/webpack:/webpack/bootstrap:19:22)
    at /Users/ceilfors/github/test-source-map/dist/webpack:/webpack/bootstrap:83:10
    at Object.<anonymous> (/Users/ceilfors/github/test-source-map/dist/throw-error.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
```

## 🔦 Context

Troubleshooting nodejs error in production is difficult without a proper stacktrace.

## 💻 Code Sample

**src/throw-error.ts**
```
import "source-map-support/register";
import SomeClass from "./SomeClass";

new SomeClass().myMethod();
```

**SomeClass.ts**
```
export default class SomeClass {
  myMethod(): void {
    throw new Error("My method boo");
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             |  12.13.0 |
| npm/Yarn         | 6.12.0 |
| Operating System | macOS 10.15.1 |

**Comment by MikuZZZ** [comment]
I'm not sure why but manually specify the `.js.map` file solved my problem

```javascript
import SourceMap from 'source-map-support';
import fs from 'fs';
SourceMap.install({
  retrieveSourceMap: function() {
    return {
      url: 'index.js',
      map: fs.readFileSync('index.js.map', 'utf8'),
    };
  },
});
```

**Comment by kunaakos** [comment]
I'm having the same issue, not just with typescript. In my case, the source mapping url is incorrect:
`//# sourceMappingURL=/main.js.map` instead of `//# sourceMappingURL=main.js.map`. If I edit this manually, it works fine.
@MikuZZZ you could be dealing with the same issue, maybe that's why the custom retrieve fn helps?

**Comment by DeMoorJasper** [comment]
This has been fixed in Parcel 2
