### ISSUE TITLE
Parcel 2: import inside <script type="module">

### ISSUE THREAD

**Issue by kocsis1david** [parcel-bundler/parcel#3927]
# 🐛 bug report

Imports within the `<style>` tag work and they get inlined into the html, but imports inside <script type="module"> doesn't work. Not sure if this is supposed to work, maybe it could be a feature request.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
npx parcel build index.html
```

package.json

```json
{
  "name": "test2",
  "version": "1.0.0",
  "description": "",
  "main": "main.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.0.0-alpha.3.2"
  }
}
```

## 🤔 Expected Behavior

The imported file `./test.js` could be inlined into the html.

## 😯 Current Behavior

```
× @parcel/namer-default: Destination name main.34e67a48.undefined extension does not match bundle type "undefined"
Error: Destination name main.34e67a48.undefined extension does not match bundle type "undefined"
    at BundlerRunner.nameBundle (C:\Users\David\Desktop\test2\node_modules\@parcel\core\lib\BundlerRunner.js:192:19)
    at async Promise.all (index 1)
    at async BundlerRunner.nameBundles (C:\Users\David\Desktop\test2\node_modules\@parcel\core\lib\BundlerRunner.js:169:5)
    at async BundlerRunner.bundle (C:\Users\David\Desktop\test2\node_modules\@parcel\core\lib\BundlerRunner.js:132:5)
    at async Parcel.build (C:\Users\David\Desktop\test2\node_modules\@parcel\core\lib\Parcel.js:372:25)        
    at async Parcel.run (C:\Users\David\Desktop\test2\node_modules\@parcel\core\lib\Parcel.js:253:18)
    at async Command.run (C:\Users\David\Desktop\test2\node_modules\parcel\lib\cli.js:155:7)
```

## 🔦 Context

I would like to create a html bundle that has everything in a single file.

## 💻 Code Sample

index.html

```html
<html>
<head>
    <!-- <style>
        @import "./test.css";
    </style> -->
</head>

<body>
    <script type="module">
        import "./test.js";
    </script>
</body>
</html>
```

test.js

```js
console.log("ok");
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2 |
| Node             | v12.14.0 |
| npm         | 6.13.4 | 
| Operating System | Windows 10 |

**Comment by kocsis1david** [comment]
It should be `<script>`  instead of `<script type="module">`. It works this way, but maybe the error message could be more helpful.
