### ISSUE TITLE
Parcel throws: Unknown version 63 of opera

### ISSUE THREAD

**Issue by agnelnieves** [parcel-bundler/parcel#3945]
# 🐛 bug report

Setting up parcel, following the steps on the doc site. Installed parcel CLI, added index.html, index.js and ran `parcel index.html` Runs on localhost:1234 but throws the following error `Unknown version 63 of opera`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parcel-test",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "parcel-bundler": "^1.12.4"
  }
}
```

## 🤔 Expected Behavior

Just run the project on the browser 

## 😯 Current Behavior

Local-host runs and throws the following error:
```
🚨 Build Error
/Users/agnelnieves/Documents/Winkode/Clients/technoandlogic/suave/quiz/project/app.js: Unknown version 63 of opera

    at Function.select (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/browserslist/index.js:941:17)
    at /Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/browserslist/index.js:255:33
    at Array.reduce ()
    at resolve (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/browserslist/index.js:237:18)
    at browserslist (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/browserslist/index.js:361:16)
    at getTargets (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/lib/targets-parser.js:179:48)
    at _default (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/lib/index.js:225:46)
    at Object.default (/Users/agnelnieves/.config/yarn/global/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12)
    at getEnvPlugins (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)
```

## 💻 Code Sample

My current setup:

Index html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Parcel</title>
</head>
<body>
    <h1>Hello</h1>
    <script src="./app.js"></script>
</body>
</html>
```

app.js
```
console.log('Hello from parcel');
```

## 🔦 Context

Just trying to run the basic parcel starter locally. Currently just using html & JS

## 🌍 Your Environment
Running on macOS, Chrome browser (79.0.3945.88) using the most basic configuration (Html & Js)

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             |  v10.16.3
| npm/Yarn         | yarn (1.17.3)
| Operating System | MacOS 10.14.6

**Comment by cdll** [comment]
did u build success?

**Comment by agnelnieves** [comment]
@cdll 
> did u build success?

To be honest, didn't think of trying. Just tried, ran `parcel build index.html` and got the same error:
```
/Users/agnelnieves/Documents/Winkode/Clients/technoandlogic/suave/quiz/parcel/app.js: Unknown version 63 of opera
    at Function.select (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/browserslist/index.js:941:17)
    at /Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/browserslist/index.js:255:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/browserslist/index.js:237:18)
    at browserslist (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/node_modules/browserslist/index.js:361:16)
    at getTargets (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/lib/targets-parser.js:179:48)
    at _default (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/node_modules/@babel/preset-env/lib/index.js:225:46)
    at Object.default (/Users/agnelnieves/.config/yarn/global/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12)
    at getEnvPlugins (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/Users/agnelnieves/.config/yarn/global/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)

```

**Comment by mischnic** [comment]
Please provide a minimal reproduction.

**Comment by agnelnieves** [comment]
> Please provide a minimal reproduction (the HTML/JS source files).

Just updated with the source files. As I mentioned, it's just a basic setup. Now, I just tried on a different MacBook running macOS Catalina and it's running fine. Also, that MacBook doesn't have Opera installed. I will keep trying on mine to see if I can get to the root of the issue.

**Comment by agnelnieves** [comment]
**Update:** I opted for uninstalling everything. Node, Yarn, Parcel and even Brew. Installed everything back, recreated the project using Yarn, got the same error.

I then tried to recreate the project using NPM instead, and interestingly enough, it worked. I tried it again with yarn just in case and got the same error. So I guess is an issue related to Yarn? Even tho I tried it with Yarn in another MacBook and it was working fine. Idk I guess I will use NPM in this case. 

I would love to see if anyone gets the same issue and finds a workaround tho. I also found a similar issue in [this](https://github.com/parcel-bundler/parcel/issues/1036) thread. It was labeled as closed and fixed tho... So might be worth looking at it again?

**Comment by wojtekmaj** [comment]
Looks like you may have issues with your .browserslistrc or wherever you configured supported browsers. caniuse package installed could simply be too old to know about Opera 63. `yarn upgrade` would have likely resolved the issue.

**Comment by agnelnieves** [comment]
@wojtekmaj Haven't set up the .browserslistrc . Forgot to mention tho, after I took the steps on the previous comment, it stopped showing the Opera error, it was showing the same thing but for safari. That was the main motivator for me to try with NPM instead. I was wasting too much time trying to get it running w yarn. After I switched to NPM everything's been running like charm.

**Comment by mischnic** [comment]
Seems to be resolved

**Comment by nerdoc** [comment]
Don't use a global version of parcel. This seems to cause the error. use the locally (in your project dir) installed one.
