### ISSUE TITLE
Parcel 2: Contributing steps problems

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3948]
# ❔ Question

When trying to contribute to parcel by fixing #3944 i followed [CONTRIBUTING](https://github.com/parcel-bundler/parcel/blob/v2/CONTRIBUTING.md#getting-started)'s steps but had some problems while following them.

Well, first of all,
```sh
git clone git@github.com:parcel-bundler/parcel.git && cd parcel
```
returned
```sh
C:\dev>git clone git@github.com:parcel-bundler/parcel.git && cd parcel
Cloning into 'parcel'...
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
but that is easily solvable by simply
```sh
git clone https://github.com/parcel-bundler/parcel
```

Once the repo cloned, i ran `yarn install`, no problems, and then i tried to launch a parcel instance on a simple `console.log('foo')` js script and got:

```sh
C:\dev\test>node C:\dev\parcel\packages\core\parcel-bundler\bin\cli.js index.js
(node:19128) UnhandledPromiseRejectionWarning: Error: Cannot find module 'C:\dev\parcel\node_modules\@parcel\workers\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:306:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:682:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (C:\dev\parcel\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\dev\parcel\packages\core\parcel-bundler\src\Bundler.js:4:20)
    at Module._compile (C:\dev\parcel\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
(node:19128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

*under Windows 10 and node v13.2.0*

**Comment by mischnic** [comment]
This will be fixed by https://github.com/parcel-bundler/parcel/pull/3610.

`core/parcel-bundler` contains Parcel 1, you want `packages/core/parcel/src/bin.js`.
