### ISSUE TITLE
Question on the use of babel-preset-env

### ISSUE THREAD

**Issue by jorgegonzalez** [parcel-bundler/parcel#407]
🐛 bug (maybe?)

Parcel seems to require the use of `babel-preset-env` (at least that's what the docs suggest), even though that particular package has been moved to the Babel mono-repo [here](https://github.com/babel/babel/tree/master/packages/babel-preset-env) (which is `@babel/preset-env` on NPM).

Are there any disadvantages to this or am I missing something?

**Comment by jorgegonzalez** [comment]
To add on to this, with this package.json:

```json
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.36",
    "@babel/preset-env": "^7.0.0-beta.36",
    "@babel/preset-react": "^7.0.0-beta.36",
    "parcel-bundler": "^1.3.1"
  },
```

I get this error:

```
Server running at http://localhost:1234
🚨  /Users/jorge/Code/parcel/index.jsx: Cannot read property 'loose' of undefined (While processing preset: "/Users/jorge/Code/parcel/node_modules
/@babel/preset-env/lib/index.js")
    at _default (/Users/jorge/Code/parcel/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:21:23)
    at Function.memoisePluginContainer (/Users/jorge/Code/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13
)
    at Function.normalisePlugin (/Users/jorge/Code/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/jorge/Code/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/jorge/Code/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/jorge/Code/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /Users/jorge/Code/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/jorge/Code/parcel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
```

**Comment by sudo-suhas** [comment]
`@babel/preset-env` is in beta for now which you can see from the version numbers. Latest release for `babel-preset-env` is `1.6.1`. See https://www.npmjs.com/package/babel-preset-env.

**Comment by jorgegonzalez** [comment]
Oh okay, didn’t realize that. Closing this issue now.
