### ISSUE TITLE
Invalid Option: 'yarn' is not a valid target - reading stuff from `engines` indiscriminately

### ISSUE THREAD

**Issue by odinho** [parcel-bundler/parcel#4087]
# 🐛 bug report

parcel shouldn't use 'yarn' in engines field as a target. 

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
    ...
    "engines": {
        "node": "^8.0.0 || ^10.0.0 || ^12.0.0",
        "yarn": "^1.13.0"
    }
}
```

## 🤔 Expected Behavior

No error.

## 😯 Current Behavior

```
odin@kaa:~/appearin/video-conference$ parcel build --no-minify --no-source-maps --target node apiServer.js 
🚨 Build failed.
@parcel/transformer-babel: [BABEL] /home/odin/appearin/video-conference/apiServer.js: Invalid Option: 'yarn' is not a valid target
        Maybe you meant to use 'node'? (While processing: "/home/odin/appearin/video-conference/nodemodules/@parcel/transformer-babel/nodemodules/@babel/preset-env/lib/index.js")
Error: [BABEL] /home/odin/appearin/video-conference/apiServer.js: Invalid Option: 'yarn' is not a valid target
        Maybe you meant to use 'node'? (While processing: "/home/odin/appearin/video-conference/node_modules/@parcel/transformer-babel/node_modules/@babel/preset-env/lib/index.js")
    at validateTargetNames (/home/odin/appearin/video-conference/node_modules/@parcel/transformer-babel/node_modules/@babel/helper-compilation-targets/lib/index.js:84:13)
    at getTargets (/home/odin/appearin/video-conference/node_modules/@parcel/transformer-babel/node_modules/@babel/helper-compilation-targets/lib/index.js:184:3)
    at _default (/home/odin/appearin/video-conference/node_modules/@parcel/transformer-babel/node_modules/@babel/preset-env/lib/index.js:228:57)
    at /home/odin/appearin/video-conference/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /home/odin/appearin/video-conference/node_modules/@parcel/transformer-babel/node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/home/odin/appearin/video-conference/node_modules/@parcel/transformer-babel/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/odin/appearin/video-conference/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/odin/appearin/video-conference/node_modules/gensync/index.js:84:14)

```

## 💁 Possible Solution

Ignore engines we don't recognize as something you can compile to.

## 🔦 Context

We added the yarn engine requirement because of some other bug we had a while back with some CI servers. Might not be needed anymore, but hey, parcel's behaviour does not seem right.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-alpha.3.2` and `nightly-77`
| Node             | node 10
| npm/Yarn         | yarn 1.21.1
| Operating System | Linux

**Comment by mischnic** [comment]
We cannot blindly copy over `engines` entries in 
https://github.com/parcel-bundler/parcel/blob/e33d91613d0ab9f600c93c5f8466f20fe9ca9dce/packages/transformers/babel/src/utils.js#L33
to pass them to `@babel/preset-env`'s `targets`. Unfortunately, the list of allowed targets isn't exposed by Babel:
https://github.com/babel/babel/blob/755ec192e22c6b6e00782e4810366d0166fdbebd/packages/babel-helper-compilation-targets/src/options.js
