### ISSUE TITLE
Issue with Parcel 2 alpha and custom transformer

### ISSUE THREAD

**Issue by green-arrow** [parcel-bundler/parcel#4105]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Basic `.parcelrc` with a custom transformer fails. I'm working on creating a transformer for SVG (similar to the svgr parcel plugin for Parcel v1) in order to fully test out the alpha.

`.parcelrc`

```json
{
  "extends": ["@parcel/config-default"],
  "transforms": {
    "*.svg": ["parcel-transformer-react-svg"]
  }
}
```

`package.json`

```json
  "alias": {
    "parcel-transformer-svg": "./parcel-transformer-react-svg.js"
  },
```

## 🤔 Expected Behavior

Parcel runs the custom transformer

## 😯 Current Behavior

I get an error message that seems to originate from the default bundler:

```
🚨 @parcel/bundler-default: The expression evaluated to a falsy value:

  (0, _assert.default)(context != null)

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert.default)(context != null)

    at enter (/Users/andrewwa/Developer/workspace/nova/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:84:29)
    at enter (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:503:16)
    at walk (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:338:26)
    at walk (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:359:22)
    at walk (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:359:22)
    at walk (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:359:22)
    at Graph.dfs (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:383:12)
    at Graph.traverse (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:287:17)
    at Graph.filteredTraverse (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/Graph.js:295:17)
    at MutableBundleGraph.traverse (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/public/MutableBundleGraph.js:175:55)
```

## 💁 Possible Solution

No idea, but I'm willing to help with this and any other issues I find when testing out the alpha on our decent size codebase 😄 

## 🔦 Context

Add custom transformer

## 💻 Code Sample

Stripped down starting point for the transformer.

`parcel-transformer-react-svg.js`

```js
import { Transformer } from '@parcel/plugin';

export default new Transformer({
  async loadConfig({ config, options, logger }) {
    await load(config, options, logger);
  },

  async transform({ asset, config, options }) {
    asset.type = 'js';

    const code = await asset.getCode();
    console.log({ code, config });

    return [
      {
        type: 'js',
        code: code,
      },
    ];
  },
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha;3
| Node             | 10.16.3
| npm/Yarn         | 1.21.1
| Operating System | macOS

**Comment by green-arrow** [comment]
Also for what it's worth, if I completely remove the `.parcelrc` file I get a different error:

```
ℹ️ Server running at http://localhost:3000
Error: function (...args) {
    return new Promise(function (resolve, reject) {
      fn(...args, function (err, ...re...<omitted>... } could not be cloned.
    at Object.serialize (v8.js:202:7)
    at serialize (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/core/lib/serializer.js:221:21)
    at ProcessWorker.send (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/workers/lib/process/ProcessWorker.js:71:54)
    at Worker.send (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/workers/lib/Worker.js:81:17)
    at Worker.call (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/workers/lib/Worker.js:91:10)
    at WorkerFarm.processQueue (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/workers/lib/WorkerFarm.js:225:16)
    at Worker.worker.on (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/workers/lib/WorkerFarm.js:182:35)
    at Worker.emit (events.js:198:13)
    at Worker.fork (/Users/andrewwa/Developer/workspace/nova/node_modules/parcel/node_modules/@parcel/workers/lib/Worker.js:77:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mischnic** [comment]
Using `alias` to use a local file as a Parcel plugin doesn't seem to work (the only way is creating a seperate package in a monorepo), more explanation here: https://github.com/parcel-bundler/parcel/issues/3397#issuecomment-521353931

> I'm willing to help with this and any other issues I find when testing out the alpha on our decent size codebase 😄

👍 

> if I completely remove the .parcelrc file I get a different error:

Does this happen consistently even after deleting the cache?

**Comment by green-arrow** [comment]
> Does this happen consistently even after deleting the cache?

Yeah, it seems to

```
> rm -rf .parcel-cache
> yarn parcel serve src/index.html --port 3000
yarn run v1.21.1
node_modules/.bin/parcel serve src/index.html --port 3000
ℹ️ Server running at http://localhost:3000
Error: function (...args) {
    return new Promise(function (resolve, reject) {
      fn(...args, function (err, ...re...<omitted>... } could not be cloned.
    at Object.serialize (v8.js:202:7)
    at serialize (node_modules/parcel/node_modules/@parcel/core/lib/serializer.js:221:21)
    at ProcessWorker.send (node_modules/parcel/node_modules/@parcel/workers/lib/process/ProcessWorker.js:71:54)
    at Worker.send (/node_modules/parcel/node_modules/@parcel/workers/lib/Worker.js:81:17)
    at Worker.call (node_modules/parcel/node_modules/@parcel/workers/lib/Worker.js:91:10)
    at WorkerFarm.processQueue (node_modules/parcel/node_modules/@parcel/workers/lib/WorkerFarm.js:225:16)
    at Worker.worker.on (node_modules/parcel/node_modules/@parcel/workers/lib/WorkerFarm.js:182:35)
    at Worker.emit (events.js:198:13)
    at Worker.fork (node_modules/parcel/node_modules/@parcel/workers/lib/Worker.js:77:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If it helps any, this is the relevant part of my `index.html` file:

```html
<script type="module" src="./index.tsx"></script>
<script type="text/javascript" nomodule src="./index.tsx"></script>
```

I don't have any configuration in `package.json` as I understand that's for "library mode" only. Is that correct?

**Comment by green-arrow** [comment]
Also RE the monorepo approach: would you be open to a PR for an official `@parcel/transformer-svg-react` package that used the [svgr library](https://github.com/gregberge/svgr) to transform SVG files into react components?

**Comment by mischnic** [comment]
Can we close this?
