### ISSUE TITLE
Solving "No transformers found for ..." error

### ISSUE THREAD

**Issue by bre7** [parcel-bundler/parcel#4117]
# ❔ Question

What's the recommended solution when dealing with the error: `No transformers found for ......` 
where there's no need for a transformer ? (i.e. geojson file)

Is it a bug ? Maybe warning instead of error and treat as plain text ?

## 🔦 Context

Unable to finish build

## 💻 Code Sample

```js
const g = await fetch( require("./assets/foo.geojson") )
```

Error:
```
 🚨 Build failed.
Error: No transformers found for "/path/src/assets/foo.geojson".
Error: No transformers found for "/path/src/assets/foo.geojson".
    at ParcelConfig.getTransformerNames (/path/src/node_modules/@parcel/core/lib/ParcelConfig.js:127:13)
    at ConfigLoader.loadParcelConfig (/path/src/node_modules/@parcel/core/lib/ConfigLoader.js:86:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PromiseQueue._runFn (/path/src/node_modules/@parcel/utils/lib/PromiseQueue.js:98:7)
    at async PromiseQueue._next (/path/src/node_modules/@parcel/utils/lib/PromiseQueue.js:85:5)
error Command failed with exit code 1.
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.95+a63f3fc9
| Node             | 13.8.0
| npm/Yarn         | yarn 1.22.0
| Operating System | macOS 10.15

**Comment by mischnic** [comment]
`fetch( require("url:./assets/foo.geojson") )`

**Comment by bre7** [comment]
🤦‍♂️ thanks
