### ISSUE TITLE
Error: Cannot find module 'readable-stream/duplex.js'

### ISSUE THREAD

**Issue by volkanongun** [parcel-bundler/parcel#4224]
# 🐛 bug report

## 🤔 Expected Behavior

parcel was starting gracefully for the version parcel@next.
I'm getting errors for request and corejs packages are deprecated.
unable to start a new project with parcel@next

## 😯 Current Behavior

`Build failed.
Error: Cannot find module 'readable-stream/duplex.js'
Require stack:
- /Users/volkan/dev/parceljs-template/nodemodules/@parcel/node-libs-browser/index.js
- /Users/volkan/dev/parceljs-template/nodemodules/@parcel/node-resolver-core/lib/builtins.js
- /Users/volkan/dev/parceljs-template/nodemodules/@parcel/node-resolver-core/lib/NodeResolver.js
- /Users/volkan/dev/parceljs-template/nodemodules/@parcel/resolver-default/lib/DefaultResolver.js
- /Users/volkan/dev/parceljs-template/nodemodules/@parcel/package-manager/lib/index.js
- /Users/volkan/dev/parceljs-template/nodemodules/@parcel/core/lib/resolveOptions.js
- /Users/volkan/dev/parceljs-template/nodemodules/@parcel/core/lib/Parcel.js
- /Users/volkan/dev/parceljs-template/nodemodules/@parcel/core/lib/index.js
- /Users/volkan/dev/parceljs-template/nodemodules/parcel/lib/cli.js
- /Users/volkan/dev/parceljs-template/nodemodules/parcel/lib/bin.js
Error: Cannot find module 'readable-stream/duplex.js'
Require stack:
- /Users/volkan/dev/parceljs-template/node_modules/@parcel/node-libs-browser/index.js
- /Users/volkan/dev/parceljs-template/node_modules/@parcel/node-resolver-core/lib/builtins.js
- /Users/volkan/dev/parceljs-template/node_modules/@parcel/node-resolver-core/lib/NodeResolver.js
- /Users/volkan/dev/parceljs-template/node_modules/@parcel/resolver-default/lib/DefaultResolver.js
- /Users/volkan/dev/parceljs-template/node_modules/@parcel/package-manager/lib/index.js
- /Users/volkan/dev/parceljs-template/node_modules/@parcel/core/lib/resolveOptions.js
- /Users/volkan/dev/parceljs-template/node_modules/@parcel/core/lib/Parcel.js
- /Users/volkan/dev/parceljs-template/node_modules/@parcel/core/lib/index.js
- /Users/volkan/dev/parceljs-template/node_modules/parcel/lib/cli.js
- /Users/volkan/dev/parceljs-template/node_modules/parcel/lib/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.resolve (/Users/volkan/dev/parceljs-template/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at Object.<anonymous> (/Users/volkan/dev/parceljs-template/node_modules/@parcel/node-libs-browser/index.js:29:34)
    at Module._compile (/Users/volkan/dev/parceljs-template/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at NodePackageManager.load (/Users/volkan/dev/parceljs-template/node_modules/@parcel/package-manager/lib/NodePackageManager.js:112:9)
    at NodePackageManager.requireSync (/Users/volkan/dev/parceljs-template/node_modules/@parcel/package-manager/lib/NodePackageManager.js:78:17)
    at Module.m.require (/Users/volkan/dev/parceljs-template/node_modules/@parcel/package-manager/lib/NodePackageManager.js:99:19)
    at require (/Users/volkan/dev/parceljs-template/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)`

## 🌍 Your Environment

yarn parcel src/index.html --no-cache
or
node_modules/.bin/parcel src/index.html --no-cache
doesn't work.

node: v12.14.0
npm: 6.14.0

**Comment by CrashyBang** [comment]
I am still getting this using `^2.0.0-alpha.3.2` have tried nuking `node_modules`, `package-lock.json` and `.parcel-cache` to no avail.

My start script is: `"start": "env-cmd -f .env.development parcel serve --no-cache src/index.html"`

**Comment by siddharth-sb** [comment]
I am also facing the same issue.  what's the solution?

**Comment by ghost** [comment]
rm -rf node_modules
pnpm i node_modules (or yarn or whatever you use)

That did it for me.  I was having trouble with nodemon.
