### ISSUE TITLE
@parcel/packager-js: Cannot read property 'constantViolations' of undefined

### ISSUE THREAD

**Issue by AKPWebDesign** [parcel-bundler/parcel#4244]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Probably best to look at my minimal repro project here: https://github.com/AKPWebDesign/When-Temp

## 🤔 Expected Behavior

Running `parcel build packages/*/*` should result in all packages being built successfully.

## 😯 Current Behavior

The build fails with this stack trace:
```
$ parcel build packages/*/*
��� Build failed.
@parcel/packager-js: Cannot read property 'constantViolations' of undefined
TypeError: Cannot read property 'constantViolations' of undefined
    at rename (/AKPWebDesign/When-Temp/node_modules/@parcel/scope-hoisting/lib/renamer.js:21:33)
    at Object.generateExports (/AKPWebDesign/When-Temp/node_modules/@parcel/scope-hoisting/lib/formats/commonjs.js:264:30)
    at exit (/AKPWebDesign/When-Temp/node_modules/@parcel/scope-hoisting/lib/link.js:564:31)
    at NodePath._call (/AKPWebDesign/When-Temp/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/AKPWebDesign/When-Temp/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/AKPWebDesign/When-Temp/node_modules/@babel/traverse/lib/path/context.js:99:8)
    at TraversalContext.visitQueue (/AKPWebDesign/When-Temp/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/AKPWebDesign/When-Temp/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/AKPWebDesign/When-Temp/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/AKPWebDesign/When-Temp/node_modules/@babel/traverse/lib/index.js:84:17)
```

## 💁 Possible Solution

Running `parcel build packages/common/SignInButton/src/index.tsx` directly works as intended.

## 🔦 Context

I am attempting to use Parcel to build/package a monorepo with multiple packages as described by @devongovett: https://twitter.com/devongovett/status/1181306747283103745

## 💻 Code Sample

https://github.com/AKPWebDesign/When-Temp

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.130
| Node             | v12.x
| npm/Yarn         | yarn 1.22.0
| Operating System | WSL 4.4.0-18362-Microsoft / macOS Catalina (10.15.3)

**Comment by green-arrow** [comment]
fwiw, I'm also receiving this when building a single page `parcel build src/index.html`. The page has two entries (one `module`, one `nomodule`, for differential serving, both pointing to the same file).
