### ISSUE TITLE
Parser "assets/JSAsset" failed to initialize when processing asset

### ISSUE THREAD

**Issue by azmatzuberi** [parcel-bundler/parcel#4276]
# 🐛 bug report

doing npm start on macOs Catilina results in an error: Parser "assets/JSAsset" failed to initialize when processing asset 

## 🎛 Configuration (.babelrc, package.json, cli command)

babelrc
{
  "presets": [
    "airbnb"
  ],
  "plugins": [
    "add-module-exports",
    ["transform-replace-object-assign", { "moduleSpecifier": "object.assign" }]
  ]
}

```

## 🤔 Expected Behavior

npm start should result in app being served properly without any errors

## 😯 Current Behavior

Parser "assets/JSAsset" failed to initialize when processing asset "node_modules/parcel-bundler/src/b
uiltins/css-loader.js". Threw the following error:
Error: Package exports for '/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath
    at resolveExports (internal/modules/cjs/loader.js:419:17)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32) falling back to RawAsset
🚨  Cannot read property 'length' of undefined
    at lineCounter (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/parcel-bundler/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/parcel-bundler/src/packagers/JSPackager.js:127:60)
    at JSPackager.addAsset (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/parcel-bundler/src/packagers/JSPackager.js:88:5)
    at Bundle._addDeps (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/parcel-bundler/src/Bundle.js:250:5)
    at Bundle._addDeps (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/parcel-bundler/src/Bundle.js:247:7)
    at Bundle._package (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/parcel-bundler/src/Bundle.js:219:7)
    at async Promise.all (index 0)
    at Bundle.package (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Promise.all (index 1)
    at Bundle.package (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/parcel-bundler/src/Bundle.js:202:5)
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "node_modules/parcel-bundler/src/builtins/hmr-runtime.js". Threw the following error:
Error: Package exports for '/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath
    at resolveExports (internal/modules/cjs/loader.js:419:17)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/azmatzuberi/Documents/htdocs/app-student/notetonic-student-app/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32) falling back to RawAsset

## 💁 Possible Solution

<!--- Not obligatory, but suggest a fix/reason for the bug -->

## 🔦 Context

I'm trying to run my app to see the changes I've made, but this error message keeps interfering

This is a Vue.js app and uses the stack of Vue.js (typescript) Express (typescript) and MongoDB all on node.js. We are using parcel as a web application bundler

## 💻 Code Sample

Code is not the issue here.

## 🌍 Your Environment

<!--- Include as many relevant details about the environment you experienced the bug in -->

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 13.0.1
| npm/Yarn         |6.14.2
| Operating System | macOS Catilina

**Comment by mischnic** [comment]
You need to upgrade `@babel/helper-compilation-targets` to at least `7.8.4` (see https://github.com/babel/babel/issues/11216), or downgrade Node.

**Comment by magic-akari** [comment]
Same issue with Node v12.16.1.
Nothing changes after upgrade @babel/helper-compilation-targets.

**Comment by rhythnic** [comment]
If the issue remains after downgrading Node, try removing `node_modules` and `package-lock.json` and then run `npm install`.  It worked for me.
