### ISSUE TITLE
Parcel 2 tree shaking assertion fails

### ISSUE THREAD

**Issue by cuberoot** [parcel-bundler/parcel#4336]
# 🐛 bug report

I am using parcel 2.0.0-alpha.3.2.

When compiling an app that imports a certain 3rd party npm package (@popper/core), I get an assertion failure during the build.

## 🎛 Configuration (.babelrc, package.json, cli command)

I have included a paired down example in the "Sample Code" section below.

babel.config.js
```javascript
module.exports = {
	presets: [
		[
			'@babel/preset-env'
		]
	],
	plugins: [
		[ '@babel/plugin-proposal-decorators', {
			legacy: false,
			decoratorsBeforeExport: false
		} ],
		[ '@babel/plugin-proposal-class-properties', { 'loose' : true } ],
		'@babel/plugin-proposal-optional-chaining'
	]
}
```

package.json:
```json
{
  "name": "importer-test-harness",
  "version": "1.0.0",
  "description": "Test harness ",
  "scripts": {
    "start": "yarn parcel --https index.html",
    "build": "yarn parcel build index.html",
    "lint": "eslint ."
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "browserslist": "last 2 chrome version, last 2 firefox version, last 2 safari version",
  "dependencies": {
    "@popperjs/core": "^2.1.0"
  },
  "devDependencies": {
    "@babel/cli": "7.7.7",
    "@babel/core": "7.7.7",
    "@babel/plugin-proposal-class-properties": "7.7.4",
    "@babel/plugin-proposal-decorators": "7.7.4",
    "@babel/plugin-proposal-optional-chaining": "7.7.5",
    "@babel/preset-env": "7.7.7",
    "autoprefixer": "^9.7.4",
    "npm-run-all": "^4.1.5",
    "parcel": "^2.0.0-alpha.3.2"
  }
}
```

## 🤔 Expected Behavior

Using parcel to build my project should result in build assets that I can deploy.

## 😯 Current Behavior

When I do a `yarn build` (see code sample below) I get the following error:

```
🚨 Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, assert.default)((0, types.isIdentifier)(id))

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert.default)((0, _types.isIdentifier)(id))

    at isUnusedWildcard (/Users/mitaylor/Scratch/parcel2-build/node_modules/@parcel/scope-hoisting/lib/shake.js:102:25)
    at /Users/mitaylor/Scratch/parcel2-build/node_modules/@parcel/scope-hoisting/lib/shake.js:60:83
    at Array.some (<anonymous>)
    at getUnusedBinding (/Users/mitaylor/Scratch/parcel2-build/node_modules/@parcel/scope-hoisting/lib/shake.js:60:40)
    at /Users/mitaylor/Scratch/parcel2-build/node_modules/@parcel/scope-hoisting/lib/shake.js:30:21
    at Array.forEach (<anonymous>)
    at treeShake (/Users/mitaylor/Scratch/parcel2-build/node_modules/@parcel/scope-hoisting/lib/shake.js:29:33)
    at exit (/Users/mitaylor/Scratch/parcel2-build/node_modules/@parcel/scope-hoisting/lib/link.js:564:28)
    at NodePath._call (/Users/mitaylor/Scratch/parcel2-build/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/mitaylor/Scratch/parcel2-build/node_modules/@babel/traverse/lib/path/context.js:42:17)
⠋ Optimizing index.html...
```

## 🔦 Context

I am am trying to build my app for deployment.

## 💻 Code Sample

[parcel2-build.zip](https://github.com/parcel-bundler/parcel/files/4335805/parcel2-build.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2|
| Node             |v12.16.0|
| npm/Yarn         |yarn|
| Operating System | OSX Catalina |

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/pull/4266 will fix this as well

**Comment by Cristy94** [comment]
Same issue here, I was forced to add a `.babelrc` for my build to work, but now I get this error:
```
@parcel/packager-js: The expression evaluated to a falsy value:
  (0, assert.default)((0, types.isIdentifier)(id))
```

I had to add this .babelrc for my React + TypeScript project (if anyone is interested) to even get to this error:
```
{
    "presets": ["@babel/preset-typescript", "@babel/preset-react", "@babel/preset-env"],
    "plugins": [
      [
        "@babel/plugin-proposal-class-properties",
        {
          "loose": true
        }
      ]
    ]
  }
```
