### ISSUE TITLE
Cannot read property 'js' of null, probably caused by async/await in TypeScript

### ISSUE THREAD

**Issue by enepomnyaschih** [parcel-bundler/parcel#4398]
# 🐛 bug report

Bundling my project with Parcel results in an error.

## 🎛 Configuration (.babelrc, package.json, cli command)

1. Checkout "parcel-bug" tag in https://github.com/enepomnyaschih/jwidget/tree/parcel-bug repository.
1. Run "npm install" in the root.
1. Run "./build.sh" in "main" folder.
1. Run "./parcel.sh" in "examples" folder.

## 🤔 Expected Behavior

No errors.

## 😯 Current Behavior

Error:

```
×  Cannot read property 'js' of null
    at JSPackager.dedupeKey (C:\jwidget\git\node_modules\parcel-bundler\src\packagers\JSPackager.js:110:40)
    at JSPackager.addAsset (C:\jwidget\git\node_modules\parcel-bundler\src\packagers\JSPackager.js:42:22)
    at JSPackager.addAssetToBundle (C:\jwidget\git\node_modules\parcel-bundler\src\packagers\JSPackager.js:145:16)
    at JSPackager.writeBundleLoaders (C:\jwidget\git\node_modules\parcel-bundler\src\packagers\JSPackager.js:161:18)
    at JSPackager.end (C:\jwidget\git\node_modules\parcel-bundler\src\packagers\JSPackager.js:221:20)
    at async Bundle._package (C:\jwidget\git\node_modules\parcel-bundler\src\Bundle.js:222:5)
    at async Promise.all (index 0)
    at async Bundle.package (C:\jwidget\git\node_modules\parcel-bundler\src\Bundle.js:202:5)
    at async Promise.all (index 2)
    at async Bundle.package (C:\jwidget\git\node_modules\parcel-bundler\src\Bundle.js:202:5)
```

## 💁 Possible Solution

1. If you comment line 16 in examples/src/defer/DelayedGreeter.ts (`await defer(1000, this.cancelToken);`) and line 17 in examples/src/request/AjaxGreeter.ts (`const data = await request($.get("data.json"), this.cancelToken);`) out, the build will succeed. I tried to pinpoint the true reason, but it led me to no success, as approaching to the problem from different angles leads to different results. You can try to, but remember to run "./build.sh" after any code modification in "main" folder to force "examples" pick it up.
1. Funny thing is that if you do the opposite, i.e. delete all contents in examples/src folder except "defer", "request", "common" and "globals.d.ts", the build will succeed.
1. If you just run parcel without cleaning the cache from the previous failed build, the build will succeed. Which means that the bug has something to do with cache.

## 🔦 Context

I'm migrating my project from WebPack to Parcel, because I was impressed by how coincise, efficient and user-friendly Parcel is.

## 💻 Code Sample

See Configuration above.

## 🌍 Your Environment

| Software         | Version(s)       |
| ---------------- | ---------------- |
| Parcel           | 1.12.4 (latest)  |
| Node             | 12.16.1 (latest) |
| npm              | 6.14.4 (latest)  |
| TypeScript       | 3.8.3 (latest)   |
| Operating System | Windows 10       |

**Comment by enepomnyaschih** [comment]
Anybody?

**Comment by enepomnyaschih** [comment]
Ok, I've switched back to WebPack and removed the bounty.
