### ISSUE TITLE
Cannot find module postcss

### ISSUE THREAD

**Issue by robbyjm** [parcel-bundler/parcel#4448]
# 🐛 bug report

Parcel can't find postcss although postcss is properly installed and `package.json` has a valid main entry.
## 🎛 Configuration (.babelrc, package.json, cli command)
minimal package.json

```
{
  "name": "project_name",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "parcel index.html"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bootstrap": "^4.4.1",
    "jquery": "^3.4.1",
    "parcel-bundler": "^1.12.4",
    "popper.js": "^1.16.1",
    "sass": "^1.26.3"
  }
}
```

```
➜ project_name tree -L 1 -C   
.
├── dist
├── index.html   <--- main
├── node_modules
├── package-lock.json
├── package.json
└── scss
```

```
➜  project_name npm ls postcss --depth 1

└─┬ parcel-bundler@1.12.4
  ├── css-modules-loader-core@1.1.0
  ├── cssnano@4.1.10
  ├── htmlnano@0.2.5
  └── postcss@7.0.27  (git+https://github.com/postcss/postcss.git#fbd955546f3ca9ea2dc58e136e8a85db2641ebfe)
```

## 😯 Current Behavior

```
Server running at http://localhost:1234 
⚠️  Parser "assets/CSSAsset" failed to initialize when processing asset "node_modules/bootstrap/dist/css/bootstrap.min.css". Threw the following error:
Error: Cannot find module '/Users/robby/Documents/project_name/node_modules/postcss/lib/postcss'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:315:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (/Users/robby/Documents/project_name/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/robby/Documents/project_name/node_modules/parcel-bundler/src/assets/CSSAsset.js:2:17)
    at Module._compile (/Users/robby/Documents/project_name/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) falling back to RawAsset
✨  Built in 1.53s.
```

## 🔦 Context

Just trying to work on a bootstrap website. 

```
➜  project_name npm ls --depth 0

├── bootstrap@4.4.1
├── jquery@3.4.1
├── parcel-bundler@1.12.4
├── popper.js@1.16.1
└── sass@1.26.3
```

## 💻 Code Sample

```
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="./scss/custom.scss">
    <title>Hello, world!</title>
</head>

<body>
    <div class="jumbotron">
        <h1>Hello, world!</h1>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="node_modules/jquery/dist/jquery.min.js"></script>
    <script src="node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</body>

</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 13.8.0
| npm/Yarn         | 6.13.7
| Operating System | macOS 10.15.1

**Comment by mischnic** [comment]
So you have something like this in your package.json?

```json
{
	"devDependencies": {
		"postcss": "postcss/postcss#fbd955546f3ca9ea2dc58e136e8a85db2641ebfe"
	}
}
```

That doesn't work because postcss requires a build step (because their sources are ESM): https://github.com/postcss/postcss/tree/master/lib

Node searches for `postcss/lib/postcss.js`, but that does not exist in the git repo itself.

**Comment by robbyjm** [comment]
> 
> 
> Where does `postcss@7.0.27 (git+https://github.com/postcss/postcss.git#fbd955546f3ca9ea2dc58e136e8a85db2641ebfe)` come from?
> Parcel doesn't install it from GitHub: https://unpkg.com/browse/parcel-bundler@1.12.4/package.json
> 
> That doesn't work because postcss requires a build step (because their sources are ESM): https://github.com/postcss/postcss/tree/master/lib
> 
> Node searches for `postcss/lib/postcss.js`, but that does not exist in the git repo itself.

thank you. i had previously added postcss as a dependency to my project (from github) before i knew it came with parcel. i deleted my `node_modules` folder after learning it was already a dependency of parcel and re-ran `npm-install`. however i did not delete my `package-lock.json` and npm installed postcss from github instead of the npm registry.
