### ISSUE TITLE
Emit Codeframe for `loadConfig`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#4464]
# 🐛 bug report

`loadConfig` should emit a codeframe on a parse error:

https://github.com/parcel-bundler/parcel/blob/2f6274311889cad76fbdf2dafe60fc23478476d6/packages/core/utils/src/config.js#L80

This is for example used for loading `.postcssrc`.

## 🤔 Expected Behavior

See screenshot in https://github.com/parcel-bundler/parcel/pull/4420

## 😯 Current Behavior

With an invalid `.postcssrc` It doesn't even tell you the filename:

```
🚨 Build failed.
@parcel/transformer-postcss: JSON5: invalid character '"' at 5:3
SyntaxError: JSON5: invalid character '\"' at 5:3
    at syntaxError (.../parcel/node_modules/json5/lib/parse.js:1:12901)
    at invalidChar (.../parcel/node_modules/json5/lib/parse.js:1:12115)
    at Object.afterPropertyValue (.../parcel/node_modules/json5/lib/parse.js:1:8071)
    at Object._default [as default] (.../parcel/node_modules/json5/lib/parse.js:1:2193)
    at lex (.../parcel/node_modules/json5/lib/parse.js:1:1618)
    at parse (.../parcel/node_modules/json5/lib/parse.js:1:930)
    at loadConfig (.../parcel/packages/core/utils/src/config.js:80:18)
    at getConfig (.../parcel/packages/core/core/src/assetUtils.js:168:14)
    at UncommittedAsset.getConfig (.../parcel/packages/core/core/src/UncommittedAsset.js:337:16)
    at Object.getConfig (.../parcel/packages/transformers/postcss/src/PostCSSTransformer.js:29:29)
```

## 💁 Solution

Would be very similar to https://github.com/parcel-bundler/parcel/pull/4420

## 💻 Code Sample

A missing comma:
```json
{
	"plugins": {
		"postcss-import": {},
		"postcss-url": {}
		"postcss-custom-properties": {}
	}
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2

**Comment by muachilin** [comment]
I am interested in handling this issue! Thank you :)

**Comment by mischnic** [comment]
Great!
