### ISSUE TITLE
Require.cache causes errors

### ISSUE THREAD

**Issue by m-allanson** [parcel-bundler/parcel#4616]
# 🐛 bug report

Parcel does not transform `require.cache` when bundling, which cause an error when running the bundled file.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json5
// in package.json
"esm": "dist/index.js",
"targets": {
"esm": {
  "includeNodeModules": true,
  "outputFormat": "esmodule",
  "isLibrary": true
}
},
```

The bundle command is `parcel build index.js --target esm --no-minify`

## 🤔 Expected Behavior

The bundled output should run without error.

## 😯 Current Behavior

Running the bundled file will cause the following error:

```
file:///<path>/parcel-repro/dist/index.js:4
for (const file in require.cache) {
                           ^

ReferenceError: require is not defined
    at file:///<path>/parcel-repro/dist/index.js:4:28
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

## 💁 Possible Solution

Parcel 1 created a shim for `require.cache`. See this earlier issue and PR:

- https://github.com/parcel-bundler/parcel/issues/1959
- https://github.com/parcel-bundler/parcel/pull/1960

In the v2 branch there is [a skipped test for the shim](https://github.com/parcel-bundler/parcel/blob/9f71164b910bb7fef050d57d8ef9036f3aa17af6/packages/core/integration-tests/test/javascript.js#L2061). 

## 🔦 Context

I want to package `node_modules` dependencies into my bundle. Some of these dependencies make use of `require.cache`.

## 💻 Code Sample

Repro here: https://github.com/m-allanson/parcel-require-repro

The `dist` directory is committed too. 

Example code that will cause the error: 

```js
// in src file index.js
for (const file in require.cache) {
  if (/color/g.test(file)) {
    result[file] = true;
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | 12 or 14 (for ESM support)
| npm/Yarn         | npm
| Operating System | macOS

**Comment by mischnic** [comment]
Needs to be added here:
https://github.com/parcel-bundler/parcel/blob/9f71164b910bb7fef050d57d8ef9036f3aa17af6/packages/shared/scope-hoisting/src/hoist.js#L266-L280

**Comment by m-allanson** [comment]
A quick trial shows this working for me 👍 It reinstates the parcel v1 shim behaviour. Is there somewhere I can add tests?

```diff
     if (t.matchesPattern(path.node, 'module.id')) { 
       path.replaceWith(t.stringLiteral(asset.id)); 
     } 
  
     if (t.matchesPattern(path.node, 'module.hot')) { 
       path.replaceWith(t.identifier('null')); 
     } 
  
     if (t.matchesPattern(path.node, 'module.require') && !asset.env.isNode()) { 
       path.replaceWith(t.identifier('null')); 
     } 
  
+    if (t.matchesPattern(path.node, 'require.cache')  && !asset.env.isNode()) {
+      path.replaceWith(t.identifier('{}'));
+    }

     if (t.matchesPattern(path.node, 'module.bundle')) { 
       path.replaceWith(t.identifier('parcelRequire')); 
     } 
```

**Comment by mischnic** [comment]
The fixture would be similar to https://github.com/parcel-bundler/parcel/tree/v2/packages/core/integration-tests/test/integration/scope-hoisting/commonjs/require-resolve (also in the `commonjs` folder) and the test itself in https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/scope-hoisting.js.

**Comment by m-allanson** [comment]
Great, thank you! I aim to open a PR this week.

**Comment by navaru** [comment]
This issue should be closed

**Comment by DeMoorJasper** [comment]
@navaru it did not get fixed, the PR has been closed not merged.
