### ISSUE TITLE
Use the default Rust toolchain, not nightly 

### ISSUE THREAD

**Issue by vp2177** [parcel-bundler/parcel#4617]
# 🐛 Bug report

Parcel installs the `nightly` Rust toolchain, unnecessarily. WebAssembly support is now available on `stable`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Rust             | 1.43 `stable`
| Node       | 14.2.0

**Comment by DeMoorJasper** [comment]
In our CI pipeline we already switched to using the stable version, you probably mean that our autoinstall feature still installs a nightly?

Not sure if it's really an issue as you'd normally already have rust installed. We should however ensure we use the stable version if we get to implementing the rust pipeline in Parcel 2

**Comment by vp2177** [comment]
@DeMoorJasper Yes, I mean the autoinstall feature.

I already have Rust installed, including the `wasm32-unknown-unknown` target (for the `stable` toolchain). But autoinstall installs the `nightly` toolchain regardless.

**Comment by DeMoorJasper** [comment]
@vp2177 ow that sounds like a bug

**Comment by vp2177** [comment]
I have also tried `parcel@next` but it just crashes (unrelated to Rust support, but still):

```
> parcel --help

./node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → ./node_modules/@parcel/watcher/build/watcher.node
 → ./node_modules/@parcel/watcher/build/Debug/watcher.node
 → ./node_modules/@parcel/watcher/build/Release/watcher.node
 → ./node_modules/@parcel/watcher/out/Debug/watcher.node
 → ./node_modules/@parcel/watcher/Debug/watcher.node
 → ./node_modules/@parcel/watcher/out/Release/watcher.node
 → ./node_modules/@parcel/watcher/Release/watcher.node
 → ./node_modules/@parcel/watcher/build/default/watcher.node
 → ./node_modules/@parcel/watcher/compiled/14.2.0/darwin/x64/watcher.node
 → ./node_modules/@parcel/watcher/addon-build/release/install-root/watcher.node
 → ./node_modules/@parcel/watcher/addon-build/debug/install-root/watcher.node
 → ./node_modules/@parcel/watcher/addon-build/default/install-root/watcher.node
 → ./node_modules/@parcel/watcher/lib/binding/node-v83-darwin-x64/watcher.node
    at bindings (./node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (./node_modules/@parcel/watcher/index.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (./node_modules/@parcel/fs/lib/NodeFS.js:20:39)
    at Module._compile (internal/modules/cjs/loader.js:1176:30) {
  tries: [
```
