### ISSUE TITLE
Circular Dependencies issue

### ISSUE THREAD

**Issue by kbariotis** [parcel-bundler/parcel#463]
**Choose one:** this is a 🐛 bug report.

### 🎛 Configuration (.babelrc, package.json, cli command)

Two files: `index.html` and `about.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Document</title>
</head>
<body>
  
  <a href="./index.html">Home</a>
  <a href="./about.html">About</a>

</body>
</html>
```

### 🤔 Expected Behavior

Parcel bundler should overcome circular dependencies. (Although I am not sure how 🤔)

### 😯 Current Behavior

```
Server running at http://localhost:1234
🚨  Maximum call stack size exceeded
    at md5 (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/utils/md5.js:3:13)
    at HTMLAsset.generateBundleName (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Asset.js:170:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:396:46)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
```
### 💁 Possible Solution

Parcel bundler should not try to parse a dependency that has already parsed before (again I am not sure if this is possible).

### 💻 Code Sample

https://github.com/kbariotis/parcel-bootstrap-pug

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1 |
| Node             | 8.9.6 |
| npm         | 5.5.1 |
| Operating System | OSX High Sierra |

**Comment by dfang** [comment]
same here

**Comment by shawwn** [comment]
Confirmed: PR #489 fixes https://github.com/kbariotis/parcel-bootstrap-pug
