### ISSUE TITLE
Yarn Error in inital setup: Unknown version 67 of opera

### ISSUE THREAD

**Issue by eduardoarandah** [parcel-bundler/parcel#4639]
# 🐛 bug report

Followed exact instructions here (for yarn)
https://parceljs.org/getting_started.html

Got this error: Error in inital setup: Unknown version 67 of opera on these commands:

```
parcel index.html
parcel index.html --no-cache
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
console.log("hola mundo")
```

## 🤔 Expected Behavior

Serve the site

## 😯 Current Behavior

```
 /home/lalo/www/bmireact/public/index.js: Unknown version 67 of opera
 at Function.select (/home/lalo/.config/yarn/global/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:1085:17)
 at /home/lalo/.config/yarn/global/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:336:33
 at Array.reduce (<anonymous>)
 at resolve (/home/lalo/.config/yarn/global/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:318:18)
 at browserslist (/home/lalo/.config/yarn/global/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:442:21)
 at getTargets (/home/lalo/.config/yarn/global/node_modules/@babel/helper-compilation-targets/lib/index.js:202:48)
 at /home/lalo/.config/yarn/global/node_modules/@babel/preset-env/lib/index.js:246:57
 at Object.default (/home/lalo/.config/yarn/global/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12)
 at getEnvPlugins (/home/lalo/.config/yarn/global/node_modules/parcel-bundler/src/transforms/babel/env.js:62:34)
 at getEnvConfig (/home/lalo/.config/yarn/global/node_modules/parcel-bundler/src/transforms/babel/env.js:12:25)
```

## 💁 Possible Solution

**It WORKED when using npm instead of yarn**

```
npm install -g parcel-bundler

npm init -y

cat > index.html << 'EOL'
<html>
<body>
  <h1>Hola Mundo</h1>
  <script src="./index.js"></script>
</body>
</html>
EOL

cat > index.js << 'EOL'
console.log('hola mundo')
EOL

parcel index.html

```

## 🔦 Context

just following "get started" instructions. 

## 🌍 Your Environment

node v12.16.2
npm 6.14.4
yarn 1.21.1
parcel 1.12.4
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

**Comment by mischnic** [comment]
> It WORKED when using npm instead of yarn

This supports my guess that Yarn installs a browserslist version that doesn't know of Opera 67 in a browserslist config (which is emitted by some other package).

Using yarn with a local Parcel install works for me:
```sh
yarn add  parcel-bundler

cat > index.html << 'EOL'
<html>
<body>
  <h1>Hola Mundo</h1>
  <script src="./index.js"></script>
</body>
</html>
EOL

cat > index.js << 'EOL'
console.log('hola mundo')
EOL

yarn parcel index.html
```

So it looks like some other globally installed package "forces" Yarn to use a browserslist version that is too old.

**Comment by mischnic** [comment]
Closing due to inactivity
