### ISSUE TITLE
babel-preset-env error on initial parcel run

### ISSUE THREAD

**Issue by kootoopas** [parcel-bundler/parcel#464]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

Same as in #427, `yarn start`. *(I was trying to replicate #427 when this happened)*

### 🤔 Expected Behavior

To throw as in #427

### 😯 Current Behavior

```
🚨  /Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/easytimer.js/src/easytimer/easytimer.js: Couldn't find preset "env" relative to directory "/Users/Fotis/burns
    at /Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.getParserOptions (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/parcel-bundler/src/assets/JSAsset.js:60:20)
    at JSAsset.parse (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/parcel-bundler/src/assets/JSAsset.js:68:32)
```

### 💁 Possible Solution

All updates after the initial are giving the expected error
```
🚨  Cannot read property 'js' of null
    at Bundler.createBundleTree (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/parcel-bundler/src/Bundler.js:405:24)
    at Bundler.createBundleTree (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.buildQueuedAssets (/Users/Fotis/burnspace/scratchpad/bundler-427-dot-in-pkg-name/node_modules/parcel-bundler/src/Bundler.js:247:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

### 💻 Code Sample

`src/index.js`:
```
import easytimer from "easytimer.js";
```

### 🌍 Your Environment

Identical as in #427 except for high sierra version. (10.13.1).

**Comment by DeMoorJasper** [comment]
If this really is a duplicate this should be closed
