### ISSUE TITLE
Can't import eslint4b:  Property name expected type of string but got null

### ISSUE THREAD

**Issue by jorpic** [parcel-bundler/parcel#4654]
# 🐛 bug report

I'm trying to use [eslint4b](https://github.com/mysticatea/eslint4b) package in my project but parcel fails to build it.

## 🎛 Configuration (.babelrc, package.json, cli command)
**package.json**
```json
{
  "dependencies": {
    "eslint4b": "^7.1.0"
  }
}
```

## 🤔 Expected Behavior

Should build successfully and log some message to the browser's console.

## 😯 Current Behavior

```
$ parcel build index.html 
🚨  /home/user/t/bug/node_modules/eslint-utils/index.mjs: /home/user/t/bug/node_modules/eslint-utils/index.mjs: Property name expected type of string but got null
    at validate (/home/user/.npm-global/lib/node_modules/parcel/node_modules/@babel/types/lib/definitions/utils.js:160:13)
    at Object.validate (/home/user/.npm-global/lib/node_modules/parcel/node_modules/@babel/types/lib/definitions/utils.js:229:7)
    at validateField (/home/user/.npm-global/lib/node_modules/parcel/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (/home/user/.npm-global/lib/node_modules/parcel/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at builder (/home/user/.npm-global/lib/node_modules/parcel/node_modules/@babel/types/lib/builders/builder.js:38:27)
    at Object.Identifier (/home/user/.npm-global/lib/node_modules/parcel/node_modules/@babel/types/lib/builders/generated/index.js:337:31)
    at /home/user/.npm-global/lib/node_modules/parcel/node_modules/regenerator-transform/lib/hoist.js:32:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (/home/user/.npm-global/lib/node_modules/parcel/node_modules/regenerator-transform/lib/hoist.js:29:23)
    at exit (/home/user/.npm-global/lib/node_modules/parcel/node_modules/regenerator-transform/lib/hoist.js:51:20)
```
## 🔦 Context

My goal is to have eslint in browser and [eslint4b](https://github.com/mysticatea/eslint4b) is some kind of modification of eslint that is advertised to work in browser. For example it is used in [codemirror.next](https://github.com/codemirror/codemirror.next) (seems like they use rollup to bundle it).

## 💻 Code Sample

**index.html**
```html
<!DOCTYPE html>
<html>
  <script src="./index.js"></script>
</html>
```
**index.js**
```js
import Linter from "eslint4b";

console.log({linter: new Linter()});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 14.3.0
| npm         |  6.13.7
| Operating System | Arch Linux

**Comment by mischnic** [comment]
That's a very odd, and that error comes from Babel, not Parcel...

Works with Parcel 2

**Comment by jorpic** [comment]
@mischnic, thank you so much. Using Parcel 2 really solves my problem.

Seems like this is known bug in babel:
https://github.com/babel/babel/issues/11411
https://github.com/facebook/regenerator/issues/391

And the workaround is to use `.babelrc` without `@babel/plugin-transform-regenerator`.
