### ISSUE TITLE
Throwing anything but an Error object from a plugin causes a Parcel error

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/parcel#4665]
# 🐛 bug report

If plugins throw anything but an `Error` object, Parcel cannot handle it properly.

## 🤔 Expected Behavior

Parcel should the thrown error.

## 😯 Current Behavior

Parcel throws a cryptic error itself.
```
TypeError: Cannot read property 'replace' of undefined
    at markdownParser (PROJECT_DIR/node_modules/@parcel/markdown-ansi/lib/markdown-ansi.js:20:17)
    at prettyDiagnostic (PROJECT_DIR/node_modules/@parcel/utils/lib/prettyDiagnostic.js:37:167)
    at writeDiagnostic (PROJECT_DIR/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:142:43)
    at _report (/PROJECT_DIR/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:97:13)
    at Object.report (PROJECT_DIR/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:169:12)
    at ReporterRunner.report (PROJECT_DIR/node_modules/@parcel/core/lib/ReporterRunner.js:73:31)
    at async Parcel.build (PROJECT_DIR/node_modules/@parcel/core/lib/Parcel.js:396:7)
    at async Parcel.run (PROJECT_DIR/node_modules/@parcel/core/lib/Parcel.js:250:18)
    at async Command.run (PROJECT_DIR/node_modules/parcel/lib/cli.js:155:7)
```
## 💁 Possible Solution

From looking through the code, I discovered that Parcel tries to deconstruct the thrown object into its `message` (along with other things) before logging. If the thrown object is a raw string, it therefore splits into a bunch of `undefined`s, which causes an error when logging. I would suggest checking `instanceof Error` before deconstructing (I'm not sure what to do if it's not an `Error` object, maybe just log without any extra info?)

P.S. I haven't filled out the other bug report sections because they are not relevant to this bug.

**Comment by mischnic** [comment]
>  I would suggest checking instanceof Error before deconstructing

Yes, but this should happen further up in the chain (so in the CLIReporter). There, printing it can also be handled.
Maybe we can also modify the types to be `mixed` so that this is also caught (also in the future) by static analysis.

> P.S. I haven't filled out the other bug report sections because they are not relevant to this bug.

(In this case I can tell from the stack trace that it's Parcel 2, but generally the Parcel version is important as well.)

**Comment by 101arrowz** [comment]
Actually, from looking into it again, it seems to want a `Diagnostic` object. The only thing that seems necessary is a converter from arbitrary object (type `any`) to `Diagnostic` so that plugins could throw anything.

**Comment by mischnic** [comment]
Yes, but it should be `mixed` because Flow wouldn't complain about `somethingAny.message`.
