### ISSUE TITLE
Could not statically evaluate fs call

### ISSUE THREAD

**Issue by guotie** [parcel-bundler/parcel#469]
🐛 bug report 

run parcel, got error:

```
web\node_modules\mime\mime.js: Could not statically evaluate fs call
    at evaluate (F:\Users\tie\AppData\Roaming\npm\node_modules\parcel-bundler\src\visitors\fs.js:163:11)
    at CallExpression.path.get.map.arg (F:\Users\tie\AppData\Roaming\npm\node_modules\parcel-bundler\src\visitors\fs.js:30:21)
    at Array.map (<anonymous>)
    at JSAsset.CallExpression (F:\Users\tie\AppData\Roaming\npm\node_modules\parcel-bundler\src\visitors\fs.js:30:10)
    at NodePath._call (F:\Users\tie\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (F:\Users\tie\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (F:\Users\tie\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (F:\Users\tie\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (F:\Users\tie\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (F:\Users\tie\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\babel-traverse\lib\context.js:192:19)
```

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "license": "ISC",
  "dependencies": {
    "art-template": "^4.12.2",
    "autoprefixer": "^7.2.3",
    "babel-preset-env": "^1.6.1",
    "bulma": "^0.6.1",
    "fastify": "^0.37.0",
    "fastify-sequelize": "^1.0.4",
    "pg": "^7.4.0",
    "postcss-modules": "^1.1.0",
    "sequelize": "^4.28.6",
    "serve-static": "^1.13.1"
  },
  "devDependencies": {
    "typescript": "^2.6.2"
  }
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.4.1
| Node             | v8.9.1
| npm/Yarn         |
| Operating System | windows

**Comment by DeMoorJasper** [comment]
Could u add a code fragment with the fs call please?
This is probably happening because u use Asynchronous FS calls, those are not supported yet

**Comment by guotie** [comment]
fastify is all async, await

**Comment by Diamondjcx** [comment]
找到解决方法了吗？

**Comment by guotie** [comment]
可能是不支持。

**Comment by FourPig** [comment]
是什么鬼问题哟
