### ISSUE TITLE
length of undefined

### ISSUE THREAD

**Issue by NikosEfthias** [parcel-bundler/parcel#4691]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)
```
{
  "name": "barcode_ball_panel",
  "version": "1.0.0",
  "description": "",
  "main": "out.js",
  "scripts": {
    "build": "parcel build --no-source-maps --public-url ./ index.html",
    "start": "parcel index.html",
    "clean": "rimraf dist",
    "nuke": "rimraf dist .cache"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/NikosEfthias/barcode_ball_panel.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/NikosEfthias/barcode_ball_panel/issues"
  },
  "homepage": "https://github.com/NikosEfthias/barcode_ball_panel#readme",
  "devDependencies": {
    "bs-platform": "^7.3.2",
    "bsb-js": "^1.1.7",
    "elm-hot": "^1.1.4",
    "eslint": "^6.8.0",
    "node-elm-compiler": "^5.0.4",
    "parcel-bundler": "^1.12.4",
    "rimraf": "^3.0.2"
  },
  "dependencies": {
    "bootstrap": "^4.5.0"
  }
}
```

```js

```

## 🤔 Expected Behavior
parcelbundler used to build this project not i get an error it should just build fine as before since there are no updates to codebase

## 😯 Current Behavior
getting the following error 
```
🚨  Cannot read property 'length' of undefined
    at lineCounter (/home/nikos/.projects/barcode_ball_panel/node_modules/parc
el-bundler/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/home/nikos/.projects/barcode_ball_panel/node_m
odules/parcel-bundler/src/packagers/JSPackager.js:127:60)
    at async JSPackager.addAsset (/home/nikos/.projects/barcode_ball_panel/nod
e_modules/parcel-bundler/src/packagers/JSPackager.js:88:5)
    at async Bundle._addDeps (/home/nikos/.projects/barcode_ball_panel/node_mo
dules/parcel-bundler/src/Bundle.js:250:5)
    at async Bundle._package (/home/nikos/.projects/barcode_ball_panel/node_mo
dules/parcel-bundler/src/Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (/home/nikos/.projects/barcode_ball_panel/node_mod
ules/parcel-bundler/src/Bundle.js:202:5)
    at async Promise.all (index 1)
    at async Bundle.package (/home/nikos/.projects/barcode_ball_panel/node_mod
ules/parcel-bundler/src/Bundle.js:202:5)
    at async Promise.all (index 1)
```

## 💁 Possible Solution
No Clue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             |14.1 and 12.18 both fails
| npm/Yarn         |6.14
| Operating System |ubuntu focal

**Comment by NikosEfthias** [comment]
no solutions to this ?

**Comment by NikosEfthias** [comment]
no updates onthis bug ?

**Comment by mischnic** [comment]
Does deleting the cache (`.cache`) help?

**Comment by NikosEfthias** [comment]
it seemingly helped but the weird thing is that I just pulled the repo from github which didnt have a .cache directory initially.

**Comment by NikosEfthias** [comment]
@mischnic I dont now why would you close this while it is clearly a bug. Again I am having the same issue and cleaning cache does not help this time

**Comment by arthursw** [comment]
I also have this problem, and found no solution so far.

**Comment by danieltroger** [comment]
I just had this issue. I added a console.log(node.properties) above the failing line and this is how it looked:

```
console: []
🚨 Build failed.
@parcel/packager-js: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at ObjectExpression ([...]/node_modules/astring/dist/astring.js:780:25)
    at Object.generator.<computed> [as ObjectExpression] ([...]/node_modules/@parcel/babel-ast-utils/lib/generator.js:270:10)
    at Object.ArrowFunctionExpression ([...]/node_modules/astring/dist/astring.js:680:12)
    at Object.generator.<computed> [as ArrowFunctionExpression] ([...]/node_modules/@parcel/babel-ast-utils/lib/generator.js:270:10)
    at formatSequence ([...]/node_modules/astring/dist/astring.js:87:29)
    at Object.CallExpression ([...]/node_modules/astring/dist/astring.js:978:5)
    at Object.generator.<computed> [as CallExpression] ([...]/node_modules/@parcel/babel-ast-utils/lib/generator.js:270:10)
    at Object.MemberExpression ([...]/node_modules/astring/dist/astring.js:989:29)
    at Object.generator.<computed> [as MemberExpression] ([...]/node_modules/@parcel/babel-ast-utils/lib/generator.js:270:10)
    at Object.CallExpression ([...]/node_modules/astring/dist/astring.js:971:29)
```
    
But I changed the line `if (node.properties.length > 0) {` to `if (node?.properties?.length > 0) {` and now it builds again :)
    
    
And yes, I tried `rm -rf .parcel-cache .cache node_modules package-log.json dist dev_dist`  and `npm install --production=false` in all my module's directories. astring v `1.6.0` and parcel `2.0.0-nightly.524+97a7bfee`

**Comment by mischnic** [comment]
Can you please open a new issue with a reproduction?

**Comment by danieltroger** [comment]
Holy shit that was fast.

I logged a bit more, this are the two `node`s which don't have `.properties`:

```
console: Node {
  type: 'OptionalMemberExpression',
  start: 8425,
  end: 8462,
  loc: SourceLocation {
    start: Position { line: 221, column: 58 },
    end: Position { line: 221, column: 95 },
    filename: 'mymainfile.ts',
    identifierName: undefined
  },
  range: undefined,
  leadingComments: undefined,
  trailingComments: undefined,
  innerComments: undefined,
  extra: undefined,
  object: Node {
    type: 'OptionalMemberExpression',
    start: 8425,
    end: 8458,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: 'mymainfile.ts',
      identifierName: undefined
    },
    range: undefined,
    leadingComments: undefined,
    trailingComments: undefined,
    innerComments: undefined,
    extra: undefined,
    object: Node {
      type: 'OptionalMemberExpression',
      start: 8425,
      end: 8455,
      loc: [SourceLocation],
      range: undefined,
      leadingComments: undefined,
      trailingComments: undefined,
      innerComments: undefined,
      extra: undefined,
      object: [Node],
      computed: false,
      property: [Node],
      optional: true
    },
    computed: true,
    property: Node {
      type: 'NumericLiteral',
      start: 8456,
      end: 8457,
      loc: [SourceLocation],
      range: undefined,
      leadingComments: undefined,
      trailingComments: undefined,
      innerComments: undefined,
      extra: [Object],
      value: 0
    },
    optional: false
  },
  computed: false,
  property: Node {
    type: 'Identifier',
    start: 8460,
    end: 8462,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: 'mymainfile.ts',
      identifierName: 'id'
    },
    range: undefined,
    leadingComments: undefined,
    trailingComments: undefined,
    innerComments: undefined,
    extra: undefined,
    name: 'id'
  },
  optional: true
}
console: Node {
  type: 'OptionalMemberExpression',
  start: 9321,
  end: 9363,
  loc: SourceLocation {
    start: Position { line: 240, column: 42 },
    end: Position { line: 240, column: 84 },
    filename: 'mymainfile.ts',
    identifierName: undefined
  },
  range: undefined,
  leadingComments: undefined,
  trailingComments: undefined,
  innerComments: undefined,
  extra: undefined,
  object: Node {
    type: 'OptionalMemberExpression',
    start: 9321,
    end: 9354,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: 'mymainfile.ts',
      identifierName: undefined
    },
    range: undefined,
    leadingComments: undefined,
    trailingComments: undefined,
    innerComments: undefined,
    extra: undefined,
    object: Node {
      type: 'OptionalMemberExpression',
      start: 9321,
      end: 9351,
      loc: [SourceLocation],
      range: undefined,
      leadingComments: undefined,
      trailingComments: undefined,
      innerComments: undefined,
      extra: undefined,
      object: [Node],
      computed: false,
      property: [Node],
      optional: true
    },
    computed: true,
    property: Node {
      type: 'NumericLiteral',
      start: 9352,
      end: 9353,
      loc: [SourceLocation],
      range: undefined,
      leadingComments: undefined,
      trailingComments: undefined,
      innerComments: undefined,
      extra: [Object],
      value: 0
    },
    optional: false
  },
  computed: false,
  property: Node {
    type: 'Identifier',
    start: 9356,
    end: 9363,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: 'mymainfile.ts',
      identifierName: 'variant'
    },
    range: undefined,
    leadingComments: undefined,
    trailingComments: undefined,
    innerComments: undefined,
    extra: undefined,
    name: 'variant'
  },
  optional: true
}
```

I got very happy because that gave me a line number! The failing line in my code is this:
```
return [...new Set(dataLayer.map(v => v?.ecommerce?.detail?.products[0]?.variant).filter(v => v))]?.join("");
```

I will try to reproduce the issue in a simpler context and open an issue ASAP! It is possibly related to #5630

**Comment by mischnic** [comment]
@danieltroger A source file with
```js
let f = (v) => v?.variant;
console.log(f);
```
is enough to trigger this.

**Comment by ta3pks** [comment]
so with the reproducible example any idea whats going on ?

**Comment by ta3pks** [comment]
so with the reproducible example any idea whats going on ?

**Comment by danieltroger** [comment]
@NikosEfthias IIRC this was an issue with parcel 1 that's long resolved with parcel 2. Just upgrade.

**Comment by ta3pks** [comment]
I tried parcel 2 but it is in a very early stage now and supports half the things that parcel1 supports.

**Comment by danieltroger** [comment]
What does it not support that you'd need?

**Comment by ta3pks** [comment]
json and pug are 2 huge ones

**Comment by danieltroger** [comment]
I compiled something using pug yesterday using parcel 2 (are you sure it's not supported? It compiled but didn't run for other reasons).
After that experience I can only say

![fuck pug](https://i.imgflip.com/5grohj.jpg)

But what do you mean with not supporting JSON? Maybe it's time to try parcel 2 again, with the newest beta it's very close to release and imo great.

**Comment by ta3pks** [comment]
@danieltroger json is not listed as supported on parcel2 docs 
![image](https://user-images.githubusercontent.com/9097437/126707903-3a4eadeb-6370-4775-a3d4-f7c55375135f.png)
 also what problem did you encounter using pug I am using pug happily for years with 0 issues

**Comment by mischnic** [comment]
There are quite a few languages that are supported but not (yet) listed in the docs: https://github.com/parcel-bundler/parcel/blob/v2/packages/configs/default/index.json

**Comment by ta3pks** [comment]
Thanks. I guess I will try to migrate to parcel 2 slowly then so its correct to assume this bug on parcel 1 will not be fixed and parcel 1 is no longer maintained right ?
