### ISSUE TITLE
Parser "assets/JSAsset" fails but doesn't break build/ci

### ISSUE THREAD

**Issue by andrenanninga** [parcel-bundler/parcel#4817]
# 🐛 bug report

I ran into the same issue related to Babel and `assets/JSAsset` as described here: 
- https://github.com/parcel-bundler/parcel/issues/4276
- https://github.com/parcel-bundler/parcel/issues/4681

We resolved the issue itself but before we did it caused an empty build to be deployed since the error didn't stop the build/ci process. In #4681 @franky47 [describes the same issue](https://github.com/parcel-bundler/parcel/issues/4681#issuecomment-644166232)

## 🤔 Expected Behavior

When this error occurs I expect the build to fail so my CI process knows something isn't right.

## 😯 Current Behavior

The errors are caught by [`Parser.js`](https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/core/parcel-bundler/src/Parser.js#L81-L93) and only logged as warnings.

```
⚠️  Parser "assets/JSAsset" failed to initialize when processing asset "src/background/index.js". Threw the following error:
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/circleci/contentking/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/circleci/contentking/node_modules/@babel/preset-env/lib/index.js
- /home/circleci/contentking/node_modules/parcel-bundler/src/transforms/babel/env.js
- /home/circleci/contentking/node_modules/parcel-bundler/src/transforms/babel/config.js
- /home/circleci/contentking/node_modules/parcel-bundler/src/transforms/babel/transform.js
- /home/circleci/contentking/node_modules/parcel-bundler/src/assets/JSAsset.js
- /home/circleci/contentking/node_modules/parcel-bundler/src/Parser.js
- /home/circleci/contentking/node_modules/parcel-bundler/src/Bundler.js
- /home/circleci/contentking/node_modules/parcel-bundler/index.js
- /home/circleci/contentking/node_modules/parcel-bundler/src/cli.js
- /home/circleci/contentking/node_modules/parcel-bundler/bin/cli.js
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
   at Function.Module._load (internal/modules/cjs/loader.js:842:27)
   at Module.require (internal/modules/cjs/loader.js:1026:19)
   at require (/home/circleci/contentking/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
   at Object.<anonymous> (/home/circleci/contentking/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
   at Module._compile (/home/circleci/contentking/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
   at Module.load (internal/modules/cjs/loader.js:986:32)
   at Function.Module._load (internal/modules/cjs/loader.js:879:14)
   at Module.require (internal/modules/cjs/loader.js:1026:19) falling back to RawAsset
```

**Comment by mischnic** [comment]
Looks like the versions  of the various babel packages you have installed are incompatible (https://github.com/parcel-bundler/parcel/issues/4681).  Try upgrading all Babel packages to their latest version (this is probably prevent by your lockfile).
