### ISSUE TITLE
Error: Got unexpected null

### ISSUE THREAD

**Issue by NixonGit** [parcel-bundler/parcel#4860]
# 🐛 bug report

When using the `serve` or  `watch` command we get an error: `Error: Got unexpected null`.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
"scripts": {
  "build": "parcel build ./src/scripts/main.js --dist-dir public/assets",
  "watch": "parcel watch ./src/scripts/main.js --dist-dir public/assets",
  "serve": "parcel serve ./src/scripts/main.js --dist-dir public/assets"
}
```

No `.babelrc` or similar. 

## 🤔 Expected Behavior

Parcel watches changes with no error.

## 😯 Current Behavior

Parcel `build` works fine, so does `watch` when your first run the command, but as soon as you make a change to the entry file the following error is thrown.

```
Error: Got unexpected null
    at nullthrows (/Users/studiofour/Sites/craft/node_modules/nullthrows/nullthrows.js:7:15)
    at Asset.get publicId [as publicId] (/Users/studiofour/Sites/craft/node_modules/@parcel/core/lib/public/Asset.js:202:36)
    at /Users/studiofour/Sites/craft/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:102:19
    at Array.map (<anonymous>)
    at HMRServer.emitUpdate (/Users/studiofour/Sites/craft/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:83:50)
    at Object.report (/Users/studiofour/Sites/craft/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:125:21)
    at ReporterRunner.report (/Users/studiofour/Sites/craft/node_modules/@parcel/core/lib/ReporterRunner.js:73:31)
    at async Parcel.build (/Users/studiofour/Sites/craft/node_modules/@parcel/core/lib/Parcel.js:383:7)
    at async Parcel.startNextBuild (/Users/studiofour/Sites/craft/node_modules/@parcel/core/lib/Parcel.js:272:21)
    at async PromiseQueue._runFn (/Users/studiofour/Sites/craft/node_modules/@parcel/utils/lib/PromiseQueue.js:98:7) {
  framesToPop: 1
}
```

## 🔦 Context

Able to reproduce when `main.js` is a simple JS file with a var declaration. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^2.0.0-beta.1
| Node             | 12.18.2
| npm/Yarn         | npm 6.14.5
| Operating System | macOS 10.15.3

From the lock file @parcel/watcher is 2.0.0-alpha.7 and @parcel/core 2.0.0-nightly.328

**Comment by mischnic** [comment]
Looks like the `asset.publicId` is being loaded from the cache when an asset is reused...
