### ISSUE TITLE
SyntaxError: JSON5: invalid character when running parcel serve

### ISSUE THREAD

**Issue by Woile** [parcel-bundler/parcel#4863]
# 🐛 bug report

I'm running parcel + tailwind, it's a super basic setup.
I get a `SyntaxError` when running `parcel serve` in my ubuntu machine and I don't know how to debug it further.
The odd thing it's that works well in my debian machine.
I've tried running `yarn upgrade`, both have the same `node version` `12.18.2`.
I need some help, how can I pin point the issue?

## 🎛 Configuration (.babelrc, package.json, cli command)

It can be reproduced by cloning my repo:

https://github.com/Woile/willy-theme

```bash
git clone git@github.com:Woile/willy-theme.git
cd willy-theme/
yarn install
yarn start
```

## 🤔 Expected Behavior

`parcel serve` should run normally

## 😯 Current Behavior

This is the error I get:

```bash
$ parcel serve --host 0.0.0.0 ./src/**/*.html
SyntaxError: JSON5: invalid character 'e' at 1:1
    at syntaxError (/home/a-user/projects/willy-theme/node_modules/@parcel/utils/node_modules/json5/lib/parse.js:1:12901)
    at invalidChar (/home/a-user/projects/willy-theme/node_modules/@parcel/utils/node_modules/json5/lib/parse.js:1:12115)
    at Object.value (/home/a-user/projects/willy-theme/node_modules/@parcel/utils/node_modules/json5/lib/parse.js:1:3700)
    at lex (/home/a-user/projects/willy-theme/node_modules/@parcel/utils/node_modules/json5/lib/parse.js:1:1618)
    at parse (/home/a-user/projects/willy-theme/node_modules/@parcel/utils/node_modules/json5/lib/parse.js:1:930)
    at loadConfig (/home/a-user/projects/willy-theme/node_modules/@parcel/utils/lib/config.js:90:18)
    at async Server.applyProxyTable (/home/a-user/projects/willy-theme/node_modules/@parcel/reporter-dev-server/lib/Server.js:262:17)
    at async Server.start (/home/a-user/projects/willy-theme/node_modules/@parcel/reporter-dev-server/lib/Server.js:300:5)
    at async Object.report (/home/a-user/projects/willy-theme/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:59:31)
    at async ReporterRunner.report (/home/a-user/projects/willy-theme/node_modules/@parcel/core/lib/ReporterRunner.js:73:9) {
  lineNumber: 1,
  columnNumber: 1
}
```

## 🔦 Context

I just don't know how to debug further, I've tried `--log-level verbose` + `--profile`, but I don't see anything useful.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-beta.1` |
| Node             | `12.18.2` |
| npm/Yarn         | `1.22.4` |
| Operating System | Ubuntu 20.04 LTS |

**Comment by mischnic** [comment]
I've cloned your repo and don't get an error on `yarn start`.  Are you sure you have no `.proxyrc` or `.proxyrc.js` file in your project?

**Comment by Woile** [comment]
Oh wow! That was the issue :pray: I've been with it for hours already. Thanks a lot!!
We can close this now :D

**Comment by dfang** [comment]
@mischnic 

i got this error `SyntaxError: JSON5: invalid character 'm' at 1:1`,

tried willy-theme and even this [guide](https://v2.parceljs.org/getting-started/webapp/)

```
node -v
v14.8.0
```

**Comment by mischnic** [comment]
Do you have a .proxyrc file?

**Comment by dfang** [comment]
you mean github.com/athityakumar/proxyrc ?

no, i use a customized version proxy() and noproxy function in ~/.bashrc.

i've unset all http_proxy or HTTP_PROXY envs.

```
/tmp/parcel2-demo λ  noproxy
GOS_UPSTREAM_ADDRESS=https://goproxy.cn
Proxy environment variable removed.
/tmp/parcel2-demo λ  env | grep -i proxy
GOS_UPSTREAM_ADDRESS=https://goproxy.cn
```
how i run it:
```
cd /tmp
mkdir parcel2-demo
cd parcel2-demo
yarn init -y
yarn add --dev parcel@next

mkdir src
cat  << EOF > src/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My App</title>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
EOF
yarn parcel serve ./src/index.html
```

**Comment by mischnic** [comment]
No, this: https://v2.parceljs.org/features/api-proxy/

> here is how i run it:

Works fine for me
