### ISSUE TITLE
Parcel 2: windows vscode 1.47 integrated terminal results in @parcel/workers: Cannot find module 

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#4880]
# 🐛 bug report

Not sure if this really is a Parcel bug or a VSCode bug so I'm posting it in here just in case you guys know what could cause this.

Since updating to VSCode 1.47, when launching parcel in the integrated terminal, there's hundred of those errors thrown

```
@parcel/workers: Cannot find module '"c:/Users/Banou/AppData/Roaming/Code/User/workspaceStorage/4e7e841f7210b43b52e0e8c17857e439/ms-vscode.js-debug/bootloader.js"'
Require stack:
internal/preload
Error: Cannot find module '"c:/Users/Banou/AppData/Roaming/Code/User/workspaceStorage/4e7e841f7210b43b52e0e8c17857e439/ms-vscode.js-debug/bootloader.js"'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1345:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:119:5)
    at MessagePort.emit (events.js:315:20)   
    at MessagePort.onmessage (internal/worker/io.js:78:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.333
| Node             | v14.3.0
| npm/Yarn         | 1.22.0

**Comment by mischnic** [comment]
How can I reproduce this? Can't get it to happen on macOS:..

**Comment by Banou26** [comment]
I'm on windows, i started having this error after updating to the latest 1.47 VSCode version.

When trying to make a repro for this i discovered another consistent error :(
https://github.com/Banou26/parcel-bug-4880


```
Error: Got unexpected null
    at nullthrows (C:\Users\Banou\Desktop\New folder\node_modules\nullthrows\nullthrows.js:7:15)
    at Asset.get publicId [as publicId] (C:\Users\Banou\Desktop\New folder\node_modules\@parcel\core\lib\public\Asset.js:202:36)
    at C:\Users\Banou\Desktop\New folder\node_modules\@parcel\reporter-dev-server\lib\HMRServer.js:102:19
    at Array.map (<anonymous>)
    at HMRServer.emitUpdate (C:\Users\Banou\Desktop\New folder\node_modules\@parcel\reporter-dev-server\lib\HMRServer.js:83:50)
    at Object.report (C:\Users\Banou\Desktop\New folder\node_modules\@parcel\reporter-dev-server\lib\ServerReporter.js:125:21)
    at ReporterRunner.report (C:\Users\Banou\Desktop\New folder\node_modules\@parcel\core\lib\ReporterRunner.js:73:31)
    at async Parcel.build (C:\Users\Banou\Desktop\New folder\node_modules\@parcel\core\lib\Parcel.js:383:7)
    at async Parcel.startNextBuild (C:\Users\Banou\Desktop\New folder\node_modules\@parcel\core\lib\Parcel.js:272:21)
    at async PromiseQueue._runFn (C:\Users\Banou\Desktop\New folder\node_modules\@parcel\utils\lib\PromiseQueue.js:98:7) {
  framesToPop: 1
}
```

**Comment by mischnic** [comment]
>  Got unexpected null

I've already opened a PR for that: https://github.com/parcel-bundler/parcel/pull/4871

**Comment by Banou26** [comment]
Alrighty, i'm gonna try to get back that initial error as a repro then

**Comment by Banou26** [comment]
My original project workspace still has the `Cannot find module` error.
When trying to copy it and remove stuff to pinpoint where the problem was i started having both

`Got unexpected null`
and
```
@parcel/cache: EPERM: operation not permitted, rename 'C:devproject.parcel-cachedf5e3721315fdad2990aa04fb9a7d388.v8.28688.0.0' -> 'C:devproject.parcel-cachedf5e3721315fdad2990aa04fb9a7d388.v8'
Error: EPERM: operation not permitted, rename 'C:\dev\project\.parcel-cache\df\5e3721315fdad2990aa04fb9a7d388.v8.28688.0.0' -> 'C:\dev\project\.parcel-cache\df\5e3721315fdad2990aa04fb9a7d388.v8'
```
which always happen so i'm not really sure if i'll be able to give a repro for the original error while these keep throwing

**Comment by mischnic** [comment]
The `unexpected null` fix is merged, will be in the next nightly.

I though the cache problem was fixed? https://github.com/parcel-bundler/parcel/issues/4495

**Comment by Banou26** [comment]
Well, I thought so too, but as far as i can see it's not a blocking error, these are just thrown but don't crash the actual build.
So obviously fixing this to remove the errors would be nice but if it's still working this shouldn't be that big of a problem for now.
```
@parcel/cache: EPERM: operation not permitted, rename 'C:devoz - Copy.parcel-cachedf5e3721315fdad2990aa04fb9a7d388.v8.48636.0.8' -> 'C:devoz - Copy.parcel-cachedf5e3721315fdad2990aa04fb9a7d388.v8'
Error: EPERM: operation not permitted, rename 'C:\dev\oz - Copy\.parcel-cache\df\5e3721315fdad2990aa04fb9a7d388.v8.48636.0.8' -> 'C:\dev\oz - Copy\.parcel-cache\df\5e3721315fdad2990aa04fb9a7d388.v8'
√ Built in 7.69s
```

**Comment by Banou26** [comment]
After installing `parcel@2.0.0-beta.1` & following https://github.com/microsoft/vscode-js-debug/issues/374#issuecomment-622239998's steps, i finally managed to have my project working again
