### ISSUE TITLE
bundleGraph.getAssetPublicId is not a function

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#4886]
# 🐛 bug report

I'm getting the following error:

```
@parcel/packager-html: bundleGraph.getAssetPublicId is not a function
TypeError: bundleGraph.getAssetPublicId is not a function
    at /Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/packager-js/lib/JSPackager.js:143:53
    at enter (/Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/core/lib/Graph.js:510:16)
    at enter (/Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/core/lib/Graph.js:510:16)
    at walk (/Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/core/lib/Graph.js:345:26)
    at walk (/Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/core/lib/Graph.js:366:22)
    at Graph.dfs (/Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/core/lib/Graph.js:390:12)
    at BundleGraph.traverseBundle (/Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/core/lib/BundleGraph.js:524:24)
    at NamedBundle.traverse (/Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/core/lib/public/Bundle.js:168:54)
    at Object.package (/Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/packager-js/lib/JSPackager.js:117:12)
    at async PackagerRunner.package (/Users/jasperdemoor/Documents/libero/react-main-application/node_modules/@parcel/core/lib/PackagerRunner.js:211:14
```

Just logging this issue for now as I won't be able to really debug this right away, if anyone knows how to solve this quickly feel free to do so otherwise I'll look into it later today.

## 🤔 Expected Behavior

Should not happen

## 💁 Possible Solution

Downgrade to the beta before any of this publicId logic was implemented.

## 🌍 Your Environment

`"parcel": "2.0.0-nightly.333"`
Node 12

**Comment by mischnic** [comment]
Apart from the error, the logging origin seems to be wrong?
```
@parcel/packager-html:....
....
    at ...../JSPackager.js
```

**Comment by DeMoorJasper** [comment]
@mischnic yeah not sure how that happened

**Comment by mischnic** [comment]
Maybe the versions of @parcel/core and @parcel/packager-js are mismatched? (old core and new pacakger)

**Comment by DeMoorJasper** [comment]
@mischnic it does seem like something with dependencies going crazy, will close this issue for now...

Will update it another time, don't really wanna waste hours debugging yarn or npm issues
