### ISSUE TITLE
Adding `@babel/preset-env` on .babelrc breaks `parcel build`

### ISSUE THREAD

**Issue by cloud-walker** [parcel-bundler/parcel#4897]
# 🐛 bug report

I'm trying to use `parcel 2.0.0-beta.1`.

I need to use the `.babelrc.js` file in order to configure `jest`:

```javascript
module.exports = api => {
  if (api.env('test')) {
    return {
      presets: [
        ['@babel/preset-env', {targets: {node: 'current'}}],
        '@babel/preset-react',
      ],
    }
  }

  return {
    presets: ['@babel/preset-env', '@babel/preset-react'],
  }
}
```

But this breaks `parcel build`:

```
 Build failed.
@parcel/packager-js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got undefined
TypeError: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got undefined
    at Object.validate (/path/to/my/project/node_modules/@babel/types/lib/definitions/utils.js:132:11)
    at validateField (/path/to/my/project/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at Object.validate (/path/to/my/project/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/path/to/my/project/node_modules/@babel/traverse/lib/path/replacement.js:172:7)
    at NodePath._remove (/path/to/my/project/node_modules/@babel/traverse/lib/path/removal.js:57:10)
    at NodePath.remove (/path/to/my/project/node_modules/@babel/traverse/lib/path/removal.js:36:8)
    at pathRemove (/path/to/my/project/node_modules/@parcel/scope-hoisting/lib/utils.js:125:8)
    at remove (/path/to/my/project/node_modules/@parcel/scope-hoisting/lib/shake.js:183:29)
    at /path/to/my/project/node_modules/@parcel/scope-hoisting/lib/shake.js:39:79
    at Array.forEach (<anonymous>)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1 |
| Node             | 14.5 |
| npm/Yarn         | yarn 1.22 |
| Operating System | MacOS Mojave |

**Comment by mischnic** [comment]
Not that this error is ideal, but this is probably caused by `@babel/preset-env` emitting transpiled CommonJS output which messes up the scope hoisting compiler.

Does using `@parcel/babel-preset-env` instead of `@babel/preset-env` work? This should forward Parcel's default config.

And maybe using a JSON Babel config works in your case as well, which enables better caching for Parcel (I haven't tested this config myself):
```json
{
  "presets": [["@babel/preset-env", {"targets": {"node": "current"}}], "@babel/preset-react"],
  "env": {
    "test": {
      "presets": ["@parcel/babel-preset-env", "@babel/preset-react"]
    }
  }
}
```

**Comment by cloud-walker** [comment]
Using `@parcel/babel-preset-env` fix the issue! I'm wondering if its documented somewhere?

**Comment by mischnic** [comment]
Great! It will be once the Babel page of the docs once we've actually written it (https://v2.parceljs.org/languages/babel/)
