### ISSUE TITLE
Vue not working in development and fails to build in production

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/parcel#4929]
# 🐛 bug report

Vue projects fail in both development and production  

## 🎛 Configuration (.babelrc, package.json, cli command)

Zero config

`parcel src/index.html`
`parcel build src/index.html`

## 🤔 Expected Behavior

First command serves a working Vue project
Second command builds the project for production

## 😯 Current Behavior

The first command works, but the resulting served bundle says:
![bug](https://user-images.githubusercontent.com/29579245/88322355-76b69900-ccd5-11ea-8d1a-5f3a57a28ec5.png)
The second command says:
```
🚨 Build failed.
@parcel/packager-js: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at BundleGraph.getDependencies (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:375:18)
    at BundleGraph.resolveSymbol (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:700:21)
    at BundleGraph.resolveSymbol (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:730:18)
    at BundleGraph.resolveSymbol (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:730:18)
    at BundleGraph.resolveSymbol (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:730:18)
    at BundleGraph.resolveSymbol (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:730:18)
    at BundleGraph.resolveSymbol (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:730:18)
    at BundleGraph.resolveSymbol (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:730:18)
    at BundleGraph.resolveSymbol (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:730:18)
    at BundleGraph.resolveSymbol (/home/USERNAME/Dev/vue-template/node_modules/@parcel/core/lib/BundleGraph.js:730:18)
```

## 💁 Possible Solution

There are duplicate module specifiers in the generated JS for development:
![bug3](https://user-images.githubusercontent.com/29579245/88322643-de6ce400-ccd5-11ea-8284-56aa52f2cf6d.png)

Not sure why, these worked in the tests.

## 🔦 Context

I'm trying to create a Vue project in Parcel 2.

## 💻 Code Sample

Reproduction repo: [link](https://github.com/101arrowz/vue-parcel-bug)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | nightly (2.0.0-nightly.349)
| Node             | 14.5.0
| npm/Yarn         | Yarn 1.22.4
| Operating System | Ubuntu 18.04 LTS on WSL

**Comment by mischnic** [comment]
> Maximum call stack size exceeded

I'm guessing there is some loop in the bundle graph?

**Comment by 101arrowz** [comment]
It's probably a bug with pipeline specifiers not being used to generate the module specifier. That could also be causing the recursive bug in the production build.

**Comment by 101arrowz** [comment]
I've found the problem. The Vue transformer basically tries to import itself with certain pipelines by emitting JS code with import statements, but for some reason, the Vue transformer is only called once during the first processing of the asset, never again with script:./App.vue or anything like that. Any idea why this could be happening? It never happened in the tests.

**Comment by 101arrowz** [comment]
@mischnic In the development build (and the test environment) for Parcel, everything works smoothly, but the NPM package has different behavior and does not seem to call the transformers needed to generate the JS for the dependencies (that, or it ignores the pipeline and thinks that it the asset has already been generated). Is there anything that could have caused this?

**Comment by 101arrowz** [comment]
After debugging a bit, I found the root of the issue. By hot-fixing `node_modules/@parcel/core/lib/Transformation.js`, I can verify that Vue works after this patch.
