### ISSUE TITLE
Bad ERROR, nothing to debug this error

### ISSUE THREAD

**Issue by ladifire** [parcel-bundler/parcel#4961]
``@parcel/packager-js: Cannot read property 'right' of undefined
TypeError: Cannot read property 'right' of undefined
    at NodePath._getKey (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@babel/traverse/lib/path/family.js:178:25)
    at NodePath.get (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@babel/traverse/lib/path/family.js:170:17)
    at NodePath._getPattern (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@babel/traverse/lib/path/family.js:210:21)
    at NodePath.get (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@babel/traverse/lib/path/family.js:172:17)
    at Object.generateExports (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@parcel/scope-hoisting/lib/formats/commonjs.js:351:38)
    at exit (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@parcel/scope-hoisting/lib/link.js:640:31)
    at NodePath._call (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@babel/traverse/lib/path/context.js:99:8)
    at TraversalContext.visitQueue (/mnt/01D4AF1F1FC8FE60/Github/XXX/node_modules/@babel/traverse/lib/context.js:112:16)
```

With this ERROR output, how can we debug it??? Impossible

**Comment by DeMoorJasper** [comment]
Could you create a minimal reproducible example please? This looks like an issue with scope-hoisting.

The error isn't really that bad though... It just points to something internal in babel and to our scopehoisting

**Comment by mischnic** [comment]
I don't think so, seems to be this line:
https://github.com/parcel-bundler/parcel/blob/22b0143af3d855d4a30ef5a830a9418296904b81/packages/shared/scope-hoisting/src/formats/commonjs.js#L474
No idea how this error could occur..
