### ISSUE TITLE
Error using MemoryFS: Corresponding Handle was not found. It may have been disposed.

### ISSUE THREAD

**Issue by Aaronius** [parcel-bundler/parcel#5015]
# 🐛 bug report

We have a long-running node process that runs Parcel multiple times in succession. The first time it runs Parcel, it succeeds just fine. The second time it runs Parcel, it fails with the following error:

```
🚨 Build failed.
Error: Corresponding Handle was not found. It may have been disposed.
Error: Corresponding Handle was not found. It may have been disposed.
    at /srv/furnace/node_modules/@parcel/workers/lib/Handle.js:59:17
    at MemoryFS._sendWorkerEvent (/srv/furnace/node_modules/@parcel/fs/lib/MemoryFS.js:532:13)
    at MemoryFS.writeFile (/srv/furnace/node_modules/@parcel/fs/lib/MemoryFS.js:164:16)
    at /srv/furnace/node_modules/@parcel/fs/lib/MemoryFS.js:90:24
    at WorkerFarm.processRequest (/srv/furnace/node_modules/@parcel/workers/lib/WorkerFarm.js:271:45)
    at Worker.<anonymous> (/srv/furnace/node_modules/@parcel/workers/lib/WorkerFarm.js:184:39)
    at Worker.emit (events.js:315:20)
    at Worker.receive (/srv/furnace/node_modules/@parcel/workers/lib/Worker.js:145:12)
    at ThreadsWorker.onMessage (/srv/furnace/node_modules/@parcel/workers/lib/Worker.js:74:64)
    at ThreadsWorker.handleMessage (/srv/furnace/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:58:10)
    at Worker.<anonymous> (/srv/furnace/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:43:44)
    at Worker.emit (events.js:315:20)
    at MessagePort.<anonymous> (internal/worker.js:192:55)
    at MessagePort.emit (events.js:315:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

We're using the in-memory file system. Here's a trimmed down example that demonstrates the issue:

**build.js**
```js
#!/usr/bin/env node
const path = require("path");
const { default: Parcel, createWorkerFarm } = require('@parcel/core');
const { NodeFS, MemoryFS } = require('@parcel/fs');
const { default: defaultConfigContents } = require("@parcel/config-default");

const bundle = async () => {
  const VIRTUAL_DIST_DIR = '/dist';
  const workerFarm = createWorkerFarm();
  const inputFS = new NodeFS();
  const outputFS = new MemoryFS(workerFarm);
  await outputFS.mkdirp(VIRTUAL_DIST_DIR);

  try {
    const bundler = new Parcel({
      entries: path.join(__dirname, 'src/index.js'),
      sourceMaps: false,
      patchConsole: false,
      autoinstall: false,
      scopeHoist: true,
      // We don't currently want to be sharing the cache between
      // builds. More testing needs to be done to make sure that
      // would work without an ever-growing cache blowing up the system.
      disableCache: true,
      inputFS,
      outputFS,
      workerFarm,
      distDir: VIRTUAL_DIST_DIR,
    });

    await bundler.run();
  } finally {
    await workerFarm.end();
  }
}

(async () => {
  console.log('Starting first build.');
  await bundle();
  console.log('Starting second build.');
  await bundle();
  console.log(bundleCode);
})();
```

**.parcelrc**

```
{
  "bundler": "@parcel/bundler-default",
  "transformers": {
    "*.js": ["@parcel/transformer-babel","@parcel/transformer-js"]
  },
  "runtimes": {
    "browser": ["@parcel/runtime-js"]
  },
  "packagers": {
    "*.js": "@parcel/packager-js"
  },
  "namers": ["@parcel/namer-default"],
  "resolvers": ["@parcel/resolver-default"],
  "reporters": ["@parcel/reporter-cli"]
}
```

If you run `build.js` from the command-line, you should see the error. The contents of the entry file doesn't seem to matter. The contents I used during my test was simply `console.log("Hello world!");`.

## 🤔 Expected Behavior

No error. I was expecting a successful build, similar to the first build.

## 😯 Current Behavior

On the second build, I receive:

```
🚨 Build failed.
Error: Corresponding Handle was not found. It may have been disposed.
Error: Corresponding Handle was not found. It may have been disposed.
    at /srv/furnace/node_modules/@parcel/workers/lib/Handle.js:59:17
    at MemoryFS._sendWorkerEvent (/srv/furnace/node_modules/@parcel/fs/lib/MemoryFS.js:532:13)
    at MemoryFS.writeFile (/srv/furnace/node_modules/@parcel/fs/lib/MemoryFS.js:164:16)
    at /srv/furnace/node_modules/@parcel/fs/lib/MemoryFS.js:90:24
    at WorkerFarm.processRequest (/srv/furnace/node_modules/@parcel/workers/lib/WorkerFarm.js:271:45)
    at Worker.<anonymous> (/srv/furnace/node_modules/@parcel/workers/lib/WorkerFarm.js:184:39)
    at Worker.emit (events.js:315:20)
    at Worker.receive (/srv/furnace/node_modules/@parcel/workers/lib/Worker.js:145:12)
    at ThreadsWorker.onMessage (/srv/furnace/node_modules/@parcel/workers/lib/Worker.js:74:64)
    at ThreadsWorker.handleMessage (/srv/furnace/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:58:10)
    at Worker.<anonymous> (/srv/furnace/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:43:44)
    at Worker.emit (events.js:315:20)
    at MessagePort.<anonymous> (internal/worker.js:192:55)
    at MessagePort.emit (events.js:315:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
```

## 💁 Possible Solution
I'm not sure. I haven't tried walking through the fs logic to see what might be happening yet.

## 🔦 Context
Just trying to run multiple builds within a single node process.

## 💻 Code Sample
See Configuration section. I can hook you up with a code repo if it helps.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.1
| Node             | 12.12.0
| npm/Yarn         | npm v6.13.4
| Operating System | Mac Mojave

**Comment by Aaronius** [comment]
I noticed if I modify my code so that the worker farm, inputFS, and outputFS are only created once and then re-used across builds (and never calling `workerFarm.end()`), I do not get the error and both builds seem to succeed. I'm not sure what the ramifications are as far as memory usage goes though. We will be potentially running thousands of builds in sequence in the same long-lived node process.

**Comment by mischnic** [comment]
>  I suppose I need to at least delete the bundle output file from the in-memory file system, right?

Yes, I would just create a new outputFS on every build. (The `.parcel-cache` cache is also written into the outputFS, even with disableCache as it's used for IPC)

**Comment by Aaronius** [comment]
Ugh..sorry, I know it's annoying when you try to reproduce a bug and it works for you. I've created a repo that demonstrates the issue: https://github.com/Aaronius/parcel2bug Just follow the readme. Again, I'm not really sure it's actually a bug. It may just be that the documentation on how to use the in-memory file system needs to be expanded to cover this type of use case.

Thanks for your insight on just recreating outputFS on every build. Okay, so I'll create a single workerFarm (that I won't call `end()` on) and inputFS and use them across builds, but I'll create a new outputFS for each build. I haven't done any sort of memory profiling, but that I at least don't get any errors. Here are the changes I've made for that in case you're interested: https://github.com/Aaronius/parcel2bug/compare/master...reuse-worker-farm-and-input

Thanks for your help.

**Comment by mischnic** [comment]
> Just follow the readme

Apparently, the error only occurs when installing with npm and not Yarn. That's why I wasn't seeing it before.

> Here are the changes I've made for that in case you're interested

👍 

Though it's possible we have a memory leak somewhere:

<img width="777" alt="Bildschirmfoto 2020-08-13 um 19 26 04" src="https://user-images.githubusercontent.com/4586894/90166638-d6ff9e80-dd9a-11ea-823d-086e7c9dcd9e.png">

**Comment by Aaronius** [comment]
Oh, that's very interesting. Do you want me to create a different issue for the potential memory leak?
