### ISSUE TITLE
🐛 Cannot read property 'getAsset' of undefined

### ISSUE THREAD

**Issue by tarnenok** [parcel-bundler/parcel#502]
🐛 bug report

I try to compile typescript file using following command `parcel index.ts`

index.ts content
```
const test = "test"
```
### 🎛 Configuration (.babelrc, package.json, cli command)

zero config

### 🤔 Expected Behavior
working behavior
### 😯 Current Behavior
```
Server running at http://localhost:1234
⏳  Building index.ts...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
🚨  C:\projects\pressball\chrome-extension\index.ts: Cannot read property 'getAsset' of undefined
    at exports.run (C:\Users\tarne\AppData\Roaming\npm\node_modules\parcel-bundler\src\worker.js:13:24)
    at handle (C:\Users\tarne\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\worker-farm\lib\child\index.js:44:8)
    at process.<anonymous> (C:\Users\tarne\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\worker-farm\lib\child\index.js:51:3)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1,4.1
| Node             |  8.9.0
| npm/Yarn         | 5.5.1
| Operating System | Windows 10

**Comment by DeMoorJasper** [comment]
Does this happen every time?
At first sight it appears to be an error with the worker farm

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tarnenok** [comment]
If I compile .js file or empty .ts file everything is ok.

**Comment by leoyoung07** [comment]
I met the same issue. Using local typescript (`npm install -D typescript`) instead of global typescript solved the problem.

**Comment by cwgabel** [comment]
I ran npm init and the error went away.
