### ISSUE TITLE
parcel watch (v2) cannot build package with module target

### ISSUE THREAD

**Issue by myobie** [parcel-bundler/parcel#5075]
# 🐛 bug report

Working on a module with a `package.json` which includes a `"module": "index.mod.js"` key fails with `parcel watch .` with error `@parcel/packager-js: esmodule output is not supported without scope hoisting.`

## 🎛 Configuration (.babelrc, package.json, cli command)

In `package.json`:

```js
{
  "source": "file.ts",
  "module": "dist/index.mod.js",
  "types": "dist/index.d.ts"
}
```

## 🤔 Expected Behavior

`parcel watch` should be able to build the package `parcel build` can build.

## 😯 Current Behavior

`parcel watch` cannot build any package which outputs an ES module because `watch` disables scope hoisting and there is not a way to re-enable scope hoisting.

```
🚨 Build failed.
@parcel/packager-js: esmodule output is not supported without scope hoisting.
Error: esmodule output is not supported without scope hoisting.
    at Object.package (/project/.yarn/$$virtual/@parcel-packager-js-virtual-ea85704bdf/0/cache/@parcel-packager-js-npm-2.0.0-nightly.366-df27b353b2-910e4fb02c.zip/node_modules/@parcel/packager-js/lib/JSPackager.js:91:13)
    at PackagerRunner.package (/project/.yarn/cache/@parcel-core-npm-2.0.0-nightly.364-ebdaeb16a5-dbd6b3ad0a.zip/node_modules/@parcel/core/lib/PackagerRunner.js:213:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PackagerRunner.getBundleResult (/project/.yarn/cache/@parcel-core-npm-2.0.0-nightly.364-ebdaeb16a5-dbd6b3ad0a.zip/node_modules/@parcel/core/lib/PackagerRunner.js:179:20)
    at async PackagerRunner.getBundleInfo (/project/.yarn/cache/@parcel-core-npm-2.0.0-nightly.364-ebdaeb16a5-dbd6b3ad0a.zip/node_modules/@parcel/core/lib/PackagerRunner.js:171:9)
    at async Child.handleRequest (/project/.yarn/$$virtual/@parcel-workers-virtual-32c1103889/0/cache/@parcel-workers-npm-2.0.0-nightly.366-966b9aca70-5b5ea20ebe.zip/node_modules/@parcel/workers/lib/child.js:171:9)
```

## 💁 Possible Solution

Either auto-detect the ES module output and re-enable scope hoisting or make a CLI flag `--scope-hoisting` to re-enable it.

## 🔦 Context

Cannot watch packages which output ES modules.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.364 |
| Node             | v14.2.0 |
| npm/Yarn         | yarn 2.1.1 |
| Operating System | macOS 10.15.6 |

**Comment by aminya** [comment]
Same error. Not sure what happens. I tried setting different scopeHoist options but none of them worked.

```json
  "targets": {
    "main": {
      "context": "browser",
      "engines": {
        "browsers": "> 0.25%"
      },
      "includeNodeModules": true,
      "isLibrary": true
    },
    "module": {
      "context": "browser",
      "engines": {
        "browsers": "Chrome 76"
      },
      "includeNodeModules": false,
      "isLibrary": true
    }
  },
```

build works but dev does not.
```
    "dev": "cross-env NODE_ENV=development parcel watch src/SimpleTable.tsx",
    "build": "cross-env NODE_ENV=production parcel build src/SimpleTable.tsx",
```

**Comment by mischnic** [comment]
ES modules can only be created with scope-hoisting, but that isn't used in development at the moment because:
- it's incompatible with HMR
- it's very slow (compared to `--no-scope-hoist`)

We should somehow make this possible anyway...

**Comment by aminya** [comment]
For now, I think the error message should be changed to a warning and contain a text like this:
```
ES modules can only be created with scope-hoisting, but that isn't used in development for now.
```

IMO, Parcel's missing implementations should not be considered an error for the users, so it should become a warning.
