### ISSUE TITLE
Why there is error pointing errors on even core files.

### ISSUE THREAD

**Issue by amarg26** [parcel-bundler/parcel#5113]
whenever I run npm run dev only for first time but it doesn't appear second time.

I am getting errors on all js files. Is it serious issue or should be ignored ?

C:\Development-Folder\RHMS>npm run dev

> RHMS@1.0.0 dev C:\Development-Folder\RHMS
> parcel index.html

Server running at http://localhost:1234 
‼  Could not load existing sourcemap of "js/bootstrap.min.js".
‼  Could not load existing sourcemap of "css/bootstrap.min.css".
‼  Could not load existing sourcemap of "css/bootstrap.min.css".
‼  Could not load existing sourcemap of "js/bootstrap.min.js".`

Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/jquery-3.5.1.min.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:124:14 Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19) {
  isAbortError: true
}
Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/bootstrap.min.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:83:27 Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19) {
  isAbortError: true
}
Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/index.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:83:27 Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19) {
  isAbortError: true
}
Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/jquery-3.5.1.min.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:124:14
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:520:9)
    at processTimers (internal/timers.js:494:7) Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:520:9)
    at processTimers (internal/timers.js:494:7) {
  isAbortError: true
}
Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/bootstrap.min.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:83:27
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:520:9)
    at processTimers (internal/timers.js:494:7) Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:520:9)
    at processTimers (internal/timers.js:494:7) {
  isAbortError: true
}
Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/index.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:83:27
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:520:9)
    at processTimers (internal/timers.js:494:7) Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:520:9)
    at processTimers (internal/timers.js:494:7) {
  isAbortError: true
}
Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/jquery-3.5.1.min.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:124:14 Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19) {
  isAbortError: true
}
Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/bootstrap.min.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:83:27 Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19) {
  isAbortError: true
}
Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/index.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:83:27 Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19) {
  isAbortError: true
}
/ Building bundle-url.js...Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/jquery-3.5.1.min.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:124:14 Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19) {
  isAbortError: true
}
Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/bootstrap.min.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:83:27 Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19) {
  isAbortError: true
}
- Building bundle-url.js...Error: Could not load script: "file:///C:/Development-Folder/RHMS/js/index.js"
    at onErrorWrapped (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:38:19)
    at Object.check (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:72:23)
    at C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:83:27 Error: request canceled by user
    at Promise.promise.abort (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\resource-loader.js:50:21)
    at RequestManager.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\resources\request-manager.js:25:21)
    at Window.close (C:\Development-Folder\RHMS\node_modules\jsdom\lib\jsdom\browser\Window.js:491:29)
    at C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:49
    at Array.forEach (<anonymous>)
    at cleanup (C:\Development-Folder\RHMS\node_modules\uncss\src\uncss.js:223:19) {
  isAbortError: true
}`

**package.json**
`{
  "name": "RHMS",
  "version": "1.0.0",
  "description": "",
  "main": "postcss.config.js",
  "scripts": {
    "dev": "parcel index.html",
    "prod": "parcel index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "autoprefixer": "^9.8.6",
    "jquery": "^3.5.1",
    "popper.js": "^1.16.1"
  },
  "devDependencies": {
    "cssnano-preset-advanced": "^4.0.7",
    "parcel-bundler": "^1.12.4",
    "postcss-modules": "^3.2.2",
    "postcss-uncss": "^0.17.0",
    "uncss": "^0.17.3"
  }
}
`

**Comment by mischnic** [comment]
https://github.com/uncss/postcss-uncss:

>  It works across multiple files

This is probably incompatible with Parcel because the referenced files don't exist when Parcel runs

**Comment by amarg26** [comment]
Is there any solution for this? or I have to ignore it?
