### ISSUE TITLE
Parcel2 on arm/pi

### ISSUE THREAD

**Issue by koellcode** [parcel-bundler/parcel#5167]
# 🐛 bug report

after succesful installing on arm i get a undefined symbol error in sourcemap.node

## 🎛 Configuration (.babelrc, package.json, cli command)

just demo

 cat package.json 
{
  "name": "parcel2-demo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {},
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  }
}

## 🤔 Expected Behavior

should build

## 😯 Current Behavior

doesn‘t build, fails with: 

$ parcel build ./src/index.html
internal/modules/cjs/loader.js:1127
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/thomas/git/parcel2-demo/node_modules/@parcel/source-map/build/Release/sourcemap.node: undefined symbol: _ZN4Napi7details31needs_objectwrap_destructor_fixE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at load (/home/thomas/git/parcel2-demo/node_modules/node-gyp-build/index.js:21:10)
    at Object.<anonymous> (/home/thomas/git/parcel2-demo/node_modules/@parcel/source-map/dist/node.js:14:43)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
error Command failed with exit code 1.

## 🔦 Context

i run code-server on a raspi4 and try some PoCs there sometimes, this time i wanted to try out parcel2
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 beta 1
| Node             | 14.11.0
| npm/Yarn         | yarn 1.22.5
| Operating System | Arch Linux ARM

**Comment by mischnic** [comment]
Looks more like a Node bug, not sure if we can do anything about that

**Comment by koellcode** [comment]
thx for the quick response :) fyi, i‘ve tried it now with nodejs 12.x and 13.x . Same issue there :/ this indeed does not eliminate the assumption thats a node bug. 


greetings thomas

**Comment by mischnic** [comment]
The code in `node-addon-api` using `needs_objectwrap_destructor_fix` exists only their version `node-addon-api@2.X.X`, not in version 3 which is what we're using in the sourcemap library.

https://github.com/nodejs/node-addon-api/blob/2.0.2/napi-inl.h#L23
