### ISSUE TITLE
@parcel/packager-css: Asset has no content

### ISSUE THREAD

**Issue by LandonSchropp** [parcel-bundler/parcel#5168]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm using the basic out-of-the-box configuration for Parcel 2. I'm not doing anything special for Sass compilation. Here's the command I used to run the Parcel server.

``` bash
parcel serve --dist-dir build ./source/index.html
```

Here's my `.babelrc`:

``` json
{
  "presets": [ "@babel/env" ]
}
```

And here's my `package.json`:

```
{
  "name": "habits",
  "description": "A habit-tracking progressive web app",
  "repository": "https://github.com/LandonSchropp/habits",
  "author": "Landon Schropp <schroppl@gmail.com> (https://landonschropp.com)",
  "license": "UNLICENSED",
  "dependencies": {
    "@babel/cli": "^7.11.6",
    "@babel/core": "^7.11.6",
    "@babel/node": "^7.10.5",
    "@babel/preset-env": "^7.11.5",
    "@babel/register": "^7.11.5",
    "@parcel/transformer-css": "^2.0.0-alpha.3",
    "@parcel/transformer-postcss": "^2.0.0-alpha.3",
    "parcel": "^2.0.0-beta.1",
    "sass": "^1.26.11"
  },
  "scripts": {
    "lint": "eslint --max-warnings=0 .",
    "build": "parcel build --dist-dir build ./source/index.html",
    "serve": "parcel serve --dist-dir build ./source/index.html"
  },
  "devDependencies": {
    "babel-eslint": "^10.1.0",
    "eslint": "^7.9.0",
    "eslint-config-optimum-energy": "^0.7.0",
    "import-js": "^4.0.2",
    "javascript-typescript-langserver": "^2.11.3"
  }
}
```

## 🤔 Expected Behavior

This should compile my Sass file without any issues.

## 😯 Current Behavior

The app fails to compile with the following error:

```
@parcel/packager-css: Asset has no content
Error: Asset has no content
    at CommittedAsset.getContent (/Users/landon/Development/personal/habits/node_modules/@parcel/core/lib/CommittedAsset.js:59:15)
    at CommittedAsset.getCode (/Users/landon/Development/personal/habits/node_modules/@parcel/core/lib/CommittedAsset.js:67:30)
    at Asset.getCode (/Users/landon/Development/personal/habits/node_modules/@parcel/core/lib/public/Asset.js:145:48)
    at /Users/landon/Development/personal/habits/node_modules/@parcel/packager-css/lib/CSSPackager.js:45:51
    at /Users/landon/Development/personal/habits/node_modules/@parcel/utils/lib/PromiseQueue.js:45:30
    at PromiseQueue._runFn (/Users/landon/Development/personal/habits/node_modules/@parcel/utils/lib/PromiseQueue.js:98:13)
    at PromiseQueue._next (/Users/landon/Development/personal/habits/node_modules/@parcel/utils/lib/PromiseQueue.js:85:16)
    at PromiseQueue.run (/Users/landon/Development/personal/habits/node_modules/@parcel/utils/lib/PromiseQueue.js:76:12)
    at Object.package (/Users/landon/Development/personal/habits/node_modules/@parcel/packager-css/lib/CSSPackager.js:54:31)
    at PackagerRunner.package (/Users/landon/Development/personal/habits/node_modules/@parcel/core/lib/PackagerRunner.js:201:36)
console: (node:30469) UnhandledPromiseRejectionWarning: Error: Asset has no content
    at CommittedAsset.getContent (/Users/landon/Development/personal/habits/node_modules/@parcel/core/lib/CommittedAsset.js:59:15)
    at CommittedAsset.getCode (/Users/landon/Development/personal/habits/node_modules/@parcel/core/lib/CommittedAsset.js:67:30)
    at Asset.getCode (/Users/landon/Development/personal/habits/node_modules/@parcel/core/lib/public/Asset.js:145:48)
    at /Users/landon/Development/personal/habits/node_modules/@parcel/packager-css/lib/CSSPackager.js:45:51
    at /Users/landon/Development/personal/habits/node_modules/@parcel/utils/lib/PromiseQueue.js:45:30
    at PromiseQueue._runFn (/Users/landon/Development/personal/habits/node_modules/@parcel/utils/lib/PromiseQueue.js:98:13)
    at PromiseQueue._next (/Users/landon/Development/personal/habits/node_modules/@parcel/utils/lib/PromiseQueue.js:85:16)
    at PromiseQueue.run (/Users/landon/Development/personal/habits/node_modules/@parcel/utils/lib/PromiseQueue.js:76:12)
    at Object.package (/Users/landon/Development/personal/habits/node_modules/@parcel/packager-css/lib/CSSPackager.js:54:31)
    at PackagerRunner.package (/Users/landon/Development/personal/habits/node_modules/@parcel/core/lib/PackagerRunner.js:201:36)
console: (node:30469) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
```

## 💁 Possible Solution

Sorry, I'm not familiar enough with Parcel's codebase to suggest anything here.

## 🔦 Context

I was setting up the skeleton so I could build a simple PWA. Nothing special.

## 💻 Code Sample

Here's the repo that has the error: https://github.com/LandonSchropp/parcel-error-example.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1 |
| Node             | 14.4.0 |
| npm/Yarn         | 1.22.4 |
| Operating System | macOS 10.15.5 |

Thanks!

**Comment by mischnic** [comment]
I cloned your repo, ran `yarn` and `yarn build`. No errors.

Is it possible that you're versions are mismatched here?

```
    "@parcel/transformer-css": "^2.0.0-alpha.3",
    "@parcel/transformer-postcss": "^2.0.0-alpha.3",
    "import-js": "^4.0.2",
    "parcel": "^2.0.0-beta.1",
```

You also don't need to install anything besides `parcel` unless you're using a `.parcelrc` to configure the plugins.

**Comment by LandonSchropp** [comment]
@mischnic I've recloned my example repo, and now I'm not seeing any problems either. Maybe I somehow got my machine into a bad state.

Thanks for taking a look! I'll reopen this if I'm able to repro again.
