### ISSUE TITLE
Got unexpected undefined: RequestGraph.invalidateUnpredictableNodes 

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5191]
I get this error too. The issue is solved when I remove the .parcel-cache. 

It happens quite randomly, and when I try to run build again.

```
❯ npm run build

> github@0.35.0 build C:\Users\aminy\Documents\GitHub\JavaScript\@atom\github
> cross-env NODE_ENV=production parcel build --target main lib/index.js

Error: Got unexpected undefined
    at nullthrows (C:\Users\aminy\Documents\GitHub\JavaScript\@atom\github\node_modules\nullthrows\nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (C:\Users\aminy\Documents\GitHub\JavaScript\@atom\github\node_modules\@parcel\core\lib\Req
uestTracker.js:195:44)
    at AssetGraphBuilder.init (C:\Users\aminy\Documents\GitHub\JavaScript\@atom\github\node_modules\@parcel\core\lib\AssetGraphBuilder.js:2
65:25)
    at async Promise.all (index 0)
    at async Parcel.init (C:\Users\aminy\Documents\GitHub\JavaScript\@atom\github\node_modules\@parcel\core\lib\Parcel.js:414:5)
    at async Parcel.run (C:\Users\aminy\Documents\GitHub\JavaScript\@atom\github\node_modules\@parcel\core\lib\Parcel.js:456:7)
    at async Command.run (C:\Users\aminy\Documents\GitHub\JavaScript\@atom\github\node_modules\parcel\lib\cli.js:351:7) {
  framesToPop: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! github@0.35.0 build: `cross-env NODE_ENV=production parcel build --target main lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the github@0.35.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aminy\AppData\Roaming\npm-cache\_logs\2020-09-26T20_29_58_747Z-debug.log



```

_Originally posted by @aminya in https://github.com/parcel-bundler/parcel/issues/5181#issuecomment-699545837_

> You can reproduce mine here: https://github.com/aminya/github/tree/parcel-bug-report
> Run `npm run build` a couple of times!

**Comment by mischnic** [comment]
> Run npm run build a couple of times!

I still don't get it after running it 10 times...

**Comment by aminya** [comment]
@mischnic Let me see if I can make a new reproduction!

**Comment by aminya** [comment]
I can't reproduce this anymore 🙄🤨

**Comment by ittaibaratz** [comment]
@mischnic we are running into this too with nightly 598...
```
Error: Got unexpected undefined
    at nullthrows (/Users/ittai/Documents/GitHub/unified-shell/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/Users/ittai/Documents/GitHub/unified-shell/node_modules/@parcel/core/lib/RequestTracker.js:245:44)
    at loadRequestGraph (/Users/ittai/Documents/GitHub/unified-shell/node_modules/@parcel/core/lib/RequestTracker.js:803:18)
    at async Function.init (/Users/ittai/Documents/GitHub/unified-shell/node_modules/@parcel/core/lib/RequestTracker.js:764:17)
    at async Parcel._init (/Users/ittai/Documents/GitHub/unified-shell/node_modules/@parcel/core/lib/Parcel.js:440:50)
    at async Parcel.run (/Users/ittai/Documents/GitHub/unified-shell/node_modules/@parcel/core/lib/Parcel.js:477:7)
    at async run (/Users/ittai/Documents/GitHub/unified-shell/node_modules/parcel/lib/cli.js:373:7) {

```

**Comment by mischnic** [comment]
Does removing the `.parcel-cache` folder fix it? My theory is that this was caused by a change in the cache format between Parcel versions

**Comment by ittaibaratz** [comment]
> Does removing the `.parcel-cache` folder fix it? My theory is that this was caused by a change in the cache format between Parcel versions

Yep! Thanks again.

**Comment by benlhy** [comment]
Removing the .parcel-cache folder fixes this issue until the cache folder is generated again.

I think it might have to do with having both the postcss.config.js file and the tailwind.config.js file. Removing the postcss.config.js file + the .parcel-cache folder fixes this issue, and after that, I have no problems when the cache folder is generated again.
