### ISSUE TITLE
[Error]Got unexpected undefined, nullthrows, RequestGraph.invalidateUnpredictableNodes, AssetGraphBuilder.ini

### ISSUE THREAD

**Issue by skqksh** [parcel-bundler/parcel#5196]
I was just coding without any problem, but suddenly react site broke with this error.

I now this kind of error already was before.

but I couldn't find any solutions

```
PS D:\sourcecode\bylink-react-web> npm start

> blue-resume@0.1.0 start D:\sourcecode\bylink-react-web
> parcel index.html

{ Error: Got unexpected undefined
    at nullthrows (D:\sourcecode\bylink-react-web\node_modules\nullthrows\nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (D:\sourcecode\bylink-react-web\node_modules\@parcel\core\lib\RequestTracker.js:153:42) 
    at AssetGraphBuilder.init (D:\sourcecode\bylink-react-web\node_modules\@parcel\core\lib\AssetGraphBuilder.js:170:25) framesToPop: 1 }
```

package.json
```
{
  "name": "blue-resume",
  "version": "0.1.0",
  "description": "",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html",
    "typecheck": "tsc --noEmit",
    "typewatch": "tsc --noEmit --watch",
    "lint": "eslint --fix src/**/*.{js,jsx,ts,tsx}"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,jsx,ts,tsx}": "eslint"
  },
  "license": "MIT",
  "dependencies": {
    "@types/styled-components": "^5.1.3",
    "bootstrap": "^4.5.2",
    "lodash": "^4.17.20",
    "react": "^16.13.1",
    "react-bootstrap": "^1.3.0",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "styled-components": "^5.2.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.10.5",
    "@babel/preset-typescript": "^7.10.4",
    "@types/react": "^16.9.34",
    "@types/react-dom": "^16.9.7",
    "@types/react-router-dom": "^5.1.5",
    "@typescript-eslint/eslint-plugin": "^4.2.0",
    "@typescript-eslint/parser": "^4.2.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-preset-nano-react-app": "^0.1.0",
    "eslint": "^7.10.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.12.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.21.2",
    "eslint-plugin-react-hooks": "^4.1.2",
    "husky": "^4.3.0",
    "lint-staged": "^10.4.0",
    "parcel": "^2.0.0-beta.1",
    "prettier": "^2.1.2",
    "typescript": "^4.0.3"
  }
}
```

babel.config.js
```
module.exports = function (api) {
  const presets = [
    '@babel/preset-typescript',
    'babel-preset-nano-react-app',
  ]

  const moduleResolver = [
    'module-resolver',
    {
      root: '.',
      alias: {
        '@constants': './src/constants',
        '@components': './src/components',
      },
    },
  ]

  const plugins = [moduleResolver]

  const envDevelopment = {
    presets,
    plugins: [
      ['@babel/plugin-proposal-decorators', { legacy: true }],
      '@babel/transform-react-jsx-source',
      moduleResolver,
    ],
  }

  if (api.env(['development', 'test'])) {
    return envDevelopment
  }

  return {
    presets,
    plugins,
  }
}
```

It's suddenly occurred.
I reinstalled nodue_modules with `npm i` but still don't work
node : v10.13.0
npm : v6.14.4
parcel: ^2.0.0-beta.1

**Comment by skqksh** [comment]
:(
I can run server with `parcel index.html --no-cache` but `parcel index.html`

**Comment by mischnic** [comment]
Is this a public project? Would help if I could reproduce this locally

**Comment by mischnic** [comment]
It's very likely that this happened because the Parcel cache format changed slightly between versions...
