### ISSUE TITLE
Vue.js 3.0 web cannot be built

### ISSUE THREAD

**Issue by krehak** [parcel-bundler/parcel#5209]
# 🐛 bug report

When I want to build my website with the latest Vue.js 3, I got an error with the package `vue-template-compiler` which expects Vue.js 2. Now I'm stuck at upgrading my website to the latest Vue.js because I can't build it.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// command
parcel dev/assets/vue/app.js --out-dir public_html/assets/dev/

// app.js
import { createApp } from 'vue';
import App from './App.vue';

createApp({
    components: { App }
}).mount('#app');

// App.vue
<script>
export default {
    data() {
        return {
            isMenuOpen: false,
        };
    },
    mounted() {
    },
};
</script>

```

## 🤔 Expected Behavior

Working

## 😯 Current Behavior

Not working

## 💁 Possible Solution

Get rid of the `vue-template-compiler` package or something, I don't know why it is required even though it doesn't support Vue.js 3

## 💻 Code Sample

This is what I get instantly after running a command:
```
Server running at http://localhost:1234 
⠙ Building app.js...Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
🚨  /Applications/MAMP/htdocs-personal/starterkit-laravel-8/dev/assets/vue/App.vue: 

Vue packages version mismatch:

- vue@3.0.0 (/Applications/MAMP/htdocs-personal/starterkit-laravel-8/node_modules/vue/index.js)
- vue-template-compiler@2.6.12 (/Applications/MAMP/htdocs-personal/starterkit-laravel-8/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Applications/MAMP/htdocs-personal/starterkit-laravel-8/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (/usr/local/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (/usr/local/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at localRequire (/usr/local/lib/node_modules/parcel-bundler/src/utils/localRequire.js:11:10)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 11.15.0
| npm/Yarn         | 6.7.0
| Operating System | macOS Catalina (10.15.6)

**Comment by mischnic** [comment]
Parcel 2 should support Vue 3....

**Comment by krehak** [comment]
Thanks, I didn't know about Parcel 2. Anyway, I'm getting this error instead:
```
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
Error: No transformers found for "/Applications/MAMP/htdocs-personal/starterkit-laravel-8/dev/assets/vue/App.vue".
Error: No transformers found for "/Applications/MAMP/htdocs-personal/starterkit-laravel-8/dev/assets/vue/App.vue".
    at ParcelConfig._getTransformerNodes (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/ParcelConfig.js:157:13)
    at ParcelConfig.getTransformerNames (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/ParcelConfig.js:164:29)
    at ConfigLoader.loadParcelConfig (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/ConfigLoader.js:82:37)
    at Promise.resolve.then (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/ConfigLoader.js:54:48)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by krehak** [comment]
Nevermind, I managed it to work, I just had to remove the parcel package from global installation and install parcel@next in the local project.
