### ISSUE TITLE
API error: "TypeError: Path must be a string."

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#5241]
# 🐛 bug report

`^2.0.0-nightly.425`

When trying to use Parcel's API, an error is thrown: 

```asm
TypeError: Path must be a string.
    at resolve (/home/codespace/workspace/EPK/node_modules/resolve/lib/async.js:55:19)
    at /home/codespace/workspace/EPK/node_modules/@parcel/utils/lib/promisify.js:6:13
    at new Promise (<anonymous>)
    at /home/codespace/workspace/EPK/node_modules/@parcel/utils/lib/promisify.js:5:12
    at resolveAsync (/home/codespace/workspace/EPK/node_modules/@parcel/utils/lib/resolve.js:56:10)
    at resolve (/home/codespace/workspace/EPK/node_modules/@parcel/utils/lib/resolve.js:67:19)
    at resolveParcelConfig (/home/codespace/workspace/EPK/node_modules/@parcel/core/lib/requests/ParcelConfigRequest.js:150:46)
    at async loadParcelConfig (/home/codespace/workspace/EPK/node_modules/@parcel/core/lib/requests/ParcelConfigRequest.js:132:22)
    at async Parcel.init (/home/codespace/workspace/EPK/node_modules/@parcel/core/lib/Parcel.js:393:9)
    at async Parcel.run (/home/codespace/workspace/EPK/node_modules/@parcel/core/lib/Parcel.js:456:7)
```

The code i'm using is the minimalist example from the [docs](https://v2.parceljs.org/features/parcel-api/)

```js
import path from 'path'
import Parcel from '@parcel/core'
import config from '@parcel/config-default'

const parcel = new Parcel({
  defaultEngines: {
    browsers: ["last 1 Chrome version"],
    node: "12",
  },
  defaultConfig: {
    ...config,
    filePath: require.resolve('@parcel/config-default')
  },
  entries: path.join(__dirname, '../tests/unit/index.ts')
})

parcel.run()
```

**Comment by mischnic** [comment]
You need to do

```js
const path = require("path");
const { default: Parcel } = require("@parcel/core");

const parcel = new Parcel({
	defaultEngines: {
		browsers: ["last 1 Chrome version"],
		node: "12",
	},
	defaultConfig: require.resolve("@parcel/config-default"),
	entries: path.join(__dirname, "test.ts"),
});

parcel.run();
```

Will be fixed very soon in the docs: https://github.com/parcel-bundler/website/pull/731
