### ISSUE TITLE
Riot JS plugin from previous parcel version doesn't work on version 2

### ISSUE THREAD

**Issue by dharmax** [parcel-bundler/parcel#5262]
# 🐛 bug report

Riot JS plugin from previous parcel version - @riotjs/parcel-plugin-riot doesn't work on parcel version 2. 

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
...
 "devDependencies": {
    "@riotjs/cli": "^4.0.3",
    "@riotjs/compiler": "^4.11.0",
    "@riotjs/hot-reload": "^4.0.1",
    "@riotjs/parcel-plugin-riot": "^4.0.1",
....
}
...
```

## 🤔 Expected Behavior
should build all, including *.riot files.

## 😯 Current Behavior

It shoots the error "Error: No transformers found for " - for the .riot files

rror: No transformers found for "/home/dharmax/work/WebstormProjects/temp/whisperation2/fe/components/generic/reset-password.riot".
Error: No transformers found for "/home/dharmax/work/WebstormProjects/temp/whisperation2/fe/components/generic/reset-password.riot".
    at ParcelConfig._getTransformerNodes (/usr/pnpm-global/4/node_modules/.pnpm/@parcel/core@2.0.0-beta.1_@parcel+core@2.0.0-beta.1/node_modules/@parcel/core/lib/ParcelConfig.js:157:13)
    at ParcelConfig.getTransformerNames (/usr/pnpm-global/4/node_modules/.pnpm/@parcel/core@2.0.0-beta.1_@parcel+core@2.0.0-beta.1/node_modules/@parcel/core/lib/ParcelConfig.js:164:29)
    at ConfigLoader.loadParcelConfig (/usr/pnpm-global/4/node_modules/.pnpm/@parcel/core@2.0.0-beta.1_@parcel+core@2.0.0-beta.1/node_modules/@parcel/core/lib/ConfigLoader.js:82:37)
    at /usr/pnpm-global/4/node_modules/.pnpm/@parcel/core@2.0.0-beta.1_@parcel+core@2.0.0-beta.1/node_modules/@parcel/core/lib/ConfigLoader.js:54:48
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PromiseQueue._runFn (/usr/pnpm-global/4/node_modules/.pnpm/@parcel/utils@2.0.0-beta.1/node_modules/@parcel/utils/lib/PromiseQueue.js:98:7)
    at async PromiseQueue._next (/usr/pnpm-global/4/node_modules/.pnpm/@parcel/utils@2.0.0-beta.1/node_modules/@parcel/utils/lib/PromiseQueue.js:85:5)
dh
## 💁 Possible Solution

?
## 🔦 Context
I was actually trying to do a workaround on a problem with parcel 1, with the browserlist, 
(" Unknown version 59 of op_mob") and see if it is solved in parcel 2.... and now my code just doesn't work.....

## 💻 Code Sample
N/A
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 14.11
| npm/Yarn         | npm  6.14.8
 Operating System | linux manjaro

**Comment by mischnic** [comment]
That plugin will have to be updated for Parcel 2. But it should be rather straightforward.
