### ISSUE TITLE
Parcel is broken on Node 1.12.4

### ISSUE THREAD

**Issue by john01dav** [parcel-bundler/parcel#5298]
[This](https://github.com/parcel-bundler/parcel/issues/2245) error seems to be happening again on newer parcel/node. I tried uninstalling and reinstalling, but I'm not comfortable with giving it permissions such as `--allow-root` and `--unsafe-perms` when these permissions are largely undocumented (it took several minutes to find *anything at all* on them, and I can't find anything that has enough detail as to what they do, and even so running something as root should probably be audited first, but I don't have time to do this right now).

Versions:
```
$ npm --version        
6.14.8
$ parcel --version                    
1.12.4
$ uname -r
5.9.1-arch1-1
```

Exact error:
```
$ npm run build       

> @ build <censored>
> parcel build *.html --out-dir ../frontend

/usr/lib/node_modules/parcel-bundler/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/build/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/build/Debug/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/build/Release/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/out/Debug/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/Debug/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/out/Release/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/Release/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/build/default/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/compiled/15.0.1/linux/x64/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /usr/lib/node_modules/parcel-bundler/node_modules/deasync/lib/binding/node-v88-linux-x64/deasync.node
    at bindings (/usr/lib/node_modules/parcel-bundler/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/lib/node_modules/parcel-bundler/node_modules/deasync/index.js:30:31)
    at Module._compile (/usr/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (/usr/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/lib/node_modules/parcel-bundler/src/utils/syncPromise.js:1:79)
    at Module._compile (/usr/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:194:30) {
  tries: [
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/build/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/build/Debug/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/build/Release/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/out/Debug/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/Debug/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/out/Release/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/Release/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/build/default/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/compiled/15.0.1/linux/x64/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/addon-build/release/install-root/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/addon-build/debug/install-root/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/addon-build/default/install-root/deasync.node',
    '/usr/lib/node_modules/parcel-bundler/node_modules/deasync/lib/binding/node-v88-linux-x64/deasync.node'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `parcel build *.html --out-dir ../frontend`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <censored>
```

**Comment by john01dav** [comment]
I just realized that this is a duplicate of #5294, so I'll re-post my original issue report on that issue.
