### ISSUE TITLE
parallel invocations of parcel with cache sometimes works, sometimes hangs, sometimes produces bad output

### ISSUE THREAD

**Issue by muja** [parcel-bundler/parcel#5321]
# 🐛 bug report

Invoking parcel multiple times in parallel with cache enabled leads to some undefined behavior:

Sometimes it works.
Sometimes one of the invocations just hang (maybe deadlock?). Doing a `ps aux | grep parcel` kept showing the parcel process running. Only way to stop it was to kill it (or `Ctrl-C`).
Sometimes a bad output is produced. Since I'm using Parcel to bundle my Lambdas for CDK, most notable for me was the file [`default-sampling-rules.json`](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/resources/default_sampling_rules.json) in the package `aws-xray-sdk-core` being bundled to a completely empty file (instead of the expected `module.exports = JSON.parse("{\"default\":{\"fixed_target\":1,\"rate\":0.05},\"version\":2}");`.

## 🎛 Configuration (.babelrc, package.json, cli command)

CLI command used:

```bash
find src -name '*.lambda.ts' -or -name index.ts | xargs -n1 -P8 parcel build --target cdk-lambda --no-autoinstall --no-scope-hoist
```

package.json/targets
```js
{
  "cdk-lambda": {
    "context": "node",
    "includeNodeModules": {
      "aws-sdk": false
    },
    "sourceMap": false,
    "minify": false,
    "engines": {
      "node": ">= 12"
    }
  }
}
```

## 🤔 Expected Behavior

Expecting working output

## 😯 Current Behavior

As I said, sometimes works, sometimes hangs, sometimes wrong output. Oh, and one time the cache seemed to be completely broken, which led to consecutive invocations to fail completely, here is the stacktrace:

```
@parcel/packager-js: Asset has no content
Error: Asset has no content
    at CommittedAsset.getContent (/Users/danyel/workspace/sde/node_modules/@parcel/core/lib/CommittedAsset.js:59:15)
    at CommittedAsset.getCode (/Users/danyel/workspace/sde/node_modules/@parcel/core/lib/CommittedAsset.js:67:30)
    at Asset.getCode (/Users/danyel/workspace/sde/node_modules/@parcel/core/lib/public/Asset.js:145:48)
    at /Users/danyel/workspace/sde/node_modules/@parcel/packager-js/lib/JSPackager.js:104:65
    at /Users/danyel/workspace/sde/node_modules/@parcel/utils/lib/PromiseQueue.js:45:30
    at PromiseQueue._runFn (/Users/danyel/workspace/sde/node_modules/@parcel/utils/lib/PromiseQueue.js:98:13)
    at PromiseQueue._next (/Users/danyel/workspace/sde/node_modules/@parcel/utils/lib/PromiseQueue.js:85:16)
    at PromiseQueue.run (/Users/danyel/workspace/sde/node_modules/@parcel/utils/lib/PromiseQueue.js:76:12)
    at Object.package (/Users/danyel/workspace/sde/node_modules/@parcel/packager-js/lib/JSPackager.js:112:31)
    at PackagerRunner.package (/Users/danyel/workspace/sde/node_modules/@parcel/core/lib/PackagerRunner.js:201:36)
console: (node:23153) UnhandledPromiseRejectionWarning: Error: Asset has no content
    at CommittedAsset.getContent (/Users/danyel/workspace/sde/node_modules/@parcel/core/lib/CommittedAsset.js:59:15)
    at CommittedAsset.getCode (/Users/danyel/workspace/sde/node_modules/@parcel/core/lib/CommittedAsset.js:67:30)
    at Asset.getCode (/Users/danyel/workspace/sde/node_modules/@parcel/core/lib/public/Asset.js:145:48)
    at /Users/danyel/workspace/sde/node_modules/@parcel/packager-js/lib/JSPackager.js:104:65
    at /Users/danyel/workspace/sde/node_modules/@parcel/utils/lib/PromiseQueue.js:45:30
    at PromiseQueue._runFn (/Users/danyel/workspace/sde/node_modules/@parcel/utils/lib/PromiseQueue.js:98:13)
    at PromiseQueue._next (/Users/danyel/workspace/sde/node_modules/@parcel/utils/lib/PromiseQueue.js:85:16)
    at PromiseQueue.run (/Users/danyel/workspace/sde/node_modules/@parcel/utils/lib/PromiseQueue.js:76:12)
    at Object.package (/Users/danyel/workspace/sde/node_modules/@parcel/packager-js/lib/JSPackager.js:112:31)
    at PackagerRunner.package (/Users/danyel/workspace/sde/node_modules/@parcel/core/lib/PackagerRunner.js:201:36)
(Use `node --trace-warnings ...` to show where the warning was created)
```
## 💁 Possible Solution

Disabling cache (--no-cache) solves it, but is significantly slower. Also it took me a lot of hours debugging to figure out that the issue was in the cache...

## 🔦 Context

CDK, per default, runs the parcel process synchronously and one-by-one. For our project that has a lot of lambdas, the build takes a ton of time, both of the developer and the CI. Our solution to parallelize parcel works fine, but doing it with cache enabled breaks the build more often than not.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 14.7.0
| npm/Yarn         | yarn 1.22.4
| Operating System | OS X 10.15.7

**Comment by mischnic** [comment]
This should ideally work. But the recommended way is to pass multiple entries `parcel`, which should work in your case:
```
find src -name '*.lambda.ts' -or -name index.ts | xargs parcel build --target cdk-lambda --no-autoinstall --no-scope-hoist
```

**Comment by muja** [comment]
Unfortunately, it doesn't work and I'm not sure if I can provide any more infos. I would love to :)
The CI server has the same issue so I can assure it's not a works-not-on-machine issue.

**Comment by mischnic** [comment]
> Unfortunately, it doesn't work and I'm not sure if I can provide any more infos.

What do you mean? The problem with `xargs -n1 -P8` is probably that the multiple Parcel invocations overwrite each others cache entries, that shouldn't happen if you invoke it only once. Or is the problem that the build is successful but the output is not what you want?

**Comment by muja** [comment]
Oh, sorry, I overlooked the difference in your command. I didn't realize parcel accepted multiple parameters or that it would run it in parallel. Thank you! That really works for now!
