### ISSUE TITLE
`BrowserslistError: Unknown version 72 of opera` when importing `react-fontawesome`

### ISSUE THREAD

**Issue by papegoje** [parcel-bundler/parcel#5354]
# 🐛 bug report

```
× Build failed.
Error: Unknown version 72 of opera
BrowserslistError: Unknown version 72 of opera
    at Function.select (C:\website\node_modules\browserslist\index.js:1101:17)
    at C:\website\node_modules\browserslist\index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (C:\website\node_modules\browserslist\index.js:318:18)
    at browserslist (C:\website\node_modules\browserslist\index.js:443:21)
    at getTargets (C:\website\node_modules\@babel\helper-compilation-targets\lib\index.js:204:48)
    at C:\website\node_modules\@babel\preset-env\lib\index.js:258:57
    at getNeededPlugins (C:\website\node_modules\@parcel\transformer-babel\lib\env.js:71:35)
    at shouldCompileFurther (C:\website\node_modules\@parcel\transformer-babel\lib\env.js:79:31)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
package.json

  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-brands-svg-icons": "^5.15.1",
    "@fortawesome/free-regular-svg-icons": "^5.15.1",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@fortawesome/react-fontawesome": "^0.1.12",
    "@fullcalendar/core": "^5.4.0",
    "@fullcalendar/daygrid": "^5.4.0",
    "@fullcalendar/react": "^5.4.0",
    "@kiu-online.jp/www": "1.0.0",
    "animate.css": "^4.1.1",
    "classnames": "^2.2.6",
    "focus-visible": "^5.2.0",
    "fontsource-montserrat": "^3.0.9",
    "fontsource-noto-sans-jp": "^3.0.10",
    "fontsource-open-sans": "^3.0.9",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-spring": "^8.0.27",
    "react-use": "^15.3.4",
    "tippy.js": "^6.2.7"
  },
  "devDependencies": {
    "autoprefixer": "^10.0.2",
    "parcel": "^2.0.0-nightly.447",
    "postcss": "^8.1.7",
    "postcss-modules": "^3.2.2",
    "postcss-nested": "^5.0.1",
    "prettier": "^2.1.2",
    "tailwindcss": "^1.9.6"
  }
```

## 🤔 Expected Behavior

Parcel to build

## 😯 Current Behavior

Not building and return `BrowserslistError`

## 💁 Possible Solution

#5164 #5320 

Tried all mentioned solutions but none worked.

## 🔦 Context

I do not know whether this is a Parcel bug or something else.

## 💻 Code Sample

```js
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.447 |
| Node             | 14.15.0 |
| npm/Yarn         | yarn  |
| Operating System | Windows 10 19042.630 |

**Comment by mischnic** [comment]
Please provide a full reproduction (package.json, lockfile. 

Works for me with 
```
{
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/react-fontawesome": "^0.1.12",
    "react": "^17.0.1"
  }
}
```

**Comment by mischnic** [comment]
Please provide a full reproduction (e.g also a lockfile...) in a Github repo.

Works for me with your package.json and 
```js
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
console.log(FontAwesomeIcon)
```

**Comment by papegoje** [comment]
> Please provide a full reproduction (e.g also a lockfile...) in a Github repo.
> 
> Works for me with your package.json and
> 
> ```js
> import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
> console.log(FontAwesomeIcon)
> ```

Thank you! I totally removed the node_modules and yarn.lock files, and now it worked.

Sorry to have opened this issue.
