### ISSUE TITLE
AssetGraph: assert fails .type is 'asset' instead of 'asset_group'

### ISSUE THREAD

**Issue by EmielM** [parcel-bundler/parcel#5404]
# 🐛 bug report

When building/watching, I often get this crash 

```
🚨 Build failed.
Error: The expression evaluated to a falsy value:

  (0, assert().default)(n.type === 'asset_group')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(n.type === 'asset_group')

    at AssetGraph.removeNode (node_modules/@parcel/core/lib/AssetGraph.js:214:31)
    at AssetGraph.removeEdge (node_modules/@parcel/core/lib/Graph.js:248:12)
    at AssetGraph.removeNode (node_modules/@parcel/core/lib/Graph.js:212:14)
    at AssetGraph.removeNode (node_modules/@parcel/core/lib/AssetGraph.js:219:18)
    at AssetGraph.removeEdge (node_modules/@parcel/core/lib/Graph.js:248:12)
    at AssetGraph.removeNode (node_modules/@parcel/core/lib/Graph.js:212:14)
    at AssetGraph.removeNode (node_modules/@parcel/core/lib/AssetGraph.js:219:18)
    at AssetGraph.removeEdge (node_modules/@parcel/core/lib/Graph.js:248:12)
```
(when inspecting the .type, we see it's a `asset` instead of `asset_group`).

It probably has something to do with my custom transformer: it makes 1x/2x/3x assets for `require('asset:/myFile.png?size=100x100')` by exposing these as extra parts in the transform step:

```js
async transform({asset, config, options}) {
    if (!asset.query.size) {
        // probably the variant!
        asset.isIsolated = true;
        return [asset];
    }
    
    let code = 'module.exports = {\n';
    const parts = [];
    // ...
    for (variant of ["3x","2x","1x"]) {
        const result = await imagePipeline.clone().toBuffer();
        const uniqueKey = asset.id+'@'+variant;
        asset.addDependency({
            moduleSpecifier: uniqueKey,
        });
        parts.push({
             type: 'png',
             pipeline: 'asset', // ??
             uniqueKey,
             content: result,
             isIsolated: true,
         });
        code += JSON.stringify(variant) + ": require(" + JSON.stringify(uniqueKey) + "),\n";
    });
    code += '}';
    asset.type = 'js';
    asset.setCode(code);
    return [asset, ...parts];
}
```

Note: re-inserting the parts into the same asset: "pipeline" feels rather clunky (might be the source if the issue?), but if I don't do it I get:
```
No transformers found for assets/myImage.png.
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
const parcel = new Parcel({
    entries: "index.html",
    distDir: 'built/',
    config: require.resolve("./.parcelrc"),
    mode: "development",
    contentHash: true,
});

await parcel.watch((e) => {
    console.log("built! ", e);
})
```

```
{
    "extends": "@parcel/config-default",
    "transformers": {
        "asset:*": ["parcel-transformer-my-asset"]
    }
}
```

Also, using `PARCEL_WORKER_BACKEND=process` env.

## 💻 Code Sample

I can try to extract the crash case on request, but it's quite some work!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-nightly.462
| Node             | node-v14.15.1-linux-x64
| npm/Yarn         | yarn 1.22.4
| Operating System | linux

**Comment by mischnic** [comment]
An example (some modifications from your snippet): https://github.com/mischnic/parcel-issue-5404/blob/master/transformer/index.js


This seems to fix it an error I get with my example, but I'm not quite sure if this is the right approach:
```diff
diff --git packages/core/core/src/Transformation.js packages/core/core/src/Transformation.js
index fdf493d9..5ce33a73 100644
--- packages/core/core/src/Transformation.js
+++ packages/core/core/src/Transformation.js
@@ -282,7 +282,7 @@ export default class Transformation {
           filePath: initialAsset.value.filePath,
           isSource: asset.value.isSource,
           newType: asset.value.type,
-          newPipeline: asset.value.pipeline,
+          newPipeline: undefined,
           currentPipeline: pipeline,
         });
       }
```
But some existing tests fail: `image.js`,  `ts-types.js`

**Comment by mischnic** [comment]
Workaround:
```diff
diff --git transformer/index.js transformer/index.js
index 64f8eb8..e3fd16a 100644
--- transformer/index.js
+++ transformer/index.js
@@ -23,9 +23,12 @@ module.exports = new Transformer({
                 "),\n";
         }
         code += "}";
-        asset.type = "js";
-        asset.pipeline = undefined;
-        asset.setCode(code);
-        return [asset, ...assets];
+        return [
+            {
+                type: "js",
+                content: code,
+            },
+            ...assets,
+        ];
     },
 });
```

**Comment by EmielM** [comment]
Thanks for the quick reproduction. The workaround doesn't seem to work when "content" of the part actually changes (in my actual pipeline it is dependent on data that might change), eg when writing "asset.query.size" to the part-content and changing `require("/my.png?size=100")` to `require("/my.png?size=101")` still seems to break.

(I didn't test it yet with patched Transformation.js)

**Comment by Banou26** [comment]
I'm currently getting this error with a normal build without any custom transformers.

Any workarounds ?

`parcel build src/index.html`

```
× Build failed.
Error: The expression evaluated to a falsy value:

  (0, assert().default)(n.type === 'assetgroup')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(n.type === 'asset_group')

    at AssetGraph.removeNode (...app\node_modules\@parcel\core\lib\AssetGraph.js:214:31)
    at AssetGraph.removeEdge (...app\node_modules\@parcel\core\lib\Graph.js:248:12)
    at AssetGraph.removeNode (...app\node_modules\@parcel\core\lib\Graph.js:212:14)
    at AssetGraph.removeNode (...app\node_modules\@parcel\core\lib\AssetGraph.js:219:18)
    at AssetGraph.removeEdge (...app\node_modules\@parcel\core\lib\Graph.js:248:12)
    at AssetGraph.removeNode (...app\node_modules\@parcel\core\lib\Graph.js:212:14)
    at AssetGraph.removeNode (...app\node_modules\@parcel\core\lib\AssetGraph.js:219:18)
    at AssetGraph.removeEdge (...app\node_modules\@parcel\core\lib\Graph.js:248:12)
    at AssetGraph.removeNode (...app\node_modules\@parcel\core\lib\Graph.js:212:14)
    at AssetGraph.removeNode (...app\node_modules\@parcel\core\lib\AssetGraph.js:219:18)
```

**Comment by mischnic** [comment]
This should have been fixed by https://github.com/parcel-bundler/parcel/pull/5522

**Comment by Banou26** [comment]
I edited the comment last night saying that upgrading to `2.0.0-nightly.540` fixed the problem.
So I think everything is all good?
