### ISSUE TITLE
[v2] 'exportDefaultFrom' isn't currently enabled when specifying browserslist

### ISSUE THREAD

**Issue by Dreamsorcerer** [parcel-bundler/parcel#5452]
With `package.json`:
```
{
  "name": "openlayers",
  "version": "1.0.0",
  "description": "",
  "main": "ol.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "parcel build index.js"
  },
  "browserslist": [
    "default"
  ],
  "targets": {
    "main": {
      "includeNodeModules": true,
      "outputFormat": "esmodule"
    }
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ol": "latest"
  },
  "devDependencies": {
    "parcel": "nightly"
  }
}
```

and `index.js`:
```
export {Feature, Map, View} from 'ol';
export TileLayer from 'ol/layer/Tile';
export VectorLayer from 'ol/layer/Vector';
export OSM from 'ol/source/OSM';
export {fromLonLat} from 'ol/proj';
export {Style, RegularShape, Fill, Stroke} from 'ol/style';
export {Vector} from 'ol/source';
export {Point} from 'ol/geom';
```

When I run `npm run build`, I get:
```
🚨 Build failed.
@parcel/transformer-babel: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (2:8):
SyntaxError: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (2:8):
    at Parser._raise (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:748:17)
    at Parser.raiseWithData (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:741:17)
    at Parser.expectPlugin (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:9106:18)
    at Parser.maybeParseExportDefaultSpecifier (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:12812:12)
    at Parser.parseExport (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:12764:29)
    at Parser.parseStatementContent (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:11782:27)
    at Parser.parseStatement (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:11676:17)
    at Parser.parseBlockOrModuleBlockBody (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:12258:25)
    at Parser.parseBlockBody (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:12244:10)
    at Parser.parseTopLevel (/home/ubuntu/hacking/teslaclub/maps/openlayers/node_modules/@babel/parser/lib/index.js:11607:10)
/home/ubuntu/hacking/teslaclub/maps/openlayers/index.js:2:7
  1 | export {Feature, Map, View} from 'ol';
> 2 | export TileLayer from 'ol/layer/Tile';
>   |       ^
  3 | export VectorLayer from 'ol/layer/Vector';
  4 | export OSM from 'ol/source/OSM';
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openlayers@1.0.0 build: `parcel build index.js`
npm ERR! Exit status 1
```

This seems to happen whenever the `browserslist` is specified (regardless of its value).

**Comment by mischnic** [comment]
Caused by this inconsistency:

https://github.com/parcel-bundler/parcel/blob/90a3f012ccada0e5f80d9aac0dda3e08f21053d1/packages/shared/babel-ast-utils/src/index.js#L38

https://github.com/parcel-bundler/parcel/blob/90a3f012ccada0e5f80d9aac0dda3e08f21053d1/packages/transformers/babel/src/babel7.js#L44

But even then, you still get an error in dev mode or with `--no-scope-hoist` because `@babel/plugin-transform-modules-commonjs` doesn't support this (because it *is* still only a JS proposal). Buthttps://github.com/parcel-bundler/parcel/pull/4366 might change that
