### ISSUE TITLE
🐛 Error on JSON import

### ISSUE THREAD

**Issue by scriptPilot** [parcel-bundler/parcel#547]
**Choose one:** 🐛 bug report

### 🤔 Expected Behavior

test.json is imported correctly

### 😯 Current Behavior

Error shown:
```
🚨  'super' keyword unexpected here
      return 'module.exports = ' + (yield super.load()) + ';';
                                          ^^^^^

SyntaxError: 'super' keyword unexpected here
    at NativeCompileCache._moduleCompile (/home/ubuntu/workspace/js-google-auth/example/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/home/ubuntu/workspace/js-google-auth/example/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/home/ubuntu/workspace/js-google-auth/example/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Parser.findParser (/home/ubuntu/workspace/js-google-auth/example/node_modules/parcel-bundler/lib/Parser.js:59:45)
    at Parser.getAsset (/home/ubuntu/workspace/js-google-
```
### 💁 Possible Solution
na

### 🔦 Context
na

### 💻 Code Sample

app.js
`import test from './test.json';`

test.json
```
{
  "foo": "bar"
}
```
### 🌍 Your Environment

```js
node v6.11.2
npm v3.10.10
parcel v1.4.1
```

**Comment by albinotonnina** [comment]
I'm not sure that's possible.
The import module imports JS modules as [stated in the documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)


There are a few ways to achieve what you want though, you can refer to this [answer on stackoverflow](https://stackoverflow.com/a/34946395/6850833)

In webpack is often used a loader (json-loader)

**Comment by albinotonnina** [comment]
I'm gonna close this bug. Feel free to reopen

**Comment by scriptPilot** [comment]
OK. Thank you for the quick response.
