### ISSUE TITLE
@parcel/optimizer-cssnano - Missed semicolon

### ISSUE THREAD

**Issue by AshotN** [parcel-bundler/parcel#5536]
# 🐛 bug report

Whenever I try to run `parcel build index.html --no-source-maps --no-scope-hoist` I get the following error

```
🚨 Build failed.
@parcel/optimizer-cssnano: <css input>:1567:14: Missed semicolon
CssSyntaxError: <css input>:1567:14: Missed semicolon
    at Input.error (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/node_modules/postcss/lib/input.js:130:16)
    at Parser.checkMissedSemicolon (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/node_modules/postcss/lib/parser.js:603:22)
    at Parser.decl (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/node_modules/postcss/lib/parser.js:286:46)
    at Parser.other (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/node_modules/postcss/lib/parser.js:133:18)
    at Parser.parse (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/node_modules/postcss/lib/parser.js:77:16)
    at parse (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/node_modules/postcss/lib/processor.js:117:23)
    at Object.optimize (/var/www/html/ampache.hego.co/client/node_modules/@parcel/optimizer-cssnano/lib/CSSNanoOptimizer.js:38:68)
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xa68bf0 node::Abort() [/usr/bin/node]
 2: 0x99bc4d node::FatalError(char const*, char const*) [/usr/bin/node]
 3: 0xc41f9a v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
 4: 0x9c139d node::UVException(v8::Isolate*, int, char const*, char const*, char const*, char const*) [/usr/bin/node]
 5: 0xa6f048 node::fs::FSReqAfterScope::Reject(uv_fs_s*) [/usr/bin/node]
 6: 0xa70319 node::fs::AfterStat(uv_fs_s*) [/usr/bin/node]
 7: 0x14479ed  [/usr/bin/node]
 8: 0x144bfe6  [/usr/bin/node]
 9: 0x145eac5  [/usr/bin/node]
10: 0x144c918 uv_run [/usr/bin/node]
11: 0x9bc025 node::SpinEventLoop(node::Environment*) [/usr/bin/node]
12: 0xb2d359 node::worker::Worker::Run() [/usr/bin/node]
13: 0xb2db68  [/usr/bin/node]
14: 0x7f283b113609  [/lib/x86_64-linux-gnu/libpthread.so.0]
15: 0x7f283b03a293 clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```

 🎛 Configuration (.babelrc, package.json, cli command)

.postcssrc
```{
  "modules": true,
  "plugins": {
    "postcss-modules": {
      "generateScopedName": "_[name]__[local]"
    }
  }
}
```

.parcelrc
```
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.png": ["@parcel/transformer-raw"],
		"*.svg": ["@parcel/transformer-raw"]
	}
}
```

.babelrc
```
{
    "presets": [
        "@babel/preset-typescript",
        "@babel/preset-env",
        "@babel/preset-react"
    ],
    "plugins": [
        "@babel/plugin-transform-runtime",
        "@babel/plugin-proposal-class-properties"
    ]
}
```

## 🔦 Context

Running `parcel index.html` works fine.

Commenting this bit of Stylus code seems to resolve the issue
```
    @keyframes fadeInFromNone
      0%
        display none
        opacity 0
      1%
        display block
        opacity 0
      100%
        display block
        opacity 1

    &:hover
      & > img
        filter invert(56%) sepia(96%) saturate(1211%) hue-rotate(0deg) brightness(103%) contrast(104%) //make orange
      & > .options
        display block
        opacity 1
        animation fadeInFromNone 0.15s easeOut
```
## 💻 Code Sample

https://github.com/ampache/ampache/tree/react-client

This is the entire project

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 15.5.0
| Yarn         | 1.19.1
| Operating System | Ubuntu 20.04.1 LTS x86_64

**Comment by AshotN** [comment]
Tried on `nightly` as well, same error

**Comment by mischnic** [comment]
This is caused by https://github.com/css-modules/postcss-modules/issues/83. You can probably work around this by using a different kind of syntax for the animation.

```js
let postcss = require("postcss");

let INPUT = `div {
  animation: run 0.15s easeOut;
}
@keyframes run {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}`;

postcss([require("postcss-modules")()])
	.process(INPUT, { from: undefined })
	.then((result) => {
		console.log(result.css);
	});
```

output (the `:local` is invalid):
```
div {
  animation: _run_1bm6h_1 0.15s :local(easeOut);
}
@keyframes _run_1bm6h_1 {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
```
