### ISSUE TITLE
Cannot get Parcel working with web3

### ISSUE THREAD

**Issue by rsaccon** [parcel-bundler/parcel#555]
🐛 bug report

I am porting a resonml app (which works perfectly with webpack) to parcel. Unfortunately requiring `web3` fails. If I comment that part of code out, all works well

### 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```js
{
  "name": "example",
  "private": true,
  "version": "0.1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel src/writer/index.html --no-cache",
    "build": "parcel build src/writer/index.html --public-url /",
    "clean": "rimraf .cache lib dist"
  },
  "dependencies": {
    ......
    ......
    ...... 
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "reason-react": "^0.3.1",
    "web3": "^1.0.0-beta.27"
  },
  "devDependencies": {
    "bs-platform": "^2.1.0",
    "bsb-js": "^1.0.2",
    "parcel-bundler": "^1.4.1",
    "rimraf": "^2.6.2"
  }
```
no .babelrc

cli command which produces the error: `yarn start`

### 🤔 Expected Behavior

the dev server should start normally

### 😯 Current Behavior

Error when starting dev server:
```
robertos-mbp:kelor-reason robertosaccon$ yarn start
yarn run v1.3.2
$ parcel src/writer/index.html --no-cache
Server running at http://localhost:1234
🚨  /Users/robertosaccon/kelor-reason/node_modules/swarm-js/lib/api-browser.js: Couldn't find preset "es2015" relative to directory "/Users/robertosaccon/kel
    at /Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.getParserOptions (/Users/robertosaccon/kelor-reason/node_modules/parcel-bundler/src/assets/JSAsset.js:60:20)
    at <anonymous>
```

(different) Error when building:
```
robertos-mbp:kelor-reason robertosaccon$ yarn build
yarn run v1.3.2
$ parcel build src/writer/index.html --public-url /
⏳  Building caml_builtin_exceptions.js...
Condition always false [0:8,6]
Dropping unreachable code [0:16,4]
Dropping side-effect-free statement [0:24,4]
Condition always true [0:28,4]
⏳  Building react-dom.development.js...
Dropping side-effect-free statement [0:249,32]
Dropping side-effect-free statement [0:253,30]
Dropping side-effect-free statement [0:285,16]
Dropping side-effect-free statement [0:393,18]
Dropping side-effect-free statement [0:397,16]
Dropping unreachable code [0:400,14]
Dropping side-effect-free statement [0:469,18]
Dropping side-effect-free statement [0:473,16]
Dropping unreachable code [0:476,14]
Dropping unreachable code [0:489,14]
Dropping side-effect-free statement [0:512,32]
Dropping side-effect-free statement [0:516,30]
Dropping side-effect-free statement [0:543,32]
Dropping side-effect-free statement [0:547,30]
Dropping side-effect-free statement [0:561,34]
⏳  Building PmSchema.bs.js...
⏳  Building caml_exceptions.js...
Dropping side-effect-free statement [0:420,2]
⏳  Building caml_obj.js...
Dropping side-effect-free statement [0:9,4]
Side effects in initialization of unused variable a4363 [0:43,6]
⏳  Building index.js...
⏳  Building ElementRe.js...
Dropping side-effect-free || [0:164,440]
Dropping side-effect-free || [0:164,499]
Dropping unused variable a6983 [0:544,10]
Dropping unused variable a6984 [0:554,10]
Dropping side-effect-free statement [0:406,8]
Side effects in initialization of unused variable a6963 [0:390,8]
⏳  Building caml_utils.js...
⏳  Building index.js...
⏳  Building browser.js...
⏳  Building index.js...
Dropping side-effect-free statement [0:113,6]
Dropping side-effect-free statement [0:118,6]
Dropping side-effect-free statement [0:23,18]
Dropping side-effect-free statement [0:30,18]
Dropping side-effect-free statement [0:31,18]
Dropping side-effect-free statement [0:35,16]
Dropping unreachable code [0:87,6]
Declarations in unreachable code! [0:87,6]
Dropping unreachable code [0:348,4]
Declarations in unreachable code! [0:348,4]
⏳  Building isTextNode.js...
🚨  /Users/robertosaccon/kelor-reason/node_modules/ethjs-unit/lib/index.js: Unknown plugin "transform-es2015-template-literals" specified in "/Users/robertos
    at /Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17or-reason/node_modules/ethjs-unit"
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/robertosaccon/kelor-reason/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.getParserOptions (/Users/robertosaccon/kelor-reason/node_modules/parcel-bundler/src/assets/JSAsset.js:60:20)
    at JSAsset.parse (/Users/robertosaccon/kelor-reason/node_modules/parcel-bundler/src/assets/JSAsset.js:68:32)
    at JSAsset.parseIfNeeded (/Users/robertosaccon/kelor-reason/node_modules/parcel-bundler/src/Asset.js:47:29)
Function.protoype.arguments not supported [0:35,4]
Function.protoype.arguments not supported [0:146,9]
Function.protoype.arguments not supported [0:147,8]
Function.protoype.arguments not supported [0:148,27]
Function.protoype.arguments not supported [0:155,27]
Dropping side-effect-free statement [0:2,0]
Dropping side-effect-free statement [0:20,8]
Dropping side-effect-free statement [0:23,8]
Dropping side-effect-free statement [0:34,8]
Dropping side-effect-free statement [0:37,8]
Dropping unreachable code [0:4896,6]
Dropping unreachable code [0:5552,4]
Declarations in unreachable code! [0:5552,4]
Condition left of && always true [0:5830,14]
Condition always false [0:4763,31]
Dropping unreachable code [0:8530,10]
Condition always true [0:8840,12]
Dropping side-effect-free || [0:8973,12]
Dropping side-effect-free statement [0:9729,8]
Condition always true [0:10050,12]
Condition left of && always true [0:10053,12]
Condition left of && always true [0:10125,16]
Condition left of && always true [0:10167,14]
Condition left of && always true [0:10209,12]
Condition left of && always true [0:10239,12]
Side effects in initialization of unused variable a2593 [0:9704,12]
Side effects in initialization of unused variable a2594 [0:9705,12]
Side effects in initialization of unused variable a2595 [0:9706,12]
Side effects in initialization of unused variable a2596 [0:9707,12]
Side effects in initialization of unused variable a2597 [0:9708,12]
Dropping side-effect-free statement [0:10527,14]
Dropping side-effect-free statement [0:10526,16]
Side effects in initialization of unused variable a2742 [0:10525,16]
Dropping unreachable code [0:5556,4]
Declarations in unreachable code! [0:5556,4]
Dropping side-effect-free statement [0:11502,10]
Dropping side-effect-free statement [0:11501,12]
Condition left of && always true [0:13774,16]
Condition left of && always true [0:14124,16]
Side effects in initialization of unused variable a3542 [0:14156,10]
Condition left of && always true [0:14293,18]
Condition left of && always true [0:14300,18]
Condition left of && always true [0:14308,16]
Dropping unreachable code [0:14908,8]
Dropping unreachable code [0:14917,8]
Declarations in unreachable code! [0:14917,8]
Dropping unreachable code [0:14918,8]
Condition left of && always true [0:15091,14]
Condition left of && always true [0:15105,14]
Condition left of && always true [0:15124,14]
Condition left of && always true [0:15129,14]
Condition always false [0:4757,27]
Dropping unreachable code [0:15319,6]
Dropping side-effect-free statement [0:15339,12]
Side effects in initialization of unused variable a1477 [0:5566,12]
Condition always false [0:12,4]
Dropping unreachable code [0:13,2]
Dropping side-effect-free statement [0:12,4]
Function.protoype.arguments not supported [0:402,15]
Function.protoype.arguments not supported [0:484,4]
Function.protoype.arguments not supported [0:484,24]
Function.protoype.arguments not supported [0:503,7]
Function.protoype.arguments not supported [0:696,4]
Dropping side-effect-free statement [0:25,0]
Condition always false [0:13,4]
Dropping unreachable code [0:14,2]
Dropping side-effect-free statement [0:63,8]
Condition always false [0:62,10]
Dropping unreachable code [0:62,41]
Condition always true [0:3,4]
Dropping unreachable code [0:6,2]
Node#moveTo was deprecated. Use Container#append.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
robertos-mbp:kelor-reason robertosaccon$
```

### 🔦 Context

the error happens in a JS file where I do:

```
var Web3 = require('web3');

// then some stuff using Web3
```

If I comment out the above, things work fine.

My webpack configuration of the previously perfectly working setup **only** contained entry and output.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 9.0.0
| Yarn         | 1.3.2
| Operating System | Mac OS X

**Comment by rsaccon** [comment]
Just checked similar issue https://github.com/parcel-bundler/parcel/issues/482

Looks like parcel is trying to transpile if it finds some .babelrc down in the dependencies, but cannot find the transpile plugin.

**Comment by albinotonnina** [comment]
@rsaccon I think that's exactly what is happening...

**Comment by DeMoorJasper** [comment]
related #13
