### ISSUE TITLE
Expected '}' instead of 'i' at line 12 column 1 of the JSON5 data. Still to read: "i}\n"

### ISSUE THREAD

**Issue by mhy-web** [parcel-bundler/parcel#556]
I have deleted all code in main.js, but the error doesn't disappear
```
➜  parcel-cli git:(master) ✗ parcel
Server running at http://localhost:1234 
🚨  /Users/member/learning/parcel-cli/main.js: Expected '}' instead of 'i' at line 12 column 1 of the JSON5 data. Still to read: "i}\n"
    at error (/usr/local/lib/node_modules/parcel-bundler/node_modules/json5/lib/json5.js:56:25)
    at next (/usr/local/lib/node_modules/parcel-bundler/node_modules/json5/lib/json5.js:72:17)
    at object (/usr/local/lib/node_modules/parcel-bundler/node_modules/json5/lib/json5.js:464:25)
    at value (/usr/local/lib/node_modules/parcel-bundler/node_modules/json5/lib/json5.js:482:20)
    at Object.parse (/usr/local/lib/node_modules/parcel-bundler/node_modules/json5/lib/json5.js:508:18)
    at Object.load (/usr/local/lib/node_modules/parcel-bundler/src/utils/config.js:40:20)
    at <anonymous>
```
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parcel-cli",
  "version": "1.0.0",
  "description": "parcel cli && react",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "parcel main.js",
    "build": "parcel build main.js --out-dir ./dist"
  },
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "styled-components": "^2.4.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "parcel-bundler": "^1.3.0"
  },
  "keywords": [
    "parcel",
    "cli",
    "react"
  ],
  "author": "",
  "license": "ISC"
}
```
### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   1.3.1
| Node             |   8.9.4
| npm/Yarn         |  npm 5.6.0
| Operating System | Mac OS 10.13.2

**Comment by DeMoorJasper** [comment]
It appears some of your JSON data is invalid

**Comment by funkjunky** [comment]
Somewhere? Shouldn't there be a more clear error message?

I'm currently having almost the exact same error. Except mine says NOTHING about a file at the beginning.
> Server running at http://localhost:1234 
> Expected '}' instead of EOF at line 17 column 1 of the JSON5 data. Still to read: ""

Every line points to either JSON5 or parcel-bundler. Shouldn't there be a clearer error message?
