### ISSUE TITLE
Yarn PnP: Cannot find parcel plugin ....

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5586]
# 🐛 bug report

After https://github.com/parcel-bundler/parcel/pull/5481 , `NodePackageManager` doesn't use the `resolve` package anymore (which uses PnP automatically) but instead reimplements part of `@parcel/node-resolver-core`. PnP support is missing: https://github.com/parcel-bundler/parcel/blob/3133b5d7282510f1faef29afbb1a441ad790c62d/packages/core/package-manager/src/NodeResolver.js#L8

Thanks to @arcanis for pinging.

**Comment by mischnic** [comment]
I started in https://github.com/parcel-bundler/parcel/tree/5586-load-plugin-pnp, but anytime PnP is used, we cannot use the Rust-based file searching.

**Comment by huw** [comment]
Ah I think I just reported this to Will also—I’m getting this error on the latest nightly with PnP (also in a monorepo).

![FDFA4A61-8931-4EEC-B14F-36F5816DDFD7](https://user-images.githubusercontent.com/2456132/103605086-02ac3c80-4f67-11eb-9837-2247791c4f11.jpeg)

**Comment by mischnic** [comment]
@huw Yeah, that's the same issue. You could revert to nightly.500 (if that's possible) for the time being.

**Comment by huw** [comment]
Hmm, I'm getting a different resolver issue on that version. Was working on `2.0.0-beta.1`:

```
🚨 Build failed.
@parcel/core: Failed to resolve '[SNIP]/packages/frontend/src/index.html' 
@parcel/resolver-default: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:122:11)
    at Object.parse (path.js:1283:5)
    at NodeResolver.findPackage ([SNIP]/.yarn/cache/@parcel-node-resolver-core-npm-2.0.0-beta.1-d53483c0df-fb7177eb08.zip/node_modules/@parcel/node-resolver-core/lib/NodeResolver.js:748:30)
    at NodeResolver.loadAlias ([SNIP]/.yarn/cache/@parcel-node-resolver-core-npm-2.0.0-beta.1-d53483c0df-fb7177eb08.zip/node_modules/@parcel/node-resolver-core/lib/NodeResolver.js:765:37)
    at NodeResolver.resolveModule ([SNIP]/.yarn/cache/@parcel-node-resolver-core-npm-2.0.0-beta.1-d53483c0df-fb7177eb08.zip/node_modules/@parcel/node-resolver-core/lib/NodeResolver.js:226:27)
    at NodeResolver.resolve ([SNIP]/.yarn/cache/@parcel-node-resolver-core-npm-2.0.0-beta.1-d53483c0df-fb7177eb08.zip/node_modules/@parcel/node-resolver-core/lib/NodeResolver.js:84:29)
    at Object.resolve ([SNIP]/.yarn/cache/@parcel-resolver-default-npm-2.0.0-beta.1-330da5a474-7e5697cd1c.zip/node_modules/@parcel/resolver-default/lib/DefaultResolver.js:42:21)
    at ResolverRunner.resolve ([SNIP]/.yarn/cache/@parcel-core-npm-2.0.0-nightly.500-49995356ba-c66d9d3dbe.zip/node_modules/@parcel/core/lib/requests/PathRequest.js:276:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run ([SNIP]/.yarn/cache/@parcel-core-npm-2.0.0-nightly.500-49995356ba-c66d9d3dbe.zip/node_modules/@parcel/core/lib/requests/PathRequest.js:160:20)
```

Did the API change recently?
