### ISSUE TITLE
fs-search does not build on Windows 32 bit

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5597]
# 🐛 bug report

You don't run the CI on Windows 32 bit and so no prebuilt binaries are available for that platform.

```


Error: Cannot find module './fs-search.win32-ia32-msvc.node'
Require stack:
- D:\a\zadeh\zadeh\node_modules\@parcel\fs-search\index.js
- D:\a\zadeh\zadeh\node_modules\@parcel\fs\lib\NodeFS.js
- D:\a\zadeh\zadeh\node_modules\@parcel\fs\lib\index.js
- D:\a\zadeh\zadeh\node_modules\parcel\lib\cli.js
- D:\a\zadeh\zadeh\node_modules\parcel\lib\bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (D:\a\zadeh\zadeh\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\a\zadeh\zadeh\node_modules\@parcel\fs-search\index.js:16:18)
    at Module._compile (D:\a\zadeh\zadeh\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\a\\zadeh\\zadeh\\node_modules\\@parcel\\fs-search\\index.js',
    'D:\\a\\zadeh\\zadeh\\node_modules\\@parcel\\fs\\lib\\NodeFS.js',
    'D:\\a\\zadeh\\zadeh\\node_modules\\@parcel\\fs\\lib\\index.js',
    'D:\\a\\zadeh\\zadeh\\node_modules\\parcel\\lib\\cli.js',
    'D:\\a\\zadeh\\zadeh\\node_modules\\parcel\\lib\\bin.js'
  ]
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
I'm curious why you need 32-bit windows support at this point? Intel hasn't offered 32-bit processors for PCs since ~2006 I believe, and Microsoft [dropped 32-bit windows support](https://www.bleepingcomputer.com/news/microsoft/rip-microsoft-to-drop-support-for-windows-10-on-32-bit-systems/) already. What hardware are you running this on? I'm not sure it's worth the maintenance, CI, and npm package size costs to support this.

**Comment by aminya** [comment]
10% of our users are on Windows 32 bit, and surprise, that is more than our Linux users. We can't just cut our user base because we want to have 10 percent faster builds.


![image](https://user-images.githubusercontent.com/16418197/103806290-693e6280-501a-11eb-95ee-ccde8256ca80.png)

**Comment by mischnic** [comment]
Alternatively, we could also fallback to the JS implementation if there's no prebuild.

**Comment by devongovett** [comment]
But seriously though, what hardware runs 32 bit windows these days? I'm kinda astonished!

**Comment by aminya** [comment]
Anyway, I have attached a PR to this issue in case you have not seen it. It requires you to trigger the run because I think I changed the CI files.

https://github.com/parcel-bundler/parcel/pull/5596

**Comment by devongovett** [comment]
That PR only affects the tests not the builds (which use GitHub Actions). Regardless, none of our native dependencies have ever supported win32 including the watcher and source maps packages, so I'm not sure why this is only a problem now.

**Comment by aminya** [comment]
> That PR only affects the tests not the builds (which use GitHub Actions)

Thanks for the mention. We can add the prebuild scripts required for 32bit builds to the ci.

> Regardless, none of our native dependencies have ever supported win32 including the watcher and source maps packages, so I'm not sure why this is only a problem now.

I added the 32bit support for the source-map myself.
https://github.com/parcel-bundler/source-map/pull/36

**Comment by lukoerfer** [comment]
**This may help future readers:**

I encountered the same error when migrating to Parcel v2, because Visual Studio used its own installation of Node to call Parcel which turned out to be 32-bit. Once I [configured](https://stackoverflow.com/questions/32603378/install-both-32-and-64-bit-bindings/32763587) Visual Studio to call Node from `PATH`, the problem was solved.

**Comment by aminya** [comment]
@lukoerfer Could you take a look at #5596? Applying your fix in the CI means that Parcel will prebuild it.

**Comment by lukoerfer** [comment]
My "fix" is not related to how Parcel is built or published. It just tells Visual Studio to call the 64-bit version of Node instead of its own 32-bit version.
