### ISSUE TITLE
Error: /lib64/libc.so.6: version `GLIBC_2.18' not found in Red Hat Enterprise Linux 7.9

### ISSUE THREAD

**Issue by guyk-yahoo** [parcel-bundler/parcel#5599]
# 🐛 bug report
With Parcel1 everything works.
After migrating to Parcel2 -- I'm getting the following error - running on Red Hat Enterprise Linux 7.9

From the looks of it - (running `/lib64/libc.so.6 --version`) this distro contains `GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.`
```
parcel build src/public/js/main.ts --target browser --no-scope-hoist
14:56:16 
14:56:16 Error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /......./node_modules/@parcel/fs-search/fs-search.linux-x64-gnu.node)
14:56:16     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
14:56:16     at Module.load (internal/modules/cjs/loader.js:928:32)
14:56:16     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
14:56:16     at Module.require (internal/modules/cjs/loader.js:952:19)
14:56:16     at require (/......./node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
14:56:16     at Object.<anonymous> (/......./node_modules/@parcel/fs-search/index.js:16:18)
14:56:16     at Module._compile (/......./node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
14:56:16     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
14:56:16     at Module.load (internal/modules/cjs/loader.js:928:32)
14:56:16     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
14:56:16 npm ERR! code ELIFECYCLE
14:56:16 npm ERR! errno 1
14:56:16 npm ERR! my_project@0.0.43-pr43.b22265458 parcel: `parcel build src/public/js/main.ts --target browser --no-scope-hoist`
14:56:16 npm ERR! Exit status 1
14:56:16 npm ERR! 
14:56:16 npm ERR! Failed at the my_project@0.0.43-pr43.b22265458 parcel script.
14:56:16 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
     "parcel": "parcel build src/public/js/main.ts --target browser --no-scope-hoist",
}
```

## 🤔 Expected Behavior
It runs on my Mac

## 😯 Current Behavior
It fails on the CI environment, running Red Hat Enterprise Linux 7.9

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.506
| Node             | v14.15.3
| npm/Yarn         | 6.14.10
| Operating System | Red Hat Enterprise Linux 7.9

**Comment by mischnic** [comment]
How we solved this the last time: https://github.com/parcel-bundler/watcher/issues/18#issuecomment-583877893

**Comment by guyk-yahoo** [comment]
I'm not sure I understand the solution.
Unfortunately, C++ is something I have yet learned.

**Comment by mischnic** [comment]
That is just a possible possible/hint for whoever wants to work on this

**Comment by ittaibaratz** [comment]
Also having this issue now when trying to upgrade from nightly 439 to 562. Any idea what is the latest nightly before this dependency was introduced?

**Comment by mischnic** [comment]
The last one should be `parcel@2.0.0-nightly.500`

What system are you on and which glibc version is installed?

**Comment by ittaibaratz** [comment]
> The last one should be `parcel@2.0.0-nightly.500`
> 
> What system are you on and which glibc version is installed?

We are on Centos 7 which follows RHEL 7 and I believe use glibc 2.17

**Comment by guyk-yahoo** [comment]
Can confirm it's fixed.
Thanks!

**Comment by ittaibaratz** [comment]
The issue is fixed, however with nightly 566 we are now getting a segmentation fault that seems related to glibc?

```
PID 28843 received SIGSEGV for address: 0x10
0   segfault-handler.node               0x0000000104ee1fe0 _ZL16segfault_handleriP9__siginfoPv + 304
1   libsystem_platform.dylib            0x00007fff7289a5fd _sigtramp + 29
2   ???                                 0x0000000000000013 0x0 + 19
3   node.napi.glibc.node                0x0000000109873dac _ZN16SourceMapBinding18findClosestMappingERKN4Napi12CallbackInfoE + 404
4   node.napi.glibc.node                0x0000000109875fa4 _ZN4Napi12InstanceWrapI16SourceMapBindingE29InstanceMethodCallbackWrapperEP10napi_env__P20napi_callback_info__ + 176
5   node.napi.glibc.node                0x0000000109875f1a _ZN4Napi12InstanceWrapI16SourceMapBindingE29InstanceMethodCallbackWrapperEP10napi_env__P20napi_callback_info__ + 38
6   node                                0x000000010007b82a _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE + 122
7   node                                0x00000001002a2718 _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE + 616
8   node                                0x00000001002a1cac _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE + 524
9   node                                0x00000001002a13b7 _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE + 263
10  node                                0x0000000100ac53b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
11  node                                0x0000000100a5e522 Builtins_InterpreterEntryTrampoline + 194
m
```
