### ISSUE TITLE
[parcel 2] builds for modern targets fail with: @parcel/packager-js: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#5637]
This issue already exists for parcel 1 (#4691) but opening a new one as instructed by @mischnic 

# 🐛 bug report

When building code containing optional chaining in the return of a function for the target "last 1 firefox version" or other modern browsers the build fails.

When building for the target "ie 11" the build succeeds but runs into #5627 on execution. So this is possibly related?

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file.

## 🤔 Expected Behavior

The code should bundle successfully.

## 😯 Current Behavior

An error occurs:
```
daniel@iMac:/tmp/a/pbr$ npm run build

> build
> parcel build src/main.ts --log-level verbose --detailed-report 100 --no-minify --target modern

🚨 Build failed.
@parcel/packager-js: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at ObjectExpression (/private/tmp/a/pbr/node_modules/astring/dist/astring.js:780:25)
    at Object.generator.<computed> [as ObjectExpression] (/private/tmp/a/pbr/node_modules/@parcel/babel-ast-utils/lib/generator.js:270:10)
    at Object.ArrowFunctionExpression (/private/tmp/a/pbr/node_modules/astring/dist/astring.js:680:12)
    at Object.generator.<computed> [as ArrowFunctionExpression] (/private/tmp/a/pbr/node_modules/@parcel/babel-ast-utils/lib/generator.js:270:10)
    at Object.VariableDeclarator (/private/tmp/a/pbr/node_modules/astring/dist/astring.js:501:27)
    at Object.generator.<computed> [as VariableDeclarator] (/private/tmp/a/pbr/node_modules/@parcel/babel-ast-utils/lib/generator.js:270:10)
    at formatVariableDeclaration (/private/tmp/a/pbr/node_modules/astring/dist/astring.js:197:15)
    at Object.VariableDeclaration (/private/tmp/a/pbr/node_modules/astring/dist/astring.js:493:5)
    at Object.generator.<computed> [as VariableDeclaration] (/private/tmp/a/pbr/node_modules/@parcel/babel-ast-utils/lib/generator.js:270:10)
    at Object.BlockStatement (/private/tmp/a/pbr/node_modules/astring/dist/astring.js:261:29)
npm ERR! code 1
npm ERR! path /private/tmp/a/pbr
npm ERR! command failed
npm ERR! command sh -c parcel build src/main.ts --log-level verbose --detailed-report 100 --no-minify --target modern

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel/.npm/_logs/2021-01-13T13_56_46_402Z-debug.log
```

## 💁 Possible Solution

I don't know. Adding optional chaining to the failing statement in astring makes builds succeed but the statement that created the issue before is removed.

## 🔦 Context

I tried to build my code but it failed.

## 💻 Code Sample

[parcel-optional-chaining-bug2.zip](https://github.com/parcel-bundler/parcel/files/5808986/parcel-optional-chaining-bug2.zip)

```
let f = (v) => v?.variant;
console.log(f);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.527+f343ebaa, 2.0.0-nightly.524+97a7bfee |
| Node             | v15.5.1 |
| npm/Yarn         | 7.3.0 |
| Operating System | macOS High Sierra (10.13.6) |

**Comment by danieltroger** [comment]
Note: adding `@babel/plugin-proposal-optional-chaining` to plugins in .babelrc makes the build succeed, but only because it transpiled the `?.` first. The goal is an output that retains `?.` untranspiled.

**Comment by danieltroger** [comment]
Thanks for the quick fix, hope it gets merged soon!

For now downgrading to `2.0.0-nightly.520+71264fe1` also does the trick, in case anyone else is suffering from this issue :)
