### ISSUE TITLE
Problems with static assets, PWAs, feedback, and more

### ISSUE THREAD

**Issue by justingolden21** [parcel-bundler/parcel#5679]
### Some feedback from someone using Parcel for the first time, encountering hours worth of bugs across several days

This isn't really a feature request, but it's the closest option I could find. Before just leaving Parcel for good, I wanted to give my fully documented feedback on it; hopefully this can help to improve Parcel in the future, since I really like the idea.

I'm building a PWA with TailwindCSS, and wanted to add Parcel, nothing more than that. It's a very simple application (< 300 lines of JS, < 100 lines HTML, < 10kb of code overall).

I was already informed going in that I need parcel 1, which doesn't support postcss 8 (so I need 7), and therefore autoprefixer 9 (not 10).

Upon installing parcel and then adding `"dev": "parcel src/index.html"` to my package.json, I got:

`error:postcss plugin tailwindcss requires postcss 8`

So I updated my dev dependencies, deleted node_modules, and ran npm install

I had the same error, so I deleted the package lock file and tried again

I got: `error: src/js/sw.js ENOENT no such file or directory`
so in my scripts I changed:
`navigator.serviceWorker.register('sw.js')`
into
`navigator.serviceWorker.register('../sw.js')`

Keep in mind that everything worked 100% perfectly before trying to add parcel

Finally, serving to localhost:1234 works

My page is almost blank, and I have many errors in the console. This is the meat of it:
```
(index):1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
Promise.then (async)
parcelRequire.js/scripts.js../..\sw.js @ scripts.js:17
newRequire @ scripts.cd665a19.js:47
(anonymous) @ scripts.cd665a19.js:81
(anonymous) @ scripts.cd665a19.js:120
(index):1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
Promise.then (async)
parcelRequire.js/scripts.js../..\sw.js @ scripts.js:125
newRequire @ scripts.cd665a19.js:47
(anonymous) @ scripts.cd665a19.js:81
(anonymous) @ scripts.cd665a19.js:120
manifest.js:8 
```

according to https://parceljs.org/json.html, I have to `import data from 'data/myfile.json';`

to I added the following to my scripts, which previously used the json files just fine:
```javascript
// for parcel to include the json files
import data from 'data/mydata.json';
import data from 'data/mydata2.json';
```

console error: identifier data has already been declared

```javascript
// for parcel to include the json files
import data from 'data/mydata.json';
import data2 from 'data/mydata2.json';
```

cannot resolve dependency data/mydata.json

```javascript
import data from '../data/mydata.json';
import data2 from '../data/mydata2.json';
```

Again, these links worked before parcel

Page is still blank. Tried reloading, killing and restarting parcel, looked through this: https://stackoverflow.com/questions/63102658/how-to-serve-a-json-file-with-parcel-without-bundling-it and https://github.com/parcel-bundler/parcel/issues/501

Moved all of my code from the json fetches:
```javascript
fetch('data/mydata.json')
 	.then(response => response.json())
 	.then(json => {
 		// my code here with json
	});
```

to `window.onload`. Still didn't work, had to update the variable names.

error in console, myscript1 doesn't exist

I tried loading it first in my index.html
```html
	<script src="js/myscript1.js"></script>
	<script src="js/myscript2.js"></script>
	<script src="js/scripts.js"></script>
```

Still doesn't work. I tried importing it:
```
myscript1.js:
export { func1 };
myscript2.js:
export { func2 };
scripts.js:
import { func1 } from 'myscript1.js';
import { func2} from 'myscript2.js';
```

Still have plenty of errors in the console:
```
Uncaught TypeError: (0 , myscript1.func1) is not a function
    at window.onload (mydata.json:1)
window.onload @ mydata.json:1
load (async)
parcelRequire.js/scripts.js../..\sw.js @ mydata.json:1
newRequire @ mydata.json:1
(anonymous) @ mydata.json:1
(anonymous) @ scripts.js:72
manifest.js:8 
```

console log mydata, works fine

console log func1, it's undefined

Read up on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import again

Removed removed `.js` from my imports, takes a while to build, still same result

Tried removing the other scripts from my `index.html` since they're already being imported, still dosen't work

Check spelling of my functions and imports and files: yup

Checked export docs on MDN: yup

Checked several other resources. Tried import { func1 } from './myscript1.js'; (adding `./`) and it works so far

Still have several errors:

- `manifest.js:8: Manifest: Line: 8, column: 1, Syntax error.`
- my images don't load
- func3 isn't defined in myscript1

Tried to get images to work with https://stackoverflow.com/questions/52841765/how-to-add-image-in-react-by-using-parcel
`import image from 'path/to/image.png';`

Still no luck

tried looping through my image names and importing them:
```javascript
for(let imgName of imgNames) {
	import image from './img/'+imgName+'.svg';
}
```

Still no luck

Tried importing from folder (even though this is apparently impossible in Parcel for some reason):

`import * from './img/';`

Still no luck

Meanwhile, I fixed my func3 issue by fixing the imports and exports.

This is the line that's an error in `manifest.js`:

`parcelRequire = (function (modules, cache, entry, globalName) {`

Yes, you read that right, manifest."js", not "json" (I don't have a manifest.js)

I googled `"manifest.js" "parcel" "syntax error"` and got 15 results, none useful...

Meanwhile, back to the images issue. I read https://github.com/parcel-bundler/parcel/issues/4683

I tried:

`import images from 'url:/img/*';`

no such file or directory

I tried:

`import images from '../img/*';`

no such file or directory

Now even removing the line the old code didn't work? even after waiting several seconds and terminal says it's done. I tried killing the terminal and restarting with npm run dev, now the old code works (still images don't work, and I have the issue with the weird manifest file).

I looked through https://parceljs.org/assets.html for help with the images.

Finally found this: https://github.com/parcel-bundler/parcel/issues/3056

Tried `const myimg1= require('../img/types/myimg1.svg');`, but even `myimg1` won't load

Now realizing because parcel isn't linking it right, I changed my loop to have all of the images link to `myimg1` and they all load with that image.

I ask a friend who suggests just copying the images over, I reference his code and use a two-line script:
```javascript
const fs = require('fs-extra')
fs.copySync('src/img', 'dist/img')
```
after installing *another* package (fs-extra) (my node_modules is now over 120mb... all for a project with 10kb of source files and 10kb of images)

The image links finally work... Maybe I should've done this with my json files too.

I still have the issue with the manifest. I check the code again. My src folder has a manifest.json, my dist folder has a manifest.js. Parcel seems to be converting my manifest.json to js for some reason...??? Surely it cannot be *that* stupid, and surely someone else on the planet attempted to make a PWA with parcel before? Nope, it truly is that stupid, it just wraps my json code in all of the parcel stuff, and on line 8:

```javascript
// modules are defined as an array
// [ module function, map of requires ]
//
// map of requires is short require name -> numeric require
//
// anything defined in a previous bundle is accessed via the
// orig method which is the require for previous bundles
parcelRequire = (function (modules, cache, entry, globalName) {
```

The first non-commented line, it breaks. Here is the full code, where it simply copies the entire contents of my manifest.json into a manifest.js and wraps it around hundreds of lines:

<details>
<summary> manifest.js </summary>
```javascript
// modules are defined as an array
// [ module function, map of requires ]
//
// map of requires is short require name -> numeric require
//
// anything defined in a previous bundle is accessed via the
// orig method which is the require for previous bundles
parcelRequire = (function (modules, cache, entry, globalName) {
  // Save the require from previous bundle to this closure if any
  var previousRequire = typeof parcelRequire === 'function' && parcelRequire;
  var nodeRequire = typeof require === 'function' && require;

  function newRequire(name, jumped) {
    if (!cache[name]) {
      if (!modules[name]) {
        // if we cannot find the module within our internal map or
        // cache jump to the current global require ie. the last bundle
        // that was added to the page.
        var currentRequire = typeof parcelRequire === 'function' && parcelRequire;
        if (!jumped && currentRequire) {
          return currentRequire(name, true);
        }

        // If there are other bundles on this page the require from the
        // previous one is saved to 'previousRequire'. Repeat this as
        // many times as there are bundles until the module is found or
        // we exhaust the require chain.
        if (previousRequire) {
          return previousRequire(name, true);
        }

        // Try the node require function if it exists.
        if (nodeRequire && typeof name === 'string') {
          return nodeRequire(name);
        }

        var err = new Error('Cannot find module \'' + name + '\'');
        err.code = 'MODULE_NOT_FOUND';
        throw err;
      }

      localRequire.resolve = resolve;
      localRequire.cache = {};

      var module = cache[name] = new newRequire.Module(name);

      modules[name][0].call(module.exports, localRequire, module, module.exports, this);
    }

    return cache[name].exports;

    function localRequire(x){
      return newRequire(localRequire.resolve(x));
    }

    function resolve(x){
      return modules[name][1][x] || x;
    }
  }

  function Module(moduleName) {
    this.id = moduleName;
    this.bundle = newRequire;
    this.exports = {};
  }

  newRequire.isParcelRequire = true;
  newRequire.Module = Module;
  newRequire.modules = modules;
  newRequire.cache = cache;
  newRequire.parent = previousRequire;
  newRequire.register = function (id, exports) {
    modules[id] = [function (require, module) {
      module.exports = exports;
    }, {}];
  };

  var error;
  for (var i = 0; i < entry.length; i++) {
    try {
      newRequire(entry[i]);
    } catch (e) {
      // Save first error but execute all entries
      if (!error) {
        error = e;
      }
    }
  }

  if (entry.length) {
    // Expose entry point to Node, AMD or browser globals
    // Based on https://github.com/ForbesLindesay/umd/blob/master/template.js
    var mainExports = newRequire(entry[entry.length - 1]);

    // CommonJS
    if (typeof exports === "object" && typeof module !== "undefined") {
      module.exports = mainExports;

    // RequireJS
    } else if (typeof define === "function" && define.amd) {
     define(function () {
       return mainExports;
     });

    // <script>
    } else if (globalName) {
      this[globalName] = mainExports;
    }
  }

  // Override the current require with this new one
  parcelRequire = newRequire;

  if (error) {
    // throw error from earlier, _after updating parcelRequire_
    throw error;
  }

  return newRequire;
})({"manifest.json":[function(require,module,exports) {
module.exports = {
  "name": "My app",
  "short_name": "My app",
  "description": "My description",
  "start_url": "index.html",
  "display": "standalone",
  "background_color": "#FFF",
  "theme_color": "#FFF",
  "orientation": "portrait-primary",
  "icons": [{
    "src": "img/icons/icon-48x48.png",
    "type": "image/png",
    "sizes": "48x48"
  }, {
    "src": "img/icons/icon-72x72.png",
    "type": "image/png",
    "sizes": "72x72"
  }, {
    "src": "img/icons/icon-96x96.png",
    "type": "image/png",
    "sizes": "96x96"
  }, {
    "src": "img/icons/icon-144x144.png",
    "type": "image/png",
    "sizes": "144x144"
  }, {
    "src": "img/icons/icon-192x192.png",
    "type": "image/png",
    "sizes": "192x192"
  }, {
    "src": "img/icons/icon-512x512.png",
    "type": "image/png",
    "sizes": "512x512"
  }]
};
},{}],"../node_modules/parcel-bundler/src/builtins/hmr-runtime.js":[function(require,module,exports) {
var global = arguments[3];
var OVERLAY_ID = '__parcel__error__overlay__';
var OldModule = module.bundle.Module;

function Module(moduleName) {
  OldModule.call(this, moduleName);
  this.hot = {
    data: module.bundle.hotData,
    _acceptCallbacks: [],
    _disposeCallbacks: [],
    accept: function (fn) {
      this._acceptCallbacks.push(fn || function () {});
    },
    dispose: function (fn) {
      this._disposeCallbacks.push(fn);
    }
  };
  module.bundle.hotData = null;
}

module.bundle.Module = Module;
var checkedAssets, assetsToAccept;
var parent = module.bundle.parent;

if ((!parent || !parent.isParcelRequire) && typeof WebSocket !== 'undefined') {
  var hostname = "" || location.hostname;
  var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
  var ws = new WebSocket(protocol + '://' + hostname + ':' + "49299" + '/');

  ws.onmessage = function (event) {
    checkedAssets = {};
    assetsToAccept = [];
    var data = JSON.parse(event.data);

    if (data.type === 'update') {
      var handled = false;
      data.assets.forEach(function (asset) {
        if (!asset.isNew) {
          var didAccept = hmrAcceptCheck(global.parcelRequire, asset.id);

          if (didAccept) {
            handled = true;
          }
        }
      }); // Enable HMR for CSS by default.

      handled = handled || data.assets.every(function (asset) {
        return asset.type === 'css' && asset.generated.js;
      });

      if (handled) {
        console.clear();
        data.assets.forEach(function (asset) {
          hmrApply(global.parcelRequire, asset);
        });
        assetsToAccept.forEach(function (v) {
          hmrAcceptRun(v[0], v[1]);
        });
      } else if (location.reload) {
        // `location` global exists in a web worker context but lacks `.reload()` function.
        location.reload();
      }
    }

    if (data.type === 'reload') {
      ws.close();

      ws.onclose = function () {
        location.reload();
      };
    }

    if (data.type === 'error-resolved') {
      console.log('[parcel] ✨ Error resolved');
      removeErrorOverlay();
    }

    if (data.type === 'error') {
      console.error('[parcel] 🚨  ' + data.error.message + '\n' + data.error.stack);
      removeErrorOverlay();
      var overlay = createErrorOverlay(data);
      document.body.appendChild(overlay);
    }
  };
}

function removeErrorOverlay() {
  var overlay = document.getElementById(OVERLAY_ID);

  if (overlay) {
    overlay.remove();
  }
}

function createErrorOverlay(data) {
  var overlay = document.createElement('div');
  overlay.id = OVERLAY_ID; // html encode message and stack trace

  var message = document.createElement('div');
  var stackTrace = document.createElement('pre');
  message.innerText = data.error.message;
  stackTrace.innerText = data.error.stack;
  overlay.innerHTML = '<div style="background: black; font-size: 16px; color: white; position: fixed; height: 100%; width: 100%; top: 0px; left: 0px; padding: 30px; opacity: 0.85; font-family: Menlo, Consolas, monospace; z-index: 9999;">' + '<span style="background: red; padding: 2px 4px; border-radius: 2px;">ERROR</span>' + '<span style="top: 2px; margin-left: 5px; position: relative;">🚨</span>' + '<div style="font-size: 18px; font-weight: bold; margin-top: 20px;">' + message.innerHTML + '</div>' + '<pre>' + stackTrace.innerHTML + '</pre>' + '</div>';
  return overlay;
}

function getParents(bundle, id) {
  var modules = bundle.modules;

  if (!modules) {
    return [];
  }

  var parents = [];
  var k, d, dep;

  for (k in modules) {
    for (d in modules[k][1]) {
      dep = modules[k][1][d];

      if (dep === id || Array.isArray(dep) && dep[dep.length - 1] === id) {
        parents.push(k);
      }
    }
  }

  if (bundle.parent) {
    parents = parents.concat(getParents(bundle.parent, id));
  }

  return parents;
}

function hmrApply(bundle, asset) {
  var modules = bundle.modules;

  if (!modules) {
    return;
  }

  if (modules[asset.id] || !bundle.parent) {
    var fn = new Function('require', 'module', 'exports', asset.generated.js);
    asset.isNew = !modules[asset.id];
    modules[asset.id] = [fn, asset.deps];
  } else if (bundle.parent) {
    hmrApply(bundle.parent, asset);
  }
}

function hmrAcceptCheck(bundle, id) {
  var modules = bundle.modules;

  if (!modules) {
    return;
  }

  if (!modules[id] && bundle.parent) {
    return hmrAcceptCheck(bundle.parent, id);
  }

  if (checkedAssets[id]) {
    return;
  }

  checkedAssets[id] = true;
  var cached = bundle.cache[id];
  assetsToAccept.push([bundle, id]);

  if (cached && cached.hot && cached.hot._acceptCallbacks.length) {
    return true;
  }

  return getParents(global.parcelRequire, id).some(function (id) {
    return hmrAcceptCheck(global.parcelRequire, id);
  });
}

function hmrAcceptRun(bundle, id) {
  var cached = bundle.cache[id];
  bundle.hotData = {};

  if (cached) {
    cached.hot.data = bundle.hotData;
  }

  if (cached && cached.hot && cached.hot._disposeCallbacks.length) {
    cached.hot._disposeCallbacks.forEach(function (cb) {
      cb(bundle.hotData);
    });
  }

  delete bundle.cache[id];
  bundle(id);
  cached = bundle.cache[id];

  if (cached && cached.hot && cached.hot._acceptCallbacks.length) {
    cached.hot._acceptCallbacks.forEach(function (cb) {
      cb();
    });

    return true;
  }
}
},{}]},{},["../node_modules/parcel-bundler/src/builtins/hmr-runtime.js","manifest.json"], null)
//# sourceMappingURL=/manifest.js.map
```
</details>

I still cannot believe Parcel is doing this, and I still cannot believe apparently nobody on the planet has ever used parcel to make a progressive web app... 

But I go on to build for production, surely if everything else works in development then production will work, right?

```cmd
\src\css\styles.css:undefined:undefined: PostCSS plugin postcss-purgecss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (C:\Users\my-name\OneDrive\Documents\GitHub\my-project\node_modules\postcss\lib\processor.js:167:15)
    at new Processor (C:\Users\my-name\OneDrive\Documents\GitHub\my-project\node_modules\postcss\lib\processor.js:56:25)
    at postcss (C:\Users\my-name\OneDrive\Documents\GitHub\my-project\node_modules\postcss\lib\postcss.js:55:10)
    at purgeUnusedUtilities (C:\Users\justi\OneDrive\Documents\GitHub\pokemon-types\node_modules\tailwindcss\lib\lib\purgeUnusedStyles.js:69:31)
    at C:\Users\my-name\OneDrive\Documents\GitHub\my-project\node_modules\tailwindcss\lib\processTailwindFeatures.js:75:555
    at LazyResult.run (C:\Users\justi\OneDrive\Documents\GitHub\my-project\node_modules\postcss\lib\lazy-result.js:288:14)
    at LazyResult.asyncTick (C:\Users\my-name\OneDrive\Documents\GitHub\pokemon-types\node_modules\postcss\lib\lazy-result.js:212:26)
    at LazyResult.asyncTick (C:\Users\my-name\OneDrive\Documents\GitHub\pokemon-types\node_modules\postcss\lib\lazy-result.js:225:14)
    at C:\Users\justi\OneDrive\Documents\GitHub\my-project\node_modules\postcss\lib\lazy-result.js:254:14
    at new Promise (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pokemon-types@1.0.0 build: `parcel build src/index.html --no-source-maps && npm run static-assets`
npm ERR! Exit status 1
```

Apparently I still have package dependency hell, even though it worked fine for dev, it doesn't work for prod.

Relevant parts of my package.json:
```json
"scripts": {
	"dev": "parcel src/index.html",
	"build": "parcel build src/index.html --no-source-maps && npm run static-assets",
	"static-assets": "node copy.js"
	},
"devDependencies": {
	"autoprefixer": "^9.8.6",
	"fs-extra": "^9.0.1",
	"parcel-bundler": "^1.12.4",
	"tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1"
	}
```

So I'll probably just copy the manifest itself, somehow get parcel to ignore that, and then still have to figure out this dependency nightmare since everything depends on everything else. I know not everything I mention is relevant to Parcel, but it's relevant to the user experience.

This is all to my point: My project worked in its entirety 100% before trying to add Parcel. Every single link every single script, image, json file, every piece of code worked perfectly. Parcel is marketed as "easy to use" and "easy to start", yet this took me, as someone who isn't familiar with Parcel, but is familiar with programming and web development in general, several hours across several days. Can you imagine someone trying to use your service and spending multiple hours each day for multiple days trying to get it to work? I must've got some great recommendations for Parcel... I can't imagine (purely looking from the outside, not too familiar with how Parcel works aside from chatting with several people about it, watching three or four videos, looking at the docs, getting started, CLI, and some other docs on the parceljs homepage and github page) how something as commonly used and well-received as parcel could not support basic features like copying static assets, handling PWAs, etc. There are just so many problems I encountered, and I'm sure many of them are not parcel's fault, but there are still quite a number of features that are missing in my opinion, that I've heard competitors like webpack have. I put this as a feature request not just because I think it's better than the other options, but because I detail several missing features in parcel here. Thank you for listening to my feedback.

**Comment by justingolden21** [comment]
Worth mentioning, in my `index.html`: `<link rel="manifest" href="manifest.json">` is converted to `<link rel="manifest" href="/manifest.js">` after parcel runs, in addition to converting my json to a js file for some reason.
