### ISSUE TITLE
Regression: `Uncaught error: Cannot find module`

### ISSUE THREAD

**Issue by lgarron** [parcel-bundler/parcel#5683]
I'm sorry for submitting such a general report without a small repro case. But this bug has already cost me a lot of time, and I'm very much at a loss for how to deal with it. I thought I'd file what I could, though.

# 🐛 bug report

Check out the following:

- Repo: https://github.com/cubing/cubing.js
- Commit: 3ff0968e92a46d14c2a1dad4f18080b6313f3949

Run: 

    make clean dev

Then visit http://localhost:3333/twisty/twisty-player.html and check the browser console.

See https://www.youtube.com/watch?v=PXkfFrLHS6o for an example of a successful build (beginning of video) and 8:32 for a failure.

To avoid the behaviour:

    npm install parcel@2.0.0-nightly.481 # no bug
    rm -rf ./node_modules/ ; make clean dev

To cause the behaviour:

    npm install parcel@2.0.0-nightly.485 # bug
    rm -rf ./node_modules/ ; make clean dev

(Parcel nightly versions 482/483/484 do not exist.)

## 🤔 Expected Behavior

No error. The page loads, shows a Rubik's Cube, and a table for some options.

## 😯 Current Behavior

*Sometimes* (the vast majority of the time, maybe 90%?) after running `npm install` from scratch, the following error appears:

    Uncaught Error: Cannot file module '2du48'.

This seems to correspond to [`./dom/viewers/Twisty3DCanvas`](https://github.com/cubing/cubing.js/blob/main/src/cubing/twisty/dom/viewers/Twisty3DCanvas.ts). It seems clear that there's an issue with the loading graph somehow related to this file, starting in `parcel@2.0.0-nightly.485`.

See https://garron.net/temp/cubing-js-parcel-2021-01-18.zip for the state of the cache folder when this occurs.

Sometimes after running `npm install`  (maybe 10% of the time?), however, there is no error. As far as I can tell, the error doesn't occur until the next time I delete `node_modules` and run `npm install` from scratch, which rolls the dice again.

## 💁 Possible Solution

No idea, I'm sorry. I've tried to dig into stack traces, but something is going wrong deep inside Parcel's module loading code and I can't debug it from inside my code.

I can't figure out how to map Parcel nightlies to Git commits, but correlating the version dates at https://www.npmjs.com/package/parcel  with https://github.com/parcel-bundler/parcel/commits/v2?after=bdc45e49437b986934d3b1b0d8f6a4ecc292a2aa+34&branch=v2 implies suggests that this regression was introduced in this range:

https://github.com/parcel-bundler/parcel/compare/a4cf3e958ea1136b4829eb93615fba5328213471...f89e5ef87fcb58e6131475b5218f188cc231a1d9

## 🔦 Context

I was trying to debug a Parcel bug that is breaking our production build. I tried to update Parcel to the latest nightly `2.0.0-nightly.539"` and was able to observe a bug in dev. That is this bug.

After spending *many* hours trying to make sense of it

## 💻 Code Sample

See above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `parcel@2.0.0-nightly.485` and above (I bisected. 481 and lower do not exhibit this issue, 482/483/484 do not exist, 485 and above do exhibit the issue).) |
| Node             | `v15.4.0` |
| npm/Yarn         | `6.14.11` 
| Operating System | macOS 10.15.7 as well as Big Sur (I can repro this issue on two different computers) |

**Comment by mischnic** [comment]
Happens consistently for me with the minimal reproduction: https://github.com/mischnic/parcel-issue-5683

For `dist/a.html`, the script tags for the shared bundles are added in the wrong order.

> I can't figure out how to map Parcel nightlies to Git commits

The hash is appended to the version field in the published tarball, you can see that for example here: https://unpkg.com/browse/parcel@2.0.0-nightly.447/package.json

**Comment by mischnic** [comment]
I've bisected the commits, this is a regression of https://github.com/parcel-bundler/parcel/pull/5200.

**Comment by mischnic** [comment]
A workaround is not using a file that is imported in some other place as a `<script>`  directly.

So instead of this https://github.com/cubing/cubing.js/blob/afa6e5b9379e8b9549769ec0cea4615a87c80a73/src/demo/twisty/2d-ll-stickering.html#L7
adding a `2d-ll-stickering.js` file with `import "../../cubing/twisty/index.ts"` (there might be other HTML files though)

**Comment by lgarron** [comment]
> A workaround is not using a file that is imported in some other place as a `<script>` directly.
> 
> So instead of this https://github.com/cubing/cubing.js/blob/afa6e5b9379e8b9549769ec0cea4615a87c80a73/src/demo/twisty/2d-ll-stickering.html#L7
> adding a `2d-ll-stickering.js` file with `import "../../cubing/twisty/index.ts"` (there might be other HTML files though)

Thanks, that's very helpful!
(I think that also explains some bugs I was seeing before.)

**Comment by ProLoser** [comment]
Would this have a similar effect for global variables such as `process`? I'm seeing a [similar bug](https://github.com/parcel-bundler/parcel/issues/5714)

**Comment by lgarron** [comment]
I've tried converting our project back to the Parcel v2 release candidate, and an error with this symptom ended up being a blocking issue again. :-/


```
VM566 2x2x2.kpuzzle.json_.a5d825d2.js:61 Uncaught Error: Cannot find module 'JacNc'
    at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:61)
    at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:45)
    at localRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:83)
    at Object.kmtFE.@parcel/transformer-js/src/esmodule-helpers.js (runtime-3acaea6fb4153fbf.js:377)
    at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:71)
    at VM566 2x2x2.kpuzzle.json_.a5d825d2.js:120
    at VM566 2x2x2.kpuzzle.json_.a5d825d2.js:143
```

`JacNc` corresponds to:

```
"@parcel/transformer-js/src/esmodule-helpers.js":"JacNc"
```

**Comment by lgarron** [comment]
> I've tried converting our project back to the Parcel v2 release candidate, and an error with this symptom ended up being a blocking issue again. :-/

After some investigation, this seems to be the issue described in https://github.com/parcel-bundler/parcel/issues/4095

The same file was imported sync in one place and async in the other place, causing the sync import to break as described above. In this case, it's easy to switch the sync import to something else, but I'm rather sad that I'm already running into this issue again. 😭

**Comment by mischnic** [comment]
That bug should be fixed though

**Comment by lgarron** [comment]
git checkout 39d9dd4260f2cdc1a1b03245392e778d5bb00ffb

**Comment by lgarron** [comment]
@mischnic This is a consistent repro for me:

**Comment by lgarron** [comment]
@mischnic This is a consistent repro for me:

```
git clone https://github.com/cubing/cubing.js && cd cubing.js
git checkout parcel-yet-again # 867bce58e6cf8c9f5e7ca781bec3ba8948f422ab
git revert f56dcb8b6c002ef87cafe82a8da410d373c1b624
npm install
make build-search-worker
npx parcel src/sites/index.html
```

This is with Parcel 2.0.0-rc.0. :-(

npm 7.21.0
node v16.8.0
macOS 11.5.2
Chrome 92.0.4515.159

**Comment by joeosburn** [comment]
I am having the same issue with `Cannot find module xxx`, which corresponds to `"@parcel/transformer-js/src/esmodule-helpers.js"`

parcel 2.0.0
npm 8.1.0
node 16.13.0
macOS 11.6
Safari 15.0 (16612.1.29.41.4, 16612)

**Comment by joeosburn** [comment]
I just updated to Parcel 2.0.1 and still having the same issue. Is this a configuration option problem in our stack or is this a bug in Parcel?

**Comment by arthurmmedeiros** [comment]
I'm also experiencing the same issue and updating parcel to 2.0.1 didn't solve it. 

parcel: 2.0.0-nightly.776

**Comment by yume-chan** [comment]
I have an even simpler repro: https://github.com/yume-chan/parcel-repro-5683

`a.js` and `b.js` each imports a different image file, so they are completely unrelated. When I include `a.js` before `b.js` in `index.html`, it works, then change the order, cannot find module. 

```
Uncaught Error: Cannot find module 'ciiiV'
    at newRequire (index.a28fffaf.js:61:19)
    at newRequire (index.a28fffaf.js:45:18)
    at localRequire (index.a28fffaf.js:84:35)
    at Object.8FjLI../a.png (runtime-1f074fef905954b1.js:473:2)
    at newRequire (index.a28fffaf.js:71:24)
    at index.a28fffaf.js:122:5
    at index.a28fffaf.js:145:3
```

It's related to build cache. If I clean the build cache, I can get the reversed behavior.

**Comment by danieltroger** [comment]
I think I'm suffering from a similar issue but not exactly this?

On `2.0.0-nightly.984+74fcc3fb` I get `index.f0bd8632.js:50 Uncaught Error: Cannot find module '43l7i'`, on 2.0.1 it works.

This issue is older than 2.0.1 so I guess it's something else. Will check if it's maybe cyclic imports…

**Comment by danieltroger** [comment]
Changing this in my entry `index.html` fixed it for me. Weird that I had no issues on 2.0.1.

```diff
diff --git a/app/public/index.html b/app/public/index.html
index 2b0e175da..1efda18df 100644
--- a/app/public/index.html
+++ b/app/public/index.html
@@ -47,6 +47,8 @@
       To begin the development, run `npm start` or `yarn start`.
       To create a production bundle, use `npm run build` or `yarn build`.
     -->
-    <script src="../src/index.tsx" type="module"></script>
+    <script type="module">
+      import "../src/index.tsx";
+    </script>
   </body>
 </html>
```

**Comment by danieltroger** [comment]
When changing the build target to `ie 11` my builds fail with `Uncaught Error: Cannot find module '2B7l9'` :(

Cleaning build cache doesn't work.

**Comment by sethsamuel** [comment]
Also hitting this on 2.3.2. Some level of complexity in the bundle graph seems to trigger it. The missing bundle is being generated, but the underlying js file is not being loaded client side. Tried fixing by removing scope hoisting and source mapping, but no luck.

Only occurs in `build`, not `watch`, since it's related to code splitting.

**Comment by sethsamuel** [comment]
The underlying cause for us here appears to be related to the pragmaFrag `/** @jsxImportSource @emotion/react */`. @emotion/react allows you to pass down the `css` prop without explicitly including it in props. This works mostly fine, even with a tree of components that lack the above frag on some of the components that are doing the passthrough.

However, as soon as there is a tree with some mixture of frag and no frag, the above error occurs. Explicitly adding the frag to the component(s) missing it in the chain, even if they don't themselves use the `css` prop, fixes the problem.

Not enough time to come up with a minimal reproduction right now, but hopefully this is helpful to some of those hitting this bug and to the authors.

**Comment by Aloento** [comment]
I have the same problem.
```
Uncaught Error: Cannot find module '622nD'
    at a (index.cad93178.js:1:578)
    at Object.<anonymous> (index.ts:2:1)
    at a (index.cad93178.js:1:534)
    at runtime-c3897e95e15efd7e.js:1:58
```

**Comment by meetdave3** [comment]
I had a similar error, after further debugging it seemed that I wasn't invoking the imported javascript function synchronously.  

```js
import '/src/scripts/myLib.ts'
window.myLib.init() // Causes the cannot find module error
```

The fix in my case was to call the init() func of myLib synchronously 

Changed it to:

```js
import('/src/scripts/myLib.ts').then(() => window.myLib.init())
```

and the error disappeared.

Using Parcel v2.4.0 

The error reporting isn't so verbose, it can be that the fix is different in other cases. This was mine ☝️ 

PS: The above fix will change the script import from inline to dynamic. If you want to still keep the script inline, invoke init() function inside the myLib.ts instead

**Comment by Hongjia-Liu** [comment]
If Hot Module Reloading is not working, the problem may relate to the periods (`.`) of the directories name. We can try to get rid of them.

Consider changing the `import` statement from relative path to absolute path, and then change it back. This magically works for me.
```jsx
import App from "./App";
import App from "/src/App"
```

**Comment by victoriomolina** [comment]
any updates?

**Comment by victoriomolina** [comment]
> ```diff
>  <script type="module">
> +      import "../src/index.tsx";
> +    </script>
> ```

Works for me too... really strange behavior!

**Comment by victoriomolina** [comment]
> Changing this in my entry `index.html` fixed it for me. Weird that I had no issues on 2.0.1.
> 
> ```diff
> diff --git a/app/public/index.html b/app/public/index.html
> index 2b0e175da..1efda18df 100644
> --- a/app/public/index.html
> +++ b/app/public/index.html
> @@ -47,6 +47,8 @@
>        To begin the development, run `npm start` or `yarn start`.
>        To create a production bundle, use `npm run build` or `yarn build`.
>      -->
> -    <script src="../src/index.tsx" type="module"></script>
> +    <script type="module">
> +      import "../src/index.tsx";
> +    </script>
>    </body>
>  </html>
> ```

@Aloento  In my case I am using bootstrap.


If I do:

```html
<body>
    <script type="module" src="../js/scripts/home.js"></script>
    <script type="module" src="../js/vendors/bootstrap.js"></script>
</body>
```

in this order, I get this strange error. But, if I change the imports order to:

```html
<body>
    <script type="module" src="../js/vendors/bootstrap.js"></script>
    <script type="module" src="../js/scripts/home.js"></script>
</body>
```

(bootstrap first), the error is gone!

**Comment by sznowicki** [comment]
I observe similar issues with quite random "cannot find module", depending on a setup it affects different imports. Only on production builds. I'm trying to make a repro repo and so far no luck finding what could be a reason. Only happens so far on our most complex mono repo.

**Comment by sznowicki** [comment]
I believe my issue is related (if not duplicate). I'm happy to say I made a repro repo and also I found a workaround for all affected: bundler-experimental seems to be free of this bug.


Issue with repro repo: https://github.com/parcel-bundler/parcel/issues/8480

Workaround `.parcelrc`:
```json
{
  "extends": "@parcel/config-default",
  "bundler": "@parcel/bundler-experimental"
}

```

**Comment by juanmirocks** [comment]
I have the same error.

On the console, I see a bunch of warnings like these:

```javascript
@parcel/transformer-js: Conditional or non-top-level `require()` call. This causes the resolved module and all dependencies to be wrapped.
@parcel/transformer-js: Unknown usage of CommonJS `module` object. This causes the module to be wrapped, and tree shaking to be disabled.
```

However, I do not have any conditional dependencies. Also, the "CommonJS `module`" errors refer to the parcel-internally generated JS code.

My stack uses:
* TypeScript
* React (written in .tsx)
* parcel `serve` mode

---

**This solution worked for me**: https://github.com/parcel-bundler/parcel/issues/5683#issuecomment-1022412113
This solution did not work for me: https://github.com/parcel-bundler/parcel/issues/5683#issuecomment-1249308888

**Comment by staplespeter** [comment]
I have encountered this error also.

I have a (AFAIK) straightforward repo and dev setup, purely for messing around with React and Node/TS.  When I try `npm run server` with the `index.js` from either the _dev_ or _release_ targets specified i get the `Cannot find module '???'` error.

For the _dev_ build it throws the following:

```
Error: Cannot find module 'express'
    at newRequire (file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:61:19)
    at newRequire (file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:45:18)
    at localRequire (file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:84:35)
    at Mo564.express (file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:159:16)
    at newRequire (file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:71:24)
    at localRequire (file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:84:35)
    at 7nGH6../Server (file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:147:15)
    at newRequire (file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:71:24)
    at file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:122:5
    at file:///mnt/Data/Repos/Demo-Project/build/dev/Server/index.js:145:3 {
  code: 'MODULE_NOT_FOUND'
}
```
from this code:
```
...
})({"1FAFy":[function(require,module,exports) {
var parcelHelpers = require("@parcel/transformer-js/src/esmodule-helpers.js");
var _server = require("./Server");
var _serverDefault = parcelHelpers.interopDefault(_server);
let server = new (0, _serverDefault.default)();
server.start();
process.on("SIGTERM", async ()=>{
    await server.stop();
});

},{"./Server":"5q1pD","@parcel/transformer-js/src/esmodule-helpers.js":"gsHjI"}],"5q1pD":[function(require,module,exports) {
//import * as inspector from 'node:inspector';
var parcelHelpers = require("@parcel/transformer-js/src/esmodule-helpers.js");
parcelHelpers.defineInteropFlag(exports);
var _express = require("express");   <-------------------------------------------- error
var _expressDefault = parcelHelpers.interopDefault(_express);
var _cors = require("cors");
var _corsDefault = parcelHelpers.interopDefault(_cors);
var _https = require("https");
var _httpsDefault = parcelHelpers.interopDefault(_https);
var _fs = require("fs");
var _fsDefault = parcelHelpers.interopDefault(_fs);
var _authRoutes = require("./Auth/AuthRoutes");
var _authRoutesDefault = parcelHelpers.interopDefault(_authRoutes);
class Server {
...
```
bundled from this src:
```
//import * as inspector from 'node:inspector';
import express, { ErrorRequestHandler } from "express";
import cors from 'cors';
import https from 'https';
import fs from 'fs';
import AuthRoutes from "./Auth/AuthRoutes";

export default class Server {
...
```
For the _release_ build it throws the following:
```
ReferenceError: $4qKYl$inspect is not defined
    at Object.<anonymous> (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:382384)
    at parcelRequire (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:5351)
    at Object.<anonymous> (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:375210)
    at parcelRequire (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:5351)
    at Object.<anonymous> (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:360826)
    at parcelRequire (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:5351)
    at Object.<anonymous> (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:356488)
    at parcelRequire (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:5351)
    at Object.<anonymous> (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:356307)
    at parcelRequire (file:///mnt/Data/Repos/Demo-Project/build/release/Server/index.js:1:5351)
```
from this code:
`...,parcelRequire.register("4ycop",function(t,r){t.exports=$4qKYl$inspect}),...`
and from god knows what source.

Here is the package.json

```
{
  "name": "demo-project",
  "type": "module",
  "scripts": {
    "clean": "rm -rf ./build",
    "testServer": "jest",
    "testClient": "testcafe",
    "build": "parcel build",
    "server": "node ./build/dev/Server/index.js",
    "servermon": "nodemon --delay 2.5 --watch build ./build/dev/Server/index.js",
    "client": "parcel --target clientDev --open --https",
    "startcs": "concurrently \"npm run servermon\" \"npm run client\""
  },
  "targets": {
    "serverRelease": {
      "context": "node",
      "engines": {
        "node": ">= 18"
      },
      "outputFormat": "esmodule",
      "scopeHoist": true,
      "isLibrary": false,
      "optimize": true,
      "includeNodeModules": true,
      "sourceMap": false,
      "source": "./src/Server/Api/index.ts",
      "distDir": "./build/release/Server",
      "publicUrl": "/"
    },
    "serverDev": {
      "context": "node",
      "engines": {
        "node": ">= 18"
      },
      "outputFormat": "esmodule",
      "scopeHoist": false,
      "isLibrary": false,
      "optimize": false,
      "includeNodeModules": false,
      "sourceMap": true,
      "source": "./src/Server/Api/index.ts",
      "distDir": "./build/dev/Server",
      "publicUrl": "/"
    },
    "clientRelease": {
      "context": "browser",
      "engines": {
        "browsers": "> 0.5%, last 2 versions, not dead"
      },
      "outputFormat": "esmodule",
      "scopeHoist": true,
      "isLibrary": false,
      "optimize": true,
      "includeNodeModules": true,
      "sourceMap": false,
      "source": "./src/wwwroot/signIn.htm",
      "distDir": "./build/release/Client",
      "publicUrl": "/"
    },
    "clientDev": {
      "context": "browser",
      "engines": {
        "browsers": "> 0.5%, last 2 versions, not dead"
      },
      "outputFormat": "esmodule",
      "scopeHoist": false,
      "isLibrary": false,
      "optimize": false,
      "includeNodeModules": true,
      "sourceMap": true,
      "source": "./src/wwwroot/signIn.htm",
      "distDir": "./build/dev/Client",
      "publicUrl": "/"
    }
  },
  "devDependencies": {
    "@types/cors": "^2.8.13",
    "@types/express": "^4.17.17",
    "@types/jest": "^28.1.3",
    "@types/react": "^18.0.21",
    "@types/react-dom": "^18.0.6",
    "buffer": "^6.0.3",
    "concurrently": "^7.6.0",
    "crypto-browserify": "^3.12.0",
    "events": "^3.3.0",
    "https-browserify": "^1.0.0",
    "jest": "^28.1.3",
    "jest-cucumber": "^3.0.1",
    "kill-port": "^2.0.1",
    "nodemon": "^2.0.22",
    "os-browserify": "^0.3.0",
    "parcel": "^2.7.0",
    "process": "^0.11.10",
    "punycode": "^1.4.1",
    "querystring-es3": "^0.2.1",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0",
    "testcafe": "^2.6.2",
    "ts-add-js-extension": "^1.4.0",
    "ts-jest": "^28.0.7",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5",
    "url": "^0.11.0",
    "util": "^0.12.4"
  },
  "dependencies": {
    "@mysql/xdevapi": "8.0.33",
    "axios": "^0.27.2",
    "cors": "^2.8.5",
    "date-fns": "^2.29.2",
    "express": "^4.18.2",
    "jose": "^4.9.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "secure-random-password": "^0.2.3"
  }
}
```
if i am using Parcel (or something else) incorrectly please let me know.  I've followed the Parcel docs and i expect it to work OOTB as it is touted as doing.

Going to try a different bundler instead.

**Comment by serenecloud** [comment]
```
-    <script src="../src/index.tsx" type="module"></script>
+    <script type="module">
+      import "../src/index.tsx";
+    </script>
 ```
We are giving this a try now - given this can be an intermittent issue we need to keep an eye on it, but the change didn't break anything and our previously failing deployment has worked.

Thanks so much for posting this - I'm hopeful it'll help us get past this problem at least until root cause is sorted.

**Comment by serenecloud** [comment]
> We are giving this a try now - given this can be an intermittent issue we need to keep an eye on it, but the change didn't break anything and our previously failing deployment has worked.

Sadly this has ended up being an incorrect statement. We've seen that images loaded using `import` (and `require` when tested) don't load correctly if you are in a url subfolder (example.com/ would work fine, but example.com/hello/ would not).

This is still a smaller problem than the main one, but definitely something to test if you use the workaround.

**Comment by ritikanand123** [comment]
Guys The Solution is very Easy Delete the dist and .parcel folder and build the product again

**Comment by serenecloud** [comment]
> Guys The Solution is very Easy Delete the dist and .parcel folder and build the product again

I understand this might work for your case, but when you're bundling and shipping software on a CI pipeline and you can't rely on the bundle being consistent and correct then it's a problem.

**Comment by vallamost** [comment]
Deleting and rebuilding feels like rebooting Windows lol

I ran into this after following this Chart JS tutorial - 
https://www.chartjs.org/docs/latest/getting-started/usage.html

When I ran into weird npm segment fault issues I upgraded node from 20 to 22, then I ran into a Cannot find module error, deleting the folders and rebuilding fixed the issue.

**Comment by evanminto** [comment]
I'm getting the same or a possibly related error, despite hearing repeatedly that it's been fixed.

`Unhandled Rejection (Error): Cannot find module '77Z1g'` and similar errors, which occur sporadically when loading pages in the develoopment build. If I refresh the page, I see the error about half the time. It seems to occur only when I reference a module from multiple other modules that have been code-split. If the module is referenced at least once inside the main bundle, the bug doesn't appear, but if the only references to it are static imports _inside dynamically imported code_, it appears. This makes it impossible to practically use code-splitting, since it's very easy to accidentally trigger the bug.

I’m on 2.0.0, but the bug appears in 2.0.0-beta.3.1 and 2.12.0 as well. I tried `@parcel/bundler-experimental` as recommended, but the bug still appears.

**Comment by jdanyow** [comment]
I can reproduce this error consistently. I've yet to be able to distill it down to a simple reproduction. In my case, I'm unable to use code splitting- eg `import('...')`. The dynamic import always works when using `parcel watch`, but when using `parcel build`, running the application results in the `Error: Cannot find module 'xxxxx'`.

**Comment by ritikanand123** [comment]
what i can think of is that parcle is not able to override the previous changes

**Comment by tehpsalmist** [comment]
Definitely would love to see this get fixed. Every single time I import another module in a file, I get the "cannot find module" error and I have to kill the process and restart. Thankfully builds are lightning fast, but this is nevertheless a frustration because it happens every time and seems like a bug that undermines the core competency of this tool.

**Comment by Gellipapa** [comment]
Hi! I have tested many different things. 

The result of the tests:
If you add the transformers in parcelrc, the build and serve will be slower, but the code will work.

```
//.parcelrc file

{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

In case you use it like this

```
<script type="module">
     import "../src/index.tsx";
</script>
```

If you don't want it to be slow, so you don't want to use transformer, you should use ```--no-hmr```. 

If you use ```--no-hmr``` the errors will disappear and the application will work. So it's probably all to do with hmr.

As has been written here before: https://github.com/parcel-bundler/parcel/discussions/6974

I hope that others will be able to solve the problem on this basis.

**Comment by TechQuery** [comment]
> I've tried converting our project back to the Parcel v2 release candidate, and an error with this symptom ended up being a blocking issue again. :-/
> 
> ```
> VM566 2x2x2.kpuzzle.json_.a5d825d2.js:61 Uncaught Error: Cannot find module 'JacNc'
>     at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:61)
>     at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:45)
>     at localRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:83)
>     at Object.kmtFE.@parcel/transformer-js/src/esmodule-helpers.js (runtime-3acaea6fb4153fbf.js:377)
>     at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:71)
>     at VM566 2x2x2.kpuzzle.json_.a5d825d2.js:120
>     at VM566 2x2x2.kpuzzle.json_.a5d825d2.js:143
> ```
> 
> `JacNc` corresponds to:
> 
> ```
> "@parcel/transformer-js/src/esmodule-helpers.js":"JacNc"
> ```

Same bug shows in `parcel@2.14.4` while Hot Module Reloading is enabled.

**Comment by Gellipapa** [comment]
> > I've tried converting our project back to the Parcel v2 release candidate, and an error with this symptom ended up being a blocking issue again. :-/
> > ```
> > VM566 2x2x2.kpuzzle.json_.a5d825d2.js:61 Uncaught Error: Cannot find module 'JacNc'
> >     at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:61)
> >     at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:45)
> >     at localRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:83)
> >     at Object.kmtFE.@parcel/transformer-js/src/esmodule-helpers.js (runtime-3acaea6fb4153fbf.js:377)
> >     at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:71)
> >     at VM566 2x2x2.kpuzzle.json_.a5d825d2.js:120
> >     at VM566 2x2x2.kpuzzle.json_.a5d825d2.js:143
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `JacNc` corresponds to:
> > ```
> > "@parcel/transformer-js/src/esmodule-helpers.js":"JacNc"
> > ```
> 
> Same bug shows in `parcel@2.14.4` while Hot Module Reloading is enabled.

Hi! I'm sad to hear that you have the same problem. One thing is for sure, your code needs to be changed and it's not a parcel error.

Things to look out for include:

1. Use module import: <script type="module" src="./test-app.tsx"></script> in entry html file. 
2. Upgrade your node version to at least 19.
3. If you are loading stuff with required somewhere, change it to import() logic.
4. This always happened after a particular page so I knew where the import problem could be and had to change the order and fix it there.
5. Use the alias option in package.json to disable the packagings if you get a required problem somewhere. 
For example:   
```
"alias": {
    "yamlparser": false,
    "punycode": false,
    "pseudomap": false
  },
```

6. Delete the old parcel logics and install only the plain "parcel" of the packagings. Also clear the cache folder of everything that is written in v2 docs.
7. parcelrc use the so: 
```
{
  "extends": "@parcel/config-default",
}
```
8. Uninstall the old tsc compiler, because parcelv2 already uses SWR to compile files and is faster.

If you go through these steps, sooner or later you will find out what the problem was. 

Unfortunately, I don't know exactly what solved the problem for me, but I've certainly done what I described.

I hope you manage to solve the problem and remember that the problem is still not in parcelv2 but in your code.

Thanks for read. 

Bye

**Comment by TechQuery** [comment]
> > > I've tried converting our project back to the Parcel v2 release candidate, and an error with this symptom ended up being a blocking issue again. :-/
> > > ```
> > > VM566 2x2x2.kpuzzle.json_.a5d825d2.js:61 Uncaught Error: Cannot find module 'JacNc'
> > >     at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:61)
> > >     at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:45)
> > >     at localRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:83)
> > >     at Object.kmtFE.@parcel/transformer-js/src/esmodule-helpers.js (runtime-3acaea6fb4153fbf.js:377)
> > >     at newRequire (VM566 2x2x2.kpuzzle.json_.a5d825d2.js:71)
> > >     at VM566 2x2x2.kpuzzle.json_.a5d825d2.js:120
> > >     at VM566 2x2x2.kpuzzle.json_.a5d825d2.js:143
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `JacNc` corresponds to:
> > > ```
> > > "@parcel/transformer-js/src/esmodule-helpers.js":"JacNc"
> > > ```
> > 
> > Same bug shows in `parcel@2.14.4` while Hot Module Reloading is enabled.
> 
> Hi! I'm sad to hear that you have the same problem. One thing is for sure, your code needs to be changed and it's not a parcel error.
> 
> Things to look out for include:
> 
> 1. Use module import: <script type="module" src="./test-app.tsx"></script> in entry html file. 
> 2. Upgrade your node version to at least 19.
> 3. If you are loading stuff with required somewhere, change it to import() logic.
> 4. This always happened after a particular page so I knew where the import problem could be and had to change the order and fix it there.
> 5. Use the alias option in package.json to disable the packagings if you get a required problem somewhere. 
> For example:   
> ```
> "alias": {
>     "yamlparser": false,
>     "punycode": false,
>     "pseudomap": false
>   },
> ```
> 
> 6. Delete the old parcel logics and install only the plain "parcel" of the packagings. Also clear the cache folder of everything that is written in v2 docs.
> 7. parcelrc use the so: 
> ```
> {
>   "extends": "@parcel/config-default",
> }
> ```
> 8. Uninstall the old tsc compiler, because parcelv2 already uses SWR to compile files and is faster.
> 
> If you go through these steps, sooner or later you will find out what the problem was. 
> 
> Unfortunately, I don't know exactly what solved the problem for me, but I've certainly done what I described.
> 
> I hope you manage to solve the problem and remember that the problem is still not in parcelv2 but in your code.
> 
> Thanks for read. 
> 
> Bye

1. Same mode
2. node@22
3. No `require()`
4. Not always the same page
5. No aliases
6. Delete cache every time
7. yes, extend default configure
8. Can't, I need ES decorator stage-3.

**Comment by Mubelotix** [comment]
I had this issue in a webextension for parcel 2.15.2. I resolved it by removing an import statement to a function that no longer existed. It wasn't used anywhere but caused issues for some reason
