### ISSUE TITLE
Build failed. @parcel/transformer-babel: D:Projetsjeydijeydi.7bb06934.js: Unknown substitution "BODY" given

### ISSUE THREAD

**Issue by jeydi243** [parcel-bundler/parcel#5719]
Hi everyone! I currently use **"parcel": "^2.0.0-beta.1"**
When i try to run  command : `parcel watch index.html ` but i have this error:
```
Error: Unknown substitution "BODY" given
    at D:\Projets\jeydi\node_modules\@babel\template\lib\populate.js:29:15
    at Array.forEach (<anonymous>)
    at populatePlaceholders (D:\Projets\jeydi\node_modules\@babel\template\lib\populate.js:27:31)
    at D:\Projets\jeydi\node_modules\@babel\template\lib\string.js:22:51    at D:\Projets\jeydi\node_modules\@babel\template\lib\builder.js:77:14
    at spec (D:\Projets\jeydi\node_modules\babel-plugin-transform-es2015-for-of\lib\index.js:171:20)
    at PluginPass.ForOfStatement (D:\Projets\jeydi\node_modules\babel-plugin-transform-es2015-for-of\lib\index.js:76:21)
    at newFn (D:\Projets\jeydi\node_modules\@babel\traverse\lib\visitors.js:175:21)
    at NodePath._call (D:\Projets\jeydi\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (D:\Projets\jeydi\node_modules\@babel\traverse\lib\× Build failed.
@parcel/transformer-babel: D:Projetsjeydijeydi.7bb06934.js: Unknown substitution "BODY" given
```
You can find and clone my repo here : [https://github.com/jeydi243/jeydi.git](url)
Tank you!

**Comment by mischnic** [comment]
> babel-plugin-transform-es2015-for-of

You're using a Babel 6 plugin. Upgrade your babel config to Babel 7 plugins
