### ISSUE TITLE
typescript: cannot build if `export * as namespace` within codebase

### ISSUE THREAD

**Issue by waynevanson** [parcel-bundler/parcel#5771]
I've been meaning to do this for months but right now I don't have time to write the issue.
I'll do it in 24 hours.

# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by waynevanson** [comment]
Updated! :)

**Comment by JoeHowarth** [comment]
Any updates here? I'm running into a similar issue I believe 

```
➜  xRaydiumClient git:(main) npx parcel src/index.html
Server running at http://localhost:1234/
🚨  /Users/jh/work/wormhole/xRaydiumClient/node_modules/@certusone/wormhole-sdk-proto-web/lib/esm/index.js: /Users/jh/work/wormhole/xRaydiumClient/node_modules/@certusone/wormhole-sdk-proto-web/lib/esm/index.js: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
> 1 | export * as annotations from "./google/api/annotations";
    |        ^^^^^^^^^^^^^^^^
  2 | export * as http from "./google/api/http";
  3 | export * as descriptor from "./google/protobuf/descriptor";
  4 | export * as gossip from "./gossip/v1/gossip";
> 1 | export * as annotations from "./google/api/annotations";
    |        ^^^^^^^^^^^^^^^^
  2 | export * as http from "./google/api/http";
  3 | export * as descriptor from "./google/protobuf/descriptor";
  4 | export * as gossip from "./gossip/v1/gossip";
    at File.buildCodeFrameError (/Users/jh/work/wormhole/xRaydiumClient/node_modules/@babel/core/lib/transformation/file/file.js:249:12)
    at NodePath.buildCodeFrameError (/Users/jh/work/wormhole/xRaydiumClient/node_modules/@babel/traverse/lib/path/index.js:145:21)
    at assertExportSpecifier (/Users/jh/work/wormhole/xRaydiumClient/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:112:16)
    at /Users/jh/work/wormhole/xRaydiumClient/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:202:9
    at Array.forEach (<anonymous>)
    at /Users/jh/work/wormhole/xRaydiumClient/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:201:31
    at Array.forEach (<anonymous>)
    at getModuleMetadata (/Users/jh/work/wormhole/xRaydiumClient/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:149:27)
    at normalizeModuleAndLoadMetadata (/Users/jh/work/wormhole/xRaydiumClient/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:58:7)
    at rewriteModuleStatementsAndPrepareHeader (/Users/jh/work/wormhole/xRaydiumClient/node_modules/@babel/helper-module-transforms/lib/index.js:93:54)
```

**Comment by subhankar-trisetra** [comment]
Same issue :-(
```bash
🚨  /Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/cheerio/node_modules/htmlparser2/lib/esm/index.js:
 /Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/cheerio/node_modules/htmlparser2/lib/esm/index.js:
Export namespace should be first transformed by `@babel/plugin-transform-export-namespace-from`.
  46 |  * They should probably be removed eventually.
  47 |  */
> 48 | export * as ElementType from "domelementtype";
     |        ^^^^^^^^^^^^^^^^
  49 | import { getFeed } from "domutils";
  50 | export { getFeed } from "domutils";
  51 | const parseFeedDefaultOptions = { xmlMode: true };
  46 |  * They should probably be removed eventually.
  47 |  */
> 48 | export * as ElementType from "domelementtype";
     |        ^^^^^^^^^^^^^^^^
  49 | import { getFeed } from "domutils";
  50 | export { getFeed } from "domutils";
  51 | const parseFeedDefaultOptions = { xmlMode: true };
    at File.buildCodeFrameError (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/node_modules/@babel/core/lib/transformation/file/file.js:205:12)
    at NodePath.buildCodeFrameError (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/path/index.js:105:21)
    at assertExportSpecifier (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:93:16)
    at /Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:179:9
    at Array.forEach (<anonymous>)
    at /Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:178:31
    at Array.forEach (<anonymous>)
    at getModuleMetadata (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:125:27)
    at normalizeModuleAndLoadMetadata (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:47:7)
    at rewriteModuleStatementsAndPrepareHeader (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/helper-module-transforms/lib/index.js:94:54)
    at PluginPass.exit (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:135:83)
    at newFn (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/visitors.js:159:14)
    at NodePath._call (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/path/context.js:90:8)
    at TraversalContext.visitQueue (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/@babel/traverse/lib/index.js:49:34)
    at transformFile (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/node_modules/@babel/core/lib/transformation/index.js:81:29)
    at transformFile.next (<anonymous>)
    at run (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at /Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/node_modules/@babel/core/lib/transform-ast.js:23:41
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/gensync/index.js:251:28)
    at sync (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at Object.transformFromAst (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/node_modules/@babel/core/lib/transform-ast.js:37:87)
    at babel7 (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/transforms/babel/babel7.js:29:17)
    at async JSAsset.transform (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/assets/JSAsset.js:127:9)
    at async JSAsset.process (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Asset.js:216:7)
    at async Pipeline.processAsset (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Pipeline.js:46:7)
    at async Pipeline.process (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Pipeline.js:24:23)
    at async Object.run (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Bundler.loadAsset (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:577:19)
    at async /Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 8)
    at async Bundler.loadAsset (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 6)
    at async Bundler.loadAsset (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 5)
    at async Bundler.loadAsset (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 0)
    at async Bundler.loadAsset (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async Bundler.processAsset (/Users/subhankar/workspace/personal/universal-pdp-scrapper/example/node_modules/parcel-bundler/src/Bundler.js:557:5)
```

**Comment by Taelar** [comment]
Any update on this ? I'm having a similar issue
```
❯ yarn start
Server running at http://localhost:1234 
🚨  /home/user/company/project/node_modules/htmlparser2/lib/esm/index.js: /home/user/company/project/node_modules/htmlparser2/lib/esm/index.js: 
Export namespace should be first transformed by `@babel/plugin-transform-export-namespace-from`.
  46 |  * They should probably be removed eventually.
  47 |  */
> 48 | export * as ElementType from "domelementtype";
     |        ^^^^^^^^^^^^^^^^
  49 | import { getFeed } from "domutils";
  50 | export { getFeed } from "domutils";
  51 | const parseFeedDefaultOptions = { xmlMode: true };
  46 |  * They should probably be removed eventually.
  47 |  */
> 48 | export * as ElementType from "domelementtype";
     |        ^^^^^^^^^^^^^^^^```

**Comment by Taelar** [comment]
My bad, I was using v1 (parcel-bundler) instead of latest version (parcel)
