### ISSUE TITLE
Multiple js entry points does not work

### ISSUE THREAD

**Issue by maksimsemenov** [parcel-bundler/parcel#5785]
# 🐛 bug report
When I'm trying to build a project with several js entry points, the parcel throws an error: 
```
Bundles must have unique filePaths

AssertionError [ERR_ASSERTION]: Bundles must have unique filePaths
    at BundlerRunner.nameBundles (parcel-multiple-entries-bug/node_modules/@parcel/core/lib/BundlerRunner.js:359:23)
    at async BundlerRunner.bundle (parcel-multiple-entries-bug/node_modules/@parcel/core/lib/BundlerRunner.js:315:5)
    at async Parcel._build (parcel-multiple-entries-bug/node_modules/@parcel/core/lib/Parcel.js:617:11)
    at async Parcel.run (parcel-multiple-entries-bug/node_modules/@parcel/core/lib/Parcel.js:480:18)
    at async run (parcel-multiple-entries-bug/node_modules/parcel/lib/cli.js:373:7)
```

## 🔦 Context

The use case that I'm trying to solve here is to have parcel build multiple bundles that then can be included into the external framework (Laravel).

## 💻 Code Sample

[Repro repository](https://github.com/maksimsemenov/parcel-multiple-entries-bug)

Run `npm install` and `npm run build`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.573
| Node             |v14.15.1
| npm        |6.14.11
| Operating System |MacOS

**Comment by mischnic** [comment]
Remove `"main": "index.js",` from package.json https://v2.parceljs.org/getting-started/migration/#package.json%23main

**Comment by maksimsemenov** [comment]
Thanks. I did that and the original error went away.

However, I'm still having the issue with multiple entry points in a more complex "production" setup.

I made changes to the [reproducible repo](https://github.com/maksimsemenov/parcel-multiple-entries-bug) to better represent what we have in our app but still stay small.

Now, if you run the `npm run build` in the [repro repo](https://github.com/maksimsemenov/parcel-multiple-entries-bug), parcel will throw:
```
@parcel/namer-default: Bundle group cannot have more than one entry bundle of the same type
AssertionError [ERR_ASSERTION]: Bundle group cannot have more than one entry bundle of the same type
    at Object.name (parcel-multiple-entries-bug/node_modules/@parcel/namer-default/lib/DefaultNamer.js:81:29)
    at BundlerRunner.nameBundle (parcel-multiple-entries-bug/node_modules/@parcel/core/lib/BundlerRunner.js:369:39)
    at parcel-multiple-entries-bug/node_modules/@parcel/core/lib/BundlerRunner.js:356:50
    at Array.map (<anonymous>)
    at BundlerRunner.nameBundles (parcel-multiple-entries-bug/node_modules/@parcel/core/lib/BundlerRunner.js:356:31)
    at async BundlerRunner.bundle (parcel-multiple-entries-bug/node_modules/@parcel/core/lib/BundlerRunner.js:315:5)
    at async Parcel._build (parcel-multiple-entries-bug/node_modules/@parcel/core/lib/Parcel.js:617:11)
    at async Parcel.run (parcel-multiple-entries-bug/node_modules/@parcel/core/lib/Parcel.js:480:18)
    at async run (parcel-multiple-entries-bug/node_modules/parcel/lib/cli.js:373:7)
```

**Comment by mischnic** [comment]
So what's happening (in a further reduced reproduction) is that Parcel wants to create these three bundles (all with `isEntry: true`):
1. the bundle for JS entrypoint A
2. the bundle for some shared CSS the entrypoints use (render.css)
3. the bundle for some CSS used by 1

Looks like that assertion is too strict, it does work correctly in this case:
```
dist/profile.js     (JS entrypoint A)
dist/profile.css    (shared CSS)
dist/user.js        (JS entrypoint B)
dist/user.css       (CSS for entrypoint B)
```
