### ISSUE TITLE
Basic Typescript App not working in 1.4.1 - 'super' keyword unexpected here

### ISSUE THREAD

**Issue by mpkelly** [parcel-bundler/parcel#579]
## Bug Report
Typescript Hello World program not working in version 1.4.1. 

## Files

**index.ts**
```
console.log("Hello, world!")
```

**index.html**

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
</head>
<body>
<div id="app"></div>
<script src="./src/index.ts"></script>
</body>
</html>
```

tsconfig.json
```json
{
    "compilerOptions": {
        "sourceMap": true,
        "allowJs": true,
        "noImplicitAny": false,
        "module": "commonjs",
        "target": "es2015"
    },
    "include": [
        "./src/**/*",
    ]
}
```
**Node JS**
```
v6.9.4
```

**Dependencies**
```
  "dependencies": {
    "@types/react": "^16.0.34",
    "@types/react-dom": "^16.0.3",
    "babel-preset-env": "^1.6.1",
    "parcel-bundler": "^1.4.1",
    "typescript": "^2.6.2"
  }
```

**Error Details**
```
Server running at http://localhost:1234 
🚨  /Users/Mike/Projects/helloworld/index.html: 'super' keyword unexpected here
      return yield super.parse(_this.contents);
                   ^^^^^
SyntaxError: 'super' keyword unexpected here
    at NativeCompileCache._moduleCompile (/Users/Mike/Projects/helloworld/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/Users/Mike/Projects/helloworld/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (/Users/Mike/Projects/helloworld/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Parser.findParser (/Users/Mike/Projects/helloworld/node_modules/parcel-bundler/lib/Parser.js:59:45)
    at Parser.getAsset (/Users/Mike/Projects/helloworld/node_modules/parcel-bundler/lib/Parser.js:66:22)

```

Can anyone see what's wrong? This is my first time using Parcel so maybe I missed something but the [documentation](https://parceljs.org/transforms.html) claims that Parcel can build TypeScript projects out of the box.

**Comment by Sylvenas** [comment]
I have the same problem，😣！

**Comment by DeMoorJasper** [comment]
Node 6 is currently not fully supported, try with node 8 or above
