### ISSUE TITLE
Parcel is unable to find module ./fs-search.linux-arm-musl.node

### ISSUE THREAD

**Issue by K-Visscher** [parcel-bundler/parcel#5812]
# 🐛 bug report

On `arm32v7/node:14.15.4-alpine` parcel is unable to find a module: `Error: Cannot find module './fs-search.linux-arm-musl.node'`

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```js
{
  "name": "some-name",
  "version": "1.0.0",
  "description": "something",
  "author": "someone",
  "license": "MIT",
  "repository": "https://github.com/somewhere/over/the/rainbow",
  "dependencies": {
    "stuff": "1.0.0",
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  },
  "scripts": {
    "dev": "npm run development",
    "development": "parcel build --dist-dir ../backend/public --public-url . src/index.html",
    "prod": "npm run production",
    "production": "parcel build --no-source-maps --public-url . src/index.html"
  }
}
```

`Dockerfile`
```
FROM arm32v7/node:14.15.4-alpine AS build

RUN apk update \
    && apk add python \
    && apk add build-base

WORKDIR /usr/src/app
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/

WORKDIR /usr/src/app/backend
RUN npm install
COPY backend .

WORKDIR /usr/src/app/frontend
RUN npm install
COPY frontend .
RUN npm run production

FROM arm32v7/node:14.15.4-alpine AS final
ENV NODE_ENV production
EXPOSE 8080

WORKDIR /usr/src/app/

COPY --from=build /usr/src/app/backend/ .
COPY --from=build /usr/src/app/frontend/dist/ ./public/

ENTRYPOINT ["node"]
CMD ["src/index.js"]
```

## 🤔 Expected Behavior
```
> parcel build --no-source-maps --public-url . src/index.html

✨ Built in 33.31s
```

## 😯 Current Behavior

```
> parcel build --no-source-maps --public-url . src/index.html

Error: Cannot find module './fs-search.linux-arm-musl.node'
Require stack:
- /usr/src/app/frontend/node_modules/@parcel/fs-search/index.js
- /usr/src/app/frontend/node_modules/@parcel/fs/lib/NodeFS.js
- /usr/src/app/frontend/node_modules/@parcel/fs/lib/index.js
- /usr/src/app/frontend/node_modules/parcel/lib/cli.js
- /usr/src/app/frontend/node_modules/parcel/lib/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/usr/src/app/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/usr/src/app/frontend/node_modules/@parcel/fs-search/index.js:15:18)
    at Module._compile (/usr/src/app/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/frontend/node_modules/@parcel/fs-search/index.js',
    '/usr/src/app/frontend/node_modules/@parcel/fs/lib/NodeFS.js',
    '/usr/src/app/frontend/node_modules/@parcel/fs/lib/index.js',
    '/usr/src/app/frontend/node_modules/parcel/lib/cli.js',
    '/usr/src/app/frontend/node_modules/parcel/lib/bin.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! some-name@1.0.0 production: `parcel build --no-source-maps --public-url . src/index.html`
npm ERR! Exit status 1
```

## 🔦 Context

Packaging a frontend app for distrubution on `ARMv7` alpine.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-beta.1`
| Node             | `14.15.4`
| npm/Yarn         | `6.14.10`
| Operating System | `arm32v7/node:14.15.4-alpine`

**Comment by mischnic** [comment]
We only build `fs-search.linux-arm-gnueabihf.node` at the moment, not musl.

- https://unpkg.com/browse/@parcel/fs-search@2.0.0-nightly.2203/
- https://github.com/parcel-bundler/parcel/blob/v2/.github/workflows/nightly-release.yml

**Comment by K-Visscher** [comment]
> We only build `fs-search.linux-arm-gnueabihf.node` at the moment, not musl.
> 
> * https://unpkg.com/browse/@parcel/fs-search@2.0.0-nightly.2203/
> * https://github.com/parcel-bundler/parcel/blob/v2/.github/workflows/nightly-release.yml

That's fine, any chance a musl build is coming in the future?
I've switched to `arm32v7/node:14.15.5-stretch-slim`, everything works great now, thanks!

**Comment by ol-loginov** [comment]
What if I have freebsd build machine? How to manage without binary modules for freebsd?

**Comment by danousna** [comment]
Hi there,

Any update on this issue ? I am getting from what I think, a similar one: 
`Error: Cannot find module './artifacts/index.linux-arm64-gnu.node'`

I am on `node 14.17.6`, the system is an Nvidia Jetson AGX Xavier. Parcel version is `2.0.0-rc.0`.

**Comment by truesteps** [comment]
heya! Any updates/build for musl?

**Comment by i-bsd** [comment]
Just started getting this error today: `Error: Cannot find module './artifacts/index.freebsd-x64.node'`

Never had this problem with FreeBSD before. What changed?

**Comment by CassaranoIFTV** [comment]
UP!
I have the same problem for each version of parcel >= 2.0.0-alpha.1:
`Error: Cannot find module './artifacts/index.freebsd-x64.node`

The previous versions work but without last features like optionalChaining

**Comment by i-bsd** [comment]
> UP! I have the same problem for each version of parcel >= 2.0.0-alpha.1: `Error: Cannot find module './artifacts/index.freebsd-x64.node`
> 
> The previous versions work but without last features like optionalChaining

Need to emphasize the importance of this for us FreeBSD users. So many Node dependencies rely on this so we are unable to do anything at work until this is resolved.

**Comment by mischnic** [comment]
Parcel packages which are missing freebsd binaries:
- https://unpkg.com/browse/@parcel/transformer-js@2.4.0/
- https://unpkg.com/browse/@parcel/fs-search@2.4.0/
- https://unpkg.com/browse/@parcel/hash@2.4.0/
- https://unpkg.com/browse/@parcel/source-map@2.0.2/
- https://unpkg.com/browse/@parcel/css@1.7.3/package.json

**Comment by i-bsd** [comment]
Any updates on this? Still urgent.

**Comment by i-bsd** [comment]
Bump. Still a major issue that needs a fix, please.

**Comment by i-bsd** [comment]
Friendly reminder that it's been over 6 months since parcel has stopped working on FreeBSD. 

Can anyone address this?

`Error: Cannot find module './artifacts/index.freebsd-x64.node'`

**Comment by xse** [comment]
Hey,
Is there a note/procedure detailing how to generate those files ?
I can understand not wanting to distribute for every possible system but it would be nice if we had details on how to do it ourselves.
I have a couple machines running free/openbsd on which I have to setup a whole thing to move files onto another computer, run the bundle thing and copy dist/ back. On slow connections it takes ages to run.

**Comment by travispaul** [comment]
Just hit this on an illumos system as well, came to try parcel because encountered a similar issue with rollup... 

I guess the old approach of npm building the module locally when a prebuilt one doesn't exist doesn't work with rust modules like it did with node-gyp/C++ (or just fell out of favor?)

**Comment by fancsali** [comment]
As @xse mentioned: I guess no-one would mind if there was a way to build it ourselves...

In fact, I am having a slightly different issue (#9496) , but still, I reckon it'd be nice to somehow allow it to be built.

**Comment by svmhdvn** [comment]
This issue blocks packaging parcel-based frontend applications on FreeBSD, such as the popular https://codeberg.org/emersion/gamja IRC web client. What's the current status of this issue?
