### ISSUE TITLE
2.0.0-nightly.585 locks up CPU and nukes node_modules folder

### ISSUE THREAD

**Issue by folknor** [parcel-bundler/parcel#5829]
# 🐛 bug report

Running my build script on 2.0.0-nightly.579 works fine, but if I update to 585 it locks the spawned node process to 100% CPU indefinitely until I forcefully kill it.

But not before it nukes all node_modules except the _folders_ that start with "@". It nukes the contents of those folders as well, but does not remove them. Nor does it remove the .bin folder, but the contents is nuked.

Obviously this is not a big problem since I can just kill the process, downgrade to 579 and `npm install` again.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
	"name": "web",
	"version": "1.0.0",
	"description": "",
	"scripts": {
		"parcel:build": "parcel build index.html --no-source-maps --no-scope-hoist --detailed-report 0 --target web"
	},
	"web": "./dist/index.html",
	"targets": {
		"web": {
			"context": "browser",
			"publicUrl": "./"
		}
	},
	"browserslist": [
		"defaults",
		"not IE 11"
	],
	"author": "",
	"license": "ISC",
	"devDependencies": {
		"@iconify/iconify": "beta",
		"animate.css": "latest",
		"autoprefixer": "latest",
		"avif": "latest",
		"bootstrap": "next",
		"copyfiles": "latest",
		"fabric": "latest",
		"parcel": "2.0.0-nightly.585",
		"sass": "latest"
	}
}
```

.sassrc
```
{
	"includePaths": ["node_modules"],
	outputStyle: "expanded",
}
```

I have no .parcelrc or equivalent, or any other config files.

**Comment by folknor** [comment]
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                                                                
  66022 folk      20   0 2196764 139092  34504 R 103,3   0,4   1:38.00 node                                                                                                                                                                                                                                                   
  66140 folk      20   0   18,6g 255112 109116 S  21,6   0,8   0:03.00 code-insiders                                                                                                                                                                                                                                          
  54727 folk      20   0 4800208 159472 105772 S   5,3   0,5   0:16.61 code-insiders                                                                                                                                                                                                                                          
  54758 folk      20   0  554712 115284  72768 S   4,7   0,4   1:32.19 code-insiders                                                                                                                                                                                                                                          

```

```
folk       65985  0.0  0.0   2628   780 pts/2    S+   20:44   0:00 sh -c npm run clean && npm run copy && npm run parcel:build 
folk       66010  0.2  0.1 688848 45628 pts/2    Sl+  20:44   0:00 npm run parcel:build
folk       66021  0.0  0.0   2628   780 pts/2    S+   20:44   0:00 sh -c parcel build index.html --no-source-maps --no-scope-hoist --detailed-report 0 --target web
folk       66022  100  0.3 2178588 121072 pts/2  Rl+  20:44   1:41 node /home/folk/[snip]/node_modules/.bin/parcel build index.html --no-source-maps --no-scope-hoist --detailed-report 0 --target web

```

(I removed the clean and copy scripts and other irrelevant content from the original comment)

**Comment by mischnic** [comment]
One change in nightly.585 was that for example the SASS Parcel plugin isn't installed anymore along with the `parcel` package. It should be autoinstalled once a SASS file is being used. What npm/OS are you using? Looks like autoinstall isn't working for you.

**Comment by folknor** [comment]
Here's where I killed node the first time
```
...
Installing @parcel/transformer-posthtml...
⠸ Building index.html...
Killed
npm ERR! code 137
```
And the 2nd time:
```
Installing @parcel/transformer-html...
⠇ Building index.html...
Killed
npm ERR! code 137
```

Using npm v7.5.3 and node 15.8, on a systemd+dpkg linux.

The `--no-autoinstall` option is not documented in the `parcel help build` output.

I ran it now, and on the first run it said `@parcel/core: Cannot find Parcel plugin "@parcel/transformer-posthtml"` so I did `npm i -D @parcel/transformer-posthtml@nightly`. Then on the second run it said the same for `transformer-html`, so I installed that. Third run it said `transformer-sass`. Fourth run it said `transformer-css`. Fifth `transformer-postcss`. Then on subsequent runs: packager-html, optimizer-htmlnano, packager-css, optimizer-cssnano.

And then finally it completed. That is to say, it builds cleanly without crashing/locking/nuking node_modules.

And now my package.json devdeps looks like

```
	"devDependencies": {
		"@iconify/iconify": "beta",
		"@parcel/optimizer-cssnano": "^2.0.0-nightly.587",
		"@parcel/optimizer-htmlnano": "^2.0.0-nightly.587",
		"@parcel/packager-css": "^2.0.0-nightly.587",
		"@parcel/packager-html": "^2.0.0-nightly.587",
		"@parcel/transformer-css": "^2.0.0-nightly.587",
		"@parcel/transformer-html": "^2.0.0-nightly.587",
		"@parcel/transformer-postcss": "^2.0.0-nightly.587",
		"@parcel/transformer-posthtml": "^2.0.0-nightly.587",
		"@parcel/transformer-sass": "^2.0.0-nightly.587",
		"animate.css": "latest",
		"autoprefixer": "latest",
		"avif": "latest",
		"bootstrap": "next",
		"copyfiles": "latest",
		"fabric": "latest",
		"parcel": "2.0.0-nightly.585",
		"sass": "latest"
	}
```

**Comment by mischnic** [comment]
> The --no-autoinstall option is not documented in the parcel help build output.

It is:
```
  --no-autoinstall           disable autoinstall
```

**Comment by folknor** [comment]
My apologies, I was running the previous nightly when I checked the docs. I didn't realise it was a new option :1st_place_medal:

**Comment by devongovett** [comment]
Are you using yarn or npm?

**Comment by folknor** [comment]
npm v7.5.3

**Comment by mischnic** [comment]
I can confirm that somehow npm isn't working correctly.

npm 6:
```
TypeError: input.replace is not a function
    at markdownParser (/Users/niklas/Desktop/asd/node_modules/@parcel/markdown-ansi/lib/markdown-ansi.js:28:17)
    at prettyDiagnostic (/Users/niklas/Desktop/asd/node_modules/@parcel/utils/lib/prettyDiagnostic.js:77:171)
    at writeDiagnostic (/Users/niklas/Desktop/asd/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:233:45)
    at _report (/Users/niklas/Desktop/asd/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:201:19)
🚨 Build failed.
unknown: Could not resolve module "@parcel/transformer-posthtml" from "/Users/niklas/Desktop/asd"
Autoinstall is disabled, please install this package manually and restart Parcel.
```

npm 7 hangs at 100% CPU.

**Comment by devongovett** [comment]
I fixed a similar issue with yarn that had to do with yarn -> parcel -> yarn process nesting. Perhaps npm has something similar.

**Comment by danieltroger** [comment]
I can't run `parcel build` anymore either, it gets stuck at

```
Installing @parcel/packager-css...
⠋ Building b3fa5a2d5a8aa5d1868dc1205ef7c83f.js..
```

with 100% cpu usage

**Comment by toastal** [comment]
I'm getting very similar issues, not with Sass, but SugarSS ... failing to install modules. I'm using Yarn (v1) with `workspaces` (e.g. `yarn workspace $PROJECT run build:prod`). The same error exists if I just run the command `set NODE_ENV production; parcel build --log-level error --no-cache --dist-dir "../../public/parcel/$NODE_ENV/$PROJECT/" --public-url "/parcel/$NODE_ENV/$PROJECT" --no-source-maps "./index.html" && cp -r "icons/" "../../public/parcel/$NODE_ENV/$PROJECT/"`. With the `--no-autoinstall` I could get further by manually installing `posthtml` and `html` transformers, but manual `postcss` and `css` transformers didn't seem to be found.

```json
{
  "...": 0,
  "dependencies": {
    "@toastal/parcel-transformer-dhall-json": "^0.0.2",
    "@toastal/parcel-utils-dhall": "^0.0.1",
    "autoprefixer": "^10.2.4",
    "parcel": "^2.0.0-alpha.3",
    "postcss": "^8.2.4",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-import": "^14.0.0",
    "postcss-mixins": "^7.0.1",
    "postcss-nesting": "^7.0.1",
    "sugarss": "^3.0.3"
  },
  "...": 0
}
```

the parcel version is nightly 599

**Comment by mischnic** [comment]
Seems to work correctly with npm 6 and 7 in the latest nightly (after https://github.com/parcel-bundler/parcel/pull/5885)

**Comment by toastal** [comment]
This isn't fixed in Yarn using workspaces.

```
$ yarn workspace pwa run build:dev
yarn workspace v1.22.10
yarn run v1.22.10
$ NODE_ENV=development yarn build:purs && yarn bundle:dev
$ spago build --purs-args="--codegen js,corefn"
           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
[info] Build succeeded.
$ NODE_ENV=development parcel build --cache-dir "./.parcel-cache" --dist-dir "../../public/parcel/$NODE_ENV/pwa/" --public-url "." --no-source-maps "./index.html"
🚨 Build failed.
Error: Failed to install @parcel/transformer-posthtml: Yarn failed to install modules
Error: Failed to install @parcel/transformer-posthtml: Yarn failed to install modules
    at install ($HOME/$PROJECT/node_modules/@parcel/package-manager/lib/installPackage.js:161:11)
    at async PromiseQueue._runFn ($HOME/$PROJECT/node_modules/@parcel/utils/lib/PromiseQueue.js:108:7)
    at async PromiseQueue._next ($HOME/$PROJECT/node_modules/@parcel/utils/lib/PromiseQueue.js:95:5)
error Command failed with exit code 1.
```

and when trying to run the dev server

```
@parcel/package-manager: yarn: Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
@parcel/package-manager: yarn: Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
🚨 Build failed.
Error: Failed to install @parcel/transformer-posthtml: Yarn failed to install modules
Error: Failed to install @parcel/transformer-posthtml: Yarn failed to install modules
    at install ($HOME/$PROJECT/node_modules/@parcel/package-manager/lib/installPackage.js:161:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PromiseQueue._runFn ($HOME/$PROJECT/node_modules/@parcel/utils/lib/PromiseQueue.js:108:7)
    at async PromiseQueue._next ($HOME/$PROJECT/node_modules/@parcel/utils/lib/PromiseQueue.js:95:5)
```
