### ISSUE TITLE
config.setWatchGlob is not a function in transformer-babel

### ISSUE THREAD

**Issue by toastal** [parcel-bundler/parcel#5841]
# 🐛 bug report

Running my prod build pipeline, I got `Error: config.setWatchGlob is not a function` and can't build. I'm not using Babel anywhere, but I guess it's being ran anyhow??

## 🎛 Configuration (.babelrc, package.json, cli command)

Versions of `transformer-babel`: 

```sh
$ rg "@parcel/core" yarn.lock
1510:"@parcel/core@2.0.0-nightly.596+f9750100":
1512:  resolved "https://registry.yarnpkg.com/@parcel/core/-/core-2.0.0-nightly.596.tgz#177b2c350ff4398e9cb24ee8bb96209809c6a171"
9118:    "@parcel/core" "2.0.0-nightly.596+f9750100"

$ rg "@parcel/transformer-babel" ./yarn.lock 
1450:    "@parcel/transformer-babel" "2.0.0-nightly.529+f343ebaa"
1494:    "@parcel/transformer-babel" "2.0.0-nightly.598+f9750100"
2109:"@parcel/transformer-babel@2.0.0-nightly.529+f343ebaa":
2111:  resolved "https://registry.yarnpkg.com/@parcel/transformer-babel/-/transformer-babel-2.0.0-nightly.529.tgz#3b166c6e9710d5bdfeb35846ded57f9622b4e06b"
2130:"@parcel/transformer-babel@2.0.0-nightly.598+f9750100":
2132:  resolved "https://registry.yarnpkg.com/@parcel/transformer-babel/-/transformer-babel-2.0.0-nightly.598.tgz#c397b8a37f153731d6b73cd87857258e6a96cdd3"
```

`package.json`

```json
{ 
  "...": 0,
  "dependencies": {
    "@toastal/parcel-transformer-dhall-json": "^0.0.2",
    "@toastal/parcel-utils-dhall": "^0.0.1",
    "autoprefixer": "^10.2.4",
    "parcel": "^2.0.0-beta.1",
    "postcss": "^8.2.4",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-import": "^14.0.0",
    "postcss-mixins": "^7.0.1",
    "postcss-nesting": "^7.0.1",
    "sugarss": "^3.0.3"
  },
  "...": 1,
}
```

`.parcelrc`

```js
// rc does not come with an extension: https://github.com/parcel-bundler/parcel/issues/3430
// vim: filetype=json5
{
  // https://github.com/parcel-bundler/parcel/blob/v2/packages/configs/default/index.json
  "extends": "@parcel/config-default",

  "transformers": {
    "*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
      // "@parcel/transformer-react-refresh-babel",
      "@parcel/transformer-babel",
      "@parcel/transformer-js",
      // "@parcel/transformer-react-refresh-wrap"
    ],
    "manifest.dhall": [
      "@toastal/parcel-transformer-dhall-json",
      "@parcel/transformer-webmanifest",
    ],
    "*.dhall": [
      "@toastal/parcel-transformer-dhall-json"
    ]
  }
}
```

## 🤔 Expected Behavior

Not build errors. ...Oh, dynamic languages and their not-a-function errors.

## 😯 Current Behavior

```sh
# running the prod build pipeline
$ spago build --purs-args="--codegen js,corefn"
$ zephyr -f App.Main.main
$ NODE_ENV=production parcel build --log-level error --no-cache --dist-dir "../../public/parcel/$NODE_ENV/pwa/" --public-url "/parcel/$NODE_ENV/pwa" --no-source-maps "./index.html"
🚨 Build failed.
Error: config.setWatchGlob is not a function
TypeError: config.setWatchGlob is not a function
    at load ($HOME/$PROJECT/node_modules/@parcel/transformer-babel/lib/config.js:158:10)
    at async Object.loadConfig ($HOME/$PROJECT/node_modules/@parcel/transformer-babel/lib/BabelTransformer.js:66:5)
    at async ConfigLoader.loadPluginConfig ($HOME/$PROJECT/node_modules/@parcel/core/lib/ConfigLoader.js:204:9)
    at async PromiseQueue._runFn ($HOME/$PROJECT/node_modules/@parcel/core/node_modules/@parcel/utils/lib/PromiseQueue.js:108:7)
    at async PromiseQueue._next ($HOME/$PROJECT/node_modules/@parcel/core/node_modules/@parcel/utils/lib/PromiseQueue.js:95:5)
```

## 💁 Possible Solution

First I'm going to see if I can ignore the unused Babel in `.parcelrc.json`, if that doesn't work gonna try to roll back versions.

**POST:** It seems I can't skip `transformer-babel` because of other dependencies. Rolling back to `@parcel/core@2.0.0-nightly.579` seemed to work.

## 🔦 Context

Just trying to run build after `yarn upgrade`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.596+f9750100
| Node             | v14.15.5
| npm/Yarn         | 1.22.10 (yarn)
| Operating System | NixOS 21.05 (Okapi) x86_64

**Comment by mischnic** [comment]
This is probably because you have a version of the babel transformer (2.0.0-nightly.529 ) that is much older than core.

**Comment by toastal** [comment]
A later upgrade seemed to fix this particular issue. Closing.

**Comment by fregante** [comment]
It just happened to me because I installed a non-nightly Parcel 2 package. 


```sh
npm i @parcel/config-webextension # failed
```
```sh
npm i @parcel/config-webextension@nightly # worked
```
