### ISSUE TITLE
i am getting this wired error

### ISSUE THREAD

**Issue by mrparag94** [parcel-bundler/parcel#5842]
I am using the default config
nightly 596

TypeError: input.replace is not a function
    at markdownParser (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
TypeError: input.replace is not a function
    at markdownParser (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
TypeError: input.replace is not a function
    at markdownParser (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
TypeError: input.replace is not a function
    at markdownParser (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
TypeError: input.replace is not a function
    at markdownParser (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
TypeError: input.replace is not a function
    at markdownParser (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
TypeError: input.replace is not a function
    at markdownParser (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)
    at Object.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:260:12)
    at ReporterRunner.report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\core\lib\ReporterRunner.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
TypeError: input.replace is not a function
    at markdownParser (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\markdown-ansi\lib\markdown-ansi.js:28:17)
    at prettyDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\utils\lib\prettyDiagnostic.js:77:171)
    at writeDiagnostic (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:233:45)
    at _report (C:\Users\xxxxxxxxx\Desktop\Dev\Programming\Web\TypeScript\LearningTypeScript\node_modules\@parcel\reporter-cli\lib\CLIReporter.js:201:19)

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/5829#issuecomment-778424244
