### ISSUE TITLE
parcel build ignores .parcelrc?

### ISSUE THREAD

**Issue by jeffpeck10x** [parcel-bundler/parcel#5882]
I'm not sure if this is a bug or a misunderstanding on my part. But, I could not find anything in the documentation about this.

I have a monorepo that has a package that imports svg's and then exports them.

To handle these, I have a .parcelrc with this:
```
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.svg": ["@parcel/transformer-inline-string", "..."]
	}
}
```

And I when I run my demo package with `parcel serve`, everything works correctly. 🎉 

However, if I do `parcel build` from the package that is importing the svg-containing package, and list that package in `includeNodeModules`, so that it will be bundled inline, I get errors like:
```
packages/markers/index.ts does not export 'asteriskSvg'
```

where that is being exported like this:
```
export { default as asteriskSvg } from "./asterisk.svg";
```

I found that if I change that to:
```
export { default as asteriskSvg } from "./asterisk.ts"; // <---- note the .ts extension
```
(and create a temporary `asterisk.ts` file that exports raw text) everything works!

So... it's not handling the .svg's.

Out of curiosity, I tried replacing the .parcelrc with random characters "kl;hsjdfkljds", and it completely ignored the change. I tried deleting .parcel-cache and doing so had no effect.

And so, my conclusion is that `parcel build` seems to ignore `.parcelrc`, but I wonder if I am doing something wrong here. Or what the recommended workaround might be.

## 🤔 Expected Behavior

Transformers in `.parcelrc` would behave the same way for `parcel build` as for `parcel serve`

## 😯 Current Behavior

It seems like `.parcelrc` is being ignored.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.573+31f431d9
| Node             | v12.20.1
| npm/Yarn         | yarn
| Operating System | MacOS 10.15.7 (19H524)

**Comment by mischnic** [comment]
I think the parcelrc behaviour is somehow caused by caching, maybe this is also already resolved. Have you tried deleting .parcel-cache after modifying it?

The "does not export message" is definitely a bug, a workaround would be doing this instead:
```js
import _asteriskSvg from "./asterisk.svg";

export const asteriskSvg = _asteriskSvg;
```

**Comment by jeffpeck10x** [comment]
Aha, so... that suggestion worked to resolve the error.

But now I am getting:
```
❯ yarn build
yarn run v1.22.10
$ yarn workspace @10xdev/basecall-layer build
$ parcel build ./src/index.ts --no-source-maps --no-cache
🚨 Build failed.
Error: Cannot read property 'hashReferences' of undefined
TypeError: Cannot read property 'hashReferences' of undefined
    at getBundlesIncludedInHash (/path/to/myproject/node_modules/@parcel/core/lib/PackagerRunner.js:674:47)
    at getBundlesIncludedInHash (/path/to/myproject/node_modules/@parcel/core/lib/PackagerRunner.js:678:7)
    at assignComplexNameHashes (/path/to/myproject/node_modules/@parcel/core/lib/PackagerRunner.js:666:31)
    at PackagerRunner.writeBundles (/path/to/myproject/node_modules/@parcel/core/lib/PackagerRunner.js:226:7)
    at async Parcel._build (/path/to/myproject/node_modules/@parcel/core/lib/Parcel.js:621:7)
    at async Parcel.run (/path/to/myproject/node_modules/@parcel/core/lib/Parcel.js:480:18)
    at async run (/path/to/myproject/node_modules/parcel/lib/cli.js:373:7)
```

I tried deleting .parcel-cache to no avail.

I am fairly certain that this is still related to the svg imports because when I replace them with this:
```
export { default as asteriskSvg } from "./test";
export { default as circleSvg } from "./test";
...etc...
```
(where `test.ts` exports a string, containing an svg)

the problem goes away and it builds perfectly.

Do you have any other suggestions?

Thanks for the help.

**Comment by mischnic** [comment]
> hashReferences 

Looks like https://github.com/parcel-bundler/parcel/issues/4145

 > still related to the svg

Yes, it is specific to that

**Comment by jeffpeck10x** [comment]
Oh, right, that's why it looked familiar. And the "fix" was to do `--no-scope-hoist`, but now that I am trying to build a module I actually seem to need to _not_ use that flag:
```
❯ yarn build
yarn run v1.22.10
$ yarn workspace @10xdev/basecall-layer build
$ parcel build ./src/index.ts --no-source-maps --no-scope-hoist --no-cache
🚨 Build failed.
@parcel/packager-js: esmodule output is not supported without scope hoisting.
Error: esmodule output is not supported without scope hoisting.
```

Unless I am misunderstanding something about all that...

**Comment by jeffpeck10x** [comment]
Aha! I can build with `main` it does indeed import. This is all set for me at the moment. For anyone searching, this is my working package.json that I can build a library with included svg's from an internally imported library/pacakge:
```
{
  "name": "my-package-name",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "main": "dist/index.js",
  "source": "src/index.ts",
  "types": "index.d.ts",
  "scripts": {
    "build": "parcel build ./src/index.ts --no-source-maps --no-scope-hoist --no-cache",
    "clean": "rm -rf ./dist",
    "rebuild": "yarn clean && yarn build"
  },
  "browserslist": [
    "> 0.2%",
    "not dead"
  ],
  "dependencies": {
    ...
  },
  "devDependencies": {
    ...
    "parcel": "^2.0.0-beta.1",
    "typescript": "^4.1.3"
  },
  "targets": {
    "types": false
  },
  "webpackEntry": "src/index.ts"
}
```

My .parcelrc looks like this:
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.svg": ["@parcel/transformer-inline-string", "..."]
  }
}
```

When I `yarn build`, it creates the `dist/index.js` and I am able to import the package into another project.

The `--no-scope-hoist` fixes the `hashReferences` issue and even allows me to import/export on one line as I was doing previously:
```
export { default as asteriskSvg } from "./asterisk.svg";
```

Although the `--no-scope-hoist` also prevents me from outputting to a `module`. But, this is a fine solution for my current purposes and perhaps will work for others too.
