### ISSUE TITLE
@parcel/transformer-typescript-tsc does not work

### ISSUE THREAD

**Issue by ranisalt** [parcel-bundler/parcel#5911]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)
package.json:
```json
{
	"source": "src/index.ts",
	"module": "dist/index.js",
	"types": "dist/index.d.ts",
}
```

`src/index.ts`
```ts
export * from './src/components';
```

CLI: `parcel build index.ts`

## 🤔 Expected Behavior

It should build.

## 😯 Current Behavior

```
@parcel/transformer-typescript-types: node.exportClause.elements is not iterable
TypeError: node.exportClause.elements is not iterable
    at visit (/home/rsa/skyfall/frontend/node_modules/@parcel/transformer-typescript-types/lib/collect.js:66:47)
    at visitNodes (/home/rsa/skyfall/frontend/node_modules/typescript/lib/typescript.js:80382:48)
    at Object.visitEachChild (/home/rsa/skyfall/frontend/node_modules/typescript/lib/typescript.js:80739:56)
    at visit (/home/rsa/skyfall/frontend/node_modules/@parcel/transformer-typescript-types/lib/collect.js:112:15)
    at visitNode (/home/rsa/skyfall/frontend/node_modules/typescript/lib/typescript.js:80329:23)
    at Object.visitEachChild (/home/rsa/skyfall/frontend/node_modules/typescript/lib/typescript.js:80737:222)
    at visit (/home/rsa/skyfall/frontend/node_modules/@parcel/transformer-typescript-types/lib/collect.js:112:15)
    at visitNodes (/home/rsa/skyfall/frontend/node_modules/typescript/lib/typescript.js:80382:48)
    at visitLexicalEnvironment (/home/rsa/skyfall/frontend/node_modules/typescript/lib/typescript.js:80422:22)
    at Object.visitEachChild (/home/rsa/skyfall/frontend/node_modules/typescript/lib/typescript.js:80809:55)
```

## 🔦 Context

I just want to build this with types.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | parcel@2.0.0-nightly.579
| Node             | v15.9.0
| npm/Yarn         | 1.22.10
| Operating System | Arch Linux

**Comment by mischnic** [comment]
I've tried this:
```
{
	"source": "index.ts",
	"types": "dist/index.d.ts",
	"scripts": {
		"build": "parcel build . --no-cache"
	},
	"dependencies": {
		"parcel": "2.0.0-nightly.579",
		"typescript": "^4.1.5"
	}
}
```

```ts
// index.ts
export * from './components';

// components.ts
export type Foo = string;
```

but it builds fine. Looks like some code in `./src/components` is triggering that error (or you have a different typescript version)?

**Comment by ranisalt** [comment]
My `src/components/index.ts` had an `export * as Icons from './Icons'`, and `Icons.tsx` exported several React components. That alone created issues with the `babel` transformer, a cryptic error message that unfortunately I didn't save, so I have been using the `typescript-tsc` which goes past that. I don't have the files in hand now, but maybe that's related?

**Comment by tia-svazquez** [comment]
I have exactly the same issue as @ranisalt when trying to export an `Icons` file on my `index.ts`.

**Comment by Swizec** [comment]
For anyone else who lands on this issue, here's a fix:

Turn this:

```typescript
export * as BagOfThings from './file_with_exports'
```

Into this:

```typescript
import * as BagOfThings from './file_with_exports'
export { BagOfThings }
```

**Comment by penx** [comment]
Confirmed I ran in to this issue and it goes away if I comment out my usage of `export * as`

**Comment by charlespeary** [comment]
I run into this issue as well whenever using `export * as foo from "./foo"` or `export * from "./foo"` syntax.

**Comment by anhpham1509** [comment]
Confirmed the same problems with `export * as something from "./somewhere"`

Also, the type declarations are bundled into one file incorrectly.

**Comment by anhpham1509** [comment]
https://github.com/parcel-bundler/parcel/pull/7315

I found this PR, might be it helps to sort things out.

**Comment by astegmaier** [comment]
I tested, and #7315 doesn't address this issue, unfortunately (although it does fix #7306).

I can confirm the repro - `export * as something from "./somewhere"` causes the issue above. Its because we assume that if `node.exportClause` is defined, it will have an `elements` property.

https://github.com/parcel-bundler/parcel/blob/106939872e15014f45671fa971ad96fee27b2d6d/packages/transformers/typescript-types/src/collect.js#L58-L60

But if you look at the relevant typescript API types, "exportsClause" could be a `NamespaceExport` type, in which case there will be no `elements` property


**ExportDeclaration** ([code](https://github.com/microsoft/TypeScript/blob/0163a624b7d91a29cf24b4d411fd6d52fb5339cb/src/compiler/types.ts#L3087-L3096))
```ts
    export interface ExportDeclaration extends DeclarationStatement, JSDocContainer {
        // ...
        /** Will not be assigned in the case of `export * from "foo";` */
        readonly exportClause?: NamedExportBindings;
        // ...
    }
```
**NamedExportBindings** ([code](https://github.com/microsoft/TypeScript/blob/0163a624b7d91a29cf24b4d411fd6d52fb5339cb/src/compiler/types.ts#L3033-L3036))
```ts
export type NamedExportBindings =
    | NamespaceExport
    | NamedExports
    ;
```
**NamespaceExport** ([code](https://github.com/microsoft/TypeScript/blob/0163a624b7d91a29cf24b4d411fd6d52fb5339cb/src/compiler/types.ts#L3074-L3078))
```ts
    export interface NamespaceExport extends NamedDeclaration {
        readonly kind: SyntaxKind.NamespaceExport;
        readonly parent: ExportDeclaration;
        readonly name: Identifier
    }
```
So the issue is that we don't handle this case, probably because it was released after the initial implementation of `@parcel/transformer-typescript-types` - [in Typescript 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#export--as-ns-syntax) (Feb 2020)

**Comment by code-and-such** [comment]
a reasonable workaround 

```
import * as StringUtils2 from './utils/StringUtils';
export const StringUtils = {
  ...StringUtils2
}
``

**Comment by jy95** [comment]
Still an issue with `"@parcel/transformer-typescript-types": "^2.3.2"` unfortunately

**Comment by oe** [comment]
Still an issue with "@parcel/transformer-typescript-types": "^2.4.0"

**Comment by lucassarcanjo** [comment]
Any updates about this issue? Same error with `"@parcel/transformer-typescript-types": "^2.4.1"`

**Comment by yuuk** [comment]
Same error with "@parcel/transformer-typescript-types": "^2.5.0"

**Comment by Remeic** [comment]
@yuuk have you found some way to solve the issue?

**Comment by yuuk** [comment]
> @yuuk have you found some way to solve the issue?

didn't yet

**Comment by bricejar** [comment]
Same issue here.

**Comment by pedromcunha** [comment]
You can get it working by doing this:

`export { default as StringUtils2 } from './utils/StringUtils'`

**Comment by kkirby** [comment]
Preliminary results show that changing the line `if (node.exportClause) {` to `if (node.exportClause && node.exportClause.elements) {` seems to work as expected. It's correctly exporting all `export * as Module from '...';` I can make a PR if anyone doesn't see anything wrong with that.

**Comment by ivanbanov** [comment]
As bizarre as it can sound, I was getting exact the same error because of the name of my file, in the project I have some utils, and one of them is called `utils/react.ts`, apparently parcel does not like the idea and throws the error 😅 

```
🚨 Build failed.

@parcel/transformer-typescript-types: Got unexpected undefined
```

**Comment by ivanbanov** [comment]
Oh ok, seems like my issue was already reported https://github.com/parcel-bundler/parcel/issues/7669 👌

**Comment by paul-mais** [comment]
After adding tsconfig.json everything works

**Comment by camdub** [comment]
I'm still seeing this issue.

I saw a PR (#8532) from @kkirby that was closed without merging. Is there a reason that fix didn't go through?

**Comment by kkirby** [comment]
@camdub I closed that for the following reason: https://github.com/parcel-bundler/parcel/pull/8532#issuecomment-1289322777

**Comment by camdub** [comment]
Ah, I missed that comment, thanks!

So at this point this is still an open issue?

**Comment by kkirby** [comment]
Yep.

**Comment by bergwerf** [comment]
I'm a bit stumped this issue is still open. I'm essentially forced to either switch to another bundler (maybe Rollup) or remove the use of `import * as ... from ...`, which I just can't.

**Comment by Taelar** [comment]
I confirm this is still an issue, using : 
    "typescript": "^4.9.3"
    "@parcel/transformer-typescript-types": "^2.10.3",
(I tried to upgrade to TS 5.3 but it did not seem to fix the problem)

It seems to happen when exporting types : 
```ts
// MyTypes.ts
export interface Car { }
export interface Bus{ }
```
```ts
// index.ts
export * as Vehicles from './MyTypes.ts'
```
This raises the error `TypeError: node.exportClause.elements is not iterable`

If anyone is interested, here's my workaround. It's far from great but it works in my case : 
```ts
// index.ts
import type { Car, Bus } from './MyTypes.ts'

export type Vehicles= {
  Bus: Bus
  Car: Car
}
```
You can then use it like this :
```ts
const myCar: Vehicles["Car"] = { }
const myBike: Vehicles["Bike"] = { } // TS Error
```

I'd be still very interested in a fix, as I don't like this solution so much 🙏

**Comment by kkirby** [comment]
It seems to me that Parcel being a library bundler isn't a high priority feature. For libraries I've resorted to using `tscp` which is typescript with the ability to monkey patch functionality. Specifically, these two: `@aliser/ts-transformer-append-js-extension` and `typescript-transform-paths`. That way the output had the correct import paths relative to the output project.
