### ISSUE TITLE
building a folder with html entry point causes the plugin autoinstaller to crash

### ISSUE THREAD

**Issue by xlf1024** [parcel-bundler/parcel#5964]
# 🐛 bug report

When running `parcel build ./` so that parcel reads the config from `package.json`, the plugin autoinstaller both fails to locate the existing `package.json` and to create a new one.

Probably related to #5829

## 🎛 Configuration (.babelrc, package.json, cli command)

Parcel: [`2.0.0-nightly.585`](https://www.npmjs.com/package/parcel/v/2.0.0-nightly.585) until [`@nightly` / `2.0.0-nightly.614`](https://www.npmjs.com/package/parcel/v/2.0.0-nightly.614)
nodejs: `15.11.0`
npm: `7.6.0`
OS: WIn10 x64

```json
{
  "name": "parcel_folder_build_error_test",
  "version": "1.0.0",
  "description": "this repository serves as test/demonstration for parcel issue#___. More info there.",
  "main": "./dist/index.html",
  "source": "./src/index.html",
  "scripts": {
    "build": "parcel build ./"
  }
}
```

## 🤔 Expected Behavior

`/src/index.html` should be bundled to `/dist/index.html`. Required plugins should come preinstalled, be installed automatically, or display install instructions.

## 😯 Current Behavior

Parcel tries and fails to autoinstall `@parcel/transformer-posthtml` and fails with the following message. Manually installing `@parcel/transformer-posthtml` through npm does not solve the issue.

```
� Build failed.
Error: Failed to install @parcel/transformer-posthtml: null
Error: Failed to install @parcel/transformer-posthtml: null
    at install (D:\Home\Felix\Programme\web\parcel_folder_build_error_test\node_modules\@parcel\package-manager\lib\installPackage.js:161:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async PromiseQueue._runFn (D:\Home\Felix\Programme\web\parcel_folder_build_error_test\node_modules\@parcel\utils\lib\PromiseQueue.js:108:7)
    at async PromiseQueue._next (D:\Home\Felix\Programme\web\parcel_folder_build_error_test\node_modules\@parcel\utils\lib\PromiseQueue.js:95:5)
 ```

for context: project folder is at `D:\Home\Felix\Programme\web\parcel_folder_build_error_test\` in this case.

## 💁 Possible Solution
*Note: all file locations refer to the files distributed via npm, not the source code in this repository*

### 1. Visible Error Message
`@parcel\package-manager\lib\installPackage.js:161:11` only rethrows the exception, which itself was created in `@parcel\package-manager\lib\Npm.js:103`.
There, `fs.writeFile` is called with the Promise syntax of `fs.promises.writeFile`.

However, this error has been there since at least #2853, which was 2 years ago, while the last know working version is under a month ago.
Also fixing this causes parcel to wipe the projects `package.json`

### 2. Wrong projectRoot
The above code probably should not even be run in this scenario.
It seems like it's meant to create a `package.json` in case none exists, while in this case ther is one.

Further inspection shows that the `packagePath` argument of `Npm.install` is `null`. This argument is set in `@parcel\package-manager\lib\installPackage.js:145`.
This already contains probably wrong information: `from` is `D:\Home\Felix\index`, which is 3 levels up from the actual project root.

This `from` was set in `@parcel\core\lib\loadParcelPlugin.js:132` which exists since #5769 . That merge correlates with the first known broken version on npm. (Last nightly before worked.)

However, I suspect the issue is older, as `options.projectRoot` should probably not be 3 layers above the actual project root. What I found is that the first upwards step seems to be done in `@parcel\utils\lib\getRootDir.js:34`, called from `@parcel\core\lib\resolveOptions.js:93:130`.
Here, `path.parse()` splits
```
"D:\\Home\\Felix\\Programme\\web\\parcel_folder_build_error_test"
````
into 
```js
{
    root: 'D:\\',
    dir: 'D:\\Home\\Felix\\Programme\\web',
    base: 'parcel_folder_build_error_test',
    ext: '',
    name: 'parcel_folder_build_error_test'
}
```
, thus already shaving off the last layer.

However, when creating the new, empty `package.json`, the current working directory is used, thus the existing `package.json` is overwritten.
## 🔦 Context

I was trying to use the targets syntax introduced in #5861, to both bundle the frontend code and convert some data files in two separate targets. In order to build both targets at the same time, I tried to use the `parcel build <folder>` syntax as described in https://v2.parceljs.org/getting-started/configuration/#specifying-entrypoints to run parcel on the `package.json`. I chose this approach instead of calling parcel on individual files because the data target contains multiple independent entry points.

Note however, that while the targets syntax was my motivation to use this, this bug is independent of it and the submitted test case does not make use of it.

## 💻 Code Sample

https://github.com/xlf1024/parcel_folder_build_error_test
`npm install`
`npm run build`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | [`2.0.0-nightly.585`](https://www.npmjs.com/package/parcel/v/2.0.0-nightly.585) until [`@nightly` / `2.0.0-nightly.614`](https://www.npmjs.com/package/parcel/v/2.0.0-nightly.614)
| Node             | `15.11.0`
| npm | `7.6.0`
| Operating System | Win10 x64

Note: I did *not* install Parcel globally, as another project of mine still is on Parcel 1.

**Comment by mischnic** [comment]
> as options.projectRoot should probably not be 3 layers above the actual project root.

So the project root is the first folder containing a (p)npm/yarn lockfile or `.git`.

5829

> 🎛 Configuration

The package.json doesn't contain `dependencies`, so you are using a kind of Yarn/npm workspace setup?

> 💻Code Sample

I ran that on macOS, but it seems to work.

**Comment by xlf1024** [comment]
> The package.json doesn't contain dependencies

I stripped that and the repository links form the code I pasted here to keep it short. The file I tested with does contain `dependencies`, see https://github.com/xlf1024/parcel_folder_build_error_test/blob/main/client/package.json . 

> are using a kind of Yarn/npm workspace setup?

not that I am aware of

> So the project root is the first folder containing a (p)npm/yarn lockfile or .git.

Does "first" refer to "closest" or "topmost"? Because as it turns out,  
`D:\Home\Felix` had a `package_lock.json`, but not a `package.json` (which didn't belong there anyway, but which I also did not expect to be relevant)  
whereas `D:\Home\Felix\Programme\web\parcel_folder_build_error_test\` has both.

Deleting the upper-level `package_lock.json` solved the issue. (so mostly my fault I guess)

However the current behaviour still seems inconsistent. While Parcel looks for the `package.json` in the project root, if none is found there, it is created in the current working directory instead. (Which is different in my case).
Also, this doesn't explain why building an individual file works fine even with the erroneous `package_lock.json` (with the installed plugins stored correctly in the local `package.json`)

Also point 1) still applies. The code for creating the `package.json` is broken; it just usually isn't called.

I updated my test case repository to reflect the case where
1) "project root" has no `package.json` but
2) current working directory hasn't

run `npm install` and `npm run build` in the `./client` subfolder.
I also reproduced the issue using that repository on a debian vm this time.

Note however that I will accept a "Wontfix, user's fault".

**Comment by mischnic** [comment]
> Does "first" refer to "closest" or "topmost"? Because as it turns out,

The closest. So when recursively going through all parent folders, the first one. 

```
.
├── .DS_Store
├── .git
├── client
│	├── package-lock.json
│	├── package.json
│	└── src
│		└── index.js
└── package-lock.josn
$ cd client && yarn parcel build .
```

Both entry root and project root are `.`  in this case (not `./client`)

entry root = the nearest folder containing all entries. so the entry root is never an entry itself
and the project root starts at the entryRoot.

An even worse example:

```
.
├── package-lock.json
├── package.json
└── src
	└── index.js

$ yarn parcel build .
```

results in
```
{
  projectRoot: '~/Desktop/asd',
  entryRoot: '~/Desktop'
}
```

So the entryroot is now outside of the project and the projectRoot is only correct because of this fallback to cwd: https://github.com/parcel-bundler/parcel/blob/98c5902cefe1bba6c890da56f111e4b31b487c64/packages/core/core/src/resolveOptions.js#L53

This is definitely wrong

> The code for creating the package.json is broken; it just usually isn't called.

You're right.

**Comment by xlf1024** [comment]
> Both entry root and project root are . in this case (not ./client)

why so? Is any `package_lock.json` in any parent folder automatically an "entry"?
The `.git` folder does not seem responsible as moving it into the `./client` folder does not solve the issue.

**Comment by mischnic** [comment]
> or is it because of calling parcel build on the folder

Yes, because of that, the parent of `client` is the entryroot.

A workaround would simply be calling `parcel build ./src/index.html` (= what's specified in `"source"`). These two are equivalent
