### ISSUE TITLE
Unknown version 67 of android

### ISSUE THREAD

**Issue by binggg** [parcel-bundler/parcel#6006]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "sandpack-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "parcel index.html --no-source-maps"
  },
  "author": "",
  "license": "ISC",
  "resolutions": {
    "browserslist": "4.0.0"
  },
  "dependencies": {
    "@formily/antd": "^1.3.13",
    "@formily/core": "^1.3.13",
    "@formily/react": "^1.3.13",
    "@formily/react-schema-renderer": "^1.3.13",
    "@govcloud/weapps-generate": "^0.0.2-demo.0",
    "@govcloud/weapps-sdk": "^1.2.12",
    "@types/react": "^16.8.23",
    "antd": "^3.14.1 || ^4.0.0",
    "axios": "^0.21.1",
    "babel-polyfill": "^6.26.0",
    "caniuse-lite": "^1.0.30001202",
    "dayjs": "^1.10.4",
    "lodash.debounce": "^4.0.8",
    "lodash.get": "^4.4.2",
    "lodash.remove": "^4.7.0",
    "lodash.set": "^4.3.2",
    "lodash.throttle": "^4.1.1",
    "react": ">=16.13.1",
    "react-dom": ">=16.8.0",
    "react-error-boundary": "^3.1.1",
    "react-eva": "^1.0.0-alpha.0",
    "react-router-dom": "^5.2.0",
    "regenerator-runtime": "^0.13.7",
    "rxjs": "^6.5.1",
    "sandpack": "^1.0.0",
    "scheduler": ">=0.11.2",
    "smooshpack": "^1.0.0-alpha-14",
    "styled-components": "^4.1.1"
  },
  "devDependencies": {
    "typescript": "^4.2.3"
  }
}
```

## 🤔 Expected Behavior
```bash
parcel index.html --no-source-maps
# should build success
```

## 😯 Current Behavior

```
parcel index.html --no-source-maps

Server running at http://localhost:1234 
⠹ Building index.html...

🚨  /Users/bookerzhao/Projects/lcap/sandpack-test/node_modules/postcss-pxtorem/node_modules/postcss/lib/postcss.js: Unknown version 67 of android
    at Function.select (/usr/local/lib/node_modules/parcel-bundler/node_modules/browserslist/index.js:1103:17)
    at /usr/local/lib/node_modules/parcel-bundler/node_modules/browserslist/index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (/usr/local/lib/node_modules/parcel-bundler/node_modules/browserslist/index.js:318:18)
    at browserslist (/usr/local/lib/node_modules/parcel-bundler/node_modules/browserslist/index.js:444:21)
    at getTargetEngines (/usr/local/lib/node_modules/parcel-bundler/src/utils/getTargetEngines.js:83:26)
    at async getEnvConfig (/usr/local/lib/node_modules/parcel-bundler/src/transforms/babel/env.js:21:25)
    at async getBabelConfig (/usr/local/lib/node_modules/parcel-bundler/src/transforms/babel/config.js:32:19)
    at async babelTransform (/usr/local/lib/node_modules/parcel-bundler/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/usr/local/lib/node_modules/parcel-bundler/src/assets/JSAsset.js:83:5)

```

## 🌍 Your Environment

  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Edge: 89.0.774.45
    Firefox: 76.0.1
    Safari: 14.0.3
  npmGlobalPackages:
    parcel-bundler: 1.12.5

**Comment by mischnic** [comment]
In the past, updating `browserslist` (e.g. bumping the version in the lockfile) has sometimes solved this
