### ISSUE TITLE
serve fails when --hmr-port is supplied 

### ISSUE THREAD

**Issue by abhishiv** [parcel-bundler/parcel#6031]
https://github.com/parcel-bundler/parcel/blob/dccbe72b77828f3fdc1f21438097fbdec26feca0/packages/reporters/dev-server/src/HMRServer.js#L66

```
./node_modules/.bin/parcel serve . --target webapp --log-level verbose --host assets.www.grati.local --hmr-port 3700
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof address === 'object' && address != null)

    at HMRServer.start (/Users/abhishiv/work/gratico/gratico/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:69:27)
```

**Comment by DeMoorJasper** [comment]
Could you share the exact command you used to trigger this?

**Comment by abhishiv** [comment]
hey @DeMoorJasper 

Sure, It was

```
./node_modules/.bin/parcel serve . --target webapp --log-level verbose --host assets.www.grati.local --hmr-port 3700
```

**Comment by mischnic** [comment]
It seems to work for me on the latest nightly.

**Comment by azzamsa** [comment]
I got the similar message even though I don't pass `--hmr-port`.

Sometimes ` rm -rf .parcel-cache dist/` works, sometimes doesn't.
Sometimes the HMR works even though the error message above appears.

```js
> parcel watch 'src/scripts/main.js' --dist-dir 'dist/scripts'

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof address === 'object' && address != null)

    at HMRServer.start (~/projects/foo/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:69:27)
    at Object.report (~/projects/foo/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:106:23)
    at ReporterRunner.report (~/projects/foo/node_modules/@parcel/core/lib/ReporterRunner.js:140:31)
    at async Parcel.watch (~/projects/foo/node_modules/@parcel/core/lib/Parcel.js:571:7)
    at async run (~/projects/foo/node_modules/parcel/lib/cli.js:342:9) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
~/projects/foo/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:148
    this.options.logger.warn({
                        ^

TypeError: Cannot read property 'warn' of undefined
    at WebSocketServer.handleSocketError (~/projects/foo/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:148:25)
    at WebSocketServer.emit (events.js:315:20)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
⠸ Building main.scss...
```

``` json
"@parcel/transformer-sass": "^2.0.0-beta.3.1",
"parcel": "^2.0.0-beta.3.1",
```

``` diff
-        "@parcel/utils": "2.0.0-nightly.680+daece49d",
+      "version": "2.0.0-beta.3.1",
+      "resolved": "https://registry.npmjs.org/parcel/-/parcel-2.0.0-beta.3.1.tgz",
+      "integrity": "sha512-jwNwDM/OILzzBAIMZZ/b+PA5DFQ+4ZTaINliSslyY/ZOfwjjkHMlmMddyj6iogLq+n74LE8pBGn3+V5ej4CH1Q==",
+      "dev": true,
+      "dependencies": {
+        "@parcel/config-default": "2.0.0-beta.3.1",
+        "@parcel/core": "2.0.0-beta.3.1",
+        "@parcel/diagnostic": "2.0.0-beta.3.1",
+        "@parcel/events": "2.0.0-beta.3.1",
+        "@parcel/fs": "2.0.0-beta.3.1",
+        "@parcel/logger": "2.0.0-beta.3.1",
+        "@parcel/package-manager": "2.0.0-beta.3.1",
+        "@parcel/reporter-cli": "2.0.0-beta.3.1",
+        "@parcel/reporter-dev-server": "2.0.0-beta.3.1",
+        "@parcel/utils": "2.0.0-beta.3.1",
```
