### ISSUE TITLE
Bundling `debug` in a node context fails

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#6042]
# 🐛 bug report

Bundling the `debug` package fails in a node context

## 😯 Current Behavior

```
/dist/index.js:687
  return ('colors' in $f66d0ab3840acee6d7b7c0764fc51343$export$inspectOpts) ? Boolean($f66d0ab3840acee6d7b7c0764fc51343$export$inspectOpts.colors) : $f66d0ab3840acee6d7b7c0764fc51343$importAsync$1fcc6a6213263ffd05b3ed55264c47d6$isatty(process.stderr.fd);
                                                                              ^

ReferenceError: $f66d0ab3840acee6d7b7c0764fc51343$importAsync$1fcc6a6213263ffd05b3ed55264c47d6$isatty is not defined
    at Function.$f66d0ab3840acee6d7b7c0764fc51343$var$useColors [as useColors] (dist/index.js:687:79)
    at createDebug (dist/index.js:258:35)
    at Object.<anonymous> (dist/index.js:851:53)
```

## 💁 Possible Solution

`$f66d0ab3840acee6d7b7c0764fc51343$importAsync$1fcc6a6213263ffd05b3ed55264c47d6$isatty`

should have been rewritten to use the inserted `var isatty = require("tty").isatty;` variable

## 🔦 Context

https://github.com/parcel-bundler/parcel/discussions/5944

## 💻 Code Sample

```js
var debug = require("debug");
let handler = debug("foo");
```
```json
{
  "dependencies": {
    "debug": "^4.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.13.10",
    "parcel": "2.0.0-nightly.630"
  },
  "targets": {
    "default": {
      "context": "node",
      "includeNodeModules": true,
      "outputFormat": "commonjs"
    }
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.630

**Comment by devongovett** [comment]
Does it work in the swc version?
