### ISSUE TITLE
[v2-beta.2] Build fails with autoprefixer

### ISSUE THREAD

**Issue by mogelbrod** [parcel-bundler/parcel#6060]
# 🐛 bug report

Parcel v2 builds with CSS chunks fail after enabling autoprefixer in the postcss config.

### Versions (package.json dependencies)
```json
  "dependencies": {
    "autoprefixer": "^10.2.5",
    "parcel": "^2.0.0-beta.2",
    "postcss-modules": "^4.0.0"
  }
```

### postcss config
I've tried using .postcssrc, postcss.config.js and `"postcss": {...}` in package.json, all with the same outcome.
Also tried `"autoprefixer": true` without success.
```json
{
  "modules": true,
  "plugins": {
    "autoprefixer": {}
  }
}
```

### index.html
Added an `animation` CSS property for autoprefixer to prefix.
```html
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        animation: test 3s ease-in-out alternate infinite;
      }
      @keyframes test {
        0% { background-color: #aff; }
        100% { background-color: #faf; }
      }
    </style>
  </head>
  <body>Hello world</body>
</html>
```

## 🤔 Expected Behavior

Running `parcel index.html` should succeed, with the CSS output including prefixed `-webkit-keyframes`.

## 😯 Current Behavior

```
parcel index.html

ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/transformer-postcss: _postcss(...).default.fromJSON is not a function
TypeError: _postcss(...).default.fromJSON is not a function
    at Object.transform (.../cwd/node_modules/@parcel/transformer-postcss/lib/PostCSSTransformer.js:175:38)
    at async Transformation.runTransformer (.../cwd/node_modules/@parcel/core/lib/Transformation.js:830:5)
    at async Transformation.runPipeline (.../cwd/node_modules/@parcel/core/lib/Transformation.js:585:36)
    at async Transformation.runPipelines (.../cwd/node_modules/@parcel/core/lib/Transformation.js:413:40)
    at async Transformation.runPipelines (.../cwd/node_modules/@parcel/core/lib/Transformation.js:444:34)
    at async Transformation.run (.../cwd/node_modules/@parcel/core/lib/Transformation.js:316:19)
    at async Child.handleRequest (.../cwd/node_modules/@parcel/workers/lib/child.js:255:9)
```

Removing the `<style>` block from index.html prevents the build from failing, but is obviously not a solution.
Replacing the inline CSS in the `<style>` block with a `<link href="index.css">` also results in the same error.

## 🔦 Context

I'm trying to use autoprefixer with parcel.

## 💻 Code Sample

https://gist.github.com/mogelbrod/c250d5424dec8368d9f98c3072f6c4d6

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             | 15.3.0
| npm/Yarn         | 6.14.9
| Operating System | Mac OSX 10.15.6 (19G73)

**Comment by mischnic** [comment]
Can you try adding a dependency to `postcss@^8.0.0` to your project?

**Comment by mogelbrod** [comment]
@mischnic: Thanks for the reply!
After installing `postcss@8.2.8` I'm still getting the same error with identical stack trace.

**Comment by mischnic** [comment]
After `yarn add postcss`, it worked for me.
And this also fixes these Yarn warnings:
```
warning " > autoprefixer@10.2.5" has unmet peer dependency "postcss@^8.1.0".
warning "parcel > @parcel/config-default > @parcel/transformer-postcss@2.0.0-beta.2" has unmet peer dependency "postcss@^8.2.1".
warning " > postcss-modules@4.0.0" has unmet peer dependency "postcss@^8.0.0".
warning "postcss-modules > postcss-modules-extract-imports@3.0.0" has unmet peer dependency "postcss@^8.1.0".
warning "postcss-modules > postcss-modules-local-by-default@4.0.0" has unmet peer dependency "postcss@^8.1.0".
warning "postcss-modules > postcss-modules-scope@3.0.0" has unmet peer dependency "postcss@^8.1.0".
warning "postcss-modules > postcss-modules-values@4.0.0" has unmet peer dependency "postcss@^8.1.0".
warning "postcss-modules > postcss-modules-local-by-default > icss-utils@5.1.0" has unmet peer dependency "postcss@^8.1.0".
```

---

npm 7 also works. But it indeed still fails with npm 6.

**Comment by mogelbrod** [comment]
@mischnic Can confirm it works with `npm@7.8.0` after running `rm -rf node_modules package-lock.json` 👍 
Thank you for the help!

**Edit:** I'm getting another error if I replace the contents of the `<style>` tag with the following:
```html
<style>
  @import "./index.css";
</style>
```

### Contents of `index.css` in the same directory
```css
body { color: red; }
```

### Error thrown
```
🚨 Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof v === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof v === 'string')

    at assertString (.../cwd/node_modules/@parcel/scope-hoisting/lib/utils.js:194:25)
    at .../cwd/node_modules/@parcel/scope-hoisting/lib/link.js:212:42
    at enter (.../cwd/node_modules/@parcel/core/lib/Graph.js:558:16)
    at enter (.../cwd/node_modules/@parcel/core/lib/Graph.js:558:16)
    at enter (.../cwd/node_modules/@parcel/core/lib/Graph.js:558:16)
    at walk (.../cwd/node_modules/@parcel/core/lib/Graph.js:393:26)
    at walk (.../cwd/node_modules/@parcel/core/lib/Graph.js:414:22)
    at Graph.dfs (.../cwd/node_modules/@parcel/core/lib/Graph.js:438:12)
    at BundleGraph.traverseBundle (.../cwd/node_modules/@parcel/core/lib/BundleGraph.js:730:24)
    at BundleGraph.traverseAssets (.../cwd/node_modules/@parcel/core/lib/BundleGraph.js:559:17)
```

**Comment by devongovett** [comment]
I think this should be fixed in the latest version.
