### ISSUE TITLE
Deasync dependency requirement | Does not work on windows 10

### ISSUE THREAD

**Issue by gameloch** [parcel-bundler/parcel#6205]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "private": true,
    "mode": "production",
    "scripts": {
        "watch": "npm watch",
        "prod": "npx parcel build app.js -d ./js --public-url /js/"
    },
    "name": "mypackage",
    "version": "1.0",
    "description": "My package.",
    "main": "./index.js",
    "devDependencies": {
        "parcel-bundler": "^1.12.5"
    },
    "dependencies": {
        "es6-promise": "^4.2.8"
}
}
```

## 🤔 Expected Behavior
It must allow the installation and execution of any package, including the parcel-bundler.

## 😯 Current Behavior

https://github.com/abbr/deasync/issues/106

- Prevents package installation: `npm install`
- Prevents installation of the parcel-bundler
- Prevents the execution of the parcel
______________________________________________________________________________________________________________________________________
Requires the installation of node-gyp, Python, Visual Studio and C ++ workload estimated at 3.45GB

## 💁 Possible Solution
Remove the dependency from deasync@0.1.21 or make it optional.

## 🔦 Context

```
npm timing build:link:node_modules/parcel-bundler Completed in 829ms
npm timing build:link:node_modules/purgecss Completed in 837ms
npm timing build:link:node_modules/semver Completed in 839ms
npm timing build:link:node_modules/quote-stream Completed in 852ms
npm timing build:link:node_modules/sha.js Completed in 855ms
npm timing build:link:node_modules/rimraf Completed in 866ms
npm timing build:link:node_modules/svgo Completed in 867ms
npm timing build:link:node_modules/sshpk Completed in 874ms
npm timing build:link:node_modules/uncss Completed in 884ms
npm timing build:link:node_modules/uuid Completed in 891ms
npm timing build:link:node_modules/regjsparser/node_modules/jsesc Completed in 876ms
npm timing build:link:node_modules/regjsparser Completed in 911ms
npm timing build:link:node_modules/js-yaml/node_modules/esprima Completed in 898ms
npm timing build:link:node_modules/static-eval/node_modules/escodegen Completed in 892ms
npm timing build:link:node_modules/jsdom/node_modules/esprima Completed in 904ms
npm timing build:link:node_modules/terser Completed in 943ms
npm timing build:link:node_modules/jsdom/node_modules/escodegen Completed in 929ms
npm timing build:link:node_modules/which Completed in 949ms
npm timing build:link:node_modules/static-eval/node_modules/esprima Completed in 933ms
npm timing build:link Completed in 1001ms
npm info run deasync@0.1.21 install node_modules/deasync node-gyp rebuild
npm info run deasync@0.1.21 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 35481ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 134369ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:365:28)
npm verb stack     at maybeClose (node:internal/child_process:1067:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm verb pkgid deasync@0.1.21
npm verb cwd C:\Users\...
npm verb Windows_NT 10.0.19042
npm verb node v16.0.0
npm verb npm  v7.10.0
npm ERR! code 1
npm ERR! path .\mypackage\node_modules\deasync
npm ERR! command failed
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.0.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find VS - not found
npm ERR! gyp verb find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2017
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
```

## 💻 Code Sample
`npm install`,`npm i --loglevel silly` or` npm run prod`

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.5
| Node             | 7.10.0
| npm/Yarn         | 16.0.0
| Operating System | Windows 10

**Comment by aminya** [comment]
Update to Parcel 2
```
npm install parcel@next
```

**Comment by gameloch** [comment]
Okay, but now I have another problem that didn’t occur in the other version:
Doesn't it recognize require (""), any solution for that?

Helpers.js error

```
var $parcel$global =
  typeof globalThis !== 'undefined'
    ? globalThis
    : typeof self !== 'undefined'
    ? self
    : typeof window !== 'undefined'
    ? window
    : typeof global !== 'undefined'
    ? global
    : {};

function $parcel$interopDefault(a) {
  return a && a.__esModule ? a.default : a;
}

function $parcel$defineInteropFlag(a) {
  Object.defineProperty(a, '__esModule', {value: true});
}

  |> function $parcel$export(e, n, v) {
  |>  Object.defineProperty(e, n, {get: v, enumerable: true});
  |> }

function $parcel$exportWildcard(dest, source) {
  Object.keys(source).forEach(function(key) {
    if (key === 'default' || key === '__esModule') {
      return;
    }

    Object.defineProperty(dest, key, {
      enumerable: true,
      get: function get() {
        return source[key];
      },
    });
  });

  return dest;
}

function $parcel$missingModule(name) {
  var err = new Error("Cannot find module '" + name + "'");
  err.code = 'MODULE_NOT_FOUND';
  throw err;
}

```
![image](https://user-images.githubusercontent.com/35765258/116560683-fe21e000-a8d7-11eb-8488-5175c32f33b9.png)
![image](https://user-images.githubusercontent.com/35765258/116561079-5bb62c80-a8d8-11eb-8bf8-d08763652751.png)

**Comment by mischnic** [comment]
> Helpers.js

I think the sourcemaps are wrong, the error is not actually thrown on that line

**Comment by gameloch** [comment]
Well, this is the only error, it seems to be a fatal error, as it prevents the execution of the remaining code, I am using ES6, but sometimes I use the call of require () in some dependencies like Jquery or the bootstrap css, in the location that use, I can only use require () or import (), because it is not at the beginning of the file.

Example 1
```
window.Promise = require('es6-promise').Promise; 
window.jQuery = window.$ = require("jquery");
```
Example 2
```
import("./loader").then(loader => {
require('bootstrap/dist/css/bootstrap.min.css');
});
```
Exemple 3
```
if($('body').hasClass('myclass')){
require('./my.css');
}
```

**Comment by mischnic** [comment]
These three cases should still work with Parcel 2.

Can you disable javascript sourcemaps in the chrome devtools and post the actual code throwing the error?

**Comment by gameloch** [comment]
I spent the day dealing with it and did what you asked, but this time he said the error was in the host's own name (http://127.0.0.1:xxxx) on line 1, being that line 1 was the` <html>` tag, the browser does not seem to know where this error is, I also have no idea what this error is, javascript is very bad to debug, but as it is being compiled correctly by Parcel, I edited the package and switched to Commonjs and now everything is working fine, this was a big delay for the project.

**Comment by gameloch** [comment]
**One note** 

If you use Parcel this way:
`npx parcel build ./app.js --dist-dir ../assets/js --public-url /assets/js/`

And if you have the "main" column in package.json, parcel will put all the output files in the same folder as the file indicated in the "main" column, which causes a relevant data loss, because it replaces the files and you lose the main file of your package.

I hope someone can solve this problem in future releases.
