### ISSUE TITLE
parcel the HTML demo file with JS  throws the following error

### ISSUE THREAD

**Issue by cherrwer** [parcel-bundler/parcel#6210]
src\js\index.js: function (prevType) {
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
×  src\js\index.js: function (prevType) {
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
    at Object.serialize (v8.js:202:7)
at _default (node_modules\_@babel_core@7.14.0@@babel\core\lib\transformation\util\clone-deep.js:16:30)    
    at normalizeFile (node_modules\_@babel_core@7.14.0@@babel\core\lib\transformation\normalize-file.js:52:36)
    at normalizeFile.next (<anonymous>)
    at run (\node_modules\_@babel_core@7.14.0@@babel\core\lib\transformation\index.js:31:50)
    at run.next (<anonymous>)
    at Function.<anonymous> (node_modules\_@babel_core@7.14.0@@babel\core\lib\transform-ast.js:20:41)
    at Generator.next (<anonymous>)
    at evaluateSync (node_modules\_gensync@1.0.0-beta.2@gensync\index.js:251:28)
    at Function.sync (node_modules\_gensync@1.0.0-beta.2@gensync\index.js:89:14)

**Comment by mischnic** [comment]
Please fill out the issue template.

**Comment by wnk77521** [comment]
function (prevType) {
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
    at Object.serialize (node:v8:260:7)
    at _default (/usr/local/lib/node_modules/parcel-bundler/node_modules/@babel/core/lib/transformation/util/clone-deep.js:22:34)
    at normalizeFile (/usr/local/lib/node_modules/parcel-bundler/node_modules/@babel/core/lib/transformation/normalize-file.js:79:36)
    at normalizeFile.next (<anonymous>)
    at run (/usr/local/lib/node_modules/parcel-bundler/node_modules/@babel/core/lib/transformation/index.js:29:50)
    at run.next (<anonymous>)
    at Function.<anonymous> (/usr/local/lib/node_modules/parcel-bundler/node_modules/@babel/core/lib/transform-ast.js:26:41)
    at Generator.next (<anonymous>)
    at evaluateSync (/usr/local/lib/node_modules/parcel-bundler/node_modules/gensync/index.js:251:28)
    at Function.sync (/usr/local/lib/node_modules/parcel-bundler/node_modules/gensync/index.js:89:14)

**Comment by taofeifanIT** [comment]
I have also encountered this problem. Hava you solved it? How did you solve it

**Comment by cherrwer** [comment]
> I have also encountered this problem. Hava you solved it? How did you solve it

No, this is demo. Now I've given up, and I can't find out which project
