### ISSUE TITLE
@parcel/config-webextension only returns manifest.js and manifest.js.map

### ISSUE THREAD

**Issue by Darhagonable** [parcel-bundler/parcel#6214]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Check the repo in the code sample section

## 🤔 Expected Behavior

I expected the dist folder to contain all the files for the compiled extension and with the structure according the the paths mentioned in the manifest.json file.
Something like this:
![image](https://user-images.githubusercontent.com/14127357/116696727-8f6d8100-a9c2-11eb-9963-205ce3cd4984.png)

## 😯 Current Behavior

This is all that shows up in the dist folder:
![image](https://user-images.githubusercontent.com/14127357/116696600-6947e100-a9c2-11eb-9649-3d98200248db.png)

## 🔦 Context

I have been attempting to create a chrome extension using react with the use of parcel and @parcel/config-webextension but when i run npm/yarn run start or build the only thing showing up in the created dist folder is manifest.js and manifest.js.map.
This mean's i have yet to get my extension running with parcel.

## 💻 Code Sample

https://github.com/Darhagonable/Projectize/tree/parcel-react-ext

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-beta.2
| Node             |v15.3.0
| Yarn         |1.22.10
| Operating System |Windows 10 Version 10.0.19042 Build 19042

**Comment by mischnic** [comment]
You have both Parcel 1 and Parcel 2 as a dependency

>     "parcel": "^2.0.0-beta.2",
>     "parcel-bundler": "^1.12.5"

I'm guessing that you are actually using Parcel 1 when building (because both install the same `parcel` CLI binary)

**Comment by Darhagonable** [comment]
Thanks! I removed the bundler dependency and added the unmet dependencies it complained about (i updated repo) but now it wont build at all. I also deleted node_modules and yarn.lock and ran yarn install again just to make sure nothing had messed up with them.
The error i'm getting:
```
PS E:\repos\Projectize> yarn start
yarn run v1.22.10
$ parcel src/manifest.json --host localhost --target webext-dev --no-cache
DOMException [DataCloneError]: function fn(...args) {
    return new Promise((resolve, reject) => {
      original.call(this, ...args, (err,...<omitted>... } could not be cloned.
    at Worker.postMessage (node:internal/worker:311:23)
    at ThreadsWorker.send (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\threads\ThreadsWorker.js:86:17)
    at Worker.send (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:145:17)
    at Worker.call (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:165:12)
    at E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:133:12
    at new Promise (<anonymous>)
    at Worker.sendSharedReference (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:132:5)
    at E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:122:20
    at Array.map (<anonymous>)
    at Worker.fork (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:121:81)
DOMException [DataCloneError]: function fn(...args) {
    return new Promise((resolve, reject) => {
      original.call(this, ...args, (err,...<omitted>... } could not be cloned.
    at Worker.postMessage (node:internal/worker:311:23)
    at ThreadsWorker.send (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\threads\ThreadsWorker.js:86:17)
    at Worker.send (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:145:17)
    at Worker.call (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:165:12)
    at E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:133:12
    at new Promise (<anonymous>)
    at Worker.sendSharedReference (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:132:5)
    at E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:122:20
    at Array.map (<anonymous>)
    at Worker.fork (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:121:81)
DOMException [DataCloneError]: function fn(...args) {
    return new Promise((resolve, reject) => {
      original.call(this, ...args, (err,...<omitted>... } could not be cloned.
    at Worker.postMessage (node:internal/worker:311:23)
    at ThreadsWorker.send (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\threads\ThreadsWorker.js:86:17)
    at Worker.send (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:145:17)
    at Worker.call (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:165:12)
    at E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:133:12
    at new Promise (<anonymous>)
    at Worker.sendSharedReference (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:132:5)
    at E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:122:20
    at Array.map (<anonymous>)
    at Worker.fork (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:121:81)
@parcel/reporter-dev-server: Trying to create the devserver but it already exists.
DOMException [DataCloneError]: function fn(...args) {
    return new Promise((resolve, reject) => {
      original.call(this, ...args, (err,...<omitted>... } could not be cloned.
    at Worker.postMessage (node:internal/worker:311:23)
    at ThreadsWorker.send (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\threads\ThreadsWorker.js:86:17)
    at Worker.send (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:145:17)
    at Worker.call (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:165:12)
    at E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:133:12
    at new Promise (<anonymous>)
    at Worker.sendSharedReference (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:132:5)
    at E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:122:20
    at Array.map (<anonymous>)
    at Worker.fork (E:\repos\Projectize\node_modules\parcel\node_modules\@parcel\workers\lib\Worker.js:121:81)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The yarnpkg page they ask me to visit sadly doesn't help much.
Any idea  what's going on here?

**Comment by mischnic** [comment]
I think this happens because some parcel packages are installed multiple times (and in different versions).

This works:
```
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.13.16",
    "@parcel/config-webextension": "2.0.0-beta.2",
    "@parcel/core": "2.0.0-beta.2",
    "parcel": "2.0.0-beta.2",
    "postcss": "^8.2.13"
  }
```

**Comment by Darhagonable** [comment]
Thanks! now it builds something :D 
hmm not fully though.
The stuff for the options page is no where to be seen. Also `.parcel-cache` folder is still being created even though I'm using `--no-cache`. :thinking:

**Comment by mischnic** [comment]
Even with --no-cache, the folder ist still used for IPC with the workers

**Comment by Darhagonable** [comment]
Oh, I see.
Any idea what is up with the options folder though?
