### ISSUE TITLE
Error: [(...previousDevDepRequests.entries(...))].filter(...).flatMap is not a function

### ISSUE THREAD

**Issue by TheNathanBlake** [parcel-bundler/parcel#6259]
# 🐛 bug report

In trying to run Parcel using `parcel src/index.html -p 3000` in a React project, I run into the following error and stack trace:
```
ℹ️ Server running at http://localhost:3000
🚨 Build failed.
Error: [(...previousDevDepRequests.entries(...))].filter(...).flatMap is not a function
TypeError: [(...previousDevDepRequests.entries(...))].filter(...).flatMap is not a function
    at Object.run (/Users/nathan/iYOTAH/external/tracerBullets/material-kit-react-parcel/node_modules/@parcel/core/lib/requests/AssetRequest.js:94:122)
```

## 🎛 Configuration (.babelrc, package.json, cli command)
No defined .babelrc file (default behavior)
package.json:
```js
{
  "scripts": {
    "start": "parcel src/index.html -p 3000",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "dependencies": {
    "@auth0/auth0-react": "^1.4.0",
    "@emotion/react": "^11.1.5",
    "@emotion/styled": "^11.1.5",
    "@material-ui/core": "^5.0.0-alpha.28",
    "@material-ui/icons": "^5.0.0-alpha.28",
    "@material-ui/styles": "^4.10.0",
    "amazon-cognito-identity-js": "^4.6.1",
    "auth0": "^2.34.2",
    "aws-amplify": "^3.4.0",
    "axios": "^0.21.1",
    "chart.js": "^2.9.4",
    "clsx": "^1.1.1",
    "formik": "^2.1.5",
    "history": "^5.0.0",
    "install": "^0.13.0",
    "lodash": "^4.17.19",
    "moment": "^2.27.0",
    "node-sass": "^5.0.0",
    "npm": "^7.7.4",
    "nprogress": "^0.2.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-chartjs-2": "^2.10.0",
    "react-dom": "^17.0.2",
    "react-feather": "^2.0.8",
    "react-grid-layout": "^1.2.4",
    "react-helmet": "^6.1.0",
    "react-perfect-scrollbar": "^1.5.8",
    "react-query": "^3.13.12",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.0",
    "src": "^1.1.2",
    "uuid": "^8.3.0",
    "yup": "^0.29.3"
  },
  "devDependencies": {
    "@parcel/transformer-image": "^2.0.0-beta.2",
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "eslint": "^7.24.0",
    "eslint-config-airbnb": "^18.2.1",
    "parcel": "^2.0.0-beta.2"
  }
}
```

## 🤔 Expected Behavior

The app should build and the UI should be hosted on port 3000

## 😯 Current Behavior

The error as described occurs, and the app hangs until terminated.

```
ℹ️ Server running at http://localhost:3000
🚨 Build failed.
Error: [(...previousDevDepRequests.entries(...))].filter(...).flatMap is not a function
TypeError: [(...previousDevDepRequests.entries(...))].filter(...).flatMap is not a function
    at Object.run (/Users/nathan/iYOTAH/external/tracerBullets/material-kit-react-parcel/node_modules/@parcel/core/lib/requests/AssetRequest.js:94:122)
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.5
| Node             | 10.16.0
| npm/Yarn         | 7.10.0
| Operating System | macOS Catalina v10.15.7

**Comment by mischnic** [comment]
> Node 10.16.0

Node 10 is EOL. Parcel requires at least Node 12: https://github.com/parcel-bundler/parcel/blob/ba57b6501632703d68923b214b0c0f6d47a34b1f/packages/core/parcel/package.json#L21
