### ISSUE TITLE
When trying to run Parcel 2 with Sass, it crashes while downloading the @parcel/transformer-sass package.

### ISSUE THREAD

**Issue by devmoksh** [parcel-bundler/parcel#6280]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

command line:
```sh
$ parcel ./index.html
```

## 🤔 Expected Behavior

It should build the SCSS code and just run.

## 😯 Current Behavior

It tries to build it and gives this error

```ℹ Server running at http://localhost:1234
× Build failed.
Error: Failed to install @parcel/transformer-sass: Yarn failed to install modules:Child process failed
Error: Failed to install @parcel/transformer-sass: Yarn failed to install modules:Child process failed
    at install (C:\Users\harpreet\AppData\Roaming\npm\node_modules\parcel\node_modules\@parcel\package-manager\lib\installPackage.js:171:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## 💁 Possible Solution

npm parcel-bundler package works.

## 🔦 Context

I have to build SCSS myself and that is not very helpful. I would like parcel to do it with no problems on my end.

## 💻 Code Sample

https://github.com/devmoksh/parcel2-sass-bug the directory I am working with.

## 🌍 Your Environment

| Software              | Version(s)          |
| -------------------| ----------------|
| Parcel                   | 2.0.0-beta.2  |
| Node                    | v12.6.3         |
| npm/Yarn             |6.14.4           |
| Operating System |Windows 10 |

**Comment by Fizzymatt** [comment]
I'm not sure whether your problem is exactly the same as mine, but I had a similar issue and found that specifying the transformer package as a dependency in package.json seemed to help.

E.g:

`"dependencies": {
    "@parcel/transformer-sass": "^2.0.0-beta.2"
  }`

Might be worth a shot at least :)

**Comment by Dylansc22** [comment]
Same error and solution worked for me! In my package.json, I moved 
`"@parcel/transformer-sass": "^2.0.0-beta.2",` from the `devDependencies` and into `dependencies` and my build command worked! Thank you!


For completeness the error was:
```
Server running at http://localhost:1234
🚨 Build failed.
@parcel/package-manager: Could not find module "@parcel/transformer-sass", but it was listed in package.json. Run your package manager first.
/home/dylan/1-apps/package.json:15:5
  14 |   "devDependencies": {
> 15 |     "@parcel/transformer-sass": "^2.0.0-beta.2",
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ Defined here, but not installed
  16 |     "eslint": "^7.20.0",
  17 |     "eslint-config-airbnb-base": "^14.2.1",
  ```
  
  My dependencies in my package.json file (after i made the change):
  ```
  "devDependencies": {
    "eslint": "^7.20.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.3.1",
    "nodemon": "^2.0.7",
    "parcel-bundler": "^1.12.5",
    "prettier": "^2.2.1",
    "sass": "^1.32.8"
  },
  "dependencies": {
    "@parcel/transformer-sass": "^2.0.0-beta.2",
    "@turf/turf": "^6.3.0",
    "here-js-api": "^2.0.0",
    "mapbox-gl": "^2.1.1",
    "src": "^1.1.2"
  }
  ```

**Comment by dioptre** [comment]
This is very much broken for me in **pnp** mode of yarn berry - and devDeps or Deps is broken (the solution doesn't work for me).

**Comment by richard-jones** [comment]
The solution doesn't work for me either, though I'm getting a slightly different error:

```
Error: Failed to install @parcel/transformer-sass: Callback must be a function. Received undefined

  Error: Failed to install @parcel/transformer-sass: Callback must be a function. Received undefined
  at install (/home/richard/Code/External/edges2/node_modules/@parcel/package-manager/lib/installPackage.js:131:11)
  at processTicksAndRejections (node:internal/process/task_queues:94:5)
  at async PromiseQueue._runFn (/home/richard/Code/External/edges2/node_modules/@parcel/utils/lib/PromiseQueue.js:88:7)
  at async PromiseQueue._next (/home/richard/Code/External/edges2/node_modules/@parcel/utils/lib/PromiseQueue.js:75:5)
```

in `package.json` I have the dependencies:

```
"devDependencies": {
    "@babel/core": "^7.15.5",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "@parcel/transformer-sass": "^2.0.0-rc.0",
    "parcel": "latest",
    "sass": "^1.39.2"
  },
  "dependencies": {
    "@parcel/transformer-sass": "^2.0.0-rc.0",
    "@babel/runtime-corejs2": "^7.15.4",
    "@swc/helpers": "^0.2.13",
    "jquery": "^3.6.0"
  }
```

Worth also noting that the scss I have compiles fine when I run the site with `parcel serve`

**Comment by richard-jones** [comment]
A little more information from here:

* running `parcel build sass/all.scss` gives

```
> edges@2.0.0-SNAPSHOT build-styles
> parcel build sass/all.scss

✨ Built in 320ms
```

which appears to have worked, but in fact nothing is output in the `dist` directory, and no errors are generated

* Setting a `target` called `styles` with `source: sass/all.scss` generates the ` Failed to install @parcel/transformer-sass:` error above.  This is run with `parcel build --target styles`

* Running the application with `parcel serve views/demo.html` works as expected, where the scss is included in the `demo.html` file as `<link rel="stylesheet" href="../sass/all.scss" />`

**Comment by moritzmhmk** [comment]
I found the issue to be a `yarn.lock` file present in a parent directory when using npm in the actual project directory.

To reproduce: setup parcel with npm in `~/test_project` and create a yarn.lock with `touch ~/yarn.lock`.

**Comment by BenedictLang** [comment]
Same for me. Also the `Callback must be a function` error. Unfortunately it worked before but im not  sure at which point it stopped working as I only worked on my PC where it compiles properly with the same `package.json`

**Comment by Arsen-Sultanov** [comment]
![image](https://user-images.githubusercontent.com/20321278/146802337-6a698f4d-384d-4a25-a4ac-c3172fc7b57f.png)
node: v16.13.1

**Comment by schpet** [comment]
@moritzmhmk 

> I found the issue to be a yarn.lock file present in a parent directory when using npm in the actual project directory.

thank you so much for posting this comment – been slamming my head against my keyboard for far too long before reading that, you really helped me out.

**Comment by GuyRimel** [comment]
I was getting the following error in the terminal:
`× Build failed.

@parcel/package-manager: Could not find module "@parcel/transformer-sass" satisfying 2.0.0-rc.0.
    23 |   "devDependencies": {
  > 24 |     "@parcel/transformer-sass": "^2.0.0-rc.0"
  >    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ Found this conflicting local requirement.     
    25 |   }
    26 | }`

what fixed it for me was reinstalling parcel globally, then again as a dev-dependency, so:
`npm install -g parcel`

then:
`npm install --save-dev parcel`

kudos @moritzmhmk for mentioning the "parent vs. actual project directory".

Hope this helps somebody!
