### ISSUE TITLE
New Worker logic destroys Windows paths

### ISSUE THREAD

**Issue by Jengamon** [parcel-bundler/parcel#6340]
# 🐛 bug report

I am unable to run anything from 2.0.0-beta.3 and up due to the new @parcel/workers resolver logic that somehow deletes Windows's path separators.

## 🎛 Configuration (.babelrc, package.json, cli command)

I don't believe this is relevant to the issue, but if asked, will provide.

## 🤔 Expected Behavior

Windows path separators should be gracefully handled and remain in strings when used.

## 😯 Current Behavior

Windows path separators are deleted, so I get this error when building or serving (and parcel never stops, so I have to restart the shell everytime):

```
@parcel/workers: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js
Rejected candidate: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js
Rejected candidate: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js.js
Rejected candidate: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js.json
Rejected candidate: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js.node

Require stack:
- internal/preload
Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js
Rejected candidate: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js
Rejected candidate: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js.js
Rejected candidate: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js.json
Rejected candidate: D:DocumentsProjectsHTML5FGDwH5JSBasicHTML5.pnp.js.node

Require stack:
- internal/preload
    at internalTools_makeError (D:\Documents\Projects\HTML5\FGDwH5JS\BasicHTML5\.pnp.js:13956:34)
    at resolveUnqualified (D:\Documents\Projects\HTML5\FGDwH5JS\BasicHTML5\.pnp.js:14995:13)
    at resolveRequest (D:\Documents\Projects\HTML5\FGDwH5JS\BasicHTML5\.pnp.js:15019:14)
    at Object.resolveRequest (D:\Documents\Projects\HTML5\FGDwH5JS\BasicHTML5\.pnp.js:15091:26)
    at Function.external_module_.Module._resolveFilename 
(D:\Documents\Projects\HTML5\FGDwH5JS\BasicHTML5\.pnp.js:14189:34)
    at Function.external_module_.Module._load 
(D:\Documents\Projects\HTML5\FGDwH5JS\BasicHTML5\.pnp.js:14054:48)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1217:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:449:5)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:122:5)
```

## 💁 Possible Solution

Change the logic [here](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/workers/src/Worker.js#L67-L78) to support Windows's path separators. I can look into how exactly to do this a bit later.

## 🔦 Context

I can't do anything with Parcel until this issue is resolved (unless I downgrade to beta.2 which has a Sass reloading issue).

## 💻 Code Sample

Running the resolver on a Windows path will show the error very clearly:

```js
let doop = "\\Users\\jaggern\\this\\is\\a\\Windows\\Path";

let opts = [''];
let quote = false;
for (let c of doop.match(/\\?.|^$/g)) {
	if (c === '"') {
	  quote = !quote;
	} else if (!quote && c === ' ') {
	  opts.push('');
	} else {
	  opts[opts.length - 1] += c.replace(/\\(.)/, '$1');
	}
}

console.log(opts);
```

Running this on Node will result in printing `[ 'UsersjaggernthisisaWindowsPath' ]` when it should print `[ '\\Users\\jaggern\\this\\is\\a\\Windows\\Path' ]`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3 |
| Node             | 14.15.5 |
| Yarn         | 2.14.x |
| Operating System | Window 10 |

**Comment by Jengamon** [comment]
Changing the regex from `/\\?.|^$/g` to `/.|^$/g` seems to solve the problem. I'll quickly make a pull request.
