### ISSUE TITLE
Vue with styles: `falsy value: (0, _assert().default)(typeof assetId === 'string')`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#6374]
# 🐛 bug report

If a vue component contains a `<style>` sheet, packaging fails with this error message:

## 😯 Current Behavior

```
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

    at ScopeHoistingPackager.resolveSymbol (.../node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:685:27)
    at ScopeHoistingPackager.buildReplacements (.../node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:594:27)
    at ScopeHoistingPackager.buildAsset (.../node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:414:39)
    at ScopeHoistingPackager.visitAsset (.../node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:369:17)
    at .../node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:464:54
    at String.replace (<anonymous>)
    at ScopeHoistingPackager.buildAsset (.../node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:433:17)
    at ScopeHoistingPackager.visitAsset (.../node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:369:17)
    at .../node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:204:40
```

## 💻 Code Sample

```html
<!DOCTYPE html>´
<div id="app"></div>
<script src="./application.js"></script>
```

```js
import { createApp } from "vue";
import App from "./App.vue";

const app = createApp(App);
app.mount("#app");
```

```html
<template>
  <h1>Hello ABC</h1>
</template>

<style scoped>
h1 {
  color: red;
}
</style>
```

## Context

Reported by @kubenstein in https://github.com/kubenstein/parcel-bundle-file-size-reproduction-repo

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.688

**Comment by devongovett** [comment]
Possibly fixed by #6489?
