### ISSUE TITLE
Building web extension fails 

### ISSUE THREAD

**Issue by tomas-hartman** [parcel-bundler/parcel#6416]
# 🐛 bug report

When I try to bundle my web-extension, build fails with following message:

```
@parcel/transformer-js: Could not resolve module "__my_extension__/node_modules/@parcel/transformer-js/native" from "__my_extension__/node_modules/@parcel/transformer-js/lib/JSTransformer.js"
Error: Could not resolve module "__my_extension__/node_modules/@parcel/transformer-js/native" from "__my_extension__/node_modules/@parcel/transformer-js/lib/JSTransformer.js"
    at NodeResolverSync.resolve (__my_extension__/node_modules/@parcel/package-manager/lib/NodeResolverSync.js:44:15)
    at NodePackageManager.resolveSync (__my_extension__/node_modules/@parcel/package-manager/lib/NodePackageManager.js:358:36)
    at NodePackageManager.requireSync (__my_extension__/node_modules/@parcel/package-manager/lib/NodePackageManager.js:177:14)
    at Module.m.require (__my_extension__/node_modules/@parcel/package-manager/lib/NodePackageManager.js:198:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at _native (__my_extension__/node_modules/@parcel/transformer-js/lib/JSTransformer.js:29:16)
    at Object.transform (__my_extension__/node_modules/@parcel/transformer-js/lib/JSTransformer.js:244:85)
    at Transformation.runTransformer (__my_extension__/node_modules/@parcel/core/lib/Transformation.js:821:23)
    at async Transformation.runPipeline (__my_extension__/node_modules/@parcel/core/lib/Transformation.js:577:36)
    at async Transformation.runPipelines (__my_extension__/node_modules/@parcel/core/lib/Transformation.js:426:40)
```

This happens because `transformer-js/native` does not exist.

## 🎛 Configuration (.babelrc, package.json, cli command)

__cmd__

```sh
parcel build src/manifest.json --dist-dir dist/test --no-content-hash --no-source-maps --no-cache"
```

> or:

```sh
parcel src/manifest.json --dist-dir dist/test"
```

__.parcelrc__

```json
{
 	"extends": "@parcel/config-webextension"
}
```

__babel.config.js__

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'entry',
        targets: {
          esmodules: true,
        },
      },
    ],
    '@babel/preset-react',
  ],
};
```

## 🤔 Expected Behavior

Build does not fail.

## 😯 Current Behavior

It fails with the error above.

## 💁 Possible Solution

Perhaps include `native` referred in `JSTransformer.js#L29.`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^2.0.0-beta.3.1
| @parcel/config-webextension  |  ^2.0.0-nightly.2220
| @parcel/transformer-webextension           |  ^2.0.0-nightly.2220
| @parcel/transformer-js           |  default + also ^2.0.0-beta.3.1
| Node             |  v14.7.0
| npm/Yarn         |  7.5.6
| Operating System | macOS 11.4

**Comment by tomas-hartman** [comment]
After updating all dependencies to `@next` (beta.3.1), I made it work. Closing this issue.
