### ISSUE TITLE
In netlify deploy, parcel build command fails with unexpected token error

### ISSUE THREAD

**Issue by Ananthakr** [parcel-bundler/parcel#6466]
# 🐛 bug report

Netlify deploy fails with Unexpected token at `node_modules/@parcel/fs/lib/NodeFS.js:237`. 

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "ananthakumar",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.html",
  "scripts": {
    "dev": "parcel index.html",
    "watch": "parcel watch index.html",
    "build": "parcel build index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "ananthakr",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {
    "cssnano": "^5.0.6",
    "parcel": "^2.0.0-beta.3.1",
    "postcss": "^8.3.4"
  }
}
```

## 🤔 Expected Behavior

Build Should have completed and deployed at netlify

## 😯 Current Behavior

```
Executing user command: npm run build
3:34:55 PM: > ananthakumar@1.0.0 build /opt/build/repo
3:34:55 PM: > parcel build index.html
3:34:55 PM: /opt/build/repo/node_modules/@parcel/fs/lib/NodeFS.js:237
3:34:55 PM: } catch {//
3:34:55 PM:         ^
3:34:55 PM: SyntaxError: Unexpected token {
3:34:55 PM:     at NativeCompileCache._moduleCompile (/opt/build/repo/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
3:34:55 PM:     at Module._compile (/opt/build/repo/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
3:34:55 PM:     at Object.Module._extensions..js (module.js:664:10)
3:34:55 PM:     at Module.load (module.js:566:32)
3:34:55 PM:     at tryModuleLoad (module.js:506:12)
3:34:55 PM:     at Function.Module._load (module.js:498:3)
3:34:55 PM:     at Module.require (module.js:597:17)
3:34:55 PM:     at require (/opt/build/repo/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
3:34:55 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/@parcel/fs/lib/index.js:21:15)
3:34:55 PM:     at Module._compile (/opt/build/repo/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
3:34:55 PM: npm
3:34:55 PM:  ERR!
3:34:55 PM: code
3:34:55 PM:  ELIFECYCLE
3:34:55 PM: npm
3:34:55 PM: ERR! errno 1
3:34:55 PM: npm
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1
| Node             | v8.17.0
| npm         | v6.13.4
| Operating System | Linux

**Comment by mischnic** [comment]
> Node v8.17.0

We only support Node 12 and newer: https://github.com/parcel-bundler/parcel/blob/e9c4ebb141698b1e7a06a1bd6f71e39d09cffaf5/packages/core/parcel/package.json#L20-L22

**Comment by Ananthakr** [comment]
Got it. Thanks :)
