### ISSUE TITLE
Parcel messes up the cache and does `Error: Got unexpected undefined` until cleaning the cache - unsure what triggers it

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6505]
# 🐛 bug report

When
a) Having a `babel.config.js`
and 
b) removing and re-adding the current working directory

parcel messes up it's cache and will no longer run without cleaning the cache

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip

## 🤔 Expected Behavior

Parcel invalidates the cache because it is inconsistent and rebuilds it.

## 😯 Current Behavior

Parcel won't run again until the cache is deleted.

```
Error: Got unexpected undefined
    at nullthrows (/private/tmp/parcel-infinity-loops/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/RequestTracker.js:252:44)
    at loadRequestGraph (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/RequestTracker.js:856:18)
    at async Function.init (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/RequestTracker.js:820:17)
    at async Parcel._init (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/Parcel.js:460:50)
    at async Parcel.watch (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/Parcel.js:529:7)
    at async run (/private/tmp/parcel-infinity-loops/node_modules/parcel/lib/cli.js:342:9) {
  framesToPop: 1
}
```

## 💁 Possible Solution

Invalidate cache if it's invalid (lol)

## 🔦 Context

This issue popped up every now and then and I just cleaned cache but now I finally found out how to reproduce it. It's been happing since pre SWC.

## 💻 Code Sample

[parcel-unexpected-undefined.zip](https://github.com/parcel-bundler/parcel/files/6697010/parcel-unexpected-undefined.zip)

How to reproduce:
go unzip file and go into folder in two terminal windows

Window 1:
```
npm install
cd src
npm run serve
```

Now switch window:
Window 2 (cwd is the parent directory of src):
```
git add src
git stash
git stash pop
```

Go back to window 1:
press ctrl+c
```
npm run serve
```

you will get this error:
```
daniel@Daniels-MacBook-Pro src % npm run serve
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:92:19)
    at new <anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:58:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:48:30)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

now continue with this:
```
cd ../src/
npm run serve
```

et voilà:

```
daniel@Daniels-MacBook-Pro src % npm run serve

> serve
> parcel serve --port 1234 src/main.ts

Error: Got unexpected undefined
    at nullthrows (/private/tmp/parcel-unexpected-undefined/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/RequestTracker.js:252:44)
    at loadRequestGraph (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/RequestTracker.js:856:18)
    at async Function.init (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/RequestTracker.js:820:17)
    at async Parcel._init (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/Parcel.js:460:50)
    at async Parcel.watch (/private/tmp/parcel-unexpected-undefined/node_modules/@parcel/core/lib/Parcel.js:529:7)
    at async run (/private/tmp/parcel-unexpected-undefined/node_modules/parcel/lib/cli.js:342:9) {
  framesToPop: 1
}

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.729+e63235f3|
| Node             |v16.3.0|
| npm/Yarn         |npm 7.15.1|
| Operating System |macOS 10.15.7 (19H1217)|

**Comment by mischnic** [comment]
I'm inclined to say that removing the cwd of a running process isn't really "supported"...

**Comment by danieltroger** [comment]
> I'm inclined to say that removing the cwd of a running process isn't really "supported"...

It happens when you're using git. I have this in my gitconfig
```
pull.rebase=true
rebase.autostash=true
```

So imagine this: I have created a new folder containing a parcel entry point, have added and committed it.
Now before pushing I run `git pull`.

That's all it needs as I understand it. Because git will stash the changes before rebasing which removes the CWD.

But ok, maybe removing the cwd of a running process shouldn't be supported*, but **all future processes shouldn't crash** because git did it - imo. This can really confuse newbies who don't know they have to delete `.parcel-cache`.

Also I don't think removing the CWD messes up the cache but rather running `parcel serve` in a not existing CWD, which could easily be avoided by a check if the CWD exists or by doing the js equivalent of `cd $PWD`.

*: the process does notice it tho and write an error message that the file has been removed, so it could simply watch for it's recreation

**Comment by danieltroger** [comment]
This also happens randomly without removing the CWD.

I was, in v732, changing the target from `last 1 firefox versions` to `last 10 firefox versions` to `ios 13.4` and got this:

```
Error: Got unexpected undefined
    at nullthrows (/private/tmp/parcel-infinity-loops/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/RequestTracker.js:252:44)
    at loadRequestGraph (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/RequestTracker.js:856:18)
    at async Function.init (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/RequestTracker.js:820:17)
    at async Parcel._init (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/Parcel.js:460:50)
    at async Parcel.run (/private/tmp/parcel-infinity-loops/node_modules/@parcel/core/lib/Parcel.js:480:7)
    at async run (/private/tmp/parcel-infinity-loops/node_modules/parcel/lib/cli.js:367:7) {
  framesToPop: 1
}
```

**Comment by danieltroger** [comment]
@mischnic Here's an alternative way to reproduce 😜

1. Download https://github.com/parcel-bundler/parcel/files/6708998/parcel-weird-transformations.zip
2. Unzip
3. `npm install`
4. `npm run build`
5. edit target in package.json to `last 1 firefox versions`
6. `npm run build`
7. edit target in package.json to `last 10 firefox versions`
8. `npm run build`

-> 
```
daniel@Daniels-MacBook-Pro parcel-weird-transformations % npm run build    

> build
> parcel build src/main.ts --log-level verbose --detailed-report 100 --target modern

Error: Got unexpected undefined
    at nullthrows (/private/tmp/parcel-weird-transformations/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/private/tmp/parcel-weird-transformations/node_modules/@parcel/core/lib/RequestTracker.js:252:44)
    at loadRequestGraph (/private/tmp/parcel-weird-transformations/node_modules/@parcel/core/lib/RequestTracker.js:856:18)
    at async Function.init (/private/tmp/parcel-weird-transformations/node_modules/@parcel/core/lib/RequestTracker.js:820:17)
    at async Parcel._init (/private/tmp/parcel-weird-transformations/node_modules/@parcel/core/lib/Parcel.js:460:50)
    at async Parcel.run (/private/tmp/parcel-weird-transformations/node_modules/@parcel/core/lib/Parcel.js:480:7)
    at async run (/private/tmp/parcel-weird-transformations/node_modules/parcel/lib/cli.js:367:7) {
  framesToPop: 1
}
```

**Comment by aminya** [comment]
I get this error often when Parcel fails to build successfully or one of the packages throws an error (e.g. sass-transformer). The expected behavior is that Parcel "must" invalidate the cache and clean the dist directory. But it instead throws this error:

```js

Error: Got unexpected undefined
    at nullthrows (C:\website\node_modules\.pnpm\nullthrows@1.1.1\node_modules\nullthrows\nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (C:\website\node_modules\.pnpm\@parcel+core@2.0.0-nightly.716\node_modules\@parcel\core\lib\RequestTracker.js:252:44)
    at loadRequestGraph (C:\website\node_modules\.pnpm\@parcel+core@2.0.0-nightly.716\node_modules\@parcel\core\lib\RequestTracker.js:856:18)
    at async Function.init (C:\website\node_modules\.pnpm\@parcel+core@2.0.0-nightly.716\node_modules\@parcel\core\lib\RequestTracker.js:820:17)
    at async Parcel._init (C:\website\node_modules\.pnpm\@parcel+core@2.0.0-nightly.716\node_modules\@parcel\core\lib\Parcel.js:460:50)
    at async Parcel.watch (C:\website\node_modules\.pnpm\@parcel+core@2.0.0-nightly.716\node_modules\@parcel\core\lib\Parcel.js:529:7)
    at async run (C:\website\node_modules\.pnpm\parcel@2.0.0-nightly.716\node_modules\parcel\lib\cli.js:342:9) {
  framesToPop: 1
```

I need to manually do the above to fix the issue.

**Comment by mischnic** [comment]
I can reproduce https://github.com/parcel-bundler/parcel/issues/6505#issuecomment-867594953 locally

@aminya Can you share an example and instructions how to trigger the error reliably in your case? I'm guessing you have some JS config file?

**Comment by aminya** [comment]
I can't reproduce it in a minimal example. It happens in a big project. But this is the kind of thing I do in my project. If my sass file has an error, and I stop the dev server and run build later, it throws that error.
[parcel-bug-test.zip](https://github.com/parcel-bundler/parcel/files/6716248/parcel-bug-test.zip)

Somehow similar to #5191, but on a recent version.

**Comment by devongovett** [comment]
I think it was because we never removed the node id from the `unpredictableNodeIds` set when the node was removed from the graph. https://github.com/parcel-bundler/parcel/pull/6541/commits/3a8e49b4c34d491ee20dd1a50ef96a6f8feaece0 fixes it for me at least in @danieltroger's example.
