### ISSUE TITLE
Error running 'serve mode'  in a project that imports an HTML file as a string

### ISSUE THREAD

**Issue by drachehavoc** [parcel-bundler/parcel#6508]
# 🐛 bug report

`./src/index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script type="module" src="./main.ts"></script>
</body>
</html>
```

`./src/main.ts`
```typescript
import htmlAsString from "bundle-text:./test.html";
console.log(htmlAsString);
```

`./src/test.html`
```html
<link href="./test.scss">
<div>TEST</div>
```

`./src/test.scss`
```scss
.z {
    &.x {
        color: red;
    }
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`

```js
{
  "name": "project-name",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "bld": "parcel build ./src/index.html --dist-dir=./dist",
    "dev": "parcel serve ./src/index.html --dist-dir=./dist-dev",
  },
  "devDependencies": {
    "@parcel/transformer-inline-string": "^2.0.0-nightly.733",
    "@parcel/transformer-sass": "^2.0.0-nightly.733",
    "http-server": "^0.12.3",
    "parcel": "^2.0.0-nightly.731"
  }
}```

`cli command`
```bash
npm run dev
```

## 🤔 Expected Behavior

I expect `console.log` to print the parsed HTML file as a string.
something like the below:

```html
<link href="/test.1b839af6.css"><div>TEST</div>
```

## 😯 Current Behavior

```bash
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(!this.bundle.hasAsset(resolved))

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(!this.bundle.hasAsset(resolved))

    at /home/.../node_modules/@parcel/packager-js/lib/DevPackager.js:123:33
    at /home/.../node_modules/@parcel/core/lib/Graph.js:538:16
    at /home/.../node_modules/@parcel/core/lib/Graph.js:538:16
    at walk (/home/.../node_modules/@parcel/core/lib/Graph.js:403:26)
    at walk (/home/.../node_modules/@parcel/core/lib/Graph.js:425:22)
    at walk (/home/.../node_modules/@parcel/core/lib/Graph.js:425:22)
    at ContentGraph.dfs (/home/.../node_modules/@parcel/core/lib/Graph.js:451:12)
    at BundleGraph.traverseBundle (/home/.../node_modules/@parcel/core/lib/BundleGraph.js:773:24)
    at NamedBundle.traverse (/home/.../node_modules/@parcel/core/lib/public/Bundle.js:241:54)
    at DevPackager.package (/home/.../node_modules/@parcel/packager-js/lib/DevPackager.js:114:17)
/home/.../dist-dev/index.HASH_REF_4d2fceada2b0187c.js
```

## 🔦 Context

This issue only happens in `serve mode`, when I build the project it works like expected.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^2.0.0-nightly.731 |
| Node             | v14.17.0 |
| npm/Yarn         | 7.18.1 |
| Operating System | Fedora 34 (Thirty Four) x86_64 |

**Comment by drachehavoc** [comment]
is there any prediction when this issue will be resolved? I apologize for pushing this issue, but I really want to keep using Parcel2 and this issue is making it impossible, my development team insists we should move to WebPack, I'm running out of arguments.

**Comment by amartincolby** [comment]
I'm encountering the same problem in Ubuntu 20.04. Works fine on my Mac laptop, but the failure on Linux is a hard crash. Ubuntu actually informed me that Node stopped working. Running 2.0.0-nightly.722+e9c4ebb1, Node v14.17.2, Yarn v1.22.10.

**Comment by drachehavoc** [comment]
this error persists on 2.0.0-nightly.750. Will this problem be fixed soon?

**Comment by drachehavoc** [comment]
I'm begging you to pay attention to this problem, please!
