### ISSUE TITLE
Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"

### ISSUE THREAD

**Issue by domoritz** [parcel-bundler/parcel#6525]
# 🐛 bug report

When I install parcel 2 (yarn add --dev parcel@next) in https://github.com/uwdata/falcon/tree/39bca404b72cdc86f0c3ce154b48b73cc2094720, I get a ts error. It used to work with parcel 1. 

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://github.com/uwdata/falcon/tree/39bca404b72cdc86f0c3ce154b48b73cc2094720

## 🤔 Expected Behavior

No crash

## 😯 Current Behavior

```
🚨 Build failed.
@parcel/transformer-babel: /Users/dominik/Code/falcon/flights/index.ts: Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"
TypeError: /Users/dominik/Code/falcon/flights/index.ts: Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"
    at Object.validate (/Users/dominik/Code/falcon/node_modules/@babel/types/lib/definitions/utils.js:130:11)
    at validateField (/Users/dominik/Code/falcon/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at Object.validate (/Users/dominik/Code/falcon/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/Users/dominik/Code/falcon/node_modules/@babel/traverse/lib/path/replacement.js:147:7)
    at NodePath.replaceWith (/Users/dominik/Code/falcon/node_modules/@babel/traverse/lib/path/replacement.js:129:8)
    at Object.ReferencedIdentifier (/Users/dominik/Code/falcon/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:44:14)
    at Object.newFn (/Users/dominik/Code/falcon/node_modules/@babel/traverse/lib/visitors.js:212:17)
    at NodePath._call (/Users/dominik/Code/falcon/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/dominik/Code/falcon/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/dominik/Code/falcon/node_modules/@babel/traverse/lib/path/context.js:90:31)
/Users/dominik/Code/falcon/flights/index.ts
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1
| Node             | 15
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
What is in your babel config? It looks like something in `babel-plugin-transform-es2015-modules-commonjs` from the stack trace?

**Comment by domoritz** [comment]
I only have this paper config: https://github.com/vega/falcon/blob/39bca404b72cdc86f0c3ce154b48b73cc2094720/.babelrc. 

```json
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": ["last 2 Chrome versions", "last 2 Firefox versions"]
        }
      }
    ]
  ]
}
```

**Comment by CharlesJones88** [comment]
any update on this @devongovett? I'm having the same issue as well
