### ISSUE TITLE
inline css in .vue files does not work as build

### ISSUE THREAD

**Issue by sda3-14** [parcel-bundler/parcel#6547]
# 🐛 bug report

I tried adding some inline css to my apps .vue file, and it does work, but when I try to create a production build instead of a dev one, it crashes.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json: 
```json
{
	"name": "...",
	"version": "...",
	"description": "",
	"dependencies": {},
	"repository": {
		"type": "git",
		"url": "..."
	},
	"author": "",
	"license": "ISC",
	"bugs": {
		"url": "..."
	},
	"homepage": "...",
	"devDependencies": {}
}

```

## 🤔 Expected Behavior

Parcel does not crash.

## 😯 Current Behavior

Parcel does crash.
```
× Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

    at ScopeHoistingPackager.resolveSymbol (C:\Users\vince\OneDrive\Desktop\GitHub Sync\pixelavie\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:685:27)
    at ScopeHoistingPackager.buildReplacements (C:\Users\vince\OneDrive\Desktop\GitHub Sync\pixelavie\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:594:27)
    at ScopeHoistingPackager.buildAsset (C:\Users\vince\OneDrive\Desktop\GitHub Sync\pixelavie\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:414:39)
    at ScopeHoistingPackager.visitAsset (C:\Users\vince\OneDrive\Desktop\GitHub Sync\pixelavie\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:369:17)
    at C:\Users\vince\OneDrive\Desktop\GitHub Sync\pixelavie\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:464:54
    at String.replace (<anonymous>)
    at ScopeHoistingPackager.buildAsset (C:\Users\vince\OneDrive\Desktop\GitHub Sync\pixelavie\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:433:17)
    at ScopeHoistingPackager.visitAsset (C:\Users\vince\OneDrive\Desktop\GitHub Sync\pixelavie\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:369:17)
    at C:\Users\vince\OneDrive\Desktop\GitHub Sync\pixelavie\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:204:40
    at enter (C:\Users\vince\AppData\Roaming\npm\node_modules\parcel\node_modules\@parcel\core\lib\Graph.js:543:16)
```

## 💻 Code Sample

index.htm: 
```html
<!doctype html>
<html>
	<head>
		<title>...</title>
	</head>
	<body>
		<div id="app"></div>
		<script src="./index.js"></script>
	</body>
</html>
```
index.js: 
```javascript
import { createApp } from 'vue';
import App from './App.vue';

const vapp = createApp(App);
vapp.mount('#app');
```
App.vue: 
```vue
<template>
	<div id="content">
		<p>testing</p>
	</div>
</template>
<style>
	#content {
		color: red;
	}
</style>
<script lang="ts">
	export default {
		data() {
			return {
			};
		}
	};
</script>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Vue              | 3.1.4 |
| @parcel/transformer-vue | 2.0.0-beta.3.1 |
| Node             | 6.14.13 |
| Operating System | Windows 11 (Insider Build) |

**Comment by mischnic** [comment]
Please try the nightly version (`yarn add -E parcel@nightly`), this was fixed recently

**Comment by sda3-14** [comment]
I'm currently having problems with the nightly build.
It says
```
× Build failed.
@parcel/transformer-js: Browser scripts cannot have imports or exports. Use a <script type="module"> instead.
```

**Comment by mischnic** [comment]
You need to add `type="module"` in your HTML, just as the error says

**Comment by sda3-14** [comment]
Thanks, it works!
