### ISSUE TITLE
All parcel commands fail with `lmdb-store` symbol not found error

### ISSUE THREAD

**Issue by awwong1** [parcel-bundler/parcel#6597]
# 🐛 bug report

After running `npm audit fix`, all parcel commands fail with an `lmdb-store` symbol not found error.
* https://github.com/DoctorEvidence/lmdb-store

Issue is also repeatable by clearing `node_modules` and `package-lock.json` and reinstalling packages.

### [`.babelrc`](https://git.sr.ht/~udia/app.udia.ca/tree/main/item/assets/.babelrc)
```json
{
  "extends": ["@parcel/config-default"],
  "reporters": ["parcel-reporter-static-files-copy"]
}
```

### [`package.json`](https://git.sr.ht/~udia/app.udia.ca/tree/main/item/assets/package.json)
```json
{
  "repository": {
    "type" : "git",
    "url" : "https://git.sr.ht/~udia/app.udia.ca",
    "directory": "assets"
  },
  "description": "Javascript/Browser client for app.udia.ca",
  "license": "AGPL-3.0-or-later",
  "private": true,
  "scripts": {
    "deploy": "parcel build --dist-dir ../priv/static src/*",
    "watch": "parcel watch --no-hmr --dist-dir ../priv/static src/*",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "phoenix": "^1.5.9",
    "phoenix_html": "^2.14.3",
    "phoenix_live_view": "^0.15.7",
    "three": "^0.130.1"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.0.0-beta.3.1",
    "@types/phoenix": "^1.5.2",
    "@types/phoenix_live_view": "^0.15.1",
    "@types/three": "^0.130.0",
    "@typescript-eslint/eslint-plugin": "^4.28.3",
    "@typescript-eslint/parser": "^4.28.3",
    "eslint": "^7.30.0",
    "node-gyp-build": "^4.2.3",
    "parcel": "^2.0.0-beta.3.1",
    "parcel-reporter-static-files-copy": "^1.3.0",
    "typescript": "^4.3.5"
  }
}
```

## 🤔 Expected Behavior

Running `parcel build` should generate my optimized files.

## 😯 Current Behavior

```bash
$ parcel build --dist-dir ../priv/static src/*

Error: dlopen(/Users/alexander/sandbox/src/git.sr.ht/udia/app.udia.ca/assets/node_modules/lmdb-store/build/Release/lmdb-store.node, 1): Symbol not found: __Z13signalHandleri
  Referenced from: /Users/alexander/sandbox/src/git.sr.ht/udia/app.udia.ca/assets/node_modules/lmdb-store/build/Release/lmdb-store.node
  Expected in: flat namespace
 in /Users/alexander/sandbox/src/git.sr.ht/udia/app.udia.ca/assets/node_modules/lmdb-store/build/Release/lmdb-store.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/Users/alexander/sandbox/src/git.sr.ht/udia/app.udia.ca/assets/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at load (/Users/alexander/sandbox/src/git.sr.ht/udia/app.udia.ca/assets/node_modules/node-gyp-build/index.js:21:10)
    at Object.<anonymous> (/Users/alexander/sandbox/src/git.sr.ht/udia/app.udia.ca/assets/node_modules/lmdb-store/index.js:7:49)
    at Module._compile (/Users/alexander/sandbox/src/git.sr.ht/udia/app.udia.ca/assets/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

## 💁 Possible Solution

🤷 

## 💻 Code Sample

```bash
git clone https://git.sr.ht/~udia/app.udia.ca
cd app.udia.ca/assets
git checkout threejs
npm install
npm run deploy # no problem
npm audit fix
npm run deploy # problem
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-nightly.769` |
| Node             | `v14.17.1` |
| **npm**/Yarn         | `7.19.1` |
| Operating System | `macOS 11.4 (20F71)` |

**Comment by mischnic** [comment]
Which version of `lmdb-store` is failing for you? (= what does package-lock say after `audit fix`)?

**Comment by awwong1** [comment]
`lmdb-store` is at `1.6.2`.
* https://www.npmjs.com/package/lmdb-store/v/1.6.2

`cat package-lock.json | grep lmdb`
```
        "lmdb-store": "^1.5.5"
    "node_modules/lmdb-store": {
      "resolved": "https://registry.npmjs.org/lmdb-store/-/lmdb-store-1.6.2.tgz",
    "node_modules/lmdb-store/node_modules/mkdirp": {
        "lmdb-store": "^1.5.5"
    "lmdb-store": {
      "resolved": "https://registry.npmjs.org/lmdb-store/-/lmdb-store-1.6.2.tgz",
```
----
EDIT: Prior to `npm audit fix`, this package was not installed. Afterwards, I see it was introduced by `@parcel/cache`

`npm ls lmdb-store`
```
assets@ /Users/alexander/sandbox/src/git.sr.ht/udia/app.udia.ca/assets
└─┬ parcel@2.0.0-nightly.769+b549b1d2
  └─┬ @parcel/core@2.0.0-nightly.769+b549b1d2
    └─┬ @parcel/cache@2.0.0-nightly.771+b549b1d2
      └── lmdb-store@1.6.2
```

**Comment by mischnic** [comment]
I can reproduce that with 1.6.2, but 1.6.3 works correctly for me

**Comment by awwong1** [comment]
Verified that this issue is now resolved with external deps changes. No action required here
