### ISSUE TITLE
Build fails: @parcel/bundler-default: The expression evaluated to a falsy value:

### ISSUE THREAD

**Issue by hanubence** [parcel-bundler/parcel#6600]
# 🐛 bug report

Today after pulling the project on my other machine I tried building my project, which failed. I haven't changed anything except for the html file in my src directory (simple markup changes for my website, nothing in particular which could affect parcel).

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```json
{
  "name": "kut",
  "version": "1.0.0",
  "description": "",
  "devDependencies": {
    "@parcel/transformer-image": "^2.0.0-nightly.2393",
    "autoprefixer": "^10.3.1",
    "express": "^4.17.1",
    "npm-run-all": "^4.1.5",
    "parcel": "^2.0.0-nightly.769",
    "postcss": "^8.3.5",
    "postcss-cli": "^8.3.1",
    "sharp": "^0.28.3",
    "tailwindcss": "^2.2.4"
  },
  "scripts": {
    "server": "node server",
    "dev": "npm-run-all --parallel dev:*",
    "dev:parcel": "parcel serve ./src/index.html",
    "dev:css": "tailwindcss -o src/tailwind.css -w",
    "build": "npm-run-all build:css build:parcel",
    "build:parcel": "parcel build ./src/index.html",
    "build:css": "tailwindcss -o src/tailwind.css"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/hanubence/kut.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/hanubence/kut/issues"
  },
  "homepage": "https://github.com/hanubence/kut#readme"
}
```

.postcssrc
```json
{
  "plugins": {
    "tailwindcss": {},
	  "autoprefixer": {}
  }
}
```

## 🤔 Expected Behavior

Successfully building my project.

## 😯 Current Behavior

after running 'npm run build' I get the following output:

```bash
$ npm run build:parcel

> kut@1.0.0 build:parcel P:\code\kut
> parcel build ./src/index.html     

🚨 Build failed.

@parcel/bundler-default: The expression evaluated to a falsy value:

  (0, _assert().default)(context != null)


  AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
  (0, _assert().default)(context != null)
  
  at enter (P:\code\kut\node_modules\@parcel\bundler-default\lib\DefaultBundler.js:174:31)
  at P:\code\kut\node_modules\@parcel\core\lib\Graph.js:520:16
  at P:\code\kut\node_modules\@parcel\core\lib\Graph.js:520:16
  at walk (P:\code\kut\node_modules\@parcel\core\lib\Graph.js:385:26)
  at walk (P:\code\kut\node_modules\@parcel\core\lib\Graph.js:407:22)
  at walk (P:\code\kut\node_modules\@parcel\core\lib\Graph.js:407:22)
  at walk (P:\code\kut\node_modules\@parcel\core\lib\Graph.js:407:22)
  at ContentGraph.dfs (P:\code\kut\node_modules\@parcel\core\lib\Graph.js:433:12)
  at ContentGraph.traverse (P:\code\kut\node_modules\@parcel\core\lib\Graph.js:336:17)
  at ContentGraph.filteredTraverse (P:\code\kut\node_modules\@parcel\core\lib\Graph.js:344:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kut@1.0.0 build:parcel: `parcel build ./src/index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kut@1.0.0 build:parcel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hanus\AppData\Roaming\npm-cache\_logs\2021-07-16T12_26_44_975Z-debug.log
```

### So far I've done the following:
- Tried building / running a dev server on two different machines
- Deleted node_modules, .parcel-cache, package-lock.json then running npm install
- Cleared npm cache
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel              | nightly.769|
| Node               | 14.17.0|
| npm/Yarn        | 6.14.13|
| Operating System |  Windows 10 x64|

**Comment by devongovett** [comment]
Do you have a code sample that reproduces the issue?
