### ISSUE TITLE
Property name expected type of string but got null

### ISSUE THREAD

**Issue by burakkaraceylan** [parcel-bundler/parcel#6643]
# 🐛 bug report

I can't build a react application.

## 🎛 Configuration (.babelrc, package.json, cli command)

create-react-app defaults

## 🤔 Expected Behavior

Should build the application.

## 😯 Current Behavior

 E:\test\node_modules@google\model-viewer\dist\model-viewer.js: E:\test\node_modules@google\model-viewer\dist\model-viewer.js: Property name expected type of string but got null
at validate (E:\test\node_modules@babel\types\lib\definitions\utils.js:158:13)
at Object.validate (E:\test\node_modules@babel\types\lib\definitions\utils.js:227:7)
at validateField (E:\test\node_modules@babel\types\lib\validators\validate.js:24:9)
at validate (E:\test\node_modules@babel\types\lib\validators\validate.js:17:3)
at builder (E:\test\node_modules@babel\types\lib\builders\builder.js:38:27)
at Object.identifier (E:\test\node_modules@babel\types\lib\builders\generated\index.js:343:31)
at E:\test\node_modules\regenerator-transform\lib\hoist.js:32:29
at Array.forEach ()
at varDeclToExpr (E:\test\node_modules\regenerator-transform\lib\hoist.js:29:23)
at exit (E:\test\node_modules\regenerator-transform\lib\hoist.js:51:20)

## 💁 Possible Solution

Ejecting react and using suggested babel configurations didn't work.

## 🔦 Context

I am coding a react app to embed in websites.

## 💻 Code Sample

Running with react-scripts start works fine but building with parcel fails.

## 🌍 Your Environment

    "@google/model-viewer": "^1.7.2",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "axios": "^0.21.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^4.0.3",
    "react-select": "^4.3.1",
    "web-vitals": "^1.1.2"

**Comment by devongovett** [comment]
Please provide a code sample that reproduces the issue. Also fully fill out the template: what version of parcel are you using?
