### ISSUE TITLE
Filenames containing non-ascii characters can't be built

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6655]
# 🐛 bug report

If a file name contains a non-ascii character like an "ö" the build fails.

## 🎛 Configuration (.babelrc, package.json, cli command)

Not relevant.

## 🤔 Expected Behavior

No failure.

## 😯 Current Behavior

```
@parcel/transformer-js: byte index 7 is not a char boundary; it is inside 'ö' (bytes 6..8) of `dist/xöxxxxxx_xxxxxxxxxxxx/xxxx.js`

  Error: byte index 7 is not a char boundary; it is inside 'ö' (bytes 6..8) of `dist/xöxxxxxx_xxxxxxxxxxxx/xxxx.js`
  at NodeSourceMap.addSource ([project_dir]/node_modules/@parcel/source-map/dist/SourceMap.js:208:35)
  at NodeSourceMap._indexedMappingsToInt32Array ([project_dir]/node_modules/@parcel/source-map/dist/SourceMap.js:138:28)
  at NodeSourceMap.addIndexedMappings ([project_dir]/node_modules/@parcel/source-map/dist/SourceMap.js:172:30)
  at Object.generate ([project_dir]/node_modules/@parcel/transformer-babel/lib/BabelTransformer.js:136:11)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Transformation.runTransformer ([project_dir]/node_modules/@parcel/core/lib/Transformation.js:577:20)
  at async Transformation.runPipeline ([project_dir]/node_modules/@parcel/core/lib/Transformation.js:357:36)
  at async Transformation.runPipelines ([project_dir]/node_modules/@parcel/core/lib/Transformation.js:241:40)
  at async Transformation.run ([project_dir]/node_modules/@parcel/core/lib/Transformation.js:167:19)
```

## 💁 Possible Solution

Update [source-map](https://github.com/parcel-bundler/source-map) like described [here](https://github.com/parcel-bundler/source-map/issues/69#issuecomment-883141935)

## 🔦 Context

We're living in 2021 and using non-ascii characters should just work.

## 💻 Code Sample

Not needed

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.776+ba7d2263|
| Node             |v16.5.0|
| npm/Yarn         |npm v7.19.1|
| Operating System | macOS 10.15.7 (19H1217)|

**Comment by DeMoorJasper** [comment]
Will publish a new version today, filenames with non-ascii characters aren't that common so pretty easy to overlook though
