### ISSUE TITLE
Sass transformation fails for style tag with type="application/sass"

### ISSUE THREAD

**Issue by aakoch** [parcel-bundler/parcel#6689]
# 🐛 bug report

I get an error when running Parcel when my html contains a style tag with the attribute `type="application/css"`.

## 🎛 Configuration (.babelrc, package.json, cli command)

I run `npx parcel src/test.html` and get the error in the "Current Behavior" section. test.html in its entirety is in the "Code Sample" section.

Pretty bare bones config. And the test I came up for this doesn't even use Pug nor the scripts section of the config.
```js
{
  "name": "XXXX",
  "version": "1.0.0",
  "description": "XXXX",
  "main": "index.js",
  "dependencies": {
    "pug": "^3.0.2",
    "pug-cli": "^1.0.0-alpha6"
  },
  "devDependencies": {
    "@parcel/transformer-image": "^2.0.0-rc.0",
    "@parcel/transformer-pug": "^2.0.0-rc.0",
    "@parcel/transformer-sass": "^2.0.0-rc.0",
    "parcel": "^2.0.0-rc.0"
  },
  "scripts": {
    "test": "parcel ./src/test.html",
    "build": "parcel build ./src/*.pug --dist-dir ./dist",
    "build-pretty": "cp -R src/css dist/ && cp -R src/images dist/ && pug -o dist --doctype html --pretty src",
    "watch": "parcel watch --log-level=verbose ./src/*.pug"
  },
  "repository": {
    "type": "git",
    "url": "XXXX"
  },
  "author": "Adam Koch",
  "license": "XXXX"
}
```

## 🤔 Expected Behavior

Honestly, I didn't expect any transformation to be done but I crossed my fingers and yes! Parcel's awesome. I guess I expect the Sass to be parsed and written to the output. 

## 😯 Current Behavior
```
@parcel/transformer-sass: Expected newline.
  ╷
2 │       .example { }
  │                ^
  ╵
  src/test.html 2:16  root stylesheet

  Error: Expected newline.
  ╷
  2 │       .example { }
  │                ^
  ╵
  src/test.html 2:16  root stylesheet
  at Object._newRenderError (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:13232:19)
  at Object._wrapException (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:13052:16)
  at _render_closure1.call$2 (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:82164:21)
  at _RootZone.runBinary$3$3 (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:27587:18)
  at _FutureListener.handleError$1 (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:26136:19)
  at _Future__propagateToListeners_handleError.call$0 (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:26434:49)
  at Object._Future__propagateToListeners (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:4550:77)
  at _Future._completeError$2 (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:26266:9)
  at _AsyncAwaitCompleter.completeError$2 (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:25920:12)
  at Object._asyncRethrow (/Users/akoch1/projects/log/node_modules/sass/sass.dart.js:4349:17)
```

## 💁 Possible Solution

It looks to me like there is already something in the Sass transformer for this: https://github.com/parcel-bundler/parcel/blob/8fc248f1f8eeb4428f7abd768bd23111451b1903/packages/transformers/sass/src/SassTransformer.js#L60
But maybe something changed and doesn't work? 
Or I'm completely off base.

## 🔦 Context

I was trying to write some Sass directly in my HTML file instead of having to move it to an external .scss file.

## 💻 Code Sample

```
<!DOCTYPE html>
<html>
  <head>
    <style type="application/sass">
      .example { }
    </style>
  </head>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v14.16.1
| npm/Yarn         | npm 6.14.12
| Operating System | Mac Catalina

**Comment by devongovett** [comment]
`<style type="sass">` should work

**Comment by aakoch** [comment]
Yup. Thanks!
