### ISSUE TITLE
Cannot install Parcel on Ubuntu 20.04

### ISSUE THREAD

**Issue by MrMarci666** [parcel-bundler/parcel#6691]
# 🐛 bug report

Cannot install Parcel on Ubuntu 20.04

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "secret",
  "version": "0.1.0",
  "author": "me",
  "license": "Unlicense",
  "scripts": {
    "clean": "rm -rf assets/dist",
    "watch": "parcel watch assets/src/main.html --dist-dir ./assets/dist --public-url /wp-content/themes/my-template/dist/ --no-source-maps",
    "build": "parcel build assets/src/main.html --dist-dir ./assets/dist --public-url /wp-content/themes/my-template/dist/ --no-source-maps --no-cache"
  },
  "dependencies": {
    "@popperjs/core": "^2.9.2",
    "bootstrap": "^5.0.2",
    "jquery": "^3.6.0"
  },
  "devDependencies": {
    "@parcel/transformer-image": "2.0.0-rc.0",
    "@parcel/transformer-sass": "2.0.0-rc.0",
    "parcel": "^2.0.0-rc.0"
  }
}

```

## 🤔 Expected Behavior

Parcel should be installed successfully.

## 😯 Current Behavior

Parcel won't be installed successfully

```
warning Error running install script for optional dependency: "/var/lib/jenkins/workspace/project/my-template/node_modules/msgpackr-extract: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /var/lib/jenkins/workspace/project/my-template/node_modules/msgpackr-extract
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.6.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at \"/usr/bin/python3\"
(node:497855) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/lib/jenkins/workspace/project/my-template/node_modules/msgpackr-extract/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/16.6.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.6.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.6.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/lib/jenkins/workspace/project/my-template/node_modules/msgpackr-extract',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/var/lib/jenkins/workspace/project/my-template/node_modules/msgpackr-extract/build'
CXX(target) Release/obj.target/msgpackr-extract/src/extract.o
make: g++: Command not found
make: *** [msgpackr-extract.target.mk:127: Release/obj.target/msgpackr-extract/src/extract.o] Error 127
make: Leaving directory '/var/lib/jenkins/workspace/project/my-template/node_modules/msgpackr-extract/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.4.0-80-generic
gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /var/lib/jenkins/workspace/project/my-template/node_modules/msgpackr-extract
[6/6] ⠐ lmdb-store
[-/6] ⠐ waiting...
[3/6] ⠐ sharp
[-/6] ⠐ waiting...
error /var/lib/jenkins/workspace/project/my-template/node_modules/lmdb-store: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /var/lib/jenkins/workspace/project/my-template/node_modules/lmdb-store
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.6.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
(node:497911) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/lib/jenkins/workspace/project/my-template/node_modules/lmdb-store/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/16.6.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.6.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.6.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/lib/jenkins/workspace/project/my-template/node_modules/lmdb-store',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/var/lib/jenkins/workspace/project/my-template/node_modules/lmdb-store/build'
CC(target) Release/obj.target/lmdb-store/dependencies/lmdb/libraries/liblmdb/midl.o
CC(target) Release/obj.target/lmdb-store/dependencies/lmdb/libraries/liblmdb/chacha8.o
CC(target) Release/obj.target/lmdb-store/dependencies/lz4/lib/lz4.o
CXX(target) Release/obj.target/lmdb-store/src/node-lmdb.o
make: g++: Command not found
make: *** [lmdb-store.target.mk:154: Release/obj.target/lmdb-store/src/node-lmdb.o] Error 127
make: Leaving directory '/var/lib/jenkins/workspace/project/my-template/node_modules/lmdb-store/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.4.0-80-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/lib/jenkins/workspace/project/my-template/node_modules/lmdb-store
```

## 🔦 Context

This works actually in my docker environment local on my computer, but won't work on a Ubuntu 20.04 Server.

## 💻 Code Sample

See package.json

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel | 2.0.0-rc.0
| Node | 16.6.1
| npm | 7.20.3 
| Yarn | 1.22.11
| Operating System | Ubuntu 20.04

**Comment by mischnic** [comment]
You need to install the `build-essential` apt package because lmdb-store doesn't provide prebuilds.

**Comment by MrMarci666** [comment]
@mischnic  Yes! Thank you very much. It has solved the problem! Just a quick question: How should I've known it that it needs to be installed? Did I missed a part in the Documentation?

**Comment by mischnic** [comment]
No, but you usually need to do this to install any npm package with a native module successfully. So one could say this is somewhat implicit like having to install Node and Yarn 🤷

**Comment by MrMarci666** [comment]
Okay, good to know, I'll add this to my installation script. Thank you for your help. I'll close this issue now.

**Comment by MrMarci666** [comment]
Okay, good to know, I'll add this to my installation script. Thank you for your help. I'll close this issue now.
