### ISSUE TITLE
Does not work with react-map-gl

### ISSUE THREAD

**Issue by ben-pr-p** [parcel-bundler/parcel#671]
🐛 Cannot resolve dependency react-map-gl 🐛

I believe there is a specific issue with react-map-gl (which may require some custom configuration in Webpack) and parcel. To reproduce:

package.json
```
{
  "dependencies": {
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "parcel-bundler": "^1.5.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-map-gl": "^3.2.0"
  },
  "devDependencies": {}
}
```

.babelrc
```
{
  "presets": ["env", "react"]
}
```

index.html
```
<div id="app"></div>
<script src="index.js"></script>
```

index.js
```
import { Component } from "react";
import { render } from "react-dom";
import ReactMapGL from "react-map-gl";

class Map extends Component {
  constructor() {
    super()
    this.state = {
      viewport: {
        width: 400,
        height: 400,
        latitude: 37.7577,
        longitude: -122.4376,
        zoom: 8
      }
    };
  }

  render() {
    return (
      <ReactMapGL
        {...this.state.viewport}
        onViewPortChange={viewport => this.setState({ viewport })}
      />
    );
  }
}

render(<Map />, document.querySelector("#app"));
```

And finally:
```
$ parcel index.html 
Server running at http://localhost:1234 
🚨  /Users/benpacker/jd/testing/index.js: Cannot resolve dependency 'react-map-gl'
    at /usr/local/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:166:21)
```

But, of course:
```
$ ls node_modules/ | grep react
babel-helper-builder-react-jsx
babel-plugin-transform-react-display-name
babel-plugin-transform-react-jsx
babel-plugin-transform-react-jsx-self
babel-plugin-transform-react-jsx-source
babel-preset-react
react
react-dom
react-map-gl
```

Possible explanations may be in https://uber.github.io/react-map-gl/#/Documentation/getting-started/get-started?section=example? I'm not quite sure what's going on that webpack config or what's happening under the hood in parcel, so I'm not sure if that helps

**Comment by devongovett** [comment]
This is because the package.json `module` key that points to a file that isn't published. https://github.com/uber/react-map-gl/blob/master/package.json#L18 I submitted a PR: https://github.com/uber/react-map-gl/pull/447

**Comment by devongovett** [comment]
Going to close this issue since it's not really a bug in parcel.

**Comment by ben-pr-p** [comment]
Thanks Devon!
