### ISSUE TITLE
Error: The specified module could not be found. @parcel\fs-search\fs-search.win32-x64-msvc.node

### ISSUE THREAD

**Issue by masx200** [parcel-bundler/parcel#6725]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
    "devDependencies": {
        "parcel": "2.0.0-nightly.799"
    },
    "name": "jsfuck-and-hieroglyphy-decoder-and-encoder",
    "version": "1.0.0",
    "main": "index.js",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/masx200/JSfuck-and-hieroglyphy-Decoder-and-ENCODER.git"
    },
    "author": "masx200 <34191203+masx200@users.noreply.github.com>",
    "license": "MIT",
    "description": "JSfuck and hieroglyphy Decoder and  ENCODER",
    "bugs": {
        "url": "https://github.com/masx200/JSfuck-and-hieroglyphy-Decoder-and-ENCODER/issues"
    },
    "homepage": "https://github.com/masx200/JSfuck-and-hieroglyphy-Decoder-and-ENCODER#readme",
    "scripts": {
        "build": "parcel build ./src/*.html",
        "start": "parcel serve ./src/*.html",
        "format": "npx prettier --write *.md *.json */*.js */*.html */*.css"
    },
    "keywords": [],
    "dependencies": {
        "prettier": "^2.3.2"
    }
}

```

## 😯 Current Behavior

```
 npx parcel serve src/index.html


Error: The specified module could not be found.
\\?\D:\Documents\GitHub\JSfuck-and-hieroglyphy-Decoder-and-ENCODER\node_modules\@parcel\fs-search\fs-search.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (D:\Documents\GitHub\JSfuck-and-hieroglyphy-Decoder-and-ENCODER\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\Documents\GitHub\JSfuck-and-hieroglyphy-Decoder-and-ENCODER\node_modules\@parcel\fs-search\index.js:19:20)
    at Module._compile (D:\Documents\GitHub\JSfuck-and-hieroglyphy-Decoder-and-ENCODER\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```
## 💻 Code Sample

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>My First Parcel App</title>
    </head>
    <body>
        <h1>Hello, World!</h1>
    </body>
</html>

```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |"2.0.0-nightly.799"
| Node             |v16.6.2
| npm/Yarn         |yarn 1.22.10
| Operating System |Microsoft Windows [版本 10.0.19043.1165]

**Comment by mischnic** [comment]
That file does exist: https://unpkg.com/browse/@parcel/fs-search@2.0.0-nightly.2423/

Does deleting the `node_modules` folder and rerunning Yarn fix it?

**Comment by masx200** [comment]
I found that the file does exist, maybe it has an incompatibility issue on Windows?

**Comment by masx200** [comment]
"parcel": "2.0.0-beta.3.1"

I found that after the downgrade, there is no such problem.

**Comment by PhanDungTri** [comment]
I have a same problem. Downgrading to 2.0.0-beta.3.1 doesn't help me solve this issue.

**Comment by PhanDungTri** [comment]
After update Windows, it works again.

**Comment by rkboy7682** [comment]
Also i am getting this error (The specified module could not be found). plz help how to resolve it.

**Comment by mischnic** [comment]
Does this help? https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755

**Comment by rkboy7682** [comment]
no its not working.
