### ISSUE TITLE
Error: Failed to install @parcel/transformer-typescript-types: Yarn failed to install modules:Child process failed

### ISSUE THREAD

**Issue by oliversalzburg** [parcel-bundler/parcel#6754]
# 🐛 bug report

Trying to bundle results in failure.

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/oliversalzburg/parcel-ts-repro/tree/628724c93d43b4434adcbb3faadd977808a2878b

## 🤔 Expected Behavior

Project is built/bundled.

## 😯 Current Behavior

```shell
╰─ yarn parcel build
🚨 Build failed.

Error: Failed to install @parcel/transformer-typescript-types: Yarn failed to install modules:Child process failed

  Error: Failed to install @parcel/transformer-typescript-types: Yarn failed to install modules:Child process failed
  at install (/home/oliver/projects/parcel-ts-repro/.yarn/__virtual__/@parcel-package-manager-virtual-9585d7e132/0/cache/@parcel-package-manager-npm-2.0.0-rc.0-f04d85f25f-bcb3a8a2df.zip/node_modules/@parcel/package-manager/lib/installPackage.js:131:11)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async PromiseQueue._runFn (/home/oliver/projects/parcel-ts-repro/.yarn/cache/@parcel-utils-npm-2.0.0-rc.0-2da8e0c855-58bc15a77b.zip/node_modules/@parcel/utils/lib/PromiseQueue.js:88:7)
  at async PromiseQueue._next (/home/oliver/projects/parcel-ts-repro/.yarn/cache/@parcel-utils-npm-2.0.0-rc.0-2da8e0c855-58bc15a77b.zip/node_modules/@parcel/utils/lib/PromiseQueue.js:75:5)
```

Installing package manually and running with `--no-autoinstall` just leads to further errors:

```shell
╰─ yarn parcel build --no-autoinstall              
🚨 Build failed.

@parcel/transformer-typescript-types: Got unexpected null

  Error: Got unexpected null
  at nullthrows (/home/oliver/projects/parcel-ts-repro/.yarn/cache/nullthrows-npm-1.1.1-3d1f817134-10806b9212.zip/node_modules/nullthrows/nullthrows.js:7:15)
  at TSModuleGraph.getAllExports
  (/home/oliver/projects/parcel-ts-repro/.yarn/__virtual__/@parcel-transformer-typescript-types-virtual-8e3109a182/0/cache/@parcel-transformer-typescript-types-npm-2.0.0-rc.0-3112c23597-ff187f151d.zip/node_modules/@parcel/transformer-typescript-types/lib/TSModuleGraph.js:177:52)
  at TSModuleGraph.propagate
  (/home/oliver/projects/parcel-ts-repro/.yarn/__virtual__/@parcel-transformer-typescript-types-virtual-8e3109a182/0/cache/@parcel-transformer-typescript-types-npm-2.0.0-rc.0-3112c23597-ff187f151d.zip/node_modules/@parcel/transformer-typescript-types/lib/TSModuleGraph.js:227:24)
  at shake (/home/oliver/projects/parcel-ts-repro/.yarn/__virtual__/@parcel-transformer-typescript-types-virtual-8e3109a182/0/cache/@parcel-transformer-typescript-types-npm-2.0.0-rc.0-3112c23597-ff187f151d.zip/node_modules/@parcel/transformer-typescript-types/lib/shake.js:42:35)
  at /home/oliver/projects/parcel-ts-repro/.yarn/__virtual__/@parcel-transformer-typescript-types-virtual-8e3109a182/0/cache/@parcel-transformer-typescript-types-npm-2.0.0-rc.0-3112c23597-ff187f151d.zip/node_modules/@parcel/transformer-typescript-types/lib/TSTypesTransformer.js:138:33
  at transformation (/home/oliver/projects/parcel-ts-repro/.yarn/cache/typescript-patch-bb3b548ba1-bc2c4fdf0f.zip/node_modules/typescript/lib/typescript.js:103015:24)
  at transformRoot (/home/oliver/projects/parcel-ts-repro/.yarn/cache/typescript-patch-bb3b548ba1-bc2c4fdf0f.zip/node_modules/typescript/lib/typescript.js:103042:82)
  at Object.transformNodes (/home/oliver/projects/parcel-ts-repro/.yarn/cache/typescript-patch-bb3b548ba1-bc2c4fdf0f.zip/node_modules/typescript/lib/typescript.js:103026:78)
  at emitDeclarationFileOrBundle (/home/oliver/projects/parcel-ts-repro/.yarn/cache/typescript-patch-bb3b548ba1-bc2c4fdf0f.zip/node_modules/typescript/lib/typescript.js:103758:43)
  at emitSourceFileOrBundle (/home/oliver/projects/parcel-ts-repro/.yarn/cache/typescript-patch-bb3b548ba1-bc2c4fdf0f.zip/node_modules/typescript/lib/typescript.js:103661:13)
```

## 💁 Possible Solution

Install the packages manually, run with `--no-autoinstall` and ensure your code has exports to work around the "Got unexpected null" defect.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v16.6.2
| npm/Yarn         | yarn 3.0.1
| Operating System | Windows

**Comment by mischnic** [comment]
Might be the same problem as https://github.com/parcel-bundler/parcel/issues/6684
