### ISSUE TITLE
assertion failed parcelv2 rc  when i try to run threejs

### ISSUE THREAD

**Issue by SUSHANTHA-LAB** [parcel-bundler/parcel#6768]
@parcel/bundler-default: The expression evaluated to a falsy value:

  (0, _assert().default)(context != null)

  AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(context != null)

  at enter (D:\new\NODE\PHYSICS\node_modules\@parcel\bundler-default\lib\DefaultBundler.js:174:31)
  at D:\new\NODE\PHYSICS\node_modules\@parcel\core\lib\Graph.js:520:16
  at D:\new\NODE\PHYSICS\node_modules\@parcel\core\lib\Graph.js:520:16
  at walk (D:\new\NODE\PHYSICS\node_modules\@parcel\core\lib\Graph.js:385:26)
  at walk (D:\new\NODE\PHYSICS\node_modules\@parcel\core\lib\Graph.js:407:22)
  at walk (D:\new\NODE\PHYSICS\node_modules\@parcel\core\lib\Graph.js:407:22)
  at walk (D:\new\NODE\PHYSICS\node_modules\@parcel\core\lib\Graph.js:407:22)
  at ContentGraph.dfs (D:\new\NODE\PHYSICS\node_modules\@parcel\core\lib\Graph.js:433:12)
  at ContentGraph.traverse (D:\new\NODE\PHYSICS\node_modules\@parcel\core\lib\Graph.js:336:17)
  at ContentGraph.filteredTraverse (D:\new\NODE\PHYSICS\node_modules\@parcel\core\lib\Graph.js:344:17)

**Comment by mischnic** [comment]
Please full out the issue template and provide a code sample
