### ISSUE TITLE
@parcel/transformer-js: Invalid comparator: latest

### ISSUE THREAD

**Issue by jvanderen1** [parcel-bundler/parcel#6828]
# 🐛 bug report

For some reason, on a different macOS machine of mine, I get an error when trying to run `parcel build`.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`:
```json
{
  "name": "@jvanderen1/unstated-next",
  "version": "1.0.1",
  "description": "Up-to-date version of everyone's favorite state management library unstated-next",
  "keywords": [
    "unstated",
    "react",
    "hooks",
    "context",
    "state",
    "react-hooks"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/jvanderen1/unstated-next"
  },
  "license": "MIT",
  "author": "<livetoscout@gmail.com>",
  "sideEffects": false,
  "main": "dist/unstated-next.cjs.js",
  "module": "dist/unstated-next.esm.js",
  "source": "src/index.ts",
  "browser": "dist/unstated-next.umd.js",
  "scripts": {
    "build": "npm run clean:dist && parcel build",
    "clean": "npm run clean:dist && npm run clean:types && npm run clean:node-modules",
    "clean:dist": "rm -rf dist/",
    "clean:node-modules": "rm -rf node_modules/",
    "clean:types": "tsc --build --clean",
    "clean-install": "npm run clean && npm install",
    "dev": "parcel example/index.html",
    "lint": "eslint './'",
    "lint:fix": "npm run lint -- --fix",
    "prepare": "husky install",
    "pretty": "prettier --check './'",
    "pretty:fix": "prettier --write './'",
    "test": "",
    "types-check": "tsc --skipLibCheck --noEmit"
  },
  "devDependencies": {
    "@parcel/transformer-typescript-types": "^2.0.0-rc.0",
    "@swc/cli": "^0.1.49",
    "@swc/core": "^1.2.80",
    "@types/node": "^16.7.1",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@typescript-eslint/eslint-plugin": "^4.29.2",
    "@typescript-eslint/parser": "^4.29.2",
    "eslint": "^7.32.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^7.0.1",
    "lint-staged": "^11.1.2",
    "parcel": "^2.0.0-rc.0",
    "prettier": "^2.3.2",
    "prop-types": "latest",
    "react": "latest",
    "react-dom": "latest",
    "ts-node": "^10.2.1",
    "typescript": "^4.3.5"
  },
  "peerDependencies": {
    "prop-types": ">= 15.5.0",
    "react": ">= 16.8.0"
  }
}
```

## 🤔 Expected Behavior

The command `npm run build` should work fine.

## 😯 Current Behavior

I receive the following error:

```sh
🚨 Build failed.

@parcel/transformer-js: Invalid comparator: latest

  TypeError: Invalid comparator: latest
  at Comparator.parse (/Users/joshuavanderen/Projects/personal/unstated-next/node_modules/@parcel/transformer-js/node_modules/semver/semver.js:754:11)
  at new Comparator (/Users/joshuavanderen/Projects/personal/unstated-next/node_modules/@parcel/transformer-js/node_modules/semver/semver.js:737:8)
  at Range.<anonymous> (/Users/joshuavanderen/Projects/personal/unstated-next/node_modules/@parcel/transformer-js/node_modules/semver/semver.js:925:12)
  at Array.map (<anonymous>)
  at Range.parseRange (/Users/joshuavanderen/Projects/personal/unstated-next/node_modules/@parcel/transformer-js/node_modules/semver/semver.js:924:13)
  at Range.<anonymous> (/Users/joshuavanderen/Projects/personal/unstated-next/node_modules/@parcel/transformer-js/node_modules/semver/semver.js:867:17)
  at Array.map (<anonymous>)
  at new Range (/Users/joshuavanderen/Projects/personal/unstated-next/node_modules/@parcel/transformer-js/node_modules/semver/semver.js:866:40)
  at Function.minVersion (/Users/joshuavanderen/Projects/personal/unstated-next/node_modules/@parcel/transformer-js/node_modules/semver/semver.js:1306:11)
  at loadConfig (/Users/joshuavanderen/Projects/personal/unstated-next/node_modules/@parcel/transformer-js/lib/JSTransformer.js:222:127)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-rc.0
| Node             | v16.8.0
| npm/Yarn         | 7.21.1
| Operating System | macOS 11.5.2

**Comment by folknor** [comment]
I was reading through the issue list to see if my latest problem was related to anything already posted, and also reading the code a bit and it seems that parcel uses an old version (5.4.1) of `semver`;
https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/js/package.json#L43
https://github.com/npm/node-semver/releases/tag/v7.3.5

I could be wrong. But also, and more importantly, I have no idea if using an older version is significant. The changelog for `semver` is very badly written.
EDIT: https://github.com/npm/node-semver/blob/master/CHANGELOG.md

That said, the problem I'm having is

```
🚨 Build failed.

@parcel/core: The plugin "@parcel/packager-svg" is not compatible with the current version of Parcel. Requires "^2.0.0-rc.0" but the current version is "2.0.0-nightly.817+461de114".

  /home/test/test/node_modules/.pnpm/@parcel+packager-svg@2.0.0-nightly.2441_@parcel+core@2.0.0-nightly.817/node_modules/@parcel/packager-svg/package.json:20:5
    19 |     "node": ">= 12.0.0",
  > 20 |     "parcel": "^2.0.0-rc.0"
  >    |     ^^^^^^^^^^^^^^^^^^^^^^^
    21 |   },
    22 |   "dependencies": {
```

And my package.json looks like
```js
  40   │         "@parcel/optimizer-cssnano": "nightly",
  41   │         "@parcel/optimizer-htmlnano": "nightly",
  42   │         "@parcel/packager-css": "nightly",
  43   │         "@parcel/packager-html": "nightly",
  44   │         "@parcel/packager-raw-url": "nightly",
  45   │         "@parcel/packager-svg": "nightly",
  46   │         "@parcel/transformer-css": "nightly",
  47   │         "@parcel/transformer-html": "nightly",
  48   │         "@parcel/transformer-image": "nightly",
  49   │         "@parcel/transformer-postcss": "nightly",
  50   │         "@parcel/transformer-posthtml": "nightly",
  51   │         "@parcel/transformer-sass": "nightly",
  52   │         "@parcel/transformer-webmanifest": "nightly",
...
  58   │         "parcel": "nightly",
```

But I wasn't prepared to file a bug yet because I'm trying out `pnpm`, although the problem is exactly the same if I nuke the node modules and run the same parcel command using `npm run` or `npx`.

It's not my intention to derail your ticket - hopefully you don't read it that way.

Hopefully a parcel dev can instruct us further.

**Comment by folknor** [comment]
This feels related to https://github.com/parcel-bundler/parcel/issues/6675 as well but it probably isn't.

**Comment by Sleepful** [comment]
Having this issue too, this bars me from using `latest` in `package.json` for react (    "react": "latest" ) which is very useful.
