### ISSUE TITLE
Add support for yarn 2/3 and PNP

### ISSUE THREAD

**Issue by KnisterPeter** [parcel-bundler/parcel#6888]
# 🙋 feature request

It would be nice to play well with pnp enabled repositories.

## 🤔 Expected Behavior

This should work out-of-the-box.

## 😯 Current Behavior

It fails when trying to execute:

```
xxx@xxx:~/xxx (main)$ yarn parcel watch
🚨 Build failed.

Error: EBADF: bad file descriptor, close

  Error: EBADF: bad file descriptor, close
  at ZipOpenFS.closePromise (/xxx/.pnp.js:19457:59)
  at VirtualFS.closePromise (/xxx/.pnp.js:17337:24)
  at PosixFS.closePromise (/xxx/.pnp.js:17337:24)
  at /xxx/.pnp.js:20533:20
  at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by mischnic** [comment]
I get a different error:
```
$ yarn set version berry
$ yarn init
$ yarn add parcel@nightly lodash
$ echo "import {add} from 'lodash';console.log(add(1,2));" > index.js
$ yarn parcel watch index.js
TypeError: Ko._resolveFilename is not a function
    at wu (/Users/niklas/Desktop/pnp/.yarn/cache/esm-npm-3.2.25-762b3ebd40-978aabe2de.zip/node_modules/esm/esm.js:1:226797)
    at Eu (/Users/niklas/Desktop/pnp/.yarn/cache/esm-npm-3.2.25-762b3ebd40-978aabe2de.zip/node_modules/esm/esm.js:1:227999)
    at Module.<anonymous> (/Users/niklas/Desktop/pnp/.yarn/cache/esm-npm-3.2.25-762b3ebd40-978aabe2de.zip/node_modules/esm/esm.js:1:295976)
    at n (/Users/niklas/Desktop/pnp/.yarn/cache/esm-npm-3.2.25-762b3ebd40-978aabe2de.zip/node_modules/esm/esm.js:1:279589)
    at Object.<anonymous> (/Users/niklas/Desktop/pnp/.yarn/cache/weak-lru-cache-npm-1.1.0-5ea1e71b05-f119f87936.zip/node_modules/weak-lru-cache/index.cjs:2:24)
    at Module._compile (/Users/niklas/Desktop/pnp/.yarn/cache/v8-compile-cache-npm-2.3.0-961375f150-adb0a271ea.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.external_module_.Module._load (/Users/niklas/Desktop/pnp/.pnp.cjs:18103:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

It works fine with `nodeLinker: "node-modules"`

**Comment by danieltroger** [comment]
It worked before I updated my stuff and now I get `TypeError: Ko._resolveFilename is not a function` too. Someone must have regressed something.

**Comment by mischnic** [comment]
At least that error is caused by `weak-lru-map@1.1.0` (released two days ago) which uses the `esm` package to load ESM in Node: 

https://github.com/kriszyp/weak-lru-cache/blob/master/index.cjs

**Comment by danieltroger** [comment]
Thanks for pinpointing that. So it's probably https://github.com/kriszyp/weak-lru-cache/commit/52d63418ea398832d50643dc32c95dd4744edefc that broke everything? Do you happen to know how I can get back to the old `weak-lru-cache` version?

**Comment by mischnic** [comment]
> So it's probably kriszyp/weak-lru-cache@52d6341 that broke everything?

Native Node ESM in dev dependencies is probably also broken for other reasons at the moment as well.

> Do you happen to know how I can get back to the old weak-lru-cache version?

Simply a Yarn `resolutions` entry?

**Comment by danieltroger** [comment]
I tried to add `"lmdb-store": "1.0.0",` to my package.json and it fails to build:

```
➤ YN0007: │ lmdb-store@npm:1.0.0 must be built because it never has been before or the last one failed
➤ YN0009: │ lmdb-store@npm:1.0.0 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/q_/xzl9z_1x2g17_4gvys67mfqw0000gn/T/xfs-af460c37/build.log)
```
[build.log](https://github.com/parcel-bundler/parcel/files/7121395/build.log)

I'll check out the `resolutions` docs again, thanks.

**Comment by kriszyp** [comment]
I can revert the change to weak-lru-cache (and update version) for now. But do you know why we can't upgrade to using ESM, or if there is a better way of doing that?

**Comment by mischnic** [comment]
I wouldn't use `require("esm")` in a "production" setting as in this case. Node has some docs on writing dual CJS and ESM packages: https://nodejs.org/api/packages.html#packages_dual_commonjs_es_module_packages

But it's not possible to have a ESM "source" file and a CJS wrapper file as you did in this case (without the "esm" loader at least), only the other way around.

**Comment by kriszyp** [comment]
Ok, I have "updated" weak-lru-cache (and ordered-binary) to v1.1.1 with ESM reverted for now.

I presume we don't want to be stuck forever in the ancient CJS world. And, of course I have read the Node docs on writing dual CJS/ESM packages. Which is total garbage, and worthless for actually getting it modules to work outside of NodeJS (in Deno). It is still not clear to me why the ESM wrapper isn't the best way to deal with the train wreck of NodeJS module loading and avoid "builds".

**Comment by kriszyp** [comment]
Ok, made a subsequent update (v1.1.2) that to (re)add support for ESM/CJS using builds (disappointingly) rather than the `esm` package. I'm still not clear why this was a problem, but let me know if you see any issues with this.

**Comment by mischnic** [comment]
Thank you! We'll look into this
