### ISSUE TITLE
 Asset was skipped or not found

### ISSUE THREAD

**Issue by kkrizzz** [parcel-bundler/parcel#6892]
# 🐛 bug report

After upgraded to rc.0 and fixed bunch of errors and messages I see this message:
` Asset was skipped or not found`

## 🎛 Configuration (.babelrc, package.json, cli command)

my .parcelrc
```js
{
  "extends": ["@parcel/config-default"],
  "reporters":  ["...", "parcel-reporter-static-files-copy"],
}
```

## 🤔 Expected Behavior

Building normally

## 😯 Current Behavior

```
$ NODE_ENV=production parcel build --target browser index.html
🚨 Build failed.

@parcel/packager-js: Asset was skipped or not found.

  AssertionError [ERR_ASSERTION]: Asset was skipped or not found.
  at ScopeHoistingPackager.getSymbolResolution (/Users/kriz/Projects/treenity-exp/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:714:29)
  at /Users/kriz/Projects/treenity-exp/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:818:31
  at Array.map (<anonymous>)
  at ScopeHoistingPackager.buildAssetPrelude (/Users/kriz/Projects/treenity-exp/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:817:37)
  at ScopeHoistingPackager.buildAsset (/Users/kriz/Projects/treenity-exp/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:382:48)
  at ScopeHoistingPackager.visitAsset (/Users/kriz/Projects/treenity-exp/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:341:17)
  at /Users/kriz/Projects/treenity-exp/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:438:38
  at String.replace (<anonymous>)
  at ScopeHoistingPackager.buildAsset (/Users/kriz/Projects/treenity-exp/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:404:19)
  at ScopeHoistingPackager.visitAsset (/Users/kriz/Projects/treenity-exp/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:341:17)
```

## 🌍 Your Environment

I think it is not relevant to environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             |  14.16.1
| npm/Yarn         | yarn 1.22.5
| Operating System | MacOS 10.15.7

**Comment by mischnic** [comment]
Can you provide a code sample that reproduces the issue?

**Comment by danmarshall** [comment]
I got the same error. I think it occurred because of a conditional `require` in a dependency? Still trying to create a minimal repro.

The workaround was to turn off scope hoisting.  

Also, would ne nice if this exception included the name of the asset: https://github.com/parcel-bundler/parcel/blob/v2/packages/packagers/js/src/ScopeHoistingPackager.js#L786

**Comment by jensengar** [comment]
I just ran into this issue as well. I haven't dug into the issue, but I can confirm that add `--no-scope-hoist` as a cli option fixes the issue.

**Comment by levrik** [comment]
Experiencing the same issue. Weirdly adding `--no-scope-hoist` didn't fix the problem although the scope hoister is mentioned in the stack trace 😕 
I'll try to dig deeper.

**Comment by garthenweb** [comment]
I run into a same issue with `parcel@v2.0.0` and was able to hunt it down to a this code path:

```
    module.hot.accept('./reducers', () => {
      const nextRootReducer = require('./reducers').default;
      store.replaceReducer(nextRootReducer);
    });
```

Removing the line `const nextRootReducer = require('./reducers').default;` fixed it. `'./reducers'` was imported using esm within the same file as well. The file containing the code is part of a dynamic imported file.

I tried to implement a simple reproducible repo but in a smaller code base it was still working without further issues. Someone has an idea how to find out more or what to look at? I unfortunately cannot share the original repository.

**Comment by mischnic** [comment]
This is very hard to reproduce because it depends on the order that dependencies are resolved in and generally on the shape of the asset graph. One helpful thing might be that this error and non-reproducible builds (where the bundle contents and therefore size/hash change between runs) usually have the same root cause (= the bug that's causing this).

**Comment by MartinDawson** [comment]
For me this happens with `parcel watch:build`. `parcel build` works fine.

**Comment by MartinDawson** [comment]
@mischnic I've reproduced this error:

Parcel: "^2.0.1"
Node: v16.13.0
Yarn: v1.22.15
OS: Ubuntu 19.04

Repo: https://github.com/TrackTak/parcel-watch-error

How to reproduce:

- run `yarn`.
- run `yarn watch:build`

output: 

```
🚨 Build failed.

@parcel/packager-js: Asset was skipped or not found.

  AssertionError [ERR_ASSERTION]: Asset was skipped or not found.
  at ScopeHoistingPackager.getSymbolResolution
  (/home/martin/Documents/parcel-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:716:29)
  at /home/martin/Documents/parcel-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:820:31
  at Array.map (<anonymous>)
  at ScopeHoistingPackager.buildAssetPrelude
  (/home/martin/Documents/parcel-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:819:37)
  at ScopeHoistingPackager.buildAsset (/home/martin/Documents/parcel-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:382:48)
  at ScopeHoistingPackager.visitAsset (/home/martin/Documents/parcel-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:341:17)
  at /home/martin/Documents/parcel-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:440:56
  at String.replace (<anonymous>)
  at ScopeHoistingPackager.buildAsset (/home/martin/Documents/parcel-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:404:19)
  at ScopeHoistingPackager.visitAsset (/home/martin/Documents/parcel-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:341:17)
```

**Comment by flexdinesh** [comment]
I'm running into the same error with `parcel watch`. `parcel build` builds successfully.

Repo reproducing the error — https://github.com/flexdinesh/parcel-react-watch-error

Node: v16.9.0
MacBook Air (M1, 2020)
macOS: Monterey 12.1

```
yarn run v1.22.11
$ parcel watch --cache-dir .parcel-cache
🚨 Build failed.

@parcel/packager-js: Asset was skipped or not found.

  AssertionError [ERR_ASSERTION]: Asset was skipped or not found.
  at ScopeHoistingPackager.getSymbolResolution
  (/Users/dineshpandiyan/workspace/parcel-react-watch-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:732:29)
  at
  /Users/dineshpandiyan/workspace/parcel-react-watch-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:836:31
  at Array.map (<anonymous>)
  at ScopeHoistingPackager.buildAssetPrelude
  (/Users/dineshpandiyan/workspace/parcel-react-watch-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:835:37)
  at ScopeHoistingPackager.buildAsset
  (/Users/dineshpandiyan/workspace/parcel-react-watch-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:398:48)
  at ScopeHoistingPackager.visitAsset
  (/Users/dineshpandiyan/workspace/parcel-react-watch-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:357:17)
  at
  /Users/dineshpandiyan/workspace/parcel-react-watch-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:456:56
  at String.replace (<anonymous>)
  at ScopeHoistingPackager.buildAsset
  (/Users/dineshpandiyan/workspace/parcel-react-watch-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:420:19)
  at ScopeHoistingPackager.visitAsset
  (/Users/dineshpandiyan/workspace/parcel-react-watch-error/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:357:17)
```

**Comment by lettertwo** [comment]
#7914 will solve this for React library cases (/cc @MartinDawson @flexdinesh).

There is still a more general problem that manifests as `Asset was skipped or not found`, which we will continue to track here.

**Comment by interstates21** [comment]
For me, this issue appears when I import `crypto-js` or `crypto` libraries

**Comment by mattcompiles** [comment]
We ran into this issue and it was caused by two re-exports of the same file.

e.g.
```js
export * from './events';

import * as _Events from "./events";
export { _Events as Events };
```

Removing one of the re-exports resolved the issue.

**Comment by mischnic** [comment]
Full reproduction for that (the error isn't thrown but the asset is still excluded incorrectly and the output JS is invalid)
```js
// index.js
import { c } from "./b.js";
console.log(c);

// b.js
export * from "./c.js";
import * as _a from "./c.js";
export { _a as c };

// c.js
export const a = 1;
export const b = 2;

// package.json
{
	"sideEffects": ["index.js"]
}
```
Output:
```js
(() => {
	console.log((0, $c98c7015a51a9260$exports.c));
})();
```

Somewhat related: https://github.com/parcel-bundler/parcel/issues/5255

One possible solution is modelling `export * from` with some boolean property as opposed to a `* -> *` entry in the symbols map.
