### ISSUE TITLE
Parcel 2 - issue with tailwindcss and JIT only when using @tailwindcss/forms

### ISSUE THREAD

**Issue by sync** [parcel-bundler/parcel#6898]
As soon as I include @tailwindcss/forms into my tailwind config, I am faced with a compilation error in dev and build mode.

This does not work (compilation fail)

```
module.exports = {
  mode: 'jit',
  purge: ["./src/*.{html,js}"],
  darkMode: 'media',
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/forms')],
};
```

If you don't include the tailwind forms no issues.

This is fine, no issues:

```
module.exports = {
  mode: 'jit',
  purge: ["./src/*.{html,js}"],
  darkMode: 'media',
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

If you don't enable JIT no issues.

This also is fine, no issues:

```
module.exports = {
  purge: ["./src/*.{html,js}"],
  darkMode: 'media',
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/forms')],
};
```

# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/sync/tailwind-jit-forms

## 🤔 Expected Behavior

running parcel or parcel build should not throw an error.

## 😯 Current Behavior

Parcel fails to complete the build.

```
🚨 Build failed.

@parcel/transformer-css: Cannot read property 'start' of undefined

  TypeError: Cannot read property 'start' of undefined
  at /Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/@parcel/transformer-css/lib/CSSTransformer.js:213:71
  at walk (/Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/postcss-value-parser/lib/walk.js:7:16)
  at ValueParser.walk (/Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/postcss-value-parser/lib/index.js:18:3)
  at /Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/@parcel/transformer-css/lib/CSSTransformer.js:209:16
  at /Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/postcss/lib/container.js:72:18
  at /Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/postcss/lib/container.js:55:18
  at Rule.each (/Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/postcss/lib/container.js:41:16)
  at Rule.walk (/Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/postcss/lib/container.js:52:17)
  at /Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/postcss/lib/container.js:60:24
  at Root.each (/Users/anthonymittaz/Projects/Parcel/tailwind-jit-forms/node_modules/postcss/lib/container.js:41:16)
```

## 💁 Possible Solution

Tailwind JIT works fine, just facing this issue when adding the `@tailwindcss/forms` plugin into the mix

## 💻 Code Sample

https://github.com/sync/tailwind-jit-forms

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | Tested with Node 14 and 16 latest (v16.5.0)
| npm/Yarn         | latest yarn v1 1.22.10
| Operating System | macOS Monterey

**Comment by sync** [comment]
previous issue: https://github.com/parcel-bundler/parcel/issues/6251

**Comment by sync** [comment]
@ bradlc you fixed the jit issue, perhaps you understand what's going wrong here ?

**Comment by sync** [comment]
@bradlc you fixed the previous jit issue perhaps you understand what is happening here ? thanks for your previous fix btw
