### ISSUE TITLE
2.0.0-rc.0 breaks when used with sass >= 1.38.0 on sass @import

### ISSUE THREAD

**Issue by steinwaywhw** [parcel-bundler/parcel#6923]
# 🐛 bug report

2.0.0-rc.0 transformer-sass seems to be broken when used with sass >= 1.38.0. It says 

```
@parcel/transformer-sass: Can't find stylesheet to import.
  ╷
4 │ @import "initial-variables"
  │         ^^^^^^^^^^^^^^^^^^^
  ╵
  file:parcel-bug/node_modules/bulma/sass/utilities/_all.sass 4:9  @import
  style.scss 1:9
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "devDependencies": {
    "@parcel/transformer-sass": "^2.0.0-rc.0",
    "parcel": "^2.0.0-rc.0",
    "sass": "~1.37.0"
  },
  "dependencies": {
    "bulma": "^0.9.3"
  }
}
```

Minimal demo project with an `index.js` and a `style.scss` with the above `package.json`

Style: 

```js
@import "bulma/sass/utilities/_all.sass";
```

Index: 

```js
import "./style.scss"
```

## 🤔 Expected Behavior

I expect that `@import "initial-variables"` as written in the Bulma library to work just fine.

## 😯 Current Behavior

```
@parcel/transformer-sass: Can't find stylesheet to import.
  ╷
4 │ @import "initial-variables"
  │         ^^^^^^^^^^^^^^^^^^^
  ╵
  file:/Users/hwwu/Github/parcel-bug/node_modules/bulma/sass/utilities/_all.sass 4:9  @import
  style.scss 1:9                                                                      root stylesheet

  Error: Can't find stylesheet to import.
  ╷
  4 │ @import "initial-variables"
  │         ^^^^^^^^^^^^^^^^^^^
  ╵
  file:/Users/hwwu/Github/parcel-bug/node_modules/bulma/sass/utilities/_all.sass 4:9  @import
  style.scss 1:9                                                                      root stylesheet
  at Object._newRenderError (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:2203:19)
  at Object._wrapException (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:2023:16)
  at _render_closure1.call$2 (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:83704:21)
  at _RootZone.runBinary$3$3 (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:28038:18)
  at _FutureListener.handleError$1 (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:26568:21)
  at _Future__propagateToListeners_handleError.call$0 (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:26867:49)
  at Object._Future__propagateToListeners (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:12499:77)
  at _Future._completeError$2 (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:26713:9)
  at _AsyncAwaitCompleter.completeError$2 (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:26382:12)
  at Object._asyncRethrow (/Users/hwwu/Github/parcel-bug/node_modules/sass/sass.dart.js:12302:17)
```

## 💁 Possible Solution

I think somehow the custom importer is working incorrectly.

## 🔦 Context

I'm not able to use sass >= 1.38.0 with Bulma in Parcel v2.

## 💻 Code Sample

Provided above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 15.12.0
| npm/Yarn         | npm 7.10.0
| Operating System | MacOS Darwin Kernel Version 20.4.0

**Comment by katzmo** [comment]
With the release of parcel 2.0.0 this now happens also with sass 1.37.5.

EDIT: But parcel 2.0.1 + sass 1.44.0 seems to work :tada:
