### ISSUE TITLE
Raspian - Cannot find module './artifacts/index.linux-arm-gnueabihf.node'

### ISSUE THREAD

**Issue by maccoylton** [parcel-bundler/parcel#6947]
# 🐛 bug report

Can't build homebridge-zigbee-nt UI on Raspian Buster 10

## 🎛 Configuration (.babelrc, package.json, cli command)

 yarn build:ui

## 🤔 Expected Behavior
It should build

## 😯 Current Behavior

It fails to build

$ parcel build public/index.html --dist-dir dist/public
Error: Cannot find module './artifacts/index.linux-arm-gnueabihf.node'
Require stack:
- /home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js
- /home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/dist/node.js
- /home/pi/homebridge-zigbee-nt/node_modules/@parcel/core/lib/Parcel.js
- /home/pi/homebridge-zigbee-nt/node_modules/@parcel/core/lib/index.js
- /home/pi/homebridge-zigbee-nt/node_modules/parcel/lib/cli.js
- /home/pi/homebridge-zigbee-nt/node_modules/parcel/lib/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/home/pi/homebridge-zigbee-nt/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js:15:18)
    at Module._compile (/home/pi/homebridge-zigbee-nt/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/@parcel/source-map/dist/node.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/@parcel/core/lib/Parcel.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/@parcel/core/lib/index.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/parcel/lib/cli.js',
    '/home/pi/homebridge-zigbee-nt/node_modules/parcel/lib/bin.js'
  ]
}

## 💁 Possible Solution

Fix dependancy error ensuring all reaquired modules etc  are present

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | parcel@2.0.0-rc.0
| Node             |v14.17.5
| npm/Yarn         |1.22.5
| Operating System | Raspbian 10

**Comment by mischnic** [comment]
This is already fixed: https://unpkg.com/browse/@parcel/source-map@2.0.0-rc.7/parcel_sourcemap_node/artifacts/

You can use the nightly version until it's released: `yarn add parcel@nightly`

**Comment by maccoylton** [comment]
Now getting this an issue with glibc:- 

Error: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by
/home/pi/homebridge-zigbee-nt/node_modules/@parcel/transformer-js/parcel-swc.linux-arm-gnueabihf.node)
