### ISSUE TITLE
Unable to use @parcel/resolver-glob

### ISSUE THREAD

**Issue by alexeyraspopov** [parcel-bundler/parcel#6963]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

I copied the config from https://v2.parceljs.org/blog/rc0/#glob-resolver-plugin

```js
{
  "extends": "@parcel/config-default",
  "resolvers": ["@parcel/resolver-glob", "..."]
}
```

Babel config is:

```js
{
  presets: [["@babel/preset-react", { development: false, runtime: "automatic" }]],
  plugins: [
    ["@babel/plugin-syntax-flow", { enums: true }],
    "babel-plugin-transform-flow-enums",
    "@babel/plugin-transform-flow-strip-types",
  ],
}
```

## 🤔 Expected Behavior

`modules/storybook.html` looks like this

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Application</title>
		<link rel="stylesheet" href="./index.css" />
		<script type="module">
			import * as stories from "./stories/*.js";
			console.log(stories);
		</script>
	</head>
	<body>
		<main></main>
	</body>
</html>
```

I simply want to glob import all files from the folder, as docs describe.

## 😯 Current Behavior

```
parcel serve modules/storybook.html
Server running at http://localhost:1234
🚨 Build failed.

@parcel/core: Failed to resolve 'modules/storybook.html'

@parcel/resolver-glob: Cannot read property 'replace' of undefined

  TypeError: Cannot read property 'replace' of undefined
  at normalizeSeparators
  (/<project_path>/node_modules/@parcel/resolver-glob/node_modules/@parcel/utils/lib/path.js:31:19)
  at isGlob
  (/<project_path>/node_modules/@parcel/resolver-glob/node_modules/@parcel/utils/lib/glob.js:54:66)
  at Object.resolve
  (/<project_path>/node_modules/@parcel/resolver-glob/lib/GlobResolver.js:79:30)
  at ResolverRunner.resolve
  (/<project_path>/node_modules/@parcel/core/lib/requests/PathRequest.js:207:44)
  at async Object.run
  (/<project_path>/node_modules/@parcel/core/lib/requests/PathRequest.js:104:16)
  at async RequestTracker.runRequest
  (/<project_path>/node_modules/@parcel/core/lib/RequestTracker.js:711:20)
  at async AssetGraphBuilder.runPathRequest
  (/<project_path>/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:722:18)
  at async PromiseQueue._runFn
  (/<project_path>/node_modules/@parcel/utils/lib/PromiseQueue.js:88:7)
  at async PromiseQueue._next
  (/<project_path>/node_modules/@parcel/utils/lib/PromiseQueue.js:75:5)

```

## 💁 Possible Solution

I was tweaking Parcel config and once somehow managed to get thing working. But wasn't able to reproduce. Seems like copying the actual default config and adding the glob resolver helped, but didn't seem to happen second time I tried.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.841
| Node             | 16.1.0
| npm/Yarn         | 7.24.0
| Operating System | macOS Big Sur

**Comment by alexeyraspopov** [comment]
Looks like the issue has been fixed in https://github.com/parcel-bundler/parcel/pull/6696. I was unable to install latest `@parcel/resolver-glob` because of some NPM shenanigans. Kudos to the team, this feature works just great!

**Comment by msimpson** [comment]
@alexeyraspopov 

What exactly resolved your issue?

If I install `parcel@nightly` presently `2.0.0-nightly.855`, and I use the following `.parcelrc`:

```
{

  "extends": "@parcel/config-default",

  "resolvers": [ "@parcel/resolver-glob" ],

  "transformers": {

    "*.svg|*.mp4": [ "@parcel/transformer-raw" ]

  }

}
```

When I run Parcel, it installs `"@parcel/resolver-glob": "^2.0.0-nightly.2338",` and immediately fails with:

```
🚨 Build failed.

@parcel/core: Failed to resolve 'source/index.html'

@parcel/resolver-glob: Cannot read property 'replace' of undefined

  TypeError: Cannot read property 'replace' of undefined
  at normalizeSeparators (C:\Users\User\Projects\siemens-idn\node_modules\@parcel\resolver-glob\node_modules\@parcel\utils\lib\path.js:31:19)
  at isGlob (C:\Users\User\Projects\siemens-idn\node_modules\@parcel\resolver-glob\node_modules\@parcel\utils\lib\glob.js:54:66)
  at Object.resolve (C:\Users\User\Projects\siemens-idn\node_modules\@parcel\resolver-glob\lib\GlobResolver.js:79:30)
  at ResolverRunner.resolve (C:\Users\User\Projects\siemens-idn\node_modules\@parcel\core\lib\requests\PathRequest.js:207:44)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Object.run (C:\Users\User\Projects\siemens-idn\node_modules\@parcel\core\lib\requests\PathRequest.js:104:16)
  at async RequestTracker.runRequest (C:\Users\User\Projects\siemens-idn\node_modules\@parcel\core\lib\RequestTracker.js:721:20)
  at async AssetGraphBuilder.runPathRequest (C:\Users\User\Projects\siemens-idn\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:722:18)     
  at async PromiseQueue._runFn (C:\Users\User\Projects\siemens-idn\node_modules\@parcel\utils\lib\PromiseQueue.js:88:7)
  at async PromiseQueue._next (C:\Users\User\Projects\siemens-idn\node_modules\@parcel\utils\lib\PromiseQueue.js:75:5)
```

**Comment by msimpson** [comment]
Still seeing this issue, opened #7020 in response.
