### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by SoftCreatR** [parcel-bundler/parcel#6987]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc
```js
{
  "extends": "@parcel/config-default"
}
```

## 🤔 Expected Behavior

Build without errors, if .parcelrc is used and extends `@parcel/config-default` (error doesn't occur without .parcelrc)

## 😯 Current Behavior

```
🚨 Build failed.

@parcel/core: Failed to resolve 'src/index.html'

@parcel/resolver-default: The "path" argument must be of type string. Received undefined

  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
  at validateString (internal/validators.js:124:11)
  at Object.isAbsolute (path.js:1133:5)
  at NodeResolver.resolveModule (/var/www/html/.yarn/cache/@parcel-node-resolver-core-npm-2.0.0-rc.0-355980cbe9-d671853069.zip/node_modules/@parcel/node-resolver-core/lib/NodeResolver.js:224:25)
  at async NodeResolver.resolve (/var/www/html/.yarn/cache/@parcel-node-resolver-core-npm-2.0.0-rc.0-355980cbe9-d671853069.zip/node_modules/@parcel/node-resolver-core/lib/NodeResolver.js:137:20)
  at async ResolverRunner.resolve (/var/www/html/.yarn/cache/@parcel-core-npm-2.0.0-nightly.843-402fcda29d-f28ce66615.zip/node_modules/@parcel/core/lib/requests/PathRequest.js:207:22)
  at async Object.run (/var/www/html/.yarn/cache/@parcel-core-npm-2.0.0-nightly.843-402fcda29d-f28ce66615.zip/node_modules/@parcel/core/lib/requests/PathRequest.js:104:16)
  at async RequestTracker.runRequest (/var/www/html/.yarn/cache/@parcel-core-npm-2.0.0-nightly.843-402fcda29d-f28ce66615.zip/node_modules/@parcel/core/lib/RequestTracker.js:721:20)
  at async AssetGraphBuilder.runPathRequest (/var/www/html/.yarn/cache/@parcel-core-npm-2.0.0-nightly.843-402fcda29d-f28ce66615.zip/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:722:18)
  at async PromiseQueue._runFn (/var/www/html/.yarn/cache/@parcel-utils-npm-2.0.0-nightly.845-27893e02cd-33e32a4407.zip/node_modules/@parcel/utils/lib/PromiseQueue.js:88:7)
  at async PromiseQueue._next (/var/www/html/.yarn/cache/@parcel-utils-npm-2.0.0-nightly.845-27893e02cd-33e32a4407.zip/node_modules/@parcel/utils/lib/PromiseQueue.js:75:5)
```

## 💁 Possible Solution

Upgrade to nightly. See comments below.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.843
| Node             | 14.17.6
| npm/Yarn         | 3.0.2
| Operating System | Ubuntu 20.04

**Comment by SoftCreatR** [comment]
Update: It seems, that I've installed `@parcel/config-default@2.0.0-rc.0`- After upgrading to `2.0.0-nightly.845`, the error given above is gone. However, building still fails:

```
🚨 Build failed.

Error: Failed to install @parcel/resolver-default: Yarn failed to install modules:Child process failed

  Error: Failed to install @parcel/resolver-default: Yarn failed to install modules:Child process failed
  at install (/var/www/html/.yarn/__virtual__/@parcel-package-manager-virtual-bfbec646c4/0/cache/@parcel-package-manager-npm-2.0.0-nightly.845-cb198e4687-6abd99b6d2.zip/node_modules/@parcel/package-manager/lib/installPackage.js:131:11)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async PromiseQueue._runFn (/var/www/html/.yarn/cache/@parcel-utils-npm-2.0.0-nightly.845-27893e02cd-33e32a4407.zip/node_modules/@parcel/utils/lib/PromiseQueue.js:88:7)
  at async PromiseQueue._next (/var/www/html/.yarn/cache/@parcel-utils-npm-2.0.0-nightly.845-27893e02cd-33e32a4407.zip/node_modules/@parcel/utils/lib/PromiseQueue.js:75:5)
```

**Comment by SoftCreatR** [comment]
Update: Looks like installing the nightly versions of all additional packages does the trick:

```
"@parcel/bundler-default": "2.0.0-nightly.839",
"@parcel/config-default": "2.0.0-nightly.845",
"@parcel/namer-default": "2.0.0-nightly.839",
"@parcel/packager-html": "2.0.0-nightly.839",
"@parcel/packager-raw": "2.0.0-nightly.839",
"@parcel/packager-raw-url": "2.0.0-nightly.2467",
"@parcel/resolver-default": "2.0.0-nightly.845",
"@parcel/runtime-browser-hmr": "2.0.0-nightly.839",
"@parcel/runtime-js": "2.0.0-nightly.839",
"@parcel/runtime-react-refresh": "2.0.0-nightly.839",
"@parcel/transformer-babel": "2.0.0-nightly.845",
"@parcel/transformer-css": "2.0.0-nightly.845",
"@parcel/transformer-html": "2.0.0-nightly.845",
"@parcel/transformer-js": "2.0.0-nightly.845",
"@parcel/transformer-jsonld": "2.0.0-nightly.2467",
"@parcel/transformer-postcss": "2.0.0-nightly.845",
"@parcel/transformer-posthtml": "2.0.0-nightly.845",
"@parcel/transformer-react-refresh-wrap": "2.0.0-nightly.845",
```

Dunno, if this behaves as designed, or if this is an issue with Yarn 2 (PnP).

**Comment by DJWassink** [comment]
I had the same issue and for me the upgrade to the latest nightlfy for the `@parcel/config-default` fixed this issue. 
I assume there is some new config required in the newer nightlies that didn't exist before.

**Comment by SoftCreatR** [comment]
Correct. In my case, some more packages were needed, i guess because of Yarn 2 with PnP enabled.
