### ISSUE TITLE
Unable to use @parcel/resolver-glob (again)

### ISSUE THREAD

**Issue by msimpson** [parcel-bundler/parcel#7020]
If I add `@parcel/resolver-glob` to a working project, the build fails.

`package.json`

```
{
  "name": "<redacted>",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "source": "source/index.html",
  "build": "build/index.html",
  "targets": {
    "main": false,
    "build": {}
  },
  "scripts": {
    "start": "parcel watch",
    "build": "parcel build",
    "electron": "electron .",
    "package": "node tasks/package.js",
    "msi": "node tasks/msi.js"
  },
  "author": "<redacted>",
  "license": "SEE LICENSE IN LICENSE",
  "private": true,
  "devDependencies": {
    "@parcel/config-default": "2.0.0-nightly.854",
    "@parcel/resolver-glob": "^2.0.0-nightly.2479",
    "@parcel/transformer-vue": "^2.0.0-nightly.2479",
    "electron": "^12.0.4",
    "electron-packager": "^15.2.0",
    "electron-wix-msi": "^3.2.0"
  },
  "dependencies": {
    "electron-serve": "^1.1.0",
    "parcel": "^2.0.0-nightly.855",
    "vue": "^3.1.5",
    "vue-router": "^4.0.10"
  }
}
```

`.parcelrc`

```
{

  "extends": "@parcel/config-default",

  "resolvers": [ "@parcel/resolver-glob" ],

  "transformers": {

    "*.svg|*.mp4": [ "@parcel/transformer-raw" ]

  }

}
```

`npm run build`

```
> <redacted>@1.0.0 build
> parcel build

🚨 Build failed.

@parcel/core: Failed to resolve 'source/index.html'

@parcel/resolver-glob: Cannot read property 'replace' of undefined

  TypeError: Cannot read property 'replace' of undefined
  at normalizeSeparators (C:\Users\User\Projects\<redacted>\node_modules\@parcel\resolver-glob\node_modules\@parcel\utils\lib\path.js:31:19)
  at isGlob (C:\Users\User\Projects\<redacted>\node_modules\@parcel\resolver-glob\node_modules\@parcel\utils\lib\glob.js:46:64)
  at Object.resolve (C:\Users\User\Projects\<redacted>\node_modules\@parcel\resolver-glob\lib\GlobResolver.js:79:30)
  at ResolverRunner.resolve (C:\Users\User\Projects\<redacted>\node_modules\@parcel\core\lib\requests\PathRequest.js:207:44)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Object.run (C:\Users\User\Projects\<redacted>\node_modules\@parcel\core\lib\requests\PathRequest.js:104:16)
  at async RequestTracker.runRequest (C:\Users\User\Projects\<redacted>\node_modules\@parcel\core\lib\RequestTracker.js:721:20)
  at async AssetGraphBuilder.runPathRequest (C:\Users\User\Projects\<redacted>\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:722:18)     
  at async PromiseQueue._runFn (C:\Users\User\Projects\<redacted>\node_modules\@parcel\utils\lib\PromiseQueue.js:88:7)
  at async PromiseQueue._next (C:\Users\User\Projects\<redacted>\node_modules\@parcel\utils\lib\PromiseQueue.js:75:5)
```

The mere addition of the module in the `.parcelrc` immediately causes an issue.

Here's a [ZIP archive](https://github.com/parcel-bundler/parcel/files/7288656/test.zip) of a test project.

Same behavior.

**Comment by devongovett** [comment]
You need to add `"..."` after `"@parcel/resolver-glob"` as in the example here: https://v2.parceljs.org/features/dependency-resolution/#glob-specifiers. That allows the default resolver to run after the glob resolver. Without it, you're overriding the default.

**Comment by msimpson** [comment]
@devongovett 

Downloaded the ZIP archive I provided, made the following change to `.parcelrc`:

```
{
  "extends": "@parcel/config-default",
  "resolvers": ["@parcel/resolver-glob", "..."]
}
```

Received the following:

```
🚨 Build failed.

@parcel/core: Failed to resolve 'index.html'

@parcel/resolver-glob: Cannot read property 'replace' of undefined

  TypeError: Cannot read property 'replace' of undefined
  at normalizeSeparators (C:\Users\User\Downloads\test\test\node_modules\@parcel\resolver-glob\node_modules\@parcel\utils\lib\path.js:31:19)
  at isGlob (C:\Users\User\Downloads\test\test\node_modules\@parcel\resolver-glob\node_modules\@parcel\utils\lib\glob.js:54:66)
  at Object.resolve (C:\Users\User\Downloads\test\test\node_modules\@parcel\resolver-glob\lib\GlobResolver.js:79:30)
  at ResolverRunner.resolve (C:\Users\User\Downloads\test\test\node_modules\parcel\node_modules\@parcel\core\lib\requests\PathRequest.js:207:44)        
  at async Object.run (C:\Users\User\Downloads\test\test\node_modules\parcel\node_modules\@parcel\core\lib\requests\PathRequest.js:104:16)
  at async RequestTracker.runRequest (C:\Users\User\Downloads\test\test\node_modules\parcel\node_modules\@parcel\core\lib\RequestTracker.js:721:20)     
  at async AssetGraphBuilder.runPathRequest
  (C:\Users\User\Downloads\test\test\node_modules\parcel\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:722:18)
  at async PromiseQueue._runFn (C:\Users\User\Downloads\test\test\node_modules\@parcel\utils\lib\PromiseQueue.js:88:7)
  at async PromiseQueue._next (C:\Users\User\Downloads\test\test\node_modules\@parcel\utils\lib\PromiseQueue.js:75:5)
```

**Comment by msimpson** [comment]
@devongovett

After changing the `.parcelrc` and forcibly updating to `2.0.0-nightly.2479` of `resolver-glob` it began to work.

**Comment by devongovett** [comment]
Yeah, when using nightlies you should pin them rather than using caret ranges. Otherwise semver does weird things.

This appeared to work with your project:

```json
"devDependencies": {
    "@parcel/config-default": "2.0.0-nightly.854",
    "@parcel/resolver-glob": "2.0.0-nightly.2479",
    "parcel": "2.0.0-nightly.855"
}
```

**Comment by msimpson** [comment]
@devongovett 

Thanks for the help. I'd recommend noting the functional nature of the ellipses in the documentation.

I intentionally removed them thinking it meant, "and other resolvers you may have."

Not, "a token used for merging the default configuration".

**Comment by devongovett** [comment]
Yeah, good idea. We do have a section that describes it in detail here but perhaps we could link it from the glob section too. https://v2.parceljs.org/features/plugins/#pipelines
