### ISSUE TITLE
[v2.rc-0] Neither bundle-analyzer nor bundle-buddy appears to work

### ISSUE THREAD

**Issue by mogelbrod** [parcel-bundler/parcel#7026]
# 🐛 bug report
Same issue as https://github.com/parcel-bundler/parcel/issues/6599 - none of following commands (some of which are listed in [the docs](https://parceljs.org/features/production/#bundle-analyzer)) appear to generate any additional output apart from the regular bundle.
```sh
parcel build src/index.html --reporter @parcel/reporter-bundle-buddy

parcel build src/index.html --reporter @parcel/reporter-bundle-analyzer
PARCEL_BUNDLE_ANALZYZER=1 parcel build src/index.html --reporter @parcel/reporter-bundle-analyzer
PARCEL_BUNDLE_ANALZYZER=1 parcel build src/index.html
```

The following throws an error on the other hand:
```sh
$ BUNDLE_BUDDY=true parcel build src/index.html --reporter @parcel/reporter-bundle-buddy

✨ Built in 23.91s

dist/index.html                671 B    15.74s
dist/index.04f664a3.css      2.02 KB    15.74s
dist/index.100d7ed1.js      695.1 KB    15.22s
dist/index.6136d69e.js     634.63 KB    15.22s
TypeError: event.bundleGraph.getDependencyResolution is not a function
    at /Users/victor/src/gql-pilot/node_modules/@parcel/reporter-bundle-buddy/lib/BundleBuddyReporter.js:46:46
    at /Users/victor/src/gql-pilot/node_modules/@parcel/core/lib/Graph.js:520:16
    at /Users/victor/src/gql-pilot/node_modules/@parcel/core/lib/Graph.js:520:16
    at /Users/victor/src/gql-pilot/node_modules/@parcel/core/lib/Graph.js:520:16
    at walk (/Users/victor/src/gql-pilot/node_modules/@parcel/core/lib/Graph.js:385:26)
    at walk (/Users/victor/src/gql-pilot/node_modules/@parcel/core/lib/Graph.js:407:22)
    at ContentGraph.dfs (/Users/victor/src/gql-pilot/node_modules/@parcel/core/lib/Graph.js:433:12)
    at BundleGraph.traverseBundle (/Users/victor/src/gql-pilot/node_modules/@parcel/core/lib/BundleGraph.js:699:24)
    at BundleGraph.traverseAssets (/Users/victor/src/gql-pilot/node_modules/@parcel/core/lib/BundleGraph.js:564:17)
    at PackagedBundle.traverseAssets (/Users/victor/src/gql-pilot/node_modules/@parcel/core/lib/public/Bundle.js:196:30)
```

#### package.json
```json
{
  "name": "test",
  "version": "0.0.1",
  "browserslist": [
    "defaults"
  ],
  "dependencies": {
    "@babel/plugin-proposal-optional-chaining": "^7.8.3",
    "@babel/preset-env": "^7.8.4",
    "@babel/preset-react": "^7.8.3",
    "babel-plugin-graphql-tag": "^3.3.0",
    "core-js": "^3.6.4",
    "parcel": "^2.0.0-rc.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "devDependencies": {
    "@babel/runtime": "^7.15.4",
    "@parcel/reporter-bundle-analyzer": "^2.0.0-nightly.1694",
    "@parcel/reporter-bundle-buddy": "^2.0.0-nightly.1902",
    "graphql": "^15.6.1"
  }
}
```

#### babel.config.json
```json
{
  "presets": [
    "@babel/preset-react"
  ],
  "plugins": [
    ["graphql-tag", { "strip": true }],
    "@babel/plugin-proposal-optional-chaining"
  ],
  "sourceType": "unambiguous"
}
```

## 🤔 Expected Behavior

Running `parcel build --reporter {REPORTER NAME}` (without having to provide both ENVars and a command line parameter) should generate the relevant meta files without throwing any error.

## 😯 Current Behavior

See first section.

## 🔦 Context

Currently impossible(?) to analyze the bundle created by parcel v2.

## 💻 Code Sample

N/A

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             |  15.4.0
| npm/Yarn         | 7.24.0
| Operating System | OSX

**Comment by mischnic** [comment]
You need to either use a nightly version or the rc for all 3 packages (and ideally a strict version range, because semver behaves strangely with prerelease versions). Autoinstall of these reporters is unfortunately somewhat broken until we are out of the prerelease phase.

**Comment by mogelbrod** [comment]
Thanks for the quick reply and suggestion @mischnic, it appears to have worked!
```sh
npm install parcel@2.0.0-rc.0 @parcel/reporter-bundle-analyzer@2.0.0-rc.0 @parcel/reporter-bundle-buddy@2.0.0-rc.0
parcel build src/index.html --reporter @parcel/reporter-bundle-analyzer # works
parcel build src/index.html --reporter @parcel/reporter-bundle-buddy # works
```
