### ISSUE TITLE
Getting falsy in reporter-bundle-analyzer assertion

### ISSUE THREAD

**Issue by dioptre** [parcel-bundler/parcel#7039]
# 🐛 bug report
Getting falsy in reporter-bundle-analyzer assertion

```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(map instanceof _utils().DefaultMap)


    at getBundleNode (/Users/a/Documents/st/sourcetable-site/node_modules/@parcel/reporter-bundle-analyzer/lib/BundleAnalyzerReporter.js:155:29)
    at async Promise.all (index 8)
    at async getBundleData (/Users/a/Documents/st/sourcetable-site/node_modules/@parcel/reporter-bundle-analyzer/lib/BundleAnalyzerReporter.js:133:16)
    at async /Users/a/Documents/st/sourcetable-site/node_modules/@parcel/reporter-bundle-analyzer/lib/BundleAnalyzerReporter.js:115:34
    at async Promise.all (index 0)
    at async Object.report (/Users/a/Documents/st/sourcetable-site/node_modules/@parcel/reporter-bundle-analyzer/lib/BundleAnalyzerReporter.js:78:5)
    at async ReporterRunner.report (/Users/a/Documents/st/sourcetable-site/node_modules/@parcel/core/lib/ReporterRunner.js:105:11)
    at async Parcel._build (/Users/a/Documents/st/sourcetable-site/node_modules/@parcel/core/lib/Parcel.js:449:7)
    at async Parcel.run (/Users/a/Documents/st/sourcetable-site/node_modules/@parcel/core/lib/Parcel.js:278:18)
    at async run (/Users/a/Documents/st/sourcetable-site/node_modules/parcel/lib/cli.js:369:7) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```
## 🎛 Configuration (.babelrc, package.json, cli command)
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "react-svg:*.svg": ["@parcel/transformer-svg-react"]
  },
  "reporters":  ["...", "parcel-reporter-static-files-copy", "@parcel/reporter-bundle-analyzer"]
}
```

## 🤔 Expected Behavior

Produce a bundle report

## 😯 Current Behavior
Build breaks with assertion error

## 💁 Possible Solution

#6658 

## 🔦 Context

Breaks build

## 🌍 Your Environment
Mac, all parcel versions "next"

**Comment by mischnic** [comment]
> all parcel versions "next"

What version exactly? It's likely that some Parcel packages here are incompatible with each other

**Comment by dioptre** [comment]
This was my package.json from yesterday:

```
  "devDependencies": {
    "@parcel/config-default": "next",
    "@parcel/core": "next",
    "@parcel/transformer-image": "next",
    "@parcel/transformer-sass": "next",
    "@parcel/transformer-svg-react": "next",
    "@parcel/transformer-yaml": "next",
    "parcel": "next",
    "parcel-reporter-static-files-copy": "^1.3.0",
    "prop-types": "^15.7.2"
  },
```

**Comment by mischnic** [comment]
1. My question was about the actual versions that `next` resolves
2. `@parcel/reporter-bundle-analyzer` isn't even listed in your snippet

**Comment by dioptre** [comment]
Ah my bad, sorry I removed it as it was killing my build.

It was "next" after a yarn install 24 hours ago.

Which I think was:
2.0.0-nightly.2491
***@***.***/reporter-bundle-analyzer/v/2.0.0-nightly.2491>
