### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module (weak-lru-cache)

### ISSUE THREAD

**Issue by pYr0x** [parcel-bundler/parcel#7106]
# 🐛 bug report

i tried to start with the basic example https://parceljs.org/getting-started/webapp/
adding all the files and run `npx parcel src/index.html`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "can-parcel",
  "version": "1.0.0",
  "description": "",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "watch": "parcel watch",
    "build": "parcel build",
    "foo": "parcel src/app.js --no-cache"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.0.0"
  }
}
```

## 🤔 Expected Behavior

i should open `http://localhost:1234/` on the browser and see "test" in the console.

## 😯 Current Behavior

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\.........\node_modules\weak-lru-cache\index.js
require() of ES modules is not supported.
require() of C:\Users\.........\node_modules\weak-lru-cache\index.js from C:\Users\.........\node_modules\lmdb-store\caching.js is an ES module file as it is a .js file whose nearest parent package.json contain
s "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\.........\node_modules\weak-lru-cache\package.json.
```

## 💻 Code Sample

src/index.html
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>My First Parcel App</title>
  <script type="module" src="src/app.js"></script>
</head>
<body>
<h1>Hello, World!</h1>
</body>
</html>
```

src/app.js
```
console.log("test");
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | v12.16.3
| npm/Yarn         | 8.1.0
| Operating System | Windows 10

**Comment by pYr0x** [comment]
it seems, that in node `v12.16.3` the ECMAScript Modules (ESM) implementation was not finalized and i have still to use `--experimental-modules` flag.
can anyone confirm this?
maybe drop support for node 12?

if i use `node --experimental-modules node_modules/parcel/lib/bin.js`  node said `(node:3200) ExperimentalWarning: The ESM module loader is experimental.` and the build is working

**Comment by TkDodo** [comment]
FYI, I was getting a different error from `weak-lru-cache` when trying to upgrade from parcel 1 to v2:

```
node_modules/weak-lru-cache/index.js:1
(function (exports, require, module, __filename, __dirname) { import { LRFUExpirer, EXPIRED_ENTRY } from './LRFUExpirer.js'
                                                                     ^
SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
```

Googling let me to this issue, so I was checking that we were also using node `v12.6.0`, and upgrading to `v16.11.1` made the issue go away 🤷

**Comment by MikeMcMahon** [comment]
similar issue, on node 14.15.3 i get

```
SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:101:7)
    at NativeCompileCache._moduleCompile (/Users/mikemcmahon/GolandProjects/ctrlstack/fe/.yarn/cache/v8-compile-cache-npm-2.2.0-b4d8f03dca-1efc994640.zip/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/mikemcmahon/GolandProjects/ctrlstack/fe/.yarn/cache/v8-compile-cache-npm-2.2.0-b4d8f03dca-1efc994640.zip/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.external_module_.Module._load (/Users/mikemcmahon/GolandProjects/ctrlstack/fe/.pnp.js:24327:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/mikemcmahon/GolandProjects/ctrlstack/fe/.yarn/cache/v8-compile-cache-npm-2.2.0-b4d8f03dca-1efc994640.zip/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/mikemcmahon/GolandProjects/ctrlstack/fe/.yarn/unplugged/lmdb-store-npm-1.6.9-64dd487a5e/node_modules/lmdb-store/caching.js:1:88)
    at Module._compile (/Users/mikemcmahon/GolandProjects/ctrlstack/fe/.yarn/cache/v8-compile-cache-npm-2.2.0-b4d8f03dca-1efc994640.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

switching to parcel version `2.0.0-beta-3.1` doesn't have this issue.

**Comment by mkane827** [comment]
I'm also having this issue on Node `12.13.1`. Haven't found my workaround yet.

# EDIT
I just realized that when you install parcel it tells you to update node.

**Comment by mischnic** [comment]
Can someone provide a reproduction for this (especially including package.json and a lockfile)? Seems to work fine for me

**Comment by mkane827** [comment]
My issue was 100% because I needed to update node. Once I did that it worked perfectly.

**Comment by aaron-goff** [comment]
@mischnic I'm currently running into this. Using node 14.18.1 and npm 7.19.1.

```
/Users/aarongoff/Code/Project/node_modules/weak-lru-cache/index.js:1
(function (exports, require, module, __filename, __dirname) { import { LRFUExpirer, EXPIRED_ENTRY } from './LRFUExpirer.js'
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:84:7)
    at NativeCompileCache._moduleCompile (/Users/aarongoff/Code/Project/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/aarongoff/Code/Project/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (/Users/aarongoff/Code/Project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/aarongoff/Code/Project/node_modules/lmdb-store/caching.js:1:88)
    at Module._compile (/Users/aarongoff/Code/Project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

package.json:
```
{
  "name": "website",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "clean": "rm -rf 'website/wwwroot/index.css' website/wwwroot/index.css.map website/wwwroot/index.js website/wwwroot/index.js.map",
    "start": "npm run clean && npm run lint && parcel watch src/*.ts src/*.tsx src/*.css --dist-dir website/wwwroot",
    "lambda": "npm run lint && parcel watch AWS/Lambda/*.ts",
    "lambda-build": "parcel build --no-content-hash --no-source-maps AWS/Lambda/*.ts",
    "build": "npm run clean && parcel build --no-content-hash --no-source-maps src/*.ts src/*.tsx src/*.css --dist-dir website/wwwroot",
    "test": "jest",
    "check-types": "tsc",
    "lint": "npm run cy:clean && eslint src/**/*.ts src/**/*.tsx cypress/**/*.ts",
    "validate": "npm-run-all --parallel check-types lint",
    "next-dev": "next dev",
    "prepare": "cd $(git rev-parse --show-toplevel) && husky install",
    "pretty-quick": "pretty-quick --staged",
    "stop-only": "stop-only --folder cypress",
    "cypress": "npx cypress open",
    "cy:clean": "rm -rf cypress/screenshots cypress/videos cypress/reports mochawesome-report",
    "cy:headless": "npx cypress run",
    "cy:chrome": "npm run cy:headless -- --browser chrome",
    "cy:firefox": "npm run cy:headless -- --browser firefox",
    "cy:chromium": "npm run cy:headless -- --browser chromium",
    "cy:chrome-mobile": "npm run cy:headless -- --browser chrome --config viewportWidth=414,viewportHeight=846",
    "cy:run-all-browsers": "CYPRESS_EXCLUDE_TAGS=AXE,AUDIT,PERCY npm-run-all cy:chrome cy:firefox cy:chromium cy:chrome-mobile",
    "cy:smoke": "CYPRESS_INCLUDE_TAGS=SMOKE npm run cy:chrome",
    "cy:axe": "CYPRESS_INCLUDE_TAGS=AXE npm run cy:chrome",
    "cy:audit": "CYPRESS_INCLUDE_TAGS=AUDIT npm run cy:chrome",
    "cy:percy": "CYPRESS_INCLUDE_TAGS=PERCY percy exec -- npm run cy:chrome"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "normalize.css": "^8.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "what-input": "^5.2.10"
  },
  "devDependencies": {
    "@percy/cli": "^1.0.0-beta.70",
    "@percy/cypress": "^3.1.1",
    "@testing-library/react": "^12.1.2",
    "@types/node": "^16.11.5",
    "@types/react": "^17.0.30",
    "@types/react-dom": "^17.0.9",
    "@typescript-eslint/eslint-plugin": "^5.1.0",
    "@typescript-eslint/parser": "^5.1.0",
    "autoprefixer": "^10.3.7",
    "axe-core": "^4.3.4",
    "cssnano": "^5.0.8",
    "cypress": "^8.7.0",
    "cypress-audit": "^1.1.0",
    "cypress-axe": "^0.13.0",
    "cypress-tags": "^0.3.0",
    "cypress-teamcity-reporter": "^3.0.0",
    "eslint": "^7.2.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "^2.25.2",
    "husky": "^7.0.0",
    "jest": "^27.3.1",
    "mocha": "^9.1.3",
    "mochawesome": "^6.3.1",
    "npm-run-all": "^4.1.5",
    "parcel": "^2.0.0",
    "postcss": "^8.3.9",
    "postcss-custom-media": "^8.0.0",
    "postcss-custom-properties": "^12.0.0",
    "postcss-import": "^14.0.2",
    "postcss-inline-svg": "^5.0.0",
    "postcss-modules": "^4.2.2",
    "postcss-nesting": "^8.0.1",
    "postcss-url": "^10.1.3",
    "prettier": "^2.4.1",
    "pretty-quick": "^3.1.1",
    "stop-only": "^3.1.2",
    "tailwindcss": "^2.2.17",
    "ts-jest": "^27.0.7",
    "typescript": "^4.4.4"
  }
}
```

package-lock.json:
[package-lock.txt](https://github.com/parcel-bundler/parcel/files/7550075/package-lock.txt)
Added as a `.txt` file, but should be able to just switch the type back to `.json`.

I'm getting the error when running our build command, `"npm run clean && parcel build --no-content-hash --no-source-maps src/*.ts src/*.tsx src/*.css --dist-dir website/wwwroot"`. It definitely is failing on the parcel build step, as I get the error when running `npx parcel build`. Let me know if you need any more information.

Edit: [Like this comment, using `2.0.0-beta.3.1`, I had no issues](https://github.com/parcel-bundler/parcel/issues/7106#issuecomment-969223280)

**Comment by qsg1215** [comment]
old: 
{
parcel:'1.12.3' // delete
}
new {
 "parcel-bundler": "^1.12.5"  //add
}

**Comment by SokratisVidros** [comment]
Same error with Node: `v14.16.0`, NPM: `v6.14.11`, Parcel: `v2.0.1`.

**Comment by mischnic** [comment]
@aaron-goff That seems to work correctly for me

**Comment by chuckdries** [comment]
We're also seeing this issue, but I'm not able to reproduce it in a fresh repo. Downgrading parcel to parcel@2.0.0-beta.3.1 also solves it for us. I will continue trying to get a minimal reproduction.
- node 12.19.0
- yarn 2.4.0
- using yarn pnp and yarn workspaces

**Comment by mischnic** [comment]
Can you determine the version of weak-lru-cache installed and also which package dependends on it (e.g. with `yarn why weak-lru-cache`)?

**Comment by chuckdries** [comment]
```
└─ lmdb-store@npm:1.6.14
   └─ weak-lru-cache@npm:1.1.3 (via npm:^1.0.0)
```

**Comment by chuckdries** [comment]
So, after more digging, we realized it's tied to the version of yarn that our workspace is using (TIL yarn stores a copy of itself in the workspace). With yarn 3 it works, but with yarn 2.4 it breaks. Reproduction in this repo https://github.com/chuckdries/parcel-weak-lru-cache-module-issue.

We're going to be upgrading yarn, but this might still be worth looking into for people that can't for whatever reason
