### ISSUE TITLE
Raw bundles must only contain one asset

### ISSUE THREAD

**Issue by louis77** [parcel-bundler/parcel#7152]
# 🐛 bug report

Whatever I do, I always get the following error message when running parcel:

```
Server running at http://localhost:1234
× Build failed.

@parcel/packager-raw: Raw bundles must only contain one asset

  AssertionError [ERR_ASSERTION]: Raw bundles must only contain one asset
  at Object.package (v1\node_modules\@parcel\packager-raw\lib\RawPackager.js:40:23)
  at PackagerRunner.package
  (\node_modules\parcel\node_modules\@parcel\core\lib\PackagerRunner.js:294:27)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async PackagerRunner.getBundleResult
  (\node_modules\parcel\node_modules\@parcel\core\lib\PackagerRunner.js:253:20)
  at async PackagerRunner.getBundleInfo
  (\node_modules\parcel\node_modules\@parcel\core\lib\PackagerRunner.js:239:9)
  at async PackagerRunner.run
  (\node_modules\parcel\node_modules\@parcel\core\lib\PackagerRunner.js:160:183)
  at async Child.handleRequest (\node_modules\parcel\node_modules\@parcel\workers\lib\child.js:217:9)
```
I've dumped the `asset` variable to the console and get a list of assets:

```
[
Asset(v1\node_modules\leaflet\dist\images\layers-2x.png)
]
[ Asset(v1\css\images\ui-icons_555_256x240.png) ]
[ Asset(v1\css\images\ui-icons_fff_256x240.png) ]
[
Asset(v1\assets\fonts\glyphicons-halflings-regular.eot)
]
[
Asset(v1\assets\fonts\glyphicons-halflings-regular.woff)
]
[ Asset(v1\assets\fonts\glyphicons-regular.eot) ]
[ Asset(v1\assets\fonts\glyphicons-regular.woff) ]
[
Asset(v1\node_modules\leaflet\dist\images\layers.png)
]
[
Asset(v1\node_modules\leaflet\dist\images\marker-icon.png)
]
[ Asset(v1\css\images\ui-icons_ffffff_256x240.png) ]
[ Asset(v1\css\images\ui-icons_cc0000_256x240.png) ]
``` 

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": ["@parcel/config-default"],
  "transformers": {
    "*.svelte": ["parcel-transformer-svelte"],
    "*.hbs": ["@andreyvolokitin/parcel-transformer-handlebars"]
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 |
| Node             | v14.18.0 |
| npm         | 6.14.15 |
| Operating System | Win 11 |

**Comment by louis77** [comment]
Ok, so quick update on this issue. It turns out that the console output from the assets is actually from those which worked. `console.log` didn't flush output (console.log is async on windows). So, I put the assets into the assert error message and got this:

```
@parcel/packager-raw: Raw bundles must only contain one asset (4 [
Asset(v1\templates\filter_feature.hbs),
Asset(v1\templates\filter_quality.hbs),
Asset(-v1\templates\filter_type.hbs),
Asset(v1\templates\filter_tags.hbs)
])
```

So for some reasons the handlebars templates appear in the packager-raw process. I'm new to Parcel so I assume it must have something to do with the `@andreyvolokitin/parcel-transformer-handlebars` transformer.

**Comment by louis77** [comment]
For the record, it was an issue with the handlebars transformer `@andreyvolokitin/parcel-transformer-handlebars`. Instead, I use this now which works perfectly:

`@anikin/parcel-transformer-handlebars-precompile`

Closing the issue, not related to parcel-bundler.
