### ISSUE TITLE
🐛 Error recovery from JS errors

### ISSUE THREAD

**Issue by adamreisnz** [parcel-bundler/parcel#718]
Similar to #632, it seems there is no proper error recovery from JS errors.
My parcel process got stuck on the following error and didn't restart/rebuild after I changed the files:

```
🚨  app/index.js: Cannot resolve dependency './components/help/help.js' at app/components/    at /Users/Adam/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/Adam/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/Adam/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/Adam/.config/yarn/global/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
^C
```

Had to restart the process for it to build again.

**Comment by devongovett** [comment]
Solved in Parcel 2.
