### ISSUE TITLE
'parcel serve' semver.js errors working in "parcel": "1.12.3", failing in "^1.12.3" and "^2.0.0"

### ISSUE THREAD

**Issue by intronic** [parcel-bundler/parcel#7217]
# 🐛 bug report

I tried upgrading parcel in `package.json` from `"1.12.3"` to `"^1.12.3"` (resolves to 1.12.4) and to `"^2.0.0"`

When I do the upgrade, both versions fail, with slightly different errors, at different lines of `node_modules/semver/semver.js`

The `^2.0.0` error is very similar to #6828 :
```
TypeError: Invalid comparator: npm:@preact/compat@^17.0.3
  at Comparator.parse (/purescript-react-realworld/node_modules/semver/semver.js:754:11)
```
 

The `^1.12.3` error is also in `semver.js`
```
Invalid Version: undefined
    at new SemVer (/purescript-react-realworld/node_modules/semver/semver.js:314:11)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm using yarn (`1.22.17`), no .babelrc, Ubuntu linux.

To replicate the working version, see this branch:
```
https://github.com/intronic/purescript-react-realworld/tree/parcel-serve-working-1.12.3
```

To replicate the failing versions, see these 2 branches:
```
https://github.com/intronic/purescript-react-realworld/tree/parcel-serve-broken-tilde-2.0.0
```
```
https://github.com/intronic/purescript-react-realworld/tree/parcel-serve-broken-tilde-1.12.3
```
The only differences are in the parcel versions (and the `yarn.lock` package versions as a consequence):
```
$ git diff parcel-serve-working-1.12.3 parcel-serve-broken-tilde-2.0.0
diff --git a/package.json b/package.json
...
-    "serve:parcel": "parcel serve --no-source-maps --out-dir serve index.html",
+    "serve:parcel": "parcel serve --no-source-maps --dist-dir serve index.html",
...

   "devDependencies": {
-    "parcel": "1.12.3",
+    "parcel": "^2.0.0",
```

```
$ git diff parcel-serve-working-1.12.3 parcel-serve-broken-tilde-1.12.3
diff --git a/package.json b/package.json
...
-    "parcel": "1.12.3",
+    "parcel": "^1.12.3",
...
diff --git a/yarn.lock b/yarn.lock
...
```

## 🤔 Expected Behavior

* Clone that repo and run the following command to do a clean / install / build and see the 'parcel serve' running on port 1234, all good, yay:
```
$ git checkout parcel-serve-working-1.12.3
$ yarn clean; yarn install ; yarn serve
...
$ parcel serve --no-source-maps --out-dir serve index.html
Server running at http://localhost:1234 
✨  Built in 1.57s.
```

## 😯 Current Behavior

* Clone that repo and run the following to see the failure on version 2.0.0; clean/install/serve, then `@parcel/transformer-js: Invalid comparator ` error:
```
$ git checkout -b parcel-serve-broken-tilde-2.0.0
$ yarn clean ; yarn install ; yarn serve

           Src   Lib   All
Warnings   1     95    96 
Errors     0     0     0  
[info] Build succeeded.
$ parcel serve --no-source-maps --dist-dir serve index.html
Server running at http://localhost:1234
🚨 Build failed.

@parcel/transformer-js: Invalid comparator: npm:@preact/compat@^17.0.3

  TypeError: Invalid comparator: npm:@preact/compat@^17.0.3
  at Comparator.parse (/purescript-react-realworld/node_modules/semver/semver.js:754:11)
  at new Comparator (/purescript-react-realworld/node_modules/semver/semver.js:737:8)
  at Range.<anonymous> (/purescript-react-realworld/node_modules/semver/semver.js:925:12)
  at Array.map (<anonymous>)
  at Range.parseRange (/purescript-react-realworld/node_modules/semver/semver.js:924:13)
  at Range.<anonymous> (/purescript-react-realworld/node_modules/semver/semver.js:867:17)
  at Array.map (<anonymous>)
  at new Range (/purescript-react-realworld/node_modules/semver/semver.js:866:40)
  at Function.minVersion (/purescript-react-realworld/node_modules/semver/semver.js:1306:11)
  at loadConfig (/purescript-react-realworld/node_modules/@parcel/transformer-js/lib/JSTransformer.js:222:127)

```

* and the following to see the `1.12.4` error (`^1.12.3`)  `Invalid Version: undefined`:

```
$  git checkout parcel-serve-broken-tilde-1.12.3
$ yarn clean; yarn install ; yarn serve
....
           Src   Lib   All
Warnings   1     95    96 
Errors     0     0     0  
[info] Build succeeded.
$ parcel serve --no-source-maps --out-dir serve index.html
Server running at http://localhost:1234 
🚨  /purescript-react-realworld/index.js: Invalid Version: undefined
    at new SemVer (/purescript-react-realworld/node_modules/semver/semver.js:314:11)
    at compare (/purescript-react-realworld/node_modules/semver/semver.js:647:10)
    at lt (/purescript-react-realworld/node_modules/semver/semver.js:688:10)
    at /purescript-react-realworld/node_modules/@babel/preset-env/lib/index.js:275:22
    at Object.default (/purescript-react-realworld/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12)
    at getEnvPlugins (/purescript-react-realworld/node_modules/parcel/src/transforms/babel/env.js:62:34)
    at getEnvConfig (/purescript-react-realworld/node_modules/parcel/src/transforms/babel/env.js:12:25)
    at async getBabelConfig (/purescript-react-realworld/node_modules/parcel/src/transforms/babel/config.js:32:19)
    at async babelTransform (/purescript-react-realworld/node_modules/parcel/src/transforms/babel/transform.js:6:16)
    at async JSAsset.pretransform (/purescript-react-realworld/node_modules/parcel/src/assets/JSAsset.js:83:5)
```

## 💁 Possible Solution

There are a lot of differences in the transitive dependencies when just changing between parcel versions `1.12.3`, `1.12.4`, and `2.0.0`.
The different parcel packages use possibly conflicting package dependencies.

The error here (and in the other report #6828) might  indicate a problem with parsing unusual version strings, like:
```
    "react": "npm:@preact/compat@^17.0.3",
    "react-dom": "npm:@preact/compat@^17.0.3"
```

## 🔦 Context

I'm trying to upgrade a project past parcel `1.12.3` but the 'parcel serve' command is failing so i'm stuck with the old version if i want parcel serve.
 

## 💻 Code Sample

See above for repo with branches to reproduce positive/negative examples.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 (ok) -> 1.12.4 (fail) -> 2.0.0 (fail)
| Node             | v16.10.0
| npm/Yarn         | yarn 1.22.17
| Operating System |Ubuntu 20.04.3 LTS

**Comment by kzc** [comment]
Have you tried `--no-scope-hoist` ?

**Comment by intronic** [comment]
that is unknown option for serve?
```
npx parcel serve --no-source-maps --no-scope-hoist --dist-dir serve index.html
error: unknown option '--no-scope-hoist'
```
Same problem in parcel 2.0.1

**Comment by intronic** [comment]
Meanwhile for anyone with the same, my particular problem can be solved by using a different syntax for alias in `package.json`:
https://preactjs.com/guide/v10/getting-started#aliasing-in-parcel
```
  "alias": {
    "react": "preact/compat",
    "react-dom": "preact/compat"
  },
```
and remove dependencies:
```
    "react": "npm:@preact/compat@^17.0.3",
    "react-dom": "npm:@preact/compat@^17.0.3"
```
