### ISSUE TITLE
`export * as x from "..."` are never deferred

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#7227]
# 🐛 bug report

export-namespace-as reexports are never deferred, even if they are statically unused.

## 🤔 Expected Behavior

If `b` isn't imported, then `export * as b from "./other.js";` can be deferred.

## 😯 Current Behavior

It's not deferred.

## 💁 Possible Solution

https://github.com/parcel-bundler/parcel/blob/c8a64c9a533072c12681ca0805d1e4d7481ee53d/packages/core/core/src/AssetGraph.js#L390

## 💻 Code Sample

```json
{
	"sideEffects": [
		"index.js"
	]
}
```

```js
// index.js
import { a } from "./lib.js";
console.log(a);

// lib.js
export const a = 2;
export * as b from "./other.js";

// other.js
export const x = 22;
export const y = 33;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | c8a64c9a533072c12681ca0805d1e4d7481ee53d

**Comment by rmja** [comment]
I am also having this issue. Basically what I want is to have something like this in `index.ts`:

```ts
export * as SomeExternalName from "./internal-module-with-exports;
```

So that the consumer of the library can do:

```ts
import { SomeExternalName } from "my-lib";
SomeExternalName.someFunction();
```

@mischnic Have you found a workaround?

**Comment by mischnic** [comment]
Are you seeing some error?

This issue is about an optimization to include less unused code in the final bundle.

**Comment by rmja** [comment]
@mischnic I think it is related to this:
https://github.com/parcel-bundler/parcel/issues/5911

**Comment by rmja** [comment]
I get this error:
```
> parcel build

🚨 Build failed.

@parcel/transformer-typescript-types: node.exportClause.elements is not iterable

  TypeError: node.exportClause.elements is not iterable
  at visit (C:\Source\Utiliread\src\ur-policystore-client\node_modules\@parcel\transformer-typescript-types\lib\collect.js:78:47)
  at visitNodes (C:\Source\Utiliread\src\ur-policystore-client\node_modules\typescript\lib\typescript.js:87646:48)
  at Object.visitEachChild (C:\Source\Utiliread\src\ur-policystore-client\node_modules\typescript\lib\typescript.js:88126:56)
  at visit (C:\Source\Utiliread\src\ur-policystore-client\node_modules\@parcel\transformer-typescript-types\lib\collect.js:124:43)
  at visitNode (C:\Source\Utiliread\src\ur-policystore-client\node_modules\typescript\lib\typescript.js:87593:23)
  at Object.visitEachChild (C:\Source\Utiliread\src\ur-policystore-client\node_modules\typescript\lib\typescript.js:88123:222)
  at visit (C:\Source\Utiliread\src\ur-policystore-client\node_modules\@parcel\transformer-typescript-types\lib\collect.js:124:43)
  at visitNodes (C:\Source\Utiliread\src\ur-policystore-client\node_modules\typescript\lib\typescript.js:87646:48)
  at visitLexicalEnvironment (C:\Source\Utiliread\src\ur-policystore-client\node_modules\typescript\lib\typescript.js:87686:22)
  at Object.visitEachChild (C:\Source\Utiliread\src\ur-policystore-client\node_modules\typescript\lib\typescript.js:88234:55)
```

**Comment by rmja** [comment]
Year, I guess that is in fact the issue that I am having. Thought they were related based on the title.

**Comment by mverissimo** [comment]
Any update on this?
