### ISSUE TITLE
Parcel 2: ReferenceError: this hasn't been initialised - super() hasn't been called

### ISSUE THREAD

**Issue by sseidel16** [parcel-bundler/parcel#7235]
# 🐛 bug report

Some very odd behavior surrounding child/parent classes with async arrow functions occurs in Parcel 2 when browserslist is added to package.json. Maybe SWC fault?

`main.ts`:

```
class Parent { };

class Child1 extends Parent {

    constructor() {
        super();
        console.log('OK');
    }

    private asyncFunc = async () => {
        this.doNothing();
    };

    private doNothing = () => { };

};

// same as Child1 with functions reordered
class Child2 extends Parent {

    constructor() {
        super();
        console.log('OK');
    }

    private doNothing = () => { };

    private asyncFunc = async () => {
        this.doNothing();
    };

};

// this succeeds
new Child1();

// this fails with ReferenceError: this hasn't been initialised - super() hasn't been called
new Child2();
```

## 🎛 Configuration (.babelrc, package.json, cli command)

No `.babelrc`
No `.parcelrc`
`package.json`:

```
{
    "name": "parcel-bug",
    "version": "1.0.0",
    "dependencies": {},
    "scripts": {
        "build": "parcel build ./src/main.ts"
    },
    "browserslist": "> 0.2%",
    "devDependencies": {
        "parcel": "2.0.0"
    },
    "description": "",
    "keywords": [],
    "author": "Stephen Seidel",
    "license": "ISC"
}
```

## 🤔 Expected Behavior

`OK` should be logged 2 times

## 😯 Current Behavior

```
OK
/Users/steseide/Documents/ProjectSwc2/dist/main.js:1 [lots of minified code here]

ReferenceError: this hasn't been initialised - super() hasn't been called
    at r (/Users/steseide/Documents/ProjectSwc2/dist/main.js:1:96)
    at new i (/Users/steseide/Documents/ProjectSwc2/dist/main.js:1:8144)
    at /Users/steseide/Documents/ProjectSwc2/dist/main.js:1:8460
    at Object.<anonymous> (/Users/steseide/Documents/ProjectSwc2/dist/main.js:1:8466)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

## 💁 Possible Solution

No idea how to fix this glitch. It seems extremely weird.

## 🔦 Context

This randomly came up in a project of mine and I iterated with several different versions of the code to find out where it went wrong.

## 💻 Code Sample

See above!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 |
| Node             | 14.16.1 |
| npm/Yarn         | 6.14.12 |
| Operating System | Mac |

**Comment by sseidel16** [comment]
Possibly related to [this issue](https://github.com/parcel-bundler/parcel/issues/7147)

**Comment by poislagarde** [comment]
This bug bit me while trying to develop a Transformer. Seems to be related to how Parcel is transpiling classes with async members.

My `browserslist` is `> 1%, last 2 versions, not dead`

Source code:

```
// this is a class expression part of a bigger generated file
class extends TwingTemplate {
  constructor(environment) {
    super(environment)

    this._source = new this.Source(
      ``,
      `e10576113ec1c33c06c0e5213e4c77e1a257721431f0a454eedd7c891e35eb79`
    )

    let aliases = new this.Context()

    this.blockHandlers = new Map([
      [
        'card_head',
        async (context, outputBuffer, blocks = new Map()) => {
          let aliases = this.aliases.clone()
        },
      ],
      [
        'card_body',
        async (context, outputBuffer, blocks = new Map()) => {
          let aliases = this.aliases.clone()
        },
      ],
      [
        'card_foot',
        async (context, outputBuffer, blocks = new Map()) => {
          let aliases = this.aliases.clone()
        },
      ],
    ])
  }

  async doDisplay(context, outputBuffer, blocks = new Map()) {
    let aliases = this.aliases.clone()

    outputBuffer.echo(`
  <div class="card">
  <div class="card-header">
  `)
    outputBuffer.echo(
      await this.traceableRenderBlock(14, this.source)(
        'card_head',
        context.clone(),
        outputBuffer,
        blocks
      )
    )
    outputBuffer.echo(`    </div>
  <div class="card-body">
  `)
    outputBuffer.echo(
      await this.traceableRenderBlock(17, this.source)(
        'card_body',
        context.clone(),
        outputBuffer,
        blocks
      )
    )
    outputBuffer.echo(`    </div>
  `)
    if (context.has(`card_footer`) ? context.get(`card_footer`) : null) {
      outputBuffer.echo(`        <div class="card-footer">
  `)
      outputBuffer.echo(
        await this.traceableRenderBlock(21, this.source)(
          'card_foot',
          context.clone(),
          outputBuffer,
          blocks
        )
      )
      outputBuffer.echo(`        </div>
  `)
    }
    outputBuffer.echo(`</div>`)
  }

  get isTraitable() {
    return false
  }
}
```

Transpiled code (comments added by me):
```
function (TwingTemplate) {
    "use strict";

// _inherits
    $64fc7f36b05addcd$export$2e2bcd8739ae039(_class, TwingTemplate);
    function _class(environment) {
        $4157fc935b703f38$export$2e2bcd8739ae039(this, _class);
        var _this2;

// _assert_this_initialized -- error is thrown inside here because _this2 is undefined
        var _this1 = $733bad68c43ec620$export$2e2bcd8739ae039(_this2);
        _this2 = $2447e84f18ded1d7$export$2e2bcd8739ae039(this, $59ba81f3a69e444e$export$2e2bcd8739ae039(_class).call(this, environment));
        _this2._source = new _this2.Source("", "e10576113ec1c33c06c0e5213e4c77e1a257721431f0a454eedd7c891e35eb79");
        var aliases1 = new _this2.Context();
        _this2.blockHandlers = new Map([
            [
                'card_head',
                function(context, outputBuffer) {
                    var _ref = $1fed9fc3d70a7ca8$export$2e2bcd8739ae039((/*@__PURE__*/$parcel$interopDefault($f110eb6e8c8d50db$exports)).mark(function _callee(context, outputBuffer, param) {
                        var blocks, aliases;
                        return (/*@__PURE__*/$parcel$interopDefault($f110eb6e8c8d50db$exports)).wrap(function _callee$(_ctx) {
                            while(1)switch(_ctx.prev = _ctx.next){
                                case 0:
                                    blocks = param === void 0 ? new Map() : param;
                                    aliases = _this3.aliases.clone();
                                case 2:
                                case "end":
                                    return _ctx.stop();
                            }
                        }, _callee);
                    }));
                    return function() {
                        return _ref.apply($733bad68c43ec620$export$2e2bcd8739ae039(_this2), arguments);
                    };
                }()
            ],
            [
                'card_body',
                function(context, outputBuffer) {
                    var _ref = $1fed9fc3d70a7ca8$export$2e2bcd8739ae039((/*@__PURE__*/$parcel$interopDefault($f110eb6e8c8d50db$exports)).mark(function _callee(context, outputBuffer, param) {
                        var blocks, _this3, aliases;
                        return (/*@__PURE__*/$parcel$interopDefault($f110eb6e8c8d50db$exports)).wrap(function _callee$(_ctx) {
                            while(1)switch(_ctx.prev = _ctx.next){
                                case 0:
                                    blocks = param === void 0 ? new Map() : param;
                                    _this3 = _this;
                                    aliases = _this.aliases.clone();
                                case 3:
                                case "end":
                                    return _ctx.stop();
                            }
                        }, _callee);
                    }));
                    return function() {
                        return _ref.apply($733bad68c43ec620$export$2e2bcd8739ae039(_this2), arguments);
                    };
                }()
            ],
            [
                'card_foot',
                function(context, outputBuffer) {
                    var _ref = $1fed9fc3d70a7ca8$export$2e2bcd8739ae039((/*@__PURE__*/$parcel$interopDefault($f110eb6e8c8d50db$exports)).mark(function _callee(context, outputBuffer, param) {
                        var blocks, _this, aliases;
                        return (/*@__PURE__*/$parcel$interopDefault($f110eb6e8c8d50db$exports)).wrap(function _callee$(_ctx) {
                            while(1)switch(_ctx.prev = _ctx.next){
                                case 0:
                                    blocks = param === void 0 ? new Map() : param;
                                    _this = _this1;
                                    aliases = _this1.aliases.clone();
                                case 3:
                                case "end":
                                    return _ctx.stop();
                            }
                        }, _callee);
                    }));
                    return function() {
                        return _ref.apply($733bad68c43ec620$export$2e2bcd8739ae039(_this2), arguments);
                    };
                }()
            ]
        ]);
        return _this2;
    }
    $3027f5da6d67258f$export$2e2bcd8739ae039(_class, [
        {
            key: "doDisplay",
            value: function doDisplay(context, outputBuffer, param) {
                var blocks = param === void 0 ? new Map() : param;
                return $1fed9fc3d70a7ca8$export$2e2bcd8739ae039((/*@__PURE__*/$parcel$interopDefault($f110eb6e8c8d50db$exports)).mark(function _callee() {
                    var aliases;
                    return (/*@__PURE__*/$parcel$interopDefault($f110eb6e8c8d50db$exports)).wrap(function _callee$(_ctx) {
                        while(1)switch(_ctx.prev = _ctx.next){
                            case 0:
                                aliases = this.aliases.clone();
                                outputBuffer.echo("\n<div class=\"card\">\n    <div class=\"card-header\">\n        ");
                                _ctx.t0 = outputBuffer;
                                _ctx.next = 5;
                                return this.traceableRenderBlock(14, this.source)('card_head', context.clone(), outputBuffer, blocks);
                            case 5:
                                _ctx.t1 = _ctx.sent;
                                _ctx.t0.echo.call(_ctx.t0, _ctx.t1);
                                outputBuffer.echo("    </div>\n    <div class=\"card-body\">\n        ");
                                _ctx.t2 = outputBuffer;
                                _ctx.next = 11;
                                return this.traceableRenderBlock(17, this.source)('card_body', context.clone(), outputBuffer, blocks);
                            case 11:
                                _ctx.t3 = _ctx.sent;
                                _ctx.t2.echo.call(_ctx.t2, _ctx.t3);
                                outputBuffer.echo("    </div>\n    ");
                                if (!(context.has("card_footer") ? context.get("card_footer") : null)) {
                                    _ctx.next = 22;
                                    break;
                                }
                                outputBuffer.echo("        <div class=\"card-footer\">\n            ");
                                _ctx.t4 = outputBuffer;
                                _ctx.next = 19;
                                return this.traceableRenderBlock(21, this.source)('card_foot', context.clone(), outputBuffer, blocks);
                            case 19:
                                _ctx.t5 = _ctx.sent;
                                _ctx.t4.echo.call(_ctx.t4, _ctx.t5);
                                outputBuffer.echo("        </div>\n    ");
                            case 22:
                                outputBuffer.echo("</div>");
                            case 23:
                            case "end":
                                return _ctx.stop();
                        }
                    }, _callee, this);
                }).bind(this))();
            }
        },
        {
            key: "isTraitable",
            get: function get() {
                return false;
            }
        }
    ]);
    return _class;
}(TwingTemplate1)
```

Hope this helps narrow it down

**Comment by sseidel16** [comment]
@poislagarde The issue stems from swc which is used internally. An issue is open with the swc project but I'd appreciate if you gave it a comment to get higher visibility with their limited resources. https://github.com/swc-project/swc/issues/2620

**Comment by sseidel16** [comment]
@devongovett this still seems to be broken in 2.1.1. Can this be reopened?
