### ISSUE TITLE
Nightly doesn't work with npm 8

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#7246]
# 🐛 bug report

With `"parcel": "2.0.0-nightly.903"`, npm 7 installs various packages (core, fs, ...) with `2.0.0` instead of the corresponding nightly.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "nightly",
  "version": "1.0.0",
  "license": "MIT",
  "devDependencies": {
    "parcel": "2.0.0-nightly.903"
  }
}

```

## 🤔 Expected Behavior

Should work

## 😯 Current Behavior

```js
$ npx parcel build index.html
...
DOMException [DataCloneError]: function fn(...args) {
    return new Promise((resolve, reject) => {
      ArrayPrototypePush(args, (err, ...va...<omitted>... } could not be cloned.
    at Worker.postMessage (node:internal/worker:341:5)
    at ThreadsWorker.send (node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:75:17)
    at Worker.send (node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:145:17)
    at Worker.call (node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:165:12)
    at node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:133:12
    at new Promise (<anonymous>)
    at Worker.sendSharedReference (node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:132:12)
    at node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:122:20
    at Array.map (<anonymous>)
```

## 💻 Code Sample

https://github.com/mischnic/parcel-issue-7246

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Node             | 16
| npm/Yarn         | npm 8.1.0

**Comment by artmsilva** [comment]
I can reproduce this as well using node 14 and npm 7 with parcel@2.0.0-nightly.951.

```bash
> parcel build 'ui/*/' --log-level verbose --no-cache

DOMException [DataCloneError]: function fn(...args) {
    return new Promise((resolve, reject) => {
      original.call(this, ...args, (err, ....<omitted>... } could not be cloned.
    at Worker.postMessage (internal/worker.js:340:23)
    at ThreadsWorker.send (<repo-directory>/node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:74:17)
    at Worker.send (<repo-directory>/node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:145:17)
    at Worker.call (<repo-directory>/node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:165:12)
    at <repo-directory>/node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:133:12
    at new Promise (<anonymous>)
    at Worker.sendSharedReference (<repo-directory>/node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:132:12)
    at <repo-directory>/node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:122:20
    at Array.map (<anonymous>)
    at Worker.fork (<repo-directory>/node_modules/parcel/node_modules/@parcel/core/node_modules/@parcel/workers/lib/Worker.js:121:81)
```
