### ISSUE TITLE
🐛 On Angular-Cli projects built with "ng new Demo_Project --style=scss" parcel can't compile scss

### ISSUE THREAD

**Issue by tatsujb** [parcel-bundler/parcel#757]
**Choose one:** is this a 🐛 

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "web.ui",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "parcel": "parcel",
    "start": "parcel ./src/index.html --no-cache",
    "build": "parcel build ./src/index.html -d /distribution --no-cache --no-minify",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.3",
    "@angular/common": "^5.2.3",
    "@angular/compiler": "^5.2.3",
    "@angular/core": "^5.2.3",
    "@angular/forms": "^5.2.3",
    "@angular/http": "^5.2.3",
    "@angular/platform-browser": "^5.2.3",
    "@angular/platform-browser-dynamic": "^5.2.3",
    "@angular/router": "^5.2.3",
    "core-js": "^2.5.3",
    "node-sass": "^4.7.2",
    "rxjs": "^5.5.6",
    "sass-loader": "^6.0.6",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.6.7",
    "@angular/compiler-cli": "^5.2.3",
    "@angular/language-service": "^5.2.3",
    "@types/jasmine": "^2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~9.4.0",
    "codelyzer": "^4.1.0",
    "jasmine-core": "~2.9.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.7.1",
    "parcel-bundler": "^1.5.1",
    "postcss-modules": "^1.1.0",
    "parcel-plugin-typescript": "^0.5.3",
    "parcel-plugin-angular": "0.5.1-next.13"
  }
}
```

### 🤔 Expected Behavior

scss is compiled on both` ng serve` and `parcel ./src/index.html`

### 😯 Current Behavior

`ng serve` creates project with compiled scss.` no errors, parcel ./src/index.html` ignores scss files entirely and outputs this error : 

```
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\polyfills.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\main.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\app\app.module.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\environments\environment.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\app\app.component.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\app\logged-in\logged-in.component.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\app\login\login.component.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\app\logged-in\top-bar\top-bar.component.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\app\logged-in\left-bar\left-bar.component.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\app\logged-in\content\content.component.ts'.
    at getValidSourceFile (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101021:23)
    at Object.getSemanticDiagnostics (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\typescript\lib\typescript.js:101200:36)
    at LanguageService.check (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\backend\service\index.js:16:24)
    at Object.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-angular\build\backend\worker\launcher.js:36:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at AngularWorker.<anonymous> (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\worker\index.js:27:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at IncomingMessage.res.setEncoding.on (C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\parcel-plugin-typescript\build\ipc\client.js:31:32)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

### 💁 Possible Solution

path into angular-cli's usage of scss compilation and use it for parcel or make sure parcel continues to use node-sass as it does with React.

### 💻 Code Sample

ts.config.json : 
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```
index.html  : 
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MyApp</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
  <script src="polyfills.ts"></script>
  <script src="main.ts"></script>
</body>
</html>
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.5.1
| Node             | 8.9.4
| npm/Yarn         | 5.6.0 
| Operating System | windows 10 pro 64bit

also my stack shows this bug : https://github.com/gdi2290/angular-starter/issues/1555  : if any scss files that are present are empty the rather than serving the app without loading any style (as I have right now) it fails to compile at all. with : 
`Unhandled promise rejection: Error: Error: Error: Could not find file: 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\src\polyfills.ts'.`

**Comment by fathyb** [comment]
@tatsujb Parcel isn't responsible for the Angular CSS support, the plugin is. It works with React projects because they mostly use the standard `import`/`require`. I'm closing this as it's a bug of the Angular plugin, please open an issue on the [plugin tracker](https://github.com/fathyb/parcel-plugin-angular/issues).
