### ISSUE TITLE
dynamic import not working in version 2.2.1 - when going back to 2.1.0 it works fine

### ISSUE THREAD

**Issue by Florian79** [parcel-bundler/parcel#7607]
# 🐛 bug report

Error: Failed to fetch dynamically imported module

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
Could you please provide a reproduction of your issue?

**Comment by Florian79** [comment]
this is my setup:


parcel-bug.js

```
const doTest = () => {
    import('xmldom').then(xmlDomGot => {
        const domParser = new (xmlDomGot.default || xmlDomGot).DOMParser(); //this is ugly but necesary to run the code plain and built
        const p = domParser.parseFromString('<xml><doc att="abc">hello</doc></xml>');
        console.log('XXX parsed document: ', p);
    }).catch(e =>
        console.error('Error while loading xmldom: ', e))
}
doTest();
```
package.json
```
{
  "name": "big",
  "version": "1.0.0",
  "description": "",
  "main": "dist/main.js",
  "module": "dist/module.js",
  "type": "module",
  "source": "./src/parcel-bug.js",
  "scripts": {
    "build": "parcel build  --no-optimize --log-level warn",
  },
   "dependencies": {
    "xmldom": "^0.6.0"
  },
  "engines": {
    "node": ">=16 <17",
    "npm": ">=8"
  },
  "devDependencies": {
    "parcel": "^2.3.1"
  }
}
```
main.js //the build result

```
import * as $koxiq$xmldom from "xmldom";


const $20947afa8df37555$var$doTest = ()=>{
    $koxiq$xmldom.then((xmlDomGot)=>{
        const domParser = new (xmlDomGot.default || xmlDomGot).DOMParser();
        const p = domParser.parseFromString('<xml><doc att="abc">hello</doc></xml>');
        console.log('XXX parsed document: ', p);
    }).catch((e)=>console.error('Error while loading xmldom: ', e)
    );
};
$20947afa8df37555$var$doTest();


//# sourceMappingURL=main.js.map
```

when running the code:

```
TypeError: $koxiq$xmldom.then is not a function
    at $20947afa8df37555$var$doTest (file:///Users/xx/dev/bit.flower/flower-core/dist/main.js:5:19)
    at file:///Users/xx/dev/bit.flower/flower-core/dist/main.js:12:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Process finished with exit code 1
```


i tried with latest version '2.3.1' and got same issue when building for browser target
