### ISSUE TITLE
ErrHandlingClass [Error]: Can't find /bundle.js.map on this server!

### ISSUE THREAD

**Issue by moezbenrebah** [parcel-bundler/parcel#7657]
I'm under nodejs 14 and npm 6, I used parcel-bundler 1.12.3. currently, I have the error that I tried to figure out how to fix but I didn't:

```bash
ErrHandlingClass [Error]: Can't find /bundle.js.map on this server!
    at /home/moez/Desktop/Go_ahead_travel/app.js:89:8
    at Layer.handle [as handle_request] (/home/moez/Desktop/Go_ahead_travel/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/moez/Desktop/Go_ahead_travel/node_modules/express/lib/router/route.js:137:13)
    at next (/home/moez/Desktop/Go_ahead_travel/node_modules/express/lib/router/route.js:131:14)
    at next (/home/moez/Desktop/Go_ahead_travel/node_modules/express/lib/router/route.js:131:14)
    at next (/home/moez/Desktop/Go_ahead_travel/node_modules/express/lib/router/route.js:131:14)
    at next (/home/moez/Desktop/Go_ahead_travel/node_modules/express/lib/router/route.js:131:14)
    at next (/home/moez/Desktop/Go_ahead_travel/node_modules/express/lib/router/route.js:131:14)
    at next (/home/moez/Desktop/Go_ahead_travel/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/home/moez/Desktop/Go_ahead_travel/node_modules/express/lib/router/route.js:112:3) {
  statusCode: 404,
  status: 'fail',
  isOperational: true
}
```

**Comment by DURGASAI-11** [comment]
AppError: Cant find /bundle.js.map on this server
    at D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\app.js:105:8
    at Layer.handle [as handle_request] (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:144:13)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at Route.dispatch (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\layer.js:95:5)
    at D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:284:15
    at param (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:365:14)
    at param (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:421:3)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:280:10) {
  statusCode: 404,
  status: 'fail',
  isOperational: true
}
Error 😒 AppError: Cant find /bundle.js.map on this server
    at D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\app.js:105:8
    at Layer.handle [as handle_request] (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:144:13)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at Route.dispatch (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\layer.js:95:5)
    at D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:284:15
    at param (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:365:14)
    at param (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:421:3)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:280:10) {
  statusCode: 404,
  status: 'fail',
  isOperational: true
}
Error 😒 AppError: Cant find /bundle.js.map on this server
    at D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\app.js:105:8
    at Layer.handle [as handle_request] (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:144:13)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:140:7)
    at Route.dispatch (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\layer.js:95:5)
    at D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:284:15
    at param (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:365:14)
    at param (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:421:3)
    at next (D:\CODE\CAREER CSE BY AJX\WEB-D\Node.js, Express, MongoDB & More - The Complete Bootcamp 2021\natours\node_modules\express\lib\router\index.js:280:10) {
  statusCode: 404,
  status: 'fail',
  isOperational: true
}
