### ISSUE TITLE
No native build was found for platform=linux arch=x64 runtime=electron

### ISSUE THREAD

**Issue by tianalemesle** [parcel-bundler/parcel#7666]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
await (new (require('@parcel/core').default)({
    entries: 'src/index.html',
    defaultConfig: '@parcel/config-default',
    env: { NODE_ENV: 'development' },
    serveOptions: { port: devServerPort },
    hmrOptions: { port: devServerPort }
})).watch();
```

## 🤔 Expected Behavior

Works just like `parcel serve src/index.html` does.

## 😯 Current Behavior

```
UnhandledPromiseRejectionWarning: Error: No native build was found for platform=linux arch=x64 runtime=electron abi=101 uv=1 libc=glibc node=16.13.0 electron=17.0.0
    loaded from: /node_modules/lmdb

    at Function.load.path (/node_modules/node-gyp-build/index.js:59:9)
    at load (/node_modules/node-gyp-build/index.js:21:30)
    at Object.<anonymous> (/node_modules/lmdb/dist/index.cjs:2250:47)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

## 💁 Possible Solution

The issue seem specific to [`@parcel/core`](https://www.npmjs.com/package/@parcel/core) which depends on [`@parcel/cache`](https://www.npmjs.com/package/@parcel/cache) which depends on [`lmdb`](https://www.npmjs.com/package/lmdb).

## 🔦 Context

Running Parcel's dev server programmatically on Electron.

## 💻 Code Sample

[`KaKi87/template-electron17-vue3-parcel2`](https://git.kaki87.net/KaKi87/template-electron17-vue3-parcel2)

## 🌍 Your Environment

| Software         | Version(s)      |
| ---------------- | --------------- |
| Parcel           | `^2.2.1`        |
| Node             | `14.19.0`       |
| ~~npm~~/Yarn     | `1.22.17`       |
| Operating System | Linux Mint 19.3 |

---

Thanks.

**Comment by mischnic** [comment]
If this is still a problem, please file an issue on https://github.com/DoctorEvidence/lmdb-js
