### ISSUE TITLE
Cannot build the simplest Vue project: Error: mod[method] is not a function

### ISSUE THREAD

**Issue by bokovhu** [parcel-bundler/parcel#7681]
# 🐛 bug report

I have tried creating a new project with the latest version of parcel, and Vue.JS. I cannot get even the most simplest app to compile, due to an error being thrown.

## 🎛 Configuration (.babelrc, package.json, cli command)

My `package.json` looks like the following (created a new one without sensitive information):

```json
{
    "name": "broken-parcel",
    "version": "0.0.1",
    "private": true,
    "source": "./src/index.html",
    "scripts": {
        "build": "parcel build",
        "serve": "parcel"
    },
    "devDependencies": {
        "@parcel/core": "^2.3.0",
        "parcel": "^2.3.0"
    },
    "dependencies": {
        "vue": "^3.2.30"
    }
}
```

## 🤔 Expected Behavior

When I run `yarn serve`, parcel should start in live-reload mode and compile the app. When I run `yarn build`, parcel should build my application.

## 😯 Current Behavior

I receive the following error when I try to run either `yarn serve` or `yarn build` on all of my configs:

```
tthe@TTHE-MSI:/mnt/c/work/broken-parcel$ yarn build
🚨 Build failed.

Error: mod[method] is not a function

  TypeError: mod[method] is not a function
  at WorkerFarm.processRequest
  (/mnt/c/work/broken-parcel/.yarn/__virtual__/@parcel-workers-virtual-37efa14426/0/cache/@parcel-workers-npm-2.3.0-0695013a3d-d28871b31f.zip/node_modules/@parcel/workers/lib/WorkerFarm.js:336:55)
  at Worker.<anonymous> (/mnt/c/work/broken-parcel/.yarn/__virtual__/@parcel-workers-virtual-37efa14426/0/cache/@parcel-workers-npm-2.3.0-0695013a3d-d28871b31f.zip/node_modules/@parcel/workers/lib/WorkerFarm.js:233:39)
  at Worker.emit (events.js:400:28)
  at Worker.receive (/mnt/c/work/broken-parcel/.yarn/__virtual__/@parcel-workers-virtual-37efa14426/0/cache/@parcel-workers-npm-2.3.0-0695013a3d-d28871b31f.zip/node_modules/@parcel/workers/lib/Worker.js:177:12)
  at ThreadsWorker.onMessage (/mnt/c/work/broken-parcel/.yarn/__virtual__/@parcel-workers-virtual-37efa14426/0/cache/@parcel-workers-npm-2.3.0-0695013a3d-d28871b31f.zip/node_modules/@parcel/workers/lib/Worker.js:98:64)
  at ThreadsWorker.handleMessage
  (/mnt/c/work/broken-parcel/.yarn/__virtual__/@parcel-workers-virtual-37efa14426/0/cache/@parcel-workers-npm-2.3.0-0695013a3d-d28871b31f.zip/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:70:10)
  at Worker.<anonymous>
  (/mnt/c/work/broken-parcel/.yarn/__virtual__/@parcel-workers-virtual-37efa14426/0/cache/@parcel-workers-npm-2.3.0-0695013a3d-d28871b31f.zip/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:55:44)
  at Worker.emit (events.js:400:28)
  at MessagePort.<anonymous> (internal/worker.js:236:53)
  at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
```

## 🔦 Context

I am trying to create a frontend application using parcel as my bundler, and Vue.JS 3 as my frontend framework. I have been stuck at step -1 during project setup.

## 💻 Code Sample

My repository looks like the following:

```
package.json
src/
    index.html
    index.js
    components/
        App.vue
```

My `src/index.html`:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Test</title>
        <meta charset="utf-8">
    </head>
    <body>
        <main role="main" id="app"></main>
        <script src="./index.js" type="module"></script>
    </body>
</html>
```

My `src/index.js`:

```js
import { createApp } from "vue"
import App from "./components/App.vue"
createApp(App).mount("#app")
```

My `src/components/App.vue`:

```
<template>
    <div>
        App works.
    </div>
</template>

<script>
export default {

}
</script>

<style>

</style>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.0 |
| Node             | 16.14.0 _and_ 14.18.3 |
| npm/Yarn         | Yarn PnP 3.1.1 |
| Operating System | Windows 11 (Node.JS 16.14.0), Ubuntu in WSL2 (Node.JS 14.18.3) |

**Comment by Midlight25** [comment]
Uhh, can confirm it's not just with Vue. I tried starting a project today with Parcel. I've got nothing in it except like the basic Emmet HTML boilerplate in my src folder and it gives me the same problem. However, I am using NPM.

I've also tried backcycling through the previous versions of Parcel to see if it's just this new v2.3.0 but I've had no luck. Not even going all the way back to v2.0.1.

My `src/index.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1>Hello World</h1>
</body>
</html>
```

and the result:
```bash
midlight25@Michael-Desktop:~/dev/community-oasis-dashboard (dev) $ npx parcel serve src/index.html
Server running at http://localhost:1234
🚨 Build failed.

Error: mod[method] is not a function

  TypeError: mod[method] is not a function
  at WorkerFarm.processRequest
  (/home/midlight25/dev/community-oasis-dashboard/node_modules/@parcel/workers/lib/WorkerFarm.js:336:55)
  at Worker.<anonymous>
  (/home/midlight25/dev/community-oasis-dashboard/node_modules/@parcel/workers/lib/WorkerFarm.js:233:39)
  at Worker.emit (node:events:520:28)
  at Worker.receive (/home/midlight25/dev/community-oasis-dashboard/node_modules/@parcel/workers/lib/Worker.js:177:12)
  at ThreadsWorker.onMessage
  (/home/midlight25/dev/community-oasis-dashboard/node_modules/@parcel/workers/lib/Worker.js:98:64)
  at ThreadsWorker.handleMessage
  (/home/midlight25/dev/community-oasis-dashboard/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:70:10)
  at Worker.<anonymous>
  (/home/midlight25/dev/community-oasis-dashboard/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:55:44)
  at Worker.emit (node:events:520:28)
  at MessagePort.<anonymous> (node:internal/worker:232:53)
  at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
```

## Environment

| Software         | Version                               |
|------------------|---------------------------------------|
| Parcel           | v2.3.0 - v2.0.1                       |
| Node             | v17.4.0                               |
| npm/Yarn         | NPM v8.4.1                            |
| Operating System | Windows 10 \| WSL Ubuntu 20.04.03 LTS |

**Comment by jordaaash** [comment]
I was able to get it to build again by using [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides). Seems like 2.3.0 broke something.

```json
    "overrides": {
        "parcel": "2.2.1",
        "@parcel/bundler-default": "2.2.1",
        "@parcel/cache": "2.2.1",
        "@parcel/codeframe": "2.2.1",
        "@parcel/compressor-raw": "2.2.1",
        "@parcel/config-default": "2.2.1",
        "@parcel/core": "2.2.1",
        "@parcel/diagnostic": "2.2.1",
        "@parcel/events": "2.2.1",
        "@parcel/fs-search": "2.2.1",
        "@parcel/fs": "2.2.1",
        "@parcel/graph": "2.2.1",
        "@parcel/hash": "2.2.1",
        "@parcel/logger": "2.2.1",
        "@parcel/markdown-ansi": "2.2.1",
        "@parcel/namer-default": "2.2.1",
        "@parcel/node-resolver-core": "2.2.1",
        "@parcel/optimizer-cssnano": "2.2.1",
        "@parcel/optimizer-htmlnano": "2.2.1",
        "@parcel/optimizer-image": "2.2.1",
        "@parcel/optimizer-svgo": "2.2.1",
        "@parcel/optimizer-terser": "2.2.1",
        "@parcel/package-manager": "2.2.1",
        "@parcel/packager-css": "2.2.1",
        "@parcel/packager-html": "2.2.1",
        "@parcel/packager-js": "2.2.1",
        "@parcel/packager-raw": "2.2.1",
        "@parcel/packager-svg": "2.2.1",
        "@parcel/plugin": "2.2.1",
        "@parcel/reporter-cli": "2.2.1",
        "@parcel/reporter-dev-server": "2.2.1",
        "@parcel/resolver-default": "2.2.1",
        "@parcel/runtime-browser-hmr": "2.2.1",
        "@parcel/runtime-js": "2.2.1",
        "@parcel/runtime-react-refresh": "2.2.1",
        "@parcel/runtime-service-worker": "2.2.1",
        "@parcel/source-map": "2.0.2",
        "@parcel/transformer-babel": "2.2.1",
        "@parcel/transformer-css": "2.2.1",
        "@parcel/transformer-html": "2.2.1",
        "@parcel/transformer-image": "2.2.1",
        "@parcel/transformer-js": "2.2.1",
        "@parcel/transformer-json": "2.2.1",
        "@parcel/transformer-postcss": "2.2.1",
        "@parcel/transformer-posthtml": "2.2.1",
        "@parcel/transformer-raw": "2.2.1",
        "@parcel/transformer-react-refresh-wrap": "2.2.1",
        "@parcel/transformer-svg": "2.2.1",
        "@parcel/types": "2.2.1",
        "@parcel/utils": "2.2.1",
        "@parcel/watcher": "2.0.5",
        "@parcel/workers": "2.2.1"
    }
```

**Comment by jordaaash** [comment]
If you're using yarn, [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) work:

```json

    "resolutions": {
        "parcel": "2.2.1",
        "@parcel/bundler-default": "2.2.1",
        "@parcel/cache": "2.2.1",
        "@parcel/codeframe": "2.2.1",
        "@parcel/compressor-raw": "2.2.1",
        "@parcel/config-default": "2.2.1",
        "@parcel/core": "2.2.1",
        "@parcel/diagnostic": "2.2.1",
        "@parcel/events": "2.2.1",
        "@parcel/fs-search": "2.2.1",
        "@parcel/fs": "2.2.1",
        "@parcel/graph": "2.2.1",
        "@parcel/hash": "2.2.1",
        "@parcel/logger": "2.2.1",
        "@parcel/markdown-ansi": "2.2.1",
        "@parcel/namer-default": "2.2.1",
        "@parcel/node-resolver-core": "2.2.1",
        "@parcel/optimizer-cssnano": "2.2.1",
        "@parcel/optimizer-htmlnano": "2.2.1",
        "@parcel/optimizer-image": "2.2.1",
        "@parcel/optimizer-svgo": "2.2.1",
        "@parcel/optimizer-terser": "2.2.1",
        "@parcel/package-manager": "2.2.1",
        "@parcel/packager-css": "2.2.1",
        "@parcel/packager-html": "2.2.1",
        "@parcel/packager-js": "2.2.1",
        "@parcel/packager-raw": "2.2.1",
        "@parcel/packager-svg": "2.2.1",
        "@parcel/plugin": "2.2.1",
        "@parcel/reporter-cli": "2.2.1",
        "@parcel/reporter-dev-server": "2.2.1",
        "@parcel/resolver-default": "2.2.1",
        "@parcel/runtime-browser-hmr": "2.2.1",
        "@parcel/runtime-js": "2.2.1",
        "@parcel/runtime-react-refresh": "2.2.1",
        "@parcel/runtime-service-worker": "2.2.1",
        "@parcel/source-map": "2.0.2",
        "@parcel/transformer-babel": "2.2.1",
        "@parcel/transformer-css": "2.2.1",
        "@parcel/transformer-html": "2.2.1",
        "@parcel/transformer-image": "2.2.1",
        "@parcel/transformer-js": "2.2.1",
        "@parcel/transformer-json": "2.2.1",
        "@parcel/transformer-postcss": "2.2.1",
        "@parcel/transformer-posthtml": "2.2.1",
        "@parcel/transformer-raw": "2.2.1",
        "@parcel/transformer-react-refresh-wrap": "2.2.1",
        "@parcel/transformer-svg": "2.2.1",
        "@parcel/types": "2.2.1",
        "@parcel/utils": "2.2.1",
        "@parcel/watcher": "2.0.5",
        "@parcel/workers": "2.2.1"
    }
````

**Comment by bokovhu** [comment]
It seems that there are multiple things in place which cause the break:

* I would take a wild guess, and say that something around `2.3.0` is broken, and causes the `Error: mod[method] is not a function` error.
* Going back to previous versions of `parcel` _will not work_, becase the package seems to use `^VERSION` locators for its dependencies. If I revert to `parcel@2.2.1`, I can see the following dependencies in my `yarn.lock` file:

```
"parcel@npm:2.2.1":
  version: 2.2.1
  resolution: "parcel@npm:2.2.1"
  dependencies:
    "@parcel/config-default": ^2.2.1
    "@parcel/core": ^2.2.1
    "@parcel/diagnostic": ^2.2.1
    "@parcel/events": ^2.2.1
    "@parcel/fs": ^2.2.1
    "@parcel/logger": ^2.2.1
    "@parcel/package-manager": ^2.2.1
    "@parcel/reporter-cli": ^2.2.1
    "@parcel/reporter-dev-server": ^2.2.1
    "@parcel/utils": ^2.2.1
    chalk: ^4.1.0
    commander: ^7.0.0
    get-port: ^4.2.0
    v8-compile-cache: ^2.0.0
  bin:
    parcel: lib/bin.js
  checksum: 081fdc011a631b88477236f1df4232c16b45e71c1c7a7e861a7b319b042698944e0fb6f9e5615b79f8d4ba5b343bb2736b4393c3798d736951cbfe1ecb1bc8dd
  languageName: node
  linkType: hard
```

But those `^2.2.1` locators are resolved to the **latest released version** for some reason, and thus I get `2.3.0` of them, for example:

```
"@parcel/config-default@npm:^2.2.1":
  version: 2.3.0
```

Using the `"resolutions": {...}` workaround above _does seem to work_, but you have to include the _entire dependency tree_, otherwise all `^2.2.1` locators will be resolved to `2.3.0`. I have tried the above workaround, but it will fail with the following error:

```
@parcel/core: The plugin "@parcel/transformer-vue" is not compatible with the current version of Parcel. Requires "^2.3.0" but the current version is "2.2.1".
```

If I add `"@parcel/transformer-vue": "2.2.1"` to my `"resolutions": {...}` field, the app finally compiles:

```
√ Built in 2.80s

dist\index.html              215 B    417ms
dist\index.fdf92d38.js    54.73 KB    1.21s
```

I would say that this does not affect projects which don't update their dependencies in the near future. I would also like to make a suggestion: to make sure, that this will not happen again, I would recommend dropping the `^VERSION` locator, and replacing it with explicit version numbers in parcel's packages. That way, it is guaranteed that the package manager will only resolve compatible versions of those packages.

**Comment by sznowicki** [comment]
What's worse it's not that easy to downgrade since from parcel@2.0.0 all deps were not pinpointed

```
parcel@2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/parcel/-/parcel-2.0.0.tgz#c5e203bf12b29f5489f426d7fb4826e6b463ebcd"
  integrity sha512-vALKLDWz9DF3YD4oGcG1UpMR32TXHr3wj0OZTCo0nLuP8LqNNhG7Twf+ZIpVf2r1b5Glex5eUl0vcx/x2xY6pw==
  dependencies:
    "@parcel/config-default" "^2.0.0"
    "@parcel/core" "^2.0.0"
    "@parcel/diagnostic" "^2.0.0"
    "@parcel/events" "^2.0.0"
    "@parcel/fs" "^2.0.0"
    "@parcel/logger" "^2.0.0"
    "@parcel/package-manager" "^2.0.0"
    "@parcel/reporter-cli" "^2.0.0"
    "@parcel/reporter-dev-server" "^2.0.0"
    "@parcel/utils" "^2.0.0"
    ```

**Comment by sznowicki** [comment]
Thanks @jordansexton! It would take me quite a while to discover `resolutions` in the docs.

**Comment by LeoniePhiline** [comment]
@devongovett Diagnosing cases like this would be less confusing if `parcel` would pin all `@parcel/*` dependencies to its own version.

Do you use versioning automation, or can I help with a pull request to pin all dependencies? (Follow-up: As 2.3.1 or as 2.3.2?)

**Comment by reesericci** [comment]
Just started up a basic tailwindcss + alpine + typescript project and got this error. Rolling back now :(

**Comment by devongovett** [comment]
Working on it

**Comment by devongovett** [comment]
@LeoniePhiline I changed to using pinned versions for all parcel deps in 699f0b24c38eabcdad0960c62c03bd2f2902b19e.

Also the actual issue is fixed in https://github.com/parcel-bundler/parcel/commit/e07b5cac81438a8b1d06ade348fa8e73290769bf. CI is running to release 2.3.1 now.

**Comment by jordaaash** [comment]
Thanks for the quick work on this @devongovett!

**Comment by ThomasBowen** [comment]
> @LeoniePhiline I changed to using pinned versions for all parcel deps in [699f0b2](https://github.com/parcel-bundler/parcel/commit/699f0b24c38eabcdad0960c62c03bd2f2902b19e).
> 
> Also the actual issue is fixed in [e07b5ca](https://github.com/parcel-bundler/parcel/commit/e07b5cac81438a8b1d06ade348fa8e73290769bf). CI is running to release 2.3.1 now.

Looks like both of these are dying in the pipeline.

**Comment by devongovett** [comment]
Ah, of course, I failed the linter. But that's just the test pipeline. The release went out successfully https://github.com/parcel-bundler/parcel/runs/5144037264?check_suite_focus=true

**Comment by LeoniePhiline** [comment]
@devongovett  Thank you! 🙏
