### ISSUE TITLE
HMR is not Reloading from ERR_UNHANDLED_REJECTION Exception while using react

### ISSUE THREAD

**Issue by laskdjlaskdj12** [parcel-bundler/parcel#7761]
# 🐛 bug report

I'm using electron and react

if there's a mistake token typo, ERR_UNHANDLED_REJECTION pops up and react reload stops.

I want HMR to be maintained even if there is a token typo.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "name": "boilerplate",
  "version": "1.0.0",
  "description": "📦🚀 React Electron Parcel Boilerplate",
  "main": "src/electron/index.js",
  "scripts": {
    "start": "node scripts/start.js",
    "electron": "electron .",
    "build": "node scripts/build.js"
  },
  "keywords": [
    "react",
    "electron",
    "parcel"
  ],
  "author": "Ferenc Almasi",
  "license": "ISC",
  "dependencies": {
    "@chakra-ui/react": "^1.8.3",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "@react-icons/all-files": "^4.1.0",
    "add": "^2.0.6",
    "framer-motion": "^6",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-indiana-drag-scroll": "^2.1.0",
    "react-photo-gallery": "^8.0.0",
    "react-scripts": "^5.0.0",
    "react-scroll-horizontal": "^1.6.6",
    "recoil": "^0.6.1",
    "smooth-scrollbar": "^8.7.4",
    "yarn": "^1.22.17"
  },
  "devDependencies": {
    "electron": "17.0.0",
    "electron-packager": "15.2.0",
    "electron-reloader": "1.1.0",
    "electron-winstaller": "4.0.1",
    "parcel-bundler": "1.12.4",
    "sass": "1.36.0"
  }
}
```

## 🤔 Expected Behavior

Still HMR ongoing, even if have token exception.

like react-scripts 

## 😯 Current Behavior

react reload is stopped while using </video <-- mistake tag

```
> boilerplate@1.0.0 electron
> electron .
🚨  /Users/ace/Desktop/lask launhcer electron/lask_launcher_electron/src/frontend/view/LoginView.js:40:20: Unexpected token, expected "jsxTagEnd" (40:20)
  38 |                         <source src={MinecraftTrailer} type={'video/mp4'}/>
  39 |                     </video
> 40 |                     {/*<Img position={'absolute'} src={MinecraftLoginView} objectFit={'none'}/>*/}
     |                    ^
  41 |                     <Box position={'relative'} left={'700px'} width={'500px'} height={'100vh'} bg={'rgba(0,0,0,0.5)'}
  42 |                          backdropFilter={'blur(20px)'}>
  43 |                         <Flex flexDirection={'column'} height={'100vh'} justifyContent={'center'} alignItems={'center'}>
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
```

## 🔦 Context

I'm using electron and react

if there's a mistake token typo, ERR_UNHANDLED_REJECTION pops up and react reload stops.

I want HMR to be maintained even if there is a token typo.
## 💻 Code Sample

electron_root.js
```js
const { app, BrowserWindow } = require('electron');

try {
    require('electron-reloader')(module);
} catch (_) {}

let mainWindow;
let loginWindow;

const createWindow = () => {
    mainWindow = new BrowserWindow({
        title: "Lask Launcher",
        resizable: true,
        autoHideMenuBar: true,
        width: 1738,
        height: 1080,
        titleBarStyle: 'hiddenInset',
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            allowRunningInsecureContent: true,
            webSecurity: false
        }
    });

    mainWindow.loadFile('build/index.html');
};

const createLoginWindow = () => {
    loginWindow = new BrowserWindow({
        title: "Login Window",
        resizable: true,
        autoHideMenuBar: true,
        width: 1370,
        height: 772,
        titleBarStyle: 'hiddenInset',
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            allowRunningInsecureContent: true,
            webSecurity: false,
        }
    });

    loginWindow.loadFile('build/index.html')
}

app.commandLine.appendSwitch("autoplay-policy", "no-user-gesture-required")
app.whenReady().then(createLoginWindow);
app.on('window-all-closed', () => app.quit());
app.on('activate', () => {

    if(loginWindow === null){
        createLoginWindow()
    }

    // if (mainWindow === null) {
    //     createWindow();
    // }
});
```

parcel bunderl js
```js
const Bundler = require('parcel-bundler');

const entry = './public/index.html';
const options = {
    outDir: './build',
    publicUrl: './',
    sourceMaps: false,
    autoInstall: false,
    hmr: false,
    target: 'electron'
};

let electronStarted = false;

(async () => {
    const bundler = new Bundler(entry, options);

    bundler.on('bundled', bundle => {
        if (!electronStarted) {
            electronStarted = true;

            require('child_process').spawn('npm', ['run', 'electron'], {
                stdio: ['ignore', 'inherit', 'inherit'],
                shell: true
            });
        }
    });

    bundler.bundle();
})();
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             | v16.13.1
| npm/Yarn         | yarn
| Operating System | mac os

**Comment by magicznyleszek** [comment]
The same thing happens for me with a much simpler setup - I only run parcel over single `scss` file and single `ts` file. 

My code looks like this:

`package.json`
```json
{
  "name": "kobotoolbox.org",
  "private": true,
  "version": "2.0.0",
  "repository": "https://github.com/kobotoolbox/kobotoolbox.org.git",
  "bugs": "https://github.com/kobotoolbox/kobotoolbox.org/issues",
  "scripts": {
    "copy-files": "node ./_scripts/copy-files.js",
    "postinstall": "npm run copy-files",
    "jekyll-build": "bundle exec jekyll build",
    "jekyll-serve": "bundle exec jekyll serve --watch --baseurl ''",
    "assets-watch": "parcel watch",
    "assets-build": "parcel build"
  },
  "dependencies": {
    "kobo-common": "https://github.com/kobotoolbox/kobo-common.git#semver:1.15.0",
    "tiny-slider": "^2.9.4"
  },
  "targets": {
    "default": {
      "source": ["_assets/styles/kobo.scss", "_assets/scripts/kobo.ts"],
      "distDir": "assets",
      "sourceMap": false
    }
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.3.2",
    "@typescript-eslint/parser": "^5.15.0",
    "autoprefixer": "^10.4.2",
    "browserslist": "^4.20.0",
    "parcel": "^2.3.2",
    "postcss": "^8.4.8",
    "typescript": "^4.6.2"
  }
}
```

My `kobo.scss` file is a list of imports:

```scss
// 0. We don't import variables into global context.

@import '../../node_modules/tiny-slider/dist/tiny-slider.css';

// 1. setup styles
@import 'setup/normalize';
@import 'setup/fonts';
@import 'setup/base';
@import 'setup/root-layout';

// 2. components
@import 'components/banner-text';
@import 'components/button';
@import 'components/feature-card';
@import 'components/feature-row';
@import 'components/footer-nav';
@import 'components/header-nav';
@import 'components/image';
@import 'components/link-card';
@import 'components/picture-banner';
@import 'components/post-card';
@import 'components/post-meta';
@import 'components/post-summary';
@import 'components/quick-links';
@import 'components/small-banner';
@import 'components/thumbnail';
@import 'components/video';
@import 'components/word-typer';

// 3. sections
@import 'sections/blog-banner';
@import 'sections/faqs';
@import 'sections/featured-posts';
@import 'sections/features-banner';
@import 'sections/features-list';
@import 'sections/get-started';
@import 'sections/home-banner';
@import 'sections/partners';
@import 'sections/post';
```

A sample file looks like this:
```scss
@use 'colors';
@use '_assets/styles/setup/sizes';
@use '_assets/styles/setup/utils';

.post-meta {
  @include utils.center-row-flex;

  color: colors.$kobo-gray-40;
}

.post-meta__author {
  font-size: sizes.$r19;
  font-weight: 700;
}

.post-meta__divider {
  display: block;
  width: sizes.$r2;
  height: sizes.$r13;
  background-color: colors.$kobo-blue;
  vertical-align: sizes.$r1;
  margin: 0 sizes.$r19;
}
```

`.postcssrc.json`
```json
{
  "plugins": {
    "autoprefixer": {}
  }
}
```

`.sassrc.json`
```json
{
  "outputStyle": "expanded",
  "includePaths": ["node_modules/kobo-common/src/styles"]
}
```

I'm running `npm run assets-watch` and whenever I use an unknown variable (e.g. any undefined local variable or when I forget importing with `@use`), I get the error that stops the watch (i.e. parcel doesn't rebuild regardless of the changes I do in the code):

```
npm run assets-watch

> kobotoolbox.org@2.0.0 assets-watch
> parcel watch

🚨 Build failed.

@parcel/transformer-sass: There is no module with the namespace "sizes".
╷
58 │   margin: sizes.$r70 auto;
│           ^^^^^^^^^^
╵
_assets/styles/components/picture-banner.scss 58:11  @import
_assets/styles/kobo.scss 20:9                        root stylesheet

  Error: There is no module with the namespace "sizes".
  ╷
  58 │   margin: sizes.$r70 auto;
  │           ^^^^^^^^^^
  ╵
  _assets/styles/components/picture-banner.scss 58:11  @import
  _assets/styles/kobo.scss 20:9                        root stylesheet
  at Object.wrapException (/Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:1241:17)
  at AsyncEnvironment0._async_environment0$_getModule$1 (/Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:67499:15)
  at AsyncEnvironment0.getVariable$2$namespace (/Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:67097:22)
  at _EvaluateVisitor_visitVariableExpression_closure2.call$0 (/Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:74388:55)
  at _EvaluateVisitor2._async_evaluate0$_addExceptionSpan$1$2 (/Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:71885:23)
  at _EvaluateVisitor2._async_evaluate0$_addExceptionSpan$2 (/Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:71906:19)
  at /Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:69924:36
  at _wrapJsFunctionForAsync_closure.$protected (/Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:3724:15)
  at _wrapJsFunctionForAsync_closure.call$2 (/Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:27826:12)
  at Object._asyncStartSync (/Users/leszek/Sites/kobo/kobotoolbox.org/node_modules/sass/sass.dart.js:3688:20)
```

Note: Initially I ran parcel without configuring `targets` and the same problem was present.

## 🌍 Your Environment
| Software | Version(s) |
| --- | --- |
| Parcel | 2.3.2 |
| Node | 17.2.0 |
| npm/Yarn | npm |
| Operating System | mac os |

**Comment by magicznyleszek** [comment]
One more thing I've noticed. When I `@import` some `.scss` file and make a typo in the name I get similar "Build failed" error. But as soon as I fix the typo, parcel manages to reload the website and rebuild itself .

**Comment by ilyamerman** [comment]
Same thing happens to us on 2.3.2, when making a syntax error on `.sass` / `.scss` we get a "Build failed" error from `transformer-sass` and the watch doesn't work anymore on the affected file even after fixing the mistake.

The watch continues to work as intended (without a restart) only after touching any other file in the project, but that process isn't intuitive

**Comment by magicznyleszek** [comment]
For me touching other `scss` files doesn't restart the watch, but if I touch `ts` file, it does restart.
