### ISSUE TITLE
Bug: bundler is resolving babel options from node_modules package.json 

### ISSUE THREAD

**Issue by nehaleem** [parcel-bundler/parcel#778]
Hi,

i tried to install module `cancelable-promise` and this package has inside its own `package.json` babel definition:

```
"babel": {
    "presets": [
      "es2015"
    ]
},
```

But, this module main is linked to `dist/CancelablePromise.js`, which is already transpiled.

Problem is that parcel bundler wants `es2015` because its found it inside this package.json.

`import CancelablePromise from 'cancelable-promise';`

```
F:\project\node_modules\cancelable-promise\dist\CancelablePromise.js: Couldn't find preset "es2015" relative to directory "F:\\project
    at F:\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (F:\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (F:\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (F:\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (F:\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (F:\project\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (F:\project\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at JSAsset.getParserOptions (F:\project\node_modules\parcel-bundler\src\assets\JSAsset.js:71:20)
    at JSAsset.parse (F:\project\node_modules\parcel-bundler\src\assets\JSAsset.js:79:32)
```

and i dont need to have `es2015`.

When ill delete these line inside theirs `package.json`, its working.

**Comment by lbguilherme** [comment]
This was probably fixed by https://github.com/parcel-bundler/parcel/pull/559. Could you try with the version from master?
