### ISSUE TITLE
Unsolvable packages version mismatch

### ISSUE THREAD

**Issue by dudematthew** [parcel-bundler/parcel#7789]
# 🐛 bug report

Hey guys!
I'm trying to use Vue 3 in my parcel project but there seems to be some version mismatch. I just can't find the answer to how to solve this particular issue, so I'll just go ahead and post this.

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc is empty.

I'm using just `parcel source/index.html`

My package.json: (after some `traumatic transitions`)
```js
{
  "name": "warhammer-isekai-easer",
  "version": "1.0.0",
  "description": "Potentialy powerful application created for RPG DM",
  "main": "index.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "start": "npm run dev",
    "dev": "parcel source/index.html",
    "build": "parcel build source/index.html"
  },
  "keywords": [
    "warhammer",
    "rpg"
  ],
  "author": "dudematthew",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@vizuaalog/bulmajs": "^0.12.1",
    "bulma": "^0.9.3",
    "parcel-bundler": "^1.12.4",
    "sass": "^1.26.8",
    "vue-template-compiler": "2.6.14"
  },
  "dependencies": {
    "@babel/runtime": "^7.17.2",
    "@fortawesome/fontawesome-free": "^6.0.0",
    "@parcel/diagnostic": "^2.3.2",
    "@vue/compiler-sfc": "^3.2.31",
    "bulma-checkradio": "^2.1.3",
    "bulma-divider": "^0.2.0",
    "bulma-iconpicker": "^2.1.0",
    "bulma-pageloader": "^0.3.0",
    "bulma-prefers-dark": "^0.1.0-beta.1",
    "jquery": "^3.6.0",
    "jquery-ui-dist": "^1.13.1",
    "selectize": "^0.12.6",
    "vue": "3.2.31"
  }
}

```

## 🤔 Expected Behavior

The project should build normally

## 😯 Current Behavior

There is an error and Vue doesn't seem to be working

```log
> parcel source/index.html        

Server running at http://localhost:1234 
×  G:\Dokumenty\Projekty\warhammer-easer\source\components\app.vue: 

Vue packages version mismatch:

- vue@3.2.31 (G:\Dokumenty\Projekty\warhammer-easer\node_modules\vue\index.js)
- vue-template-compiler@2.6.14 (G:\Dokumenty\Projekty\warhammer-easer\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


Vue packages version mismatch:

- vue@3.2.31 (G:\Dokumenty\Projekty\warhammer-easer\node_modules\vue\index.js)
- vue-template-compiler@2.6.14 (G:\Dokumenty\Projekty\warhammer-easer\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (G:\Dokumenty\Projekty\warhammer-easer\node_modules\vue-template-compiler\index.js:10:9)
    at Module._compile (G:\Dokumenty\Projekty\warhammer-easer\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (G:\Dokumenty\Projekty\warhammer-easer\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at localRequire (G:\Dokumenty\Projekty\warhammer-easer\node_modules\parcel-bundler\src\utils\localRequire.js:11:10)
    at async VueAsset.parse (G:\Dokumenty\Projekty\warhammer-easer\node_modules\parcel-bundler\src\assets\VueAsset.js:15:32)
    at async VueAsset.parseIfNeeded (G:\Dokumenty\Projekty\warhammer-easer\node_modules\parcel-bundler\src\Asset.js:65:18)
```

## 💁 Possible Solution

Maybe `@parcel/transformer-vue` or any other lib used is outdated?

## 🔦 Context

Just trying to make a vue app in parcel.

## 💻 Code Sample

This is the exact project, that the issue is happening on: https://github.com/dudematthew/warhammer-easer

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.4
| Node             | 16.6.2
| npm/Yarn         | 8.5.2
| Operating System | Windows 10

**Comment by dudematthew** [comment]
I've resolved the problem by installing Parcel 2 by using `npm uninstall parcel & npm install parcel@next` then manually resolving sass problem with `npm install sass & npm update` and it's all working now

In case you want to investigate problem on your own, here's the commit the bug was on: https://github.com/dudematthew/warhammer-easer/commit/b7da7386db2d1f687fd98ee135fd0af79a1f898d
