### ISSUE TITLE
Binary deps cause ERR_DLOPEN_DISABLED

### ISSUE THREAD

**Issue by FossPrime** [parcel-bundler/parcel#7799]
# 🐛 bug report

```
$ parcel index.html courses/**/* --open
_0x5037b1 [Error]: Cannot load native addon because loading addons is disabled.
    at process.dlopen (https://node-rma527.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:193771)
    at Object.Module._extensions..node (https://node-rma527.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:196774)
    at Module.load (https://node-rma527.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:194488)
    at Function.Module._load (https://node-rma527.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:192091)
    at Module.require (https://node-rma527.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:194806)
    at i (https://node-rma527.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:349630)
    at _0x2ab051 (https://node-rma527.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:101485)
    at Object.eval (/home/projects/node-rma527/node_modules/@parcel/source-map/parcel_sourcemap_node/index.js:15:18)
    at Object.function (https://node-rma527.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:101848)
    at Module._compile (https://node-rma527.w.staticblitz.com/blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6:196043) {
  code: 'ERR_DLOPEN_DISABLED'
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel build index.html`

## 🤔 Expected Behavior

Install and build with no hard binary dependencies

## 😯 Current Behavior

ERR_DLOPEN_DISABLED

## 💁 Possible Solution

Remove binary dependencies and use Browser compatible APIs

## 🔦 Context

I'm running Stackblitz on an HP 14c. The error happens on cloud projects and on on-disk projects.

## 💻 Code Sample

[Vanilla TS Sandbox](https://stackblitz.com/edit/feathersjs-kjxg6j?devtoolsheight=33&file=src/index.ts)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3
| Node             | 16.14
| npm/Yarn         |  7.17
| Operating System | ChromeOS / Stackblitz WebContainers

## Related

- https://github.com/parcel-bundler/parcel/issues/7748

**Comment by FossPrime** [comment]
Duplicate #7748
