### ISSUE TITLE
@parcel/transformer-postcss: Unexpected token p in JSON at position 6

### ISSUE THREAD

**Issue by maxleistner** [parcel-bundler/parcel#7902]
I got the following setup: 

```
{
  "license": "MIT",
  "scripts": {
    "dev": "parcel src/*.html",
    "build": "parcel build src/*.html"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.0",
    "cssnano": "^5.0.16",
    "parcel": "^2.2.1",
    "postcss": "^8.4.6",
    "tailwindcss": "^3.0.13"
  },
  "dependencies": {
    "@tailwindcss/forms": "^0.4.0",
    "alpinejs": "^3.8.1"
  },
  "packageManager": "yarn@3.2.0"
}

```

and get the following error trying to run `yarn run build`

```
Build failed.

@parcel/transformer-postcss: Unexpected token p in JSON at position 6

  SyntaxError: Unexpected token p in JSON at position 6
  at unexpectedToken (***node_modules/json-source-map/index.js:224:11)
  at wasUnexpectedToken (***node_modules/json-source-map/index.js:229:5)
  at parseObject (***node_modules/json-source-map/index.js:144:29)
  at _parse (***node_modules/json-source-map/index.js:39:24)
  at Object.exports.parse (***node_modules/json-source-map/index.js:24:11)
  at generateJSONCodeHighlights (***node_modules/@parcel/diagnostic/lib/diagnostic.js:153:64)
  at configHydrator (***node_modules/@parcel/transformer-postcss/lib/loadConfig.js:122:70)
  at async loadPluginConfig (***node_modules/@parcel/core/lib/requests/ConfigRequest.js:65:21)
  at async Transformation.loadTransformerConfig (***node_modules/@parcel/core/lib/Transformation.js:543:5)
  at async Transformation.loadPipeline (***node_modules/@parcel/core/lib/Transformation.js:482:20)


```

Any ideas? Node Version is 16.13.0

**Comment by devongovett** [comment]
Could you provide a bit more so that we can reproduce this? Some code or a small example would be helpful

**Comment by Cayan** [comment]
I had a similar issue. After downgrading back to 2.3.2, my build is working again.

**Comment by mischnic** [comment]
Can you share your postcss config file?

**Comment by Cayan** [comment]
@mischnic here:
```
{
	plugins: {
		'postcss-import': { },
		"postcss-simple-vars": { },
		"postcss-nested": { },
		"autoprefixer": {},
	},
}
```

**Comment by mischnic** [comment]
What's the name of that file? That is not a valid JSON file, and for a JS file the export is missing?

**Comment by Cayan** [comment]
That's true, it was already there. Its called: `.postcssrc`

**Comment by maxleistner** [comment]
I got the same file but different content: 
```
{
    plugins: {
        tailwindcss: {},
        autoprefixer: {},
        cssnano: {},
    },
}

```

After downgrading to 2.3.1 it worked again.,..

**Comment by mischnic** [comment]
This is another instance of https://github.com/parcel-bundler/parcel/issues/6921
