### ISSUE TITLE
transformer-sass imports es/index.js instead of index.scss files for @use statements in a SCSS file

### ISSUE THREAD

**Issue by arcfide** [parcel-bundler/parcel#7923]
# 🐛 bug report

When using a `@use 'path';` line inside of `index.scss`, attempting to build through Parcel fails to load the `path/index.scss` file and instead loads `path/es/index.js`, leading to an error. The same file built explicitly with `sass --load-path=node_modules index.scss` works. 

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:

```js
{
  "source": "index.html",
  "scripts": {
    "start": "parcel serve",
    "build": "parcel build"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.4.1",
    "parcel": "^2.4.1"
  },
  "dependencies": {
    "@carbon/react": "^1.0.3",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  }
}
```

## 🤔 Expected Behavior

Building the `index.scss` file should work with `npm x -- parcel build index.scss`.

## 😯 Current Behavior

The following command works:

```
npm x -- sass -I node_modules index.scss index.css
```

But the following command fails:

```
>npm x -- parcel build index.scss
× Build failed.

@parcel/transformer-sass: expected "{".
╷
8 │ import './feature-flags.js';
│                            ^
╵
node_modules\@carbon\react\es\index.js 8:28  @use
index.scss 1:1                               root stylesheet

  Error: expected "{".
  ╷
  8 │ import './feature-flags.js';
  │                            ^
  ╵
  node_modules\@carbon\react\es\index.js 8:28  @use
  index.scss 1:1                               root stylesheet
  at Object.wrapException (C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:1254:17)
  at Object.throwWithTrace0 (C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:22948:15)
  at ScssParser0.wrapSpanFormatException$1$1
  (C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:89311:13)
  at ScssParser0.wrapSpanFormatException$1
  (C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:89317:19)
  at ScssParser0.parse$0 (C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:92996:19)
  at Object.Stylesheet_Stylesheet$parse0 (C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:22334:56)
  at C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:69814:63
  at _wrapJsFunctionForAsync_closure.$protected
  (C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:3737:15)
  at _wrapJsFunctionForAsync_closure.call$2
  (C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:28057:12)
  at _awaitOnObject_closure.call$1 (C:\Users\arcfi\OneDrive\Documents\ERP\node_modules\sass\sass.dart.js:28045:32)
```

## 💻 Code Sample

index.scss:

```
@use '@carbon/react';
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 16.13.2
| npm/Yarn         | 8.5.3
| Operating System | Windows 10 64-bit

**Comment by Daveiano** [comment]
Got the same error with 

`@use '@carbon/styles';`

Error Output:

```
🚨 Build failed.

@parcel/transformer-sass: expected "{".
╷
7 │ var black = '#000000';
│                      ^
╵
node_modules/@carbon/styles/node_modules/@carbon/colors/es/index.js 7:22  @forward
node_modules/@carbon/styles/scss/_colors.scss 8:1                         @forward
node_modules/@carbon/styles/index.scss 9:1                                @use
skins/weewx-wdc/src/scss/index.scss 1:1                                   root stylesheet
```

**Comment by tay1orjones** [comment]
Hey, I'm a maintainer on the Carbon team for the packages listed above. We're also running into this with the internal example apps we build for the above carbon packages. 

In addition to the above, we're also seeing the same problem if we `@import` a file that uses `@use`. The [interop](https://sass-lang.com/documentation/at-rules/import#import-and-modules) between `@use` and `@import` intended by the sass module system doesn't seem to be working.

I dug around a bit and discovered the following:

* Parcel's using sass v1.38.0
* Sass introduced a new JS API in [v1.45.0](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1450)
  * Specifically,
    > A new importer API that more closely matches the Sass specification's logic for resolving loads. This makes it much easier for Sass to cache information across `@import` and `@use` rules, which substantially improves performance for applications that rely heavily on repeated `@imports`.
* `transformer-sass` uses it's own reimplementation of the sass loader api - maybe this needs to be updated with the improved loader logic added in sass 1.45.0?

https://github.com/parcel-bundler/parcel/blob/9e5d05586577e89991ccf90400f2c741dca11aa3/packages/transformers/sass/src/SassTransformer.js#L104-L106

**Comment by nkdas91** [comment]
Got the same error with ```@use "@material/ripple";```

```
🚨 Build failed.

@parcel/transformer-sass: expected "{".
   ╷
23 │ import * as util from './util';
   │                               ^
   ╵
  node_modules/@material/ripple/index.js 23:31 
```

**Comment by sid137** [comment]
@tay1orjones just running into this as well.   What's your recommendation - drop parcel for now?  Or did you find a workaround ?

**Comment by sid137** [comment]
Here's a repo that reproduces this issue.  Can be shown by running

yarn
yarn start

[bug-parcel-sass](https://github.com/boundlessdigital/bug-parcel-sass)

**Comment by thathsara404** [comment]
@sid137 @nkdas91 @tay1orjones did you find any workaround for this?

**Comment by sid137** [comment]
> @sid137 @nkdas91 @tay1orjones did you find any workaround for this?

@thathsara404 

I didn't... but I switched to https://vitejs.dev/ and it just worked

**Comment by thathsara404** [comment]
Thanks @sid137 did you try webpack?

**Comment by sid137** [comment]
@thathsara404 I didn't... I was looking for something quick and easier to get started with, didn't want to spend a week dealing with webpack

**Comment by nkdas91** [comment]
> Thanks @sid137 did you try webpack?

@thathsara404 Yes it works with Webpack and Vite.

**Comment by thathsara404** [comment]
@nkdas91 @sid137 thank you for your responses.

**Comment by tay1orjones** [comment]
@sid137 @thathsara404 Yeah unfortunately we moved our sample apps off of parcel due to this. We've been using vite and nextjs instead.

**Comment by Lefthandmedia** [comment]
Look like sass is trying to resolve xxx.scss   as xxx.js.
in my app.scss i have @import 'settings'; 
but the error states
`@parcel/transformer-sass: expected "{".
╷
8 │ import './settings.js';
│  `
to be clear `settings.js` does noet exist `_settings.scss` does

**Comment by rkh** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed in 14 days if no further activity occurs.

Fair enough. I guess no one is using Parcel with SASS libraries? We definitely gave up on it because of this issue.
