### ISSUE TITLE
 Docker build on MacOS M1: No native build was found for platform=linux arch=arm64

### ISSUE THREAD

**Issue by Richard87** [parcel-bundler/parcel#7943]
# 🐛 bug report

Failed to run parcel build in docker on Apple M1 (natively).

## 🤔 Expected Behavior

Build should work

## 😯 Current Behavior

```
 Error: No native build was found for platform=linux arch=arm64 runtime=node abi=102 uv=1 armv=8 libc=glibc node=17.8.0
```

```
[builder 7/7] RUN cd /app && yarn run parcel build --cache-dir /.parcel-cache --public-url /build2:
#11 0.214 yarn run v1.22.18
#11 0.229 $ /app/node_modules/.bin/parcel build --cache-dir /.parcel-cache --public-url /build2
#11 0.392 Error: No native build was found for platform=linux arch=arm64 runtime=node abi=102 uv=1 armv=8 libc=glibc node=17.8.0
#11 0.392     loaded from: /app/node_modules/@parcel/watcher
#11 0.392 
#11 0.392     at Function.load.path (/app/node_modules/node-gyp-build/index.js:60:9)
#11 0.392     at load (/app/node_modules/node-gyp-build/index.js:22:30)
#11 0.392     at Object.<anonymous> (/app/node_modules/@parcel/watcher/index.js:1:104)
#11 0.392     at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
#11 0.392     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
#11 0.392     at Module.load (node:internal/modules/cjs/loader:975:32)
#11 0.392     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
#11 0.392     at Module.require (node:internal/modules/cjs/loader:999:19)
#11 0.392     at require (/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
#11 0.392     at Object.<anonymous> (/app/node_modules/@parcel/fs/lib/index.js:5:28)
#11 0.513 error Command failed with exit code 1.
#11 0.513 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c cd /app && yarn run parcel build --cache-dir /.parcel-cache --public-url /build2]: exit code: 1
➜  eportal git:(feature/folder-structure) ✗ 
```

## 💁 Possible Solution

No idea... :/

## 🔦 Context

Trying to build our docker container in native ARM, instead of x86/linux.

## 💻 Code Sample

Trying to build this container on M1:
 ```Dockerfile
FROM node:17 as builder
RUN mkdir -p /app
COPY frontend/package.json frontend/yarn.lock /app/
COPY frontend/tsconfig.json /app
# --mount=type=cache,id=npm-cache,target=/.npm-cache \
RUN cd /app && \
    npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && \
    npm config set "//npm.fontawesome.com/:_authToken" 09388961-7472-4FC8-9B00-2369A5A718AC && \
    yarn install --frozen-lockfile --ignore-scripts  --preferred-cache-folder /.npm-cache
COPY frontend/ /app/
RUN cd /app && yarn run parcel build --cache-dir /.parcel-cache --public-url /build2
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 17.8
| npm/Yarn         | Yarn
| Operating System | Docker Desktop on MacOS M1 12.2.1

**Comment by devongovett** [comment]
We'd need to add prebuilds for arm linux in the watcher module: https://github.com/parcel-bundler/watcher/blob/master/azure-pipelines.yml. Going to move this issue to that repo.

If you remove the `--ignore-scripts` option for `yarn` it should compile on install though.
