### ISSUE TITLE
Parcel serve fails with source maps

### ISSUE THREAD

**Issue by waltonseymour** [parcel-bundler/parcel#7949]
# 🐛 bug report

Wasn't sure if I should file this here or in https://github.com/parcel-bundler/source-map.

When running `parcel serve` with parcel 2.4.1 with source maps enabled I get an error.

## 🎛 Configuration (.babelrc, package.json, cli command)
`parcel serve`
```
{
      "scopeHoist": false,
      "sourceMap": true,
      "optimize": false
}
```

## 🤔 Expected Behavior

Development server should run with source maps successfully

## 😯 Current Behavior

```
@parcel/transformer-css: Invalid argument, T on unrwap is not the type of wrapped object

  Error: Invalid argument, T on unrwap is not the type of wrapped object
  at NodeSourceMap.extends (.../node_modules/@parcel/source-map/dist/node.js:58:35)
  at Object.transform (.../node_modules/@parcel/transformer-css/lib/CSSTransformer.js:174:20)
  at async Transformation.runTransformer (.../node_modules/@parcel/core/lib/Transformation.js:627:5)
  at async Transformation.runPipeline (.../node_modules/@parcel/core/lib/Transformation.js:376:36)
  at async Transformation.runPipelines (.../node_modules/@parcel/core/lib/Transformation.js:253:40)
  at async Transformation.runPipelines (.../node_modules/@parcel/core/lib/Transformation.js:297:34)
  at async Transformation.run (.../node_modules/@parcel/core/lib/Transformation.js:173:21)
  at async Child.handleRequest (.../node_modules/@parcel/workers/lib/child.js:217:9)

```

## 🔦 Context
Possibly related to https://github.com/parcel-bundler/parcel/issues/6425

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 16.14.0
| npm/Yarn         | 8.3.1
| Operating System | linux

**Comment by devongovett** [comment]
It is likely that you somehow have two different versions of `@parcel/source-map` installed. Maybe you need to delete one of them from your lock file?

**Comment by waltonseymour** [comment]
Yup two conflicting versions of `2.0.0` and `2.0.2`.

Thanks!

**Comment by jonasbraga** [comment]
I started having the same error after changing my package manager to pnpm
to fix it I had to install the @parcel/source-map package directly to my dev dependencies

**Comment by aspiers** [comment]
I have the same issue with yarn.  Installing @parcel/source-map as a dev dependency doesn't help.
