### ISSUE TITLE
🐛? Import, Dynamic import doesn't work (anyway for me)

### ISSUE THREAD

**Issue by mikkiek** [parcel-bundler/parcel#804]
Hello,

I've very simple code, and somehow it doesn't work for me. Probably i'm doing something wrong, but i'm not so expirenced to understand what exactly wrong.

index.html
```
<!DOCTYPE html>
<html>
    <body>
        <script type="text/javascript" src="./index.js"></script>
    </body>
</html>
```
index.js
```
import 'babel-polyfill';
const module = import('./test');
```
test.js
```
export function About() {
    alert('about!');
}
```
.babelrc
```
{
    "presets": [
        "env",
        "stage-2"
    ]
}
```
package.json
```
{
    "dependencies": {
        "babel-polyfill": "^6.26.0",
        "deepmerge": "^2.0.1",
        "material-design-icons": "^3.0.1",
        "vue": "^2.5.13",
        "vue-resource": "^1.3.5",
        "vue-router": "^3.0.1",
        "vue2-animate": "^1.0.4",
        "vuex": "^3.0.1"
    },
    "devDependencies": {
        "autoprefixer": "^8.0.0",
        "babel-core": "^6.26.0",
        "babel-plugin-transform-runtime": "^6.23.0",
        "babel-preset-env": "^1.6.1",
        "babel-preset-stage-2": "^6.24.1",
        "babel-preset-vue": "^2.0.1",
        "cross-env": "^5.1.3",
        "css-loader": "^0.28.9",
        "node-sass": "^4.7.2",
        "parcel-bundler": "^1.5.1",
        "parcel-plugin-vue": "^1.5.0"
    }
}
```
### 🤔 Expected Behavior
I've expected it will work, but seems my dreams can't come true, anyway not today.

### 😯 Current Behavior
Hardly believe it might be correct.
```
> parcel --port 5555 --no-cache .debug/src/index.html --out-dir .debug/dist

Server running at http://localhost:5555
×  Cannot read property 'add' of undefined
    at JSPackager.addAsset (D:\repository\node_modules\parcel-bundler\src\packagers\JSPackager.js:47:32)
    at Bundle._addDeps (D:\repository\node_modules\parcel-bundler\src\Bundle.js:146:20)
    at <anonymous>
```

### 💁 Possible Solution
No idea, at all.

**Comment by mischnic** [comment]
Same error message as in #659. Is a bug in parcel-plugin-vue, see https://github.com/BoltDoggy/parcel-plugin-vue/issues/24.

Works with  parcel-plugin-vue removed.

--- 
@DeMoorJasper, is this how it's supposed to be? (`data.error.stack`)

![bildschirmfoto 2018-02-19 um 14 37 56](https://user-images.githubusercontent.com/4586894/36380476-bd0e1ed0-1582-11e8-9527-0f7248319b2b.png)

**Comment by DeMoorJasper** [comment]
Appears to be the same issue indeed
