### ISSUE TITLE
Cannot read properties of undefined (reading 'NODE_ENV')

### ISSUE THREAD

**Issue by spointecker** [parcel-bundler/parcel#8041]
# 🐛 bug report

My app is not rendering due to the given javascript exception.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "modules": false,
                "useBuiltIns": false,
                "targets": {
                    "node": "current"
                }
            }
        ],
        "@babel/preset-react"
    ],
    "plugins": ["babel-plugin-styled-components"],
    "env": {
        "test": {
            "plugins": ["@babel/plugin-transform-modules-commonjs"]
        }
    }
}

```

```
{
 "dependencies": {
        "@fingerprintjs/fingerprintjs": "^2.1.5",
        "@react-icons/all-files": "^4.1.0",
        "@sentry/react": "^6.19.7",
        "body-scroll-lock": "^3.1.3",
        "bulma": "^0.9.3",
        "cogo-toast": "^4.2.3",
        "focus-trap-react": "^8.11.0",
        "formik": "^2.2.9",
        "framer-motion": "^6.3.3",
        "query-string": "^7.1.1",
        "react": "^17.0.2",
        "react-autosuggest": "^10.1.0",
        "react-dom": "^17.0.2",
        "react-facebook-login": "^4.1.1",
        "react-google-login": "^5.2.2",
        "react-intl": "^5.25.1",
        "react-router-dom": "^5.2.0",
        "react-sticky-el": "^2.0.9",
        "react-truncate": "^2.4.0",
        "styled-components": "^5.3.5",
        "yup": "^0.32.11"
    },
    "devDependencies": {
        "@babel/core": "^7.17.10",
        "@babel/eslint-parser": "^7.17.0",
        "@babel/preset-env": "7.17.10",
        "@babel/preset-react": "7.16.7",
        "@parcel/optimizer-htmlnano": "2.5.0",
        "@parcel/packager-css": "2.5.0",
        "@parcel/packager-html": "2.5.0",
        "@parcel/transformer-css": "2.5.0",
        "@parcel/transformer-html": "2.5.0",
        "@parcel/transformer-image": "2.5.0",
        "@parcel/transformer-inline-string": "2.5.0",
        "@parcel/transformer-postcss": "2.5.0",
        "@parcel/transformer-posthtml": "2.5.0",
        "@parcel/transformer-sass": "2.5.0",
        "@testing-library/jest-dom": "^5.16.4",
        "@testing-library/react": "^11.2.6",
        "@testing-library/react-hooks": "^7.0.2",
        "@testing-library/user-event": "^13.1.8",
        "@types/react": "^17.0.39",
        "autoprefixer": "^10.4.6",
        "babel-jest": "^27.2.1",
        "babel-plugin-styled-components": "^1.13.2",
        "eslint": "^7.26.0",
        "eslint-plugin-react": "^7.29.4",
        "jest": "^26.6.3",
        "jest-styled-components": "^7.0.8",
        "jest-transform-stub": "^2.0.0",
        "node-sass": "^7.0.1",
        "parcel": "^2.5.0",
        "react-test-renderer": "^17.0.2",
        "sass": "^1.51.0"
    },

    "browserslist": [
        "> 0.25%",
        "IE 11",
        "not dead"
    ]
}
``` 
## 🤔 Expected Behavior

The app is rendering without exception. According the parcel documentation the env var NODE_ENV should be set automatically: 
"The NODE_ENV environment variable is automatically set by Parcel depending on the mode. When running parcel build, NODE_ENV is set to production by default, otherwise it is set to development. This can be overridden by setting NODE_ENV yourself (e.g. in your shell)."
And it has been working before but isn't since version 2.4.0.

## 😯 Current Behavior

The app is building via parcel but the browser is throwing the following exception:
```
index.mjs:13 Uncaught TypeError: Cannot read properties of undefined (reading 'NODE_ENV')
    at Object.fBuY4.tslib (index.mjs:13:25)
    at newRequire (index.975ef6c8.js:71:24)
    at localRequire (index.975ef6c8.js:84:35)
    at Object.5bZBB../render/dom/motion.mjs (index.mjs:3:1)
    at newRequire (index.975ef6c8.js:71:24)
    at localRequire (index.975ef6c8.js:84:35)
    at Object.6xZ89.react/jsx-dev-runtime (NotificationBar.jsx:1:1)
    at newRequire (index.975ef6c8.js:71:24)
    at localRequire (index.975ef6c8.js:84:35)
    at Object.42KXG.react/jsx-dev-runtime (AppRequirementsBar.jsx:8:1)
```
Code where exception is thrown:
```
var isDev = process.env.NODE_ENV !== "production";
```
It seems that the `motion` lib already accesses the `process.env` and this is undefined at that moment.

## 💁 Possible Solution

It worked with parcel version <2.4.0 so maybe a change in parcel is causing the problem.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 17.7.1
|Yarn         | 1.22.18
| Operating System | Mac OS 12.3.1

**Comment by mischnic** [comment]
Please provide a reproduction or more details.
Building a file with
```js
var isDev = process.env.NODE_ENV !== "production";
console.log(isDev)
```
works fine for me (gets replaced with `var isDev = false;`)

**Comment by spointecker** [comment]
Alright I found the issue on my side. I had this alias due to a other error which has already been fixed by parcel in my `package.json`:
```
     "alias": {
         "base": "~/base",
        "base/views": "~/base/views",
        "process": {
           "global": "{}"
        }
     },
```

After this I had to add the [process](https://www.npmjs.com/package/process) package and then it worked like expected.
