### ISSUE TITLE
@parcel/transformer-js: cannot access a scoped thread local variable without calling `set` first

### ISSUE THREAD

**Issue by satvikt** [parcel-bundler/parcel#8111]
# 🐛 bug report

`parcel index.html` results in the following error:

![Screenshot from 2022-05-19 23-45-54](https://user-images.githubusercontent.com/21122115/169379465-29f30a8d-466b-4cc8-8140-2dbd76536692.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "@algolia/autocomplete-example-tags-in-searchbox",
  "description": "Autocomplete example with Tags in the searchbox",
  "version": "1.6.3",
  "private": true,
  "license": "MIT",
  "scripts": {
    "build": "parcel build index.html",
    "start": "parcel index.html"
  },
  "dependencies": {
    "@algolia/autocomplete-js": "1.6.3",
    "@algolia/autocomplete-plugin-algolia-insights": "1.6.3",
    "@algolia/autocomplete-plugin-tags": "1.6.3",
    "@algolia/autocomplete-theme-classic": "1.6.3",
    "@algolia/client-search": "4.9.1",
    "algoliasearch": "4.9.1",
    "@parcel/transformer-js": "2.5.0",
    "preact": "10.5.13",
    "ramda": "0.27.1",
    "search-insights": "1.7.1"
  },
  "devDependencies": {
    "parcel": "2.5.0"
  },
  "keywords": [
    "algolia",
    "autocomplete",
    "javascript"
  ]
}

```

## 🤔 Expected Behavior

Build should succeed and The application should run without any error.

## 😯 Current Behavior

Getting the following error 

`@parcel/transformer-js: cannot access a scoped thread local variable without calling set first`

### Stacktrace
```
yarn run v1.18.0
$ parcel index.html
Server running at http://localhost:1234

@parcel/transformer-babel: It looks like you're using a JavaScript Babel config file. This means the config cannot be watched for changes, and Babel transformations
cannot be cached. You'll need to restart Parcel for changes to this config to take effect. Try using a babel.config.json file instead.


@parcel/transformer-babel: It looks like you are using `require` to configure Babel plugins or presets. This means Babel transformations cannot be cached and will run
on each build. Please use strings to configure Babel instead.

Installing @parcel/transformer-sass...
⠼ Building stream-browser.js...
thread '<unnamed>' panicked at 'cannot access a scoped thread local variable without calling `set` first', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:168:9
yarn: [1/4] Resolving packages
yarn: [2/4] Fetching packages
@parcel/package-manager: yarn: fsevents@2.3.2: The platform "linux" is incompatible with this module.
@parcel/package-manager: yarn: "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
@parcel/package-manager: yarn: esbuild-android-64@0.14.39: The platform "linux" is incompatible with this module.
@parcel/package-manager: yarn: "esbuild-android-64@0.14.39" is an optional dependency and failed compatibility check. Excluding it from installation.
@parcel/package-manager: yarn: esbuild-android-arm64@0.14.39: The platform "linux" is incompatible with this module.
@parcel/package-manager: yarn: "esbuild-android-arm64@0.14.39" is an optional dependency and failed compatibility check. Excluding it from installation.
@parcel/package-manager: yarn: esbuild-android-arm64@0.14.39: The CPU architecture "x64" is incompatible with this module.
@parcel/package-manager: yarn: esbuild-darwin-64@0.14.39: The platform "linux" is incompatible with this module.
@parcel/package-manager: yarn: "esbuild-darwin-64@0.14.39" is an optional dependency and failed compatibility check. Excluding it from installation.
@parcel/package-manager: yarn: esbuild-darwin-arm64@0.14.39: The platform "linux" is incompatible with this module.
@parcel/package-manager: yarn: "esbuild-darwin-arm64@0.14.39" is an optional dependency and failed compatibility check. Excluding it from installation.
@parcel/package-manager: yarn: esbuild-darwin-arm64@0.14.39: The CPU architecture "x64" is incompatible with this module.
@parcel/package-manager: yarn: esbuild-freebsd-64@0.14.39: The platform "linux" is incompatible with this module.
@parcel/package-manager: yarn: "esbuild-freebsd-64@0.14.39" is an optional dependency and failed compatibility check. Excluding it from installation.
Server running at http://localhost:1234
🚨 Build failed.

@parcel/transformer-js: cannot access a scoped thread local variable without calling `set` first

  Error: cannot access a scoped thread local variable without calling `set` first
  at Object.transform (/home/satvik/Documents/project/autocomplete_2/node_modules/@parcel/transformer-js/lib/JSTransformer.js:379:31)
  at async Transformation.runTransformer (/home/satvik/Documents/project/autocomplete_2/node_modules/@parcel/core/lib/Transformation.js:627:5)
  at async Transformation.runPipeline (/home/satvik/Documents/project/autocomplete_2/node_modules/@parcel/core/lib/Transformation.js:376:36)
  at async Transformation.runPipelines (/home/satvik/Documents/project/autocomplete_2/node_modules/@parcel/core/lib/Transformation.js:253:40)
  at async Transformation.run (/home/satvik/Documents/project/autocomplete_2/node_modules/@parcel/core/lib/Transformation.js:173:21)
  at async Child.handleRequest (/home/satvik/Documents/project/autocomplete_2/node_modules/@parcel/workers/lib/child.js:217:9)

```

Have been through existing issues #6605 , #7234 and stackoverflow [answer](https://stackoverflow.com/q/69797352)

Have tried all solutions mentioned at the above links, none to any avail.

1. Remove `node_modules` directory and installed
2. Removed the pragma `/** @jsx h */`
3. Kept `/** @jsxRuntime classic */` as pragma on top of app.tsx.

## 💻 Code Sample

the code has been taken from [Algolia Autocomplete example](https://github.com/algolia/autocomplete/tree/next/examples/tags-in-searchbox).
The project files are attached in the following zip

[tags-in-searchbox.zip](https://github.com/parcel-bundler/parcel/files/8733069/tags-in-searchbox.zip)

Steps to install dependencies and start:

```
yarn install --force --ignore-engines
yarn start
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | v18.1.0
| npm/Yarn         | 8.8.0/1.18.0
| Operating System | Ubuntu 20.04

**Comment by mischnic** [comment]
> Steps to install dependencies and start:

This works fine for me.

**Comment by satvikt** [comment]
@mischnic  Can you provide the versions of the following, so that i can try and check in a similar environment?

1.  Parcel
2. Yarn/npm
3. Node
4. OS

**Comment by mischnic** [comment]
Here's your zip but including my Yarn lockfile: [tags-in-searchbox 2.zip](https://github.com/parcel-bundler/parcel/files/8743736/tags-in-searchbox.2.zip)


Yarn 1.22.18, macOS 12, Node 16.15.0 or v18.2.0
