### ISSUE TITLE
Error: Cannot find module '../parcel_sourcemap_node/index

### ISSUE THREAD

**Issue by jtojnar** [parcel-bundler/parcel#8115]
# 🐛 bug report

After updating to latest parcel version I get `Error: Cannot find module '../parcel_sourcemap_node/index'`

## 🤔 Expected Behavior

It should succeed.

## 😯 Current Behavior

```
> parcel watch index.html --dist-dir ../client/ --public-url ./

Error: Cannot find module '../parcel_sourcemap_node/index'ted in 2ms
Require stack:
- /home/jtojnar/Projects/pengu/node_modules/@parcel/source-map/dist/node.js
- /home/jtojnar/Projects/pengu/node_modules/@parcel/utils/lib/index.js
- /home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/public/Config.js
- /home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/utils.js
- /home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/public/Environment.js
- /home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/public/Asset.js
- /home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/Parcel.js
- /home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/index.js
- /home/jtojnar/Projects/pengu/node_modules/parcel/lib/cli.js
- /home/jtojnar/Projects/pengu/node_modules/parcel/lib/bin.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/home/jtojnar/Projects/pengu/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/jtojnar/Projects/pengu/node_modules/@parcel/source-map/dist/node.js:14:18)
    at Module._compile (/home/jtojnar/Projects/pengu/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jtojnar/Projects/pengu/node_modules/@parcel/source-map/dist/node.js',
    '/home/jtojnar/Projects/pengu/node_modules/@parcel/utils/lib/index.js',
    '/home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/public/Config.js',
    '/home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/utils.js',
    '/home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/public/Environment.js',
    '/home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/public/Asset.js',
    '/home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/Parcel.js',
    '/home/jtojnar/Projects/pengu/node_modules/@parcel/core/lib/index.js',
    '/home/jtojnar/Projects/pengu/node_modules/parcel/lib/cli.js',
    '/home/jtojnar/Projects/pengu/node_modules/parcel/lib/bin.js'
  ]
}
```

## 🔦 Context

It looks like the `@parcel/source-map` is missing `parcel_sourcemap_node/index` file in <https://registry.npmjs.org/@parcel/source-map/-/source-map-2.0.4.tgz>. It was present in <https://registry.npmjs.org/@parcel/source-map/-/source-map-2.0.2.tgz>.

## 💻 Code Sample

https://github.com/jtojnar/pengu/tree/bump

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.5.0
| Node             |v18.1.0
| npm         |8.8.0
| Operating System |Linux

**Comment by jtojnar** [comment]
Duplicate of #8114
