### ISSUE TITLE
Parcel transpiles dynamic import wrong, when wrapped into `Promise.resolve()`

### ISSUE THREAD

**Issue by SmartArray** [parcel-bundler/parcel#8116]
# 🐛 bug report

We are trying to import a module from a mono repo. That monorepo is setup correctly but it imports another library with `import()` wrapped into a `Promise.resolve()`

However, when parcel transpiles the code, we got a runtime error with `res is not defined`.

I successfully created a minimalistic example that helps us to reproduce the issue. It doesn't seem to be an issue with `babel`. Though, I hope you guys can help me to identify the source of the issue.

## 🎛 Configuration (.babelrc, package.json, cli command)
This issue can be reproduced with parcel's default babel config, so I removed it completely.
The package json looks like this:

```json
{
  "name": "xxx",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "source": "index.html",
  "dependencies": {
    "prando": "^6.0.1"
  },
  "scripts": {
    "start": "parcel index.html",
    "babel": "babel index.js --out-file babel/script-compiled.js  --presets=@babel/preset-env"
  },
  "devDependencies": {
    "@babel/cli": "^7.17.10",
    "@babel/core": "^7.18.0",
    "@parcel/babel-preset": "^2.0.0-alpha.2",
    "parcel": "^2.5.0"
  }
}
```

My `index.html`:
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>My First Parcel App</title>
    <script type="module" src="index.js"></script>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```

And last but not least, my index.js:

```javascript
class Test {
  constructor() {
    this.someModule = null;
    this.seed = 123;
  }

  async loadInvalid() {
    const this$4 = this;

    if (!this.someModule) {
      // An import wrapped into Promise.resolve() causes issues. The callbacks 
      // will be ordered incorrectly.
      return Promise.resolve(import('prando').then(function (m) {
        var _m$default;

        return (_m$default = m == null ? void 0 : m["default"]) != null ? _m$default : m;
      })).then(function (SomeModule) {
        this$4.someModule = new SomeModule(this$4.seed);
      });
    } 
  }

  async loadValid() {
    const this$4 = this;

    if (!this.someModule) {
      return import('prando').then(function (m) {
        var _m$default;

        return (_m$default = m == null ? void 0 : m["default"]) != null ? _m$default : m;
      }).then(function (SomeModule) {
        this$4.someModule = new SomeModule(this$4.seed);
      });
    }     
  }
}

window.onload = () => {
  const test = new Test();

  test.loadValid().then(() => {
    console.log('Valid', test.someModule);
  });

  test.loadInvalid().then(() => {
    console.log('Invalid', test.someModule);
  });
};
```
## 🤔 Expected Behavior

`loadInvalid()` should work like `loadValid()`. It should load the library without any definition issues.

## 😯 Current Behavior

Instead, the source code gets transpiled with invalid ordering of the promises, so that a variable `res` is defined in the wrong scope.

```
Uncaught (in promise) ReferenceError: res is not defined
    at Test.loadInvalid (index.js:11:30)
    at window.onload (index.js:43:8)
```

## 💁 Possible Solution
Step 1: Identify the exact root cause for the issue. I wasn't able to reproduce it with babel alone. Please checkout `yarn babel` and open `babel/index.html` in your browser. Both methods will work correctly.
Step 2: Find out, why code gets restructured incorrectly when wrapped into `Promise.resolve()`

## 🔦 Context
I can't change the code of the module that I am importing, but this module gets transpiled by parcel, such that we receive the above error. The module wraps the import into a `Promise.resolve()` for whatever reason.

By the way, is there a way to turn off transpilation for a specific module?

## 💻 Code Sample

[promise-resolve-issue.zip](https://github.com/parcel-bundler/parcel/files/8738166/promise-resolve-issue.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 16.15.0
| npm/Yarn         | 1.22.18
| Operating System | Mac OS

**Comment by devongovett** [comment]
[Minimal reproduction](https://parcel2-repl-mischnic.vercel.app/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyUHJvbWlzZS5yZXNvbHZlKGltcG9ydCgnLiUyRm90aGVyJykpLnRoZW4oeCUyMCUzRCUzRSUyMGNvbnNvbGUubG9nKHgpKSU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyU1QiUyMiUyRnNyYyUyRm90aGVyLmpzJTIyJTJDJTdCJTIydmFsdWUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMHglMjAlM0QlMjAyJTNCJTIyJTdEJTVEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmVudHJpZXMlMjIlM0ElNUIlNUQlMkMlMjJtaW5pZnklMjIlM0FmYWxzZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0FmYWxzZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMnB1YmxpY1VybCUyMiUzQSUyMiUyRl9fcmVwbF9kaXN0JTIyJTJDJTIydGFyZ2V0VHlwZSUyMiUzQSUyMmJyb3dzZXJzJTIyJTJDJTIydGFyZ2V0RW52JTIyJTNBJTIyQ2hyb21lJTIwOTUlMjIlMkMlMjJvdXRwdXRGb3JtYXQlMjIlM0ElMjJlc21vZHVsZSUyMiUyQyUyMmhtciUyMiUzQWZhbHNlJTJDJTIybW9kZSUyMiUzQSUyMmRldmVsb3BtZW50JTIyJTJDJTIycmVuZGVyR3JhcGhzJTIyJTNBZmFsc2UlMkMlMjJ2aWV3U291cmNlbWFwcyUyMiUzQWZhbHNlJTJDJTIyZGVwZW5kZW5jaWVzJTIyJTNBJTVCJTVEJTJDJTIybnVtV29ya2VycyUyMiUzQTAlN0QlMkMlMjJ1c2VUYWJzJTIyJTNBZmFsc2UlMkMlMjJicm93c2VyQ29sbGFwc2VkJTIyJTNBJTVCJTVEJTJDJTIydmlld3MlMjIlM0ElNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyUyMiUyRnNyYyUyRm90aGVyLmpzJTIyJTJDJTIyT3B0aW9ucyUyMiU1RCUyQyUyMmN1cnJlbnRWaWV3JTIyJTNBMiU3RA==)

**Comment by SmartArray** [comment]
Hey @devongovett 

This is great, thank you. I love this playground and I didn't know it existed.

Looking forward to help fixing this. Can you point me to the right direction which part of the project transpiles the code?

**Comment by TechQuery** [comment]
@devongovett `parcel@^2.16` compiles incorrectly for **Dynamic Import** without `async` & `await`:

```js
import * as $xxx from 'some-library';

$xxx.then(); // should be `Promise.resolve($xxx).then();` at least
```

but [Parcel REPL works fine][1].

- real world code: idea2app/MobX-RESTful@eddcac6

[1]: https://parcel2-repl-mischnic.vercel.app/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyZXhwb3J0JTIwY2xhc3MlMjBUZXN0JTIwJTdCJTVDbiUyMCUyMHN0YXRpYyUyMGRldGVjdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTVDbiUyMCUyMCUyMCUyMGltcG9ydCgnaWRiLWtleXZhbCcpLnRoZW4oKCU3QiUyMGdldCUyMCU3RCklMjAlM0QlM0UlMjBnZXQoJ3JlYWR5JykpJTNCJTVDbiU1Q24lMjAlMjBhc3luYyUyMGxvYWQoa2V5KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zdCUyMCU3QiUyMGdldCUyMCU3RCUyMCUzRCUyMGF3YWl0JTIwaW1wb3J0KCdpZGIta2V5dmFsJyklM0IlNUNuJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMGdldChrZXkpJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJlbnRyaWVzJTIyJTNBJTVCJTVEJTJDJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBZmFsc2UlMkMlMjJzb3VyY2VNYXBzJTIyJTNBZmFsc2UlMkMlMjJwdWJsaWNVcmwlMjIlM0ElMjIlMkZfX3JlcGxfZGlzdCUyMiUyQyUyMnRhcmdldFR5cGUlMjIlM0ElMjJicm93c2VycyUyMiUyQyUyMnRhcmdldEVudiUyMiUzQSUyMiUzRSUyMDAuNSUyNSUyQyUyMGxhc3QlMjAyJTIwdmVyc2lvbnMlMkMlMjBub3QlMjBkZWFkJTJDJTIwSUUlMjAxMSUyMiUyQyUyMm91dHB1dEZvcm1hdCUyMiUzQSUyMmNvbW1vbmpzJTIyJTJDJTIyaG1yJTIyJTNBZmFsc2UlMkMlMjJtb2RlJTIyJTNBJTIycHJvZHVjdGlvbiUyMiUyQyUyMnJlbmRlckdyYXBocyUyMiUzQWZhbHNlJTJDJTIydmlld1NvdXJjZW1hcHMlMjIlM0FmYWxzZSUyQyUyMmRlcGVuZGVuY2llcyUyMiUzQSU1QiU1QiUyMiU0MHN3YyUyRmhlbHBlcnMlMjIlMkMlMjIlNUUwLjUuMTclMjIlNUQlMkMlNUIlMjJpZGIta2V5dmFsJTIyJTJDJTIyJTVFNiUyMiU1RCU1RCUyQyUyMm51bVdvcmtlcnMlMjIlM0EwJTdEJTJDJTIydXNlVGFicyUyMiUzQWZhbHNlJTJDJTIyYnJvd3NlckNvbGxhcHNlZCUyMiUzQSU1QiU1RCUyQyUyMnZpZXdzJTIyJTNBJTVCJTIyJTJGc3JjJTJGaW5kZXguanMlMjIlMkMlMjJPcHRpb25zJTIyJTVEJTJDJTIyY3VycmVudFZpZXclMjIlM0ExJTdE
