### ISSUE TITLE
choking on HTML entities within inline-SVG

### ISSUE THREAD

**Issue by SirkoS** [parcel-bundler/parcel#8124]
# 🐛 bug report

When running parcel on an HTML document with an embedded SVG that uses named HTML entities like below, the build fails with an error.

```html
<!doctype html>
<html>
<body>
  <svg viewBox="0 0 100 100">
    <text x="20" y="20" style="fill: black;">&cross;</text>
  </svg>
</body>
</html>
```

Replacing the HTML entity with its numeric variation (`&#10007;`) seems to work just fine.

## 🤔 Expected Behavior

No error. Simply return an (almost) unchanged HTML file.

## 😯 Current Behavior

```
× Build failed.

@parcel/optimizer-htmlnano: Cannot read properties of undefined (reading 'attrs')

  TypeError: Cannot read properties of undefined (reading 'attrs')
  at path\node_modules\.pnpm\htmlnano@2.0.2_svgo@2.8.0\node_modules\htmlnano\lib\modules\sortAttributesWithLists.js:77:15
  at traverse (path\node_modules\.pnpm\posthtml@0.16.6\node_modules\posthtml\lib\api.js:105:26)
  at traverse (path\node_modules\.pnpm\posthtml@0.16.6\node_modules\posthtml\lib\api.js:111:5)
  at traverse (path\node_modules\.pnpm\posthtml@0.16.6\node_modules\posthtml\lib\api.js:105:17)
  at traverse (path\node_modules\.pnpm\posthtml@0.16.6\node_modules\posthtml\lib\api.js:111:5)
  at traverse (path\node_modules\.pnpm\posthtml@0.16.6\node_modules\posthtml\lib\api.js:105:17)
  at traverse (path\node_modules\.pnpm\posthtml@0.16.6\node_modules\posthtml\lib\api.js:111:5)
  at traverse (path\node_modules\.pnpm\posthtml@0.16.6\node_modules\posthtml\lib\api.js:105:17)
  at Array.walk (path\node_modules\.pnpm\posthtml@0.16.6\node_modules\posthtml\lib\api.js:39:10)
  at sortAttributesWithListsInAlphabeticalOrder (path\node_modules\.pnpm\htmlnano@2.0.2_svgo@2.8.0\node_modules\htmlnano\lib\modules\sortAttributesWithLists.js:76:8)
```

## 💁 Possible Solution

Named entities are not defined in standalone SVG according to [this SO answer](https://stackoverflow.com/a/18473406/1169798). However, they work in inline SVG (open the above file directly in your browser).

So it seems this inline SVG is treated as standalone SVG at some point during the pipeline.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 18.2.0

**Comment by devongovett** [comment]
Looks like the issue is occurring in htmlnano. Maybe file an issue over there instead? https://github.com/posthtml/htmlnano

**Comment by OzzyCzech** [comment]
have same issue here - check https://github.com/posthtml/htmlnano/issues/197

```text
parcel build --dist-dir public/dist --public-url /dist --no-cache               
🚨 Build failed.

@parcel/optimizer-htmlnano: Cannot read properties of undefined (reading 'attrs')

  TypeError: Cannot read properties of undefined (reading 'attrs')
  at /Volumes/Work/testomato.com/node_modules/htmlnano/lib/modules/sortAttributesWithLists.js:77:15
  at traverse (/Volumes/Work/testomato.com/node_modules/posthtml/lib/api.js:105:26)
  at traverse (/Volumes/Work/testomato.com/node_modules/posthtml/lib/api.js:111:5)
  at traverse (/Volumes/Work/testomato.com/node_modules/posthtml/lib/api.js:105:17)
  at traverse (/Volumes/Work/testomato.com/node_modules/posthtml/lib/api.js:111:5)
  at traverse (/Volumes/Work/testomato.com/node_modules/posthtml/lib/api.js:105:17)
  at traverse (/Volumes/Work/testomato.com/node_modules/posthtml/lib/api.js:111:5)
  at traverse (/Volumes/Work/testomato.com/node_modules/posthtml/lib/api.js:105:17)
  at traverse (/Volumes/Work/testomato.com/node_modules/posthtml/lib/api.js:111:5)
  at traverse (/Volumes/Work/testomato.com/node_modules/posthtml/lib/api.js:105:17)
```

Temporary workaround, create `.htmlnanorc` file in the root and disable SVG minification with

```json
{
  "minifySvg": false
}
```

**Comment by SirkoS** [comment]
should be fixed with the next release after https://github.com/posthtml/htmlnano/pull/198
