### ISSUE TITLE
Parcel 2.6.0 segmentation fault on armv7l

### ISSUE THREAD

**Issue by supernes** [parcel-bundler/parcel#8174]
# 🐛 bug report

Parcel 2.6.0 segfaults when running on simple inputs because of lmdb-js v2.3.x.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
$ npx parcel src/repro.html 
Server running at http://localhost:1234
⠴ Optimizing repro.[hash].js...
Segmentation fault
```

# 💁 Possible Solution

Downgrade lmdb-js to v.2.2.4 with package.json override.

## 🔦 Context

https://github.com/DoctorEvidence/lmdb-js/issues/174

## 💻 Code Sample

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  This will not package successfully.
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.6.0
| Node             |v16.13.1
| npm/Yarn         |8.10.0
| Operating System |Linux 5.15.32 armv7l

**Comment by supernes** [comment]
Here's a backtrace of the fault:

```bash
Thread 8 "node" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb37bf400 (LWP 4757)]
0xb3ae93be in LZ4_compress_fast_continue () from .../node_modules/lmdb-linux-arm/node.napi.glibc.node

#0  0xb3ae93be in LZ4_compress_fast_continue () from .../node_modules/lmdb-linux-arm/node.napi.glibc.node
#1  0xb3afe3f0 in CompressionWorker::Execute() () from .../node_modules/lmdb-linux-arm/node.napi.glibc.node
#2  0x03a7c270 in zero_statbuf ()

Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

GLibC version is 2.31 (`2.31-13+rpt2+rpi1+deb11u2`)
