### ISSUE TITLE
ERR_DLOPEN_FAILED Error when trying to run parcel

### ISSUE THREAD

**Issue by ubeydeozdmr** [parcel-bundler/parcel#8190]
First of all, hello everyone,

Although dependencies and dev dependencies are specified in the package.json file (I also downloaded the modules to the node_modules folder with the npm install command), I get the following error when I enter the npx parcel index.html command. What would be the reason?

Edit: While I didn't have this problem on my old computer, I am having it on my new computer. I have this problem especially when using parcel

```
  "devDependencies": {
    "@parcel/transformer-sass": "^2.6.0",
    "parcel": "^2.6.0"
  },
  "dependencies": {
    "bootstrap-icons": "^1.8.3"
  }
```

Console output:

```
PS C:\Users\ubeyd\GitHub\countrypedia> npx parcel index.html
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Error: The specified module could not be found.
\\?\C:\Users\ubeyd\GitHub\countrypedia\node_modules\@parcel\source-map\parcel_sourcemap_node\artifacts\index.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\ubeyd\GitHub\countrypedia\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\ubeyd\GitHub\countrypedia\node_modules\@parcel\source-map\parcel_sourcemap_node\index.js:15:18)
    at Module._compile (C:\Users\ubeyd\GitHub\countrypedia\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by mischnic** [comment]
Which files does this directory contain `C:\Users\ubeyd\GitHub\countrypedia\node_modules\@parcel\source-map\parcel_sourcemap_node\artifacts\`?

**Comment by ubeydeozdmr** [comment]
> Which files does this directory contain `C:\Users\ubeyd\GitHub\countrypedia\node_modules\@parcel\source-map\parcel_sourcemap_node\artifacts\`?

![image](https://user-images.githubusercontent.com/89304966/172055474-2e9040b2-2220-4d75-882e-f599db611335.png)

**Comment by ubeydeozdmr** [comment]
I think at this point there is an error related to the operating system or node.js installation. Parcel worked successfully on Fedora Linux, which I used with dualboot on the same computer, my old windows 11 computer did the same. But I noticed that there is a problem with the w11 on my new device, but I could not find a solution on the internet.

**Comment by ubeydeozdmr** [comment]
My problem is solved: https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755

**Comment by ambastos** [comment]
OMG, Thanks a lot ubeydeozdmr!

**Comment by ubeydeozdmr** [comment]
> OMG, Thanks a lot ubeydeozdmr!

You're welcome

**Comment by hassammuhammad** [comment]
My problem is solved also thanks

**Comment by ubeydeozdmr** [comment]
> My problem is solved also thanks

You're welcome
