### ISSUE TITLE
Circular dependency detection broken in Parcel 2.6.0, causing "Error: Bundles must have unique names"

### ISSUE THREAD

**Issue by Tomalak** [parcel-bundler/parcel#8219]
# 🐛 bug report

When using HTML blocks that contain links to HTML files, parcel will run run into a "Bundles must have unique names" error upon build. The dev server however is fine.

## 🎛 Configuration

Minimal reproducible example:

`package.json`
```json
{
  "devDependencies": {
    "parcel": "^2.6.0"
  }
}
```

`index.html`
```html
<h1>Index</h1>
<nav></nav>
<script type="module">
    import * as nav from 'bundle-text:./components/nav.html';
    document.querySelector('nav').innerHTML = nav;
</script>
```

`components/nav.html`
```html
<a href="../index.html">Index</a>
<!-- more links... -->
```

CLI command

The following actually works. The browser opens and the the nav link is functional.
```
yarn parcel index.html --open
```

This fails:
```
yarn parcel build index.html
```

## 🤔 Expected Behavior

The project should compile, just as it does in dev server mode.

## 😯 Current Behavior

```
> yarn parcel build index.html
yarn run v1.22.10
warning package.json: No license field
$ C:\test\node_modules\.bin\parcel build index.html
× Build failed.

Error: Bundles must have unique names

  AssertionError [ERR_ASSERTION]: Bundles must have unique names
      at BundlerRunner.nameBundles (C:\test\node_modules\@parcel\core\lib\requests\BundleGraphRequest.js:343:23)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async BundlerRunner.bundle (C:\test\node_modules\@parcel\core\lib\requests\BundleGraphRequest.js:286:5)
      at async RequestTracker.runRequest (C:\test\node_modules\@parcel\core\lib\RequestTracker.js:725:20)
      at async Object.run (C:\test\node_modules\@parcel\core\lib\requests\ParcelBuildRequest.js:62:7)
      at async RequestTracker.runRequest (C:\test\node_modules\@parcel\core\lib\RequestTracker.js:725:20)
      at async Parcel._build (C:\test\node_modules\@parcel\core\lib\Parcel.js:397:11)
      at async Parcel.run (C:\test\node_modules\@parcel\core\lib\Parcel.js:276:18)
      at async run (C:\test\node_modules\parcel\lib\cli.js:376:7)

error Command failed with exit code 1.
```

The `bundleNames` in `BundleGraphRequest.js:343:23` contains:

```
dist/index.html
dist/index.HASH_REF_dafe515b7580f5b6.js
dist/index.HASH_REF_1144a10e07e6a5bb.html
dist/index.html
dist/index.HASH_REF_19de14e872ce7079.js
```

It seems the relative link to the HTML file is the culprit. I think it's important to note that similar relative links to *other* file types (e.g. images) do not (!) cause an error.

## 💁 Possible Solution

This issue appears to be an error in the circular dependency detection in the bundle graph. A dirty workaround is to comment out the `assert()` in `./node_modules/@parcel/core/lib/requests/BundleGraphRequest.js` on line 343:

```js
    //assert().default.deepEqual(bundleNames, (0, _utils().unique)(bundleNames), 'Bundles must have unique names');
```

This lets the build process finish. Some assets will be compiled compiled twice, but the overall result appears to be unchanged.

```
> yarn parcel build index.html
yarn run v1.22.10
warning package.json: No license field
$ C:\test\node_modules\.bin\parcel build index.html
√ Built in 1.37s

dist\index.html    130 B    1.97s
dist\index.html    130 B    1.97s
Done in 2.54s.
```

## 🔦 Context

The example above is simplified to outline the issue. Overall this is for a website that uses HTML components in a client-side JS framework. HTML for these components is stored in a sub-folder.

## 💻 Code Sample

All necessary code is shown above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.0
| Node             | 16.15.1 64 bit
| Yarn         | 1.22.10
| Operating System | Windows 10 21H2, 19044.1645

**Comment by Tomalak** [comment]
Guys, are you sure that it's a good thing to auto-close an issue that comes with full analysis and reproduction code *and* still exists, just because nobody from the team has looked at it? 

It's not that I have not responded to a clarification request for too long, or delivered not enough data to act on.
