### ISSUE TITLE
SASS transformer wrongly marks statement as using an undefined variable

### ISSUE THREAD

**Issue by Jacob-Lockwood** [parcel-bundler/parcel#8232]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`:
```js
{
  "name": "my-app",
  "source": "src/index.pug",
  "scripts": {
    "start": "parcel",
    "build": "parcel build"
  },
  "devDependencies": {
    "@parcel/transformer-pug": "^2.6.1",
    "@parcel/transformer-sass": "^2.6.1",
    "parcel": "^2.6.1"
  }
}
```

## 🤔 Expected Behavior

The following piece of SASS code:
```sass
=spike-clip-path($width: 5, $height: 15)
  $path: null
  $curr: 0
  @for $i from 1 through calc(50 / $width)
    $path: $path, $curr + $i * $width * 1% 0%, $i * 10% $height * 1%
    $curr: $curr + $width
  // this is marked as using an undefined variable:
  clip-path: polygon($path, 100% 100%, 0% 100%)
```
Should not fail (It works in [this playground](https://www.sassmeister.com/))

## 😯 Current Behavior

The code fails with this error:
```
Server running at http://localhost:1234
🚨 Build failed.

@parcel/transformer-sass: Undefined variable.
   ╷
66 │   clip-path: polygon($path, 100% 100%, 0% 100%)
   │                      ^^^^^
   ╵
  src/style.sass 66:22  root stylesheet

  Error: Undefined variable.
     ╷
  66 │   clip-path: polygon($path, 100% 100%, 0% 100%)
     │                      ^^^^^
     ╵
    src/style.sass 66:22  root stylesheet
      at Object.wrapException (/path/to/project/node_modules/sass/sass.dart.js:1234:17)
      at /path/to/project/node_modules/sass/sass.dart.js:70383:23
      at _wrapJsFunctionForAsync_closure.$protected 
  (/path/to/project/node_modules/sass/sass.dart.js:3726:15)
      at _wrapJsFunctionForAsync_closure.call$2 
  (/path/to/project/node_modules/sass/sass.dart.js:27983:12)
      at Object._asyncStartSync (/path/to/project/node_modules/sass/sass.dart.js:3690:20)
      at _EvaluateVisitor2.visitVariableExpression$body$_EvaluateVisitor0 
  (/path/to/project/node_modules/sass/sass.dart.js:70389:16)
      at _EvaluateVisitor2.visitVariableExpression$1 
  (/path/to/project/node_modules/sass/sass.dart.js:70363:19)
      at VariableExpression0.accept$1$1 (/path/to/project/node_modules/sass/sass.dart.js:97380:22)
      at VariableExpression0.accept$1 (/path/to/project/node_modules/sass/sass.dart.js:97383:19)
      at /path/to/project/node_modules/sass/sass.dart.js:72110:47
```

## 🔦 Context

I am trying to use this mixin to avoid inlining some very long clip paths but this is preventing me from using it in my project.

## 💻 Code Sample

Sample files:

`src/index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <link href="./style.sass" rel="stylesheet" />
  </head>
  <body>
    <p>hello</p>
  </body>
</html>
```
`src/style.sass`
```sass
=spike-clip-path($width: 5, $height: 15)
  $path: null
  $curr: 0
  @for $i from 1 through calc(50 / $width)
    $path: $path, $curr + $i * $width * 1% 0%, $i * 10% $height * 1%
    $curr: $curr + $width
  clip-path: polygon($path, 100% 100%, 0% 100%)

p
  color: blue
  +spike-clip-path
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.1
| Node             | v17.2.0
| npm/Yarn         | NPM 8.1.4
| Operating System | macOS Big Sur 11.3.1

**Comment by mischnic** [comment]
I've put these two files in a new directory, ran `npm i -D parcel` and then `npx parcel build index.html` and it worked correctly. What version of sass is installed in your project?
```
$ npm ls sass
8232-sass-for@ ...
└─┬ @parcel/transformer-sass@2.6.1
  └── sass@1.52.3
```

**Comment by Jacob-Lockwood** [comment]
Omg, I was accidentally referencing the variable somewhere else and the code was messed up 🤦‍♂️ Sorry for the inconvenience!
