### ISSUE TITLE
yarn build native -- fails on m1 mac

### ISSUE THREAD

**Issue by ultrasaurus** [parcel-bundler/parcel#8251]
# 🐛 bug report

I was going to try to build parcel and see if I could contribute a bug fix, but wasn't able to build.  Perhaps there's an issue building on m1 macs?

## 🎛 Configuration / Repro steps

```
uname -a
Darwin Airtemis.attlocal.net 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 x86_64 i386 MacBookAir10,1 Darwin
```

steps to reproduce:
```
git clone git@github.com:parcel-bundler/parcel.git
cd parcel
yarn install
yarn build native
```

## 🤔 Expected Behavior

expected to build without error

## 😯 Current Behavior

I see the following errors:

```
$ yarn build native
yarn run v1.22.17
$ yarn build-bundles && cross-env NODE_ENV=production PARCEL_BUILD_ENV=production gulp native
$ rm -rf packages/*/*/lib && cross-env NODE_ENV=production PARCEL_BUILD_ENV=production PARCEL_SELF_BUILD=true parcel build packages/core/{fs,codeframe,package-manager,utils} packages/reporters/{cli,dev-server}
node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module './parcel-hash.darwin-x64.node'
Require stack:
- /src/parcel-bundler/parcel/packages/utils/hash/index.js
- /src/parcel-bundler/parcel/packages/core/utils/src/hash.js
- /src/parcel-bundler/parcel/packages/core/utils/src/index.js
- /src/parcel-bundler/parcel/packages/core/graph/src/AdjacencyList.js
- /src/parcel-bundler/parcel/packages/core/graph/src/Graph.js
- /src/parcel-bundler/parcel/packages/core/graph/src/index.js
- /src/parcel-bundler/parcel/packages/core/core/src/utils.js
- /src/parcel-bundler/parcel/packages/core/core/src/public/Environment.js
- /src/parcel-bundler/parcel/packages/core/core/src/public/Asset.js
- /src/parcel-bundler/parcel/packages/core/core/src/Parcel.js
- /src/parcel-bundler/parcel/packages/core/core/src/index.js
- /src/parcel-bundler/parcel/packages/core/parcel/src/cli.js
- /src/parcel-bundler/parcel/packages/core/parcel/src/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Function.Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/src/parcel-bundler/parcel/packages/utils/hash/index.js:17:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (/src/parcel-bundler/parcel/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .js] (/src/parcel-bundler/parcel/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/src/parcel-bundler/parcel/packages/utils/hash/index.js',
    '/src/parcel-bundler/parcel/packages/core/utils/src/hash.js',
    '/src/parcel-bundler/parcel/packages/core/utils/src/index.js',
    '/src/parcel-bundler/parcel/packages/core/graph/src/AdjacencyList.js',
    '/src/parcel-bundler/parcel/packages/core/graph/src/Graph.js',
    '/src/parcel-bundler/parcel/packages/core/graph/src/index.js',
    '/src/parcel-bundler/parcel/packages/core/core/src/utils.js',
    '/src/parcel-bundler/parcel/packages/core/core/src/public/Environment.js',
    '/src/parcel-bundler/parcel/packages/core/core/src/public/Asset.js',
    '/src/parcel-bundler/parcel/packages/core/core/src/Parcel.js',
    '/src/parcel-bundler/parcel/packages/core/core/src/index.js',
    '/src/parcel-bundler/parcel/packages/core/parcel/src/cli.js',
    '/src/parcel-bundler/parcel/packages/core/parcel/src/bin.js'
  ]
}

Node.js v18.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ultrasaurus** [comment]
FYI: tested with Node v18.4, as expected, no change

**Comment by mischnic** [comment]
You need to run `yarn build-native`, with a hypen. That's also how it's shown in https://github.com/parcel-bundler/parcel/blob/v2/CONTRIBUTING.md#getting-started-with-bug-fixing. Looks like you forgot that?

**Comment by ultrasaurus** [comment]
oops -- was following the guide visually, should have triple checked. Thank you!  

![image](https://user-images.githubusercontent.com/41906/175649453-d278f752-f762-470e-a82f-556fd12ab460.png)
