### ISSUE TITLE
HMR doesnt work on simplest example and throws error

### ISSUE THREAD

**Issue by psnet** [parcel-bundler/parcel#8348]
# 🐛 bug report

When changing one symbol in html's `title` tag text server fails with error.

Code:

package.json:
```json
{
  "name": "hmr-test",
  "scripts": {
    "start": "parcel src/index.html"
  },
  "dependencies": {
    "parcel": "^2.6.2"
  }
}
```

src/index.html
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Test 1</title>
    </head>
    <body>
        Hello
    </body>
</html>
```

## 🤔 Expected Behavior

When change title text from `Test 1` to `Test 2` it will show changes

## 😯 Current Behavior

server and page fails with error:

```
- Building index.html...
@parcel/compressor-raw: Cannot read property 'on' of undefined


TypeError: Cannot read property 'on' of undefined
    at ...\node_modules\@parcel\utils\lib\index.js:35069:16
    at new Promise (<anonymous>)
Server running at http://localhost:1234
? Build failed.

@parcel/compressor-raw: Cannot read property 'on' of undefined

  TypeError: Cannot read property 'on' of undefined
      at ...\node_modules\@parcel\utils\lib\index.js:35069:16
      at new Promise (<anonymous>)
  (...\node_modules\@parcel\utils\lib\index.js:35068:12)
      at move (...\node_modules\@parcel\fs\lib\index.js:1008:59)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             | v16.6.1

**Comment by mischnic** [comment]
Works fine for me with 2.8.3
