### ISSUE TITLE
Parcel Build Module Not Found

### ISSUE THREAD

**Issue by tylim88** [parcel-bundler/parcel#8441]
# 🐛 bug report

```
- C:\Users\limte\OneDrive\Desktop\FireSageJS\node_modules\@parcel\core\lib\public\Environment.js
- C:\Users\limte\OneDrive\Desktop\FireSageJS\node_modules\@parcel\core\lib\public\Asset.js
- C:\Users\limte\OneDrive\Desktop\FireSageJS\node_modules\@parcel\core\lib\Parcel.js
- C:\Users\limte\OneDrive\Desktop\FireSageJS\node_modules\@parcel\core\lib\index.js
- C:\Users\limte\OneDrive\Desktop\FireSageJS\node_modules\parcel\lib\cli.js
- C:\Users\limte\OneDrive\Desktop\FireSageJS\node_modules\parcel\lib\bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\limte\OneDrive\Desktop\FireSageJS\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\limte\OneDrive\Desktop\FireSageJS\node_modules\@parcel\source-map\parcel_sourcemap_node\index.js:15:18)
    at Module._compile (C:\Users\limte\OneDrive\Desktop\FireSageJS\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\@parcel\\source-map\\parcel_sourcemap_node\\index.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\@parcel\\source-map\\dist\\node.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\@parcel\\utils\\lib\\index.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\@parcel\\core\\lib\\public\\Config.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\@parcel\\core\\lib\\utils.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\@parcel\\core\\lib\\public\\Environment.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\@parcel\\core\\lib\\public\\Asset.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\@parcel\\core\\lib\\Parcel.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\@parcel\\core\\lib\\index.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\parcel\\lib\\cli.js',
    'C:\\Users\\limte\\OneDrive\\Desktop\\FireSageJS\\node_modules\\parcel\\lib\\bin.js'
  ]
```

## 🎛 Configuration (.babelrc, package.json, cli command)

command: `parcel build`
package.json config
```js
{
	"targets": {
		"types": false,
		"main": {
			"optimize": true
		}
	},
}
```

## 🤔 Expected Behavior

should compile

## 😯 Current Behavior

error

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 16.16.0
| npm/Yarn         | 8.0.0
| Operating System | window 11
| VS Code |1.71.0

**Comment by tylim88** [comment]
I have tried this solution but is not working

![image](https://user-images.githubusercontent.com/5227509/188344705-492cbeb5-7a90-417e-af56-b13adf7cf1bd.png)

**Comment by mischnic** [comment]
That file is correctly published: https://unpkg.com/browse/@parcel/core@2.7.0/lib/public/Environment.js
So try deleting node_modules and rerunning npm

**Comment by tylim88** [comment]
still having the same issue after reinstallation

![image](https://user-images.githubusercontent.com/5227509/188457550-2c809c22-f51b-44dd-9556-67118365711d.png)
Environment.js exist

**Comment by mischnic** [comment]
Please post the full error, there's more in that terminal window if you scroll up. It's something about the native sourcemap module

**Comment by tylim88** [comment]
![image](https://user-images.githubusercontent.com/5227509/188500277-5c47d8ad-e66e-481e-a774-db19820a2b5a.png)

`npm run parcel` is `parcel build`

**Comment by mischnic** [comment]
Does this help? https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755

**Comment by tylim88** [comment]
I don't need this anymore, but thx for the help
