### ISSUE TITLE
Restrict typescript version to <4 in @parcel/transformer-typescript-types

### ISSUE THREAD

**Issue by joshocalico** [parcel-bundler/parcel#8494]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  // stock standard library config with the exclusion of types 
  "types": "dist/types/lib.d.ts"
  "devDependencies": { 
    ... 
    "parcel": "latest",
    "typescript": "^4.6.4", 
    ...
  }
}
```

## 🤔 Expected Behavior

It should build correctly with correct generated types.

## 😯 Current Behavior

The build fails completely.

```
> parcel build


console: DeprecationWarning: 'updateBundle' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation 
context instead.

console: DeprecationWarning: 'getMutableClone' has been deprecated since v4.0.0. Use an appropriate `factory.update...` method instead, use `setCommentRange` or 
`setSourceMapRange`, and avoid setting `parent`.

console: DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation 
context instead.

console: DeprecationWarning: 'updateQualifiedName' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your 
transformation context instead.

console: DeprecationWarning: 'createModifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation 
context instead.

console: DeprecationWarning: 'createImportSpecifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your 
transformation context instead.

console: DeprecationWarning: 'createNamedImports' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your 
transformation context instead.

console: DeprecationWarning: 'createImportClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your 
transformation context instead.

console: DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, 
🚨 Build failed.

@parcel/transformer-typescript-types: Invalid arguments

  TypeError: Invalid arguments
      at Object.updateExportDeclaration (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/typescript/lib/typescript.js:170487:19)
      at Object.updateExportDeclaration (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/typescript/lib/typescript.js:171319:27)
      at Object.updateExportDeclaration (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/typescript/lib/typescript.js:3324:29)
      at visit (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/@parcel/transformer-typescript-types/lib/shake.js:113:42)
      at visitArrayWorker (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/typescript/lib/typescript.js:90658:48)
      at visitNodes (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/typescript/lib/typescript.js:90621:23)
      at Object.visitEachChild (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/typescript/lib/typescript.js:91131:56)
      at visit (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/@parcel/transformer-typescript-types/lib/shake.js:220:34)
      at visitNode (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/typescript/lib/typescript.js:90569:23)
      at Object.visitEachChild (/Users/joshuasteele/fluidity/fluidity-app/web/surfing/node_modules/typescript/lib/typescript.js:91128:166)
```

## 💁 Possible Solution

Restrict typescript dependency to less than version 4 as the API has changed.

## 🔦 Context

I was unable to build our project with parcel.

## 💻 Code Sample

I believe any project with types in the package.json, TS to transform and typescript v4 will be able to reproduce this issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.7.0
| Node             |16.17.0
| npm/Yarn         |npm 8.15.0
| Operating System |macOS Ventura (ARM)

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/pull/8443 and https://github.com/parcel-bundler/parcel/issues/8419

Though the error messages here are different

**Comment by mischnic** [comment]
Also, can someone please provide a reproduction?

**Comment by mischnic** [comment]
And/or: try it with the next nightly (which will include https://github.com/parcel-bundler/parcel/pull/8661) to see if it's working now.
