### ISSUE TITLE
parcel dev server hung, not CTRL-C'able (possibly due to `BuildAbortError`s?)

### ISSUE THREAD

**Issue by broofa** [parcel-bundler/parcel#8509]
# 🐛 bug report

While running the dev server (i.e. actively making code changes), the parcel process has stopped responding, even so far as to not be CTRL-C'able.  (`kill -9`'ing it worked, though.)

Here's what I'm seeing in the shell I launch parcel from:
```bash
Server running at http://localhost:1234
⠇ Optimizing index.html...
BuildAbortError
    at assertSignalNotAborted (/Users/kieffer/projects/flightcard/node_modules/@parcel/core/lib/utils.js:85:11)
    at RequestTracker.runRequest (/Users/kieffer/projects/flightcard/node_modules/@parcel/core/lib/RequestTracker.js:732:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

{{{ Nine more identical "BuildAbortError" exceptions removed for brevity }}}

```

FWIW, I've had the dev server running for ~10 hours, and have closed my laptop ("sleep" mode) a couple times during this time.

## 🤔 Expected Behavior

Regardless of what caused the build errors, CTRL-C'ing the process should always be possible.

## 🎛 Configuration (.babelrc, package.json, cli command)

No babelrc file.

I have this in .parcelrc:
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.png": [
      "@parcel/transformer-raw"
    ]
  }
}
```

I start the dev server by running `parcel index.html`

## 🌍 Your Environment

```
  System:
    OS: macOS 12.5.1
    CPU: (10) x64 Apple M1 Max
    Memory: 543.91 MB / 64.00 GB
    Shell: 5.1.8 - /usr/local/bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 103.0.1
    Safari: 15.6.1
  npmPackages:
    @babel/core: ^7.18.13 => 7.18.13
    @cloudflare/workers-types: 3.15.0 => 3.15.0
    @parcel/babel-plugin-transform-runtime: ^2.7.0 => 2.7.0
    @parcel/packager-raw-url: ^2.7.0 => 2.7.0
    @parcel/transformer-image: ^2.7.0 => 2.7.0
    @parcel/transformer-sass: ^2.7.0 => 2.7.0
    @parcel/transformer-webmanifest: ^2.7.0 => 2.7.0
    @popperjs/core: ^2.11.6 => 2.11.6
    @types/react: ^18.0.17 => 18.0.17
    @types/react-dom: ^18.0.6 => 18.0.6
    @types/react-router-dom: ^5.3.3 => 5.3.3
    @typescript-eslint/eslint-plugin: ^5.35.1 => 5.35.1
    @typescript-eslint/parser: ^5.35.1 => 5.35.1
    blueimp-md5: ^2.19.0 => 2.19.0
    bootstrap: ^5.2.0 => 5.2.0
    checkcss: ^1.3.1 => 1.3.1
    eslint: ^8.22.0 => 8.22.0
    eslint-plugin-react: ^7.31.0 => 7.31.0
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0
    firebase: ^9.9.3 => 9.9.3
    firebaseui: ^6.0.1 => 6.0.1
    nanoid: ^4.0.0 => 4.0.0
    parcel: ^2.7.0 => 2.7.0
    process: ^0.11.10 => 0.11.10
    react: ^18.2.0 => 18.2.0
    react-bootstrap: ^2.5.0 => 2.5.0
    react-dom: ^18.2.0 => 18.2.0
    react-router-bootstrap: ^0.26.2 => 0.26.2
    react-router-dom: ^6.3.0 => 6.3.0
    sass: ^1.54.5 => 1.54.5
    simplur: ^3.0.1 => 3.0.1
    thrustcurve-db: ^3.0.1 => 3.0.1
    typescript: ^4.7.4 => 4.7.4
    victory: ^36.6.5 => 36.6.5
```

**Comment by mischnic** [comment]
The custom CTRL-C handling is here: https://github.com/parcel-bundler/parcel/blob/e3a39a1f3642d28f8fd25919cda698ad34502cee/packages/core/parcel/src/cli.js#L275-L299

**Comment by mischnic** [comment]
I've never seen this myself though. Is this still an issue?

**Comment by broofa** [comment]
Have not seen this recently.  Closing.
