### ISSUE TITLE
Parcel fails to build with AntD

### ISSUE THREAD

**Issue by estormfield** [parcel-bundler/parcel#8521]
After upgrading from a 2.0 beta, parcel is not building correctly with antd.
When using --no-scope-hoist, parcel builds but fails in browser with any usage of antd.
Removing --no-scope-hoist, Parcel build produces variations of the "does not have node" error.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": false
      },
      "macros"
    ]
  ]
}
```

## 🤔 Expected Behavior

Parcel should build and run without error.

## 😯 Current Behavior

parcel build 
```
⠇ Building FolderTwoTone.js...
Error: Does not have node 12886
    at AssetGraph._assertHasNodeId (/Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/graph/lib/Graph.js:403:13)
    at AssetGraph.getNodeIdsConnectedFrom (/Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/graph/lib/Graph.js:113:10)
    at visitChildren (/Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:162:47)
    at /Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:157:67
Error: Does not have node 16555
    at AssetGraph._assertHasNodeId (/Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/graph/lib/Graph.js:403:13)
    at AssetGraph.getNodeIdsConnectedFrom (/Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/graph/lib/Graph.js:113:10)
    at visitChildren (/Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:162:47)
    at /Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:157:67
Error: Does not have node 18805
    at AssetGraph._assertHasNodeId (/Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/graph/lib/Graph.js:403:13)
    at AssetGraph.getNodeIdsConnectedFrom (/Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/graph/lib/Graph.js:113:10)
    at visitChildren (/Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:162:47)
    at /Users/ericstormfield/repos/slfus-client-onboard/node_modules/@parcel/cor
```

## 🔦 Context

This appears related to this error: https://github.com/parcel-bundler/parcel/issues/5985

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.7
| Node             | v14.18
| npm/Yarn         | v6.14
| antd | v 4.23

**Comment by mischnic** [comment]
Please provide a complete code sample.
