### ISSUE TITLE
BuildAbortError when making changes while watch mode is building

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#8548]
# 🐛 bug report

When making too many changes too quickly while a build is already running in watch mode, an error occurs:

```
✨ Built in 452ms
Building...
Bundling...
Packaging & Optimizing...
Building...
Bundling...
Building...
Bundling...
Packaging & Optimizing...
BuildAbortError:
    at assertSignalNotAborted (parcel/parcel-react-native/packages/core/core/src/utils.js:43:11)
    at RequestTracker.runRequest (parcel/parcel-react-native/packages/core/core/src/RequestTracker.js:990:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runDevDepRequest (parcel/parcel-react-native/packages/core/core/src/requests/DevDepRequest.js:170:3)
    at runCompressor (parcel/parcel-react-native/packages/core/core/src/requests/WriteBundleRequest.js:284:5)
    at async Promise.all (index 0)
    at writeFiles (parcel/parcel-react-native/packages/core/core/src/requests/WriteBundleRequest.js:233:3)
    at Object.run (parcel/parcel-react-native/packages/core/core/src/requests/WriteBundleRequest.js:150:3)
    at RequestTracker.runRequest (parcel/parcel-react-native/packages/core/core/src/RequestTracker.js:982:20)```
```

## 🤔 Expected Behavior

Correctly stops the old builds?

## 😯 Current Behavior

See error

## Reproduction

- Set VSCode "Auto Save" to "afterDelay"
- Set "Auto Save Delay" to "1ms"
- type

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 4ebb9675daf0b473675c5dbc1f92907cfb69b4c4
| Node             | 16.18.0
| Operating System | macOS

**Comment by obrassard** [comment]
Hello, I found this GH issue on Google, I was experiencing the same problem after upgrading to parcel v2.7 !
 Are you planning a release on NPM soon that would include the fix?

Thanks in advance !

EDIT : Downgraded my project to parcel v2.6, and the issue persist. Therefore the bug might have been there before v2.7
