### ISSUE TITLE
"RangeError: Invalid count value" when building, but running works

### ISSUE THREAD

**Issue by Faerleon** [parcel-bundler/parcel#8574]
# 🐛 bug report
When building my project using parcel build, it fails with an untracable error while starting the project via `parcel src/index.tsx` works perfectly fine.

### babel.config.js
```js
module.exports = {
  presets: [
    ["@babel/preset-env", { targets: { node: "current" } }],
    ["@babel/preset-react", { runtime: "automatic" }],
    "@babel/preset-typescript"
  ]
};
```

### package.json
```json
{
  "name": "seedit-frontend",
  "version": "3.5.1",
  "author": {
    "name": "webnature solutions GmbH",
    "email": "info@webnature.io",
    "url": "https://webnature.io/"
  },
  "repository": {
    "type": "git",
    "url": "https://git.rle.de/ykasper/arbeitsplatz_frontend/"
  },
  "bugs": "https://git.rle.de/ykasper/arbeitsplatz_frontend/-/issues/",
  "homepage": "https://rle.de/",
  "private": true,
  "scripts": {...},
  "dependencies": {
    "@date-io/moment": "^1.3.13",
    "@lottiefiles/lottie-player": "^1.5.7",
    "@material-ui/core": "^4.12.4",
    "@material-ui/icons": "^4.11.3",
    "@material-ui/lab": "^4.0.0-alpha.61",
    "@material-ui/pickers": "^3.3.10",
    "@material-ui/types": "^5.1.0",
    "@mobiscroll/react": "^5.16.1",
    "@nivo/bar": "^0.69.0",
    "@nivo/core": "^0.69.0",
    "@nivo/line": "^0.69.0",
    "@react-keycloak/web": "^3.4.0",
    "@reduxjs/toolkit": "^1.8.6",
    "@types/supercluster": "^7.1.0",
    "@workplace-booking/facility-manager": "file:../facility-manager/workplace-booking-facility-manager-0.0.0.tgz",
    "@workplace-booking/weplace-api-client": "^1.2.1",
    "autosuggest-highlight": "^3.3.4",
    "axios": "^1.1.3",
    "body-scroll-lock": "^4.0.0-beta.0",
    "env-cmd": "^10.1.0",
    "formik": "^2.2.9",
    "google-map-react": "^2.2.0",
    "i18next": "^22.0.0",
    "i18next-browser-languagedetector": "^6.1.8",
    "i18next-parser": "^6.6.0",
    "jest-webgl-canvas-mock": "^0.2.3",
    "json-loader": "^0.5.7",
    "keycloak-js": "^19.0.3",
    "lodash": "^4.17.21",
    "material-table": "^1.69.3",
    "material-ui-dropzone": "^3.5.0",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.38",
    "myzod": "^1.8.8",
    "nivo": "^0.31.0",
    "notistack": "^1.0.2",
    "postcss": "^8.4.18",
    "prettier": "^2.7.1",
    "react": "^18.2.0",
    "react-color": "^2.19.3",
    "react-data-export": "^0.6.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^11.18.6",
    "react-number-format": "^5.0.1",
    "react-qrcode-logo": "^2.8.0",
    "react-query": "^3.39.2",
    "react-redux": "^8.0.4",
    "react-rotating-text": "^1.4.1",
    "react-router-dom": "^6.4.2",
    "react-script-hook": "^1.7.2",
    "react-spring": "^9.5.5",
    "react-to-print": "^2.14.7",
    "react-virtualized": "^9.22.3",
    "reactour": "^1.18.7",
    "recharts": "^2.1.15",
    "sass": "^1.55.0",
    "socket.io-client": "^4.5.3",
    "supercluster": "^7.1.5",
    "timeframes": "^1.1.2",
    "timekeeper": "^2.2.0",
    "userpilot": "^1.2.8",
    "uuid": "^9.0.0",
    "xlsx": "^0.18.5",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.19.6",
    "@babel/preset-env": "^7.19.4",
    "@babel/preset-react": "^7.18.6",
    "@babel/preset-typescript": "^7.18.6",
    "@commitlint/cli": "^17.1.2",
    "@commitlint/config-conventional": "^17.1.0",
    "@faker-js/faker": "^7.6.0",
    "@iconify/json": "^2.1.124",
    "@iconify/json-tools": "^1.0.10",
    "@iconify/react": "^4.0.0",
    "@iconify/react-with-api": "^1.0.0-rc.7",
    "@parcel/packager-raw-url": "^2.7.0",
    "@parcel/transformer-sass": "^2.7.0",
    "@parcel/transformer-svg-react": "^2.7.0",
    "@parcel/transformer-webmanifest": "^2.7.0",
    "@storybook/addon-actions": "^6.5.12",
    "@storybook/addon-essentials": "^6.5.12",
    "@storybook/addon-interactions": "^6.5.12",
    "@storybook/addon-links": "^6.5.12",
    "@storybook/builder-webpack5": "^6.5.12",
    "@storybook/manager-webpack5": "^6.5.12",
    "@storybook/node-logger": "^6.5.12",
    "@storybook/preset-create-react-app": "^4.1.2",
    "@storybook/react": "^6.5.12",
    "@storybook/testing-library": "^0.0.13",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/react-hooks": "^8.0.0",
    "@testing-library/user-event": "^12.8.3",
    "@types/autosuggest-highlight": "^3.2.0",
    "@types/body-scroll-lock": "^3.1.0",
    "@types/google-map-react": "^2.1.7",
    "@types/google.maps": "^3.50.4",
    "@types/jest": "^29.2.0",
    "@types/lodash": "^4.14.186",
    "@types/moment-timezone": "^0.5.13",
    "@types/node": "^18.11.2",
    "@types/react": "^18.0.21",
    "@types/react-color": "^3.0.6",
    "@types/react-dom": "^18.0.6",
    "@types/react-router-dom": "^5.3.3",
    "@types/react-test-renderer": "^18.0.0",
    "@types/react-virtualized": "^9.21.21",
    "@types/reactour": "^1.18.2",
    "@types/recharts": "^1.8.23",
    "@types/uuid": "^8.3.4",
    "@types/webpack": "^5.28.0",
    "@typescript-eslint/eslint-plugin": "^5.40.1",
    "@typescript-eslint/parser": "^5.40.1",
    "babel-jest": "^29.2.1",
    "cross-env": "^7.0.3",
    "eslint": "^8.25.0",
    "eslint-plugin-react": "^7.31.10",
    "eslint-plugin-react-hooks": "^4.6.0",
    "form-data": "^4.0.0",
    "husky": "^8.0.1",
    "jest": "29.2.1",
    "jest-localstorage-mock": "^2.4.22",
    "jest-mock-axios": "^4.6.1",
    "jest-spy-object": "^1.4.0",
    "jest-transform-stub": "^2.0.0",
    "mockdate": "^3.0.5",
    "parcel": "^2.7.0",
    "react-test-renderer": "^18.2.0",
    "typedoc": "^0.23.17",
    "typescript": "4.8.4"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ]
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "jest": {
    "resetMocks": false,
    "moduleNameMapper": {
      "react-i18next": "<rootDir>/src/__mocks__/react-i18next.js"
    },
    "coverageReporters": [
      "text-summary",
      "lcov",
      "cobertura"
    ],
    "coveragePathIgnorePatterns": [
      "<rootDir>/src/setupTests.js"
    ],
    "testEnvironment": "jsdom",
    "setupFiles": [
      "<rootDir>/src/setupTests.js"
    ],
    "transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "babel-jest",
      ".+\\.(css|styl|less|sass|scss|png|jpg|jpeg|ttf|woff|woff2|svg)$": "jest-transform-stub"
    }
  },
  "eslintConfig": {
    "overrides": [
      {
        "files": [
          "**/*.stories.*"
        ],
        "rules": {
          "import/no-anonymous-default-export": "off"
        }
      }
    ]
  }
}
```

### Command 
`parcel build src/index.html`

## 🤔 Expected Behavior
The project builds fine

## 😯 Current Behavior
The build stops after a short time, throwing
```bash
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at $796233c1fee0ccb8$export$2e2bcd8739ae039 (/Users/ictaoxheth/Documents/GitHub/arbeitsplatz_frontend/node_modules/@parcel/codeframe/lib/codeframe.js:36000:54)
    at $f02d6a9d30f55938$export$2e2bcd8739ae039 (/Users/ictaoxheth/Documents/GitHub/arbeitsplatz_frontend/node_modules/@parcel/utils/lib/index.js:32344:101)
    at async $7c213f7c22b64117$var$writeDiagnostic (/Users/ictaoxheth/Documents/GitHub/arbeitsplatz_frontend/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:7435:121)
    at async $7c213f7c22b64117$export$12358408d9820617 (/Users/ictaoxheth/Documents/GitHub/arbeitsplatz_frontend/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:7401:13)
    at async ReporterRunner.report (/Users/ictaoxheth/Documents/GitHub/arbeitsplatz_frontend/node_modules/@parcel/core/lib/ReporterRunner.js:105:11)
    at async Parcel._build (/Users/ictaoxheth/Documents/GitHub/arbeitsplatz_frontend/node_modules/@parcel/core/lib/Parcel.js:466:7)
    at async Parcel.run (/Users/ictaoxheth/Documents/GitHub/arbeitsplatz_frontend/node_modules/@parcel/core/lib/Parcel.js:276:18)
    at async run (/Users/ictaoxheth/Documents/GitHub/arbeitsplatz_frontend/node_modules/parcel/lib/cli.js:376:7)
```

### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "downlevelIteration": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noFallthroughCasesInSwitch": false,
    "jsx": "react-jsx"
  },
  "include": ["src"],
  "exclude": ["node_modules", "**/*.spec.ts", "**/*.tsx", "**/*.stories.tsx"]
}

```

## 💁 Possible Solution
Since the error is hard to trace, I cannot really offer a possible solution.

## 🔦 Context
The project built fine before and stopped working when I fixed my tests. 
I included some images using the "require" syntax in the code. 
Building with "tsc" also works fine. I removed the cache/ and dist/ folders and reinstalled my packages too.

Also, I started with parcel-bundler and it worked. It only breaks after migrating to parcel 2!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.7.0
| Node             | 16
| npm/Yarn         | v18.16.0
| Operating System | MacOS

**Comment by Faerleon** [comment]
I tried downgrading to parcel-bundler tonight and it builds. Strange thing is, when I try to launch the builded artefact, it only shows a blank screen and this:
![image](https://user-images.githubusercontent.com/12459210/197717213-347d7b5b-59c4-426f-a2c1-366751d477bd.png)

Strangely, when I THEN start the development mode with `parcel src/index.tsx`, quit that and start the builded artefact again, it works, so the dev-server writes something into the dist folder the builder does not correctly.

**Comment by mischnic** [comment]
Any chance you can share a reproduction? Looks like it's related to `require`ing images, so it probably still throws that build error when you remove all most of the other application code.
