### ISSUE TITLE
Parcel is not imported React through Electron BrowserWindow on target context `electron-renderer`

### ISSUE THREAD

**Issue by PlayerNguyen** [parcel-bundler/parcel#8605]
# 🐛 bug report
When running the Electron and React app application built by using the **Parcel API** script. The Electron app was not found `react/jsx-dev-runtime` module and occurred an error `Uncaught Error: Cannot find module 'react/jsx-dev-runtime'` (belongs to React bundler files). 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/10703461/199917111-e4905a75-bae9-4503-bf85-ec926019b7fe.png">

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
"targets": {
    "main": {
      "context": "electron-main",
      "engines": {
        "source": "./src/electron/index.js"
      },
      "distDir": "./dist/main"
    },
    "render": {
      "context": "electron-renderer",
      "engines": {
        "source": "./src/render/index.html"
      },
      "distDir": "./dist/render",
      "publicUrl": "./"
    }
  }
```

## 🤔 Expected Behavior
Print a Hello World on the render view.

## 😯 Current Behavior

It throws an exception. Seems like the React file was not bundled into the output files.

```
Uncaught Error: Cannot find module 'react/jsx-dev-runtime'
    at newRequire (index.c0b546d1.js:61:19)
    at newRequire (index.c0b546d1.js:45:18)
    at localRequire (index.c0b546d1.js:84:35)
    at e7tUG../components/App (index.js:1:1)
    at newRequire (index.c0b546d1.js:71:24)
    at index.c0b546d1.js:122:5
    at index.c0b546d1.js:145:3
```

## 💁 Possible Solution

After changing the context from `electron-render` to `browser` and re-bundle, it is work as expected.
```json
"targets": {
    "main": {
      "context": "electron-main",
      "engines": {
        "source": "./src/electron/index.js"
      },
      "distDir": "./dist/main"
    },
    "render": {
      "context": "browser",
      "engines": {
        "source": "./src/render/index.html"
      },
      "distDir": "./dist/render",
      "publicUrl": "./"
    }
  }
```
<img width="803" alt="Ảnh màn hình 2022-11-04 lúc 14 36 20" src="https://user-images.githubusercontent.com/10703461/199918266-f8f321c5-a4a6-47d2-84fd-89c5821b294b.png">

## 💻 Code Sample

./scripts/start.js
```js
const { Parcel } = require("@parcel/core");
const chalk = require("chalk");

let renderBundler = new Parcel({
  entries: "./src/render/index.html",
  defaultConfig: "@parcel/config-default",
  targets: ["render"],
});
let mainBundler = new Parcel({
  entries: "./src/electron/index.ts",
  defaultConfig: "@parcel/config-default",
  targets: ["main"],
});

async function bundle(parcel, name) {
  try {
    let { bundleGraph, buildTime } = await parcel.run();
    let bundles = bundleGraph.getBundles();

    console.log(
      chalk.bold(
        chalk.green(
          `✨ Completely bundling ${name} module ${chalk.yellow(
            bundles.length
          )} asset(s) in ${chalk.blue(buildTime / 1000)} s`
        )
      )
    );
  } catch (err) {
    console.error(err.diagnostics);
    throw err;
  }
}

(async () => {
  await bundle(renderBundler, "render");
  await bundle(mainBundler, "main");

  // Run electron app (spawn a child_process)
  require("electroner")("./dist/main/index.js", {});
})();
```
package.json
```json
 "scripts": {
    "start": "cross-env NODE_ENV=dev node ./scripts/start.js",
  },
  "devDependencies": {
    "@parcel/config-default": "^2.7.0",
    "@parcel/core": "^2.7.0",
    "chalk": "4.1.2",
    "cross-env": "^7.0.3",
    "electron": "^21.2.2",
    "electroner": "^4.0.9"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "targets": {
    "main": {
      "context": "electron-main",
      "engines": {
        "source": "./src/electron/index.js"
      },
      "distDir": "./dist/main"
    },
    "render": {
      "context": "electron-renderer",
      "engines": {
        "source": "./src/render/index.html"
      },
      "distDir": "./dist/render",
      "publicUrl": "./"
    }
  }
```

./src/electron/index.js
```js
import { BrowserWindow, app } from "electron";
import { resolve } from "path";
const createWindow = () => {
  const window = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {},
  });

  window.loadFile(resolve("dist", "render", "index.html"));

  return window;
};

 app.on("ready", () => {
    createWindow();
  });
```

./src/render/index.js
```jsx
import React, { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./components/App";

const root = createRoot(document.getElementById("app"));
root.render(
  <StrictMode>
    <App />
  </StrictMode>
);


```
**And the default index.html** with `<script src="./index.js" type="module"></script>`
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0|
| Node             | v14.17.6|
| npm/Yarn         | 1.22.11|
| Operating System | macOS Ventura |

**Comment by PlayerNguyen** [comment]
I found that when I remove the whole `./dist` file and then rebuild with `context: browser`. It is also not bundled. The `./dist/render` won't come up

**Comment by ykrasik** [comment]
+1 with parcel `2.8.0`, setting `context: electron-renderer` seems to not bundle any node_module dependencies.
