### ISSUE TITLE
Edge from 2050 to 2051 not found!

### ISSUE THREAD

**Issue by yrral86** [parcel-bundler/parcel#8632]
After upgrading to 2.8.0, I am seeing
```
🚨 Build failed.

@parcel/bundler-default: Edge from 2050 to 2051 not found!

  Error: Edge from 2050 to 2051 not found!
      at ContentGraph.removeEdge (/redacted/node_modules/@parcel/graph/lib/Graph.js:156:13)
      at MutableBundleGraph.createBundleGroup (/redacted/node_modules/@parcel/core/lib/public/MutableBundleGraph.js:134:24)
      at decorateLegacyGraph (/redacted/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:159:35)
      at Object.bundle (/redacted/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:126:7)
      at BundlerRunner.bundle (/redacted/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:288:23)
      at async Object.run (/redacted/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:156:17)
      at async RequestTracker.runRequest (/redacted/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async Object.run (/redacted/node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:56:7)
      at async RequestTracker.runRequest (/redacted/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async Parcel._build (/redacted/node_modules/@parcel/core/lib/Parcel.js:400:11)
```

_Originally posted by @yrral86 in https://github.com/parcel-bundler/parcel/issues/8554#issuecomment-1315777682_
      

Downgrading to 2.7.0 results in a successful build.

**Comment by flavio-b** [comment]
I got the same error after upgrading to 2.8.0.

**Comment by mischnic** [comment]
Can someone please provide a reproduction?

**Comment by yrral86** [comment]
I'm dealing with an app with 100s of thousands of lines that I'm trying to upgrade from parcel 1.  I'm currently chasing [another issue ](https://github.com/parcel-bundler/parcel/issues/7609#issuecomment-1318832749) with version 2.7.0, but later I can try a build with --detailed-report and --log-level verbose to see if that gets me anything helpful.  Do you have any other tips for getting more information to help narrow it down?

**Comment by flavio-b** [comment]
I've just tried updating my project from Parcel 2.7.0 to 2.8.0 again. 

Running `serve` and `build` commands work successfully now. I have no idea what fixed it. Maybe, some deep dependency that got updated in the last couple of days. FYI, project only contains SCSS, CSS, HTML, plain JS and images. Essentially, it's based on this [Bootstrap & Parcel ](https://getbootstrap.com/docs/5.2/getting-started/parcel/)tutorial.

**Comment by yrral86** [comment]
I'm not sure what is different this time (possibly tsconfig?), but I'm now seeing this:

```
console: type: css
console: type: css
🚨 Build failed.

@parcel/namer-default: Bundle group cannot have more than one entry bundle of 
the same type

  AssertionError [ERR_ASSERTION]: Bundle group cannot have more than one entry 
  bundle of the same type
  ```
  
I added some logging to DefaultNamer.js and all I was able to figure out was that the ones with the error are type = css.
  
Rolling back to 2.7.0 resolves the error, but then I'm back to `Could not resolve bundle with id` when registering the service-worker.
