### ISSUE TITLE
Resolve error when using nested Workers + self-referential Worker

### ISSUE THREAD

**Issue by RReverser** [parcel-bundler/parcel#8727]
# 🐛 bug report

I'm getting Parcel runtime error when it tries to resolve some chunk in a built Web Worker. I suspect this is a continuation of my issue from https://github.com/parcel-bundler/parcel/issues/5920, except now I had to add nested Workers (one Worker spawning another) to the mix.

## 🎛 Configuration (.babelrc, package.json, cli command)

```bash
$ parcel build index.html --dist-dir pkg/parcel --public-url .
```

## 🤔 Expected Behavior

No error should occur.

## 😯 Current Behavior

When building wasm-bindgen-rayon tests, I'm getting a resolution error with Parcel at runtime after a successful build. Other bundlers as well as a no-bundler modes work fine:

```
> node run-tests.mjs

Getting available port… done.
Starting server on port 53097… done.
Starting browser… done.
Running tests...
parcel [Error: Error: Could not resolve bundle with id 55I7O
    at Object.o (http://localhost:53097/pkg/parcel/workerHelpers.4e9e3c97.js:1:2076)
    at Object.<anonymous> (http://localhost:53097/pkg/parcel/workerHelpers.4e9e3c97.js:1:681)
    at o (http://localhost:53097/pkg/parcel/workerHelpers.4e9e3c97.js:1:408)
    at http://localhost:53097/pkg/parcel/workerHelpers.4e9e3c97.js:1:3172]
rollup: log: OK
webpack: log: OK
webpack: log: OK
no-bundler: log: OK
Shutting down… done.
```

FWIW this is the stacktrace resolved via sourcemap if I try to open it directly in browser instead of using Puppeteer:

```
Uncaught (in promise) Error: Could not resolve bundle with id 55I7O
    at Object.o (bundle-manifest.js:17:11)
    at Object.<anonymous> (runtime-e9ac9dbd9bb26463.js:1:113)
    at o (workerHelpers.4e9e3c97.js:1:408)
    at workerHelpers.js:64:3
[...repeated N times for number of workers in the threadpool]
```

## 💁 Possible Solution

No idea what's going on there.

## 🔦 Context

This library is used to support Rust multithreading library Rayon on the Web via Wasm + Web Workers.

## 💻 Code Sample

To make it easier to reproduce without dealing with nightly Rust & wasm-pack toolchains, I just committed all the prebuilt assets to a separate branch: https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/tree/with-prebuilt-assets

You can find Parcel assets [here](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/tree/with-prebuilt-assets/test/pkg/parcel) and their sources [here](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/tree/with-prebuilt-assets/test).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2 |
| Node             | 19.1.0 |
| npm/Yarn         | npm 8.9.0 |
| Operating System | Windows 10 x64 |

**Comment by RReverser** [comment]
cc @mischnic @devongovett as the two people who looked at the original mentioned issue

**Comment by RReverser** [comment]
Sounds a bit similar to https://github.com/parcel-bundler/parcel/issues/5504 but that one was resolved long ago.

**Comment by mischnic** [comment]
I cloned that branch, cd'ed into `test`, ran `rm -rf pkg/parcel; npx parcel build index.html --dist-dir pkg/parcel --public-url .`, and then with `serve` going to http://localhost:3000/pkg/parcel/index.html, I get `Failed to fetch at workerHelpers.no-bundler.js:62:30`. And not the error you posted

**Comment by RReverser** [comment]
That's odd. You can see the same error I had locally on the CI too: https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/actions/runs/3807848746/jobs/6477924018#step:3:192

(and I only now noticed that error is not correctly propagated to CI status, I'll fix that separately but that's beside the point anyway)

**Comment by RReverser** [comment]
~~FWIW you need this serve config for COOP/COEP, maybe that's related to your "Failed to fetch" error? (I guess that might be not picked up in case you started `serve` in a different workdir) https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/blob/with-prebuilt-assets/test/serve.json~~

~~No, wait, why would it pick up and try to load `workerHelpers.no-bundler.js` at all? That's not the JS the bundler build uses. Something is clearly off.~~

Ah, I think it's because the last command ran `build:no-bundler` task, which overrode those intermediate files. Sorry about that, let me just disable that task temporarily if you want to rerun parcel build yourself.

**Comment by RReverser** [comment]
Pushed an update to the repro branch, you should now be able to do `npm run build:parcel` to rebuild Parcel from intermediate files at-will.

**Comment by RReverser** [comment]
Friendly ping - have you had a chance to take another look?

**Comment by RReverser** [comment]
Just ran into this issue again. Generally it will affect ~all Emscripten projects using pthreads and being built by Parcel, as well as wasm-bindgen-rayon projects like in example above.

Any chance someone would look into this? It's been a while.

**Comment by RReverser** [comment]
Pretty sure this is still a issue, although there hasn't been a response after initial submission.
