### ISSUE TITLE
`Edge from X to Y not found!` when using inline Sass and multiple targets

### ISSUE THREAD

**Issue by jay-sus** [parcel-bundler/parcel#8754]
# 🐛 bug report

Error gets thrown when building multiple targets, that include the same sass file which contains an `url()` function. The sass file is included with a link tag in the first target and with an inline import statement in the second target.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "scripts": {
        "build": "parcel build",
        "thisworks": "parcel build --target target1 && parcel build --target target2"
    },
    "targets": {
        "target1": {
            "source": [
                "./src/target1.html"
            ],
            "distDir": "./target1/"
        },
        "target2": {
            "source": [
                "./src/target2.html"
            ],
            "distDir": "./target2/"
        }
    },
    "devDependencies": {
        "@parcel/transformer-sass": "^2.8.2",
        "parcel": "^2.8.2"
    }
}
```

## 🤔 Expected Behavior

Build command should not fail.

## 😯 Current Behavior

```
× Build failed.

@parcel/bundler-default: Edge from 7 to 8 not found!

  Error: Edge from 7 to 8 not found!
      at ContentGraph.removeEdge (D:\parcel-edge-not-found\node_modules\@parcel\graph\lib\Graph.js:156:13)
      at MutableBundleGraph.createBundleGroup
  (D:\parcel-edge-not-found\node_modules\@parcel\core\lib\public\MutableBundleGraph.js:134:24)
      at decorateLegacyGraph
  (D:\parcel-edge-not-found\node_modules\@parcel\bundler-default\lib\DefaultBundler.js:159:35)
      at Object.bundle (D:\parcel-edge-not-found\node_modules\@parcel\bundler-default\lib\DefaultBundler.js:126:7)
      at BundlerRunner.bundle
  (D:\parcel-edge-not-found\node_modules\@parcel\core\lib\requests\BundleGraphRequest.js:288:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.run (D:\parcel-edge-not-found\node_modules\@parcel\core\lib\requests\BundleGraphRequest.js:156:17)
      at async RequestTracker.runRequest
  (D:\parcel-edge-not-found\node_modules\@parcel\core\lib\RequestTracker.js:756:20)
      at async Object.run (D:\parcel-edge-not-found\node_modules\@parcel\core\lib\requests\ParcelBuildRequest.js:56:7)
      at async RequestTracker.runRequest
  (D:\parcel-edge-not-found\node_modules\@parcel\core\lib\RequestTracker.js:756:20)
  ```

## 🔦 Context

Building each target separately works as a temporary solution (`thisworks` script in package.json).

## 💻 Code Sample

Repo [here](https://github.com/jay-sus/parcel-edge-not-found).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2
| Node             | 18.12.1 64bit
| npm/Yarn         | 8.19.2
| Operating System | Win 10

**Comment by devongovett** [comment]
Maybe related to #8716, though the error is different...

cc. @AGawrys

**Comment by Mikescops** [comment]
I'm facing the exact same error with 2 targets:
```
@parcel/bundler-default: Edge from 1185 to 1186 not found!

  Error: Edge from 1185 to 1186 not found!
  
  at ContentGraph.removeEdge (/home/cmors/dev/tools/mrext/node_modules/@parcel/graph/lib/Graph.js:156:13)
```

**Comment by LeoniePhiline** [comment]
Same (two targets, using shared files; two different dist dirs):

```
@parcel/bundler-default: Edge from 1515 to 1516 not found!

  Error: Edge from 1515 to 1516 not found!
      at ContentGraph.removeEdge (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+graph@2.8.2/node_modules/@parcel/graph/lib/Graph.js:156:13)
      at MutableBundleGraph.createBundleGroup (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/public/MutableBundleGraph.js:134:24)
      at decorateLegacyGraph (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+bundler-default@2.8.2_@parcel+core@2.8.2/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:159:35)
      at Object.bundle (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+bundler-default@2.8.2_@parcel+core@2.8.2/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:126:7)
      at BundlerRunner.bundle (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:288:23)
      at async Object.run (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:156:17)
      at async RequestTracker.runRequest (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async Object.run (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:56:7)
      at async RequestTracker.runRequest (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async Parcel._build (/home/leonie/www/Kwintessens/kwink/typo3/public/typo3conf/ext/cb_kwink_sitepackage/Resources/Private/Frontend/Assets/Digibord/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/Parcel.js:400:11)

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by mischnic** [comment]
Can someone share a reproduction?

**Comment by LeoniePhiline** [comment]
I'll try to rebuild my big project into something small - hopefully it'll still trigger.

**Comment by LeoniePhiline** [comment]
@mischnic In my attempts to reproduce, I always end up with a different bug: https://github.com/parcel-bundler/parcel/issues/6310

```
$ npm run dev                                                                                                                                                                                                                                                                                          

> test@0.1.0 dev /tmp/test
> NODE_ENV=development parcel build --no-optimize

🚨 Build failed.

@parcel/namer-default: Bundle group cannot have more than one entry bundle of the same type

  AssertionError [ERR_ASSERTION]: Bundle group cannot have more than one entry bundle of the same type
      at Object.name (/tmp/test/node_modules/.pnpm/@parcel+namer-default@2.8.2_@parcel+core@2.8.2/node_modules/@parcel/namer-default/lib/DefaultNamer.js:82:29)
      at BundlerRunner.nameBundle (/tmp/test/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:402:39)
      at /tmp/test/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:378:50
      at Array.map (<anonymous>)
      at BundlerRunner.nameBundles (/tmp/test/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:378:31)
      at async BundlerRunner.bundle (/tmp/test/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:341:7)
      at async Object.run (/tmp/test/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:156:17)
      at async RequestTracker.runRequest (/tmp/test/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async Object.run (/tmp/test/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:56:7)
      at async RequestTracker.runRequest (/tmp/test/node_modules/.pnpm/@parcel+core@2.8.2/node_modules/@parcel/core/lib/RequestTracker.js:756:20)

 ELIFECYCLE  Command failed with exit code 1.
```
