### ISSUE TITLE
ElmTransformer.formatElmError - wrong usage of `String.prototype.repeat`

### ISSUE THREAD

**Issue by Janiczek** [parcel-bundler/parcel#8805]
# 🐛 bug report

In `ElmTransformer`, sometimes the `formatElmError` function crashes because it gives a negative number to `String.prototype.repeat` (see the stacktrace below).

I suspect this is because of wrong calculation on the line just above it:
```js
  const padLength = 80 - 5 - problem.title.length - relativePath.length;
  const dashes = '-'.repeat(padLength);
```

as it can get negative once the file path is long enough, and `String.prototype.repeat` doesn't like negative numbers.

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`:
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.elm": ["parcel-transformer-elm-svg-modules", "..."]
  }
}
```

`package.json` dependencies:
* `"@parcel/transformer-elm": "^2.8.3"`
* `"parcel": "^2.8.3"`

## 🤔 Expected Behavior

Don't crash, work correctly no matter how long the problem title and relativePath is.

## 😯 Current Behavior

```
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at formatElmError (/Users/martin/Localhost/permutive/frontend-gcp/elm/node_modules/@parcel/transformer-elm/lib/ElmTransformer.js:241:22)
    at /Users/martin/Localhost/permutive/frontend-gcp/elm/node_modules/@parcel/transformer-elm/lib/ElmTransformer.js:236:40
    at Array.map (<anonymous>)
    at elmCompileErrorToParcelDiagnostics (/Users/martin/Localhost/permutive/frontend-gcp/elm/node_modules/@parcel/transformer-elm/lib/ElmTransformer.js:236:25)
    at Array.flatMap (<anonymous>)
    at Object.transform (/Users/martin/Localhost/permutive/frontend-gcp/elm/node_modules/@parcel/transformer-elm/lib/ElmTransformer.js:149:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Transformation.runTransformer (/Users/martin/Localhost/permutive/frontend-gcp/elm/node_modules/@parcel/core/lib/Transformation.js:653:5)
```

## 💁 Possible Solution

min/max/clamp?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3 |
| Node             | v16.19.0 |
| npm/Yarn         | npm 8.19.3, yarn 1.22.15 |
| Operating System | macOS Ventura 13.1 |

**Comment by danieltroger** [comment]
I'm getting the same issue in a typescript react project just before parcel is about to print a sass error:

```
RangeError: Invalid count value: -3
    at String.repeat (<anonymous>)
    at $796233c1fee0ccb8$export$2e2bcd8739ae039 (/Users/daniel/Documents/depict.ai/portal/frontend/app/.yarn/cache/@parcel-codeframe-npm-2.8.3-e5df811b95-a6e82c30e6.zip/node_modules/@parcel/codeframe/lib/codeframe.js:36038:54)
    at $f02d6a9d30f55938$export$2e2bcd8739ae039 (/Users/daniel/Documents/depict.ai/portal/frontend/app/.yarn/cache/@parcel-utils-npm-2.8.3-13fd8c7807-69edf3e7c3.zip/node_modules/@parcel/utils/lib/index.js:33490:101)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $ed871dc03bbf580d$var$writeDiagnostic (/Users/daniel/Documents/depict.ai/portal/frontend/app/.yarn/cache/@parcel-reporter-cli-npm-2.8.3-d340f7fcb8-791dd4706a.zip/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:7462:121)
```

Clearing the cache makes it go away tho (it's flaky and doesn't happen every time). Just wanted to let you know.
