### ISSUE TITLE
parcel watch error: Expected content key 2d39cdf7c618ab5b to exist

### ISSUE THREAD

**Issue by ted-palmer** [parcel-bundler/parcel#8874]
# 🐛 bug report

When running `parcel watch 'packages/*' --no-cache` I'm getting the following errors:
```
Error: Expected content key 2d39cdf7c618ab5b to exist
    at nullthrows (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/nullthrows/nullthrows.js:7:15)
    at ContentGraph.getNodeIdByContentKey (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/graph/lib/ContentGraph.js:81:38)
    at BundleGraph.getDependencies (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/core/lib/BundleGraph.js:746:30)
    at BundleGraph.getDependencies (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/core/lib/public/BundleGraph.js:145:24)
    at /Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:17188:54
    at /Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33551:34
    at $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33579:19)
    at $b0fd219fea43bcac$export$2e2bcd8739ae039._next (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33572:20)
    at $b0fd219fea43bcac$export$2e2bcd8739ae039.run (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33567:81)
    at $7728b866c345490a$export$2e2bcd8739ae039.emitUpdate (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:17210:34) {
  framesToPop: 1
}
Error: Expected content key 2d39cdf7c618ab5b to exist
    at nullthrows (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/nullthrows/nullthrows.js:7:15)
    at ContentGraph.getNodeIdByContentKey (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/graph/lib/ContentGraph.js:81:38)
    at BundleGraph.getDependencies (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/core/lib/BundleGraph.js:746:30)
    at BundleGraph.getDependencies (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/core/lib/public/BundleGraph.js:145:24)
    at /Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:17188:54
    at /Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33551:34
    at $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33579:19)
    at $b0fd219fea43bcac$export$2e2bcd8739ae039._next (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33572:20)
    at $b0fd219fea43bcac$export$2e2bcd8739ae039.run (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33567:81)
    at $7728b866c345490a$export$2e2bcd8739ae039.emitUpdate (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:17210:34) {
  framesToPop: 1
}
Error: Expected content key 2b62a9a42f419169 to exist
    at nullthrows (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/nullthrows/nullthrows.js:7:15)
    at ContentGraph.getNodeIdByContentKey (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/graph/lib/ContentGraph.js:81:38)
    at BundleGraph.getDependencies (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/core/lib/BundleGraph.js:746:30)
    at BundleGraph.getDependencies (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/core/lib/public/BundleGraph.js:145:24)
    at /Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:17188:54
    at /Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33551:34
    at $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33579:19)
    at $b0fd219fea43bcac$export$2e2bcd8739ae039._next (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33572:20)
    at $b0fd219fea43bcac$export$2e2bcd8739ae039.run (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33567:81)
    at $7728b866c345490a$export$2e2bcd8739ae039.emitUpdate (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:17210:34) {
  framesToPop: 1
}
Error: Expected content key a628082bff6583f1 to exist
    at nullthrows (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/nullthrows/nullthrows.js:7:15)
    at ContentGraph.getNodeIdByContentKey (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/graph/lib/ContentGraph.js:81:38)
    at BundleGraph.getDependencies (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/core/lib/BundleGraph.js:746:30)
    at BundleGraph.getDependencies (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/core/lib/public/BundleGraph.js:145:24)
    at /Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:17188:54
    at /Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33551:34
    at $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33579:19)
    at $b0fd219fea43bcac$export$2e2bcd8739ae039._next (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33572:20)
    at $b0fd219fea43bcac$export$2e2bcd8739ae039._next (/Users/tedpalmer/Desktop/reservoir-kit/node_modules/@parcel/utils/lib/index.js:33573:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  framesToPop: 1
✨ Built in 6.89s
```
Running `parcel build 'packages/*' --no-cache` builds fine with no errors.

Downgrading to parcel 2.8.2 didn't fix this, as suggested in #8787 

Deleting `.parcel-cache` also didn't work.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "devDependencies": {
    "@parcel/optimizer-data-url": "2.8.2",
    "@parcel/packager-ts": "2.8.2",
    "@parcel/transformer-inline-string": "2.8.2",
    "@parcel/transformer-typescript-tsc": "2.8.2",
    "@parcel/transformer-typescript-types": "2.8.2",
    "@types/node": "^17.0.10",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "buffer": "^6.0.3",
    "ethers": "^5.6.9",
    "gitlog": "^4.0.4",
    "parcel": "2.8.2",
    "prettier": "^2.5.1",
    "process": "^0.11.10",
    "replace-in-files": "^3.0.0",
    "typescript": "^4.9.4"
  },
}
```

## 🤔 Expected Behavior

Running `parcel watch 'packages/*' --no-cache` should build with no errors, just as `parcel build 'packages/*' --no-cache` does.

## 😯 Current Behavior

Seeing the errors mentioned above.

## 💁 Possible Solution

Update: adding the `--no-hmr` parameter to `parcel watch` made the errors go away

## 💻 Code Sample
Here is the repo where I am running into this issue:
https://github.com/reservoirprotocol/reservoir-kit/tree/ted/upgrade-typescript-solution

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3 and 2.8.2
| Node             | 
| npm/Yarn         | 
| Operating System | macOS Ventura 13.1

**Comment by cyrusdean** [comment]
I'm also experiencing this issue, but it's also on my `build`. At first I noticed it when building my Docker image but not locally. After clearing my package-lock and installing the latest version it began happening locally as well.

I've also tried 2.8.2 and same result.

When I tried to revert back to the version I was using, 2.7.0, I started getting a new error: 

`@parcel/workers: Expected constructor 2.7.0:BundleGraph to be registered with serializer to deserialize`

I've yet to find a way around this issue.

EDIT:

Just now found a way around it. I reverted to 2.7.0 again and found where the error in reverting before was. I hadn't explicitly installed `@parcel/core` at 2.7.0. Adding that to the dependencies, matching `parcel` and `@parcel/transformer-sass` my build functions again.

**Comment by ted-palmer** [comment]
Update: I also hadn't explicitly installed `@parcel/core`, however, that didn't fix the issue for me. After a lot of testing I discovered that adding the `--no-hmr` parameter to `parcel watch` made the errors go away

**Comment by vinayadiga7** [comment]
For me it worked when I deleted the .parcel-cache and dist folders completely in the root directory and did the rebuild.

**Comment by rcramh** [comment]
delete the .parcel-cache folder, then try running command again, it'll work.

**Comment by nitukumari34** [comment]
error: Expected content key de1e4a02ec63c4eb to exist
This error occurs in parcel version 2.9.2 .
  then I downgrade the parcel version into 2.7.0 and then error resolved .

**Comment by taofeek-ob** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.

This fixed it for me.

**Comment by akanandhu** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.

This worked for me

**Comment by Harshitbansal637** [comment]
Same error occurred to me in parcel version - 2.9.3
Solution that worked for me - clear the parcel cache (rm -rf .parcel-cache) and run the application again.

**Comment by rajatrawal** [comment]
> 



> then

this worked for me

**Comment by NiteshJ1998** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.

This worked for me . Thank you

**Comment by nitrathod** [comment]
I just deleted the .parcel-cache and dist folders completely from the root directory and rebuild the applicate, it did worked for me

**Comment by chhatrapati295** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.
Thank you , it works . First delete parcel-cache folder then start your dev server ex. : npx parcel index.html

**Comment by RuquiaAlam** [comment]
> error: Expected content key de1e4a02ec63c4eb to exist This error occurs in parcel version 2.9.2 . then I downgrade the parcel version into 2.7.0 and then error resolved .

this helped me..thanks

**Comment by ghost** [comment]
Thanks, I deleted both the dist and cache, and now it works. It accidentally deleted the dist first so you probably won't have to. But thanks for the solution. I haven't worked with a dist before so appreciate your post.

**Comment by Subha8371** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.

its working✨

**Comment by Rashid004** [comment]
Error: Expected content key de1e4a02ec63c4eb to exist

  Error: Expected content key de1e4a02ec63c4eb to exist
      at nullthrows (C:\Users\Ansari Rashid\Desktop\starter\node_modules\nullthrows\nullthrows.js:7:15)
      at AssetGraph.getNodeIdByContentKey (C:\Users\Ansari
  Rashid\Desktop\starter\node_modules\@parcel\graph\lib\ContentGraph.js:67:38)
      at C:\Users\Ansari Rashid\Desktop\starter\node_modules\@parcel\core\lib\SymbolPropagation.js:52:82
      at Array.map (<anonymous>)
      at propagateSymbols (C:\Users\Ansari Rashid\Desktop\starter\node_modules\@parcel\core\lib\SymbolPropagation.js:52:61)
      at AssetGraphBuilder.build (C:\Users\Ansari
  Rashid\Desktop\starter\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:168:62)
      at async Object.run (C:\Users\Ansari Rashid\Desktop\starter\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:60:37)  
      at async RequestTracker.runRequest (C:\Users\Ansari
  Rashid\Desktop\starter\node_modules\@parcel\core\lib\RequestTracker.js:633:20)
      at async Object.run (C:\Users\Ansari Rashid\Desktop\starter\node_modules\@parcel\core\lib\requests\BundleGraphRequest.js:103:11)
      at async RequestTracker.runRequest (C:\Users\Ansari
  Rashid\Desktop\starter\node_modules\@parcel\core\lib\RequestTracker.js:633:20)

**Comment by collokaris** [comment]
> This worked for me. Thank you

**Comment by KeshavTandon** [comment]
> Error: Expected content key de1e4a02ec63c4eb to exist
> 
> Error: Expected content key de1e4a02ec63c4eb to exist at nullthrows (C:\Users\Ansari Rashid\Desktop\starter\node_modules\nullthrows\nullthrows.js:7:15) at AssetGraph.getNodeIdByContentKey (C:\Users\Ansari Rashid\Desktop\starter\node_modules@parcel\graph\lib\ContentGraph.js:67:38) at C:\Users\Ansari Rashid\Desktop\starter\node_modules@parcel\core\lib\SymbolPropagation.js:52:82 at Array.map () at propagateSymbols (C:\Users\Ansari Rashid\Desktop\starter\node_modules@parcel\core\lib\SymbolPropagation.js:52:61) at AssetGraphBuilder.build (C:\Users\Ansari Rashid\Desktop\starter\node_modules@parcel\core\lib\requests\AssetGraphRequest.js:168:62) at async Object.run (C:\Users\Ansari Rashid\Desktop\starter\node_modules@parcel\core\lib\requests\AssetGraphRequest.js:60:37) at async RequestTracker.runRequest (C:\Users\Ansari Rashid\Desktop\starter\node_modules@parcel\core\lib\RequestTracker.js:633:20) at async Object.run (C:\Users\Ansari Rashid\Desktop\starter\node_modules@parcel\core\lib\requests\BundleGraphRequest.js:103:11) at async RequestTracker.runRequest (C:\Users\Ansari Rashid\Desktop\starter\node_modules@parcel\core\lib\RequestTracker.js:633:20)

I am getting the same error

**Comment by Steve-1993** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.

This worked for me too. Thank you

**Comment by jason-murray** [comment]
Deleting .parcel-cache works for me until I change the HTML node structure in any way, then the problem returns. I'm changing elements all the time so this fix isn't really valid for me. Anyone else got this?

**Comment by AkashBharti97** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.

It work for me .

**Comment by JINESH-742203970** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.

Yeah,after deleting .parcel-cache folder and run command again .It's working for me

**Comment by Rashid004** [comment]
Nice

**Comment by ARyaskov** [comment]
Right, deleting of `.parcel-cache` did a trick.
If you are using monorepos pls **delete a top-level `.parcel-cache`**, not into `/packages/your-package/`.

**Comment by SodiqSWE** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.

Yep, this did it for me as well!

**Comment by 0xchikku** [comment]
> For me it worked when I deleted the .parcel-cache and dist folders completely in the root directory and did the rebuild.

Worked for me, using parcel version 2.10.3

**Comment by Revathi-80** [comment]
> folder

yes deleting .parcel-cache worked for me

**Comment by priyanshukumar001** [comment]
after closing the server and 
then deleting the .parcel-cache file and 
again executing npx parcel <entry point>

solved the problem!

**Comment by aakash-01-1996** [comment]
Step 1. Stop the Server (ctrl + c)
Step 2. Delete **.parcel-cache** folder
Step 3. npx parcel index.html

Problem solved!🤝

**Comment by DerekGray2022** [comment]
> > delete the .parcel-cache folder, then try running command again, it'll work.
> 
> Stopping the server running then doing this worked for me.

**Comment by r-rayns** [comment]
> Deleting .parcel-cache works for me until I change the HTML node structure in any way, then the problem returns. I'm changing elements all the time so this fix isn't really valid for me. Anyone else got this?

This is what I'm experiencing too. I can edit one of my JavaScript files over and over without this error occurring. I can even edit inside a `<script>` tag inside a `.html` document without issue. As soon as I start editing my HTML markup I get this error and have to restart parcel.

**Comment by pandeyvimal-03** [comment]
delete parcel-cache and dist folder then restart your using npx parcel index.html

**Comment by uuf6429** [comment]
It's been well over a year since this was reported, and there is still no real solution except the half-assed workaround repeatedly mentioned in the previous ~25 useless comments (kudos on that guys /s).

**Comment by Pulastya12** [comment]
using "rm -rf .parcel-cache"  command to remove the "parcel cache" worked for me

**Comment by itzmk06** [comment]
> delete the .parcel-cache folder, then try running command again, it'll work.

this worked !

**Comment by uuf6429** [comment]
@itzmk06 oh wow, what do you know .. the same thing >20 people already said above turned out to be true. /s

**Comment by helloint** [comment]
I'm using pacel `2.8.0` and encountered this issue. The issue only happened on `watch`, not `build`.
```
"@parcel/packager-ts": "2.8.0",
"@parcel/transformer-typescript-types": "2.8.0",
"parcel": "2.8.0",
```
I have tried removing `.parcel-cache/`, also `dist/` (But I don't think `dist/` is related), still doesn't fix.
I then tried to downgrade to `2.7.0`:
```
"@parcel/packager-ts": "2.7.0",
"@parcel/transformer-typescript-types": "2.7.0",
"parcel": "2.7.0",
```
The issue gone.
But downgrade is not a good solution, so I tried to upgrade to latest `2.12.0`:
```
"@parcel/packager-ts": "2.12.0",
"@parcel/transformer-typescript-types": "2.12.0",
"parcel": "2.12.0",
```
It works. Looks like there is something wrong with `2.8`, but as long as the later version works, it doesn't matter to me.

**Comment by TechQuery** [comment]
Any update?

**Comment by Rashid004** [comment]
Use old version 🧠if not working some time ⚡old version work we'll ✅

**Comment by TechQuery** [comment]
@devongovett @mischnic Latest `parcel@2.16.1` has the same error with latest LESS compiler, and `rm -rf .parcel-cache/` can't fix this (FreeCodeCamp-Chengdu/fcc.chengdu@9569979), but `--no-scope-hoist` works fine (#5985).
