### ISSUE TITLE
parcel build: Error loading shared library (ERR_DLOPEN_FAILED) when cross-compiling

### ISSUE THREAD

**Issue by dkwo** [parcel-bundler/parcel#8962]
on linux, when cross-compiling the program ui of https://github.com/influxdata/chronograf from x86_64-musl to aarch64-glibc with `CFLAGS="$CFLAGS -fPIC" CXXFLAGS="$CXXFLAGS -fPIC" npm_config_target_arch=arm64 npm_config_target_platform=linux npm_config_target_libc=glibc make .jsdep assets`
the step `cd ui && yarn run clean && yarn run build` fails with
```
cd ui && yarn --no-progress --no-emoji
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "workspace-aggregator-4aff40ea-0700-4a6b-b51f-8ede52839c87 > chronograf-ui > cypress-image-snapshot@4.0.1" has incorrect peer dependency "cypress@^4.5.0".
warning "workspace-aggregator-4aff40ea-0700-4a6b-b51f-8ede52839c87 > chronograf-ui > react-tooltip@3.11.6" has incorrect peer dependency "react@>=^16.0.0".
warning "workspace-aggregator-4aff40ea-0700-4a6b-b51f-8ede52839c87 > chronograf-ui > react-tooltip@3.11.6" has incorrect peer dependency "react-dom@>=^16.0.0".
warning "workspace-aggregator-4aff40ea-0700-4a6b-b51f-8ede52839c87 > chronograf-ui > cypress-image-snapshot > jest-image-snapshot@4.2.0" has incorrect peer dependency "jest@>=20 <=26".
[4/4] Building fresh packages...
$ echo "" > ../node_modules/go.mod
Done in 53.27s.
cd ui && yarn run clean && yarn run build
yarn run v1.22.18
$ rm -rf ./build/* && rm -rf ./.cache ../.parcel-cache
Done in 0.12s.
yarn run v1.22.18
$ APP_VERSION=$npm_package_version GIT_SHA=$(git rev-parse HEAD) parcel build --log-level error
fatal: not a git repository (or any of the parent directories): .git
Error: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /builddir/chronograf-1.10.1/node_modules/lmdb/build/Release/lmdb.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1249:18)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (/builddir/chronograf-1.10.1/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.load [as default] (/builddir/chronograf-1.10.1/node_modules/lmdb/node_modules/node-gyp-build-optional-packages/index.js:20:10)
    at Object.<anonymous> (/builddir/chronograf-1.10.1/node_modules/lmdb/dist/index.cjs:47:47)
    at Module._compile (/builddir/chronograf-1.10.1/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32) {
  code: 'ERR_DLOPEN_FAILED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:62: .jssrc] Error 1
```
Is there a simple way to fix this?
Refs: https://github.com/influxdata/chronograf/issues/6036 https://github.com/void-linux/void-packages/pull/42644

**Comment by mischnic** [comment]
Sounds like a problem specific to [lmdb](https://github.com/kriszyp/lmdb-js) and not Parcel?

**Comment by dkwo** [comment]
Thanks, I reported it there https://github.com/kriszyp/lmdb-js/issues/229
