### ISSUE TITLE
CSS module composes triggers `Got unexpected null` in ScopeHoistingPackager

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#9071]
# 🐛 bug report

CSS module with composes triggers `Got unexpected null`

## 🤔 Expected Behavior

Works

## 😯 Current Behavior

```
  Error: Got unexpected null
      at nullthrows (parcel/node_modules/nullthrows/nullthrows.js:7:15)
      at every (parcel/packages/packagers/js/src/ScopeHoistingPackager.js:1081:35)
      at Array.every (<anonymous>)
      at filter (parcel/packages/packagers/js/src/ScopeHoistingPackager.js:1080:35)
      at Array.filter (<anonymous>)
      at ScopeHoistingPackager.buildAssetPrelude (parcel/packages/packagers/js/src/ScopeHoistingPackager.js:1069:60)
      at ScopeHoistingPackager.buildAsset (parcel/packages/packagers/js/src/ScopeHoistingPackager.js:448:48)
      at ScopeHoistingPackager.visitAsset (parcel/packages/packagers/js/src/ScopeHoistingPackager.js:383:17)
      at processAsset (parcel/packages/packagers/js/src/ScopeHoistingPackager.js:143:40)
      at visit (parcel/packages/packagers/js/src/ScopeHoistingPackager.js:170:7)
      at visit (parcel/packages/core/graph/src/Graph.js:504:16)
      at visit (parcel/packages/core/graph/src/Graph.js:504:16)
      at enter (parcel/packages/core/graph/src/Graph.js:504:16)
      at walk (parcel/packages/core/graph/src/Graph.js:346:26)
      at walk (parcel/packages/core/graph/src/Graph.js:367:22)
      at ContentGraph.dfs (parcel/packages/core/graph/src/Graph.js:395:12)
      at BundleGraph.traverseBundle (parcel/packages/core/core/src/BundleGraph.js:1321:24)
      at BundleGraph.traverseAssets (parcel/packages/core/core/src/BundleGraph.js:1117:17)
      at NamedBundle.traverseAssets (parcel/packages/core/core/src/public/Bundle.js:193:30)
      at ScopeHoistingPackager.package (parcel/packages/packagers/js/src/ScopeHoistingPackager.js:164:17)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at Object.package (parcel/packages/packagers/js/src/index.js:62:26)
```

## 💁 Possible Solution

Something about the JS generated for the CSS module has to trigger this?

## 🔦 Context

https://github.com/parcel-bundler/parcel/issues/9058

## 💻 Code Sample

[src.zip](https://github.com/parcel-bundler/parcel/files/11645155/src.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 0645f644238f6dbdadb8e01fa63be6ed2152830b

**Comment by AndrewKvalheim** [comment]
A reproduction trimmed down from my codebase:

```console
$ echo 'export const c = "c"; export default "a";' > a.js
$ echo 'import { c } from "./a"; console.log(c);' > b.js
$ echo '<script type=module src='{a,b}'.js></script>' > index.html
$ yarn add parcel@2.8.3 && parcel build index.html
✨ Built in 722ms
$ yarn add parcel@2.9.2 && parcel build index.html
🚨 Build failed.

@parcel/packager-js: Got unexpected null

  Error: Got unexpected null
      at nullthrows (node_modules/nullthrows/nullthrows.js:7:15)
      at node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:813:51
      at Array.every (<anonymous>)
      at node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:812:35
      at Array.filter (<anonymous>)
      at ScopeHoistingPackager.buildAssetPrelude
  (node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:802:60)
      at ScopeHoistingPackager.buildAsset
  (node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:367:48)
      at ScopeHoistingPackager.visitAsset
  (node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:322:17)
      at processAsset (node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:126:40)
      at ScopeHoistingPackager.package
  (node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:140:9)
```

**Comment by colorgold** [comment]
I was having this same issue, but I solved it by running `parcel build public/index.html --no-scope-hoist`.
Adding the `--no-scope-hoist` is what did it for me. I don't know exactly what was preventing Parcel from "scope hoisting", so in the meantime I will go without it.

**Comment by DimaPFf** [comment]
Thank you! It works for me too!

**Comment by ajyoon** [comment]
I'm running into this issue as well, coming from the same line in `ScopeHoistingPackager`.

**Comment by shepmaster** [comment]
Continues to happen in 2.12

```
🚨 Build failed.

@parcel/packager-js: Got unexpected null

  Error: Got unexpected null
      at nullthrows
  (<project>/node_modules/.pnpm/nullthrows@1.1.1/node_modules/nullthrows/nullthrows.js:7:15)
      at
  <project>/node_modules/.pnpm/@parcel+packager-js@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:864:51
      at Array.every (<anonymous>)
      at
  <project>/node_modules/.pnpm/@parcel+packager-js@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:863:35
      at Array.filter (<anonymous>)
      at ScopeHoistingPackager.buildAssetPrelude
  (<project>/node_modules/.pnpm/@parcel+packager-js@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:853:60)
      at ScopeHoistingPackager.buildAsset
  (<project>/node_modules/.pnpm/@parcel+packager-js@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:404:48)
      at ScopeHoistingPackager.visitAsset
  (<project>/node_modules/.pnpm/@parcel+packager-js@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:359:17)
      at processAsset
  (<project>/node_modules/.pnpm/@parcel+packager-js@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:142:40)
      at
  <project>/node_modules/.pnpm/@parcel+packager-js@2.12.0_@parcel+core@2.12.0/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:167:7
```

**Comment by l3laze** [comment]
I tried to load extra JS modules in the HTML which are later chain-imported by the primary script. `app.mjs` is executed by the HTML and imports a class from `one.mjs` which imports a named object from `two.mjs`.


This works without `parcel build`, but when using it fails with only the extremely cryptic "Got unexpected null". So, multiple imports of the same module may be relevant to this issue.


In this case the `--no-scope-hoist` workaround above caused an `uncaught error 'cannot find module [hash name]'` when running the app, which of course causes it to die horribly.

**Comment by shepmaster** [comment]
Continues to happen in 2.14.4:

```
@parcel/packager-js: Got unexpected null

  Error: Got unexpected null
      at nullthrows (<project>/node_modules/.pnpm/nullthrows@1.1.1/node_modules/nullthrows/nullthrows.js:7:15)
      at <project>/node_modules/.pnpm/@parcel+packager-js@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:963:51
      at Array.every (<anonymous>)
      at <project>/node_modules/.pnpm/@parcel+packager-js@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:962:35
      at Array.filter (<anonymous>)
      at ScopeHoistingPackager.buildAssetPrelude
  (<project>/node_modules/.pnpm/@parcel+packager-js@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:952:60)
      at ScopeHoistingPackager.buildAsset
  (<project>/node_modules/.pnpm/@parcel+packager-js@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:426:48)
      at ScopeHoistingPackager.visitAsset
  (<project>/node_modules/.pnpm/@parcel+packager-js@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:357:17)
      at <project>/node_modules/.pnpm/@parcel+packager-js@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:480:58
      at String.replace (<anonymous>)
```
