### ISSUE TITLE
RangeError: Invalid count value error

### ISSUE THREAD

**Issue by ola-893** [parcel-bundler/parcel#9112]
# 🐛 bug report

parcel build returning throwing an error

## 🎛 Configuration (.babelrc, package.json, cli command)

CLI command:  ```rm -rf dist/* && rm -rf .parcel-cache && parcel build index.html --public-url ./```

## 🤔 Expected Behavior

parcel build should create a build output in the dist folder

## 😯 Current Behavior

CLI command:  ```rm -rf dist/* && rm -rf .parcel-cache && parcel build index.html --public-url ./``` throws the error below
```🚨 Build failed.
RangeError: Invalid count value```

full stack trace

```🚨 Build failed.
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at $796233c1fee0ccb8$export$2e2bcd8739ae039 (/Users/ola/Documents/Github/Gambloc-2.0/frontend/node_modules/@parcel/codeframe/lib/codeframe.js:36028:54)
    at $f02d6a9d30f55938$export$2e2bcd8739ae039 (/Users/ola/Documents/Github/Gambloc-2.0/frontend/node_modules/@parcel/utils/lib/index.js:34143:101)
    at $25f952b9ba2ff3e6$var$writeDiagnostic (/Users/ola/Documents/Github/Gambloc-2.0/frontend/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:7473:162)
    at $25f952b9ba2ff3e6$export$12358408d9820617 (/Users/ola/Documents/Github/Gambloc-2.0/frontend/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:7439:19)
    at Object.report (/Users/ola/Documents/Github/Gambloc-2.0/frontend/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:7501:16)
    at ReporterRunner.report (/Users/ola/Documents/Github/Gambloc-2.0/frontend/node_modules/@parcel/core/lib/ReporterRunner.js:98:33)
    at Parcel._build (/Users/ola/Documents/Github/Gambloc-2.0/frontend/node_modules/@parcel/core/lib/Parcel.js:363:34)
    at async Parcel.run (/Users/ola/Documents/Github/Gambloc-2.0/frontend/node_modules/@parcel/core/lib/Parcel.js:195:18)
    at async run (/Users/ola/Documents/Github/Gambloc-2.0/frontend/node_modules/parcel/lib/cli.js:308:7)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | v16.18.0
| npm/Yarn         | 8.19.2
| Operating System | macOS ventura 13.3.1

**Comment by gmerciel** [comment]
I'm having the same issue

**Comment by ola-893** [comment]
Hopefully we'll get a response soon

**Comment by gmerciel** [comment]
Going back to previous commits that worked, I found that my problem was with a line like this:
`delete (gmap)`
Changing to `gmap = undefined` allowed me to build

**Comment by devongovett** [comment]
Please provide a reproduction.

**Comment by furkanmustafa** [comment]
We also encountered this issue, but I believe it is fairly difficult to produce a reproduction. Because parcel is unable to report what the problem is.

The spot in the enourmous file `@parcel/codeframe/lib/codeframe.js:36028` here, is trying to mark the error location, possibly a multi line spanning problematic code ? so it calculates positions for the first line/col, last line/col and such.. but apparently there is a problem in the calculation. Which I couldn't read/study further to understand better. yet.

**Comment by studiosciences** [comment]
I'm seeing this after upgrading to 2.9.3, so it could be anywhere in our code. Based on previous comments and related issues, I've tried:
- deleting all css/less imports
- not using the `delete` command.

This did not fix anything.
