### ISSUE TITLE
`@parcel/fs tried to access @parcel/core (a peer dependency) but it isn't provided by its ancestors` error when following tutorial

### ISSUE THREAD

**Issue by perlun** [parcel-bundler/parcel#9114]
# 🐛 bug report

Following the general tutorial at https://parceljs.org/getting-started/webapp/ gives me the error below when trying to run `yarn parcel src/index.html`.

The `yarn add` step worked fine and added `parcel` properly to the my `package.json`.

### `package.json`

```json
{
  "name": "example.com",
  "packageManager": "yarn@3.6.0",
  "devDependencies": {
    "parcel": "^2.9.3"
  }
}
```

I don't have any `.babelrc` AFAICT.

## 🤔 Expected Behavior

The app should be built and the devserver should be started.

## 😯 Current Behavior

```
$ yarn parcel src/index.html
Server running at http://localhost:1234
🚨 Build failed.

@parcel/core: Failed to resolve 'src/index.html' 
@parcel/resolver-default: @parcel/fs tried to access @parcel/core (a peer dependency) but it isn't provided by its ancestors; this makes the
 require call ambiguous and unsound.

Required package: @parcel/core
Required by: 
@parcel/fs@virtual:eef76f9fa9a588b8c892c493e6d851511aea6315c558ec074869cea35c69731f4489ed7c976fb55873d3f05e6ad5a0ad010792d1d87f51f47b52fc5dc26251b7#npm:2.9.3
 (via 
/home/per/git/example.com/.yarn/__virtual__/@parcel-fs-virtual-e623c8b450/0/cache/@parcel-fs-npm-2.9.3-f6cd93298b-c9bf9ca9e6.zip/node_modules/@parcel/fs/lib/)

Ancestor breaking the chain: @parcel/node-resolver-core@npm:3.0.3
Ancestor breaking the chain: @parcel/types@npm:2.9.3


Require stack:
- 
/home/per/git/example.com/.yarn/__virtual__/@parcel-fs-virtual-e623c8b450/0/cache/@parcel-fs-npm-2.9.3-f6cd93298b-c9bf9ca9e6.zip/node_modules/@parcel/fs/lib/index.js
- 
/home/per/git/example.com/.yarn/unplugged/@parcel-node-resolver-core-npm-3.0.3-e85849af08/node_modules/@parcel/node-resolver-core/lib/Wrapper.js
- 
/home/per/git/example.com/.yarn/unplugged/@parcel-node-resolver-core-npm-3.0.3-e85849af08/node_modules/@parcel/node-resolver-core/lib/index.js
- 
/home/per/git/example.com/.yarn/__virtual__/@parcel-package-manager-virtual-bbad0025e5/0/cache/@parcel-package-manager-npm-2.9.3-c065cee1b5-46acc905b8.zip/node_modules/@parcel/package-manager/lib/index.js
- /home/per/git/example.com/.yarn/cache/@parcel-core-npm-2.9.3-b343ad5e82-e4ba4e0909.zip/node_modules/@parcel/core/lib/resolveOptions.js
- /home/per/git/example.com/.yarn/cache/@parcel-core-npm-2.9.3-b343ad5e82-e4ba4e0909.zip/node_modules/@parcel/core/lib/Parcel.js
- /home/per/git/example.com/.yarn/cache/@parcel-core-npm-2.9.3-b343ad5e82-e4ba4e0909.zip/node_modules/@parcel/core/lib/index.js
- 
/home/per/git/example.com/.yarn/__virtual__/parcel-virtual-2add9e67f2/0/cache/parcel-npm-2.9.3-33db24662f-d9b9c0083f.zip/node_modules/parcel/lib/cli.js
- 
/home/per/git/example.com/.yarn/__virtual__/parcel-virtual-2add9e67f2/0/cache/parcel-npm-2.9.3-33db24662f-d9b9c0083f.zip/node_modules/parcel/lib/bin.js
```

## 💻 Code Sample

N/A at the moment, but can be provided if needed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | v18.16.1, installed using `asdf`
| npm/Yarn         | Yarn 3.6.0
| Operating System | Debian GNU/Linux 12 (bookworm)

**Comment by hrynevychroman** [comment]
can you give a reproduction link? https://codesandbox.io/ will be great

**Comment by Kuinox** [comment]
I'm having the same issue.
simply running
```
yarn init -2
yarn add --dev parcel
yarn parcel index.html
```
triggers the problem.

**Comment by Kuinox** [comment]
I made a codesanbox here: https://codesandbox.io/p/sandbox/zealous-https-z83pz3
But again, simply following the getting started using yarn lead to this. There is nothing specific.

**Comment by hrynevychroman** [comment]
please, add @parcel/core to your dev dependencies)
<img width="415" alt="image" src="https://github.com/parcel-bundler/parcel/assets/82209198/cf2bef57-fc47-4ab5-8358-5bdc596d72a3">

And everything will work fine: link to reproduction - https://codesandbox.io/p/sandbox/gallant-haze-t9qjqh?file=%2Fsrc%2Findex.html%3A10%2C13

Also i would recommend to add index.html to src/ folder 🙂

**Comment by Kuinox** [comment]
> Also i would recommend to add index.html to src/ folder 🙂

That's was for the demo.  

> please, add @parcel/core to your dev dependencies)  

The getting started doesn't mention this.  
![image](https://github.com/parcel-bundler/parcel/assets/18743295/41dd343f-020f-43bb-b799-65d7160699e3)

Also, this workarounds doesn't works on bigger projects:  
![image](https://github.com/parcel-bundler/parcel/assets/18743295/a797b119-ef94-4197-baab-647f7cb0fe3d)

A "stable" workaround is to put yarn pnp in "loose" mode.

**Comment by hrynevychroman** [comment]
> The getting started doesn't mention this.

I'm a simple dev like you, i don't have permision to edit docs 🙂 

> Also, this workarounds doesn't works on bigger projects:

I see that parcel in your dependencies is not similar with @parcel/ packages, maybe this is an issue)

**Comment by Kuinox** [comment]
> I see that parcel in your dependencies is not similar with @parcel/ packages, maybe this is an issue)

Ah it's just the leftover of me trying to see if it's a recent parcel change. The behavior are the same on the lastest version.

**Comment by perlun** [comment]
Thanks for all the feedback. :pray: This does seem to be a real issue with following the docs with Yarn then. :thinking:  

(I ended up skipping Parcel for my (very simple, rudimentary) project. I detest Node.js anyway. :wink: :see_no_evil:)

**Comment by hrynevychroman** [comment]
In conclusion to this, i think Parcel need to update docs to install @parcel/core in dev dependencies too)

**Comment by Kuinox** [comment]
> In conclusion to this, i think Parcel need to update docs to install @parcel/core in dev dependencies too)

As I said, it doesn't solve the issue on larger projects.

**Comment by wojtekmaj** [comment]
FYI, Yarn's own E2Es are also broken because of this: https://github.com/yarnpkg/berry/actions/runs/5794322982/job/15703692932

**Comment by blutorange** [comment]
I agree that the proper solution is to fix the dependencies in the corresponding packages. What you can do as a *workaround* is to use yarn's [package extension](https://yarnpkg.com/configuration/yarnrc#packageExtensions) mechanism, e.g. by putting something like the following into your `.yarnrc.yml`

```yaml
packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.9.3
```

For projects with multiple workspaces, this applies the extensions to all of them.

You might need to add `@parcel/core` to `@parcel/types` as well, if you use that, as I'm getting a warning here as well:

```sh
➤ YN0002: │ @parcel/types@npm:2.9.3 doesn't provide @parcel/core (pf46c3), requested by @parcel/fs
➤ YN0002: │ @parcel/types@npm:2.9.3 doesn't provide @parcel/core (p16f90), requested by @parcel/workers
➤ YN0002: │ @parcel/types@npm:2.9.3 doesn't provide @parcel/core (p385c8), requested by @parcel/cache
➤ YN0002: │ @parcel/types@npm:2.9.3 doesn't provide @parcel/core (p76fb9), requested by @parcel/package-manager
```

**Comment by olivier-spinelli** [comment]
Any progress on this? I'm stuck.
Tried the:
```
packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.9.3
```
No luck.

**Comment by perlun** [comment]
@olivier-spinelli Sorry to hear that. What's the error you're seeing, the same as in my original issue description?

**Comment by olivier-spinelli** [comment]
Sorry for the delayed answer.
Yes, it's the same peer dependency error. I've been forced to switch to Vite.

**Comment by dsimonov-lionsgatewt** [comment]
[TEMP SOLUTION] I had to create .yarnrc.yml file in the root of my project and add the following in it:
```yaml
packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.9.3
  "@parcel/types@*":
    dependencies:
      "@parcel/core": 2.9.3
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": 2.9.3
```
Save file and run `yarn install` a few times
Try building again

My package.js devDependencies looks like this now (ignore the packager-raw-url, transformer-webmanifest):
```
"devDependencies": {
    "@parcel/packager-raw-url": "2.11.0",
    "@parcel/transformer-webmanifest": "2.11.0",
    "parcel": "^2.11.0"
  }
```
Everything works now. Hope it helps someone.

**Comment by bartek-szymanski** [comment]
In my case I don't have this issue after switching to `npm`.

**Comment by puresick** [comment]
Just preventing the Bot from closing this issue.
It still happens.

**Comment by yezhiyi9670** [comment]
I am having this error after adding parcel and `@parcel/config-default` as dependencies.

```plain
@parcel/package-manager: Could not find module "@parcel/reporter-dev-server", but it was listed in package.json. Run your package manager first.

[redacted]\Yarn\Berry\cache\@parcel-config-default-npm-2.13.0-c9e25435a7-10c0.zip\node_modules\@parcel\config-default\package.json:35:5
  34 |     "@parcel/packager-wasm": "2.13.0",
> 35 |     "@parcel/reporter-dev-server": "2.13.0",
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Defined here, but not installed
  36 |     "@parcel/resolver-default": "2.13.0",
  37 |     "@parcel/runtime-browser-hmr": "2.13.0",
```

Extending dependencies for `@parcel/package-manager` `@parcel/config-default`, or adding `@parcel/reporter-dev-server` does not work.

**Comment by davidrhoderick** [comment]
So about 2 weeks ago, I was able to get this work in an npm workspace without issue.  Today, I am doing the same thing with yarn and I'm getting this error:
```
🚨 Build failed.

@parcel/core: Failed to resolve 'types/src/index.js' 
@parcel/resolver-default: @parcel/fs tried to access @parcel/core (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: @parcel/core
Required by: @parcel/fs@virtual:8ddf9e16b58a94c138a5ebf85978913b872a59eeb779a2755b23737abc031a12c92515e5e8c24f2b97294b0c59b417f45b38dab937acf99f6e958ee4bdbc980a#npm:2.13.2 (via 
/home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/@parcel-fs-virtual-5a7f1f1b41/3/.yarn/berry/cache/@parcel-fs-npm-2.13.2-946fd3b299-10c0.zip/node_modules/@parcel/fs/lib/)

Ancestor breaking the chain: @parcel/node-resolver-core@npm:3.4.2


Require stack:
- 
/home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/@parcel-fs-virtual-5a7f1f1b41/3/.yarn/berry/cache/@parcel-fs-npm-2.13.2-946fd3b299-10c0.zip/node_modules/@parcel/fs/lib/index.js
- /home/davidr/.yarn/berry/cache/@parcel-node-resolver-core-npm-3.4.2-8ddf9e16b5-10c0.zip/node_modules/@parcel/node-resolver-core/lib/Wrapper.js
- /home/davidr/.yarn/berry/cache/@parcel-node-resolver-core-npm-3.4.2-8ddf9e16b5-10c0.zip/node_modules/@parcel/node-resolver-core/lib/index.js
- 
/home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/@parcel-package-manager-virtual-758d0983dc/3/.yarn/berry/cache/@parcel-package-manager-npm-2.13.2-bf1cdabec3-10c0.zip/node_modules/@parcel/package-manager/lib/index.js
- /home/davidr/.yarn/berry/cache/@parcel-core-npm-2.13.2-ef6ed01569-10c0.zip/node_modules/@parcel/core/lib/resolveOptions.js
- /home/davidr/.yarn/berry/cache/@parcel-core-npm-2.13.2-ef6ed01569-10c0.zip/node_modules/@parcel/core/lib/Parcel.js
- /home/davidr/.yarn/berry/cache/@parcel-core-npm-2.13.2-ef6ed01569-10c0.zip/node_modules/@parcel/core/lib/index.js
- /home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/parcel-virtual-53825f4f8b/3/.yarn/berry/cache/parcel-npm-2.13.2-58f729bd64-10c0.zip/node_modules/parcel/lib/cli.js
- /home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/parcel-virtual-53825f4f8b/3/.yarn/berry/cache/parcel-npm-2.13.2-58f729bd64-10c0.zip/node_modules/parcel/lib/bin.js

  Error: @parcel/fs tried to access @parcel/core (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
  
  Required package: @parcel/core
  Required by: @parcel/fs@virtual:8ddf9e16b58a94c138a5ebf85978913b872a59eeb779a2755b23737abc031a12c92515e5e8c24f2b97294b0c59b417f45b38dab937acf99f6e958ee4bdbc980a#npm:2.13.2 (via 
  /home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/@parcel-fs-virtual-5a7f1f1b41/3/.yarn/berry/cache/@parcel-fs-npm-2.13.2-946fd3b299-10c0.zip/node_modules/@parcel/fs/lib/)
  
  Ancestor breaking the chain: @parcel/node-resolver-core@npm:3.4.2
  
  
  Require stack:
  - 
  /home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/@parcel-fs-virtual-5a7f1f1b41/3/.yarn/berry/cache/@parcel-fs-npm-2.13.2-946fd3b299-10c0.zip/node_modules/@parcel/fs/lib/index.js
  - /home/davidr/.yarn/berry/cache/@parcel-node-resolver-core-npm-3.4.2-8ddf9e16b5-10c0.zip/node_modules/@parcel/node-resolver-core/lib/Wrapper.js
  - /home/davidr/.yarn/berry/cache/@parcel-node-resolver-core-npm-3.4.2-8ddf9e16b5-10c0.zip/node_modules/@parcel/node-resolver-core/lib/index.js
  - 
  /home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/@parcel-package-manager-virtual-758d0983dc/3/.yarn/berry/cache/@parcel-package-manager-npm-2.13.2-bf1cdabec3-10c0.zip/node_modules/@parcel/package-manager/lib/index.js
  - /home/davidr/.yarn/berry/cache/@parcel-core-npm-2.13.2-ef6ed01569-10c0.zip/node_modules/@parcel/core/lib/resolveOptions.js
  - /home/davidr/.yarn/berry/cache/@parcel-core-npm-2.13.2-ef6ed01569-10c0.zip/node_modules/@parcel/core/lib/Parcel.js
  - /home/davidr/.yarn/berry/cache/@parcel-core-npm-2.13.2-ef6ed01569-10c0.zip/node_modules/@parcel/core/lib/index.js
  - /home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/parcel-virtual-53825f4f8b/3/.yarn/berry/cache/parcel-npm-2.13.2-58f729bd64-10c0.zip/node_modules/parcel/lib/cli.js
  - /home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/parcel-virtual-53825f4f8b/3/.yarn/berry/cache/parcel-npm-2.13.2-58f729bd64-10c0.zip/node_modules/parcel/lib/bin.js
      at require$$0.Module._resolveFilename (/home/davidr/Development/bts-schema-sharing-demo/.pnp.cjs:13179:13)
      at Function.<anonymous> (node:internal/modules/cjs/loader:1075:27)
      at require$$0.Module._load (/home/davidr/Development/bts-schema-sharing-demo/.pnp.cjs:13070:31)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
      at Module.require (node:internal/modules/cjs/loader:1340:12)
      at require (node:internal/modules/helpers:141:16)
      at Object.<anonymous> 
  (/home/davidr/Development/bts-schema-sharing-demo/.yarn/__virtual__/@parcel-fs-virtual-5a7f1f1b41/3/.yarn/berry/cache/@parcel-fs-npm-2.13.2-946fd3b299-10c0.zip/node_modules/@parcel/fs/lib/index.js:6:25)
      at Module._compile (node:internal/modules/cjs/loader:1546:14)
      at Object.<anonymous> (node:internal/modules/cjs/loader:1689:10)
```
Here are the commands I ran:
```
mkdir types
cd types
npm init // named it correctly
cd ../
// I created my `src/index.js`
// I updated the package.json from the documentation
yarn workspace types add parcel @parcel/core // I tried without adding @parcel/core as well
yarn workspace types run build
```
I'll try to get you a reproduction but you can just follow the steps here, most of which are based off of the documentation of this project and some tips from this issue.  I was really loving parcel until running into this...

**Comment by blutorange** [comment]
`@parcel/fs` declares a peer dependency on `@parcel/core` [here](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/fs/package.json#L70). Making it a normal dependency would solve the issue. The reason why that's not being done I guess is because `@parcel/core` [also depends on](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/core/package.json#L32) `@parcel/fs`, which creates a circular dependency. So to properly solve this issue, the packages would probably needed to be refactored first to solve the circular dependency.

**Comment by AntonRich** [comment]
@hrynevychroman  Thanks, your solution worked for me.

**Comment by raffaeldp** [comment]
Any news on that ? The issue is still existing !
I have used yarn4 and simply followed the getting started guide to build a library.

However installing @parcel/core as mentioned before has fixed the issue for me.

It's a bit frustrating when you follow the getting started documentation and it just don't work ! Maybe this should be added to the documentation ? (quickest fix).
Thx everyone :)

**Comment by wojtekmaj** [comment]
Bad bot

**Comment by ckiyme** [comment]
Commenting because this is still an issue. I wanted to try `yarn` and Parcel for the first time and I ended up here 😢

**Comment by dsimonov-lionsgatewt** [comment]
> Commenting because this is still an issue. I wanted to try `yarn` and Parcel for the first time and I ended up here 😢

I simply stopped using yarn. npm is good enough these days.
