### ISSUE TITLE
Error while bundling JS file (sapphireEditorDriver.js:61 Uncaught Error: Cannot find module '@babel/runtime/helpers/defineProperty')

### ISSUE THREAD

**Issue by happysamyak** [parcel-bundler/parcel#9217]
Hi Team,

I am facing the issue while running yarn build with the parcel.

sapphireEditorDriver.js:61 Uncaught Error: Cannot find module '@babel/runtime/helpers/defineProperty'
    at newRequire (sapphireEditorDriver.js:61:19)
    at newRequire (sapphireEditorDriver.js:45:18)
    at localRequire (sapphireEditorDriver.js:84:35)
    at efHPv.@babel/runtime/helpers/defineProperty (sapphireEditorDriver.js:685:23)
    at newRequire (sapphireEditorDriver.js:71:24)
    at localRequire (sapphireEditorDriver.js:84:35)
    at dYHCi.../config/global (sapphireEditorDriver.js:339:15)
    at newRequire (sapphireEditorDriver.js:71:24)
    at localRequire (sapphireEditorDriver.js:84:35)
    at a03Sd.../utils/manifest (sapphireEditorDriver.js:165:17)

    "parcel": "2.9.3",
     "@exc/parcel-namer": "0.0.6",
     "@parcel/transformer-less": "2.8.3",
     "@babel/cli": "7.21.0",
    "@babel/core": "7.21.4",
    "@babel/node": "7.20.7",
    "@babel/plugin-proposal-class-properties": "7.18.6",
    "@babel/plugin-proposal-export-default-from": "7.18.10",
    "@babel/plugin-syntax-dynamic-import": "7.8.3",
    "@babel/plugin-transform-runtime": "7.21.4",
    "@babel/preset-env": "7.21.4",
    "@babel/preset-react": "7.18.6",
    "@babel/preset-typescript": "7.21.4",

<img width="1792" alt="image" src="https://github.com/parcel-bundler/parcel/assets/12069006/0c49d292-9215-4a98-b13a-04d2e060380e">

**Comment by danieltroger** [comment]
Are you sure you have `@babel/runtime` installed/in your package.json?
