### ISSUE TITLE
Parcel v2 generates several JS files which cannot be ran by node

### ISSUE THREAD

**Issue by declanelcocks** [parcel-bundler/parcel#9259]
# 🐛 bug report

In the past I was using Parcel v1 along with `parcel-plugin-run-server` (not necessarily relevant but just giving some context) to build a `dist` output of a TypeScript Node.js backend and run it. The options were quite simple:

```
const options = {
  outDir: './dist',
  outFile: 'main.js',
  publicUrl: './',
  watch: true,
  cache: true,
  cacheDir: '.cache',
  contentHash: false,
  minify: false,
  scopeHoist: false,
  target: 'node',
  bundleNodeModules: false,
  logLevel: 3,
  sourceMaps: true,
  detailedReport: false,
  autoInstall: true,
};
```

This would generate some static files and one, big `dist/main.js` file that the plugin could run using `node dist/main.js`. I've tried to copy these options across to Parcel v2 with:

```
{
    entries: entryFiles,
    shouldDisableCache: false,
    shouldContentHash: false,
    shouldAutoInstall: true,
    mode: 'development',
    logLevel: 'error',
    targets: {
      default: {
        context: 'node',
        publicUrl: './',
        distDir: './dist',
        distEntry: 'main.js',
        optimize: false,
        scopeHoist: false,
        includeNodeModules: false,
        sourceMap: true,
      },
    },
  }
```

This will build `dist/main.js` but it will also build several other files like `main.5c9552c8.js`. This itself is fine, I guess it's code splitting the bundles as the docs explain, but when running `node dist/main.js` it now results in this error:

```
node:internal/modules/cjs/loader:1026
  const err = new Error(message);
              ^

Error: Cannot find module '9vinu'
Require stack:
- /Users/<REPO_PATH>/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at newRequire (/Users/<REPO_PATH>/dist/main.js:58:18)
    at newRequire (/Users/<REPO_PATH>/dist/main.b8135af0.js:53:18)
    at newRequire (/Users/<REPO_PATH>/dist/main.b8135af0.js:45:18)
    at localRequire (/Users/<REPO_PATH>/dist/main.b8135af0.js:84:35)
    at Object.aE43U.a48566ca5e2ae079 (/Users/<REPO_PATH>/dist/main.b8135af0.js:151:20)
    at newRequire (/Users/<REPO_PATH>/dist/main.b8135af0.js:71:24)
    at /Users/<REPO_PATH>/dist/main.b8135af0.js:122:5 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/<REPO_PATH>/dist/main.js' ]
}
```

Can I configure Parcel to output a single JS file? Or is there something else I'm missing? Nothing else in the repo has changed.

Thanks 🙏 

(Seems similar to https://github.com/parcel-bundler/parcel/issues/5683)

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`
```
{
  "extends": [
    "@parcel/config-default"
  ],
  "reporters":  [
    "...",
    "parcel-reporter-static-files-copy"
  ]
}
```

Relevant `package.json`
```
"main": "dist/main.js",
```

`.babelrc`
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "@babel/preset-typescript"
  ],
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    [
      "@babel/proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "@babel/proposal-class-properties",
      { "loose": true },
      "@babel/plugin-proposal-class-properties-loose"
    ],
    [
      "@babel/plugin-proposal-private-methods",
      { "loose": true },
      "@babel/plugin-proposal-private-methods-loose"
    ],
    ["@babel/plugin-proposal-private-property-in-object", { "loose": true }],
    [
      "module-resolver",
      {
        "alias": {
          "@some_alias": "....."
        },
        "root": ["./src"],
        "extensions": [".js", ".jsx", ".ts", ".tsx"]
      }
    ],
    [
      "transform-inline-environment-variables",
      {
        "exclude": ["PORT", "TEST_DEPLOYMENT_TARGET", "TEST_ENV_TARGET"]
      }
    ]
  ]
}

```

## 🤔 Expected Behavior

Running `node dist/main.js` on the built output fails.

**Comment by ChristophP** [comment]
I'm also seeing this error about not finding modules.
It happens in the browser during when I run `parcel serve`. `parcel build` completes just fine.

![grafik](https://github.com/parcel-bundler/parcel/assets/5880236/8ed8d686-5ab6-434e-a1d9-601733819919)

It shows up for versions 2.9.0 - 2.9.3.
For 2.8.3 everything works as expected.

**Comment by declanelcocks** [comment]
For what it's worth downgrading to `2.8.3` makes no difference for my use case, although I'm guessing the root cause could be similar given how your error looks.

**Comment by mischnic** [comment]
Please provide a (small) complete code sample that reproduces the issue.
