### ISSUE TITLE
SyntaxError: Unexpected token '(' at @parcel/utils/lib/index.js:37573

### ISSUE THREAD

**Issue by pbogre** [parcel-bundler/parcel#9279]
# 🐛 bug report

im trying to package a vue project into a single html file to serve that to the backend that handles requests. everything is running in docker, and it runs successfully when i do it from my main os (macos), but when i run it while building the docker image i get the error shown.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```json
{
  "name": "mybrary",
  "version": "0.1.0",
  "scripts": {
    "build": "parcel build mybrary/src/index.html --dist-dir mybrary/dist",
    "watch": "parcel mybrary/src/index.html --dist-dir mybrary/dist"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "3.3.0",
    "axios": "1.5.1",
    "bootstrap-vue": "2.23.0",
    "parcel": "2.0.0",
    "vue-hot-reload-api": "2.3.4",
    "vue-template-compiler": "2.7.14"
  }
}
```
`Dockerfile`
```docker
ARG BUILD_PATH=/build
FROM --platform=$BUILDPLATFORM python:3.11-slim-bullseye AS build

ARG BUILD_PATH

RUN mkdir ${BUILD_PATH}
WORKDIR ${BUILD_PATH}

RUN apt update && apt install -y npm
COPY package.json package-lock.json ./
RUN npm ci

COPY mybrary/src ./mybrary/src
RUN npm run build
```

## 🤔 Expected Behavior

Image is built successfully and packages the vue project into a single html file at `/build/mybrary/dist/index.html`

## 😯 Current Behavior

I get the following error while building the image
```

0.307 > mybrary@0.1.0 build
0.307 > parcel build mybrary/src/index.html --dist-dir mybrary/dist
0.307
0.404 /build/node_modules/@parcel/utils/lib/index.js:37573
0.404     #getIndex(item) {
0.404              ^
0.404 SyntaxError: Unexpected token '('
0.404     at new Script (vm.js:88:7)
0.404     at NativeCompileCache._moduleCompile (/build/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
0.404     at Module._compile (/build/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
0.404     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
0.404     at Module.load (internal/modules/cjs/loader.js:863:32)
0.404     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
0.404     at Module.require (internal/modules/cjs/loader.js:887:19)
0.404     at require (/build/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
0.404     at _utils (/build/node_modules/@parcel/core/lib/public/Config.js:22:16)
0.404     at Object.<anonymous> (/build/node_modules/@parcel/core/lib/public/Config.js:31:37)
0.517 npm ERR! code 1
0.517 npm ERR! path /build
0.519 npm ERR! command failed
0.519 npm ERR! command sh -c parcel build mybrary/src/index.html --dist-dir mybrary/dist
```

**Comment by mischnic** [comment]
Looks like the Node version in your Docker image is too old for private methods.

**Comment by pbogre** [comment]
fixed by using the `node:bullseye-slim` image (instead of `python:3.11-slim-bullseye` and then installing node from there)
