### ISSUE TITLE
Runtime error in development builds but not production

### ISSUE THREAD

**Issue by cgauld** [parcel-bundler/parcel#9450]
I've got an interesting case of a project that has a runtime error in development builds but not production builds. I've been able to create a minimal example that demonstrates the issue:
[Archive.zip](https://github.com/parcel-bundler/parcel/files/13714803/Archive.zip)

It's triggered in this project using the  React Markdown library. Doing a bit of digging into it I do believe it's a Parcel bug although my understanding of the workings of Parcel mean that I can't be 100% sure. It looks like there's an issue with a dependency chain that should resolve to a const exported from a module within a package. In development mode, the const ends up undefined, and indeed no source map for the module appears in the browser at runtime. Here's the stack trace:
```
index.js:874 Uncaught TypeError: Cannot read properties of undefined (reading 'href')
    at createProperty (index.js:874:20)
    at createElementProps (index.js:691:22)
    at element (index.js:439:17)
    at one (index.js:391:12)
    at createChildren (index.js:823:20)
    at element (index.js:440:18)
    at one (index.js:391:12)
    at createChildren (index.js:823:20)
    at root (index.js:560:22)
    at one (index.js:407:12)
    at toJsxRuntime (index.js:361:18)
    at Markdown (index.js:225:21)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)
```

Note, this package has a dependency that requires the Parcel setting for supporting package exports - not sure if that's related or not:
```
  "@parcel/resolver-default": {
    "packageExports": true
  }
```

I've been able to replicate this issue both with 2.10.3 and 2.9 (the first version to support package exports).

**Comment by AntonKrutikov** [comment]
Same behaviour for me, not found cause for now.

**Comment by ManishMadan2882** [comment]
Facing same issues in React Markdown only with Parcel.

**Comment by will8211** [comment]
Facing this as well. Does anyone know of a workaround?

**Comment by Joeoeoe** [comment]
Facing this as well

**Comment by drewwestphal** [comment]
Me too. Has anyone found a way around it?
