### ISSUE TITLE
[build] import syntax in dist file failed when building nodejs app

### ISSUE THREAD

**Issue by mister-good-deal** [parcel-bundler/parcel#9456]
# 🐛 bug report

When building a nodejs app (for production), the generated `index.mjs` fails to import some nodejs lib because of a broken `import` syntax trying to find a non existing name.

The generated `module.js` by the build step works fine.

## 🎛 Configuration (.babelrc, package.json, cli command)

**package.json**

```json
{
    "name": "slack",
    "version": "0.0.2",
    "private": true,
    "main": "dist/index.mjs",
    "source": "src/index.ts",
    "types": "dist/index.d.ts",
    "module": "dist/module.js",
    "targets": {
        "main": {
            "includeNodeModules": true,
            "optimize": false
        }
    },
    "engines": {
        "node": ">= 18"
    },
    "scripts": {
        "prepare": "husky install",
        "start": "ts-node --esm src/index.ts",
        "type-check": "tsc --noEmit",
        "style-check": "prettier --check src/**/*.ts",
        "style-fix": "prettier --write src/**/*.ts",
        "lint-report": "eslint src --format gitlab --output-file gl-code-quality-report.json --ext .ts --ignore-path .gitignore",
        "lint-check": "eslint src --ext .ts --ignore-path .gitignore --max-warnings 0 --report-unused-disable-directives",
        "lint-fix": "eslint src --ext .ts --fix --ignore-path .gitignore",
        "test:unit": "jest --reporters=jest-junit",
        "test:unit:coverage": "jest --reporters=jest-junit --coverage ",
        "build": "parcel build --no-scope-hoist",
        "postinstall": "cp monkey-patch/prisma/index.js node_modules/@prisma/client/index.js"
    },
    "lint-staged": {
        "*.{ts,js}": [
            "prettier --write",
            "eslint --fix"
        ],
        "*.{json,md}": [
            "prettier --write"
        ]
    },
    "packageManager": "yarn@4.0.1",
    "type": "module",
    "dependencies": {
        "@gitbeaker/rest": "^39.25.0",
        "@prisma/client": "^5.7.1",
        "@slack/bolt": "^3.14.0",
        "@slack/web-api": "^6.9.1",
        "axios": "^1.6.2",
        "dotenv": "^16.3.1",
        "lodash-es": "^4.17.21",
        "openai": "^4.16.1"
    },
    "devDependencies": {
        "@parcel/packager-ts": "2.10.3",
        "@parcel/transformer-typescript-types": "2.10.3",
        "@types/jest": "^29.5.10",
        "@types/lodash": "^4",
        "@types/lodash-es": "^4",
        "@types/node": "^20.10.5",
        "@typescript-eslint/eslint-plugin": "^6.10.0",
        "@typescript-eslint/parser": "^6.10.0",
        "eslint": "^8.53.0",
        "eslint-config-prettier": "^9.0.0",
        "eslint-formatter-gitlab": "^5.1.0",
        "husky": "^8.0.3",
        "jest": "^29.7.0",
        "jest-junit": "^16.0.0",
        "jest-mock-extended": "^3.0.5",
        "lint-staged": "^15.1.0",
        "lodash": "^4.17.21",
        "parcel": "^2.10.3",
        "prettier": "3.1.0",
        "prisma": "^5.7.1",
        "ts-jest": "^29.1.1",
        "ts-node": "^10.9.1",
        "typescript": "^5.2.2"
    }
}
```

## 🤔 Expected Behavior

```sh
node /app/dist/index.mjs
```

Should run successfully.

## 😯 Current Behavior
The following command fails

```
node dist/index.js
file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:2570
var $77dea8ba1dcdc1ea$require$Stream = $54RfL$Stream;
                                       ^

ReferenceError: $54RfL$Stream is not defined
    at Object.<anonymous> (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:2570:40)
    at parcelRequire (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:53:12)
    at Object.<anonymous> (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:2231:14)
    at parcelRequire (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:53:12)
    at Object.<anonymous> (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:2225:14)
    at parcelRequire (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:53:12)
    at Object.<anonymous> (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:1975:14)
    at parcelRequire (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:53:12)
    at Object.<anonymous> (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:1915:14)
    at parcelRequire (file:///home/rom1/Projects/ai-project-team/slack/dist/index.js:53:12)

Node.js v18.17.1
```

Generated files from `build` step:

**index.mjs**

```js
import $54RfL$util, * as $54RfL$util1 from "util";
import * as $54RfL$path from "path";
import $54RfL$http, * as $54RfL$http1 from "http";
import $54RfL$https, * as $54RfL$https1 from "https";
import $54RfL$url, {parse as $54RfL$parse, URL as $54RfL$URL, format as $54RfL$format, resolve as $54RfL$resolve, URLSearchParams as $54RfL$URLSearchParams, Url as $54RfL$Url} from "url";
import * as $54RfL$fs from "fs";
import $54RfL$stream, * as $54RfL$stream1 from "stream";
import $54RfL$zlib, * as $54RfL$zlib1 from "zlib";
import $54RfL$events, * as $54RfL$events1 from "events";
import * as $54RfL$assert from "assert";
import * as $54RfL$tty from "tty";
import * as $54RfL$os from "os";
import * as $54RfL$querystring from "querystring";
import * as $54RfL$net from "net";
import {connect as $54RfL$connect1} from "tls";
import $54RfL$crypto1, * as $54RfL$crypto from "crypto";
import * as $54RfL$buffer from "buffer";
import {StringDecoder as $54RfL$StringDecoder} from "string_decoder";
import * as $54RfL$child_process from "child_process";
import * as $54RfL$fspromises from "fs/promises";
import {AsyncResource as $54RfL$AsyncResource} from "async_hooks";

// ...

var $22dca5120340fe66$require$Stream = $54RfL$Stream; // Error here
```

**module.js**

```js
import $lSd6q$slackbolt from "@slack/bolt";
import {OpenAI as $lSd6q$OpenAI} from "openai";
import $lSd6q$dotenv from "dotenv";
import $lSd6q$axios from "axios";
import {partial as $lSd6q$partial, find as $lSd6q$find, isObject as $lSd6q$isObject, has as $lSd6q$has, kebabCase as $lSd6q$kebabCase} from "lodash-es";
import {WebClient as $lSd6q$WebClient} from "@slack/web-api";
import {PrismaClient as $lSd6q$PrismaClient} from "@prisma/client";
import $lSd6q$crypto from "crypto";
import {createServer as $lSd6q$createServer} from "http";

// ...
```

## 💁 Possible Solution

Some config addition ?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.10.3
| Node             | Node.js v18.17.1
| npm/Yarn         | Yarn 4.0.1
| Operating System | Ubuntu 20.04

**Comment by mister-good-deal** [comment]
Is there someting I'm missing?

I just want to package my app into a single js node executable file `index.mjs` containing all the required js dependencies without the need of running `yarn` or `npm install` in the target environnement.

To achieve this I used the Parcel option `includeNodeModules` to include deps in the build:

```json
{
    "targets": {
        "main": {
            "includeNodeModules": true
        }
    }
 }
```

Are there some not mentioned other packages to install (some node utility packages) manually to make this work?

The error comes from the following import where `$54RfL$stream` is undefined while it should come from nodejs `node:stream` lib (if the internal parcel string replacement is correct).

```js
import $54RfL$stream, * as $54RfL$stream1 from "stream";
```

**Comment by mischnic** [comment]
This should be working.

What does your source code look like which uses that stream import?

**Comment by mister-good-deal** [comment]
@mischnic Actually there is no direct use of stream in my source code, neither import statement for node:stream.

Some libs deps could use stream internally like Slack WebAPI. I can look for that

**Comment by mister-good-deal** [comment]
Ok I found out that [openAI](https://github.com/openai/openai-node) lib is using `node:stream`.

**openai/_shims/node-runtime.js** [source in TS here](https://github.com/openai/openai-node/blob/master/src/_shims/node-runtime.ts)

```js
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getRuntime = void 0;
/**
 * Disclaimer: modules in _shims aren't intended to be imported by SDK users.
 */
const nf = __importStar(require("node-fetch"));
const fd = __importStar(require("formdata-node"));
const agentkeepalive_1 = __importDefault(require("agentkeepalive"));
const abort_controller_1 = require("abort-controller");
const node_fs_1 = require("node:fs");
const form_data_encoder_1 = require("form-data-encoder");
const node_stream_1 = require("node:stream");
const MultipartBody_1 = require("./MultipartBody.js");
// @ts-ignore (this package does not have proper export maps for this export)
const ponyfill_es2018_js_1 = require("web-streams-polyfill/dist/ponyfill.es2018.js");
let fileFromPathWarned = false;
async function fileFromPath(path, ...args) {
    // this import fails in environments that don't handle export maps correctly, like old versions of Jest
    const { fileFromPath: _fileFromPath } = await Promise.resolve().then(() => __importStar(require('formdata-node/file-from-path')));
    if (!fileFromPathWarned) {
        console.warn(`fileFromPath is deprecated; use fs.createReadStream(${JSON.stringify(path)}) instead`);
        fileFromPathWarned = true;
    }
    // @ts-ignore
    return await _fileFromPath(path, ...args);
}
const defaultHttpAgent = new agentkeepalive_1.default({ keepAlive: true, timeout: 5 * 60 * 1000 });
const defaultHttpsAgent = new agentkeepalive_1.default.HttpsAgent({ keepAlive: true, timeout: 5 * 60 * 1000 });
async function getMultipartRequestOptions(form, opts) {
    const encoder = new form_data_encoder_1.FormDataEncoder(form);
    const readable = node_stream_1.Readable.from(encoder);
    const body = new MultipartBody_1.MultipartBody(readable);
    const headers = {
        ...opts.headers,
        ...encoder.headers,
        'Content-Length': encoder.contentLength,
    };
    return { ...opts, body: body, headers };
}
function getRuntime() {
    // Polyfill global object if needed.
    if (typeof AbortController === 'undefined') {
        // @ts-expect-error (the types are subtly different, but compatible in practice)
        globalThis.AbortController = abort_controller_1.AbortController;
    }
    return {
        kind: 'node',
        fetch: nf.default,
        Request: nf.Request,
        Response: nf.Response,
        Headers: nf.Headers,
        FormData: fd.FormData,
        Blob: fd.Blob,
        File: fd.File,
        ReadableStream: ponyfill_es2018_js_1.ReadableStream,
        getMultipartRequestOptions,
        getDefaultAgent: (url) => (url.startsWith('https') ? defaultHttpsAgent : defaultHttpAgent),
        fileFromPath,
        isFsReadStream: (value) => value instanceof node_fs_1.ReadStream,
    };
}
exports.getRuntime = getRuntime;
//# sourceMappingURL=node-runtime.js.map
```

[Prisma client](https://github.com/prisma/prisma/tree/main) is also using `stream` in its [source code](https://github.com/prisma/prisma/blob/main/packages/generator-helper/src/GeneratorProcess.ts).
