### ISSUE TITLE
@parcel/transformer-vue fails to compile

### ISSUE THREAD

**Issue by 0x1af2aec8f957** [parcel-bundler/parcel#9457]
```bash
# parcel build --no-optimize --no-cache --no-source-maps --log-level='error' --dist-dir='./build'

yarn run v1.22.21
$ parcel build --no-optimize --no-cache --no-source-maps --log-level='error' --dist-dir='./build'
(node:34376) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
🚨 Build failed.

@parcel/transformer-vue: "version" is a required argument.

  Error: "version" is a required argument.
      at Object.getArg (@workDir/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:8208:12)
      at new BasicSourceMapConsumer (@workDir/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:9841:24)
      at new SourceMapConsumer$1 (@workDir/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:9569:7)
      at merge (@workDir/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:11140:24)
      at scss (@workDir/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:11204:14)
      at preprocess (@workDir/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:15405:10)
      at doCompileStyle (@workDir/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:15312:46)
      at Object.compileStyleAsync (@workDir/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:15293:10)
      at @workDir/node_modules/@parcel/transformer-vue/lib/VueTransformer.js:378:44
      at Array.map (<anonymous>)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

https://github.com/parcel-bundler/parcel/blob/cf5e1293009fbbb812eca8bc607fee7906de2da3/packages/transformers/vue/package.json#L27

The latest version of `parcel` cannot be compiled successfully. After investigation, it is caused by parameter changes after the upgrade of `@vue/compiler-sfc`.

Temporary solution:

```
# @workDir/package.json
...
"resolutions": {
    "@vue/compiler-sfc": "3.2.27"
  },
...
```

**Comment by mischnic** [comment]
So yet another breaking change just like https://github.com/parcel-bundler/parcel/issues/9405...
