### ISSUE TITLE
Error: Does not have node XXXX when executing parcel build

### ISSUE THREAD

**Issue by isitgeorge** [parcel-bundler/parcel#9464]
# 🐛 bug report

I seem to randomly get the error `Error: Does not have node XXXX` when executing `parcel build`. It happens mostly in the build pipeline within CircleCI and doesn't have reproducible steps - for example a scheduled build will run successfully today but tomorrow it will fail with this error (building same commit/revision).

```
Error: Does not have node 5298
    at AssetGraph._assertHasNodeId (/home/circleci/repo/service-ui/node_modules/@parcel/graph/lib/Graph.js:405:13)
    at AssetGraph.getNodeIdsConnectedFrom (/home/circleci/repo/service-ui/node_modules/@parcel/graph/lib/Graph.js:82:10)
    at visitChildren (/home/circleci/repo/service-ui/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:147:47)
    at /home/circleci/repo/service-ui/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:143:67

Exited with code exit status 1
```

`5298` is not consistent and changes. For example:

```
Error: Does not have node 2301
    at AssetGraph._assertHasNodeId (/home/circleci/repo/service-ui/node_modules/@parcel/graph/lib/Graph.js:405:13)
    at AssetGraph.getNodeIdsConnectedFrom (/home/circleci/repo/service-ui/node_modules/@parcel/graph/lib/Graph.js:82:10)
    at visitChildren (/home/circleci/repo/service-ui/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:147:47)
    at /home/circleci/repo/service-ui/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:143:67

Exited with code exit status 1
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "edge": "17",
          "firefox": "60",
          "chrome": "67",
          "safari": "11.1"
        },
        "useBuiltIns": "usage",
        "corejs": "3.6.5"
      }
    ]
  ]
}
```

## 🤔 Expected Behavior

`parcel build` should successfully execute

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.10.3
| Node             | 18.19
| npm/Yarn         | 10.2.3
| Operating System | Ubuntu (cimg/node:18.19)

I don't currently have a code example or MVP to reproduce the error as I believe it may be environmental, but I'm bit lost as to where to begin debugging. Does anybody know of anything obvious that may cause this before I start digging?

Cheers,
George

**Comment by Peta-S** [comment]
Hi George,
How did you go with resolving this issue?

I just faced the same issue after many previously successful builds.  

I deleted the .parcel-cache folder and that **fixed the issue.**

All the best
Peta
