### ISSUE TITLE
Failed to resolve '#supports-color'

### ISSUE THREAD

**Issue by TheAyes** [parcel-bundler/parcel#9481]
# 🐛 bug report

I'm developing a web extension and would like to use chalk for my fancy console logs. Unfortunately Parcel seems to not like chalk all too much. I'm unable to build due to a resolver error inside of chalk's codebase.

## 🎛 Configuration (.babelrc, package.json, cli command)
root package.json
```json
{
	"name": "@you-may-not-know/root",
	"version": "2.0.0",
	"private": true,
	"prettier": "@vercel/style-guide/prettier",
	"type": "module",
	"scripts": {
		"dev": "concurrently \"pnpm run dev:app\" \"pnpm run dev:styles\" ",
		"build": "concurrently \"pnpm run build:app\" \"pnpm run build:styles\" ",
		"build:app": "parcel build apps/extension/manifest.json --config @parcel/config-webextension",
		"dev:app": "parcel apps/extension/manifest.json --config @parcel/config-webextension --host localhost",
		"build:styles": "sass packages/restyle/styles:dist/styles",
		"dev:styles": "sass packages/restyle/styles:dist/styles --watch"
	},
	"dependencies": {
		"lodash": "^4.17.21"
	},
	"devDependencies": {
		"concurrently": "^8.2.2",
		"@digitak/esrun": "^3.2.26",
		"tsx": "^4.7.0",
		"@parcel/config-webextension": "^2.11.0",
		"@parcel/core": "^2.11.0",
		"@parcel/optimizer-data-url": "2.10.3",
		"@parcel/packager-ts": "2.10.3",
		"@parcel/transformer-inline-string": "2.10.3",
		"@parcel/transformer-sass": "2.11.0",
		"@types/lodash": "^4.14.202",
		"@types/node": "^20.10.8",
		"@types/parcel-env": "^0.0.5",
		"@vercel/style-guide": "^5.1.0",
		"babel-loader": "^9.1.3",
		"dotenv": "^16.3.1",
		"parcel": "^2.11.0",
		"prettier": "^3.1.1",
		"process": "^0.11.10",
		"typescript": "^5.3.3"
	},
	"overrides": {
		"svgo": "3.1.0"
	},
	"packageExports": true
}
```
project package.json
```json
{
	"name": "@you-may-not-know/debug",
	"type": "module",
	"main": "index.ts",
	"dependencies": {
		"chalk": "^5.3.0"
	}
}
```

## 🤔 Expected Behavior

I'd expect the server to keep running or the build to actually pass

## 😯 Current Behavior

Upon build (or dev) parcel throws the following error and fails:
```log
pnpm.cmd run dev:app
> you-may-not-know@2.0.0 dev:app C:\Projekte\you-may-not-know
> parcel apps/extension/manifest.json --config @parcel/config-webextension --host localhost

Server running at http://localhost:1234
× Build failed.

@parcel/core: Failed to resolve '#supports-color' from './node_modules/.pnpm/chalk@5.3.0/node_modules/chalk/source/index.js'

  C:\Projekte\you-may-not-know\node_modules\.pnpm\chalk@5.3.0\node_modules\chalk\source\index.js:2:27
    1 | import ansiStyles from '#ansi-styles';
  > 2 | import supportsColor from '#supports-color';
  >   |                           ^^^^^^^^^^^^^^^^^
    3 | import { // eslint-disable-line import/order
    4 |   stringReplaceAll,

@parcel/resolver-default: Cannot read properties of undefined (reading 'message')

  TypeError: Cannot read properties of undefined (reading 'message')
      at new ThrowableDiagnostic (C:\Projekte\you-may-not-know\node_modules\.pnpm\@parcel+diagnostic@2.11.0\node_modules\@parcel\diagnostic\lib\diagnostic.js:128:26)
      at ResolverRunner.resolve (C:\Projekte\you-may-not-know\node_modules\.pnpm\@parcel+core@2.11.0\node_modules\@parcel\core\lib\requests\PathRequest.js:296:72)
      at async Object.run (C:\Projekte\you-may-not-know\node_modules\.pnpm\@parcel+core@2.11.0\node_modules\@parcel\core\lib\requests\PathRequest.js:92:16)
      at async RequestTracker.runRequest (C:\Projekte\you-may-not-know\node_modules\.pnpm\@parcel+core@2.11.0\node_modules\@parcel\core\lib\RequestTracker.js:653:20)
      at async AssetGraphBuilder.runPathRequest (C:\Projekte\you-may-not-know\node_modules\.pnpm\@parcel+core@2.11.0\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:340:18)
      at async $31bd78e367586e0a$export$2e2bcd8739ae039._runFn (C:\Projekte\you-may-not-know\node_modules\.pnpm\@parcel+utils@2.11.0\node_modules\@parcel\utils\lib\index.js:34305:13)
      at async $31bd78e367586e0a$export$2e2bcd8739ae039._next (C:\Projekte\you-may-not-know\node_modules\.pnpm\@parcel+utils@2.11.0\node_modules\@parcel\utils\lib\index.js:34298:9)
```

## 💻 Code Sample

The Code that causes me this:
```ts
import chalk from "chalk";

const typeColorMap = {
	boolean: chalk.rgb(255, 120, 0),
	number: chalk.rgb(42, 171, 183),
	string: chalk.rgb(99, 145, 78),
	object: chalk.rgb(229, 181, 53)
};

const getArgColorCode = (arg: any) => typeColorMap[typeof arg];

export const printMessage = (fn: string, args: any[]) => {
	const header = chalk.rgb(255, 120, 60).bold.underline("RECEIVED - Message with signature:");
	const fnString = `${chalk.rgb(255, 120, 60)("function")}: ${chalk.blueBright(fn)}`;
	const argsString = `${chalk.rgb(255, 120, 60)("args")}: ${args.reduce((accumulator, currentValue, index) => {
		return `${accumulator}\n  arg${index}: ${chalk.rgb(255, 120, 60)(typeof currentValue)} = ${getArgColorCode(currentValue)(currentValue)}`;
	}, "")}`;

	console.log(`${header}\n${fnString}\n${argsString}`);
};
printMessage("Test", [true, false, { key: "oof" }, [1, 2, 3], "Hello World!"]);
```
Haven't tested with simpler cases yet. Might add that later.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.11.0 |
| Node             | 18.18.0 |
| pnpm         | 8.12.0 |
| Operating System | Windows 10 x64 |

**Comment by mischnic** [comment]
You need to do
```json5
{
  //  ...
  "overrides": {
    "svgo": "3.1.0"
  },
  "@parcel/resolver-default": {
    "packageExports": true
  }
}
```
and not
```json5
{
  //  ...
  "overrides": {
    "svgo": "3.1.0"
  },
  "packageExports": true
}
```

**Comment by TheAyes** [comment]
That did indeed help thanks :) I may need to open an issue at concurrently next since it just keeps terminating parcel instead of waiting for the shutdown....
