### ISSUE TITLE
Vue 3 defineProps fail with imported types

### ISSUE THREAD

**Issue by Demivan** [parcel-bundler/parcel#9565]
# 🐛 bug report

When using Vue `defineProps<Type>()` compilation fails when type is imported from a separate file.

```vue
<script setup lang="ts">
import type { ExternalProps } from './types';

defineProps<ExternalProps>();
</script>
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Default config

```json
{
  "scripts": {
    "build": "parcel build index.html"
  },
  "devDependencies": {
    "@parcel/transformer-vue": "2.12.0",
    "parcel": "^2.12.0"
  },
  "dependencies": {
    "vue": "^3.4.21"
  }
}

```

## 🤔 Expected Behavior

Using imported types for `defineProps` (and other Vue macros) should work.

## 😯 Current Behavior

```
  Error: [@vue/compiler-sfc] No fs option provided to `compileScript` in non-Node environment. File system access is required for resolving imported types.
  
  /parcel-vue/src/App.vue
  2  |  import type { ExternalProps } from './types';
  3  |  
  4  |  defineProps<ExternalProps>();
     |              ^^^^^^^^^^^^^
  5  |  </script>
  6  |  
      at ScriptCompileContext.error (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:15575:11)
      at importSourceToScope (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18385:16)
      at resolveTypeFromImport (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18374:23)
      at innerResolveTypeReference (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18261:14)
      at resolveTypeReference (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18249:20)
      at innerResolveTypeElements (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:17854:24)
      at resolveTypeElements (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:17799:20)
      at resolveRuntimePropsFromType (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:19324:20)
      at extractRuntimeProps (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:19300:17)
      at genRuntimeProps (/parcel-vue/node_modules/.pnpm/@vue+compiler-sfc@3.4.21/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:19288:18)
```

## 💁 Possible Solution

Pass `fs` configuration to `compileScript`.

## 💻 Code Sample

https://github.com/Demivan/parcel-vue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.12.0
| Node             | 21.6.2
| pnpm             | 8.12.1
| Operating System | Linux (NixOS)

**Comment by danwomersley** [comment]
I've had the same issue. Did you find a solution?

**Comment by Kagenoki** [comment]
I have the same problem. Is there no way to fix this?

**Comment by Demivan** [comment]
Can only be fixed by patching parcel. I have just gave up on parcel, as they ignored my other Vue issue with a PR to fix it.

**Comment by crystalfp** [comment]
This starts happening after upgrading typescript to 7.0.2 from 6.0.3

**Comment by TechQuery** [comment]
> Can only be fixed by patching parcel.

You can patch Parcel like this: https://github.com/idea2app/Vue-MobX-Shadcn-ts/pull/15
