### ISSUE TITLE
`@parcel/packager-js: Got unexpected null` with CSS module composes

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#9635]
# 🐛 bug report

A CSS module file useing composes fails with this error:

```
@parcel/packager-js: Got unexpected null

  Error: Got unexpected null
      at nullthrows (node_modules/nullthrows/nullthrows.js:7:15)
      at node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:918:51
      at Array.every (<anonymous>)
      at node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:917:35
      at Array.filter (<anonymous>)
      at ScopeHoistingPackager.buildAssetPrelude (node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:907:60)
      at ScopeHoistingPackager.buildAsset (node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:393:48)
      at ScopeHoistingPackager.visitAsset (node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:348:17)
      at node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:448:58
      at String.replace (<anonymous>)
```

## 🤔 Expected Behavior

Works

## 😯 Current Behavior

Fails with the error

## 🔦 Context

Originally reported by @arty-name in https://github.com/parcel-bundler/parcel/issues/8375#issuecomment-2047365356

## 💻 Code Sample

Minimal reproduction: https://github.com/mischnic/parcel-issue-9634

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | e60cbeb87f96c7d48b1891d20f27e3bb004e6c63
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by arty-name** [comment]
No new version has been released since the last version 2.12.0 had this issue, so the issue still persists. Looking forward to the big release!

**Comment by arty-name** [comment]
The issue still persists with parcel@2.14.4 in the minimal reproduction case

**Comment by arty-name** [comment]
The issue still exists with parcel@2.16.0

**Comment by arty-name** [comment]
The issue still exists with parcel@2.16.4
