### ISSUE TITLE
Error when using Parcel v2 with Bun without an installed Node.js

### ISSUE THREAD

**Issue by koddr** [parcel-bundler/parcel#9707]
# 🐛 bug report

I get error when using Parcel v2 in my project, when I use [Bun](https://bun.sh) **without** an installed Node.js.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "project",
  "version": "0.0.0",
  "license": "MIT",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "source": [
    "./assets/scripts.js",
    "./assets/styles.scss"
  ],
  "targets": {
    "default": {
      "distDir": "./static"
    }
  },
  "scripts": {
    "watch": "parcel watch",
    "fmt": "prettier --write .",
    "dev": "parcel build --no-optimize",
    "build": "parcel build"
  },
  "dependencies": {
    "htmx.org": "latest"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "latest",
    "parcel": "latest",
    "prettier": "latest"
  }
}
```

## 🤔 Expected Behavior

Add support Bun without Node.js.

## 😯 Current Behavior

```console
$ bun run build

3619 |                     (0, ($parcel$interopDefault($aniHR$module)))._extensions[".js"](m, filename);
3620 |                 };
3621 |             }
3622 |         }
3623 |         try {
3624 |             m.load(filePath);
                   ^
TypeError: m.load is not a function. (In 'm.load(filePath)', 'm.load' is undefined)
      at load (/Users/user/project/node_modules/@parcel/package-manager/lib/index.js:3624:13)

3619 |                     (0, ($parcel$interopDefault($aniHR$module)))._extensions[".js"](m, filename);
3620 |                 };
3621 |             }
3622 |         }
3623 |         try {
3624 |             m.load(filePath);
                   ^
TypeError: m.load is not a function. (In 'm.load(filePath)', 'm.load' is undefined)
      at load (/Users/user/project/node_modules/@parcel/package-manager/lib/index.js:3624:13)

3619 |                     (0, ($parcel$interopDefault($aniHR$module)))._extensions[".js"](m, filename);
3620 |                 };
3621 |             }
3622 |         }
3623 |         try {
3624 |             m.load(filePath);
                   ^
TypeError: m.load is not a function. (In 'm.load(filePath)', 'm.load' is undefined)
      at load (/Users/user/project/node_modules/@parcel/package-manager/lib/index.js:3624:13)

3619 |                     (0, ($parcel$interopDefault($aniHR$module)))._extensions[".js"](m, filename);
3620 |                 };
3621 |             }
3622 |         }
3623 |         try {
3624 |             m.load(filePath);
                   ^
TypeError: m.load is not a function. (In 'm.load(filePath)', 'm.load' is undefined)
      at load (/Users/user/project/node_modules/@parcel/package-manager/lib/index.js:3624:13)

10 |   }
11 | }
12 |
13 | let binding;
14 | try {
15 |   binding = require(name);
     ^
TypeError: symbol 'napi\_register\_module\_v1' not found in native module. Is this a Node API (napi) module?
      at dlopen (native:1:1)
      at /Users/user/project/node_modules/@parcel/watcher/index.js:15:2
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/fs/lib/index.js:21:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/package-manager/lib/index.js:35:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/core/lib/worker.js:102:1
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/workers/lib/child.js:111:19
10 |   }
11 | }
12 |
13 | let binding;
14 | try {
15 |   binding = require(name);
     ^
TypeError: symbol 'napi\_register\_module\_v1' not found in native module. Is this a Node API (napi) module?
      at dlopen (native:1:1)
      at /Users/user/project/node_modules/@parcel/watcher/index.js:15:2
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/fs/lib/index.js:21:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/package-manager/lib/index.js:35:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/core/lib/worker.js:102:1
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/workers/lib/child.js:111:19
10 |   }
11 | }
12 |
13 | let binding;
14 | try {
15 |   binding = require(name);
     ^
TypeError: symbol 'napi\_register\_module\_v1' not found in native module. Is this a Node API (napi) module?
      at dlopen (native:1:1)
      at /Users/user/project/node_modules/@parcel/watcher/index.js:15:2
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/fs/lib/index.js:21:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/package-manager/lib/index.js:35:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/core/lib/worker.js:102:1
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/workers/lib/child.js:111:19
10 |   }
11 | }
12 |
13 | let binding;
14 | try {
15 |   binding = require(name);
     ^
TypeError: symbol 'napi\_register\_module\_v1' not found in native module. Is this a Node API (napi) module?
      at dlopen (native:1:1)
      at /Users/user/project/node_modules/@parcel/watcher/index.js:15:2
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/fs/lib/index.js:21:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/package-manager/lib/index.js:35:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/core/lib/worker.js:102:1
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/workers/lib/child.js:111:19

Bun v1.1.7 (macOS arm64)
error: script "build" exited with code 1
```

## 💁 Possible Solution

Add types to resolve `TypeError: symbol 'napi\_register\_module\_v1' not found in native module. Is this a Node API (napi) module?` or something like this.

## 🌍 Your Environment

```console
$ node -v
zsh: command not found: node

$ npm -v
zsh: command not found: npm
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.12.0 |
| ~~Node~~ Bun             | v1.1.7 |
| ~~npm/Yarn~~ Bun         | v1.1.7 |
| Operating System | macOS 14.4.1 (23E224) |

**Comment by mischnic** [comment]
We don't really support using Bun instead of Node.
This is rather that Bun doesn't have full compatibility with Node.js (yet), maybe you should report this to Bun.
