### ISSUE TITLE
Installing via `yarn` fails with `Error: @swc/types@workspace:^: Workspace not found (@swc/types@workspace:^)`

### ISSUE THREAD

**Issue by puresick** [parcel-bundler/parcel#9746]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

No special configuration in place.
It might be worth mentioning that I manage NodeJS via `fnm` (https://github.com/Schniz/fnm).

## 🤔 Expected Behavior

Parcel should be installed successfully.

## 😯 Current Behavior

On a fresh repository, I do the following:
1. `corepack enable`
2. `yarn init -2`
3. `yarn add --dev parcel`

This results in the following error during the installation process:
```
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @swc/types@workspace:^: Workspace not found (@swc/types@workspace:^)
    at St.getWorkspaceByDescriptor (/home/puresick/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:210:3520)
    at l1.getCandidates (/home/puresick/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:140:115276)
    at Pd.getCandidates (/home/puresick/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:141:1311)
    at Pd.getCandidates (/home/puresick/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:141:1311)
    at /home/puresick/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:210:8409
    at Ky (/home/puresick/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:140:53916)
    at Fe (/home/puresick/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:210:8389)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 11)
    at async _c (/home/puresick/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:140:53244)
➤ YN0000: └ Completed in 1s 353ms
➤ YN0000: · Failed with errors in 1s 364ms
```

## 🔦 Context

I want to setup a fresh project with parcel using yarn as package manager.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.12.0
| Node             | v22.2.0
| npm/Yarn         | 4.2.2
| Operating System | Arch Linux

**Comment by mischnic** [comment]
See https://github.com/swc-project/swc/issues/8988

You might need `"resolutions": {"@swc/core":"1.5.7"}`

**Comment by puresick** [comment]
Thanks for the info @mischnic!
Adding the proper `@swc/core` version to `package.json` solved it.
